### ISSUE TITLE
How to debug ingress

### ISSUE THREAD

**Issue by jwalton** [rancher/k3s#1001]
**Version:** k3s version v0.9.1 (755bd1c6)

**Describe the bug**

I've been banging my head against a wall for the last hour trying to get the K3s ingress to give me back anything other than "404 not found".

**To Reproduce**

I brought up a new AWS instance in ca-central-1 and used k3sup to install k3s:

```
$ curl -sLS https://get.k3sup.dev | sh

$ k3sup install --ip aaa.bbb.ccc.ddd --user ubuntu \
          --local-path ca-central.kubeconfig \
          --context ca-central
```

I then tried to bring up the 2048 game and associated ingress (See [my config here](https://gist.github.com/jwalton/463b4dead5b1b5e8172b6660d8272659)).

I added `my.domain.ca` to /etc/hosts:

```
127.0.0.1 my.domain.ca
```

This is about as simple an example as I can come up with.

**Expected behavior**

On the k3s machine, I expect `curl my.domain.ca:80/` to return something.

**Actual behavior**

`curl my.domain.ca:80/` gives me back "404 not found".  I've tried it with and without the "ingress.class" annotation, I've tried with and without an explicit "host: my.domain.ca" in the `rules`.  I even tried `curl -k https://mydomain.ca`.  Everything gives me back "404 not found".

The service is definitely up:

```
$ kubectl get services
NAME           TYPE       CLUSTER-IP    EXTERNAL-IP   PORT(S)        AGE
service-2048   NodePort   10.43.83.70   <none>        80:31648/TCP   3m55s

$ curl localhost:31648
<!DOCTYPE html>
<html>
...
```

I see traefik is listening on 8080, so I tried to visit localhost:8080/dashboard/, but this gives me "404 not found".

I tried `sudo kubectl --namespace kube-system logs traefik-d869575c8-x6qps`, which mostly gives me a bunch of "Service configuration reloaded..." log lines.  I do see a few:

```
{"level":"warning","msg":"Endpoints not available for blazeloopca/service-2048","time":"2019-11-01T19:49:37Z"}
{"level":"warning","msg":"Endpoints not available for blazeloopca/service-2048","time":"2019-11-01T19:49:39Z"}
{"level":"warning","msg":"Endpoints not available for blazeloopca/service-2048","time":"2019-11-01T19:49:41Z"}
```

but these are all from around when I started the service, and they're not happening anymore.  At least I know I'm having some effect on traefik.

I tried `sudo kubectl --namespace kube-system logs svclb-traefik-69brr lb-port-80`, but this gives me some iptables commands and that's it.

So... What am I doing wrong, and/or how do I debug this?

**Comment by curx** [comment]
The problem seem in your ingress rule, so please check the path of your ruleset:

```yaml=
...
spec:
  rules:
    - host: my.domain.ca
      http:
        paths:
          - path: /* # ->  e.g. change to - path: /
            backend:
              serviceName: "service-2048"
              servicePort: 80
...
```
and check it like: 
`$ curl --resolve my.domain.ca:80:<ipaddr-of-your-k3s-node> 'http://my.domain.ca'`

**Comment by jwalton** [comment]
@curx Thanks so much!  All the work I've done so far has been using an AWS ingress with an ALB, where the "/*" is required.  If you just use "/" you end up with an ALB with a rule that says `If path is "/"`, which will literally only match requests where the path is "/".  :P

I never would have figured that out.
