### ISSUE TITLE
Update docs to reflect that k3s doesnt remove alpha features

### ISSUE THREAD

**Issue by cjellick** [rancher/k3s#1017]
This line is wrong:
> Legacy, alpha, non-default features are removed. Hopefully, you shouldn’t notice the stuff that has been removed.

we added those things back in recently

**Comment by cjellick** [comment]
This section could also possibly mention the things weve added, ie local storage provider, service load balancer, helm-controller, traefik ingress controller

Also, the bullet points do not follow sentence structure or tense. Like:
"Legacy...has been removed" <- verb at the end
"Removed most..." <- verb at the beginnning
"Add sqlite3.." <- not past tense

**Comment by CamelCaseNotation** [comment]
Glad y'all _did_ add them back cuz I really wanted to use PodPreset :)
