### ISSUE TITLE
how does K3S support the watch mechanism under K8S after using Sqlite3?

### ISSUE THREAD

**Issue by jamesxia20181001** [rancher/k3s#102]
Does Sqlite3 support a watch mechanism similar to etcd? If Sqlite3 does not support the watch mechanism itself, how does K3S support the watch mechanism under K8S after using Sqlite3? Thank you!

**Comment by ibuildthecloud** [comment]
sqlite3 is fully in memory so it quite simple to know when something has changed.  So we just monitor all mutations and fire events.  Additionally the way the data is stored in sqlite is effectively a log which is how we can replay history.  Full code here.  It's really quite simple https://github.com/ibuildthecloud/kvsql/tree/master/clientv3/driver

**Comment by jamesxia20181001** [comment]
Since sqlite3 does not support HA, etcd needs 3 nodes. Can you replace etcd or sqlite3 with postgresql, provide master/slave HA with 2 nodes, and implement the watch mechanism? Thank you!

**Comment by xiaosuiba** [comment]
There's a  distributed relational database built on SQLite - [rqlite](https://github.com/rqlite/rqlite).

**Comment by jamesxia20181001** [comment]
Rqlite uses Raft to achieve consensus across all the instances of the SQLite databases. This means that at least 3 nodes are needed, and HA is not available at 2 nodes.

**Comment by ibuildthecloud** [comment]
@jamesxia20181001 We will eventually support postgresql and/or mysql for a datastore.  Right now we do not because there are other issues with HA that prevent it from fully working properly.

**Comment by hunknownz** [comment]
It's [kine](https://github.com/k3s-io/kine).
