### ISSUE TITLE
Why in k3s-1.15.3 that kvsql is disappear?

### ISSUE THREAD

**Issue by andyzheung** [rancher/k3s#1023]
while the 1.14.6 is still here, but I can't find in 1.15.3:？
![image](https://user-images.githubusercontent.com/22912347/68384716-3046fb80-0193-11ea-9261-d9ede8b8991b.png)

![image](https://user-images.githubusercontent.com/22912347/68385939-e875a380-0195-11ea-96bd-675b5a649d20.png)

**Comment by erikwilson** [comment]
kvsql is now kine

**Comment by andyzheung** [comment]
> kvsql is now kine
what do you mean?
@erikwilson

**Comment by warmchang** [comment]
Here it is: https://github.com/rancher/k3s/tree/master/vendor/github.com/rancher/kine/pkg/drivers

The kine contains multiple drivers for external DBs (Such as mysql, pg and sqlite and so on).

**Comment by andyzheung** [comment]
> Here it is: [vendor/github.com/rancher/kine/pkg/drivers](https://github.com/rancher/k3s/tree/6290029e6dbd84c4e6a9525040e092516e100151/vendor/github.com/rancher/kine/pkg/drivers)
> 
> The kine contains multiple drivers for external DBs (Such as mysql, pg and sqlite and so on).

Thank you,  but why I download the tag verison, I can't see this? For example:

![image](https://user-images.githubusercontent.com/22912347/68450704-e4de2d00-0226-11ea-8136-81ad1f980df0.png)

**Comment by warmchang** [comment]
Switch to the k3s tag, for example v0.10.2:
https://github.com/rancher/k3s/tree/v0.10.2/vendor/github.com/rancher/kine/pkg/drivers

or just check the [master ](https://github.com/rancher/k3s/tree/master/vendor/github.com/rancher/kine/pkg)branch.

BTW:
Following k/k's version of the tag has been deprecated, and the k3s has been changed to use Go Modules to build. 
The k/k source code maintenance in [separate  repo](https://github.com/rancher/kubernetes/tree/v1.16.2-k3s.1), and use [go.mod](https://github.com/rancher/k3s/blob/5d342a3051d0c68c0ccb834652745371dbb2359b/go.mod#L53) file to control & sync to vender fouder (by `go mod vendor`).

**Comment by andyzheung** [comment]
Thank you so much!
@warmchang

**Comment by warmchang** [comment]
Welcome!
/close
