### ISSUE TITLE
metrics-server missing endpoints

### ISSUE THREAD

**Issue by jandriotty** [rancher/k3s#1025]
I am on a raspberry pi 3 B+ using v0.9.1 because when I tried v0.10.2, k3s installation still exits with an error code. I am trying to install the metrics-server. I cloned github.com/rancher/metrics-server and deployed the 1.8+ version, but when i do kubectl get apiservices, under available, it says "False (missing endpoints)" and the pod is on CrashLoopBackOff. 

I see that in the latest release metrics-server is included by default and a metrics-server directory is added in manifests. That would be helpful to me now, but i am unable to use the latest version. Any ideas on how to troubleshoot/how to make adjustments to metrics-server that could help?

I saw that someone said rancher/metrics-server:v0.3.6 is available and compatible with arm, but i can't seem to find it on the repo, so i am on v0.3.5 based on the image k8s.gcr.io/metrics-server-amd64:v0.3.5.

Thanks

**Comment by davidnuzik** [comment]
May we ask why you are not able to use the latest? It also has other fixes for armhf (pis) and is suggested. We will be releasing v1.0 soon in less than a week.

**Comment by jandriotty** [comment]
here is part of the output of journalctl -xe. the same thing happened with 0.10.0 and 0.10.1

`A start job for unit k3s.service has begun execution.
-- 
-- The job identifier is 2197.
Nov 06 21:28:33 under2 k3s[1667]: time="2019-11-06T21:28:33.622572826-05:00" level=info msg="Starting k3s v0.10.2 (8833bfd9)"
Nov 06 21:28:33 under2 k3s[1667]: time="2019-11-06T21:28:33.633636368-05:00" level=info msg="Kine listening on unix://kine.sock"
Nov 06 21:28:33 under2 k3s[1667]: time="2019-11-06T21:28:33.636280795-05:00" level=info msg="Fetching bootstrap data from etcd"
Nov 06 21:28:33 under2 k3s[1667]: time="2019-11-06T21:28:33.659381837-05:00" level=info msg="Running kube-apiserver --advertise-port=6443 --allow-privileged=
Nov 06 21:28:33 under2 k3s[1667]: Flag --basic-auth-file has been deprecated, Basic authentication mode is deprecated and will be removed in a future release
Nov 06 21:28:33 under2 k3s[1667]: I1106 21:28:33.661652    1667 server.go:650] external host was not specified, using 192.124.1.192
Nov 06 21:28:33 under2 k3s[1667]: I1106 21:28:33.663432    1667 server.go:162] Version: v1.16.2-k3s.1
Nov 06 21:28:33 under2 k3s[1667]: I1106 21:28:33.699299    1667 plugins.go:158] Loaded 11 mutating admission controller(s) successfully in the following orde
Nov 06 21:28:33 under2 k3s[1667]: I1106 21:28:33.699537    1667 plugins.go:161] Loaded 7 validating admission controller(s) successfully in the following ord
Nov 06 21:28:33 under2 k3s[1667]: I1106 21:28:33.705152    1667 plugins.go:158] Loaded 11 mutating admission controller(s) successfully in the following orde
Nov 06 21:28:33 under2 k3s[1667]: I1106 21:28:33.705273    1667 plugins.go:161] Loaded 7 validating admission controller(s) successfully in the following ord
Nov 06 21:28:33 under2 k3s[1667]: I1106 21:28:33.839664    1667 master.go:259] Using reconciler: lease
Nov 06 21:28:33 under2 k3s[1667]: I1106 21:28:33.967723    1667 rest.go:115] the default service ipfamily for this cluster is: IPv4
Nov 06 21:28:35 under2 k3s[1667]: W1106 21:28:35.625867    1667 genericapiserver.go:404] Skipping API batch/v2alpha1 because it has no resources.
Nov 06 21:28:35 under2 k3s[1667]: W1106 21:28:35.751014    1667 genericapiserver.go:404] Skipping API node.k8s.io/v1alpha1 because it has no resources.
Nov 06 21:28:35 under2 k3s[1667]: W1106 21:28:35.877572    1667 genericapiserver.go:404] Skipping API rbac.authorization.k8s.io/v1alpha1 because it has no re
Nov 06 21:28:35 under2 k3s[1667]: W1106 21:28:35.901123    1667 genericapiserver.go:404] Skipping API scheduling.k8s.io/v1alpha1 because it has no resources.
Nov 06 21:28:35 under2 k3s[1667]: W1106 21:28:35.980025    1667 genericapiserver.go:404] Skipping API storage.k8s.io/v1alpha1 because it has no resources.
Nov 06 21:28:36 under2 k3s[1667]: W1106 21:28:36.111472    1667 genericapiserver.go:404] Skipping API apps/v1beta2 because it has no resources.
Nov 06 21:28:36 under2 k3s[1667]: W1106 21:28:36.111584    1667 genericapiserver.go:404] Skipping API apps/v1beta1 because it has no resources.
Nov 06 21:28:36 under2 k3s[1667]: I1106 21:28:36.226640    1667 plugins.go:158] Loaded 11 mutating admission controller(s) successfully in the following orde
Nov 06 21:28:36 under2 k3s[1667]: I1106 21:28:36.226765    1667 plugins.go:161] Loaded 7 validating admission controller(s) successfully in the following ord
Nov 06 21:28:36 under2 k3s[1667]: time="2019-11-06T21:28:36.292521211-05:00" level=info msg="Running kube-scheduler --bind-address=127.0.0.1 --kubeconfig=/va
Nov 06 21:28:36 under2 k3s[1667]: time="2019-11-06T21:28:36.306747669-05:00" level=info msg="Running kube-controller-manager --allocate-node-cidrs=true --bin
Nov 06 21:28:36 under2 k3s[1667]: I1106 21:28:36.336465    1667 controllermanager.go:161] Version: v1.16.2-k3s.1
Nov 06 21:28:36 under2 k3s[1667]: I1106 21:28:36.339405    1667 deprecated_insecure_serving.go:53] Serving insecurely on [::]:10252
Nov 06 21:28:36 under2 k3s[1667]: I1106 21:28:36.339994    1667 server.go:143] Version: v1.16.2-k3s.1
Nov 06 21:28:36 under2 k3s[1667]: I1106 21:28:36.340432    1667 defaults.go:91] TaintNodesByCondition is enabled, PodToleratesNodeTaints predicate is mandato
Nov 06 21:28:36 under2 k3s[1667]: W1106 21:28:36.346640    1667 authorization.go:47] Authorization is disabled
Nov 06 21:28:36 under2 k3s[1667]: W1106 21:28:36.346724    1667 authentication.go:79] Authentication is disabled
Nov 06 21:28:36 under2 k3s[1667]: I1106 21:28:36.346787    1667 deprecated_insecure_serving.go:51] Serving healthz insecurely on [::]:10251
Nov 06 21:28:46 under2 k3s[1667]: time="2019-11-06T21:28:46.322559800-05:00" level=fatal msg="starting tls server: Get https://127.0.0.1:6444/apis/apiextensi
Nov 06 21:28:46 under2 systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
`

**Comment by jandriotty** [comment]
So i was able to install v0.11.0-alpha4 successfully, and the metrics-server is here but still has the missing endpoints problem.

**Comment by erikwilson** [comment]
It sounds like you tried to install an amd64 version of metrics server on the rpi3, which is arm.

I think the pod is in a backoff state from the previous errors and might resolve itself eventually, but the easiest thing to do would be to completely uninstall k3s and install the newest rc.

**Comment by jandriotty** [comment]
it seems like the metrics-server is working now, thanks!
