### ISSUE TITLE
EXTERNAL-IP not working

### ISSUE THREAD

**Issue by kaihendry** [rancher/k3s#1030]
**Version:**
    k3s version v0.9.1 (755bd1c6)

**Describe the bug**
LoadBalancer external IP isn't addressable outside of the host

Locally it's fine

```
pi@four:~$ kubectl get services
NAME         TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
kubernetes   ClusterIP      10.43.0.1      <none>        443/TCP          19d
sla          LoadBalancer   10.43.182.50   192.168.1.4   9000:30470/TCP   10d
pi@four:~$ curl http://192.168.1.4:9000
Slept: 0 ms
```

**To Reproduce**
http://s.natalian.org/2019-11-08/deploy.yaml

Now curl that URL on a different host in the network.

**Expected behavior**
`curl http://192.168.1.4:9000` to work from my other machine `192.168.1.2` on ny network. But it doesn't.

**Actual behavior**
curl times out

```
freenas% ifconfig  | grep 192
        inet 192.168.1.2 netmask 0xffffff00 broadcast 192.168.1.255
freenas% curl http://192.168.1.4:9000
curl: (7) Failed to connect to 192.168.1.4 port 9000: Operation timed out
```

**Comment by alexellis** [comment]
If you want to access your service, you could try port-forward or https://inlets.dev/ (to forward from the K8s network, to your freenas - running an exit server there)

```sh
kubectl port-forward svc/sla 9000:9000 &
```

What OS are you running on and what type of device?

```
uname -a
cat /etc/os-release
```

There are a few people encountering issues with k3s and iptables on RPi, due to the "wrong" version being installed on the latest Raspbian release. @ibuildthecloud may know more

**Comment by alexellis** [comment]
What's the health of your deployment and pod that go with the service? `kubectl get pod -o wide`

**Comment by kaihendry** [comment]
```pi@four:~$ kubectl get pod -o wide
NAME                   READY   STATUS    RESTARTS   AGE     IP           NODE   NOMINATED NODE   READINESS GATES
sla-74cbc54b85-6g4x8   1/1     Running   0          4h45m   10.42.0.43   four   <none>           <none>
svclb-sla-sb9wq        1/1     Running   0          4h42m   10.42.0.44   four   <none>           <none>
pi@four:~$ kubectl get services
NAME         TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
kubernetes   ClusterIP      10.43.0.1      <none>        443/TCP          19d
sla          LoadBalancer   10.43.182.50   192.168.1.4   9000:30470/TCP   10d
pi@four:~$ curl 192.168.1.4:9000
Slept: 0 ms
pi@four:~$ logout
Connection to 192.168.1.4 closed.
[hendry@t480s ~]$ curl 192.168.1.4:9000
```

**Comment by alexellis** [comment]
Did the port forward work?

**Comment by kaihendry** [comment]
I don't want to port forward, I want to host my service from the Rpi somehow.

Freenas doesn't have `kubectl`

**Comment by alexellis** [comment]
Please could you help me out as I tried to help you debug what is going wrong. I'm not suggesting this solves your problem, it does help me diagnose the issue.

**Comment by alexellis** [comment]
Please could you give the output of the os and device?

**Comment by kaihendry** [comment]
Rebooted and the problem went away. Scary.

https://serverfault.com/questions/991247/ports-became-filtered-but-why

**Comment by niftydevelopment** [comment]
> iptables -P FORWARD ACCEPT
