### ISSUE TITLE
Set proper ROLE value for worker nodes in k3s

### ISSUE THREAD

**Issue by izaac** [rancher/k3s#1032]
**Version:**
k3s version v0.10.2 (8833bfd9)

**Describe the bug**
After installing a master and two worker nodes I do a `kubectl get nodes` And these nodes show `<none>` as their ROLE.

**To Reproduce**
Install k3s one master and a worker, after that do a `kubectl get nodes`

**Expected behavior**
Could be a good improvement to add this ROLE value to the k3s worker nodes. Like RKE cluster does:

```bash
NAME                   STATUS   ROLES          AGE   VERSION
izaac-do-test-cp-1     Ready    controlplane   80m   v1.16.2
izaac-do-test-etcd-1   Ready    etcd           80m   v1.16.2
izaac-do-test-wrkr-1   Ready    worker         79m   v1.16.2
izaac-do-test-wrkr-2   Ready    worker         78m   v1.16.2
izaac-do-test-wrkr-3   Ready    worker         79m   v1.16.2
```

**Actual behavior**
`<none>` is displayed as the worker ROLE value.
```
NAME                 STATUS   ROLES    AGE   VERSION
izaac-k3s-worker-2   Ready    <none>   26h   v1.16.2-k3s.1
izaac-k3s-worker-1   Ready    <none>   26h   v1.16.2-k3s.1
izaac-k3s-master     Ready    master   27h   v1.16.2-k3s.1
```

**Additional context**

**Comment by erikwilson** [comment]
Is it causing an issue?

dupe #878

**Comment by izaac** [comment]
@erikwilson not an issue but it would be a good enhancement. Not critical.

**Comment by erikwilson** [comment]
As the linked issue states, not having a role is the default in kubernetes.

**Comment by izaac** [comment]
I wasn't aware of the dupe, I skim through and seems there was already an agreement on this. Closing. Thanks @erikwilson
