### ISSUE TITLE
coreDNS and traefik keep on crashing

### ISSUE THREAD

**Issue by jait** [rancher/k3s#104]
Hi,

And thanks for a great project! 

I installed k3s from get.k3s.io on Raspbian Stretch Lite, running on RPi 3 B+. I was able to create a custom deployment but it seems that coreDNS and traefik keep on crashing and restarting:
```
pi@k3s-server:~ $ kubectl --namespace=kube-system get pods
NAME                                    READY   STATUS             RESTARTS   AGE
coredns-7748f7f6df-n985z                0/1     CrashLoopBackOff   335        23h
helm-install-traefik-49t7s              0/1     CrashLoopBackOff   262        23h
```

The pod logs have errors about apiserver certs:
```
E0301 10:51:21.962243       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:322: Failed to list *v1.Namespace: Get https://10.43.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: x509: certificate signed by unknown authority
E0301 10:51:21.965162       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:315: Failed to list *v1.Service: Get https://10.43.0.1:443/api/v1/services?limit=500&resourceVersion=0: x509: certificate signed by unknown authority
E0301 10:51:23.074862       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:317: Failed to list *v1.Endpoints: Get https://10.43.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: x509: certificate signed by unknown authority
E0301 10:51:23.077681       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:315: Failed to list *v1.Service: Get https://10.43.0.1:443/api/v1/services?limit=500&resourceVersion=0: x509: certificate signed by unknown authority
E0301 10:51:23.078258       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:322: Failed to list *v1.Namespace: Get https://10.43.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: x509: certificate signed by unknown authority
[INFO] SIGTERM: Shutting down servers then terminating
```

```
+ helm install --name traefik stable/traefik --set-string rbac.enabled=true --set-string ssl.enabled=true
[tiller] 2019/03/01 10:52:05 preparing install for traefik
[storage] 2019/03/01 10:52:05 getting release history for "traefik"
[storage/driver] 2019/03/01 10:52:05 query: failed to query with labels: Get https://10.43.0.1:443/api/v1/namespaces/kube-system/secrets?labelSelector=NAME%3Dtraefik%2COWNER%3DTILLER: x509: certificate signed by unknown authority
[tiller] 2019/03/01 10:52:05 failed install prepare step: Get https://10.43.0.1:443/version?timeout=32s: x509: certificate signed by unknown authority
Error: Get https://10.43.0.1:443/version?timeout=32s: x509: certificate signed by unknown authority
```

What could be wrong here?

**Comment by ibuildthecloud** [comment]
@jait can you check the Node IP is correct `kubectl get node -o yaml` and look for InternalIP.

10.43.0.1:443 should through iptables be routed to 127.0.0.1:6444 (not 6443) which should be using the TLS cert `/var/lib/rancher/server/token-node.crt` which should be signed by `/var/lib/rancher/k3s/agent/client-ca.pem`

The only reasonable thing I can think is going wrong is the either you have some bad state from maybe a failed installation so the certs don't match or there is something else running on your host that is occupying a port that is messing something up.  I would just try running the k3s-uninstall.sh script to clean things up and try running the get.k3s.io script again.  Sorry :/

**Comment by jose-sanchezm** [comment]
Hello, I'm having the same problem here. When I look at the InternalIP for both my master and slave it's set to each node's public IP. Is it supposed to work like this?

**Comment by jait** [comment]
I was able to resolve the problem by uninstalling, rebooting and reinstalling. So most likely it was some bad state from an earlier failed installation. I decided to reboot because it looks like the uninstall script did not remove all the network interfaces.

**Comment by jait** [comment]
Closing as this was a bad installation
