### ISSUE TITLE
Log rotation for containers

### ISSUE THREAD

**Issue by wc-matteo** [rancher/k3s#1047]
How is log rotation handled for containers? Can you configure logs max size like you can with docker?

**Comment by galal-hussein** [comment]
@wc-matteo Kubelet is supposed to handle log rotation on its own, the default max size for logs is 10Mi:
```

--container-log-max-size string
--
  | Set the maximum size (e.g. 10Mi) of container log file before it is rotated. This flag can only be used with --container-runtime=remote. (default "10Mi") (DEPRECATED: This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.)


```

**Comment by davidnuzik** [comment]
Let us know if there are any further questions around this. Can re-open the issue if needed.

**Comment by wc-matteo** [comment]
Thanks.

But [here ](https://kubernetes.io/docs/concepts/cluster-administration/logging/)it seems to contradict that information:

> **Kubernetes currently is not responsible for rotating logs**, but rather a deployment tool should set up a solution to address that. For example, in Kubernetes clusters, deployed by the kube-up.sh script, there is a logrotate tool configured to run each hour. You can also set up a container runtime to rotate application’s logs automatically, e.g. by using Docker’s log-opt.

**Comment by erikwilson** [comment]
Is it possible that syslogd has automatically rotated the logs?

**Comment by wc-matteo** [comment]
my worry is that the logs are gonna consume all the space on the disk. Is there no definitive answer on this?

**Comment by erikwilson** [comment]
Please see your system cron and logrotate configuration. You can also check the contents of `/var/log`, `/var/log/pods`, and the output of `df -h /var/log/` for disk usage. Some systems will automatically rotate, compress, and remove old logs, whiles others may not.

**Comment by wc-matteo** [comment]
Ah, okay. I'll check then. Thanks. I'm using k3OS, by the way.On Nov 28, 2019 18:34, Erik Wilson <notifications@github.com> wrote:Please see your system cron and logrotate configuration. You can also check the contents of /var/log, /var/log/pods, and the output of df -h /var/log/ for disk usage. Some systems will automatically rotate, compress, and remove old logs, whiles others may not.

**Comment by wc-matteo** [comment]
I hope you don't mind If I ask here even though it's about `k3OS`. But...

`k3OS` does have `logrotate` but it's not configured to handle pods' logs. So without manual intervention, those logs are gonna pile up forever, right?

***

crontab it's not configured at all:
```
crontab: can't change directory to '/var/spool/cron/crontabs': No such file or directory
```

I've read that `logrotate` uses `cron` to run automatically. So by default, `logrotate` doesn't run at all on `k3OS`?

**Comment by prashilgupta** [comment]
Is there any update on this feature request?

**Comment by brandond** [comment]
The text on that page isn't entirely accurate. The kubelet does have log rotation configuration:
https://github.com/kubernetes/kubernetes/pull/59898
https://github.com/containerd/containerd/issues/3351#issuecomment-635925513
