### ISSUE TITLE
After first start without `--no-deploy=local-storage` flag, subsequent starts with the flag still deploy local storage

### ISSUE THREAD

**Issue by sgielen** [rancher/k3s#1048]
**Version:**
`k3s version v0.11.0-alpha2 (405f85aa)`
`root      1917  118  5.3 355120 203940 ?       Ssl  09:24   0:07 /sbin/k3s server --no-deploy=servicelb --no-deploy=local-storage`

**Describe the bug**
After adding `--no-deploy=local-storage`, I expect no local-path provisioner to be running, but it is and the service class is registered.

**To Reproduce**
- Have an existing installation of k3s with local-storage.
- Provide my own storage class and delete the `local-path` storage class.
- Add `--no-deploy=local-storage` to the flags of k3s and restart.

(See https://github.com/rancher/k3s/issues/1048#issuecomment-553864526 for more information and screenshots.)

**Expected behavior**
- No `local-path` service class is created and no `local-path-provisioner` is running as they are disabled.

**Actual behavior**
- The `local-path` service class is recreated and the `local-path-provisioner` is running.

```
$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                      READY   STATUS      RESTARTS   AGE
[...]
kube-system   local-path-provisioner-58fb86bdfd-487rl   1/1     Running     1          45h
default       nfs-client-provisioner-6b9fb56458-nmbvj   1/1     Running     1          22h
[...]
$ kubectl get sc
NAME                            PROVISIONER                   AGE
managed-nfs-storage (default)   k8s.sjor.sg/nfs-provisioner   22h
local-path (default)            rancher.io/local-path         3m13s
```

**Comment by sgielen** [comment]
I also added `--no-deploy=servicelb` which did cause the svclb **not** to be deployed after a reboot. Then, I added `--no-deploy=traefik` but traefik **is** actually deployed after this... Weird?

**Comment by davidnuzik** [comment]
What does the k3s service look like? How did you install k3s exactly?

**Comment by galal-hussein** [comment]
@sgielen I cant reproduce the issue, I started k3s with `--no-deploy local-storage` and I can see that neither the storage class nor the local path provisioner deployment got deployed

CC @davidnuzik

**Comment by galal-hussein** [comment]
@sgielen can you describe exactly how did you start k3s with the --no-deploy, if you started without --no-deloy and then tried to add it after it won't delete the deployment that already has been installed

**Comment by sgielen** [comment]
I have these steps to reproduce in the task description:
- Already have k3s running without any `--no-deploy` flags
- Delete the storage class
- Add the `--no-deploy=local-storage` flag and restart k3s
- The local storage provisioner is still started and the storage class recreated

@galal-hussein this sounds reasonable, that the deployment isn't automatically removed – but it did trigger me that when you add `--no-deploy=servicelb`, the svclb *is* automatically removed. Is there a difference between how local-storage and servicelb are deployed that would explain this difference? Perhaps this is something to make consistent, or else, something to document?

**Comment by sgielen** [comment]
I set up k3s in an x86_64 VM with default args (just `k3s server`) and svclb started:

![after setup](https://user-images.githubusercontent.com/328769/68856820-b3130d80-06e1-11ea-8ab1-7d4f6de1a53f.png)

Then, added `--no-deploy=servicelb` to `/k3os/system/config.yaml` and rebooted. Initially, svclb was running but then (without me doing anything) it was set to Terminating, then removed:

![after adding no-deploy](https://user-images.githubusercontent.com/328769/68856866-d342cc80-06e1-11ea-96e1-eedc6764b0b3.png)

**Comment by sgielen** [comment]
Worse, I removed the local path provisioner and the storage class and rebooted and they come back even though `--no-deploy=local-storage` is given:

![before](https://user-images.githubusercontent.com/328769/68857618-70eacb80-06e3-11ea-800b-8d825d6a631f.png)

![after](https://user-images.githubusercontent.com/328769/68857661-924bb780-06e3-11ea-8363-09bfd9b87539.png)

**Comment by sgielen** [comment]
Probably, it's related to `/var/lib/rancher/k3s/server/manifests/local-storage.yaml` which exists even after `--no-deploy` is added. (Related issue: #717) Indeed, after removing the deployment and storage class *and* removing the file *and* adding `--no-deploy=local-storage`, the local path provisioner is not recreated.

I would consider k3s' behaviour less surprising if it would not load the `local-storage.yaml` manifest (and perhaps even `kubectl delete` whatever it added before) if `--no-deploy=local-storage` is given?

**Comment by Ehco1996** [comment]
i found this too
i want a clean version that do NOT contain any pre install component such as traefik or local-path-storage

---
also  the cli args such as `--no-deploy traefik`  is so strange, as a user, i dont't need `no-deploy`
i need deploy-xxx cmd

**Comment by jonfairbanks** [comment]
> also the cli args such as `--no-deploy traefik` is so strange, as a user, i dont't need `no-deploy`
> i need deploy-xxx cmd

+1 to this request. Opt in would be preferred. I suppose that would make it let seamless for new users coming in though.

**Comment by casidiablo** [comment]
Yeah, seems like deleting `/var/lib/rancher/k3s/server/manifests/traefik.yaml` also fixes the problem from traefik

**Comment by casidiablo** [comment]
Actually, this is happening again even without `/manifests/` file in my server

**Comment by cjellick** [comment]
We introduced a --disable flag to accomplish what is being asked here.
