### ISSUE TITLE
[Documentation] Update HA storage cert parameters

### ISSUE THREAD

**Issue by davidnuzik** [rancher/k3s#1059]
Review new HA docs, specifically around the secure method with the storage params for certs.

PR should remove the Secure method and Insecure method headings, but still include examples for both with and without these parameters and then briefly explain what the params do.

- Simpler method (not utilizing certs) goes first (is more common method)
- Client cert auth method goes second and explain the flags.

- Change .crt / etc names to "client.crt" for example so it's more clear.

- Meta info around how dsn works if not supplied is not important info for most users should go last at the end of the docs.

- "Join worker node(s) section"
Remove line:
> Note: You may want to provide the cluster-secret temporarily via a file or environment variable then destroy it or clear your bash history so the password is no longer exposed in plain text on the machine.

**Comment by davidnuzik** [comment]
If not familiar with current procedure for rancher/docs -- fork and make a feature branch and just submit a pr against rancher/docs:master for review by @catherineluse

**Comment by cjellick** [comment]
Thinking it can be like this (My markup here isnt exact, just using it to mimic the existing layou:

## Create Server Nodes
...Existing preamble about node requirements and tainting notes

### Storage endpoint
To configure an HA k3s cluster to use an external database you must specify a storage endpoint. To do so, either set the `K3S_STORAGE_ENDPOINT` environment variable or pass the `--storage-endpoint`  command line flag when running the `k3s server` command.
> **Note:** As a best practice we recommend using the `K3S_STORAGE_ENDPOINT` environment rather than the command line argument so that your database credentials aren't exposed as part of the k3s process info.

The value of this parameter is the data source name (DSN) used to connect to the external database and is dependent on the database being used, as specified below.

| POSTGRES  | MYSQL | ETCD |
| ------------- | ------------- | ------- |
|   |
this isnt a table | it's a tabbed section for each db's dsn. | But I don't care if it is a tabbed section or just three normal subsections. If it looks better as non-tabbed that's fine by me.

### Additional storage configuration options
All storage providers also support the following optional parameters:

| CLI Flag  | Environment Variable | Description |
| ------------- | ------------- | ------- |
|  <pre>--storage-cafile</pre> | K3S_STORAGE_CA_FILE | Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. |                              
|  <pre>--storage-certfile</pre>  | K3S_STORAGE_CERT_FILE | Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. |     
|  <pre>--storage-keyfile</pre>  | `K3S_STORAGE_CA_FILE` | Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. | 


### Example
The following example shows how to connect to a postgres database using client certificate authentication:
```
# Sample command
```
