### ISSUE TITLE
add a FAQ for "Where are the k3s logs"

### ISSUE THREAD

**Issue by cjellick** [rancher/k3s#1061]
we explain where logs go in https://rancher.com/docs/k3s/latest/en/advanced/ but i htink this should be an FAQ.

Not a must have for 1.0, but would be nice

**Comment by catherineluse** [comment]
This issue can be closed because https://github.com/rancher/docs/pull/2551 was merged

**Comment by magikid** [comment]
For anyone else who lands here from a search:

From: https://rancher.com/docs/k3s/latest/en/faq/

> **Where are the K3s logs?**
> 
> The installation script will auto-detect if your OS is using systemd or openrc and start the service.
>
> When running with openrc, logs will be created at `/var/log/k3s.log`.
>
> When running with systemd, logs will be created in `/var/log/syslog` and viewed using `journalctl -u k3s`.
