### ISSUE TITLE
k3s is put under unbearable load if there is a hight rate of conflicts

### ISSUE THREAD

**Issue by cjellick** [rancher/k3s#1069]
In load testing Rancher, we try to import 100 k3s clusters into a rancher server that is running on a signle node k3s cluster backed by an external mysql db.

This causes a lot of write/update load on k3s and specifically causes a lot of 409 conflicts. These conflicts are not k3s's fault they are biproduct of rancher's controller logic. However, they pointed out that if a lot of updates and conflicts are forced onto k3s, k3s will basically get so bogged down that it will never catch up.

I wonder if we could reproduce this without the overhead of rancher by a simple test that does a lot of concurrent writes.

**Comment by cjellick** [comment]
will be in rc2

**Comment by cjellick** [comment]
@ShylajaDevadiga we can just have dan do another pass with the new rc tomorrow to verify this

**Comment by dramich** [comment]
Running rc3 I didn't encounter this issue
