### ISSUE TITLE
Support cri-o or any arbitrary CRI implementation

### ISSUE THREAD

**Issue by ibuildthecloud** [rancher/k3s#107]
Right now the only options are to run the embedded containerd or run with Docker as the container runtime.  Support should be added such that in arbitrary CRI implementation can be used.

**Comment by Prodian0013** [comment]
@ibuildthecloud this is a big one for us!

**Comment by ibuildthecloud** [comment]
@Prodian0013 I should have a RC build next week to test this.  But just to clarify, if you want to use a different CRI you will have to install and manage it yourself.

**Comment by Prodian0013** [comment]
> @Prodian0013 I should have a RC build next week to test this. But just to clarify, if you want to use a different CRI you will have to install and manage it yourself.

@ibuildthecloud sounds good, I can test this with cri-o when rc is out.

**Comment by ibuildthecloud** [comment]
@Prodian0013 This should be working in v0.2.0-rc3.  I tested crio with cgroups manager set to "cgroupfs".  Right now the external CRI will not work with our included flannel.  So you have to run with `--container-runtime-endpoint=/var/run/crio/crio.sock --no-flannel`.  I'm still working on getting an external CRI work with the embedded flannel.

**Comment by ibuildthecloud** [comment]
I think for the time being I'm going to have to make it such that if you use an external CRI you must also bring your own CNI.  This is because both k3s and the CRI interact with CNI and the configuration must match.  That makes things hard so I'm just going to punt and say if you want your own CRI do CNI also. :/
