### ISSUE TITLE
Documentation for HA in 1.0 is unclear

### ISSUE THREAD

**Issue by jkirklan** [rancher/k3s#1082]
**Version:**

1.0 rc3
**Describe the bug**

Is k3s in 1.0 multi-master?  are there multiple copies of the server binary running across the multiple hosts?  The term server is overloaded, especially in the diagram.  The examples given only show one invocation of the server binary.  The diagram clearly shows multi-node running.  It is just unclear if the diagram is showing physical servers or multiple instances of the server process.  

Let me know if this is unclear.  thanks
**To Reproduce**

read the doc ;-p
**Expected behavior**

**Actual behavior**

**Additional context**

**Comment by erikwilson** [comment]
k3s 1.0 does have multi-master (HA) support.
A "node" may be a virtual or physical machine, and a "server" refers to a k3s server executable instance running in a node.

**Comment by cjellick** [comment]
I'll see if I can find a place to define these terms in the doc

**Comment by jkirklan** [comment]
That would be great.  Since it was the web site, I didn't see where I could do a PR to fox directly...

**Comment by cjellick** [comment]
updates merged. Will be live within the hour
