### ISSUE TITLE
How to build a k3s release for arm64?

### ISSUE THREAD

**Issue by zhuyong74** [rancher/k3s#1083]
"make" only to release for x86_64,how to release arm64？ 
how to set $K3S_ARM64_HOST & K3S_ARM64_HOST_USER in scripts/release.sh

**Comment by yanggeorge** [comment]
I also want to know.

**Comment by zimme** [comment]
There's currently no support for cross compiling as far as I understand it. However it seems as though at least someone has succeeded in cross compiling k3s using cgo.

https://github.com/rancher/k3s/issues/139

**Comment by zhuyong74** [comment]
in scripts/packet-cli，

BIN_SUFFIX="-${ARCH}"

if [ ${ARCH} = amd64 ]; then

BIN_SUFFIX=""

elif [ ${ARCH} = arm ]; then

BIN_SUFFIX="-armhf"

fi

no arm64

**Comment by zimme** [comment]
Yeah, that's becuse it will just use `ARCH` as `BIN_SUFFIX` for `arm64` in the case of `amd64` there will be no suffix on the binary i.e. `k3s` is for `amd64`, for `arm` it will use the suffix `armhf` i.e. `k3s-armhf` and for `arm64` it will just use `arm64` i.e. `k3s-arm64`.

**Comment by zimme** [comment]
If you don't know how to cross compile go projects, you can always build the project using make on an arm64 device and you'll get the `k3s-arm64` binary.

**Comment by zhuyong74** [comment]
I have builded the project using make on an arm64 device and I have getted the k3s-arm64 binary.
