### ISSUE TITLE
Impossible to include a worker in the cluster

### ISSUE THREAD

**Issue by gmoisio** [rancher/k3s#1085]
**Version:**
k3s version v1.0.0-rc3 (4a267279)
Ubuntu 18.04
Linux  4.15.0-70-generic #79-Ubuntu SMP Tue Nov 12 10:36:11 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Plaform AMD 64 bits

**Describe the bug**
When running the install on a node giving the right K3S_URL and the K3S_TOKEN, the install fails with this message in the /var/log/syslog:

```
Nov 15 09:51:41 myContainer-1 systemd[1]: Started Lightweight Kubernetes.
Nov 15 09:51:43 myContainer-1 k3s[6054]: time="2019-11-15T09:51:43.059013727+01:00" level=fatal msg="--token is required"
Nov 15 09:51:43 myContainer-1 systemd[1]: k3s-agent.service: Main process exited, code=exited, status=1/FAILURE
Nov 15 09:51:43 myContainer-1 systemd[1]: k3s-agent.service: Failed with result 'exit-code'.
```

FYI: when I try to use v0.10.2, the master does not want to start, but when I try v0.9.1 all is working fine.

Thanks
Regards

**Comment by zimme** [comment]
It's because `K3S_TOKEN` was broken. I saw that @erikwilson fixed it recently in this [commit](https://github.com/rancher/k3s/commit/95ff805c98fa48ffa8a477649d4e3ac87184fc16). So pretty sure this should work in the next release.

**Comment by gmoisio** [comment]
Thanks I will try it as soon as a new release will be online.
Regards

**Comment by davidnuzik** [comment]
Should be fixed in next rc

**Comment by davidnuzik** [comment]
This is verified working in v1.0.0-rc4
