### ISSUE TITLE
Traefik ingress default bind port

### ISSUE THREAD

**Issue by marcolag** [rancher/k3s#1086]
Hello,

i would like to install k3s alongside an existing nginx on my single node bare metal server but i would still like to use your traefik ingress. The proble is that if i install k3s with its default traefik it binds to port 80 and 443 on localhost and i cannot access my self hosted websited anymore. What i owuld like to do is terminate SSL at my nginx and then forward to my traefik.

**Comment by cjellick** [comment]
Can you check out these docs and let me know if they give you sufficient guidance?
https://rancher.com/docs/k3s/latest/en/networking/#traefik-ingress-controller

**Comment by marcolag** [comment]
Thanks for the help. I already discovered the link but it didnt really help me. I tried a few modifications on the deployed manifest like deployment.hostPort.httpsEnabled true and deployment.hostPort.httpsPort 444 but that only adds an additioanl bind for 444 along the existing 443. I think i have to modify the underlying traefik service but i am not sure how to do it.

**Comment by galal-hussein** [comment]
@marcoceppi we are using stable/traefik helm chart to deploy the ingress controller with service type LoadBalancer, and the ports there are hardcoded to 443 and 80 https://github.com/helm/charts/blob/master/stable/traefik/templates/service.yaml, as a workaround you can either:
- edit the traefik service after deployment and change the port from 80 and 443 to whatever you like
or 
- add `serviceType: NodePort` and use `service.nodePorts.https` option to use different nodeport port on the host

**Comment by biels** [comment]
Afaik, the ports will be reset everytime k3s starts. How do you work around this? My idea is that you should put a "patch" file in the same folder alongside `/var/lib/rancher/k3s/server/manifests/traefik.yaml`. How should this yaml file look like? Any other solution?

**Comment by brandond** [comment]
@biels https://rancher.com/docs/k3s/latest/en/helm/#customizing-packaged-components-with-helmchartconfig

**Comment by SandroHc** [comment]
For anyone else struggling with this, here's how to do it:

1. Create file `/var/lib/rancher/k3s/server/manifests/traefik-config.yaml` with contents:
```yml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      web:
        exposedPort: 8080
      websecure:
        exposedPort: 8443
```
2. Apply changes with `sudo kubectl apply -f /var/lib/rancher/k3s/server/manifests/traefik-config.yaml`

**Comment by asg0451** [comment]
does anyone know: how come the config says `exposedPort: 80` and yet in reality it picks a random one every time k3s starts up?

**Comment by brandond** [comment]
What exactly are you talking about? The service is exposed externally on port 80, but the node ports are randomly assigned. Thats just how it works.

**Comment by Herz3h** [comment]
@SandroHc solution won't work for me, I'm confused, i literally copied what he posted, checked docs which say the same thing, but ports are not changed. What to do ?
