### ISSUE TITLE
Agents failing to connect for few times in HA setup

### ISSUE THREAD

**Issue by galal-hussein** [rancher/k3s#1087]
**Version:**
v1.0.0-rc3

**Describe the bug**
When agent start in HA setup, it fails to connect to the master and exits with the following error:
```
Nov 14 19:27:05 ip-172-31-9-105 k3s[2410]: time="2019-11-14T19:27:05.341346031Z" level=fatal msg="tls: private key does not match public key"
```
The agent eventually reconciles and connect back, it takes about 5 to 10 minutes

**To Reproduce**
- start HA cluster with 3 master and mysql/postgres/etcd backend
- join 10 or more workers

**Expected behavior**
All agents join immediately.

**Actual behavior**
Some agents fails to connect immediately and exits with the above error.

**Comment by davidnuzik** [comment]
Should be fixed (but not merged in master just yet)

**Comment by cjellick** [comment]
@galal-hussein please test by just running the rc through the same steps to repro again
