### ISSUE TITLE
Consider changing versioning scheme

### ISSUE THREAD

**Issue by cjellick** [rancher/k3s#1088]
We need to consider if and how we should align k3s' versioning with k8s' upstream versioning so that users can easily tell from the version what version of k8s will be ran.

**Comment by erikwilson** [comment]
I think it might work well if the k8s version is appended as build metadata, so it might be something like k3s `v1.2.3+k8s-1.16.3` or k3s `v1.2.3+k8s-1.15.6`, and similarly the k8s version should have the k3s version as build metadata, so it might report as something like `v1.16.3+k3s.1-1.2.3`

**Comment by cjellick** [comment]
We landed on `<k8s version>+<k3s metadata>` like `v1.17.0+k3s.1`
