### ISSUE TITLE
Unable to use env var K3S_TOKEN  while joining the worker node

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/k3s#1089]
**Version:**
v1.0.0-rc3

**Describe the bug**
Unable to join worker node using K3S_TOKEN while using the --token flag works as expected.

**To Reproduce**
Set the K3S_TOKEN=XXX while joining the node

**Expected behavior**
Node is in Ready state

**Actual behavior**
Node is not joined

**Additional context**
```k3s[7486]: time="2019-11-15T19:38:42.671617204Z" level=fatal msg="--token is required"```
Usage
```curl -fL https://get.k3s.io | INSTALL_K3S_VERSION=v1.0.0-rc3 sh -s - agent K3S_TOKEN=<TOKEN> K3S_URL=https://<MASTER>:6443```

**Comment by erikwilson** [comment]
dupe #1085

**Comment by ShylajaDevadiga** [comment]
Fixed. Closing issue. ```curl -fL https://get.k3s.io | INSTALL_K3S_VERSION=v1.0.0-rc4 K3S_TOKEN=<token> K3S_URL=<server> sh -```
