### ISSUE TITLE
Failed to update status for pod: conversion Error: v1.PodIP

### ISSUE THREAD

**Issue by ckaczor** [rancher/k3s#1095]
**Version:**
k3s version v0.9.1 (755bd1c6)

Using a default install - no special flags.

**Describe the bug**
After running for a while the pods on my worker node go into an unknown state and networking between the pods on that node stops working.  

The agent log for that node has a bunch of errors like this for each pod:

`Nov 17 14:00:31 weather k3s[423]: W1117 14:00:31.455245     423 status_manager.go:501] Failed to update status for pod "weather-serial-reader-7559dfd96c-w2pzd_home-monitor(15b8e687-b906-49de-a3d8-07bbd8932d78)": failed to patch status "{\"status\":{\"$setElementOrder/conditions\":[{\"type\":\"Initialized\"},{\"type\":\"Ready\"},{\"type\":\"ContainersReady\"},{\"type\":\"PodScheduled\"}],\"conditions\":[{\"lastTransitionTime\":\"2019-11-17T02:49:02Z\",\"message\":null,\"reason\":null,\"status\":\"True\",\"type\":\"Ready\"},{\"lastTransitionTime\":\"2019-11-17T02:49:02Z\",\"message\":null,\"reason\":null,\"status\":\"True\",\"type\":\"ContainersReady\"}],\"containerStatuses\":[{\"containerID\":\"containerd://0be2419bb5542c36e9e374ab5b68e55064793c12ebb515e36511abca8ed4afdf\",\"image\":\"docker.io/ckaczor/home-monitor-weather-serialreader:33\",\"imageID\":\"docker.io/ckaczor/home-monitor-weather-serialreader@sha256:ffda42538d25596279063175df85bad77ea90671d7c69eed040599305bba75cd\",\"lastState\":{\"terminated\":{\"containerID\":\"containerd://38a2face051e48e07ff2fcee7da286d1e81f33b7ef25e9afe6e5262a6811f2fa\",\"exitCode\":255,\"finishedAt\":\"2019-11-17T02:34:25Z\",\"reason\":\"Unknown\",\"startedAt\":\"2019-11-16T13:43:46Z\"}},\"name\":\"weather-serial-reader\",\"ready\":true,\"restartCount\":1,\"state\":{\"running\":{\"startedAt\":\"2019-11-17T02:49:02Z\"}}}],\"podIP\":\"10.42.3.15\"}}" for pod "home-monitor"/"weather-serial-reader-7559dfd96c-w2pzd": conversion Error: v1.PodIP(10.42.3.15) != v1.PodIPs[0](10.42.3.2)`

**To Reproduce**
Not really sure how to reproduce this - I can get it to clear up if I delete the pods and let them restart but then it happens again a while later.

**Additional context**
The cluster had originally been running k3os v0.2.1 on the master and a corresponding version of k3s (I forget exactly which version) on the worker.

Recently I rebuilt the master VM and installed k3os v0.6 and uninstalled k3s on the worker and reinstalled it using 0.9.1 (I had tried 0.10.0 but had the Raspberry PI TLS issues) - it could be that something got left behind on the worker that is causing issues?  The master was recreated from scratch so that shouldn't have anything residual.

Thanks!

**Comment by erikwilson** [comment]
It is probably a good idea to have the server & agents all on the same version of k3s. If you are able to recreate the cluster using k3s v1.0.0, the RPi tls issue should be resolved.

**Comment by ckaczor** [comment]
I tore down the cluster and recreated it using on k3os v0.7.0 and k3s v1.0.0 - everything is running fine now but the real test will be how long it stays that way.  =)

Thanks!
