### ISSUE TITLE
FATA[...] Initial server URL host is not defined for load balancer

### ISSUE THREAD

**Issue by Yuval-Ai** [rancher/k3s#1101]
Hi, 
I'm trying to connect a **K3s** Node to a **K8s** Master. 

While starting the k3s agent: 
```console
 # k3s agent -s <master IP> -t <master token>
```
i get the following error:

> INFO[...] Starting k3s agent v1.0.0 (18bd921c)
> INFO[...] module overlay was already loaded
> INFO[...] module nf_conntrack was already loaded
> INFO[...] module br_netfilter was already loaded
> WARN[...] Error starting load balancer: Initial server URL host is not defined for load balancer
> FATA[...] Initial server URL host is not defined for load balancer

Any thoughts? 

Thanks!

**Comment by erikwilson** [comment]
Thanks for the info! We should probably verify the server is valid earlier in the process, but the `K3S_URL` or `--server` flag should be a complete URL with scheme and port, eg: `https://10.135.135.1:6443`

**Comment by yuvalailer** [comment]
Yes! This was the problem.
Thank you @erikwilson for the fast reply.

**Comment by Yuval-Ai** [comment]
This was the specific problem,
but this course is currently irrelevant because of #1110 .
Thank you @erikwilson for the fast reply.
