### ISSUE TITLE
k3s 0.10.2 -> 1.0.0 upgrade: "failed to find any PEM data in key input"

### ISSUE THREAD

**Issue by luisbrandao** [rancher/k3s#1102]
Maybe I am not supposed to do this way, but I was testing the upgrade to version 1.0.0 in my cluster.
I run the update with only one of the worker nodes, and end up with:
```
Nov 19 11:01:45 0019d182f673.agrotis.io k3s[8952]: time="2019-11-19T11:01:45.544051881-03:00" level=error msg="tls: failed to find any PEM data in key input"
Nov 19 11:01:50 0019d182f673.agrotis.io k3s[8952]: time="2019-11-19T11:01:50.575954470-03:00" level=error msg="tls: failed to find any PEM data in key input"

```
repeating in loop.
(node end up not been listing by the master)

Wasn't I supposed to be able to upgrade each node at a time?

**Comment by erikwilson** [comment]
Server nodes should be upgraded first.

**Comment by luisbrandao** [comment]
yeah, thats it. wrong upgrade order. Thanx
