### ISSUE TITLE
wy root needed, why not use systemd user sessions?

### ISSUE THREAD

**Issue by vtolstov** [rancher/k3s#1105]
i don't want to install globally and want to run only as non root user.
How can i do that? I can specify bin dir to my local user $HOME/bin, services can be installed to $HOME/.config/systemd/user/
Why you not provide such case? And does it possible to run via unprivileged user?

**Comment by vtolstov** [comment]
after patching shell installer i can run via systemd --user services, but not all fine
```
Flexvolume plugin directory at /usr/libexec/kubernetes/kubelet-plugins/volume/exec/
```

does it possible to be able to override such path? for example use something like .local/xxxx ?

**Comment by andypost** [comment]
There's `--rootless` option for server and agent https://rancher.com/docs/k3s/latest/en/installation/install-options

@vtolstov  nice idea with user's session

**Comment by vtolstov** [comment]
Thanks for pointing for rootless.

чт, 21 нояб. 2019 г., 15:08 Andy Postnikov <notifications@github.com>:

**Comment by davidnuzik** [comment]
You can utilize `--rootless` as @andypost mentioned. I'll be closing this issue now; if you have any other specific questions around this issue let us know (and reopen this issue) or open a new issue. Thanks!
