### ISSUE TITLE
Incredibly high CPU usage when deploying prometheus-operator

### ISSUE THREAD

**Issue by David-Igou** [rancher/k3s#1108]
**Version:**
k3s version v1.0.0 (18bd921c)

k3s on t2.micros [I'm aware these are small, but this behaviour is observed when no other loads are being ran, so I don't think this is entirely a question of resources]

**Describe the bug**
When I deploy the prometheus-operator, CPU usage on the master skyrockets and makes the master pretty much unresponsive. The API frequently times out and the only way to immediately alleviate these symptoms is to run "kubectl delete deployment prometheus-operator" in a loop until one request is successful

**To Reproduce**
> Deploy k3s cluster 
> kubectl create the prometheus-operator stack using the bundle.yml off of their github repo

**Expected behaviour**
CPU usage does not rise to the point the API is unresponsive

**Additional context**

What's frustrating here is this is a difficult issue to troubleshoot, so I'm open to any guidance. Setting logging to all on the prometheus-operator doesn't seem to give any insight. There's nothing in the master's journal that gives any insight. I'm not sure if this is the operator sending extremely expensive queries to the API, or a flood or requests. etc.

I'm leaning towards this being a "k3s issue" and not a "prometheus operator" issue since I've never observed anything like this on far more underpowered systems.

node_exporter node_load1: (You can guess which is the master)
![image](https://user-images.githubusercontent.com/10202463/69249260-9bbd9f80-0b7b-11ea-997a-845bb738d080.png)

**Comment by runningman84** [comment]
These issues could be linked: https://github.com/rancher/k3s/issues/294

**Comment by David-Igou** [comment]
Here are the system logs during a spike.

So, after I deploy the operator and the CPU spikes, if I restart the instance it'll come back up eventually and act fine. But, after ~16-20 hours, the spike happens again and the master running the k3s service becomes unresponsive

CPU load via node_exporter at the time:

![image](https://user-images.githubusercontent.com/10202463/69484763-25cc6900-0e05-11ea-812f-6c1eb00f58e4.png)

Here are the system logs for that period of time:

https://gist.githubusercontent.com/David-Igou/011a5fe0a180023575571ac743a05aa4/raw/48f1848673d8ebbd34a5c6ee0c41dfbf9af27ac5/gistfile1.txt

**Comment by David-Igou** [comment]
This turned out to be orchestrated by a couple of mistakes I made:

First, I accidentally used Ubuntu server on my nodes.  Server ships with a bunch of cron jobs and add-ons that a t2.micro running the k3s server cannot handle, creating a huge backlog of requests, and thus slower and slower API responses. This also immediately burned all of the nodes burst credits and put it into a death spiral.

Masking most of the expensive services that are automatically enabled in ubuntu-server fixed this.

The reason I blamed the prometheus-operator was that the first time I saw this, I was deploying the operator the first time. I'm not sure what causes so much API load about this, but I can still recreate that by deleting the CRDs and redeploying the operator. I think it just barely pushes the limit of a micro on creation?

This was a super fun issue to troubleshoot, but as soon as I noticed the API was going down every night at ~2AM est, it was clear

**Comment by anydef** [comment]
I get similar behaviour on my raspberry-pi cluster.

**Comment by David-Igou** [comment]
@anydef Blast from the past getting a notification for this!

I'd recommend checking out to see if you're having an i/o bottleneck on your mater node. I too was able to recreate this on a Pi a bit later (I've been hosting my k8s labs on ARM boards for about 3 years now) and for me it turned out to be a read/write bottleneck to "etcd" (sqlite).

I eventually upgraded my single master to a Rock Pi 4 backed with an NVME drive, and the issues went away entirely. I have a lot of workloads on maanged nodes now and the master node performs fine.

The first thing I'd recommend to you, if you're seeing the same spike in master i/o (even if your prometheus-operator pod is on a different node) is to invest in a USB3 drive (even a decent flash drive will work here) and boot off that. I recommend checking out Jeff Geerling's Pi 4 storage blogs.

**Comment by anydef** [comment]
@David-Igou thanks for the reply. The gag is, that master nodes hanged when installing  the monitoring stack, or not even that, but an operator. Also I couldn't even ssh, only after power off/on. Worker nodes were behaving just fine. 
I will definitely look into the i/o. the SD cards I'm using are Samsung EVO. maybe when I could justify it, I will upgrade storage solution and replace master node with something better that rpi3.

**Comment by David-Igou** [comment]
@anydef Yeah I recommend at least a 4gb Pi 4 to use as a master. I ran into an unmanageable amount of issues attempting to use Pi 3's as my master(s)

**Comment by anydef** [comment]
maybe in the year 2024 when they start shipping again. 
but to mitigate current issue, I was considering to abandon prometheus-operator and install the stack using bare k8s manifest + tf modules
