### ISSUE TITLE
Failed to build from source

### ISSUE THREAD

**Issue by wpf710** [rancher/k3s#1109]
**Version:**
   Latest code 
**Describe the bug**
  by following the guilde,    when executing the `./scripts/download && ./scripts/build && ./scripts/package-cli`,   the console display as below:
   go: modernc.org/mathutil@v1.0.0: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /root/go/pkg/mod/cache/vcs/fb72eb2422fda47ac75ca695d44b06b82f3df3c5308e271486fca5e320879130: exit status 128:
	error: RPC failed; result=22, HTTP code = 404
	fatal: The remote end hung up unexpectedly

**To Reproduce**
   git clone  and cd k3s   , ./scripts/download && ./scripts/build && ./scripts/package-cli

**Expected behavior**
  build worked

**Actual behavior**
  build failed

**Additional context**

**Comment by erikwilson** [comment]
This looks like a temporary error with modernc.org, but if you `export GO111MODULE=off` then go 1.13+ should use packages from the `vendor` directory.

**Comment by wpf710** [comment]
still failed as below
`+ go build -tags 'ctrd apparmor seccomp no_btrfs netcgo osusergo providerless ' -ldflags '
    -X github.com/rancher/k3s/pkg/version.Version=v1.0.0
    -X github.com/rancher/k3s/pkg/version.GitCommit=18bd921
    -X github.com/rancher/k3s/vendor/github.com/containerd/containerd/version.Version=v1.3.0-k3s.4
    -X github.com/rancher/k3s/vendor/github.com/containerd/containerd/version.Package=github.com/rancher/containerd
    -X github.com/rancher/k3s/vendor/github.com/kubernetes-sigs/cri-tools/pkg/version.Version=v1.16.1-k3s.1 
    -w -s 
' -o bin/containerd ./cmd/server/main.go
cmd/server/main.go:8:2: import "github.com/kubernetes-sigs/cri-tools/cmd/crictl" is a program, not an importable package
[root@izj6cauhsvadcj1ztbh5pmz k3s]# go version
go version go1.13.3 linux/amd64
[root@izj6cauhsvadcj1ztbh5pmz k3s]# uname -r
3.10.0-693.2.2.el7.x86_64
`

**Comment by erikwilson** [comment]
No idea, sorry. Check to see if you have that package already in your go path. It is working fine in CI and on my build setup.

**Comment by wpf710** [comment]
First ,  I remove the old `github.com/kubernetes-sigs`, it can continue,  but  said that  ` gcc ld -lpthread` error.

Then, I switch to `make` again (don't know why ,maybe just want to try ),  found that my docker is 1.13, not support the `From xxx as base`,  so install the docker-ce

Eventually,  worked. 

thanks.
