### ISSUE TITLE
k3s does not allow _ in hostname

### ISSUE THREAD

**Issue by samirsss** [rancher/k3s#1120]
**Version:** k3s -v
k3s version v0.10.2 (8833bfd9)

**Describe the bug**
We have some servers with _ in host names and k3s doesnt start there. The regex that k3s currently uses doesnt permit having _ in hostname

**To Reproduce**
change the hostname to have an _ and verify that k3s wont deploy/start the app

**Expected behavior**
_ is very common to have in hostnames even in lab environments and hence we would like this to be allowed

**Comment by erikwilson** [comment]
hostnames should not contain _ (https://en.wikipedia.org/wiki/Hostname), DNS names can, but according to RFCs hostnames should only be case-insensitive alphanumeric and hyphen.

**Comment by samirsss** [comment]
Thanks @erikwilson we will guard against this in our installation script in that case
