### ISSUE TITLE
--flannel-backend option not recognised when starting agent with it

### ISSUE THREAD

**Issue by vitobotta** [rancher/k3s#1125]
**Version:**
k3s version v1.0.0 (18bd921c)

**Describe the bug**
Not sure it is expected, but when I run k3s in agent mode specifying ipsec as the backend for flannel, I get this:

```
flag provided but not defined: -flannel-backend
```

However, the list of options available for the agent shows this:

```
--no-flannel                        (deprecated) use --flannel-backend=none
```

suggesting that the --flannel-backend option should be available.

If I start the server with that option, and the agents without it, will the traffic be encrypted or not?

**To Reproduce**
Start the agent with `--flannel-backend=ipsec`

**Expected behavior**
I thought that I would have to specify the flannel backend for the agents as well, and the list of options seems to suggest that this should be possible/required for the traffic to be encrypted.

**Actual behavior**
The `--flannel-backend`  option is not recognised when starting the agent with it.

**Comment by sebastien-prudhomme** [comment]
It seems that this flag is only need on the master. When i launch the agent, there is some log about ipsec. I guess it got the right config from the master.

**Comment by vitobotta** [comment]
Hi @sebastien-prudhomme I also saw some ipsec lines in the logs so I guess I should be good. Thanks!

**Comment by identitymonk** [comment]
Hi,

I ask to reopen this please. I got the issue with K3s v1.17 when using the --flannel-backend=none on K3s agent cause I want to use calico instead.

The service unit fails with:

```
[root@slave1 ~]# systemctl status k3s-agent -l
● k3s-agent.service - Lightweight Kubernetes
   Loaded: loaded (/etc/systemd/system/k3s-agent.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2020-06-10 02:49:22 CDT; 3s ago
     Docs: https://k3s.io
  Process: 4907 ExecStart=/usr/local/bin/k3s agent --flannel-backend=none --debug (code=exited, status=1/FAILURE)
  Process: 4905 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
  Process: 4903 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
 Main PID: 4907 (code=exited, status=1/FAILURE)

Jun 10 02:49:22 slave1.k3s.local k3s[4907]: time="2020-06-10T02:49:22-05:00" level=fatal msg="flag provided but not defined: -flannel-backend"
Jun 10 02:49:22 slave1.k3s.local systemd[1]: k3s-agent.service: main process exited, code=exited, status=1/FAILURE
Jun 10 02:49:22 slave1.k3s.local systemd[1]: Unit k3s-agent.service entered failed state.
Jun 10 02:49:22 slave1.k3s.local systemd[1]: k3s-agent.service failed.
```
But it woks fine if I use the command line. Also the service does not work if using the legacy `--no-flanel`

JF

**Comment by identitymonk** [comment]
So tweaking the service unit for K3s with:
```
ExecStart=/usr/local/bin/k3s \
    agent \
        '\--flannel-backend=none'
```
did the trick. Please note the \ before the --

**Comment by brandond** [comment]
You shouldn't be configuring the flannel backend on the agent, which is why the flag is deprecated. Flannel configuration for agents is controlled by the server and pushed to agents when they start.

**Comment by identitymonk** [comment]
That's what I thought initally but I got flannel running on my worker nodes even when I said no flannel CNI at the server/master. This situation messed up with the BGP communication needed by Calico between Server and Agent.

This why I tried to deactivate it at agent level which is not deprecated (using --no-flannel is deprecated, not --flannel-backend=none).

Still there is an issue cause I got the same problem with -- debug. When the service is created, K3s cries cause systemctl asks it to run `k3s agent -debug` and it does not know -debug. This has to be solved with the same trick: putting `'\--debug'` in the service unit.

**Comment by brandond** [comment]
I think this might be unique to your environment. I have multiple flags passed to both the agent and server without needing to muck about with quoting or escaping characters. What does your unit file look like?

I also see the flannel configuration being properly pulled from the server without having to pass it to each individual agent.

**Comment by identitymonk** [comment]
So you think it pulls, I think it installs it by default. It does not take it from the serve.

I installed my server/Master with no flannel CNI cause I use Calico there and still my worker , by default, after joining got Flannel. Which messed up with Calico BGP.

The only way to not have Flannel installed on the worker node was to use the non deprecated `--flannel-backend=none` flag on the K3s installer script:
```
K3S_URL=https://${K3S_MASTER_HOSTNAME}:6443 K3S_TOKEN=<K3s Master Token> INSTALL_K3S_SKIP_DOWNLOAD=true all-in-one/scripts/Rancher/install.sh --flannel-backend=none
```
The service unit for K3s seemed to be OK:
```
ExecStart=/usr/local/bin/k3s \
    agent \
        '--flannel-backend=none'
```

but when starting I got the following error:
```
[root@slave1 ~]# systemctl status k3s-agent -l
● k3s-agent.service - Lightweight Kubernetes
   Loaded: loaded (/etc/systemd/system/k3s-agent.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2020-06-10 02:49:22 CDT; 3s ago
     Docs: https://k3s.io
  Process: 4907 ExecStart=/usr/local/bin/k3s agent --flannel-backend=none --debug (code=exited, status=1/FAILURE)
  Process: 4905 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
  Process: 4903 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
 Main PID: 4907 (code=exited, status=1/FAILURE)

Jun 10 02:49:22 slave1.k3s.local k3s[4907]: time="2020-06-10T02:49:22-05:00" **level=fatal msg="flag provided but not defined: -flannel-backend"**
Jun 10 02:49:22 slave1.k3s.local systemd[1]: k3s-agent.service: main process exited, code=exited, status=1/FAILURE
Jun 10 02:49:22 slave1.k3s.local systemd[1]: Unit k3s-agent.service entered failed state.
Jun 10 02:49:22 slave1.k3s.local systemd[1]: k3s-agent.service failed.
```
Only escaping the `--flannel-backend=none` in the service unit allowed me to have the service started without flannel.

I got the same issue with : `K3S_URL=https://${K3S_MASTER_HOSTNAME}:6443 K3S_TOKEN=<K3s Master Token> INSTALL_K3S_SKIP_DOWNLOAD=true all-in-one/scripts/Rancher/install.sh --debug
`
Where I got the corresponding error : `level=fatal msg="flag provided but not defined: -debug`

**Comment by brandond** [comment]
You're not making this work by adding backslashes, you're just making it ignore those arguments entirely. I'm not super familiar with the argument parser that k3s is using, but it appears you can pass it anything you want if you prefix it with a backslash:

```
root@dev01:~# /usr/local/bin/k3s agent '--total-garbage=yes'
FATA[0000] flag provided but not defined: -total-garbage

root@dev01:~# /usr/local/bin/k3s agent '\--total-garbage=yes'
FATA[2020-06-12T14:33:42.655779916-07:00] --token is required
```

If you want to see the actual valid arguments you can run `/usr/local/bin/k3s --help` and `/usr/local/bin/k3s agent --help`. Note that `--debug` is a global flag, not a flag for the `agent` command, so you if you want to add it you have to put it before agent: `usr/local/bin/k3s --debug agent` or set the K3S_DEBUG environment variable.
