### ISSUE TITLE
Error: Kubernetes cluster unreachable with helm 3.0

### ISSUE THREAD

**Issue by rubiktubik** [rancher/k3s#1126]
**Version:** 
k3s version v1.0.0 (18bd921c)

**Describe the bug**
I want to use helm version 3 with k3s but i when type `helm install stable/postgresql --generate-name` for example i get:
`Error: Kubernetes cluster unreachable`

**To Reproduce**

1. Installed helm 3 with script](https://helm.sh/docs/intro/install/#from-script).
2. Add repo with `helm repo add stable https://kubernetes-charts.storage.googleapis.com/`
3. Update repo with `helm repo update`
4. Install posgresql-chart with `helm install stable/postgresql --generate-name`

**Expected behavior**
Installation should work.

**Actual behavior**
`Error: Kubernetes cluster unreachable`

**Additional context**

**Comment by r1chjames** [comment]
Same issue here.

**Comment by davix** [comment]
I see the same issue with microk8s.

**Comment by grawin** [comment]
Try setting the KUBECONFIG environment variable.
`export KUBECONFIG=/etc/rancher/k3s/k3s.yaml`

**Comment by r1chjames** [comment]
That worked for me. Thanks @grawin

**Comment by Genubath** [comment]
Same issue. The fix @grawin posted doesn't solve it for me though.

**Comment by rubiktubik** [comment]
The fix @grawin posted doesn't worked for me either, i'am using a ubuntu 18.04 system.

**Comment by sixcorners** [comment]
If you add "-v 20" to your helm command line it will show it's connecting to port 8080.
Running this seems to fix it:
`kubectl config view --raw >.kube/config`

This lets helm use the same config kubectl is using I think.

**Comment by galal-hussein** [comment]
@rubiktubik looks like helm can't reach the k3s cluster, can you try to use --kubeconfig with helm command or using ~/.kube/config as @sixcorners suggested, please reopen the issue if the problem still persists.

**Comment by ShylajaDevadiga** [comment]
Closing issue as it has been resolved with v1.17.0-rc.3-k3s.1.

**Comment by kilroy05** [comment]
> If you add "-v 20" to your helm command line it will show it's connecting to port 8080.
> Running this seems to fix it:
> `kubectl config view --raw >~/.kube/config`
> 
> This lets helm use the same config kubectl is using I think.

can confirm this solution works for me as well

**Comment by pcgeek86** [comment]
This resolved the error message for me.

```
sudo helm install harbor/harbor --version 1.3.0 --generate-name --kubeconfig /etc/rancher/k3s/k3s.yaml
```

**Comment by michelcameroon** [comment]
with k3s i had the same problem, system tells me the file
/etc/rancher/k3s/k3s,yaml 
is not reachable

the file had rw for root i change to 744  and it works. please tell me if it is correct,

**Comment by aureq** [comment]
If you are using `sudo`, be aware that this command doesn't preserve environment variables (such as `KUBECONFIG`) by *default* when switching to a different context.

If you wish to preserve specific environment variables when using `sudo` then:

```bash
cat << EOF > /etc/sudoers.d/env
Defaults env_keep += "http_proxy https_proxy no_proxy"
Defaults env_keep += "HTTP_PROXY HTTPS_PROXY NO_PROXY"
Defaults env_keep += "KUBECONFIG"
EOF
```

**Comment by Vesnica** [comment]
> If you are using `sudo`, be aware that this command doesn't preserve environment variables (such as `KUBECONFIG`) by _default_ when switching to a different context.
> 
> If you wish to preserve specific environment variables when using `sudo` then:
> 
> ```shell
> cat << EOF > /etc/sudoers.d/env
> Defaults env_keep += "http_proxy https_proxy no_proxy"
> Defaults env_keep += "HTTP_PROXY HTTPS_PROXY NO_PROXY"
> Defaults env_keep += "KUBECONFIG"
> EOF
> ```

Just use `sudo -E`, which will preserve the environment variables.

**Comment by jordanburke** [comment]
@Vesnica thanks that worked for me.

**Comment by xbmono** [comment]
I'm using helm 3.2.4 on Windows and have the same issue. Setting environment variable KUBECONFIG didn't help either. Without `--kubeconfig` it doesn't fail but it returns no result on `helm ls`

**Comment by montaro** [comment]
what worked for me is to set the `KUBECONFIG` with absoult path value after changing directory to the chart directory.

**Comment by CarlosPerdomo** [comment]
> If you add "-v 20" to your helm command line it will show it's connecting to port 8080.
> Running this seems to fix it:
> `kubectl config view --raw >~/.kube/config`
> 
> This lets helm use the same config kubectl is using I think.

This `kubectl config view --raw >~/.kube/config` works for me. thaks

**Comment by poojabolla** [comment]
I tried this command,

kubectl config view --raw >~/.kube/config

but after running this config file became empty.

Can anyone suggest how to recover my config file with all values?

**Comment by Sudhakarch99** [comment]
Its gone, you must use >> instead > on appending something in existing file

**Comment by EKami** [comment]
I tried all the above solutions with Ansible with no success.
Was anyone able to make it work with Ansible? Here is the config I use:
```
- name: Install ingress-nginx
  community.kubernetes.helm:
    name: ingress-nginx
    chart_ref: ingress-nginx/ingress-nginx
    chart_version: "{{ ingress_nginx_release_name }}"
    release_namespace: ingress-nginx
    create_namespace: true
    update_repo_cache: yes
    values_files:
      - /tmp/ingress_nginx_values.yaml
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
```

**Comment by lpossamai** [comment]
I'm having the same issue when running `terraform destroy`.

```
provider "kubectl" {
  version = "1.7.1"
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.cluster.token
  load_config_file       = false
}
```

`kubectl get ns` directly from my terminal works.

`kubectl config view --raw >~/.kube/config` didn't work for me.

`helm` version specified on terraform:

```
    helm = {
      source = "hashicorp/helm"
      version = "=1.3.2"
    }
```

**Comment by brandond** [comment]
@lpossamai are you using k3s? Looks like you're set up to use EKS...

**Comment by lpossamai** [comment]
> 
> 
> @lpossamai are you using k3s? Looks like you're set up to use EKS...

You're right. I've commented [here](https://github.com/hashicorp/terraform-provider-helm/issues/400#issuecomment-781769504). Cheers

**Comment by sachinmalanki** [comment]
> @poojabolla.. Its gone, you must use >> instead > on appending something in existing file

I got this issue when using azure kubernetes

az aks get-credentials -n <myCluster>-g <myResourceGroup>
The config file is autogenerated and placed in '~/.kube/config' file as per OS

**Comment by MrMYHuang** [comment]
For microk8s, the k8s config can be generated by this command:
`microk8s.kubectl config view --raw > ~/.kube/config`

**Comment by sufiyanpk7** [comment]
For microk8s you can try with
```
export KUBECONFIG=/var/snap/microk8s/4094/credentials/client.config
```
