### ISSUE TITLE
rancher/k3s latest tag is not being updated

### ISSUE THREAD

**Issue by jonstelly** [rancher/k3s#1151]
**Version:**
1.0

**Describe the bug**
Docker Hub Image `rancher/k3s` tag for `latest` is not getting updated.  `latest` was last updated [7 months ago](https://hub.docker.com/r/rancher/k3s/tags?page=1&name=latest).

**Expected behavior**
For latest to point to latest stable image at any given time.

**Actual behavior**
It don't.

**Comment by davidnuzik** [comment]
This should be updated now.
