### ISSUE TITLE
Error 1071: Specified key was too long; max key length is 1000 bytes 

### ISSUE THREAD

**Issue by adi90x** [rancher/k3s#1153]
Hello,

When trying to bootstrap a new cluster, I got an error 1071 : Specified key was too long; max key length is 1000 bytes .
I am using MySQL has backend : --storage-endpoint="mysql://"

Any suggestion ?

Regards,

**Comment by mattmattox** [comment]
I got the same error when using MariaDB 10.0.38 but once I upgraded to 10.4.12 it worked without issue.

**Comment by adi90x** [comment]
Same after upgrading to MariaDB 10.4 no more issue

**Comment by alexellis** [comment]
I'm seeing two versions reported, how does this compare to yours @mattmattox and @adi90x? This is from the Linode marketplace.

```
mariadb --version
mariadb  Ver 15.1 Distrib 10.1.48-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```

**Comment by brandond** [comment]
I think `10.1.48-MariaDB` is the key version there.
