### ISSUE TITLE
Attempting to use aws vpc cni

### ISSUE THREAD

**Issue by markitoxs** [rancher/k3s#1154]
This might be a silly question, and please accept my apologies if so. 

Would anyone be able to either point me in the right direction or help me deploy AWS vpc cni? 

Whenever I attempt to do so, the daemonset is unable to pull the image from the aws ECR. Something tells me the kubelet is not picking up the credentials as it should, despite the instance having full admin access:
```  Normal   Scheduled  <unknown>          default-scheduler                                     Successfully assigned kube-system/aws-node-pl958 to ip-172-31-18-125.us-west-2.compute.internal
  Normal   Pulling    19s (x3 over 61s)  kubelet, ip-172-31-18-125.us-west-2.compute.internal  Pulling image "602401143452.dkr.ecr.us-east-2.amazonaws.com/amazon-k8s-cni:v1.5.3"
  Warning  Failed     19s (x3 over 60s)  kubelet, ip-172-31-18-125.us-west-2.compute.internal  Failed to pull image "602401143452.dkr.ecr.us-east-2.amazonaws.com/amazon-k8s-cni:v1.5.3": rpc error: code = Unknown desc = failed to pull and unpack image "602401143452.dkr.ecr.us-east-2.amazonaws.com/amazon-k8s-cni:v1.5.3": failed to resolve reference "602401143452.dkr.ecr.us-east-2.amazonaws.com/amazon-k8s-cni:v1.5.3": unexpected status code [manifests v1.5.3]: 401 Unauthorized                                  
``` 

How would one go into enabling the aws cloud provider? Is that even possible in k3s ?

**Comment by OzySky** [comment]
@netguino How did you solve this in the end? Using the Rancher ECR credentials helper?
