### ISSUE TITLE
Unable to disable Traefik

### ISSUE THREAD

**Issue by riker09** [rancher/k3s#1160]
**Version:**
k3s version v1.0.0 (18bd921c)

**Describe the bug**
I am unable to disable the build-in traefik load balancer.

**To Reproduce**
According to documentation all files in `/var/lib/rancher/k3s/server/manifests` are automatically deployed. I have removed the `traefik.yaml` file from this folder and changed `/etc/systemd/system/k3s.service`, followed by `systemctl daemon-reload` (everything as root user, of course).

The new service file has these lines in it:

```
ExecStart=/usr/local/bin/k3s \
    server \
    --docker \
    --no-deploy traefik \
```

Restart k3s service with `service k3s stop && service k3s start`. (yes, I also tried `service k3s restart`)

**Expected behavior**

Expected `kubectl -n kube-system get pods` to not list traefik pod.

**Actual behavior**

The pod is still restarted on each service restart.

**Additional context**

Ubuntu 19.10 with Docker 19.03.2.

**Comment by a01fe** [comment]
I think you'll have to manually remove the resources defined by `traefik.yaml`. Removing the manifest and restarting won't remove any resources that already exist.

**Comment by riker09** [comment]
I guess then the [official documentation](https://rancher.com/docs/k3s/latest/en/networking/#traefik-ingress-controller) is somewhat misleading. It says in docs:

> To disable it [Traefik], start each server with the --no-deploy traefik option. 

Obviously when installing k3s with the install script this is not enough. I also have to remove the previously created resources. I haven't checked it, but is there a configuration switch in the install.sh script that prevents deploying resources to the cluster during initial setup?

**Comment by riker09** [comment]
For the record and future me, this is what needs to be done to disable Traefik during initial setup:

1. Remove traefik helm chart resource: `kubectl -n kube-system delete helmcharts.helm.cattle.io traefik`
2. Stop the k3s service: `sudo service k3s stop`
3. Edit service file `sudo nano /etc/systemd/system/k3s.service` and add this line to `ExecStart`:
```
    --no-deploy traefik \
```
4. Reload the service file: `sudo systemctl daemon-reload`
5. Remove the manifest file from auto-deploy folder: `sudo rm /var/lib/rancher/k3s/server/manifests/traefik.yaml`
6. Start the k3s service: `sudo service k3s start`

**Comment by galal-hussein** [comment]
@riker09 you can still use the no-deploy with the install script, you just need to run the command as follows:
```
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --no-deploy traefik" sh
```
This will configure the server with no traefik and you wont find it in the manifests

thats also described here in the docs https://rancher.com/docs/k3s/latest/en/installation/install-options/#installation-script-options

**Comment by davidnuzik** [comment]
Use the `--no-deploy traefik` flag and value when installing. Please let us know if there are any other questions / concerns.

**Comment by khayyamsaleem** [comment]
Just updating to mention that `--no-deploy` is deprecated, and now people referring to this should use `--disable` instead.

**Comment by shahamit** [comment]
Despite executing the command "curl -sfL https://get.k3s.io **--disable traefik** | K3S_KUBECONFIG_MODE="644" sh -" I still see traefik service and pods getting created. What could be going wrong?

**Comment by brandond** [comment]
You're passing the disable flag to curl instead of the install script.

**Comment by shahamit** [comment]
Ah ok. The right command should be 
`curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644"  | INSTALL_K3S_EXEC="server --disable traefik" sh`
right?

**Comment by brandond** [comment]
no, now you've got a pipe with no command. You want both of the variables after the pipe

`curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="server --disable=traefik" sh -`

**Comment by AlecKotovichSAM** [comment]
> For the record and future me, this is what needs to be done to disable Traefik during initial setup:
> 
>     1. Remove traefik helm chart resource: `kubectl -n kube-system delete helmcharts.helm.cattle.io traefik`
> 
>     2. Stop the k3s service: `sudo service k3s stop`
> 
>     3. Edit service file `sudo nano /etc/systemd/system/k3s.service` and add this line to `ExecStart`:
> 
> 
> ```
>     --no-deploy traefik \
> ```
> 
>     4. Reload the service file: `sudo systemctl daemon-reload`
> 
>     5. Remove the manifest file from auto-deploy folder: `sudo rm /var/lib/rancher/k3s/server/manifests/traefik.yaml`
> 
>     6. Start the k3s service: `sudo service k3s start`

This is the only right way that works from all mentioned above

**Comment by brandond** [comment]
If you use `--disable=traefik` instead of `--no-deploy`, it will actually remove the manifest from disk and uninstall the helm chart. Is there some reason you suggest manually removing all these things instead?

**Comment by AlecKotovichSAM** [comment]
I tried --disable=traefik and unfortunately it did not work

**Comment by cawoodm** [comment]
I tried the following commands in Rancher Desktop both to no avail and the same result:
```
$ curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--no-deploy traefik" INSTALL_K3S_VERSION="1.23.3" sh -s -
[INFO]  Using 1.23.3 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/1.23.3/sha256sum-amd64.txt

$ curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable traefik" INSTALL_K3S_VERSION="1.23.3" sh -s -
[INFO]  Using 1.23.3 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/1.23.3/sha256sum-amd64.txt
```
It looks like no work is done.

I specified the version 1.23.3 because that's what Rancher Desktop installs. If I specify no version it tries to install 1.22.5

**Comment by chrisdecker1201** [comment]
@cawoodm Maybe you missed the = between disable and traefik

~~~bash
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable=traefik" INSTALL_K3S_VERSION="1.23.3" sh -
~~~

**Comment by koying** [comment]
Is there actually a way to disable traefik *post installation*?
`--disable` with or without `=` seems to have no effect.
Even worse, removing `/var/lib/rancher/k3s/server/manifests/traefik.yaml` does not work as it seems recreated at every restart.

Only working workaround is to do a `kubectl -n kube-system delete helmcharts.helm.cattle.io traefik` after each server restart 😟

**Comment by brandond** [comment]
Restarting with --disable=traefik should work, are you seeing otherwise? We had a regression present in a couple releases that broke that, but it has been resolved as far as I know: https://github.com/k3s-io/k3s/issues/5114

**Comment by koying** [comment]
> Restarting with --disable=traefik should work

I confirm it doesn't. 
Furthermore, it's unclear whether `=` is needed or not (or irrelevant). The help tells it's not.
```
--disable value                            (components) Do not deploy packaged components and delete any deployed components (valid items: coredns, servicelb, traefik, local-storage, metrics-server)
```

**Comment by brandond** [comment]
I can confirm that Traefik is properly uninstalled after restarting with traefik disabled. Can you confirm that you did a `systemctl daemon-reload` before restarting K3s, to make systemd pick up the change to the k3s service unit file? Do you perhaps have a config file at /etc/rancher/k3s/config.yaml that is overriding the disable list from the CLI flags?

```console
root@ubuntu01:~# kubectl get node -o wide
NAME                 STATUS   ROLES                  AGE    VERSION        INTERNAL-IP   EXTERNAL-IP   OS-IMAGE       KERNEL-VERSION           CONTAINER-RUNTIME
ubuntu01.lan.khaus   Ready    control-plane,master   5m4s   v1.22.9+k3s1   10.0.1.147    <none>        Ubuntu 21.10   5.14.13-051413-generic   containerd://1.5.11-k3s2

root@ubuntu01:~# kubectl get pod -o wide -A
NAMESPACE     NAME                                      READY   STATUS      RESTARTS   AGE     IP          NODE                 NOMINATED NODE   READINESS GATES
kube-system   local-path-provisioner-84bb864455-gjl5m   1/1     Running     0          4m13s   10.42.0.6   ubuntu01.lan.khaus   <none>           <none>
kube-system   svclb-traefik-4gms4                       2/2     Running     0          4m1s    10.42.0.7   ubuntu01.lan.khaus   <none>           <none>
kube-system   helm-install-traefik-crd--1-j4xs2         0/1     Completed   0          4m13s   10.42.0.3   ubuntu01.lan.khaus   <none>           <none>
kube-system   helm-install-traefik--1-twbkm             0/1     Completed   1          4m13s   10.42.0.2   ubuntu01.lan.khaus   <none>           <none>
kube-system   metrics-server-ff9dbcb6c-mgn2l            0/1     Running     0          4m13s   10.42.0.4   ubuntu01.lan.khaus   <none>           <none>
kube-system   coredns-7796b77cd4-7t4hb                  1/1     Running     0          4m13s   10.42.0.5   ubuntu01.lan.khaus   <none>           <none>
kube-system   traefik-d497b4cb6-pmqsl                   1/1     Running     0          4m1s    10.42.0.8   ubuntu01.lan.khaus   <none>           <none>
```

After restarting with `--disable=traefik`

```console
root@ubuntu01:~# kubectl get pod -o wide -A
NAMESPACE     NAME                                      READY   STATUS      RESTARTS   AGE     IP          NODE                 NOMINATED NODE   READINESS GATES
kube-system   local-path-provisioner-84bb864455-gjl5m   1/1     Running     0          4m19s   10.42.0.6   ubuntu01.lan.khaus   <none>           <none>
kube-system   metrics-server-ff9dbcb6c-mgn2l            0/1     Running     0          4m19s   10.42.0.4   ubuntu01.lan.khaus   <none>           <none>
kube-system   coredns-7796b77cd4-7t4hb                  1/1     Running     0          4m19s   10.42.0.5   ubuntu01.lan.khaus   <none>           <none>
kube-system   helm-delete-traefik-crd--1-6njt5          0/1     Completed   0          4s      10.42.0.9   ubuntu01.lan.khaus   <none>           <none>
```

**Comment by koying** [comment]
I guess I'm missing something, but I fail to see what.

```shell
$ kubectl get node -o wide
NAME     STATUS   ROLES                  AGE     VERSION        INTERNAL-IP       EXTERNAL-IP       OS-IMAGE             KERNEL-VERSION       CONTAINER-RUNTIME
app      Ready    <none>                 7d15h   v1.22.7+k3s1   100.64.224.55     100.64.224.55     Ubuntu 20.04.4 LTS   5.4.0-105-generic    containerd://1.5.9-k3s1
cloud    Ready    <none>                 7d15h   v1.22.7+k3s1   100.111.169.115   100.111.169.115   Ubuntu 16.04.7 LTS   4.15.0-142-generic   containerd://1.5.9-k3s1
uranus   Ready    control-plane,master   7d16h   v1.22.7+k3s1   100.127.151.84    100.127.151.84    Ubuntu 18.04.6 LTS   5.4.0-109-generic    containerd://1.5.9-k3s1

$ kubectl get pod -n kube-system -o wide
NAME                                      READY   STATUS    RESTARTS        AGE     IP           NODE     NOMINATED NODE   READINESS GATES
local-path-provisioner-84bb864455-qkgpc   1/1     Running   4 (3d21h ago)   7d16h   10.42.0.37   uranus   <none>           <none>
metrics-server-ff9dbcb6c-pnvj6            1/1     Running   9 (3d21h ago)   7d16h   10.42.0.31   uranus   <none>           <none>
coredns-96cc4f57d-948b6                   1/1     Running   5 (3d21h ago)   7d16h   10.42.0.30   uranus   <none>           <none>


$ rm /var/lib/rancher/k3s/server/manifests/traefik.yaml.skip

$# cat /etc/systemd/system/k3s.service
[Unit]
Description=Lightweight Kubernetes
Documentation=https://k3s.io
Wants=network-online.target
After=network-online.target

[Install]
WantedBy=multi-user.target

[Service]
Type=notify
EnvironmentFile=-/etc/default/%N
EnvironmentFile=-/etc/sysconfig/%N
EnvironmentFile=-/etc/systemd/system/k3s.service.env
KillMode=process
Delegate=yes
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=1048576
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
TimeoutStartSec=0
Restart=always
RestartSec=5s
ExecStartPre=/bin/sh -xc '! /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service'
ExecStartPre=-/sbin/modprobe br_netfilter
ExecStartPre=-/sbin/modprobe overlay
ExecStart=/usr/local/bin/k3s \
    server \
    --disable=traefik \

$ systemctl daemon-reload

$ systemctl restart k3s

$ kubectl get pod -n kube-system -o wide
NAME                                      READY   STATUS      RESTARTS        AGE     IP           NODE     NOMINATED NODE   READINESS GATES
local-path-provisioner-84bb864455-qkgpc   1/1     Running     4 (3d21h ago)   7d16h   10.42.0.37   uranus   <none>           <none>
coredns-96cc4f57d-948b6                   1/1     Running     5 (3d21h ago)   7d16h   10.42.0.30   uranus   <none>           <none>
metrics-server-ff9dbcb6c-pnvj6            1/1     Running     9 (3d21h ago)   7d16h   10.42.0.31   uranus   <none>           <none>
svclb-traefik-brkrn                       2/2     Running     0               102s    10.42.0.62   uranus   <none>           <none>
helm-install-traefik--1-vdrvd             0/1     Completed   0               113s    10.42.2.24   app      <none>           <none>
svclb-traefik-t8hrj                       2/2     Running     0               102s    10.42.1.53   cloud    <none>           <none>
svclb-traefik-b5hkq                       2/2     Running     0               102s    10.42.2.25   app      <none>           <none>
traefik-56c4b88c4b-4scfz                  1/1     Running     0               102s    10.42.0.63   uranus   <none>           <none>

$ kubectl -n kube-system delete helmcharts.helm.cattle.io traefik

$ kubectl get pod -n kube-system -o wide
NAME                                      READY   STATUS    RESTARTS        AGE     IP           NODE     NOMINATED NODE   READINESS GATES
local-path-provisioner-84bb864455-qkgpc   1/1     Running   4 (3d21h ago)   7d16h   10.42.0.37   uranus   <none>           <none>
metrics-server-ff9dbcb6c-pnvj6            1/1     Running   9 (3d21h ago)   7d16h   10.42.0.31   uranus   <none>           <none>
coredns-96cc4f57d-948b6                   1/1     Running   5 (3d21h ago)   7d16h   10.42.0.30   uranus   <none>           <none>

$ systemctl restart k3s

$ kubectl get pod -n kube-system -o wide
NAME                                      READY   STATUS      RESTARTS        AGE     IP           NODE     NOMINATED NODE   READINESS GATES
local-path-provisioner-84bb864455-qkgpc   1/1     Running     4 (3d21h ago)   7d16h   10.42.0.37   uranus   <none>           <none>
metrics-server-ff9dbcb6c-pnvj6            1/1     Running     9 (3d21h ago)   7d16h   10.42.0.31   uranus   <none>           <none>
coredns-96cc4f57d-948b6                   1/1     Running     5 (3d21h ago)   7d16h   10.42.0.30   uranus   <none>           <none>
svclb-traefik-24tbv                       2/2     Running     0               12s     10.42.0.64   uranus   <none>           <none>
traefik-56c4b88c4b-svx2w                  0/1     Running     0               12s     10.42.0.65   uranus   <none>           <none>
helm-install-traefik--1-x52bz             0/1     Completed   0               22s     10.42.2.27   app      <none>           <none>
svclb-traefik-lbqmc                       2/2     Running     0               12s     10.42.1.54   cloud    <none>           <none>
svclb-traefik-dw574                       2/2     Running     0               12s     10.42.2.28   app      <none>           <none>

$ kubectl -n kube-system delete helmcharts.helm.cattle.io traefik

$ touch /var/lib/rancher/k3s/server/manifests/traefik.yaml.skip

$ systemctl restart k3s

$ kubectl get pod -n kube-system -o wide
NAME                                      READY   STATUS    RESTARTS        AGE     IP           NODE     NOMINATED NODE   READINESS GATES
local-path-provisioner-84bb864455-qkgpc   1/1     Running   4 (3d21h ago)   7d16h   10.42.0.37   uranus   <none>           <none>
metrics-server-ff9dbcb6c-pnvj6            1/1     Running   9 (3d21h ago)   7d16h   10.42.0.31   uranus   <none>           <none>
coredns-96cc4f57d-948b6                   1/1     Running   5 (3d21h ago)   7d16h   10.42.0.30   uranus   <none>           <none>
```

**Comment by dyipon** [comment]
Same here on a multi-master-node k3s cluster, cannot uninstall default shipped traefik. 
Tried to delete helm chart, tried to delete the jobs, tried to setup --disable=traefik, but no success, helm chart always getting back.

**Comment by himao** [comment]
Disable traefik post installation:
```bash
helm -n kube-system delete traefik traefik-crd
kubectl -n kube-system delete helmchart traefik traefik-crd
touch /var/lib/rancher/k3s/server/manifests/traefik.yaml.skip
systemctl restart k3s
```

This should be a better approach, except for cleaning up the traefik part, which is in fact the main reason I'm here. We no longer need to use parameters or environment variables to modify systemd service files. And have good compatibility with upgrades, I think.
If you want to re-enable traefik, just delete traefik.yaml.skip and restart k3s.
About the `.skip`files: https://rancher.com/docs/k3s/latest/en/installation/disable-flags/

**Comment by mbrunn** [comment]
It is not working for me either. It is really frustrating. 

Steps I did:

1. removed the helm deployments
2. added the "--disable traefik" flag
```yaml
ExecStart=/usr/local/bin/k3s \
    server \
    --disable traefik \
```
3. did a daemon-reload
4. added the /var/lib/rancher/k3s/server/manifests/traefik.yaml.skip file (with root permissions)
5. restartet the service

The result is, that traefik is stell there "pending"

**Comment by jemygraw** [comment]
Both flag "--disable" and "--no-deploy" should not work as expected just because they are not implemented.

https://github.com/k3s-io/k3s/blob/master/pkg/cli/cmds/server.go#L421

https://github.com/k3s-io/k3s/blob/master/pkg/cli/cmds/server.go#L517

**Comment by Cesarsk** [comment]
> ```shell
> systemctl restart k3s
> ```

Hero! This worked

`k get all -A | grep traefik` finally returns... nothing!

**Comment by Cesarsk** [comment]
> Disable traefik post installation:
> 
> ```shell
> helm -n kube-system delete traefik traefik-crd
> kubectl -n kube-system delete helmchart traefik traefik-crd
> touch /var/lib/rancher/k3s/server/manifests/traefik.yaml.skip
> systemctl restart k3s
> ```
> 
> This should be a better approach, except for cleaning up the traefik part, which is in fact the main reason I'm here. We no longer need to use parameters or environment variables to modify systemd service files. And have good compatibility with upgrades, I think. If you want to re-enable traefik, just delete traefik.yaml.skip and restart k3s. About the `.skip`files: https://rancher.com/docs/k3s/latest/en/installation/disable-flags/

Hero!! This worked!

Finally this returns nothing: `k get all -A | grep traefik`

**Comment by napalm684** [comment]
This still seems to be an issue. Following the instructions @Cesarsk and @himao posted seems to clean up everything but the traefik service. I run kubectl delete svc traefik -n kube-system and it says it is deleted but the command never returns back to the prompt. It also is still in the get request.

**Comment by ondrejsika** [comment]
```
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --disable traefik" sh
```
