### ISSUE TITLE
Bump github.com/google/cadvisor from v0.34.0 to v0.35.0

### ISSUE THREAD

**Issue by joakimr-axis** [rancher/k3s#1163]
github.com/google/cadvisor [commit 0a8da7895f412260b8a1731bc631b7b9b150be94](https://github.com/google/cadvisor/commit/0a8da7895f412260b8a1731bc631b7b9b150be94) added support for overlayfs systems. This is something we need & use (currently we are patching k3s for this).

k3s currently use cadvisor v0.34.0, while the aforementioned commit is included in v0.35.0. Hence I would like to bump the v0.34.0 to v0.35.0. But I do not know how this is done; is there some "magic" involved or is it a complete code repository copy or something else that needs to be done? (I am happy to provide a PR once I get clarity on how it should be done.)

BR,

/J

**Comment by galal-hussein** [comment]
k3s uses our fork of kubernetes in https://github.com/rancher/k3s/blob/master/go.mod#L35  cadvisor can be updated in the go.mod in the rancher's kubernetes fork https://github.com/rancher/kubernetes/blob/v1.16.3-k3s.2/go.mod#L69

**Comment by davidnuzik** [comment]
Closing as question has been answered. Please reopen if needed and let us know if you need anything else. Thanks!

**Comment by joakimr-axis** [comment]
> k3s uses our fork of kubernetes in https://github.com/rancher/k3s/blob/master/go.mod#L35 cadvisor can be updated in the go.mod in the rancher's kubernetes fork https://github.com/rancher/kubernetes/blob/v1.16.3-k3s.2/go.mod#L69

I failed to create a PR on the rancher fork; the go.mod exists for the tags but I cannot find it if I check out branches? Anyway, parent repository kubernetes has updated to cadvisor v0.35.0 in [commit 9474154012eedc547e1cfa58c4a8d5d0e3308290](https://github.com/kubernetes/kubernetes/commit/9474154012eedc547e1cfa58c4a8d5d0e3308290) so I guess it will come into the rancher branch eventually.
