### ISSUE TITLE
K3s agent on Amazon Linux2

### ISSUE THREAD

**Issue by newtonsu** [rancher/k3s#1165]
the k3s server in ubuntu, I want to install agent in Amazon Linux2,but gas some wrong  
![image](https://user-images.githubusercontent.com/32892958/70316497-ce8fb500-1856-11ea-8aa5-c70a8e1c2629.png)

and get the node info is 
![image](https://user-images.githubusercontent.com/32892958/70316614-0eef3300-1857-11ea-8bcb-32fd496bb29d.png)
How can i solve this problem？

**Comment by davidnuzik** [comment]
@newtonsu is the concern about the "none" role for the worker? This is expected.

**Comment by davidnuzik** [comment]
Please let me know if my response did not answer your concern or if you have any specific questions. You can reopen the issue.
