### ISSUE TITLE
K3s nodes Status:NotReady after rebooting

### ISSUE THREAD

**Issue by samsja** [rancher/k3s#1170]
**Version:**

`v1.16.3-k3s.2`

**Describe the bug**

I instaledl k3s via k3sup on two of my raspberry 4 ( 4gb raspian lite): everething worked great.

Then I had to shut down both of my raspberry and reboot them.

However when it restart the system, node stay for ever in NotReady status ... I have experience with k8s but note with the kubelet kubeadm part and I don't now which service and how restart them. 

**To Reproduce**

* install raspbian lite on a raspberry pi 4
* install k3s via k3sup : ```k3sup install --ip $RASP_IP --user pi```
* (eventualy install k3s on a wokrer  raspberry pi : ```k3sup join --ip $WORKER_IP  --server-ip $MASTER_IP--user pi```
* shut down both master and worker
* restart both master and worker
* kubectl get nodes (on the pc with the right KUBECONFIG)

you should see something like

```
NAME     STATUS     ROLES    AGE     VERSION
worker   NotReady   <none>   3d18h   v1.16.3-k3s.2
master   NotReady   master   3d19h   v1.16.3-k3s.2
```

**Expected behavior**

I would expect the nodes to work like before. Or is it just not recommanded to shut down k3s nodes ? Because I need to move my raspberri Pis cluste sometimes

**Additional context**
```
20m         Normal    RegisteredNode            node/woker                   Node worker event: Registered Node arcko in Controller
20m         Normal    RegisteredNode            node/master               Node master event: Registered Node salameche in Controller
```

**Comment by samsja** [comment]
I finaly found a (very simple ) solution:

just did on the master nodes:

```
sudo systemctl restart k3s
```

**Comment by FordMustang0288** [comment]
> I finaly found a (very simple ) solution:
> 
> just did on the master nodes:
> 
> ```
> sudo systemctl restart k3s
> ```

My hero
