### ISSUE TITLE
Secrets are not populated

### ISSUE THREAD

**Issue by mortenlj** [rancher/k3s#118]
**Describe the bug**
The coredns pod that is created by the server fails to start and goes into CrashLoopBackOff. According to the logs, this is because there is no token in the serviceaccount secret. From the kubernetes side, everything looks correct. Looking in more detail at the actual docker container, reveals that the directory on the host that is supposed to contain the secret (the directory that is bind mounted into the container) is empty.

I'm not sure which component is responsible for populating this directory, but something seems to cause it to not be properly populated. That results in no token for coredns, which results in no dns in the cluster, making traefik fail to start.

**To Reproduce**
See #73 for information about my setup. RancherOS on a Rpi3B, running k3s server and k3s agent as separate containers on the system-docker.

**Expected behavior**
I expected the directory to be populated with data from the serviceaccount secret.

**Additional context**
The agent is logging messages about containers that does not exist during startup, but I can't see which containers it is complaining about, or any that are obviously missing.

**Comment by ibuildthecloud** [comment]
@mortenlj I think it's not going to be possible to use system-docker to run k3s and have k3s use the user docker.  I have a couple PRs in right now to fix k3s on RancherOS. We should produce a rc that you can test with on Monday.  But we haven't been able to get it to work running k3s in the "system" scope.

**Comment by mortenlj** [comment]
That's too bad, I kind of liked the separation. I'll try to purge everything and retry using user docker and see how that goes.

**Comment by mortenlj** [comment]
When using user docker it seems this problem goes away, so I'm closing it. If you feel you want to investigate further, feel free to reopen.
