### ISSUE TITLE
[Documentation] Node tainting and tolerations

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/k3s#1197]
Docs to include node tainting on master and worker nodes. Also include tolerations.
--node-taint value                         (agent/node) Registering kubelet with set of taints

**Comment by rektide** [comment]
Just to chime in here with a very lowly & recent new user's experiences, the docs made me think at first that I needed a multi-node cluster. I was surprised when I started a single node k3s server that I could run workloads on it. I was expecting there to be some tainting/tolerations issues that would have prevented this.

I haven't tried moving my k3s's towards multi-node clusters yet but I'm not sure whether taint/tolerations are going to kick in & remove workloads from the first node/server or not. And I'm not sure what I should be looking at to understand these systems.

Please forgive me if these comments to not belong in this ticket. It seemed similar & I was surprised I made it as far as I did (having only one node), & I'm not sure how to view or understand what goes on here. Maybe nothing will happen as my cluster goes multi-node. That would actually be fine for my very preliminary low-use use case, but I'd like to better understand this topic & what if anything k3s does or doesn't do here & how to understand it. Thanks @ShylajaDevadiga &al.

**Comment by davidnuzik** [comment]
Need to review this with @ShylajaDevadiga determine what we need clearly in the docs.

**Comment by davidnuzik** [comment]
@ShylajaDevadiga can you post what you are looking for? We call out the option in docs - do you want it expaned on? What is needed? 
Reference:
https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/
- and -
https://rancher.com/docs/k3s/latest/en/installation/install-options/agent-config/#node-labels-and-taints-for-agents

**Comment by ShylajaDevadiga** [comment]
@rektide this is expected behavior. A master is an agent as well, so you can run workloads on it. Thats what you are seeing. To avoid being able to run workloads you can apply taints, but agent components, kubelet kubeproxy will still be running on it.

**Comment by davidnuzik** [comment]
Based on discussion sounds like what we have should be sufficient in the documentation. If there are objections we can reopen the issue.
