### ISSUE TITLE
edited 'local-storage.yaml' gets overwritten on reboot

### ISSUE THREAD

**Issue by makkus** [rancher/k3s#1206]
**Version:**
```
# k3s -v
k3s version v1.0.0 (18bd921c)
```
installed using
```
curl -sfL https://get.k3s.io | sh -s - server --no-deploy=traefik --tls-san 10.0.0.6
```

**Describe the bug**
I am editing ``/var/lib/rancher/k3s/server/manifests/local-storage.yaml`` to change the default path for storage on my master node, but when I restart the node the old setting is applied again.

I've also tried to edit the configmap in question as well as the file, but can't seem to get k3s to keep my settings.

**Expected behavior**
The settings for the local-path-config map should be changed to the values I set.

**Additional context**
Am I wrong wrong in assuming this setting can be changed?

**Comment by luisbrandao** [comment]
Same issue here, but with the metric servers...
I changed some stuff... its gone now.

**Comment by DavidZisky** [comment]
Yes, k3s (over)writes all manifest files every time it restarts:

> Dec 19 09:27:28 k3s-master2 k3s[3087]: time="2019-12-19T09:27:28.617440333Z" level=info msg="Writing manifest: /var/lib/rancher/k3s/server/manifests/local-storage.yaml"

But in order to change what you want to change you should simply pass the parameter to the k3s server instead:

`--default-local-storage-path value         (storage) Default local storage path for local provisioner storage class`

**Comment by makkus** [comment]
@DavidZisky thanks, wasn't aware that's the way to to it. I somehow assumed those parameters would be mainly useful when setting up the node. So, just to confirm: the 'inbuilt' manifests are immutable (other than with command-line parameters), but any additional ones are fair game and can be changed at will?

**Comment by DavidZisky** [comment]
@makkus yes, correct. I should be a bit more specific. When I wrote "(over)writes all manifest files" I meant all "inbuilt" manifests indeed. Any additional one can be put in manifests folder and changed at will and they won't be overwritten or deleted by k3s - just applied every time server restarts.

**Comment by makkus** [comment]
Thanks, much appreciated!

**Comment by rafadesu** [comment]
I guess you would need to disable local-path-provisioner and deploy the objects yourself if you had more complex changes to paths in the cm, would that work?

**Comment by brandond** [comment]
@rafadesu yes that is the recommended way to handle this.

**Comment by rafadesu** [comment]
Thank you! That makes sense! BTW congratulations on K3S. Great work!
