### ISSUE TITLE
Upgrade helm controller to use v3

### ISSUE THREAD

**Issue by galal-hussein** [rancher/k3s#1218]
Helm controller should be using v3 which doesn't require tiller anymore, the controller should also respect The old release that were created by v2 and keep managing them with the same version

**Comment by ShylajaDevadiga** [comment]
With k3s version v1.17.0-rc.2-k3s.1
```kube-system   helm-install-traefik-n52jj                0/1     CrashLoopBackOff```
```helm_v3 install --set-string kubernetes.ingressEndpoint.useDefaultPublishedService=true --set-string metrics.prometheus.enabled=true --set-string rbac.enabled=true --set-string ssl.enabled=true traefik 'https://%{KUBERNETES_API}%/static/charts/traefik-1.81.0.tgz'
Error: failed to download "https://%{KUBERNETES_API}%/static/charts/traefik-1.81.0.tgz" (hint: running `helm repo update` may help)```
