### ISSUE TITLE
Unable to successfully upgrade with dqlite

### ISSUE THREAD

**Issue by davidnuzik** [rancher/k3s#1230]
**Version:**
v1.0.x to v1.17.0-rc.3-k3s.1 upgrade (dqlite HA)

**Describe the bug**
Upon attempting to upgrade K3s to the v1.17 rcs with a dqlite HA setup (3-node server cluster), this will fail upon attempting to upgrade the second server.

Specifically, we observe the following in the logs of the second server when we attempt to upgrade it. The upgrade of the initial server seems to succeed.
```
Dec 20 21:50:05 ip-172-31-22-67 k3s[3953]: time="2019-12-20T21:50:05.076116342Z" level=info msg="Starting k3s v1.17.0-rc.3-k3s.1 (5c374547)"
Dec 20 21:50:05 ip-172-31-22-67 k3s[3953]: time="2019-12-20T21:50:05.076470173Z" level=info msg="Cluster bootstrap already complete"
Dec 20 21:50:05 ip-172-31-22-67 k3s[3953]: time="2019-12-20T21:50:05.350371804Z" level=info msg="Testing connection to peers [172.31.16.199:6443 172.31.22.67:6443]"
Dec 20 21:50:05 ip-172-31-22-67 k3s[3953]: time="2019-12-20T21:50:05.659613378Z" level=info msg="Failed to test dqlite connection: reseting node ID from 3810358016083437419 to 1874274155, please restart"
Dec 20 21:50:07 ip-172-31-22-67 k3s[3953]: time="2019-12-20T21:50:07.660069415Z" level=info msg="Testing connection to peers [172.31.16.199:6443 172.31.22.67:6443]"
```

Notably, `Dec 20 21:50:05 ip-172-31-22-67 k3s[3953]: time="2019-12-20T21:50:05.659613378Z" level=info msg="Failed to test dqlite connection: reseting node ID from 3810358016083437419 to 1874274155, please restart"` is the key concern.

We see that with the install script it is stuck on "starting K3s" perpetually. Kubectl client commands will fail with message such as:
`Error from server (ServiceUnavailable): the server is currently unable to handle the request `
or
`Error from server: rpc error: code = Unknown desc = failed to create dqlite connection: no available dqlite leader server found`

**To Reproduce**
Create 3 machines, install dqlite normally with v1.0.0 or v1.0.1. Now, start upgrading the servers. Start with the initial server (--cluster-init server) this succeeds. Now, attempt to upgrade the second server -- this will fail as per the above.

**Expected behavior**
Successful k3s upgrade with dqlite HA. No issues upgrading the servers.

**Actual behavior**
Failure upon attempting to upgrade the second dqlite server with "Failed to test dqlite connection: reseting node ID from 3810358016083437419 to 1874274155, please restart"

**Additional context**
N/A

**Comment by ShylajaDevadiga** [comment]
Fixed in v1.17.0-rc4-k3s.1

**Comment by davidnuzik** [comment]
Should be fixed in rc4. Needs PR attached.

**Comment by davidnuzik** [comment]
Pretty sure fixed via: https://github.com/rancher/k3s/pull/1235
