### ISSUE TITLE
failed to start the child: fork/exec /proc/self/exe: operation not permitted

### ISSUE THREAD

**Issue by debianmaster** [rancher/k3s#1234]
**Version:**
1.0.0

**Describe the bug**
When trying to run k3s in rootless mode inside a container, container breaks with $subject error

**To Reproduce**
```
docker run --rm rancher/k3s:v1.0.0 server --rootless  -t testtoken
time="2019-12-21T11:23:44.213414927Z" level=fatal msg="failed to start the child: fork/exec /proc/self/exe: operation not permitted"
```

**Expected behavior**
k3s should run in docker conainer

**Actual behavior**
k3s stops running with error

**Comment by AkihiroSuda** [comment]
You need `--privileged`

**Comment by davidnuzik** [comment]
Please let us know if this did not resolve the issue (and provide any details). The issue can be re-opened.
