### ISSUE TITLE
[Documentation] Uninstall docs needs to include killall script

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/k3s#1238]
Needs documentation for k3s-killall.sh

**Comment by davidnuzik** [comment]
@davidnuzik - if run killall can just run k3s again? needs install again? (if restores iptables how would k3s work properly post killall script?

**Comment by davidnuzik** [comment]
Was able to confirm with Shylaja you can just start K3s again and it will work correctly.

**Comment by catherineluse** [comment]
Closing this issue because https://github.com/rancher/docs/pull/2507 was merged

**Comment by davidnuzik** [comment]
Closing will look into permissions for Catherine tomorrow
