### ISSUE TITLE
make compontentstatus usable

### ISSUE THREAD

**Issue by curx** [rancher/k3s#126]
**Is your feature request related to a problem? Please describe.**
No, make more act like the k8s ;)

**A clear and concise description of what the problem is.**
a kubectl get componentstatus give not the expected results

```shell=
# k3s kubectl get componentstatus
NAME                 STATUS      MESSAGE                                                                                     ERROR
controller-manager   Unhealthy   Get http://127.0.0.1:10252/healthz: dial tcp 127.0.0.1:10252: connect: connection refused   
scheduler            Unhealthy   Get http://127.0.0.1:10251/healthz: dial tcp 127.0.0.1:10251: connect: connection refused  
```

**Describe the solution you'd like**
see a clean status

**Additional context**
Make the controller-manager on 10252 and scheduler listen on the port 10251 and don't disable it or
make it configurable ?

See:
for control-manager:
https://github.com/rancher/k3s/blob/828ce5a24a5d7e36a61bcf26167b74ce195e0665/pkg/daemons/control/server.go#L105

and scheduler:
https://github.com/rancher/k3s/blob/828ce5a24a5d7e36a61bcf26167b74ce195e0665/pkg/daemons/control/server.go#L124

**Comment by ibuildthecloud** [comment]
The ports are currently disabled because we didn't want any public ports ports exposed.  If there is a simple way to make them bind to 127.0.0.1 we can do that.  Either which way we will fix it such that component status doesn't return unhealthy.

**Comment by ibuildthecloud** [comment]
Oh hey, I didn't see you already put in a PR.  Cool, thanks!
