### ISSUE TITLE
[Documentation] HA doc needs to have example using curl script as well as k3s binary

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/k3s#1273]
Installating k3s using external DB, needs to have a complete example of using curl as well as  k3s binary on the same page. And have a link to Installation Options page for more options.

**Comment by davidnuzik** [comment]
I'm going to close this issue in favor of https://github.com/rancher/k3s/issues/1194 which has requested overall that we are more consistent with how we show our examples for running k3s, not just for HA necessarily.
