### ISSUE TITLE
Installation hangs forever when firewall(ufw) is active

### ISSUE THREAD

**Issue by tullo** [rancher/k3s#1280]
**Version:** k3s version v1.17.0+k3s.1 (0f644650) on Ubuntu 19.10
**Describe the bug**
I had to disable ufw otherwise the installation of k3s would just hang there forever.

**To Reproduce**
sudo ufw status

```
Status: active
To                         Action      From
--                         ------      ----
443                        ALLOW       Anywhere                  
22/tcp                     ALLOW       Anywhere              
22/tcp (v6)                ALLOW       Anywhere (v6)             
443 (v6)                   ALLOW       Anywhere (v6)       
```
**Expected behavior** `curl -sfL https://get.k3s.io | sh -` runs as expected

**Actual behavior** installation gets stuck

**Comment by TeNNoX** [comment]
Fix:
`sudo ufw allow 6443 && sudo ufw reload`

**Comment by tullo** [comment]
Thanks, yes that works, but I'd rather not have to open that port!

**Comment by philipp1992** [comment]
yeah id also like to use ufw without allowing port 6443 to public, any workaround?

**Comment by brandond** [comment]
Needs to be open to the local node and any other nodes, not the world.

**Comment by philipp1992** [comment]
Same error on a single node installation

**Comment by brandond** [comment]
Yes, even on a single node installation you will still need to be able to connect locally to that port. If ufw blocks even local access then you'll need to open it up - this isn't like dockerd where you can disable the network and have it listen on a Unix socket.

Maybe try something like: `ufw allow from <node-ip> to any port 6443`

**Comment by rancher-max** [comment]
## I am able to recreate this with the following steps:

1. Create a new Ubuntu 19.10 VM
2. Enable ufw and allow the ports mentioned in this issue:
```
$ sudo ufw enable
$ ufw allow 443 && ufw allow 22/tcp
$ ufw status
Status: active

To                         Action      From
--                         ------      ----
443                        ALLOW       Anywhere                  
22/tcp                     ALLOW       Anywhere                  
443 (v6)                   ALLOW       Anywhere (v6)             
22/tcp (v6)                ALLOW       Anywhere (v6)   
```
3. Install k3s: `curl -sfL https://get.k3s.io | sh -`. Note here I tried with a few different versions of K3S and they all failed the same way:
```
$ k3s kubectl get pods -A
NAMESPACE     NAME                                     READY   STATUS             RESTARTS   AGE
kube-system   coredns-8655855d6-99rxk                  0/1     Running            0          5m18s
kube-system   metrics-server-7566d596c8-6dck6          0/1     CrashLoopBackOff   4          5m18s
kube-system   local-path-provisioner-6d59f47c7-cp7np   0/1     CrashLoopBackOff   4          5m18s
kube-system   helm-install-traefik-xmtmd               0/1     CrashLoopBackOff   2          5m19s
```

## Additional Info
Describing the pods shows just: `  Warning  Unhealthy  4m41s (x59 over 14m)  kubelet, k3s       Readiness probe failed: HTTP probe failed with statuscode: 503` on the coredns pod and nothing useful on the others.

The issue is as Brandon mentioned above with allowing 6443. Logs on all of the pods just timeout in retrieving endpoint: `Failed to list *v1.Endpoints: Get https://10.43.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.43.0.1:443: i/o timeout`

**Comment by brandond** [comment]
@rancher-max did you allow 6443? It looks like you allowed 22 and 443, neither of which k3s uses.

**Comment by rancher-max** [comment]
Correct, even if I do:
```
$ sudo ufw allow from <node_ip>  to any port 6443
$ sudo ufw allow from 10.43.0.1 to any port 6443
$ sudo ufw allow from 10.43.0.1 to any port 443
$ sudo ufw status
Status: active

To                         Action      From
--                         ------      ----
443                        ALLOW       Anywhere                  
22/tcp                     ALLOW       Anywhere                  
6443                       ALLOW       <node_ip>
443                        ALLOW       10.43.0.1                 
6443                       ALLOW       10.43.0.1    
443 (v6)                   ALLOW       Anywhere (v6)             
22/tcp (v6)                ALLOW       Anywhere (v6) 
```

K3S fails to start the coredns pod properly, with a state of Running but not ready. Logs show: `E0723 22:01:37.038850       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Endpoints: Get https://10.43.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.43.0.1:443: i/o timeout
[INFO] plugin/ready: Still waiting on: "kubernetes"`

**Comment by rancher-max** [comment]
That said, I believe the answer to this issue is probably more: "Ensure ufw is allowing all ports needed by applications your kubernetes/k3s cluster is using" and less a bug with k3s.

**Comment by brandond** [comment]
Hmm, from 10.43.0.1? I think that should be to. As a matter of fact, you might try allowing all and from the cluster and service CIDRs: 10.42.0.0/22 and 10.43.0.0/22

**Comment by rancher-max** [comment]
And it works! Thank you @brandond 
Looks like that was the key rule: 
```
$ sudo ufw allow from 10.42.0.0/16 to any && sudo ufw allow from 10.43.0.0/16 to any
$ sudo ufw status
Status: active

...
Anywhere                   ALLOW       10.42.0.0/16              
Anywhere                   ALLOW       10.43.0.0/16   
...
```

```

**Comment by brandond** [comment]
Yeah, sounds like the UFW rules are higher up in the ruleset than the kube-proxy rules, so it's blocking traffic to cluster services. I'm not sure if we specifically support UFW at the moment, but it probably wouldn't hurt to mention in the doc somewhere.

**Comment by bangonkali** [comment]
> And it works! Thank you @brandond
> Looks like that was the key rule:
> 
> ```
> $ sudo ufw allow from 10.42.0.0/16 to any && sudo ufw allow from 10.43.0.0/16 to any
> $ sudo ufw status
> Status: active
> 
> ...
> Anywhere                   ALLOW       10.42.0.0/16              
> Anywhere                   ALLOW       10.43.0.0/16   
> ...
> ```

Hi @rancher-max is this configuration secure if for example I'm hosting on Linode? This is just for study purposes btw. I just want to clarify the security implications i should be aware of for this `allow` command.

**Comment by bangonkali** [comment]
Okay, upon further check it seems my ufw list wasn't even followed at all even though it's status is enabled. Ports were still accessible from out side even if only port 22 was open.
