### ISSUE TITLE
Joining K3s agent node to K8s Master node

### ISSUE THREAD

**Issue by ronit1495** [rancher/k3s#1284]
Hi, I was curious if we can use k8s and k3s together as it will help me in solving a complex architecture for edge computing. 

I have a running k8s cluster prepared using kubeadm. For edge devices, I would like to have lightweight k3s running on them. Is it possible to use k8s cluster control plane to control  k3s agent running on edge devices (embedded/routers etc)?

This kind of setup will open a lot of options for me as I'll have k8s functionality with k3s light footprint.
I tried using the default token of kubeadm k8s on k3s agent node (worker) but obviously it didn't join.

**Comment by erikwilson** [comment]
Related #1110

**Comment by davidnuzik** [comment]
Hello, at this time we do not have any plans for supporting K8s and K3s together. Reference the issue Erik mentioned. Let us know if you have any questions.
