### ISSUE TITLE
Modular API Access

### ISSUE THREAD

**Issue by Promaethius** [rancher/k3s#129]
I know golang does function reaping for dependencies, so has the k3s subset of k8s APIs been modularized somewhere? I'd like to fork and extend k3s for personal use but I'd like to use some alpha APIs.

**Comment by erikwilson** [comment]
Features have been manually pruned @Promaethius, your best bet might be to look at the history of https://github.com/rancher/k3s/tree/k3s-v1.13.4 and undo some of those changes.

**Comment by deniseschannon** [comment]
@Promaethius if you have more questions, please feel free to open another issue.
