### ISSUE TITLE
How to specify an internal registry address for the coredns deployed by k3s

### ISSUE THREAD

**Issue by colben** [rancher/k3s#1294]
# ENV
- production, internet not available
- CentOS7 with k3s latest

# Issue
- k3s can auto-deploy coredns/traefik ifself by downloading the needed image from internet, is there any way to specify an internal private registry address for these images?

**Comment by dweomer** [comment]
@colben please see https://rancher.com/docs/k3s/latest/en/installation/airgap/#create-registry-yaml

**Comment by davidnuzik** [comment]
Please let us know if the airgap documentation is not sufficient. We can re-open the issue if necessary.
