### ISSUE TITLE
Support a release, install, and upgrade model that allows for stable and testing/edge

### ISSUE THREAD

**Issue by cjellick** [rancher/k3s#1307]
This is coming from @ibuildthecloud:

 we really need a someway to have stable and testing releases.  like v1.17.0 shouldn't be considered stable.
 not saying they are low quality, but there's got to be some bake in time.  i think conservative users should not be jumping on the .0 release the day it comes out.

**Comment by davidnuzik** [comment]
Closing - this is what channel server does. This has been tested.
