### ISSUE TITLE
k3s如何修改国内pause

### ISSUE THREAD

**Issue by still-L** [rancher/k3s#131]
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      coredns
    Optional:  false
  coredns-token-nwkqg:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  coredns-token-nwkqg
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  beta.kubernetes.io/os=linux
Tolerations:     CriticalAddonsOnly
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                     From                  Message
  ----     ------                  ----                    ----                  -------
  Warning  FailedCreatePodSandBox  30m (x177 over 2d17h)   kubelet, ceph-client  Failed create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox image "k8s.gcr.io/pause:3.1": failed to pull image "k8s.gcr.io/pause:3.1": failed to resolve image "k8s.gcr.io/pause:3.1": no available registry endpoint: failed to do request: Head https://k8s.gcr.io/v2/pause/manifests/3.1: dial tcp 64.233.189.82:443: i/o timeout
  Warning  FailedCreatePodSandBox  15m (x3485 over 2d22h)  kubelet, ceph-client  Failed create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox image "k8s.gcr.io/pause:3.1": failed to pull image "k8s.gcr.io/pause:3.1": failed to resolve image "k8s.gcr.io/pause:3.1": no available registry endpoint: failed to do request: Head https://k8s.gcr.io/v2/pause/manifests/3.1: dial tcp 74.125.204.82:443: i/o timeout
  Warning  FailedCreatePodSandBox  10m (x215 over 2d22h)   kubelet, ceph-client  Failed create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox image "k8s.gcr.io/pause:3.1": failed to pull image "k8s.gcr.io/pause:3.1": failed to resolve image "k8s.gcr.io/pause:3.1": no available registry endpoint: failed to do request: Head https://k8s.gcr.io/v2/pause/manifests/3.1: dial tcp 64.233.188.82:443: i/o timeout
  Warning  FailedCreatePodSandBox  7m53s (x3 over 9m18s)   kubelet, ceph-client  Failed create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox image "k8s.gcr.io/pause:3.1": failed to pull image "k8s.gcr.io/pause:3.1": failed to resolve image "k8s.gcr.io/pause:3.1": no available registry endpoint: failed to do request: Head https://k8s.gcr.io/v2/pause/manifests/3.1: dial tcp 64.233.188.82:443: i/o timeout
  Warning  FailedCreatePodSandBox  2m12s (x8 over 7m12s)   kubelet, ceph-client  Failed create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox image "k8s.gcr.io/pause:3.1": failed to pull image "k8s.gcr.io/pause:3.1": failed to resolve image "k8s.gcr.io/pause:3.1": no available registry endpoint: failed to do request: Head https://k8s.gcr.io/v2/pause/manifests/3.1: dial tcp 74.125.204.82:443: i/o timeout
  Warning  FailedCreatePodSandBox  1s (x3 over 89s)        kubelet, ceph-client  Failed create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox image "k8s.gcr.io/pause:3.1": failed to pull image "k8s.gcr.io/pause:3.1": failed to resolve image "k8s.gcr.io/pause:3.1": no available registry endpoint: failed to do request: Head https://k8s.gcr.io/v2/pause/manifests/3.1: dial tcp 74.125.203.82:443: i/o timeout

**Comment by ibuildthecloud** [comment]
Right now we do not have support for changing the image registries that k3s uses.  We will be adding support for that.  Unfortunately right now I believe gcr.io is not accessible in China.

**Comment by xiaosuiba** [comment]
You can not use a custom pause image currently. But you could try this way:
1. Download a containerd bin package from https://github.com/containerd/containerd/releases.
2. Use `ctr cri load` command to load pause images into every node, pay attention to the address of containerd.sock.

**Comment by still-L** [comment]
> Right now we do not have support for changing the image registries that k3s uses. We will be adding support for that. Unfortunately right now I believe gcr.io is not accessible in China.

ok 谢谢。

**Comment by still-L** [comment]
> 您目前无法使用自定义暂停图像。但你可以尝试这种方式：
> 
> 1. 从https://github.com/containerd/containerd/releases下载containerd bin包。
> 2. 使用`ctr cri load`命令将暂停图像加载到每个节点，注意containerd.sock的地址。

好的 我试试

**Comment by zergl** [comment]
Here is a useful trick to fix the issue alternatively in mainland of China:
```
$ docker pull mirrorgooglecontainers/pause:3.1
$ docker tag mirrorgooglecontainers/pause:3.1 k8s.gcr.io/pause:3.1
```

May it help.

**Comment by ntfs32** [comment]
Just have command get image from other registry, like `ctl pull notices/pause:3.1`, but it's have not like `ctl tag notices/pause:3.1 k8s.gcr.io/pause:3.1`,  what‘s next?
@zergl

**Comment by xiaosuiba** [comment]
On a machine with docker installed:
```
docker pull notices/pause:3.1
docker tag notices/pause:3.1 k8s.gcr.io/pause:3.1
docker save k8s.gcr.io/pause:3.1 -o pause.tar
```
On the machine with k3s installed:
```
ctr cri load pause.tar
```
@ntfs32 

Or, you can simply use docker instead of containerd.

**Comment by zergl** [comment]
> Just have command get image from other registry, like `ctl pull notices/pause:3.1`, but it's have not like `ctl tag notices/pause:3.1 k8s.gcr.io/pause:3.1`, what‘s next?
> @zergl

preparing k8s.gcr.io/pause:3.1 image locally before you run `kubectl run`  to start a new service on k3s.

**Comment by wbright** [comment]
> > Just have command get image from other registry, like `ctl pull notices/pause:3.1`, but it's have not like `ctl tag notices/pause:3.1 k8s.gcr.io/pause:3.1`, what‘s next?
> > @zergl
> 
> preparing k8s.gcr.io/pause:3.1 image locally before you run `kubectl run` to start a new service on k3s.
> 
> @ntfs32

in arm64 device, i installed containerd by "apt-get install" ,but that is a low version release(0.2.4),and the command "ctr"  has no topic for cri, so i cann,t load the "pause.rar" on my device

**Comment by lygstate** [comment]
@xiaosuiba 
```
ctr: failed to load image: rpc error: code = Unimplemented desc = unknown service api.v1.CRIPluginService
```

**Comment by xiaosuiba** [comment]
> @xiaosuiba
> 
> ```
> ctr: failed to load image: rpc error: code = Unimplemented desc = unknown service api.v1.CRIPluginService
> ```

Now with v0.2.0 you can **preload** all the images you need.

**Comment by carvendy** [comment]
Not effective

**Comment by lygstate** [comment]
@xiaosuiba How to preload? I am using v0.2.0 but failed

**Comment by lygstate** [comment]
almost works, except
```
/wd # kubectl describe pod helm-install-traefik-8n9kz  --namespace kube-system
Name:               helm-install-traefik-8n9kz
Namespace:          kube-system
Priority:           0
PriorityClassName:  <none>
Node:               rancher.lan/192.168.199.189
Start Time:         Mon, 18 Mar 2019 07:10:27 +0000
Labels:             controller-uid=e12b192d-494c-11e9-8051-7085c2394e50
                    helm.k3s.cattle.io/chart=traefik
                    job-name=helm-install-traefik
Annotations:        <none>
Status:             Running
IP:                 172.17.0.2
Controlled By:      Job/helm-install-traefik
Containers:
  helm:
    Container ID:  docker://47faa2e049d55756834f8888e32263782d6abc49e9b3ae7e0abe215eeb6c4a32
    Image:         rancher/klipper-helm:v0.1.3
    Image ID:      docker-pullable://rancher/klipper-helm@sha256:72e7bbbc6c71891dca7253e63b5bf88732aac1833dbad9ae3c32611009a63121
    Port:          <none>
    Host Port:     <none>
    Args:
      install
      --name
      traefik
      stable/traefik
      --set-string
      rbac.enabled=true
      --set-string
      ssl.enabled=true
    State:          Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 18 Mar 2019 07:10:56 +0000
      Finished:     Mon, 18 Mar 2019 07:11:06 +0000
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 18 Mar 2019 07:10:41 +0000
      Finished:     Mon, 18 Mar 2019 07:10:51 +0000
    Ready:          False
    Restart Count:  1
    Environment:
      NAME:         traefik
      VERSION:
      REPO:
      VALUES_HASH:  e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from helm-traefik-token-d5jkg (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  helm-traefik-token-d5jkg:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  helm-traefik-token-d5jkg
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                From                  Message
  ----     ------     ----               ----                  -------
  Normal   Scheduled  50s                default-scheduler     Successfully assigned kube-system/helm-install-traefik-8n9kz to rancher.lan
  Normal   Pulling    26s (x2 over 49s)  kubelet, rancher.lan  pulling image "rancher/klipper-helm:v0.1.3"
  Normal   Pulled     22s (x2 over 36s)  kubelet, rancher.lan  Successfully pulled image "rancher/klipper-helm:v0.1.3"
  Normal   Created    21s (x2 over 36s)  kubelet, rancher.lan  Created container
  Normal   Started    21s (x2 over 36s)  kubelet, rancher.lan  Started container
  Warning  BackOff    10s                kubelet, rancher.lan  Back-off restarting failed container
```

**Comment by lygstate** [comment]
I'd like to publish a script that works under rancheros
```
docker pull mirrorgooglecontainers/pause:3.1
docker tag mirrorgooglecontainers/pause:3.1 k8s.gcr.io/pause:3.1

docker pull mirrorgooglecontainers/kubernetes-dashboard-amd64:v1.10.1
docker tag mirrorgooglecontainers/kubernetes-dashboard-amd64:v1.10.1 k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1

# https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/

docker rm -f k3s
sudo rm -rf /var/lib/rancher/k3s
sudo rm -rf /etc/rancher/k3s
docker run -d --restart=always --privileged --name k3s --net=host --pid=host --ipc=host \
  -v /etc/rancher/k3s:/etc/rancher/k3s \
  -v /var/lib/rancher/k3s:/var/lib/rancher/k3s:rshared \
  -v /var/lib/docker:/var/lib/docker:rshared \
  -v /var/run:/var/run \
  -v ~:/wd \
  -v /run:/run \
  rancher/k3s:v0.2.0 server --docker
docker exec -it k3s /bin/sh


kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml
kubectl apply -f dashboard-adminuser.yaml
kubectl proxy --address='0.0.0.0' --accept-hosts='^.*$'

```

**Comment by lygstate** [comment]
The k8s helm still failed
```
[rancher@rancher ~]$ docker logs k8s_helm_helm-install-traefik-8n9kz_kube-system_e849eef4-494c-11e9-8051-7085c2394e50_120
+ export HELM_HOST=127.0.0.1:44134
+ HELM_HOST=127.0.0.1:44134
+ + helm init --client-onlytiller
--listen=127.0.0.1:44134 --storage=secret
[main] 2019/03/18 17:33:54 Starting Tiller v2.12.3 (tls=false)
[main] 2019/03/18 17:33:54 GRPC listening on 127.0.0.1:44134
[main] 2019/03/18 17:33:54 Probes listening on :44135
[main] 2019/03/18 17:33:54 Storage driver is Secret
[main] 2019/03/18 17:33:54 Max history per release is 0
Creating /root/.helm
Creating /root/.helm/repository
Creating /root/.helm/repository/cache
Creating /root/.helm/repository/local
Creating /root/.helm/plugins
Creating /root/.helm/starters
Creating /root/.helm/cache/archive
Creating /root/.helm/repository/repositories.yaml
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com
Error: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Get https://kubernetes-charts.storage.googleapis.com/index.yaml: dial tcp: lookup kubernetes-charts.storage.googleapis.com on 10.43.0.10:53: read udp 172.17.0.2:48865->10.43.0.10:53: i/o timeout
[rancher@rancher ~]$
```

**Comment by carvendy** [comment]
> > 您目前无法使用自定义暂停图像。但你可以尝试这种方式：
> > 
> > 1. 从[https://github.com/containerd/containerd/releases下载containerd](https://github.com/containerd/containerd/releases%E4%B8%8B%E8%BD%BDcontainerd) bin包。
> > 2. 使用`ctr cri load`命令将暂停图像加载到每个节点，注意containerd.sock的地址。
> 
> 好的 我试试

你解决了么?

**Comment by lygstate** [comment]
@carvendy 我目前不需要使用 containerd, 直接用容器部署没问题，只是 目前helm会失败

**Comment by erikwilson** [comment]
This should be fixed with the most recent airgap PR.

Related issues:
rancher/k3s/issues/172
rancher/k3s/issues/166

**Comment by zhanghongtong** [comment]
你们解决这个问题了么？我在树莓派上安装了docker，并且用`docker load`加载了 `k8s.gcr.io/pause:3.1`，然后我直接 `k3s agent`，看到k3s的输出的日志中依然有报错
```
E0328 17:38:08.488782   31924 pod_workers.go:190] Error syncing pod 0a480869-4ed2-11e9-8a06-b827eb86cc9d ("coredns-7748f7f6df-q8b7d_kube-system(0a480869-4ed2-11e9-8a06-b827eb86cc9d)"), skipping: failed to "CreatePodSandbox" for "coredns-7748f7f6df-q8b7d_kube-system(0a480869-4ed2-11e9-8a06-b827eb86cc9d)" with CreatePodSandboxError: "CreatePodSandbox for pod \"coredns-7748f7f6df-q8b7d_kube-system(0a480869-4ed2-11e9-8a06-b827eb86cc9d)\" failed: rpc error: code = Unknown desc = failed to get sandbox image \"k8s.gcr.io/pause:3.1\": failed to pull image \"k8s.gcr.io/pause:3.1\": failed to resolve image \"k8s.gcr.io/pause:3.1\": no available registry endpoint: failed to do request: Head https://k8s.gcr.io/v2/pause/manifests/3.1: dial tcp 74.125.203.82:443: i/o timeout"
```

**Comment by erikwilson** [comment]
It should work @zhanghongtong, please see how it was tested here: https://github.com/rancher/k3s/issues/172#issuecomment-476339625

Loading into docker may work but only if the `--docker` flag is also used. The preferred way is to copy the images to /var/lib/rancher/k3s/agent/images/.

**Comment by erikwilson** [comment]
@zhanghongtong `docker pull` and `docker save` are helpful for creating images, but we need to use containerd with the default install for loading. You can maybe also use `k3s crictl` but just placing the tar in the agent images directory is preferable. Closing, but if you continue to have issues feel free to re-open.

**Comment by flytreeleft** [comment]
If you are in [K3OS](https://github.com/rancher/k3os), you can get `ctr` via executing `docker run --rm -it -v "$(pwd)":/mnt alpine:edge sh -c 'apk add --no-cache containerd && cp /usr/bin/ctr /mnt/'` and copy it to all K3OS hosts.

**Comment by lianghuiyuan** [comment]
In K3OS, It have no docker deamon, so, How to execute `docker run ......`?
Follow I run `sudo k3s agent --server https://myserver:6443 --token ${NODE_TOKEN} --docker &`:
![image](https://user-images.githubusercontent.com/8090998/58384201-90951700-8011-11e9-9085-853b19fb989c.png)
so? Should I install docker daemon in K3OS? Or do something else?
It would be nice for fix my problem if I can rename the images in K3OS. But `crictl` can not rename the image.....

**Comment by j3ffyang** [comment]
@carvendy - on one K3S worker, I fixed this issue by 

`
docker pull sapcc/tiller:v2.14.3
docker tag sapcc/tiller:v2.14.3 gcr.io/kubernetes-helm/tiller:v2.14.3
docker save gcr.io/kubernetes-helm/tiller:v2.14.3 > ./tiller.tar
sudo cp tiller.tar /var/lib/rancher/k3s/agent/images/
sudo systemctl restart k3s-agent.service
`

**Comment by rafi** [comment]
The solution that works for me with k3s v1.0.1 and containerd. First, prepare a tar with images needed:
```sh
# On an existing cluster
kubectl get pods -A -o jsonpath="{.items[*].spec.containers[*].image}" \
  | tr -s '[[:space:]]' '\n' | sort | uniq > image-list.txt
```

The `image-list.txt` file should look something like this:
```
docker.io/postgres:10.11
docker.io/nginx:1.16
```

1. Ensure images on your pc: `xargs -n1 docker pull <<< "$(cat image-list.txt)"`
1. Create a tar archive: `docker save $(cat image-list.txt) -o my-images.tar`
1. Copy tar to k3s server's directory `/var/lib/rancher/k3s/agent/images/`
1. If k3s is already running, restart with `systemctl restart k3s.service`
1. If k3s is not installed, follow guide at https://rancher.com/docs/k3s/latest/en/installation/airgap/

Test with:
```sh
kubectl run my-test --image docker.io/postgres:10.11 --image-pull-policy=Never --expose --port 5432
kubectl get pod
# Clean test:
kubectl delete deploy/my-test svc/my-test
```
