### ISSUE TITLE
Upgrade to k8s 1.18.2

### ISSUE THREAD

**Issue by davidnuzik** [rancher/k3s#1320]
We discussed that we could rebase off of betas to make it easier for us to release.
There is an alpha of 1.18.2 out currently.

**Comment by unixfox** [comment]
1.18 is now out :)!

**Comment by davidnuzik** [comment]
PR: https://github.com/rancher/k3s/pull/1569

**Comment by davidnuzik** [comment]
Assigned to @ShylajaDevadiga for QA validation testing of v1.18.2 via RCs

**Comment by ShylajaDevadiga** [comment]
Validation of k3s v1.18.2-rc2+k3s1 is done on Ubuntu and CentOS.

**Comment by ShylajaDevadiga** [comment]
At a high level areas covered include:
Channel server functionality
Helm Controller PR verification
CoreDns fix
Single Node Install and Upgrade on Ubuntu
Multinode Install and Upgrade on Ubuntu using mysql, postgres external db
Single Node Install and Upgrade on CentOS
Multinode Install and Upgrade on CentOS using mysql, postgres external db
Airgap install on amd64 arch using tarball
Airgap install using Private Registry
Upgrade using traditional k3s method as well as SUC on Ubuntu
Import k3s Ubuntu/CentOS cluster into Rancher
Conformance test on Ubuntu using mysql backend.

**Comment by brandond** [comment]
External block storage is broken on 1.18.2. Ia that not part of the test suite? See https://github.com/rancher/k3s/issues/1682
