### ISSUE TITLE
All pods stays pending

### ISSUE THREAD

**Issue by tonsV2** [rancher/k3s#1346]
**Version:**
k3s version v1.17.0+k3s.1 (0f644650)

**Describe the bug**
I installed k3s as show on the frontpage.
`curl -sfL https://get.k3s.io | sh -`

Then I did the following
    - `export KUBECONFIG="~/.kube/config:/etc/rancher/k3s/k3s.yaml"`
    - `sudo chmod ugo+r /etc/rancher/k3s/k3s.yaml`
    - `kubectl get node`

The above command returns the following
```
NAME    STATUS   ROLES    AGE   VERSION
p5520   Ready    master   29h   v1.17.0+k3s.1
```
But when I do `kubectl get pods --all-namespaces` I get the following
```
NAMESPACE     NAME                                      READY   STATUS    RESTARTS   AGE
kube-system   helm-install-traefik-gnf67                0/1     Pending   0          29h
kube-system   local-path-provisioner-58fb86bdfd-xr66r   0/1     Pending   0          29h
kube-system   coredns-d798c9dd-cmxnw                    0/1     Pending   0          29h
kube-system   metrics-server-6d684c7b5-fxm5x            0/1     Pending   0          29h
```

I'm running Fedora 31 and Docker version 19.03.5. Please let me know if there's anymore I need to add.

**Comment by brandond** [comment]
What do the k3s service logs and or `kubectl describe pods -A` show?

**Comment by tonsV2** [comment]
All pods shows the same error message.

```
Name:           metrics-server-6d684c7b5-fxm5x
Namespace:      kube-system
Priority:       0
Node:           <none>
Labels:         k8s-app=metrics-server
                pod-template-hash=6d684c7b5
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/metrics-server-6d684c7b5
Containers:
  metrics-server:
    Image:        rancher/metrics-server:v0.3.6
    Port:         <none>
    Host Port:    <none>
    Environment:  <none>
    Mounts:
      /tmp from tmp-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from metrics-server-token-5cccm (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  tmp-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  metrics-server-token-5cccm:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  metrics-server-token-5cccm
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age        From               Message
  ----     ------            ----       ----               -------
  Warning  FailedScheduling  <unknown>  default-scheduler  0/1 nodes are available: 1 node(s) had taints that the pod didn't tolerate.
```

**Comment by tonsV2** [comment]
The output of `journalctl -u`

[k3s.log](https://github.com/rancher/k3s/files/4106691/k3s.log)

**Comment by erikwilson** [comment]
Also seeing this periodically with errors like:
```
E0129 15:35:24.245798   15046 node_controller.go:364] failed to set node provider id: failed to get instance ID from cloud provider: Failed to find node k3s: node "k3s" not found
E0129 15:35:24.245822   15046 node_controller.go:423] error fetching node by provider ID: unimplemented, and error by node name: Failed to find node k3s: node "k3s" not found
```
and node taint:
```
$ kubectl get node k3s -o yaml
apiVersion: v1
kind: Node
metadata:
  annotations:
    flannel.alpha.coreos.com/backend-data: '{"VtepMAC":"3a:4a:db:8e:d2:88"}'
    flannel.alpha.coreos.com/backend-type: vxlan
    flannel.alpha.coreos.com/kube-subnet-manager: "true"
    flannel.alpha.coreos.com/public-ip: 10.0.2.15
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2020-01-29T22:25:13Z"
  finalizers:
  - wrangler.cattle.io/node
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    k3s.io/hostname: k3s
    k3s.io/internal-ip: 10.0.2.15
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: k3s
    kubernetes.io/os: linux
    node-role.kubernetes.io/master: "true"
  name: k3s
  resourceVersion: "378"
  selfLink: /api/v1/nodes/k3s
  uid: 09532f5d-d4d3-475e-b8cb-a4cfd84fe0bf
spec:
  podCIDR: 10.42.0.0/24
  podCIDRs:
  - 10.42.0.0/24
  taints:
  - effect: NoSchedule
    key: node.cloudprovider.kubernetes.io/uninitialized
    value: "true"
```

**Comment by tullo** [comment]
Is there a firewall turned on?

**Comment by ajay-dua** [comment]
hey, even i have started facing the same issue and its not  only with the latest version  v1.17.x but seems with other  versions as well i checked installing v1.0.1 and result same.. screen shot below..
 
![k3s_v1 0 1](https://user-images.githubusercontent.com/13228170/73489821-469ad700-43d1-11ea-98f4-4db4e2a575b7.PNG)

**Comment by tonsV2** [comment]
While looking for something unrelated in my logs I discovered the following.

```
Jan 31 23:18:49 p5520 k3s[1463]: I0131 23:18:49.319958    1463 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
Jan 31 23:19:03 p5520 k3s[1463]: I0131 23:19:03.461553    1463 image_gc_manager.go:300] [imageGCManager]: Disk usage on image filesystem is at 90% which is over the high threshold (85%). Trying to free 95408195>
Jan 31 23:19:03 p5520 k3s[1463]: E0131 23:19:03.467008    1463 kubelet.go:1298] Image garbage collection failed multiple times in a row: failed to garbage collect required amount of images. Wanted to free 95408>
Jan 31 23:19:49 p5520 k3s[1463]: I0131 23:19:49.326495    1463 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
Jan 31 23:20:49 p5520 k3s[1463]: I0131 23:20:49.336288    1463 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
```

The disk in question had more than a 100 GB free and I assumed it was more than enough. But after seeing the above error message and deleting enough to get the disk usage down to 78% my pods are starting.

**Comment by ajay-dua** [comment]
> While looking for something unrelated in my logs I discovered the following.
> 
> ```
> Jan 31 23:18:49 p5520 k3s[1463]: I0131 23:18:49.319958    1463 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
> Jan 31 23:19:03 p5520 k3s[1463]: I0131 23:19:03.461553    1463 image_gc_manager.go:300] [imageGCManager]: Disk usage on image filesystem is at 90% which is over the high threshold (85%). Trying to free 95408195>
> Jan 31 23:19:03 p5520 k3s[1463]: E0131 23:19:03.467008    1463 kubelet.go:1298] Image garbage collection failed multiple times in a row: failed to garbage collect required amount of images. Wanted to free 95408>
> Jan 31 23:19:49 p5520 k3s[1463]: I0131 23:19:49.326495    1463 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
> Jan 31 23:20:49 p5520 k3s[1463]: I0131 23:20:49.336288    1463 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
> ```
> 
> The disk in question had more than a 100 GB free and I assumed it was more than enough. But after seeing the above error message and deleting enough to get the disk usage down to 78% my pods are starting.

thats the news then would try cleaning disk and see if it works for me.

**Comment by ajay-dua** [comment]
$> sudo iptables --list
$>k3s check-config

for me firewall was a culprit and for some reason docker snap as it is known issue as well.
its started working for me as soon as change the state to inactive and restart Linux box it worked after few restarts..

if its a same issue at your end you can check with iptables list as for me KUBE-SERVICES, KUBE-EXTERNAL-SERVICES and KUBE-FIREWALL all were missing.

if its happening for some other reason you can check with running "k3s check-config"

P.S could be on k3s side as well something they changed wanting us to figure out or migrate to RKE ;)

**Comment by David-Igou** [comment]
I did a cluster deployment earlier with the latest version and had the same taint. You can just delete the taint via a kubectl edit node and pods will schedule. I was told in the Rancher slack "When the kubelet is started with “external” cloud provider, this taint is set on a node to mark it as unusable. After a controller from the cloud-controller-manager initializes this node, the kubelet removes this taint."

**Comment by erikwilson** [comment]
There are multiple issues going on in this thread @David-Igou, the original issue that was reported looks due to free disk space and has been resolved, so this issue can probably be closed.

The error that I shared regarding the cloud provider is a different issue, and was triggered while using the built-in cloud controller.

**Comment by andyjeffries** [comment]
I get the same issue with a 1.17.2 k3s cluster. In my case it's not a disk space issue:

```
/dev/vda1        49G  1.2G   48G   3% /
```

The cloud provider/taints issue, is that being tracked somewhere else? Any simple steps to follow? (I would have thought the k3s clusters should come up automatically fine as previous ones have, rather than needing a cloud controller to do something afterwards?)

**Comment by andyjeffries** [comment]
I edited a node and removed the taint and the pods started. I guess I could do the same thing with `--disable-cloud-controller`? Should this be the default though - feels weird for such an easy to use system that it now brings a cluster up in a non-functioning state.

**Comment by erikwilson** [comment]
Closing this issue as it appears the original problem was due to not enough disk space. 

Please re-open if you think this is an error @tonsV2.

For other people having issues please describe an affected pod and node to see if there is a legitimate reason for the pending state, and file a new issue if appropriate.

**Comment by EvanCarroll** [comment]
It would be nice to know _how_ to change this usage requirement. I don't need 100 gigabytes to run Wordpress on k3s. I don't see this in this ticket. On other k3s distributions they seem to edit a `kublet/config.yaml` but I don't see that file on k3s.

https://devops.stackexchange.com/questions/16070/where-does-k3s-store-its-var-lib-kubelet-config-yaml-file
