### ISSUE TITLE
docker-compose k3s kubectl doesn't work on either server or agent

### ISSUE THREAD

**Issue by SamD** [rancher/k3s#1349]
**Version:**
k3s version v1.17.0+k3s.1 (0f644650)

**Describe the bug**

This is using the docker-compose file provided for the specified version: https://github.com/rancher/k3s/blob/v1.17.0%2Bk3s.1/docker-compose.yml

`k3s kubectl` doesn't work on either master or agent

**To Reproduce**

```
export K3S_TOKEN=${RANDOM}${RANDOM}${RANDOM}
export K3S_VERSION=v1.17.0-k3s.1
docker compose -f ./k3s-docker-compose.yml pull
docker compose -f ./k3s-docker-compose.yml up
docker-compose -f ./k3s-docker-compose.yml exec server /bin/sh
/ # k3s kubectl get node
Error: unknown command "kubectl" for "kubectl"
Run 'kubectl --help' for usage.
unknown command "kubectl" for "kubectl"
```
**Expected behavior**

`k3s kubectl get node` works
**Additional context**

`kubectl get node` however does work **but** only on the server
```
# server
/ # kubectl get node
NAME           STATUS   ROLES    AGE   VERSION
77166a6d2259   Ready    master   21m   v1.17.0+k3s.1
3b5a23b46d06   Ready    <none>   21m   v1.17.0+k3s.1

# agent 
/ # kubectl get node
The connection to the server localhost:8080 was refused - did you specify the right host or port?

```

**Comment by SamD** [comment]
Ok so I just noticed the generated `kubeconfig.yaml` locally after the `dock-compose up` , this works fine but would like to be able to be able to carry out the ops on either the master worker nodes

**Comment by erikwilson** [comment]
I can understand the desire to have admin access from worker nodes, but from a security perspective it is probably better to limit admin kubeconfig generation to master nodes.

**Comment by SamD** [comment]
ok thanks so kuebectl works fine the k3s kubectl gives that error
just reporting that since its specified in the docs that it should work

in any case I'll close this issue and leave the other up to your discretion
