### ISSUE TITLE
Possibility of dynamic change between single node and multi-nodes cluster

### ISSUE THREAD

**Issue by avarf** [rancher/k3s#1360]
Hi,

I have a question regarding the number of nodes for K3s.Can I start K3s as a single node cluster and later add nodes to dynamically and make it multi-host (one master and 2 workers for example)? Or I need to tear down the single node cluster and set it up again as a multi-node?

**Comment by brandond** [comment]
As far as I can tell, you should be able to add additional servers (masters) at any time later if you start the first with --init-cluster to use dqlite, or with an external datastore. The default sqlite datastore is single-master only.

**Comment by davidnuzik** [comment]
Also keep in mind dqlite uses the raft algorithm and so you should have 1 or 3 or 5 (for example) masters.
Please let us know if there are any further questions.
