### ISSUE TITLE
some pods in Error status after 'k3s kubectl scale'

### ISSUE THREAD

**Issue by yechnlin** [rancher/k3s#137]
## H/W env
master: ubuntu amd64(skylake)
slave: ubuntu arm64 (raspberry pi 3)

## setup
master:
```
    root@ye:/home/ye# k3s server
```
slave:
```
    root@ubuntu:/home/ubuntu# k3s-arm64 agent -s ${SERVER} -t ${TOKEN} --docker
```

## test procedures
```
root@ye:/home/ye# k3s kubectl run hello-k3s --image=yechenglin/hello-k8s:v1.0.0-arm64
```
```
root@ye:/home/ye# k3s kubectl get pods
NAME                                    READY   STATUS    RESTARTS   AGE
hello-k3s-64b7c54c5f-tjhs2   1/1           Running    0                  131m
```
```
root@ye:/home/ye# k3s kubectl scale --replicas=5 deployment/hello-k3s
deployment.extensions/hello-k3s scaled
```
```
root@ye:/home/ye# k3s kubectl get pods
NAME                                    READY   STATUS    RESTARTS   AGE
hello-k3s-64b7c54c5f-dqltk   0/1          Error          3                   47s
hello-k3s-64b7c54c5f-jtchc   0/1          Error          3                   47s
hello-k3s-64b7c54c5f-td9t9   1/1         Running     0                    47s
hello-k3s-64b7c54c5f-tjhs2   1/1         Running     0                   132m
hello-k3s-64b7c54c5f-wclcx   0/1        Error          3                    47s
```

## Issue
It seems that a haft of pods are in Error status only if the 'replicas' value greater than one.

**Comment by ibuildthecloud** [comment]
There's quite a few things that could fail there.  Did you try running `kubectl describe pod XXXX` on one of the failed pods?  Might help to see what the Error is.

**Comment by yechnlin** [comment]
Thanks for you feedback.

[Log of 'kubectl describe pod xxx']
the failed pods log:
Events:
  Type     Reason                  Age                   From               Message
  ----     ------                  ----                  ----               -------
  Normal   Scheduled               4m34s                 default-scheduler  Successfully assigned default/hello-k3s-5f679b84f9-6glwv to ye
  Warning  FailedCreatePodSandBox  12s (x21 over 4m34s)  kubelet, ye       Failed create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox image "k8s.gcr.io/pause:3.1": failed to pull image "k8s.gcr.io/pause:3.1": failed to resolve image "k8s.gcr.io/pause:3.1": no available registry endpoint: failed to do request: Head https://k8s.gcr.io/v2/pause/manifests/3.1: proxyconnect tcp: tls: oversized record received with length 20527

the successful pods log:
Events:
  Type    Reason     Age    From               Message
  ----    ------     ----   ----               -------
  Normal  Pulled     11m    kubelet, raspi    Container image "yechenglin/hello-k8s:v1.0.0-arm64" already present on machine
  Normal  Created    11m    kubelet, raspi    Created container
  Normal  Started    11m    kubelet, raspi    Started container
  Normal  Scheduled  6m37s  default-scheduler  Successfully assigned default/hello-k3s-5f679b84f9-5m72n to raspi

and at slave side, log showed:
I0305 10:36:24.064710    7150 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "default-token-7w9rk" (UniqueName: "kubernetes.io/secret/0b97f808-3ef0-11e9-97fa-3497f6a0a5d9-default-token-7w9rk") pod "hello-k3s-64b7c54c5f-x76dc" (UID: "0b97f808-3ef0-11e9-97fa-3497f6a0a5d9") 


[Analysis:]
From log showed, after 'root@ye:/home/ye# k3s kubectl scale --replicas=5 deployment/hello-k3s', it seems that one replicate pod was deployed into slave, and others were deployed into master by default-scheduler.

**Comment by yechnlin** [comment]
After I unset https_proxy environment at master side, error log is different, following,
---
Events:
  Type     Reason     Age               From               Message
  Normal   Scheduled  2m13s             default-scheduler  Successfully assigned default/hello-k3s-64b7c54c5f-gxgvq to bdk
  Normal   Pulling    2m12s             kubelet, ye       pulling image "yechenglin/hello-k8s:v1.0.0-arm64"
  Normal   Pulled     20s               kubelet, ye       Successfully pulled image "yechenglin/hello-k8s:v1.0.0-arm64"
  Normal   Created    4s (x3 over 20s)  kubelet, ye       Created container
  Normal   Pulled     4s (x2 over 18s)  kubelet, ye       Container image "yechenglin/hello-k8s:v1.0.0-arm64" already present on machine
  Normal   Started    3s (x3 over 19s)  kubelet, ye       Started container
  Warning  BackOff    2s (x3 over 17s)  kubelet, ye       Back-off restarting failed container
---

BTW
error log same as coredns and helm

**Comment by yechnlin** [comment]
From log of the failed pods, it seems that the proxy is the root cause, so I "unset https_proxy", it worked well, however, another error of pod start, 
```
Events:
  Type     Reason     Age                 From               Message
  Normal   Scheduled  2m5s                default-scheduler  Successfully assigned default/hello-k3s-64b7c54c5f-b7xh5 to bdk
  Normal   Pulled     40s (x5 over 2m4s)  kubelet, ye       Container image "yechenglin/hello-k8s:v1.0.0-arm64" already present on machine
  Normal   Created    40s (x5 over 2m4s)  kubelet, ye       Created container
  Normal   Started    39s (x5 over 2m4s)  kubelet, ye       Started container
  Warning  BackOff    1s (x10 over 2m2s)  kubelet, ye       Back-off restarting failed container
```
the root cause is that the image of hello-k8s is arm64 architecture, however, it was deployed into master on amd64.

So, I want to know, can we specify the node which we want to deploy our pods?

**Comment by iluminae** [comment]
@yechnlin use `NodeSelectors` on your deployments, `beta.kubernetes.io/arch=amd64` for example. All nodes are given that label that matches their arch. [see here](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector)

Also look into [taints and tolorations](https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/).

**Comment by yechnlin** [comment]
@iluminae thanks for your help, it's really helpful for me.
