### ISSUE TITLE
install.sh: Add the INSTALL_K3S_MIRROR variable to increase k3s binary file download speed

### ISSUE THREAD

**Issue by xiaoluhong** [rancher/k3s#1374]
It is difficult for Chinese users to download the K3S binaries without a VPN. therefore we created a download source mirror hosted on aliyun oss, for speeding up file downloads and improving the user experience.

PR: https://github.com/rancher/k3s/pull/1373

**Comment by davidnuzik** [comment]
The associated PR was closed https://github.com/rancher/k3s/pull/1373 - waiting to hear reason why.

**Comment by xiaoluhong** [comment]
Hi, I have resubmitted PR: https://github.com/rancher/k3s/pull/1700. Thank you.
