### ISSUE TITLE
Update to 1.16.6 kubernetes

### ISSUE THREAD

**Issue by davidnuzik** [rancher/k3s#1375]
v1.16.6 is out as of 1/21/20. (v1.16.7 is currently in beta, should it be released by the time we get around to this, then of course use latest v1.16 patch version)

Based on discussion with Craig; start releasing as version in alignment with k8s ver (v1.16.6+k3s1)

**Comment by ShylajaDevadiga** [comment]
Verified k3s version v1.16.7-rc1+k3s1 with k8s version v1.16.7
