### ISSUE TITLE
Remove no-deploy flag due to new disable flag

### ISSUE THREAD

**Issue by davidnuzik** [rancher/k3s#1382]
With our new addition of the disable flag the no-deploy flag is now deprecated. In a release or two we should consider removing the no-deploy flag from the CLI. Perhaps first hide in CLI but don't remove functionality. Then perhaps a release after remove functionality too.

**Comment by stuartpb** [comment]
I think the no-deploy behavior should be kept, for environments where the default component *may or may not* still exist, but either way, the server *should not modify it*. Perhaps a `--no-deploy=all` for "don't attempt to adjust my service configuration in any way"?

**Comment by stuartpb** [comment]
Or, heck, looking [a little closer at the implementation](https://github.com/rancher/k3s/blob/eb96a437e1d82428a7c190ca05be360915fa395f/manifests/coredns.yaml), you still need `no-deploy` if you just want to *configure* the service k3s uses - not specifying it will apply the default configuration over your own, and `disable` will remove it.
