### ISSUE TITLE
k3s kubectl -n <blah> get all takes lot longer with the newer 1.17.2 version

### ISSUE THREAD

**Issue by samirsss** [rancher/k3s#1384]
**Version:**
v1.17.2+k3s1 - default configuration

**Describe the bug**
We were on 1.0.0 version of k3s and just upgraded to 1.17.2 version yesterday and see that the k3s kubectl -n <blah> get all command takes a lot longer to display the ingress/node/service details.

**To Reproduce**
Just execute k3s kubectl -n <blah> get all  with a different namespace (not kube-system or kube) with some pods/services/ingress defined. This was on a single node cluster.

**Expected behavior**
with 1.0.0 this command used to be ~1-2 seconds and now it takes over a minute

**Actual behavior**

**Additional context**
admin@TPVM:~$ time k3s kubectl -n efa get all
NAME                                       READY   STATUS    RESTARTS   AGE
pod/efa-api-docs-6498d5cf5c-sm5rl          1/1     Running   0          5h32m
pod/godb-service-564d7bdfdd-xk827          1/1     Running   0          5h32m
pod/rabbitmq-0                             1/1     Running   0          5h32m
pod/goinventory-service-5c8cfd9d8b-qmdrk   1/1     Running   1          5h32m
pod/govcenter-service-6d59ddbf8b-b4m8h     1/1     Running   4          5h32m
pod/gotenant-service-7dbbfd77db-rmjnk      1/1     Running   1          5h32m
pod/goopenstack-service-5dc4b688dd-zsxcg   1/1     Running   4          5h32m
pod/gofabric-service-7c7f7dfb58-2rdb8      1/1     Running   2          5h32m
pod/gohyperv-service-8568f5bb44-dzkfw      1/1     Running   5          5h32m

NAME                          TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                          AGE
service/gofabric-service      ClusterIP   10.43.28.178    <none>        8081/TCP                         5h32m
service/goinventory-service   ClusterIP   10.43.245.157   <none>        8082/TCP                         5h32m
service/gotenant-service      ClusterIP   10.43.223.72    <none>        8083/TCP                         5h32m
service/efa-api-docs          ClusterIP   10.43.14.132    <none>        80/TCP                           5h32m
service/rabbitmq              NodePort    10.43.27.103    <none>        15672:31672/TCP,5672:30672/TCP   5h32m
service/db-service            NodePort    10.43.112.220   <none>        5432:30432/TCP                   5h32m
service/goopenstack-service   NodePort    10.43.88.55     <none>        8085:30085/TCP                   5h32m
service/govcenter-service     ClusterIP   10.43.207.206   <none>        8086/TCP                         5h32m
service/gohyperv-service      ClusterIP   10.43.19.139    <none>        8087/TCP                         5h32m

NAME                                  READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/efa-api-docs          1/1     1            1           5h32m
deployment.apps/godb-service          1/1     1            1           5h32m
deployment.apps/goinventory-service   1/1     1            1           5h32m
deployment.apps/govcenter-service     1/1     1            1           5h32m
deployment.apps/gotenant-service      1/1     1            1           5h32m
deployment.apps/goopenstack-service   1/1     1            1           5h32m
deployment.apps/gofabric-service      1/1     1            1           5h32m
deployment.apps/gohyperv-service      1/1     1            1           5h32m

NAME                                             DESIRED   CURRENT   READY   AGE
replicaset.apps/efa-api-docs-6498d5cf5c          1         1         1       5h32m
replicaset.apps/godb-service-564d7bdfdd          1         1         1       5h32m
replicaset.apps/goinventory-service-5c8cfd9d8b   1         1         1       5h32m
replicaset.apps/govcenter-service-6d59ddbf8b     1         1         1       5h32m
replicaset.apps/gotenant-service-7dbbfd77db      1         1         1       5h32m
replicaset.apps/goopenstack-service-5dc4b688dd   1         1         1       5h32m
replicaset.apps/gofabric-service-7c7f7dfb58      1         1         1       5h32m
replicaset.apps/gohyperv-service-8568f5bb44      1         1         1       5h32m

NAME                        READY   AGE
statefulset.apps/rabbitmq   1/1     5h32m

real	1m4.411s

**Comment by davidnuzik** [comment]
Without more info this can be a bit difficult to troubleshoot. Does this query happen on the same K3s server, and if so what is are the specifications of the server? No memory/cpu/etc pressure? 
If possible, are you able to reproduce the issue?
The K3s server logs could be helpful around when the kubectl query is executed.

**Comment by samirsss** [comment]
This is on an Lenovo M5 server with 12 cores and 32 GB Memory (Just a dev setup). Eventually this wil be running on a small VM with 2 vCPUS and 4 Gb Memory. 

I did look at CPU utilization and it maxed out at 9-10% utilization.

The query was on the same server where k3s was installed.

Will try to get the k3s logs and get it back  to you.

**Comment by samirsss** [comment]
Hi Any updates on this one? I've upgraded to 1.17.3 and still see it taking over a minute

**Comment by samirsss** [comment]
Here's some data

extreme@tpvm:~$ date
Wed Apr  8 20:19:44 UTC 2020
extreme@tpvm:~$ time k3s kubectl -n efa get all
NAME                                          READY   STATUS    RESTARTS   AGE
pod/efa-api-docs-55c97cbdf-7qbtg              1/1     Running   0          97m
pod/gonotification-service-6cc76f46f6-4t9xr   1/1     Running   0          97m
pod/goraslog-service-595b8c94bd-kqgd7         1/1     Running   5          97m
pod/gorbac-service-7dc96bf99f-f5zr2           1/1     Running   5          97m
pod/goauth-service-7b68fccc5c-fqlp9           1/1     Running   5          97m
pod/goopenstack-service-c9c75b46b-lzr7s       1/1     Running   5          97m
pod/govcenter-service-9dbcbb95d-x7xg9         1/1     Running   5          97m
pod/godb-service-54c857fdd-hbkpn              1/1     Running   1          97m
pod/rabbitmq-lfc7m                            1/1     Running   1          97m
pod/gotenant-service-57f79bcdf4-rngsl         1/1     Running   1          97m
pod/goinventory-service-57fbf86cd6-p5zh2      1/1     Running   1          97m
pod/gohyperv-service-689c4d7bb-plxjt          1/1     Running   7          97m
pod/gofabric-service-59c869c658-qq4bb         1/1     Running   3          97m

NAME                             TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                          AGE
service/gofabric-service         ClusterIP   10.43.193.176   <none>        8081/TCP                         97m
service/goinventory-service      ClusterIP   10.43.187.187   <none>        8082/TCP                         97m
service/gotenant-service         ClusterIP   10.43.79.50     <none>        8083/TCP                         97m
service/efa-api-docs             ClusterIP   10.43.94.48     <none>        80/TCP                           97m
service/goraslog-service         ClusterIP   10.43.44.71     <none>        514/TCP,514/UDP                  97m
service/gonotification-service   ClusterIP   10.43.212.41    <none>        8088/TCP                         97m
service/goauth-service           ClusterIP   10.43.187.55    <none>        8080/TCP                         97m
service/gorbac-service           ClusterIP   10.43.8.34      <none>        8089/TCP                         97m
service/rabbitmq                 NodePort    10.43.131.223   <none>        15672:31672/TCP,5672:30672/TCP   97m
service/db-service               NodePort    10.43.125.220   <none>        5432:30432/TCP                   97m
service/goopenstack-service      NodePort    10.43.230.41    <none>        8085:30085/TCP                   97m
service/govcenter-service        ClusterIP   10.43.13.221    <none>        8086/TCP                         97m
service/gohyperv-service         ClusterIP   10.43.41.13     <none>        8087/TCP                         97m

NAME                      DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/rabbitmq   1         1         1       1            1           <none>          97m

NAME                                     READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/efa-api-docs             1/1     1            1           97m
deployment.apps/gonotification-service   1/1     1            1           97m
deployment.apps/goraslog-service         1/1     1            1           97m
deployment.apps/gorbac-service           1/1     1            1           97m
deployment.apps/goauth-service           1/1     1            1           97m
deployment.apps/goopenstack-service      1/1     1            1           97m
deployment.apps/govcenter-service        1/1     1            1           97m
deployment.apps/godb-service             1/1     1            1           97m
deployment.apps/gotenant-service         1/1     1            1           97m
deployment.apps/goinventory-service      1/1     1            1           97m
deployment.apps/gohyperv-service         1/1     1            1           97m
deployment.apps/gofabric-service         1/1     1            1           97m

NAME                                                DESIRED   CURRENT   READY   AGE
replicaset.apps/efa-api-docs-55c97cbdf              1         1         1       97m
replicaset.apps/gonotification-service-6cc76f46f6   1         1         1       97m
replicaset.apps/goraslog-service-595b8c94bd         1         1         1       97m
replicaset.apps/gorbac-service-7dc96bf99f           1         1         1       97m
replicaset.apps/goauth-service-7b68fccc5c           1         1         1       97m
replicaset.apps/goopenstack-service-c9c75b46b       1         1         1       97m
replicaset.apps/govcenter-service-9dbcbb95d         1         1         1       97m
replicaset.apps/godb-service-54c857fdd              1         1         1       97m
replicaset.apps/gotenant-service-57f79bcdf4         1         1         1       97m
replicaset.apps/goinventory-service-57fbf86cd6      1         1         1       97m
replicaset.apps/gohyperv-service-689c4d7bb          1         1         1       97m
replicaset.apps/gofabric-service-59c869c658         1         1         1       97m

real	1m4.454s
user	0m1.233s
sys	0m0.403s

output from journalctl -f -u k3s

Apr 08 20:19:30 tpvm k3s[5682]: I0408 20:19:30.922943    5682 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
Apr 08 20:19:46 tpvm k3s[5682]: I0408 20:19:46.629298    5682 log.go:172] http: TLS handshake error from 127.0.0.1:35208: EOF
Apr 08 20:20:30 tpvm k3s[5682]: I0408 20:20:30.929622    5682 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
Apr 08 20:21:30 tpvm k3s[5682]: I0408 20:21:30.936140    5682 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io

**Comment by samirsss** [comment]
Just to make sure there is some more data:
On 1.16.3 for a similar deployment here are the stats. It takes about 1.5 second vs about 65 seconds to fetch the same data on 1.17.3 k3s. 

admin@TPVM:~$ k3s kubectl get nodes
NAME   STATUS   ROLES    AGE   VERSION
tpvm   Ready    master   26m   v1.16.3-k3s.2

admin@TPVM:~$ time k3s kubectl -n efa get all
NAME                                       READY   STATUS    RESTARTS   AGE
pod/efa-api-docs-6bb5dbcc74-6j9g8          1/1     Running   1          24m
pod/godb-service-5b4f9bbd6c-xmjzq          1/1     Running   1          24m
pod/goopenstack-service-554c57548f-qsccl   1/1     Running   6          24m
pod/rabbitmq-0                             1/1     Running   1          24m
pod/govcenter-service-f6b49d9b9-72vdq      1/1     Running   9          24m
pod/gotenant-service-55fd8889d8-5fsb2      1/1     Running   4          24m
pod/gofabric-service-69d8995fc6-pj5bc      1/1     Running   4          24m
pod/gohyperv-service-854654f6b9-qdxmb      1/1     Running   9          24m
pod/goinventory-service-59d9b798d8-rmfbv   1/1     Running   4          24m

NAME                          TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                          AGE
service/gofabric-service      ClusterIP   10.43.143.199   <none>        8081/TCP                         24m
service/goinventory-service   ClusterIP   10.43.153.167   <none>        8082/TCP                         24m
service/gotenant-service      ClusterIP   10.43.235.175   <none>        8083/TCP                         24m
service/efa-api-docs          ClusterIP   10.43.94.212    <none>        80/TCP                           24m
service/rabbitmq              NodePort    10.43.112.36    <none>        15672:31672/TCP,5672:30672/TCP   24m
service/db-service            NodePort    10.43.47.174    <none>        5432:30432/TCP                   24m
service/goopenstack-service   NodePort    10.43.109.91    <none>        8085:30085/TCP                   24m
service/govcenter-service     ClusterIP   10.43.139.32    <none>        8086/TCP                         24m
service/gohyperv-service      ClusterIP   10.43.95.164    <none>        8087/TCP                         24m

NAME                                  READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/efa-api-docs          1/1     1            1           24m
deployment.apps/godb-service          1/1     1            1           24m
deployment.apps/goopenstack-service   1/1     1            1           24m
deployment.apps/govcenter-service     1/1     1            1           24m
deployment.apps/gotenant-service      1/1     1            1           24m
deployment.apps/gofabric-service      1/1     1            1           24m
deployment.apps/gohyperv-service      1/1     1            1           24m
deployment.apps/goinventory-service   1/1     1            1           24m

NAME                                             DESIRED   CURRENT   READY   AGE
replicaset.apps/efa-api-docs-6bb5dbcc74          1         1         1       24m
replicaset.apps/godb-service-5b4f9bbd6c          1         1         1       24m
replicaset.apps/goopenstack-service-554c57548f   1         1         1       24m
replicaset.apps/govcenter-service-f6b49d9b9      1         1         1       24m
replicaset.apps/gotenant-service-55fd8889d8      1         1         1       24m
replicaset.apps/gofabric-service-69d8995fc6      1         1         1       24m
replicaset.apps/gohyperv-service-854654f6b9      1         1         1       24m
replicaset.apps/goinventory-service-59d9b798d8   1         1         1       24m

NAME                        READY   AGE
statefulset.apps/rabbitmq   1/1     24m

**real	0m1.853s**
user	0m0.995s
sys	0m0.277s

**Comment by brandond** [comment]
Is it slow every time, or just the first time? I noticed that the API discovery step got much slower at some point. API discovery is cached, so it should only happen when you haven't interacted with the system for a while.

This is just anecdotal, but after switching from kine to etcd, it's much faster.

First run - empty cache:
```
(python37) brandond@seago:~$ time k3s kubectl -n kube-system get all 1>/dev/null

real    0m3.296s
user    0m0.383s
sys     0m0.109s
```

Second run - populated cache:
```
(python37) brandond@seago:~$ time k3s kubectl -n kube-system get all 1>/dev/null

real    0m0.277s
user    0m0.293s
sys     0m0.047s
```

**Comment by samirsss** [comment]
Thanks Brandon - 

We see it consistently even when we've had a bunch of other k3s kubectl calls (like to get pods and nodes etc). The k3s kubectl -n <namespace> get all call is the only one which takes some time.

Before rm -rf  on ~/.kube/cache

real	1m4.702s
user	0m1.184s
sys	0m0.458s

After sudo rm -rf ~/.kube/cache

real	1m4.484s
user	0m1.215s
sys	0m0.405s

So there isnt much of a difference. Seems like between 1.16.3 and 1.17.3 there were some major delays introduced in the api

**Comment by PhilippeVienne** [comment]
Hello, I am having same issue on `kubectl get all`, I have some logs to add:

```
philippe@ds-1 ±develop⚡ » kubectl get all
I0424 20:59:14.830486   13043 request.go:621] Throttling request took 1.071843378s, request: GET:https://localhost:6443/apis/autoscaling/v1?timeout=32s
I0424 20:59:25.030454   13043 request.go:621] Throttling request took 1.385597179s, request: GET:https://localhost:6443/apis/authorization.k8s.io/v1?timeout=32s
I0424 20:59:35.230391   13043 request.go:621] Throttling request took 3.985600839s, request: GET:https://localhost:6443/apis/rbac.authorization.k8s.io/v1beta1?timeout=32s
I0424 20:59:45.430396   13043 request.go:621] Throttling request took 6.589731191s, request: GET:https://localhost:6443/apis/apiextensions.k8s.io/v1?timeout=32s
I0424 20:59:55.630482   13043 request.go:621] Throttling request took 1.589033238s, request: GET:https://localhost:6443/apis/apps/v1?timeout=32s
I0424 21:00:05.830305   13043 request.go:621] Throttling request took 4.185046898s, request: GET:https://localhost:6443/apis/authentication.k8s.io/v1beta1?timeout=32s
I0424 21:00:16.030287   13043 request.go:621] Throttling request took 6.784971184s, request: GET:https://localhost:6443/apis/scheduling.k8s.io/v1?timeout=32s
NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
service/kubernetes   ClusterIP   10.43.0.1    <none>        443/TCP   2m46s
philippe@ds-1 ±develop⚡ » kubectl get all
I0424 21:00:30.254350   13413 request.go:621] Throttling request took 1.12821134s, request: GET:https://localhost:6443/apis/admissionregistration.k8s.io/v1?timeout=32s
I0424 21:00:40.254358   13413 request.go:621] Throttling request took 1.586168659s, request: GET:https://localhost:6443/api/v1?timeout=32s
I0424 21:00:50.454174   13413 request.go:621] Throttling request took 4.18558743s, request: GET:https://localhost:6443/apis/authorization.k8s.io/v1?timeout=32s
I0424 21:01:00.454217   13413 request.go:621] Throttling request took 6.583598129s, request: GET:https://localhost:6443/apis/scheduling.k8s.io/v1beta1?timeout=32s
I0424 21:01:10.654152   13413 request.go:621] Throttling request took 1.585603797s, request: GET:https://localhost:6443/apis/networking.k8s.io/v1beta1?timeout=32s
I0424 21:01:20.854959   13413 request.go:621] Throttling request took 4.185918254s, request: GET:https://localhost:6443/apis/storage.k8s.io/v1beta1?timeout=32s
I0424 21:01:31.053936   13413 request.go:621] Throttling request took 6.784308876s, request: GET:https://localhost:6443/apis/authentication.k8s.io/v1?timeout=32s
NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
service/kubernetes   ClusterIP   10.43.0.1    <none>        443/TCP   4m1s

```

**Comment by brandond** [comment]
What does the cpu/memory/disk load look like? If you build out the same workload using a single-node etcd backend, does it exhibit the same behavior?

**Comment by samirsss** [comment]
@brandond my setup was on a single-node sqlite based backend (air gapped k3s installation) and i dont see CPU or memory spikes.

**Comment by samirsss** [comment]
with 1.18.2 this issue is fixed. Please close the issue now. Thanks!

**Comment by davidnuzik** [comment]
Closing @PhilippeVienne you mentioned an issue as well. If you think it's not a hardware/resourcing issue and still see the problem let us know. We can re-open the issue if necessary.
