### ISSUE TITLE
Cross compiling failed

### ISSUE THREAD

**Issue by Iot-lilei** [rancher/k3s#139]
I am trying to compile k3s with cross compiling from centos to raspberry pi with command:
GOOS=linux GOARCH=arm go build -o k3s
But I got the error:
vendor/github.com/google/cadvisor/accelerators/nvidia.go:29:2: build constraints exclude all Go files in /home/user/mygo/src/github.com/rancher/k3s/vendor/github.com/mindprince/gonvml
I tried go version 1.11 and 1.11.4.

**Comment by ibuildthecloud** [comment]
This might be due to the fact that `github.com/mindprince/gonvml` is CGO. When cross compiling does CGO work?

**Comment by Iot-lilei** [comment]
Yes, CGO works. Thank you!
