### ISSUE TITLE
 postgres CPU usage when load testing rancher

### ISSUE THREAD

**Issue by dramich** [rancher/k3s#1392]
When load testing rancher postgres CPU would pin at 100% while still having a low IOPS count.

**Comment by davidnuzik** [comment]
@ShylajaDevadiga just ensure no regressions in PostgreSQL and MySQL. query has been optimized and validated -- just want to ensure no regressions.

**Comment by ShylajaDevadiga** [comment]
Verified on v1.18.2-rc2+k3s1. No regressions found with Postgres or MySQL. 
@dramich please feel free to reopen the if you see the issue with CPU usage.
