### ISSUE TITLE
Changes to the upgrade script for k3s-upgrade image

### ISSUE THREAD

**Issue by galal-hussein** [rancher/k3s#1393]
The k3s-upgrade image should have the following changes:
 - Add more info level logging to the upgrade script. Include runtime relevant information
 - Remove architecture and k3d specific code
 - Remove any code related to systemd or openrc

**Comment by galal-hussein** [comment]
- Adding checksum check for downloaded binaries

**Comment by ShylajaDevadiga** [comment]
Verified k3s upgrade using system-upgrade controller.
