### ISSUE TITLE
Does the k3s kubelet support reporting back CSI kubelet_volume metrics?

### ISSUE THREAD

**Issue by onedr0p** [rancher/k3s#1396]
**Version:**
v1.17.2+k3s1

**Describe the bug**
Unable to see `kubelet_volume_*` metrics, deployed rook-ceph and I am unable to see `kubelet_volume_*` metrics in Prometheus.

**To Reproduce**
- Deploy k3s
- Deploy Prometheus Operator Helm chart
- Deploy rook-ceph Helm chart (or any CSI driver that supports reporting these metrics)

Check if you receive `kubelet_volume_*` metrics in Prometheus.

```
kubelet_volume_stats_available_bytes
kubelet_volume_stats_capacity_bytes
kubelet_volume_stats_inodes
kubelet_volume_stats_inodes_free
kubelet_volume_stats_inodes_used
kubelet_volume_stats_used_bytes
```

**Expected behavior**
To see `kubelet_volume_*` metrics in Prometheus

**Actual behavior**
Unable to see kubelet_volume_ metrics, deployed rook-ceph and I am unable to see `kubelet_volume_*` metrics in Prometheus.

**Comment by danieldabate** [comment]
I'm also interested in this. Have you got any clue?

**Comment by onedr0p** [comment]
@danieldabate This is working for me, I'm not sure what fixed the issue to be honest. Maybe a k3s update? Prometheus update? rook-ceph update? who knows.

**Comment by JinLinGan** [comment]
@onedr0p  I check this metrics in version **v1.17.5+k3s1**，I still haven't found these metrics.
you find these metrics in which revision？

**Comment by brandond** [comment]
Working for me on 1.18.3 and several prior releases:

```kubelet_volume_stats_used_bytes{beta_kubernetes_io_arch="amd64", beta_kubernetes_io_os="linux", instance="seago.lan.khaus", job="kubernetes-nodes-kubelet", kubernetes_io_arch="amd64", kubernetes_io_hostname="seago.lan.khaus", kubernetes_io_os="linux", namespace="traefik", node_role_kubernetes_io_master="true", persistentvolumeclaim="traefik-storage", topology_kubernetes_io_region="khaus", topology_kubernetes_io_zone="khaus-0"}```

**Comment by JinLinGan** [comment]
@onedr0p @brandond  @danieldabate  

https://github.com/google/cadvisor/issues/1702#issuecomment-538337013

I find this comment in cadvisor，It seems to be because the cis plugin did not expose these metrics？

I use Longhorn to be my default Storage Class，I will check other Storage Class tomorrow

**Comment by rgstephens** [comment]
I'm also not getting these stats for rancher `local-path` volumes in 1.18.8

**Comment by brandond** [comment]
Local-path volumes are not true volumes, they're just paths mounted from the host filesystem.
