### ISSUE TITLE
Pod deploying on master and not on node 

### ISSUE THREAD

**Issue by DhruvM1994** [rancher/k3s#1402]
**Version:**
1.17

**Describe the bug**
I am trying to deploy a k3s cluster on two Raspberry Pi computers. Thereby, I would like to use the Rapsberry Pi 4 as the master/server of the cluster and a Raspberry Pi 3 as a worker node/agent.
However, when I try to make a deployment the pod is always deployed on the Raspberry Pi 4 (master) and not on the worker node.

**To Reproduce**
On both computers:
- Insert ```cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory``` into /boot/cmdline.txt

On master Raspberry Pi 4:
```curl -sfL https://get.k3s.io | sh -```
```sudo kubectl run nginx-sample -image nginx --port 80```

On worker node Raspberry Pi 3:
```curl -sfL https://get.k3s.io | K3S_URL=https://myserver:6443 K3S_TOKEN=XXX sh -```

**Expected behavior**
The command ```sudo kubectl get pods -o wide --all-namespaces``` should show that the pod is deployed on the worker node.

**Actual behavior**
The command ```sudo kubectl get pods -o wide --all-namespaces``` shows that the pod is deployed on the master node.

![SampleDeployment](https://user-images.githubusercontent.com/56864563/74106930-610c4780-4b6b-11ea-81d8-68be8a132e9e.PNG)

**Additional context**
The command ```sudo kubectl get nodes```shows both nodes.

![Pod](https://user-images.githubusercontent.com/56864563/74106865-9fedcd80-4b6a-11ea-8e30-a09260a54dae.PNG)

When trying to use the Raspberry Pi 3 as the master and the Raspberry Pi 4 as the node, then the pod is deployed on the worker node.

**Comment by carpenike** [comment]
Did you taint the master node? I believe by default k3s will not taint it.

`kubectl label --overwrite node <MASTER> node-role.kubernetes.io/master=true:NoSchedule`

**Comment by DhruvM1994** [comment]
@carpenike I did not specify it explicitly. 
However, when I use the Raspberry Pi 3 as the master node and the Rasperry Pi 4 as the worker node, then the deployment is deployed on the worker node, as expected.

**Comment by Kerwood** [comment]
@carpenike If you taint the node master node like that, what happens if you delete the coredns pod? It wouldn't be able to reschedule on the master node again, would it ?

**Comment by carpenike** [comment]
@Kerwood  -- correct. You'd have to use a toleration within a deployment to allow deployments on the master node. Also, I mis-wrote that. It's taint, not label.

`kubectl taint--overwrite node <MASTER> node-role.kubernetes.io/master=true:NoSchedule`

My suspicion is that it's choosing the node with the most available resources when doing the node selection, and choosing the Pi4.

**Comment by Kerwood** [comment]
I have been trying different things to achieve the same the last couple of days.
Here's my solution. (Which in my opinion should be default)

Taint the master with below command.
```
kubectl taint node dev-k3s-master k3s-controlplane=true:NoSchedule
```
Add tolerance on the control-plane services.
```
kubectl edit deployments local-path-provisioner -n kube-system
```

And add the following to the containers spec.
```
spec:
  ...
  template:
  ...
    spec:
    ...
      tolerations:
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        operator: Exists
``` 

Do the same for `metrics-server` and `coredns`. The latter will have will have `tolerations:` present, so just add the two effects to the list.

**Comment by keslerm** [comment]
It would be nice to have the install script recognize this setup (e.g. --no-schedule-master or some kind of flag) that would grant these the appropriate tolerations automatically.

**Comment by onedr0p** [comment]
@alekc It is my understanding that if the k3s-master is rebooted those will get overwritten or am I wrong?

**Comment by izeau** [comment]
To add up on @alekc's answer, I also had to patch the service load balancer:

```shell
$ kubectl patch daemonset svclb-traefik -n kube-system --patch "$(cat patch.yaml)"
```

**Comment by alekc** [comment]
Right, I've been deploying with `--no-deploy=traefik` flag so didn't have that one.

**Comment by DhruvM1994** [comment]
I used the ```nodeSelector``` entry.

**Comment by franciscosuca** [comment]
Try this command to avoid pods on master node
`sudo kubectl taint node <your_master_node> node-role.kubernetes.io/master:NoSchedule`
To deploy to a specific node try [nodeSelector](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector) and for several nodes try [nodeAffinity](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity).
