### ISSUE TITLE
Add CI pipeline to automatically build k3s-upgrade images with each release

### ISSUE THREAD

**Issue by galal-hussein** [rancher/k3s#1408]
A new k3s-upgrade image should be created for each k3s release, this can be accomplished by github actions that listen for each release publish and trigger a dispatch event to k3s-upgrade image with the desired tag.

**Comment by davidnuzik** [comment]
Since this is a task, will just close when this is complete.

**Comment by davidnuzik** [comment]
As we discussed needs testing when have a build to work with.

**Comment by davidnuzik** [comment]
Closing this was confirmed working
