### ISSUE TITLE
3 k3s racing to setup a db cause 2 to fail 

### ISSUE THREAD

**Issue by dramich** [rancher/k3s#1410]
Using a script to spin up three k3s servers pointing at the DB at the same time causes one to succeed and the other two to fail. 

Happening on master

**Comment by davidnuzik** [comment]
@galal-hussein could you look into as a low priority? I have placed this in the v1.x - Backlog milestone for now.

**Comment by davidnuzik** [comment]
Closing out (per Craig) - shouldn't be an issue any longer.
