### ISSUE TITLE
k3s core dumps on armv7l/cumulus linux

### ISSUE THREAD

**Issue by ThomasADavis** [rancher/k3s#1419]
**Version:**
wget https://github.com/rancher/k3s/releases/download/v1.17.2%2Bk3s1/k3s-armhf 

**Describe the bug**
./k3s-armhf --help
Illegal instruction (core dumped)

**Expected behavior**
does not core dump

**Actual behavior**
core dumps

**Additional context**
trying it on cumulus linux v3.7.7

root@sw-d8-r11-u35:~ uname -a
Linux sw-d8-r11-u35 4.1.0-cl-7-iproc #1 SMP Cumulus 4.1.33-1+cl3u25 (2019-11-25) armv7l GNU/Linux

root@sw-d8-r11-u35:~ free
             total       used       free     shared    buffers     cached
Mem:       1999888     765712    1234176      41604        960     517128
-/+ buffers/cache:     247624    1752264
Swap:            0          0          0
root@sw-d8-r11-u35:~# cat /proc/cpuinfo 
processor	: 0
model name	: ARMv7 Processor rev 0 (v7l)
BogoMIPS	: 1980.41
Features	: half thumb fastmult edsp tls 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x3
CPU part	: 0xc09
CPU revision	: 0

processor	: 1
model name	: ARMv7 Processor rev 0 (v7l)
BogoMIPS	: 1990.65
Features	: half thumb fastmult edsp tls 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x3
CPU part	: 0xc09
CPU revision	: 0

Hardware	: BRCM XGS iProc
Revision	: 0000
Serial		: 0000000000000000

**Comment by ThomasADavis** [comment]
Figured it out.  Processor is closer to an ARMv5 than an V7..

**Comment by PiotrBzdrega** [comment]
Same behaviour on mine ARMv5 
```shel
Linux MIK23097384 4.14.336mCU #1 PREEMPT Thu Apr 25 18:12:13 CEST 2024 armv5tejl GNU/Linux
```

**Comment by brandond** [comment]
We don't support arm v5.
