### ISSUE TITLE
--selector -l multiple parameter bug?

### ISSUE THREAD

**Issue by hadeschen** [rancher/k3s#1425]
Version:
wget https://github.com/rancher/k3s/releases/download/v1.17.2%2Bk3s1/k3s

Describe the bug
```
[root@k3s-node2 ~]# ll `which kubectl`
lrwxrwxrwx 1 root root 18 2月  12 19:53 /usr/local/bin/kubectl -> /usr/local/bin/k3s
[root@k3s-node2 ~]# kubectl get pod -n comm -l app=demo1
NAME                       READY   STATUS    RESTARTS   AGE
sso-demo1-7b4997b4-nk6ww   1/1     Running   0          48m
[root@k3s-node2 ~]# kubectl get pod -n comm -l app=demo2
NAME                        READY   STATUS    RESTARTS   AGE
sso-demo2-5b4df5bdd-6n7wg   1/1     Running   0          48m
[root@k3s-node2 ~]# kubectl get pod -n comm -l app=demo3
NAME                         READY   STATUS    RESTARTS   AGE
sso-demo3-6c4fb9465b-ln8lq   1/1     Running   0          48m
[root@k3s-node2 ~]#
[root@k3s-node2 ~]# kubectl get pod -n comm -l app=demo1,app=demo2
No resources found in comm namespace.
[root@k3s-node2 ~]# kubectl get pod -n comm -l app=demo1,app=demo2,app=demo3
No resources found in comm namespace.
[root@k3s-node2 ~]# kubectl get pod -n comm -l app=demo2
NAME                        READY   STATUS    RESTARTS   AGE
sso-demo2-5b4df5bdd-6n7wg   1/1     Running   0          49m
```

**Comment by brandond** [comment]
Were you expecting this to be a union? It's not.

> The API currently supports two types of selectors: equality-based and set-based. A label selector can be made of multiple requirements which are comma-separated. In the case of multiple requirements, all must be satisfied so the comma separator acts as a logical AND (&&) operator.

https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/

**Comment by hadeschen** [comment]
I was so stupid

> 
> 
> Were you expecting this to be a union? It's not.
> 
> > The API currently supports two types of selectors: equality-based and set-based. A label selector can be made of multiple requirements which are comma-separated. In the case of multiple requirements, all must be satisfied so the comma separator acts as a logical AND (&&) operator.
> 
> https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/

I was so stupid,thanks.
