### ISSUE TITLE
Is it possible to use AWS ECR as repository for K3S running on AWS EC2

### ISSUE THREAD

**Issue by urupaud** [rancher/k3s#1426]
Thanks for helping us to improve k3s! We welcome all feature requests. Please fill out each area of the template so we can better understand the request. ***You can delete this message portion of the bug report.***

**Is your feature request related to a problem? Please describe.**
We have a k3s cluster which is running on AWS ec2, we want to deploy containers into this cluster using images in our AWS ECR, is this possible ?

**Describe the solution you'd like**
Able to use AWS ECR images to use in K3S cluster running on EC2

**Comment by davidnuzik** [comment]
Closing in favor of https://github.com/rancher/k3s/issues/1427 (duplicate)
