### ISSUE TITLE
No deploy traefik also disables ServiceLB

### ISSUE THREAD

**Issue by jishminor** [rancher/k3s#1439]
**Version:**

`v1.17.2+k3s1`

**Describe the bug**

Specifying no deploy for traefik results in service load balancer also not being deployed.

**To Reproduce**

```bash
# Install k3s using the following command
curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 664 --bind-address $THIS_HOST_IP --advertise-address $ADVERTISE_IP --no-deploy=traefik
```

**Expected behavior**

Servicelb daemonset and corresponding pod should be deployed.

**Actual behavior**

Servicelb Daemonset, and consequently its pods, is/are not created.

**Additional context**

My intention is to install traefik 2 on top of k3s, using their prototype helm chart found [here](https://github.com/containous/traefik-helm-chart). I would like to simply install k3s, then add my own custom traefik.yaml file to `/var/lib/rancher/k3s/server/manifests/`. I thought this would be a reasonable approach, however it does not seem to work, as servicelb is not deployed.

**Comment by jishminor** [comment]
I found that once traefik was deployed via helm, the servicelb is created.

**Comment by ogbofjnr** [comment]
I have the same issue, spend some time till realize that servicelb is not deployed when --no-deploy=traefik passed to install script. Please fix it or update documentation.

**Comment by yifeikong** [comment]
> I found that once traefik was deployed via helm, the servicelb is created.

I don't think the servicelb is disabled, it's just lazily created. The svclb-xxx pod was not created simply because you don't have a "LoadBalancer" type service, traefik is not required, any LoadBalancer will do.
