### ISSUE TITLE
journalctl -u k3s "No entries"

### ISSUE THREAD

**Issue by spitfire88** [rancher/k3s#146]
Thanks for helping us to improve k3s! We welcome all bug reports. At this stage, we are also looking for help in testing/QAing fixes. Once we've fixed you're issue, we'll ping you in the comments to see if you can verify the fix. We'll give you details on what version can be used to test the fix. Additionally, if you are interested in testing fixes that you ***didn't*** report, look for the issues with the `status/to-test` label. You can pick any of these up for verification.  ***You can delete this message portion of the bug report.***

**Describe the bug**
journalctl -u k3s
-- Logs begin at Sat 2019-03-02 07:14:45 UTC, end at Mon 2019-03-04 19:18:55 UTC. --
-- No entries --

**To Reproduce**
1. sudo k3s server &
2. journalctl -u k3s

**Expected behavior**
Expect to see k3s logs.

**Screenshots**

**Additional context**

**Comment by ibuildthecloud** [comment]
@spitfire88 can you provide the output of `systemctl status k3s`?  Also `sudo k3s server` will not run the service under systemd.  You need to run `systemctl start k3s`.

**Comment by erikwilson** [comment]
The systemd installer should fit your needs @spitfire88, if not please re-open this issue.
