### ISSUE TITLE
[Documentation] Mention that Nginx is now the default ingress controller and how to upgrade from Traefik and how to keep Traefik

### ISSUE THREAD

**Issue by davidnuzik** [rancher/k3s#1480]
For https://github.com/rancher/k3s/issues/817 Document what is required if you previously had Traefik before an upgrade and wish to opt-in to upgrading with Nginx instead.

E.g. 
- remove the traefik addon object
- remove the traefik deployment
- upgrade k3s with nginx

The documentation should say that as of version "X" the default ingress controller is now Nginx. It should briefly describe how to switch from traefix to nginx and how to continue using traefik going forward instead of the default nginx.

An ideal place for this in docs may be https://rancher.com/docs/k3s/latest/en/upgrades/
As for new installs, the release notes will mention that Nginx is now the default ingress controller.

**Comment by cjellick** [comment]
Nope. We're sticking with traefik. https://github.com/rancher/k3s/pull/1519
