### ISSUE TITLE
HA with Embedded DB is Experimental,Why? Are there any known issues？

### ISSUE THREAD

**Issue by lsk8867485** [rancher/k3s#1481]
Are there any known issues？

**Comment by cjellick** [comment]
Good question. The primary reason is that the failure scenarios around losing (and recovering) nodes are not fully tested. Fundamentally, it needs more rigorous testing before we can certify it and other work items have taken priority.

**Comment by lsk8867485** [comment]
> Good question. The primary reason is that the failure scenarios around losing (and recovering) nodes are not fully tested. Fundamentally, it needs more rigorous testing before we can certify it and other work items have taken priority.

[#1391](https://github.com/rancher/k3s/issues/1391)
Thanks，Is there a good solution to this issue？

**Comment by davidnuzik** [comment]
Thanks for the question see https://github.com/rancher/k3s/issues/1391 for example and Craig's comment. Please ask your question about https://github.com/rancher/k3s/issues/1391 in that issue. If you have any other questions let us know.
