### ISSUE TITLE
In HA the compaction in kine will get stuck and can corrupt data

### ISSUE THREAD

**Issue by cjellick** [rancher/k3s#1483]
THis is an issue to track the already merged https://github.com/rancher/k3s/pull/1377

**Comment by davidnuzik** [comment]
I'm not certain if there is a direct or easy way to test this. If I had to guess the original issue would not be identified unless there was a lot of transactions to the cluster datastore (under load). Perhaps the best course of action is to set up an external db (mysql or mariadb) and simply run conformance? I would hardly call this putting the cluster under load but that's the best I can think of unless @cjellick has any suggestions.

**Comment by davidnuzik** [comment]
Closing based on 3/21/20 discussion.
