### ISSUE TITLE
Improve the ability to build and run k3s server on windows

### ISSUE THREAD

**Issue by cjellick** [rancher/k3s#1486]
Tracking issue for:
- https://github.com/rancher/k3s/pull/1440 - Renaming an open file doesn't work on windows and is a bad practice on linux
- https://github.com/rancher/k3s/pull/1444 - Add logic/structure changes for being able to build the k3s server on windows

**Comment by cjellick** [comment]
Now, we should consider adding a Windows server to drone to ensure we don't break the compilation in a future commit

**Comment by davidnuzik** [comment]
@KnicKnic could you validate the fix? Then I can close the issue.
We have an RC here: https://github.com/rancher/k3s/releases/tag/v1.18.2-rc1%2Bk3s1

**Comment by KnicKnic** [comment]
> @KnicKnic could you validate the fix? Then I can close the issue.
> We have an RC here: https://github.com/rancher/k3s/releases/tag/v1.18.2-rc1%2Bk3s1

@davidnuzik 
I needed to checkin a build fix. see https://github.com/rancher/k3s/pull/1664

other than that it came up.
```
 kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299
a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:11:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/
amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2-k3s.1", GitCommit:"3d7d34a23ec464c08b81486aeca0b
7d1bb6e044c", GitTreeState:"clean", BuildDate:"2020-04-19T05:33:19Z", GoVersion:"go1.14.1", Compiler:"gc", Platform:"win
dows/amd64"}
```

**Comment by davidnuzik** [comment]
@KnicKnic thank you so much for the contributions and help checking this :) I can't promise quick review of https://github.com/rancher/k3s/pull/1664 but got it on the radar.

**Comment by davidnuzik** [comment]
#1664 is merged in. I will be closing this issue. Thanks for your contributions @KnicKnic we really appreciate it! :)
