### ISSUE TITLE
Containers can get orphaned and stuck when running in rootless mode

### ISSUE THREAD

**Issue by cjellick** [rancher/k3s#1487]
When running rootless mode if you kill the agent the old containers will stick around but they are in an orphaned network namespace.

This is a tracking issue for https://github.com/rancher/k3s/pull/1343

**Comment by AkihiroSuda** [comment]
> This is a tracking issue for #1343

Just to confirm, you mean that #1343 resolves this issue?

**Comment by ShylajaDevadiga** [comment]
Unable to install k3s with --rootless flag. k3s does not start.
Env and Steps followed.
```
cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"

sudo apt-get install uidmap
Reading package lists... Done
Building dependency tree       
Reading state information... Done
uidmap is already the newest version (1:4.5-1ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

ubuntu@ip-172-31-9-159:~$ cat /etc/subuid
lxd:100000:65536
root:100000:65536
ubuntu:165536:65536

ubuntu@ip-172-31-9-159:~$ cat /etc/subgid
lxd:100000:65536
root:100000:65536
ubuntu:165536:65536

export KUBECONFIG=~/.kube/k3s.yaml

./k3s server --rootless >k3s.log 2>&1 &
[1]+  Exit 1                  ./k3s server --rootless > k3s.log 2>&1

cat k3s.log 
time="2020-04-24T19:57:23.087549729Z" level=fatal msg="failed to setup network &{binary:slirp4netns mtu:65520 ipnet:0xc0008957d0 disableHostLoopback:true apiSocketPath: enableSandbox:false enableSeccomp:false}: waiting for ready fd (/home/ubuntu/.rancher/k3s/data/1cd84d78e73d1835ec46d86660cd74dd4d52357ced9b4050a211168c4b1da90a/bin/slirp4netns --mtu 65520 -r 3 --disable-host-loopback --cidr 10.41.0.0/16 1986 tap0): slirp4netns failed"
time="2020-04-24T19:57:23.089651925Z" level=fatal msg="child diedparsing message from fd 3: EOF"
```

**Comment by AkihiroSuda** [comment]
slirp4netns not installed?

**Comment by ShylajaDevadiga** [comment]
@AkihiroSuda Thanks for quick response. I was not able to install slirp4netns.
```
sudo apt install slirp4netns
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package slirp4netns
```
As per the ReadMe https://github.com/rootless-containers/slirp4netns, it should be Ubuntu19.04 or later. 
Will test on Ubuntu 19.04.

**Comment by AkihiroSuda** [comment]
Binary is here
https://github.com/rootless-containers/slirp4netns/releases/tag/v1.0.1

**Comment by ShylajaDevadiga** [comment]
@AkihiroSuda slirp4netns  is already installed as part of k3s as seen in the error log above. Ubuntu version 20.04 as well seems to have the same error.

**Comment by AkihiroSuda** [comment]
I can repro the issue. Seems a regression happened recently.

**Comment by AkihiroSuda** [comment]
Does reverting https://github.com/rancher/k3s/pull/1343 solve the issue?

(I'm trying to confirm but I can't compile k3s)

**Comment by AkihiroSuda** [comment]
Let's track the slirp4netns issue in https://github.com/rancher/k3s/issues/1709

**Comment by davidnuzik** [comment]
@ShylajaDevadiga lowered rank in zube while waiting for #1709 fix.

**Comment by AkihiroSuda** [comment]
The current master (c8282f4939ea8e36b5411936ed174787eaefaccc) seems working well for rootless

**Comment by brandond** [comment]
@AkihiroSuda @cjellick you feel comfortable closing this out?

**Comment by AkihiroSuda** [comment]
yes
