### ISSUE TITLE
Simplify SELinux detection and add --disable-selinux flag

### ISSUE THREAD

**Issue by cjellick** [rancher/k3s#1490]
We now have an explicit --disable-selinux flag to force it off.
We automatically detect selinux and turn it on. The logic was flaky. We simplified it.

**Comment by davidnuzik** [comment]
Pretty sure `ps -efZ` can be utilized to check the context on the container process(s). If we set the `--disable-selinux` flag the context should be different for the container processes

**Comment by ShylajaDevadiga** [comment]
Created cluster passing --disable-selinux flag. Pods are in ContainerCreating State. 
```
# k3s -v
k3s version v1.17.3-alpha1+k3s1 (fa85cf78)

# ps -ef |grep k3s
root     13468     1 21 04:52 ?        00:00:12 /usr/local/bin/k3s server --disable-selinux

# kubectl get pods -A
NAMESPACE     NAME                                      READY   STATUS              RESTARTS   AGE
kube-system   metrics-server-6d684c7b5-rdbtx            0/1     ContainerCreating   0          63s
kube-system   helm-install-traefik-db7jh                0/1     ContainerCreating   0          63s
kube-system   local-path-provisioner-58fb86bdfd-krp9b   0/1     ContainerCreating   0          63s
kube-system   coredns-d798c9dd-flzsx                    0/1     ContainerCreating   0          63s
```
Logs:
```
Warning  FailedCreatePodSandBox  3m4s (x26 over 8m47s)  kubelet, ip-172-31-9-28.us-east-2.compute.internal  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"write /proc/self/attr/keycreate: permission denied\"": unknown
```

**Comment by davidnuzik** [comment]
Check containerd configuration - SELinux should be disabled there.
May need to specify Unconfined type on the k3s binary

Needs documentation; if pass this flag and SELinux is set to enforcing you may run into issues such as those observed today.

**Comment by ShylajaDevadiga** [comment]
Verified using v1.18.2-rc2+k3s1. Confirmed selinux is disabled in containerd configuration and k3s processes have selinux turned off using ps -eZ.
```
cat /var/lib/rancher/k3s/agent/etc/containerd/config.toml |grep selinux
  enable_selinux = false
```
