### ISSUE TITLE
[Documentation] During k3s upgrade, standalone pods gets deleted as expected

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/k3s#1496]
k3s upgrade implicitly runs kubectl drain --force, which deletes unmanaged pods during upgrade as of now, which is a default k8s behavior.

**Comment by davidnuzik** [comment]
Close in favor of https://github.com/rancher/k3s/issues/1498 that issue is more general talking about the need to document the system upgrade controller and I also mention your concern in that issue.
