### ISSUE TITLE
Add config file support to K3s

### ISSUE THREAD

**Issue by davidnuzik** [rancher/k3s#1505]
Add support for flat config file which specifies flags to run binary with.

- YAML structure.
- CLI and CONFIG file should have a very obvious relationship to each other.
_That is to say, should be able to pull from config file and turn this into a line to run k3s with these args_

To expand on the CLI and CONFIG file relationship. The concern is that if the config file is different enough from the cli flags, it makes things difficult to understand. Docs would be required for both the config and cli with different terms and this just makes things confusing.

Ideally, can run K3s strictly from a config file and to change things dynamically supply command line flags to change things [if we do this how does config file get updated (and should it)].

**Comment by ShylajaDevadiga** [comment]
On k3s version v1.18.6+k3s-169ee639
Validated following scenarios:
Args passed in  /etc/rancher/k3s/flags.conf is used during the install process.
```
curl -sfL http://get.k3s.io |INSTALL_K3S_COMMIT=169ee63907a51004ff000af1238e3483ce0c5fd8 sh -

/etc/rancher/k3s/flags.conf
write-kubeconfig-mode: "0644"
ls -l /etc/rancher/k3s/k3s.yaml 
-rw-r--r-- 1 root root 2789 Jul 31 20:48 /etc/rancher/k3s/k3s.yaml
```
Passing config file as a parameter using --config /tmp/args.conf 
```
curl -sfL http://get.k3s.io |INSTALL_K3S_COMMIT=169ee63907a51004ff000af1238e3483ce0c5fd8 sh -s - server  --config /tmp/args.conf

cat /tmp/args.conf 
write-kubeconfig-mode: "0644"
node-label:
  - "foo1=bar1"

kubectl describe node |grep foo
                    foo1=bar1
```
Override flag in config with cli argument
```
cat /tmp/args.conf
write-kubeconfig-mode: "0644"
node-label:
  - "foo1=bar1"

curl -sfL http://get.k3s.io |INSTALL_K3S_COMMIT=169ee63907a51004ff000af1238e3483ce0c5fd8 sh -s - server  --config /tmp/args.conf --node-label foo1=bar2

kubectl describe node |grep foo
                    foo1=bar2
```
Joining agent passing args through config file
```
curl -sfL http://get.k3s.io |INSTALL_K3S_COMMIT=169ee63907a51004ff000af1238e3483ce0c5fd8 sh -s - agent  --config /tmp/args1.conf

cat /tmp/args1.conf
server: https://IP:6443
token: TOKEN
```

**Comment by cjellick** [comment]
Linking to the new issue that I created to have a clean reference point for this feature: https://github.com/rancher/k3s/issues/2228
