### ISSUE TITLE
With SELinux enabled setup, kube-system pods are in CrashLoopBackoff State

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/k3s#1530]
**Version:**
Operating System: CentOS
CentOS Linux release 7.6.1810

k3s version
v1.17.3-alpha1+k3s1

**Describe the bug**
With SELinux enabled k3s install on CentOS, pods not in running state.

**To Reproduce**
Install k3s using curl script
Run kubectl get pods -A

**Expected behavior**
kube-system pods should be running

**Actual behavior**
kube-system pods are in CrashLoopBAckoff state

**Additional context**
```Events:
  Type     Reason                  Age                    From                                                 Message
  ----     ------                  ----                   ----                                                 -------
  Warning  FailedCreatePodSandBox  11m (x595 over 176m)   kubelet, ip-172-31-13-88.us-east-2.compute.internal  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:319: getting the final child's pid from pipe caused \"EOF\"": unknown
  Normal   SandboxChanged          76s (x2466 over 4h1m)  kubelet, ip-172-31-13-88.us-east-2.compute.internal  Pod sandbox changed, it will be killed and re-created.```

**Comment by davidnuzik** [comment]
We recommend just using RPM / repo install for CentOS

**Comment by ShylajaDevadiga** [comment]
Using RPMs, install was successful. k3s version v1.17.4-alpha1+k3s1
```
rpm -i https://rpm.rancher.io/k3s-selinux-0.1.1-rc1.el7.noarch.rpm
rpm -i https://rpm.rancher.io/k3s-1.17.4-alpha1.1.el7.x86_64.rpm
```

**Comment by jhmnieuwenhuis** [comment]
Are there also rpm's available for centos 8 ?
I just updated from  v1.17.1+k3s1 to v1.17.4+k3s1 and k3s no longer runs
Disabled selinux and it runs again.
Installed and updated using : curl -sfL https://get.k3s.io  | INSTALL_K3S_VERSION="v1.17.4+k3s1" ...

**Comment by ShylajaDevadiga** [comment]
@jhmnieuwenhuis It's going to be a while for CentOS 8 rpm's to be available as are currently progressing on CentOS 7 support with SELinux. Here is the issue you can follow https://github.com/rancher/k3s/issues/1371 and we have the docs updated https://rancher.com/docs/k3s/latest/en/advanced/#experimental-selinux-support. Thanks
