### ISSUE TITLE
[Documentation] RPM install

### ISSUE THREAD

**Issue by davidnuzik** [rancher/k3s#1535]
Document the RPM install method. At a minimum we should cover:

- How to do a typical install of the server and agent RPMs
- How to config the service and how to set it to start after reboot (enable it)
- How to uninstall

**Comment by davidnuzik** [comment]
Some content covered in https://github.com/rancher/docs/pull/2397
Still needs it's own child page in the install section with the requirements outlined in the issue body above.

**Comment by davidnuzik** [comment]
Depends on finish the RPM based work (main RPM installer for k3s itself, not the SELinux policies).

**Comment by Oats87** [comment]
As we are not going to be publishing K3s RPMs past the `k3s-selinux` RPMs, do we still need this @davidnuzik ?

**Comment by davidnuzik** [comment]
To be discussed with @cjellick

**Comment by Oats87** [comment]
https://github.com/rancher/k3s/issues/2440 has put a nail in the coffin for K3s RPMs (for now)

**Comment by davidnuzik** [comment]
Closing. RPM artifacts disabled in pipeline. The latest release notes call this out.
Perhaps later we change this and introduce RPMS again, but this is for discussion later. If/when that happens we can open a new docs issue for documenting rpms.

**Comment by mysticaltech** [comment]
For those in need, this repo works well to install the latest k3s-selinux on latest Fedora 34:

Create `/etc/yum.repos.d/rpm-rancher-io.repo` and put the following content inside:

```
[rancher] 
name=Rancher 
baseurl=https://rpm.rancher.io/k3s/stable/common/centos/8/noarch
enabled=1 
gpgcheck=1 
gpgkey=https://rpm.rancher.io/public.key
```
