### ISSUE TITLE
[Documentation] SELinux experimental support

### ISSUE THREAD

**Issue by davidnuzik** [rancher/k3s#1536]
SELinux support will be added as experimental in v1.17.4 as we'd like additional testing from the community. We should document known issues as necessary (release notes and/or in the K3s docs) and we should document any "gotchas" or other information that we are aware of.

This may also be a good place to discuss the disable-selinux flag and necessary config for containerd should you wish to disable selinux in an environment that has it set to Enforcing mode.

**Comment by polachz** [comment]
Hallo. During install, I have got info:
[ERROR]  Failed to apply container_runtime_exec_t to /usr/local/bin/k3s, please install k3s-selinux RPM

But I', not able to find **k3s-selinux ** RPM. Can you extend documentation about that, or give me a hint how-to continue, please ?

**Comment by erikwilson** [comment]
Sorry about that @polachz , the k3s-selinux policy can be installed like the following for now:
```
yum install -y container-selinux selinux-policy-base
rpm -i https://rpm.rancher.io/k3s-selinux-0.1.1-rc1.el7.noarch.rpm
```
the selinux policy rpm can also be found at https://github.com/rancher/k3s-selinux/releases

Hopefully in the future we will have a repo & k3s package available which will automatically install the required selinux policy.

**Comment by davidnuzik** [comment]
Fixed in https://github.com/rancher/docs/pull/2397 including 
```
yum install -y container-selinux selinux-policy-base
rpm -i https://rpm.rancher.io/k3s-selinux-0.1.1-rc1.el7.noarch.rpm
```

**Comment by Aisuko** [comment]
```
yum install -y container-selinux selinux-policy-base
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.aliyun.com
 * extras: mirrors.aliyun.com
 * updates: mirrors.aliyun.com
Package 2:container-selinux-2.119.1-1.c57a6f9.el7.noarch already installed and latest version
Package selinux-policy-targeted-3.13.1-266.el7.noarch already installed and latest version
Nothing to do


 ⚡ root@es-node01  ~  rpm -i https://rpm.rancher.io/k3s-selinux-0.1.1-rc1.el7.noarch.rpm
warning: /var/tmp/rpm-tmp.8rJIvR: Header V4 RSA/SHA1 Signature, key ID e257814a: NOKEY
	package k3s-selinux-0.1.1-rc1.el7.noarch is already installed

 ✘ ⚡ root@es-node01  ~  curl -sfL https://get.k3s.io | sh -
[INFO]  Finding release for channel stable
[INFO]  Using v1.18.4+k3s1 as release
[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v1.18.4+k3s1/sha256sum-amd64.txt
[INFO]  Skipping binary downloaded, installed k3s matches hash
[ERROR]  Failed to apply container_runtime_exec_t to /usr/local/bin/k3s, please install:
    yum install -y container-selinux selinux-policy-base
    rpm -i https://rpm.rancher.io/k3s-selinux-0.1.1-rc1.el7.noarch.rpm

```

Maybe I need more help here with Centos 7

**Comment by LowApe** [comment]
> Hello sir @davidnuzik
> 
> ```
> yum install -y container-selinux selinux-policy-base
> Loaded plugins: fastestmirror
> Loading mirror speeds from cached hostfile
>  * base: mirrors.aliyun.com
>  * extras: mirrors.aliyun.com
>  * updates: mirrors.aliyun.com
> Package 2:container-selinux-2.119.1-1.c57a6f9.el7.noarch already installed and latest version
> Package selinux-policy-targeted-3.13.1-266.el7.noarch already installed and latest version
> Nothing to do
> 
> 
>  ⚡ root@es-node01  ~  rpm -i https://rpm.rancher.io/k3s-selinux-0.1.1-rc1.el7.noarch.rpm
> warning: /var/tmp/rpm-tmp.8rJIvR: Header V4 RSA/SHA1 Signature, key ID e257814a: NOKEY
> 	package k3s-selinux-0.1.1-rc1.el7.noarch is already installed
> 
>  ✘ ⚡ root@es-node01  ~  curl -sfL https://get.k3s.io | sh -
> [INFO]  Finding release for channel stable
> [INFO]  Using v1.18.4+k3s1 as release
> [INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v1.18.4+k3s1/sha256sum-amd64.txt
> [INFO]  Skipping binary downloaded, installed k3s matches hash
> [ERROR]  Failed to apply container_runtime_exec_t to /usr/local/bin/k3s, please install:
>     yum install -y container-selinux selinux-policy-base
>     rpm -i https://rpm.rancher.io/k3s-selinux-0.1.1-rc1.el7.noarch.rpm
> ```
> 
> Maybe I need more help here with Centos 7

the same error
