### ISSUE TITLE
Service node port timeout/answer depending node 

### ISSUE THREAD

**Issue by tanguyfalconnet** [rancher/k3s#1539]
Hi everyone, thanks for any help :)

**Version:**

```
k3s version v1.17.3+k3s1 (5b17a175)
```

**Describe the bug**

- In a cluster of 3 worker nodes behind a NAT and 1 master node in cloud, pods that are on worker nodes can't communicate with pod on master node.

- If a service node port is defined on a pod which is on worker node, only worker nodes will answer to requests (master will timeout)

- If a service node port is defined on a pod which is on a master node, only master node will answer to requests (worker will timeout)

**To Reproduce**

1. Install k3s on a rpi at home

2. Install k3s on a cloud instance

3. Create a VPN with wireguard

4. Deploy k3s cluster on vpn

5. Add pod & service node port

6. Try to access them from node where pod isn't running => it should timeout.

**Expected behavior**

A pod should answer from any nodes with a service node port.

**Actual behavior**

Pod answers only from "local" nodes.

**Additional context**

```
$ kubectl get node -o wide
NAME     STATUS   ROLES    AGE   VERSION        INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                         KERNEL-VERSION   CONTAINER-RUNTIME
scw-01   Ready    master   25m   v1.17.3+k3s1   10.0.255.10   <none>        Debian GNU/Linux 9 (stretch)     4.9.0-12-amd64   containerd://1.3.3-k3s1
rpi-02   Ready    <none>   14m   v1.17.3+k3s1   10.0.255.21   <none>        Raspbian GNU/Linux 10 (buster)   4.19.97-v7l+     containerd://1.3.3-k3s1
rpi-03   Ready    <none>   14m   v1.17.3+k3s1   10.0.255.22   <none>        Raspbian GNU/Linux 10 (buster)   4.19.97-v7l+     containerd://1.3.3-k3s1
rpi-01   Ready    <none>   14m   v1.17.3+k3s1   10.0.255.20   <none>        Raspbian GNU/Linux 10 (buster)   4.19.97-v7l+     containerd://1.3.3-k3s1
```

VPN 10.0.255.0/24
```
k3s server --bind-address 10.0.255.10 --advertise-address 10.0.255.10 --node-ip 10.0.255.10 --node-name scw-01 --cluster-cidr 172.30.0.0/16 --service-cidr 172.31.0.0/16 --no-deploy traefik --flannel-backend wireguard
```

Flannel backend, cluster-cidr and service-cidr have no influence on issue.

**Comment by tanguyfalconnet** [comment]
Issue is comming from flannel I guess

**Comment by Mishuni** [comment]
I have also same problem when I use a flannel named vxlan and ipsec.

**Comment by phantomlsh** [comment]
I have the same problem as well.
