### ISSUE TITLE
Secrets should be encrypted at rest while using experimental --secrets-encryption flag

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/k3s#1558]
**Version:**
k3s -v
k3s version v1.17.4-alpha1+k3s1 (e5e7617a)

**K3s arguments:**
--secrets-encryption 

**Describe the bug**
Secrets should have been encrypted

**To Reproduce**
Install k3s passing --secrets-encryption flag
List the secrets and decode it with base64
```
kubectl get secrets --all-namespaces  -o json 
```
Confirm it is encrypted.

**Expected behavior**
Secrets should have been encrypted

**Actual behavior**
Secrets are not encrypted

**Comment by davidnuzik** [comment]
Notice, this is an experimental flag and the CLI help indicates so. We have plans post v1.17.4+k3s1 release to resolve this issue.

**Comment by galal-hussein** [comment]
kubectl decrypts the secret when it fetches it from the API, on verifying the secret from the database you can see that the secret has been encrypted correctly:
```
sqlite> select value from kine where name like "/registry/secrets/default/db-user-pass";
k8s:enc:aescbc:v1:aescbckey:�q�=x����51R"�O(,�-���d������A֚�����DĐ#A�}�Z�t

```

**Comment by amitkatyal** [comment]
I'm checking this feature on version 
$ k3s --version
k3s version v1.18.6+k3s1 (6f56fa1d)

Please see the steps followed and outcome,
1. Modified k3s systemd service file to pass --secrets-encryption flag to k3s server
2. Reload systemd daemon
3. Restart k3s serverice
4. Collected k3s logs and confirmed that addition encryption configuration flag is not being passed to kube-apiserver.

: time="2020-10-15T08:00:57.376535248+05:30" level=info msg="Running kube-apiserver --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=unknown --authorization-mode=Node,RBAC --basic-auth-file=/var/lib/rancher/k3s/server/cred/passwd --bind-address=127.0.0.1 --cert-dir=/var/lib/rancher/k3s/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --enable-admission-plugins=NodeRestriction --etcd-servers=unix://kine.sock --insecure-port=0 --kubelet-certificate-authority=/var/lib/rancher/k3s/server/tls/server-ca.crt --kubelet-client-certificate=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.crt --kubelet-client-key=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.key --proxy-client-cert-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt --proxy-client-key-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.key --requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6444 --service-account-issuer=k3s --service-account-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-account-signing-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-cluster-ip-range=10.43.0.0/16 --storage-backend=etcd3 --tls-cert-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt --tls-private-key-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.key"

5. Also, 
   created one secret with encryption enabled.
   disable the encryption
   read the secret via kubectl CLI and confirmed secret  returned was base64 encoded. This confirms that secrets were not 
   getting encrypted after enabling the encryption.

Please let me know if I am missing something. Thanks !!

**Comment by amitkatyal** [comment]
Another observation, If I pass the flag while manually starting the server - "k3s server --secrets-encryption, then it works fine".

**Comment by amitkatyal** [comment]
Does K3S supports secret encryption with external KMS ?
I checked RKE documentation and confirmed that secrets encryption with external KMS is supported but not sure about K3S. Please confirm. Thanks!!

**Comment by brandond** [comment]
@amitkatyal no, it uses a static encryption key
https://github.com/rancher/k3s/blob/master/pkg/daemons/control/server.go#L1033

**Comment by amitkatyal** [comment]
> @amitkatyal no, it uses a static encryption key
> https://github.com/rancher/k3s/blob/master/pkg/daemons/control/server.go#L1033

Thanks @brandond !!
One more related query, I checked encryption at rest with static configuration and seems to be getting enabled but how do I double confirm that data at rest is encrypted.

**Comment by amitkatyal** [comment]
> @amitkatyal no, it uses a static encryption key
> https://github.com/rancher/k3s/blob/master/pkg/daemons/control/server.go#L1033

@brandond , My requirement is to use "Custom configuration for at-rest data encryption" so that encryption key is not stored in clear on disk. Is there a way I can do with K3s ?. OR is it something planned for future release ? OR Can I modify the encryption configuration file generated by K3s ?

**Comment by brandond** [comment]
I haven't tested it and can't make any guarantees, but we haven't removed anything from the apiserver, so what you're describing should work.

**Comment by amitkatyal** [comment]
> I haven't tested it and can't make any guarantees, but we haven't removed anything from the apiserver, so what you're describing should work.

@brandond , I applied the configration as per above but after that k3s is not starting and throwing below error.

"failed to create connection to unix socket: /var/run/kmsplugin/socket.sock, error: dial unix /var/run/kmsplugin/socket.sock: connect: connection refused"

Does that mean kube-apiserver is expecting kms-plugin to be up and running ?. Any idea ?

**Comment by brandond** [comment]
This is all just upstream Kubernetes stuff - it does look like you are responsible for ensuring that the kms plugin is already running.

https://kubernetes.io/docs/tasks/administer-cluster/kms-provider/#deploying-the-kms-plugin
