### ISSUE TITLE
The invalid API group returned by the "k3s kubectl api-versions" should be cleaned up.

### ISSUE THREAD

**Issue by warmchang** [rancher/k3s#156]
**Describe the bug**
The invalid API group returned by the "k3s kubectl api-versions" should be cleaned up.

**To Reproduce**
Run "k3s kubectl api-versions", check the result.

**Expected behavior**
Print only the API group reserved by K3S.

**Screenshots**
N/A

**Additional context**
```
$ k version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3-k3s.6", GitCommit:"da4e14f160174f356b1d95198f48439971cc8a85", GitTreeState:"clean", BuildDate:"2019-02-24T05:21+00:00Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3-k3s.6", GitCommit:"da4e14f160174f356b1d95198f48439971cc8a85", GitTreeState:"clean", BuildDate:"2019-02-24T05:21+00:00Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
$
$ k api-versions
admissionregistration.k8s.io/v1beta1
apiextensions.k8s.io/v1beta1
apiregistration.k8s.io/v1
apiregistration.k8s.io/v1beta1
apps/v1
apps/v1beta1
apps/v1beta2
authentication.k8s.io/v1
authorization.k8s.io/v1
autoscaling/v1
autoscaling/v2beta2
batch/v1
batch/v1beta1
certificates.k8s.io/v1beta1
extensions/v1beta1
k3s.cattle.io/v1
networking.k8s.io/v1
policy/v1beta1
rbac.authorization.k8s.io/v1
rbac.authorization.k8s.io/v1beta1
scheduling.k8s.io/v1beta1
storage.k8s.io/v1
storage.k8s.io/v1beta1
v1
$
```

**Comment by ibuildthecloud** [comment]
Those look proper. Can you point to something that is wrong with that output?

**Comment by warmchang** [comment]
Is it possible to keep only the latest version of the resource group?

Fox example: just keep the "apps/v1" api group and delete the two previous versions (Not only print result, but also prune the [source](https://github.com/rancher/k3s/tree/v1.13.4-k3s.1/staging/src/k8s.io/api/apps/v1beta1) [code](https://github.com/rancher/k3s/tree/v1.13.4-k3s.1/staging/src/k8s.io/api/apps/v1beta2)).

> apps/v1
> apps/v1beta1
> apps/v1beta2

**Comment by ibuildthecloud** [comment]
@warmchang We delete as many old versions as we can without breaking large percentages of apps in the wild.  So we are fine with dropping alpha APIs and expecting people to just move forward, but specifically if I drop these apps/v1beta* APIs something like 80% of apps in the wild won't work.  So its a balance between dropping things and how much we make k3s incompatible.

**Comment by warmchang** [comment]
@ibuildthecloud Thank you for reply! I understood, we need to keep the balance.
