### ISSUE TITLE
enabled NVME support inside K3OS Kernel

### ISSUE THREAD

**Issue by danielsand** [rancher/k3s#1576]
**Is your feature request related to a problem? Please describe.**
i want to fresh install my home cluster on intel NUC's with NVME's with K3OS
Currently NVMe's cannot be used under K3OS - they're not detected - because no kernel support 
so no native k3os install :/

**Describe the solution you'd like**
Enable NVME support inside the Kernel + initrd image for K3OS

**Describe alternatives you've considered**
- building my own kernel + initrd an placing it on the stick (will fix my problem - but without contribution for others)
- installing a HD into the NUC'S (have no spare around currently)
- going sadly back to ubuntu / debian to run k3s :/

**Additional context**
if you give me some pointers into your CI and to build a PR to make it work - i would give it a shot.
Also it would be good to have enabled NVME support as default - in the IoT world i have seen some boards that have NVME's on them.

**Comment by dweomer** [comment]
@danielsand you've posted this to the issue tracker for k3s which k3OS is built on. Please notice https://github.com/rancher/k3os/issues/403 and post further communications regarding this issue there.
