### ISSUE TITLE
[Question] Does hyperkube in this repo also a pruned one?

### ISSUE THREAD

**Issue by gyliu513** [rancher/k3s#158]
I found that here are some explanation for `hyperkube` in k3s https://github.com/rancher/k3s#hyperkube , so does the `hyperkube` here a pruned one?

As I found that the binary of `hyperkube` was only 100+M, while the `hyperkube` from vanila k8s was 200+M. 

And alslo the code here for k8s seems also pruned https://github.com/rancher/k3s/tree/master/vendor/k8s.io/kubernetes ?

**Comment by ibuildthecloud** [comment]
The hyperkube is a compilation of the k8s source we use so it has all the same bits removed as k3s.

The source for it and the corresponding patches are referred to in vendor.conf in the root of this repo.

Currently the hyperkube by itself is not well tested. It should work by YMMV. Please file issues if something doesn't work. We will work on testing it more.

**Comment by gyliu513** [comment]
@ibuildthecloud can you please show some detail for how did you remove the useless code in https://github.com/rancher/k3s/tree/master/vendor/k8s.io/kubernetes ?

**Comment by erikwilson** [comment]
There is a lot of manual pruning involved, looking at the history of https://github.com/rancher/k3s/commits/k3s-v1.13.3 might help.

**Comment by gyliu513** [comment]
Thanks @erikwilson , this really helps!!
