### ISSUE TITLE
Adding k3s worker node to a microk8s master

### ISSUE THREAD

**Issue by ednaganon** [rancher/k3s#1588]
Hello,
I am trying to add a k3s worker node to a microk8s master node. On the k8s master node , using an add-node command gives the details how a worker should join itself:
$sudo microk8s.add-node
Join node with: microk8s.join 192.168.1.5:25000/gfjmzgrvBSGzhlsOeNvXmjfMUHzWwcdP

I try to use that with the k3s agent command:
k3s agent --server https://192.168.1.5:25000 --token gfjmzgrvBSGzhlsOeNvXmjfMUHzWwcdP

But i get errors:
INFO[2020-03-27T00:03:28.516672663Z] Starting k3s agent v1.17.2+k3s1 (cdab19b0)
INFO[2020-03-27T00:03:28.517230988Z] module overlay was already loaded
INFO[2020-03-27T00:03:28.517293986Z] module nf_conntrack was already loaded
INFO[2020-03-27T00:03:28.517316883Z] module br_netfilter was already loaded
INFO[2020-03-27T00:03:28.518174532Z] Running load balancer 127.0.0.1:37745 -> [192.168.1.5:25000]
ERRO[2020-03-27T00:03:30.495570567Z] failed to get CA certs at https://127.0.0.1:37745/cacerts: https://127.0.0.1:37745/cacerts: 404 NOT FOUND
ERRO[2020-03-27T00:03:33.481817338Z] failed to get CA certs at https://127.0.0.1:37745/cacerts: https://127.0.0.1:37745/cacerts: 404 NOT FOUND
ERRO[2020-03-27T00:03:36.187736563Z] failed to get CA certs at https://127.0.0.1:37745/cacerts: https://127.0.0.1:37745/cacerts: 404 NOT FOUND

If I use port 6443 I get the following error:
INFO[2020-03-27T00:04:09.658717519Z] Starting k3s agent v1.17.2+k3s1 (cdab19b0)
INFO[2020-03-27T00:04:09.659101326Z] module overlay was already loaded
INFO[2020-03-27T00:04:09.659137360Z] module nf_conntrack was already loaded
INFO[2020-03-27T00:04:09.659160079Z] module br_netfilter was already loaded
INFO[2020-03-27T00:04:09.659959118Z] Running load balancer 127.0.0.1:41885 -> [192.168.1.5:6443]
ERRO[2020-03-27T00:04:09.674260352Z] failed to get CA certs at https://127.0.0.1:41885/cacerts: Get https://127.0.0.1:41885/cacerts: read tcp 127.0.0.1:34464->127.0.0.1:41885: read: connection reset by peer
ERRO[2020-03-27T00:04:11.940360206Z] failed to get CA certs at https://127.0.0.1:41885/cacerts: Get https://127.0.0.1:41885/cacerts: read tcp 127.0.0.1:34476->127.0.0.1:41885: read: connection reset by peer
^CERRO[2020-03-27T00:04:14.275783678Z] failed to get CA certs at https://127.0.0.1:41885/cacerts: Get https://127.0.0.1:41885/cacerts: read tcp 127.0.0.1:34496->127.0.0.1:41885: read: connection reset by peer

Any idea?

Thanks, Edna

**Comment by brandond** [comment]
I haven't seen anything that would lead me to believe that microk8s and k3s clusters are interoperable. They use different methods for secrets exchange, and k3s does some interesting things to tunnel server/agent communications. Is there some reason in particular that you expected this to work?

**Comment by ednaganon** [comment]
I am checking a telecom edge/ IOT model, in which low-resource devices at the customer premises will run k3s, but the central management will be a full-blown k8s running at the central office, and building clusters of the remote nodes. Isn't this a viable scenario?

**Comment by cjellick** [comment]
The topology of k3s is fairly unique and requires both the server nodes and the agents be k3s. k3s agents are not plug-and-play with k8s distribution control planes.

That said, the k3s control plane is pretty full featured and robust. There is a good chance it might meet your needs back at the central office.

I'm going to close this issue since this isn't a supported scenario.
