### ISSUE TITLE
Traefik does not restart with the latest config after modifying `manifests/traefik.yaml`

### ISSUE THREAD

**Issue by imWildCat** [rancher/k3s#1609]
**Version:**

`v1.17.3+k3s1 (5b17a175)`

**K3s arguments:**

`curl -sfL https://get.k3s.io | sh -s - --docker`

**Describe the bug**

After modifying `traefik.yml`, the traefik service didn't restart.

**To Reproduce**

1. Modify `traefik.yml`
2. Observe whether the traefik pod restarts.

**Expected behavior**

It will restart.

**Actual behavior**

It never restarts.

**Additional context / logs**

Don't know how to collect related logs. Please let me know if needed.

**Comment by ShylajaDevadiga** [comment]
@imWildCat With the steps provided I am unable to repro the issue.  Could you provide the environment you are running the cluster on?
OS:
OS Version:
Docker Version:

Thanks

**Comment by imWildCat** [comment]
OS: `Ubuntu`
OS Version: `Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-72-generic x86_64)`
Docker Version: `Docker version 18.09.7, build 2d0083d`

I tried on two of my VPS and all can repro.

**Comment by niusmallnan** [comment]
@imWildCat Please try this format:
```
dashboard.enabled: "true"
acme.logging: "true"
```
Your configuration way cannot be recognized.

**Comment by imWildCat** [comment]
@niusmallnan You're right! Thank you so much!

Helm chart config only support the format that you replied with, right?
