### ISSUE TITLE
Connection to server refused on Raspberry Pi and Ubuntu Server

### ISSUE THREAD

**Issue by DhruvM94** [rancher/k3s#1619]
**Version:**

```k3s version v1.17.4+k3s1```

**Describe the bug**
When trying to execute any kubectl command the following output is generated:
```Error from server (ServiceUnavailable): the server is currently unable to handle the request (get nodes)``` or
```The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?```

**To Reproduce**
- Install Ubuntu Server (64-bit) on Raspberry Pi 4B
- Install k3s using ```curl -sfL https://get.k3s.io | sh -```

**Expected behavior**
A k3s cluster should be present.

**Actual behavior**
The kubectl command cannot reach the server.

**Additional context / logs**
As described above I am trying to setup a k3s-cluster on a Raspberry Pi running Ubuntu Server (64-bit) as the os.

**Comment by alekc** [comment]
What does syslog/journalctl says?

**Comment by DhruvM94** [comment]
@alekc thanks for the hint. It showed that ```cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory``` has not been inserted.
After appending the above to ```boot/firmware/nobtcmd.txt``` and ```/boot/firmware/btcmd.txt``` I was able to run the ```kubectl``` commands.
