### ISSUE TITLE
Improve docs - e.g., provide a link to the Rancher chart repository that is used by this automatic deployment service

### ISSUE THREAD

**Issue by jambajaar** [rancher/k3s#1634]
I have setup an automated deployment of a k3s cluster in my home lab and encountered gaps in the documentation. An example would be the k3s helm documentation about the automatically deployed manifests located at the directory path /var/lib/rancher/k3s/server/manifests. 

The documentation does not provide a link to the Rancher chart repository that is used by this automatic deployment service. 

Without a link to the charts that can be used there is no way to know which charts and the values to set for deployment. It's these little gotcha's that i find occasionally as I go through a deployment process. 

gz#9473

**Comment by brandond** [comment]
It doesn't pull them from a helm repo. They're bundled into the k3s binary, you can find them here:
https://github.com/rancher/k3s/tree/master/manifests
