### ISSUE TITLE
k3s.service   ExecStart error

### ISSUE THREAD

**Issue by char1st** [rancher/k3s#1645]
**Version:**
k3s: v1.17.4+k3s1
OS: CentOS Linux release 7.7.1908 (Core)

**Describe the bug**
copy https://github.com/rancher/k3s/blob/master/install.sh to local 
and run sh install.sh
/etc/systemd/system/k3s.service
[Unit]
Description=Lightweight Kubernetes
Documentation=https://k3s.io
Wants=network-online.target
[Install]
WantedBy=multi-user.target
[Service]
Type=notify
EnvironmentFile=/etc/systemd/system/k3s.service.env
KillMode=process
Delegate=yes
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
TimeoutStartSec=0
Restart=always
RestartSec=5s
ExecStartPre=-/sbin/modprobe br_netfilter
ExecStartPre=-/sbin/modprobe overlay
ExecStart=/usr/local/bin/k3s \ 
    server \

looks like need to  change  /usr/local/bin/k3s \ 
    server \
to /usr/local/bin/k3s  \ 
  server 

and looks like quote_indent bug in install.sh

**Comment by davidnuzik** [comment]
>looks like need to change /usr/local/bin/k3s \
server
to /usr/local/bin/k3s \
server

I tested with:
k3s: v1.17.4+k3s1
OS: CentOS Linux release 7.7.1908 (Core)

And followed the steps. In my case k3s starts and there is no ExecStart error. Perhaps something else is going on?

Anything interesting in logs when check via `journalctl -u k3s` ? Thanks!

**Comment by char1st** [comment]
pr 23 11:09:22 k3sm1 systemd[1]: [/etc/systemd/system/k3s.service:21] Trailing garbage, ignoring.
Apr 23 11:09:22 k3sm1 systemd[1]: k3s.service lacks both ExecStart= and ExecStop= setting. Refusing.
Apr 23 11:11:04 k3sm1 systemd[1]: k3s.service lacks both ExecStart= and ExecStop= setting. Refusing.
Apr 23 11:11:04 k3sm1 systemd[1]: k3s.service lacks both ExecStart= and ExecStop= setting. Refusing.
Apr 23 11:11:04 k3sm1 systemd[1]: k3s.service lacks both ExecStart= and ExecStop= setting. Refusing.

**Comment by brandond** [comment]
@char1st did you by any chance copy paste the contents of the shell script rather than downloading it from GitHub or https://get.k3s.io? It sure sounds like the script got munged somehow, and pasting with bad indentation or escapes would do that.

**Comment by char1st** [comment]
I diff my install.sh and download install.sh  and  found 
there is  a blank line  above the EOF  at 660 line  in download intall.sh file . So  I  append a blank line to my k3s.service file. It  works !  My mistake.  Thansk for you help.
