### ISSUE TITLE
Offline support

### ISSUE THREAD

**Issue by ibuildthecloud** [rancher/k3s#166]
It should be possible to run k3s with no internet access.  Image preloading would be the preferred approach right now to getting images, but next what prevents us from offline install is helm and upstream DNS not being configurable.

**Comment by uablrek** [comment]
With [containerd config template support](https://github.com/rancher/k3s/pull/248) it should be possible to re-direct pulls to a local insecure docker registry, which is [really easy](https://docs.docker.com/registry/deploying/) to setup. Just specify a mirror for the used registries;
```
[plugins.opt]
    path = "%OPT%"
[plugins.cri]
  stream_server_address = "%NODE%"
  stream_server_port = "10010"
[plugins.cri.registry.mirrors]
  [plugins.cri.registry.mirrors."docker.io"]
    endpoint = ["http://172.17.0.2:5000"]
```
I will try this myself as soon as I have learned how to re-build `k3s` with a PR applied.

**Comment by erikwilson** [comment]
@uablrek This issue is specifically for running air-gap using the images generated for the RC and placing them in the `/var/lib/rancher/k3s/agent/images/` directory.

We would like to provide better support for secure private registries but that is a different issue.

**Comment by uablrek** [comment]
Sorry, I thought the "no internet access" was the issue. Then if networking still works a local registry is more flexible than pre-pulled images IMHO. I have a similar problem when working with VMs on my laptop while on mobile internet but I realize this is a different problem.

**Comment by erikwilson** [comment]
@uablrek running a registry server is probably more overhead than we need for air-gap if we just want to load some pre-saved images into containerd.

**Comment by erikwilson** [comment]
Verified by rancher/k3s/issues/172
