### ISSUE TITLE
K3s install failed on ubun18 

### ISSUE THREAD

**Issue by modogo2000** [rancher/k3s#1663]
**Version:**
v1.17.4+k3s1
Ubuntu 18.04.4 

**K3s arguments:**
curl -sfL https://get.k3s.io | sh -s - server --datastore-endpoint="mysql://xxx:xxx@tcp(192.168.1.100:3306)/database" --no-deploy traefik --no-deploy

**Describe the bug**
server crash after
[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v1.17.4+k3s1/sha256sum-amd64.txt

I can't install k3s on my server ubuntu(18)  each time I try it failled at this step 
[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v1.17.4+k3s1/sha256sum-amd64.txt

**To Reproduce**
to reproduce : 
sudo curl -sfL https://get.k3s.io | sh -s - server --datastore-endpoint="mysql://xxx:xxx@tcp(192.168.1.100:3306)/database" --no-deploy traefik --no-deploy servicelb

**Expected behavior**
INstall k3s

**Actual behavior**
Installation not working

**Additional context / logs**

**Comment by brandond** [comment]
Could you maybe include the actual error message you're getting? Either from the install script or system log?

**Comment by modogo2000** [comment]
Hello,

I went to try the installation in order to get the log but the installation is working. I don't change anything juste restart the node.

**Comment by modogo2000** [comment]
After restart of the node the installtion is working . I didn't change anything

**Comment by modogo2000** [comment]
finaly I still have issue I try to instal on an other server 

`r 22 19:14:28 master3 kernel: [  295.751225] kernel BUG at /build/linux-UDHJtG/linux-4.15.0/drivers/net/vmxnet3/vmxnet3_drv.c:1441!
Apr 22 19:14:28 master3 kernel: [  295.751404] invalid opcode: 0000 [#1] SMP PTI
Apr 22 19:14:28 master3 kernel: [  295.751482] Modules linked in: vmw_vsock_vmci_transport vsock coretemp vmw_balloon joydev input_leds serio_raw shpchp mac_hid vmw_vmci sch_fq_codel ib_iser rdma_cm iw_cm ib_cm ib_core iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi ip_tables x_tables autofs4 btrfs zstd_compress raid10 raid456 async_raid6_recov async_memcpy async_pq async_xor async_tx xor raid6_pq libcrc32c raid1 raid0 multipath linear crct10dif_pclmul crc32_pclmul ahci hid_generic libahci ghash_clmulni_intel pcbc usbhid hid aesni_intel aes_x86_64 crypto_simd glue_helper cryptd psmouse vmwgfx ttm drm_kms_helper syscopyarea mptspi sysfillrect mptscsih sysimgblt fb_sys_fops mptbase vmxnet3 scsi_transport_spi drm i2c_piix4 pata_acpi
Apr 22 19:14:28 master3 kernel: [  295.752505] CPU: 5 PID: 0 Comm: swapper/5 Not tainted 4.15.0-96-generic #97-Ubuntu
Apr 22 19:14:28 master3 kernel: [  295.752638] Hardware name: VMware, Inc. VMware Virtual Platform/440BX Desktop Reference Platform, BIOS 6.00 04/05/2016
Apr 22 19:14:28 master3 kernel: [  295.752867] RIP: 0010:vmxnet3_rq_rx_complete+0x868/0xeb0 [vmxnet3]
Apr 22 19:14:28 master3 kernel: [  295.753001] RSP: 0018:ffff9a707fb43e20 EFLAGS: 00010297
Apr 22 19:14:28 master3 kernel: [  295.753112] RAX: 0000000000000001 RBX: ffff9a7075d6e150 RCX: ffff9a7075101700
Apr 22 19:14:28 master3 kernel: [  295.753240] RDX: 0000000000000013 RSI: 0000000000000040 RDI: 0000000000000003
Apr 22 19:14:28 master3 kernel: [  295.753365] RBP: ffff9a707fb43e88 R08: 0000000000000028 R09: 0000000000000000
Apr 22 19:14:28 master3 kernel: [  295.753617] R10: 0000000000000000 R11: ffff9a707b6cc8c0 R12: 0000000000000000
Apr 22 19:14:28 master3 kernel: [  295.753685] R13: ffff9a707b6cd600 R14: ffff9a7070d69000 R15: ffff9a7075d0c000
Apr 22 19:14:28 master3 kernel: [  295.753745] FS:  0000000000000000(0000) GS:ffff9a707fb40000(0000) knlGS:0000000000000000
Apr 22 19:14:28 master3 kernel: [  295.753811] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Apr 22 19:14:28 master3 kernel: [  295.753859] CR2: 00007f667c8f12c9 CR3: 00000000b3de8000 CR4: 00000000001006e0
Apr 22 19:14:28 master3 kernel: [  295.754009] Call Trace:
Apr 22 19:14:28 master3 kernel: [  295.754059]  <IRQ>
Apr 22 19:14:28 master3 kernel: [  295.754108]  vmxnet3_poll_rx_only+0x36/0xa0 [vmxnet3]
Apr 22 19:14:28 master3 kernel: [  295.756008]  net_rx_action+0x140/0x3a0
Apr 22 19:14:28 master3 kernel: [  295.757879]  __do_softirq+0xe4/0x2d4
Apr 22 19:14:28 master3 kernel: [  295.759773]  irq_exit+0xc5/0xd0
Apr 22 19:14:28 master3 kernel: [  295.761572]  do_IRQ+0x86/0xe0
Apr 22 19:14:28 master3 kernel: [  295.763372]  common_interrupt+0x8c/0x8c
Apr 22 19:14:28 master3 kernel: [  295.765070]  </IRQ>
Apr 22 19:14:28 master3 kernel: [  295.766736] RIP: 0010:native_safe_halt+0x12/0x20
Apr 22 19:14:28 master3 kernel: [  295.768353] RSP: 0018:ffffba15006bfe80 EFLAGS: 00000246 ORIG_RAX: ffffffffffffffd8
Apr 22 19:14:28 master3 kernel: [  295.770003] RAX: ffffffff8a3c0350 RBX: 0000000000000005 RCX: 0000000000000000
Apr 22 19:14:28 master3 kernel: [  295.771624] RDX: 0000000000000000 RSI: 0000000000000000 RDI: 0000000000000000
Apr 22 19:14:28 master3 kernel: [  295.773205] RBP: ffffba15006bfe80 R08: 00000044ef072900 R09: ffff9a7070c73200
Apr 22 19:14:28 master3 kernel: [  295.774723] R10: 0000000000000000 R11: 7fffffffffffffff R12: 0000000000000005
Apr 22 19:14:28 master3 kernel: [  295.776275] R13: 0000000000000000 R14: 0000000000000000 R15: 0000000000000000
Apr 22 19:14:28 master3 kernel: [  295.777770]  ? __sched_text_end+0x1/0x1
Apr 22 19:14:28 master3 kernel: [  295.779266]  default_idle+0x20/0x100
Apr 22 19:14:28 master3 kernel: [  295.780718]  arch_cpu_idle+0x15/0x20
Apr 22 19:14:28 master3 kernel: [  295.782091]  default_idle_call+0x23/0x30
Apr 22 19:14:28 master3 kernel: [  295.783576]  do_idle+0x172/0x1f0
Apr 22 19:14:28 master3 kernel: [  295.784843]  cpu_startup_entry+0x73/0x80
Apr 22 19:14:28 master3 kernel: [  295.786142]  start_secondary+0x1ab/0x200
Apr 22 19:14:28 master3 kernel: [  295.787391]  secondary_startup_64+0xa5/0xb0
Apr 22 19:14:28 master3 kernel: [  295.788560] Code: 00 00 00 00 00 e9 06 f9 ff ff 49 8d 7d 20 48 89 ce 4c 89 5d a8 4c 89 55 b0 e8 95 a0 11 ca 4c 8b 5d a8 4c 8b 55 b0 e9 e1 fa ff ff <0f> 0b 0f 0b 0f 0b 49 8b 47 08 49 89 85 48 01 00 00 48 8b 45 a0
Apr 22 19:14:28 master3 kernel: [  295.792132] RIP: vmxnet3_rq_rx_complete+0x868/0xeb0 [vmxnet3] RSP: ffff9a707fb43e20
Apr 22 19:14:28 master3 kernel: [  295.793468] ---[ end trace 10dc81c71882c97c ]---
`

**Comment by brandond** [comment]
Appears to be a bug in vmxnet3. Have you tried a different virtual nic, like e1000?

**Comment by modogo2000** [comment]
No I will try .

**Comment by brandond** [comment]
A little googling suggests this is a vmware bug:
https://www.suse.com/support/kb/doc/?id=000019330
https://kb.vmware.com/s/article/2151480

**Comment by modogo2000** [comment]
Hello,

I confirm it's vmware bug thank you for your help.

Best regards
