### ISSUE TITLE
QA: Validation tests to test SELinux label functionality

### ISSUE THREAD

**Issue by davidnuzik** [rancher/k3s#1671]
**Description:**
We plan to add support for SELinux to K3s in a future release. We should create validation tests that actually test label functionality for SELinux. Can work with Erik as needed.

**Additional context**
K8s conformance tests do not currently have good coverage for SELinux.

**Comment by ShylajaDevadiga** [comment]
Update on validating SELinux on k3s:
NodeOS: CentOS 7.8 and RHEL 7.8
k3s Version: v1.18.6+k3s1
1. SELinux is in Enforcing mode
3. SELinux is enabled in Containerd config 
```
cat /var/lib/rancher/k3s/agent/etc/containerd/config.toml  |grep enable
  enable_selinux = true
```
4. Processes have correct labels set.
```
ps -eZ | grep -E 'k3s|containerd|shim'
system_u:system_r:container_runtime_t:s0 10008 ? 00:00:04 containerd-shim
system_u:system_r:container_runtime_t:s0 10188 ? 00:00:04 containerd-shim
system_u:system_r:container_runtime_t:s0 10323 ? 00:00:04 containerd-shim
system_u:system_r:container_runtime_t:s0 28948 ? 00:11:03 k3s-server
system_u:system_r:container_runtime_t:s0 28961 ? 00:00:47 containerd
 ps -eZ |grep coredns
system_u:system_r:container_t:s0:c487,c686 10095 ? 00:00:46 coredns
ps -eZ |grep nginx
system_u:system_r:container_t:s0:c237,c399 30433 ? 00:00:00 nginx

```

**Comment by ShylajaDevadiga** [comment]
Conformance test results are tracked here #1960
