### ISSUE TITLE
allow server to use windows volume guid paths

### ISSUE THREAD

**Issue by KnicKnic** [rancher/k3s#1687]
**NOTE:**
Is waiting for https://github.com/rancher/k3s/issues/1662 (v1.19.0 bump) to first complete.

**Version:**

k3s.exe version dev (HEAD)

**K3s arguments:**

`.\k3s.exe server -d "\\?\Volume{26a21bda-a627-11d7-9931-806e6f6e6963}\tmp\k3s" --flannel-backend none --docker  --kube-proxy-arg "proxy-mode=userspace" --disable-network-policy --disable-agent`

**Describe the bug**

Windows is somewhat tolerant of paths in the format of `c:\tmp/k3s` however it is not tolerant of paths in the format of `\\?\Volume{26a21bda-a627-11d7-9931-806e6f6e6963}\tmp/k3s`. 

This bug is to ensure that correct path manipulation functions are used. This will allow using volume guid paths, rather than drive letters.

**Expected behavior**
k3s starts server when using a windows volume guid path

**Actual behavior**
failure.

**Additional context / logs**
I will be submitting PR's for this issue.

**Comment by KnicKnic** [comment]
@davidnuzik can you add this to the  v1.19.0+k3s1 milestone (v1.19.0 is the release that the cert fix in the kubernetes client-go package should be in)

**Comment by davidnuzik** [comment]
@KnicKnic I'm assuming this is something you can take? If so I'm happy to put in that milestone (and have done so). Right now our team doesn't have cycles to take this on.
BTW thanks again for your contributions -- we appreciate it.

**Comment by KnicKnic** [comment]
@davidnuzik I believe all the code to be complete, however it will require the 1.19 update like I said to pickup the updated kubernetes client code.

In my testing the change to dynamic listener did not seem to be required, but I made it anyways for completeness. 

Mainly I wanted the 1.19 tag to track this issue and come back to it as there is nothing actionable till then.

**Comment by davidnuzik** [comment]
Depends on https://github.com/rancher/k3s/issues/1662

**Comment by rancher-max** [comment]
Closing this as we don't fully validate windows yet and @KnicKnic is handling it very well. I have not seen any regressions as a part of these changes. The changes are merged into the branch associated with the milestone so should be available for anyone who needs them either in the v1.19 rc or master commit.
