### ISSUE TITLE
List of ENVIRONMENT VARIABLES that would tune the behavior of k3s docker-compose.yml file ... 

### ISSUE THREAD

**Issue by nmvega** [rancher/k3s#1698]
Hello Friends:

I'm using the below `docker-compose.yml` file -- obtained [here](https://github.com/rancher/k3s/blob/master/docker-compose.yml) -- to launch a `k3s` cluster with `qty. 1-master` and `qty 3-nodes / agents`:

user$ `docker-compose up -d --scale agent=3`

Where do I find the list of **ENVIRONMENT VARIABLES** and their meanings, available to tweak the behavior of the `server` and `agents` in a `docker-compose.yml` **k3s** implementation (like below)?

PS: I tried looking for the `Dockerfile` used to build the below, but there are few, so I'm unsure which to refer to. But whether a `Dockerfile` or list of **ENVIRONMENT VARIABLES** that the below would respect, would be helpful.

Thank you in advance! =:)

```
# docker-compose.yml

# to run define K3S_TOKEN, K3S_VERSION is optional, eg:
#   K3S_TOKEN=${RANDOM}${RANDOM}${RANDOM} docker-compose up

version: '3'
services:

  server:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    command: server
    tmpfs:
    - /run
    - /var/run
    privileged: true
    environment:
    - K3S_TOKEN=${K3S_TOKEN:?err}
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
    volumes:
    - k3s-server:/var/lib/rancher/k3s
    # This is just so that we get the kubeconfig file out
    - .:/output
    ports:
    - 6443:6443

  agent:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    tmpfs:
    - /run
    - /var/run
    privileged: true
    environment:
    - K3S_URL=https://server:6443
    - K3S_TOKEN=${K3S_TOKEN:?err}
   #- K3S_NODE_NAME=k3s-Node

volumes:
  k3s-server: {}

```

**Comment by nmvega** [comment]
For instance (though not the only reason for my question), I'd like to construct `docker-compose.yml` to have these components resolve to proper names. But I digress. There are other reasons to know the ENVIRONMENT VARIABLES, too. Thanks!

```
user$ kubectl get nodes
7ae0125b3573   Ready    <none>   11m   v1.17.4+k3s1
3be693b33fd8   Ready    <none>   11m   v1.17.4+k3s1
b6f1efb9fd7e   Ready    master   11m   v1.17.4+k3s1
381a3f025125   Ready    <none>   11m   v1.17.4+k3s1
```

**Comment by brandond** [comment]
You mean the environment variables documented here:
https://rancher.com/docs/k3s/latest/en/installation/install-options/#options-for-installation-with-script

**Comment by nmvega** [comment]
Hi. Thanks. I read that page, and those definitely apply when starting `k3s` via the means described on that page (i.e. `CLI` and `curl(1)`), but I'm not sure (and the page does not mention) if those variables carry through when launching via `docker-compose(1) up`. For instance, I did try removing `INSTALL_` from `INSTALL_K3S_NAME` (from the page you cited) to set a `Node` name, but that didn't work. It was actually `K3S_NODE_NAME` that worked, which I found elsewhere -- [here (agent)](https://rancher.com/docs/k3s/latest/en/installation/install-options/agent-config/) and [here (server)](https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/) -- by refining my search to include `docker` in it.

I'll definitely scrape whatever those two pages have, but was hoping there was a definitive list for `docker-compose` launch model; or absent that, a `Dockerfile` I could crawl through. :)

**Comment by brandond** [comment]
The Dockerfile is [here](https://github.com/rancher/k3s/blob/master/package/Dockerfile) but I'm not sure that'll help you much - most of the options that you can pass to the install script via environment variables just end up getting written into the systemd unit or what have you. If you're running k3s in docker, those options would probably be best passed as direct arguments to `k3s server` or `k3s agent`.

**Comment by nmvega** [comment]
You're correct. Since we last had coffee, I interactively `docker exec`ed into running the `agent` and `server` containers to have a look, and that's exactly they will be consumed (by `k3s agent | server`. But this definitely helps me though, so thank you. I appreciate it!
