### ISSUE TITLE
Unable to attach or mount volumes

### ISSUE THREAD

**Issue by liyongxian** [rancher/k3s#1705]
**Version:**

**k3s version v1.17.4+k3s1 (3eee8ac3)**
**K3s arguments:**

**server  --no-flannel**
**Describe the bug**

**To Reproduce**

1.Deploy provisioner of glusterfs in K3s;
2.Create pvc by storageclass of glusterfs,it is ok.
3.Create a Pod,which mounts  by PVC, the pod's status is ContainerCreating.it happens FailedMount.
4.Describe the pod,The error info is 
**Warning  FailedMount  52m                    kubelet, agent-1   Unable to attach or mount volumes: unmounted volumes=[data default-token-7gxd4], unattached volumes=[data default-token-7gxd4]: failed to get Plugin from volumeSpec for volume "pvc-f1007597-2104-4d1a-8af3-52bef3865d8b" err=no volume plugin matched**
Thanks.
**Expected behavior**

**Actual behavior**

**Additional context / logs**

**Comment by liyongxian** [comment]
Describe node ,the node's annotations:
**volumes.kubernetes.io/controller-managed-attach-detach: "true"**
Why does it annotation? it cannot work.

**Comment by brandond** [comment]
Volume plugins are no longer recommended, and I've seen a couple other folks report issues getting k3s to load them properly. You might try using a CSI driver instead, as storage plugins are deprecated.

Unfortunately it seems like the Gluster CSI driver is dead and there's no replacement, so you GlusterFS might not be a good choice for a new deployment. Maybe look at rook.io or kadalu?

**Comment by liyongxian** [comment]
@brandond Thanks.I Add glusterfs plugins in K3s,and Rebuild it.Can Create pvc by StorageClass of Glusterfs.However, it does not Resize The PVC.How Can I Do?

**Comment by liyongxian** [comment]
The issue can close.Thanks.
