### ISSUE TITLE
Can't compile without access to gs://k3s-ci-builds 

### ISSUE THREAD

**Issue by AkihiroSuda** [rancher/k3s#1707]
**Version:**

690a4ca7a4eb55d373f9390475842943e067df30

**Describe the bug**

https://github.com/rancher/k3s/blob/690a4ca7a4eb55d373f9390475842943e067df30/scripts/package-cli#L62-L64

**Expected behavior**

Compilation should be possible without access to `gs://k3s-ci-builds` for running `build-upload`

**Actual behavior**

Can't compile without access to `gs://k3s-ci-builds`

**Comment by brandond** [comment]
I've been building k3s from source regularly to test things and have never run into this. What command are you running to start the build that's triggering this issue?

**Comment by AkihiroSuda** [comment]
Sorry, it seems I'm not hitting this actually, but this issue seems still problematic when GCLOUD_AUTH is set to unexpected value

https://github.com/rancher/k3s/blob/690a4ca7a4eb55d373f9390475842943e067df30/scripts/build-upload#L3

**Comment by brandond** [comment]
Seems reasonable that the build script tries to upload to gcloud when gcloud is configured. I tend to run my builds in a clean environment anyway just to make sure there are no external factors influencing the build.
