### ISSUE TITLE
Document RancherOS installation

### ISSUE THREAD

**Issue by ibuildthecloud** [rancher/k3s#173]
Information needed to install k3s is current in https://github.com/rancher/k3s/issues/73#issuecomment-469413149 and should be put in the README.md

**Comment by curx** [comment]
make it sense add these yaml file to https://github.com/rancher/os-services/tree/master/k as well, or it's only for os services?

**Comment by ibuildthecloud** [comment]
@curx that's a good idea to just create k3s as a system service in rancheros.  I'll see if that make sense for the RancherOS team to support.

**Comment by cjellick** [comment]
we arent going to support this

**Comment by Goldenstarc** [comment]
> we arent going to support this

So rancherOS can be used only for single docker image ? not docker-compose,  k3s and k8s clusters ?
