### ISSUE TITLE
Masterless K3s - server with only control plane

### ISSUE THREAD

**Issue by KnicKnic** [rancher/k3s#1734]
**Is your feature request related to a problem? Please describe.**
I want to leverage an external HA platform to do HA of the kubernetes control plane. As this can float between different nodes, I do not wish to register those nodes when starting the control plane.

I have 2 nodes A&B
K3s floats between nodes A&B with control plane componentry but does not run kubelet or kube-proxy.
Nodes A & B both separately run k3s agent connected to the floating control plane

**Describe the solution you'd like**
Due to https://github.com/rancher/k3s/pull/1695 making kube-proxy optional, I think I would only need kubelet.exe as optional as well.

Not sure is anything else needed?

**Describe alternatives you've considered**
Traditional model of kubernetes HA. ETCD on 3+nodes & control plane HA - does not support 2 node well

**Additional context**
There exists HA platforms that allow you to use 2 nodes plus an external witness. I would like to be able to leverage these.

**Comment by brandond** [comment]
There is a hidden `--disable-agent` option to `k3s server` that you might try, if you haven't yet.

https://github.com/rancher/k3s/blob/master/pkg/cli/cmds/server.go#L287

**Comment by KnicKnic** [comment]
> There is a hidden `--disable-agent` option to `k3s server` that you might try, if you haven't yet.
> 
> https://github.com/rancher/k3s/blob/master/pkg/cli/cmds/server.go#L287

Is this deprecated and going to get removed, or just hidden?

**Comment by brandond** [comment]
It's not described as deprecated like several other options are, so I would say just hidden.

**Comment by brandond** [comment]
Note that k8s does not have any sort of quorum requirement, just etcd. You could just run a 3 node etcd cluster and point however many k3s nodes you have at that.
