### ISSUE TITLE
crictl generating error on run

### ISSUE THREAD

**Issue by bjornramberg** [rancher/k3s#174]
**Describe the bug**
crictl is generating the following:
`FATA[date] failed to connect: failed to connect: context deadline exceeded`

**To Reproduce**
```
me@k8s1:~ $ k3s crictl version
NAME:
   crictl version - Display runtime version information

USAGE:
   crictl version [arguments...]
FATA[2019-03-06T20:52:59.197614183+01:00] failed to connect: failed to connect: context deadline exceeded 
me@k8s1:~ $ 
```

**Additional context**
Fresh install of Raspbian, k3s installed with installer.
```
me@k8s1:~ $ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 9.4 (stretch)
Release:        9.4
Codename:       stretch
```

```
me@k8s1:~ $ uname -a
Linux k8s1 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux
```

**Comment by ibuildthecloud** [comment]
crictl must be ran as root. We should add a check and error out of not root.

**Comment by bjornramberg** [comment]
Was expecting to see version without running elevated :)
Yes, a error msg if not run as root would be great.
Closing, cheers!
