### ISSUE TITLE
Arm64 arch for k8s.gcr.io/pause:3.1 ?

### ISSUE THREAD

**Issue by koehoorn** [rancher/k3s#176]
Coredns and helm-install-traefik fail to run :

Events:
  Type     Reason                  Age                     From             Message  ----     ------                  ----                    ----             -------  Warning  FailedCreatePodSandBox  3m41s (x2182 over 10h)  kubelet, node01  Failed create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox image "k8s.gcr.io/pause:3.1": failed to pull image "k8s.gcr.io/pause:3.1": failed to pull and unpack image "k8s.gcr.io/pause:3.1": failed to unpack image on snapshotter overlayfs: no match for platform in manifest sha256:f78411e19d84a252e53bff71a4407a5686c46983a2c2eeed83929b888179acea: not found

**Comment by ibuildthecloud** [comment]
What version are you running? v0.1.0 or v0.2.0-rcX? This could be a regression in 0.2.

**Comment by koehoorn** [comment]
I'm using k3s referenced from k3s.io , 0.1.0-initial release. I see there are newer builds, I'll will try a few today.
Here's some more details:
https://paste.ubuntu.com/p/49FvHNsGKG/

**Comment by ibuildthecloud** [comment]
@koehoom Hmm... I'll test arm64 now, but previously v0.1.0 for sure worked on arm64.  We did fix [issues](https://github.com/containerd/containerd/pull/2992) in this area with containerd so this is probably a legit containerd bug.

**Comment by ibuildthecloud** [comment]
@koehoorn I just tested v0.1.0 on a AWS a1 instance and it worked.  I'm guess there is something platform specific here.  What is your setup?  `uname -a`?

**Comment by koehoorn** [comment]
Hi,

my nodes are the first type of pine64 2gb,
Uname reports:

Ubuntu 16.04.6 LTS (GNU/Linux 3.10.105-bsp-1.2-ayufan-118 aarch64

But the nodes architecture is correctly labeled as arm64.

Also see the error and info on the pastebin.


Either the arm64 arch is really not defined in the pause image
manifest, but I don't have and could you compile manifest-tool to test
this.

Or it is using the uname -m output and aarch64 is not defined in the manifest.

Or the error is lying and there is another reason to fail.


Haven't got the time yet to try newer builds. I'll try now

**Comment by koehoorn** [comment]
Armv8-a instruction set should be called aarch64 build Target.

Historically
Apples name for build target in their backend llvm was called arm64 and gnu build tools called it aarch64.

After apple opensourced their compiler the code was merged and all arm64 target names got replaced by aarch64. This was almost 5 years ago.

https://github.com/llvm-mirror/llvm/commit/29f94c72014eaa5d0d3b920686e689e79759cacb

And today this old name arm64 aperantly is still used and possibly causing this bug.

**Comment by kalinkrustev** [comment]
Docker-ce 18.9.3 has the same issue with pulling images on pine64. It can't find images, saying "unknown" platform. Still `docker pull --platform arm64 <image>` works. So the images exists, just there is some bug related to recognizing the platform.

**Comment by kalinkrustev** [comment]
The issue may be related to the `proc/cpuinfo` returning `AArch64` for `CPU architecture`, instead of what is expected [here](https://github.com/containerd/containerd/blob/master/platforms/cpuinfo.go#L99).
```sh
~$ cat /proc/cpuinfo 
Processor       : AArch64 Processor rev 4 (aarch64)
processor       : 0
processor       : 1
processor       : 2
processor       : 3
Features        : fp asimd aes pmull sha1 sha2 crc32 
CPU implementer : 0x41
CPU architecture: AArch64
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4
```

**Comment by deniseschannon** [comment]
We have made the pause image configurable as of v0.5.0. Can you please open a new issue if you are still having issues?
