### ISSUE TITLE
Fail to run k3s using TLS mysql when server cert doesn't contain any IP SANs

### ISSUE THREAD

**Issue by gitlawr** [rancher/k3s#1763]
**Version:**
v1.17.4+k3s1 (3eee8ac3)

**K3s arguments:**
``` 
--datastore-endpoint="mysql://<user>:<password>@tcp(<IP>:3306)/database" --tls-san <IP2> \
  --datastore-cafile=<ca.pem> --datastore-certfile=<client-cert.pem> \
  --datastore-keyfile=<client-key.pem> 
```

**Describe the bug**
k3s server command failed, error logs from journald:
```
k3s[30781]: time="2020-05-06T13:50:38.910630084Z" level=fatal msg="starting kubernetes: preparing server: creating storage endpoint: building kine: x509: cannot validate certificate for <IP> because it doesn't contain any IP SANs"
```
However, I'm able to connect the database using mysql-client

**To Reproduce**
1. provision an ubuntu18.04 instance in AWS.
2. set up mysql
```
$ sudo apt-get update && sudo apt-get install -y mysql-server mysql-client
$ sudo mysql_secure_installation
# use the install tool in the mysql-server package with the following options
# no validate password plugin
# remove anonymous users
# disallow root login remotely
# remove test database 
```
```
$ sudo vi /etc/mysql/my.cnf
# Add the following configs
[mysqld]
# Require clients to connect either using SSL or through a local socket file
require_secure_transport = ON
bind-address = 0.0.0.0


$ sudo systemctl restart mysql
```
3. configure db, user and auth
```
$ sudo mysql -u root -p
mysql> CREATE USER 'testuser'@'%' IDENTIFIED BY 'password';
mysql> GRANT ALL PRIVILEGES ON *.* TO 'testuser'@'%';
mysql> ALTER USER 'testuser'@'%' REQUIRE X509;
mysql> FLUSH PRIVILEGES;
mysql> create database example;
mysql> SHOW VARIABLES LIKE '%ssl%';
+---------------+-----------------+
| Variable_name | Value           |
+---------------+-----------------+
| have_openssl  | YES             |
| have_ssl      | YES             |
| ssl_ca        | ca.pem          |
| ssl_capath    |                 |
| ssl_cert      | server-cert.pem |
| ssl_cipher    |                 |
| ssl_crl       |                 |
| ssl_crlpath   |                 |
| ssl_key       | server-key.pem  |
+---------------+-----------------+
9 rows in set (0.01 sec)
```
4. Check access to the database
```
# get certs from /var/lib/mysql
$ mysql -u testuser -p -h <IP> --ssl-ca=ca.pem --ssl-cert=client-cert.pem --ssl-key=client-key.pem
```
5. run k3s
```
curl -sfL https://get.k3s.io | sh -s - server \
  --datastore-endpoint="mysql://<user>:<password>@tcp(<IP>:3306)/database" --tls-san <IP2> \
  --datastore-cafile=<ca.pem> --datastore-certfile=<client-cert.pem> \
  --datastore-keyfile=<client-key.pem> 
```

**Expected behavior**
Be able to run k3s using the mysql instance. 
Or provide additional flags to help pass the certificate validation.

**Additional context / logs**

k3s runs successfully when IP SANs are added to the certificate. For example:
```
$ echo subjectAltName = IP:192.168.1.1 > extfile.cnf
$ openssl req -newkey rsa:2048 -days 3600 \
        -nodes -keyout server-key.pem -out server-req.pem
$ openssl rsa -in server-key.pem -out server-key.pem
$ openssl x509 -req -in server-req.pem -days 3600 \
        -CA ca.pem -CAkey ca-key.pem -set_serial 01 -out server-cert.pem -extfile extfile.cnf
$ chown mysql:mysql *.pem && mv *.pem /var/lib/mysql/
$ sudo systemctl restart mysql
```

IP SANs are usually not set following MySQL docs to generate certs: https://dev.mysql.com/doc/refman/5.7/en/creating-ssl-rsa-files.html

**Comment by brandond** [comment]
This doesn't appear to be a k3s issue. The error you're getting is from the golang core crypto library:
https://github.com/golang/go/blob/master/src/crypto/x509/verify.go#L122

You need to either disable certificate validation, use the hostname instead of the IP address in the datastore address, or add the IP address to the SANs on the cert.

**Comment by gitlawr** [comment]
I was wondering if we can have additional configurations, such as servername in tlsConfig.
I think your suggestion makes sense.

**Comment by xuwang** [comment]
See the comments from Google Could SQL Team: https://stackoverflow.com/questions/33878356/certificate-validation-on-cloud-sql
It would be nice to have an option to turn off only `hostname` validation.

**Comment by up9cloud** [comment]
@brandond I tried to skip verification, but it does not work `--datastore-endpoint="mysql://<user>:<password>@tcp(<IP>:3306)/database?tls=skip-verify"` (https://github.com/go-sql-driver/mysql#tls)

@gitlawr can reopen this issue? (for requesting `ServerName` in tlsConfig...)
