### ISSUE TITLE
How to use the built-in database kine？

### ISSUE THREAD

**Issue by kingfeiyu1** [rancher/k3s#1776]
We want to use the built-in database kine to save data！！！

**Comment by brandond** [comment]
Kine with the built-in sqlite database is used by default unless you configure something else. You can us an external database (mysql/postgres) which still uses kine, since kine is a translation layer between the etcd api and a sql backend. You can also use a traditional etcd backend if you want.

**Comment by davidnuzik** [comment]
Additionally, you can check out the docs here https://rancher.com/docs/k3s/latest/en/installation/
