### ISSUE TITLE
Add automation to import k3s cluster into rancher

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/k3s#1778]
This issue is created for tracking purpose of the task.

**Comment by ShylajaDevadiga** [comment]
PRs
https://github.com/rancher/rancher/pull/26882
https://github.com/rancher/rancher/pull/26983

**Comment by ShylajaDevadiga** [comment]
Both PRs are merged. Closing task.

**Comment by memelet** [comment]
Is the means for this automation documented anywhere?
