### ISSUE TITLE
Error 413 in load balancer

### ISSUE THREAD

**Issue by Serrvosky** [rancher/k3s#1779]
**Version:**
k3s version v1.17.4+k3s1 (3eee8ac3)

**K3s arguments:**
/usr/local/bin/k3s server --node-ip 10.168.63.22 --node-external-ip 10.168.63.22

**Describe the bug**
I'm using k3s to deploy my web applications, and I noticed that in uploads of files bigger that 1mb, I was always getting as 413 error. After some debug and research I found that the problem is in 
 rancher/klipper-lb that k3s deploys everytime that I expose traefik in port 80.

To test this, I use Postman to perform the calls, and if I make a port-forward from my machine port XXX to port 80 of traefik, directly, everything works, but not with those load balancers. I tryed to check if there are any variables or configs to change limit buffering size or something similar, but no luck.

How can I workaround this? One small thing, I check k3s docs, and found that I could deploy k3s cluster with this --no-deploy servicelb, what I didn't, but I can't restart my cluster, because I have a lot of deploy there

Thanks

**Comment by brandond** [comment]
klipper-lb just configures iptables on the node to forward traffic to your service; it doesn't actually process the requests and is incapable of generating HTTP errors. If you're getting a 413 error that would probably be coming from either the traefik ingress, or your web framework.

**Comment by Serrvosky** [comment]
@brandond, I found my problem. It was another reverse proxy in my network.... what a debug afternoon...

Thnaks a lot for your reply
