### ISSUE TITLE
Add k8s version in release info

### ISSUE THREAD

**Issue by daixiang0** [rancher/k3s#178]
Now in release info, does not record k8s version, which make users confused when use an over-version API, comment it clearly then users will know which API they can use or not.

**Comment by ibuildthecloud** [comment]
Are you asking that we clearly state which kubernetes version is packaged in each release?

**Comment by daixiang0** [comment]
@ibuildthecloud yes, it is what i mean.

**Comment by daixiang0** [comment]
any update?

**Comment by deniseschannon** [comment]
In v0.3.0, we announced which k8s version: https://github.com/rancher/k3s/releases/tag/v0.3.0

but after you get k3s up, you should be able to do `kubectl version` to print out what version of k8s it's based on.

**Comment by daixiang0** [comment]
@deniseschannon maybe highlight the k8s version is better for users.
