### ISSUE TITLE
VarEnv shared among all pods of the same namespace

### ISSUE THREAD

**Issue by bflorat** [rancher/k3s#1780]
**Version:**
k3s version v1.17.3+k3s1 (5b17a175)

**K3s arguments:**
INSTALL_K3S_EXEC="--no-deploy traefik"

**Describe the bug**
I deployed several pods in 'default namespace'. When I log in any pod, I can see Kube EnvVar of the others pods of the same namespace. I don't know if it is done purposely but it appears as a major security flaw to me...

**To Reproduce**
kubectl exec -it pod1 -- /bin/sh
$ set
APP_VARRENV_POD1=...
APP_VARRENV_POD2=...

**Expected behavior**
Pod 1 can see only its own EnvVar...

**Actual behavior**
Pod 1 can see EnvVar of the others pods.

**Comment by brandond** [comment]
Which environment variables do you believe it's sharing between pods? Are you sure you're not just seeing the namespace service address and port variables?

**Comment by bflorat** [comment]
Exactly, sorry, I didn't figure out that only 
APP1_PORT_80_TCP='tcp://10.43.135.175:80'
APP1_PORT_80_TCP_ADDR='10.43.135.175'
...

Env vars were shared, not custom ones. 

I suppose this is a regular internal K8S mechanism ?

Thanks for pointing this out, I close this.
