### ISSUE TITLE
Defineable log/download paths

### ISSUE THREAD

**Issue by rockaut** [rancher/k3s#1782]
I'm on a RPi4 and have changed my /var/log to be on tmpfs (also /tmp) and that's causing me two troubles with k3s.

- first, the download fails (silently) as it always tries to download to /tmp (mktemp) first
- second, /var/log is full in no time

It would be cool if we could define these two folders freely.

**Comment by brandond** [comment]
1. Why has changing your /var/log to tmpfs broken mktemp? Did you also change something else that broke this? I think it's reasonable to expect mktemp to be functional. 

1. The container logs path appears to be hardcoded in the kubelet: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L131 - Your best bet is to make /var/log/containers and /var/log/pods symlinks to somewhere else.

**Comment by rockaut** [comment]
It's not broken because auf k3s but because I made it somewhat small ( just 30 MB ).
I already made the symlinks. Not only that but I also symlinked /var/lib/rancher as a whole to the usb.

Ok i see... so I guess it's not in k3s hands. Thx.
