### ISSUE TITLE
CoreDNS and Traefik pods don't start (iptables)

### ISSUE THREAD

**Issue by g574** [rancher/k3s#1801]
**Version:**
k3s version v1.17.4+k3s1 (3eee8ac3)

**K3s arguments:**

k3s server --pause-image k8s.gcr.io/pause:3.1 --resolv-conf=/etc/resolv.conf --cluster-cidr=172.17.0.0/16 --service-cidr=172.18.0.0/16 --tls-san=<ip of the server>

**Describe the bug**
I installed K3s on a CentOS 7 machine (manually, not with the script).
CoreDNS and Traefik pods do not start. They are either "Running" with 0/1 containers ready or in a "CrashLoopBackOff" state.

**To Reproduce**
Start K3s server with provided flags.

**Expected behavior**
CoreDNS and Traefik should be Running (READY 1/1)

**Actual behavior**
CoreDNS and Traefik pods do not start.

**Additional context / logs**
Traefik error message in the log:
```
1 reflector.go:205] github.com/containous/traefik/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1.Service: Get https://172.18.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 172.18.0.1:443: i/o timeout
```
CoreDNS error message:
```
 pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Service: Get https://172.18.0.1:443/api/v1/services?limit=500&resourceVersion=0:
dial tcp 172.18.0.1:443: i/o timeout

```
(Sometimes I see this: `[INFO] SIGTERM: Shutting down servers then terminating`.)

I know there have been many similar cases (e.g. https://github.com/rancher/k3s/issues/24) and I tried to implement those solutions, but it did not solve the problem.
I am using CentOS 7 with iptables (`iptables v1.4.21`).
Policies:
INPUT DROP
FORWARD ACCEPT
OUTPUT DROP
I tried to apply the solution from issue #24 like this: `iptables -I INPUT 1 -i cni0 -s 172.17.0.0/16 -j ACCEPT` but the issue persists.
Some more info:
```
cat /run/flannel/subnet.env
FLANNEL_NETWORK=172.17.0.0/16
FLANNEL_SUBNET=172.17.0.1/24
FLANNEL_MTU=1450
FLANNEL_IPMASQ=true
```
```
 cat /proc/sys/net/ipv4/ip_forward
1
```
I tried this from the host:
```
curl --noproxy '*' -k "https://172.18.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0"
```
- it hangs forever.
If I turn off iptables then these pods start but it is not a good solution for me unfortunately.

**Comment by samirsss** [comment]
If possible the recommendation is to upgrade iptables to version > 1.6.1 https://rancher.com/docs/k3s/latest/en/known-issues/

**Comment by jbutler992** [comment]
Thats confusing guidance since iptabpes 1.8+ on distros such as fedora 31 use nftables and dont appear to work. I switched to centos 7 and my issues have gone away with the lower iptables versions

**Comment by g574** [comment]
@samirsss , thanks for the advice. I have updated to iptables v1.6.2. The original error message is gone, but now I get this:
```
Readiness probe failed: Get http://172.17.0.41:8181/ready: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```
This still has something to do with iptables, if iptables is turned off it works again.

**Comment by g574** [comment]
I have figured out I needed a rule like this, as well:
`iptables -I OUTPUT 1 -s 172.17.0.0/16 -j ACCEPT`
Problem solved.
