### ISSUE TITLE
Unit k3s.service has failed -- Defined-By: systemd  for a k3s with external DB

### ISSUE THREAD

**Issue by Rajakavitha1** [rancher/k3s#1805]
**Version:**

**K3s arguments:**
export K3S_DATASTORE_ENDPOINT="mysql://rajie:password@tcp(mysql.rajie.wiki:3306)/rancher"
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig-mode 644 -t agent-secret --tls-san k3s.rajie.wiki --node-taint k3s-controlplane=true:NoExecute" sh -s - server

**Describe the bug**

```
[INFO]  Finding release for channel stable
[INFO]  Using v1.18.2+k3s1 as release
[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v1.18.2+k3s1/sha256sum-amd64.txt
[INFO]  Skipping binary downloaded, installed k3s matches hash
[INFO]  Skipping /usr/local/bin/kubectl symlink to k3s, already exists
[INFO]  Skipping /usr/local/bin/crictl symlink to k3s, already exists
[INFO]  Skipping /usr/local/bin/ctr symlink to k3s, already exists
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.
[INFO]  systemd: Starting k3s
Job for k3s.service failed because the control process exited with error code.
See "systemctl status k3s.service" and "journalctl -xe" for details.

rajie@master:~$ sudo journalctl -xe
May 18 10:45:40 master systemd[1]: k3s.service: Service hold-off time over, scheduling restart.
May 18 10:45:40 master systemd[1]: k3s.service: Scheduled restart job, restart counter is at 4.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Automatic restarting of the unit k3s.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
May 18 10:45:40 master systemd[1]: Stopped Lightweight Kubernetes.
-- Subject: Unit k3s.service has finished shutting down
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit k3s.service has finished shutting down.
May 18 10:45:40 master systemd[1]: Starting Lightweight Kubernetes...
-- Subject: Unit k3s.service has begun start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit k3s.service has begun starting up.
May 18 10:45:40 master k3s[6003]: time="2020-05-18T10:45:40.836759299+05:30" level=info msg="Starting k3s v1.18.2+k3s1 
May 18 10:45:40 master k3s[6003]: time="2020-05-18T10:45:40.844976831+05:30" level=fatal msg="starting kubernetes: prep
May 18 10:45:40 master systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
May 18 10:45:40 master systemd[1]: k3s.service: Failed with result 'exit-code'.
May 18 10:45:40 master systemd[1]: Failed to start Lightweight Kubernetes.
-- Subject: Unit k3s.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit k3s.service has failed.
-- 
-- The result is RESULT.
May 18 10:45:41 master sudo[6031]:    rajie : TTY=pts/5 ; PWD=/home/rajie ; USER=root ; COMMAND=/bin/journalctl -xe
May 18 10:45:41 master sudo[6031]: pam_unix(sudo:session): session opened for user root by rajie(uid=0)
```

**To Reproduce**
Step 1: https://rancher.com/docs/rancher/v2.x/en/installation/k8s-install/create-nodes-lb/
Step 2: https://rancher.com/docs/rancher/v2.x/en/installation/k8s-install/kubernetes-rke/

**Expected behavior**
k3s service should start

**Actual behavior**
Unit k3s.service has failed.

**Additional Info**
Configured a TCP load balancer as documented in https://rancher.com/docs/rancher/v2.x/en/installation/options/nginx/

**Comment by brandond** [comment]
Can you provide full k3s log output from the journal? There's not really enough provided to figure out why it's crashing.

**Comment by Rajakavitha1** [comment]
Here's the output:
rajie@master:~$ sudo tail -f /var/log/syslog
May 18 07:17:00 master k3s[23546]: time="2020-05-18T12:47:00.033463480+05:30" level=info msg="Starting k3s v1.18.2+k3s1 (698e444a)"
May 18 07:17:00 master k3s[23546]: time="2020-05-18T12:47:00.044250493+05:30" level=fatal msg="starting kubernetes: preparing server: creating storage endpoint: building kine: dial tcp 45.79.122.91:3306: connect: connection refused"
May 18 07:17:00 master systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
May 18 07:17:00 master systemd[1]: k3s.service: Failed with result 'exit-code'.
May 18 07:17:00 master systemd[1]: Failed to start Lightweight Kubernetes.
May 18 07:17:01 master CRON[23574]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
May 18 07:17:05 master systemd[1]: k3s.service: Service hold-off time over, scheduling restart.
May 18 07:17:05 master systemd[1]: k3s.service: Scheduled restart job, restart counter is at 1320.
May 18 07:17:05 master systemd[1]: Stopped Lightweight Kubernetes.
May 18 07:17:05 master systemd[1]: Starting Lightweight Kubernetes...
May 18 07:17:05 master k3s[23578]: time="2020-05-18T12:47:05.550195214+05:30" level=info msg="Starting k3s v1.18.2+k3s1 (698e444a)"
May 18 07:17:05 master k3s[23578]: time="2020-05-18T12:47:05.555762461+05:30" level=fatal msg="starting kubernetes: preparing server: creating storage endpoint: building kine: dial tcp 45.79.122.91:3306: connect: connection refused"
May 18 07:17:05 master systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
May 18 07:17:05 master systemd[1]: k3s.service: Failed with result 'exit-code'.
May 18 07:17:05 master systemd[1]: Failed to start Lightweight Kubernetes.
May 18 07:17:10 master systemd[1]: k3s.service: Service hold-off time over, scheduling restart.
May 18 07:17:10 master systemd[1]: k3s.service: Scheduled restart job, restart counter is at 1321.
May 18 07:17:10 master systemd[1]: Stopped Lightweight Kubernetes.
May 18 07:17:10 master systemd[1]: Starting Lightweight Kubernetes...
May 18 07:17:11 master k3s[23618]: time="2020-05-18T12:47:11.078974549+05:30" level=info msg="Starting k3s v1.18.2+k3s1 (698e444a)"
May 18 07:17:11 master k3s[23618]: time="2020-05-18T12:47:11.091168596+05:30" level=fatal msg="starting kubernetes: preparing server: creating storage endpoint: building kine: dial tcp 45.79.122.91:3306: connect: connection refused"
May 18 07:17:11 master systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
May 18 07:17:11 master systemd[1]: k3s.service: Failed with result 'exit-code'.
May 18 07:17:11 master systemd[1]: Failed to start Lightweight Kubernetes.
May 18 07:17:16 master systemd[1]: k3s.service: Service hold-off time over, scheduling restart.
May 18 07:17:16 master systemd[1]: k3s.service: Scheduled restart job, restart counter is at 1322.
May 18 07:17:16 master systemd[1]: Stopped Lightweight Kubernetes.
May 18 07:17:16 master systemd[1]: Starting Lightweight Kubernetes...
May 18 07:17:16 master k3s[23665]: time="2020-05-18T12:47:16.580108618+05:30" level=info msg="Starting k3s v1.18.2+k3s1 (698e444a)"
May 18 07:17:16 master k3s[23665]: time="2020-05-18T12:47:16.588431802+05:30" level=fatal msg="starting kubernetes: preparing server: creating storage endpoint: building kine: dial tcp 45.79.122.91:3306: connect: connection refused"
May 18 07:17:16 master systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
May 18 07:17:16 master systemd[1]: k3s.service: Failed with result 'exit-code'.
May 18 07:17:16 master systemd[1]: Failed to start Lightweight Kubernetes.
May 18 07:17:21 master systemd[1]: k3s.service: Service hold-off time over, scheduling restart.
May 18 07:17:21 master systemd[1]: k3s.service: Scheduled restart job, restart counter is at 1323.
May 18 07:17:21 master systemd[1]: Stopped Lightweight Kubernetes.
May 18 07:17:21 master systemd[1]: Starting Lightweight Kubernetes...
May 18 07:17:22 master k3s[23703]: time="2020-05-18T12:47:22.073338279+05:30" level=info msg="Starting k3s v1.18.2+k3s1 (698e444a)"

**Comment by Rajakavitha1** [comment]
> Can you provide full k3s log output from the systemd journal? There's not really enough provided to figure out why it's crashing.

thanks for the response @brandond  I am new to k3s...could you please let me know how to get the full k3s log?

**Comment by dweomer** [comment]
> May 18 07:17:16 master k3s[23665]: time="2020-05-18T12:47:16.588431802+05:30" level=fatal msg="starting kubernetes: preparing server: creating storage endpoint: building kine: dial tcp 45.79.122.91:3306: connect: connection refused"

**Comment by Rajakavitha1** [comment]
> > May 18 07:17:16 master k3s[23665]: time="2020-05-18T12:47:16.588431802+05:30" level=fatal msg="starting kubernetes: preparing server: creating storage endpoint: building kine: dial tcp 45.79.122.91:3306: connect: connection refused"
> 
> Is MySQL running or blocked via firewall?
Is this the one you are referring to:
`May 18 09:18:21 master k3s[13034]: time="2020-05-18T14:48:21.118757122+05:30" level=fatal msg="starting kubernetes: preparing server: creating storage endpoint: building kine: driver: bad connection"`

**Comment by Rajakavitha1** [comment]
> > > May 18 07:17:16 master k3s[23665]: time="2020-05-18T12:47:16.588431802+05:30" level=fatal msg="starting kubernetes: preparing server: creating storage endpoint: building kine: dial tcp 45.79.122.91:3306: connect: connection refused"
> > 
> > 
> > Is MySQL running or blocked via firewall?
> > Is this the one you are referring to:
> > `May 18 09:18:21 master k3s[13034]: time="2020-05-18T14:48:21.118757122+05:30" level=fatal msg="starting kubernetes: preparing server: creating storage endpoint: building kine: driver: bad connection"`

@dweomer Thanks for the response.
Here's what my mysql machine reads:
rajie@mysql:~$ sudo ufw status
Status: active

To                         Action      From
--                         ------      ----
22/tcp                     ALLOW       Anywhere                  
80/tcp                     ALLOW       Anywhere                  
443/tcp                    ALLOW       Anywhere                  
6443/tcp                   ALLOW       Anywhere                  
3306/tcp                   ALLOW       Anywhere                  
Anywhere                   ALLOW       45.79.123.93              
22/tcp (v6)                ALLOW       Anywhere (v6)             
80/tcp (v6)                ALLOW       Anywhere (v6)             
443/tcp (v6)               ALLOW       Anywhere (v6)             
6443/tcp (v6)              ALLOW       Anywhere (v6)             
3306/tcp (v6)              ALLOW       Anywhere (v6)             

3306/tcp                   ALLOW OUT   Anywhere                  
3306/tcp (v6)              ALLOW OUT   Anywhere (v6)

**Comment by Rajakavitha1** [comment]
Here's the output from the log:
rajie@master:~$ sudo tail -f /var/log/syslog
May 18 10:49:50 master systemd[1]: k3s.service: Failed to schedule restart job: Unit k3s.service not found.
May 18 10:49:50 master systemd[1]: k3s.service: Failed with result 'exit-code'.
May 18 10:49:50 master systemd[1]: Reloading.
May 18 10:49:51 master systemd[1]: Reloading.
May 18 10:55:01 master CRON[17533]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
May 18 11:01:46 master systemd[1]: Started Session 915 of user rajie.
May 18 11:02:18 master systemd[1]: Reloading.
May 18 11:02:19 master systemd[1]: Reloading.
May 18 11:02:19 master systemd[1]: Reloading.
May 18 11:05:01 master CRON[17825]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)

**Comment by brandond** [comment]
@Rajakavitha1 The command you're looking for is: `journalctl -u k3s --no-pager --no-hostname`. Tailing syslog still just gives small chunks of logs, insufficient to do any real troubleshooting.

I agree with  @dweomer though - it sure looks like an error connecting to your datastore. Have you confirmed that your k3s host can connect to the mysql server at`mysql.rajie.wiki:3306`?

**Comment by Rajakavitha1** [comment]
Hi @brandond  Here's the output of journalctl -u k3s --no-pager --no-hostname:
May 18 16:19:49 systemd[1]: k3s.service: Service hold-off time over, scheduling restart.
May 18 16:19:49 systemd[1]: k3s.service: Scheduled restart job, restart counter is at 997.
May 18 16:19:49 systemd[1]: Stopped Lightweight Kubernetes.
May 18 16:19:49 systemd[1]: Starting Lightweight Kubernetes...
May 18 16:19:50 k3s[17397]: time="2020-05-18T16:19:50.029404362+05:30" level=info msg="Starting k3s v1.18.2+k3s1 (698e444a)"
May 18 16:19:50 k3s[17397]: time="2020-05-18T16:19:50.036498014+05:30" level=info msg="Cluster bootstrap already complete"
May 18 16:19:50 k3s[17397]: [mysql] 2020/05/18 16:19:50 packets.go:36: unexpected EOF
May 18 16:19:50 k3s[17397]: [mysql] 2020/05/18 16:19:50 packets.go:36: unexpected EOF
May 18 16:19:50 k3s[17397]: http: TLS handshake error from 45.79.124.109:36354: remote error: tls: bad certificate
May 18 16:19:50 k3s[17397]: [mysql] 2020/05/18 16:19:50 packets.go:36: unexpected EOF
May 18 16:19:50 k3s[17397]: time="2020-05-18T16:19:50.076362083+05:30" level=fatal msg="starting kubernetes: preparing server: creating storage endpoint: building kine: driver: bad connection"
May 18 16:19:50 systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
May 18 16:19:50 systemd[1]: k3s.service: Failed with result 'exit-code'.
May 18 16:19:50 systemd[1]: Failed to start Lightweight Kubernetes.
May 18 16:19:50 systemd[1]: k3s.service: Service hold-off time over, scheduling restart.
May 18 16:19:50 systemd[1]: k3s.service: Failed to schedule restart job: Unit k3s.service not found.
May 18 16:19:50 systemd[1]: k3s.service: Failed with result 'exit-code'.

**Comment by brandond** [comment]
Did you check to see if you can actually get to the MySQL server?

**Comment by Rajakavitha1** [comment]
> Did you check to see if you can actually get to the MySQL server?

Yes, I am able to connect 
rajie@master:~$ sudo mysql -urajie -pScorpion -h 45.79.125.20
[sudo] password for rajie: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 30
Server version: 10.1.44-MariaDB-0ubuntu0.18.04.1 Ubuntu 18.04

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> exit
Bye
rajie@master:~$ export K3S_DATASTORE_ENDPOINT="mysql://rajie:password@tcp(mysql.rajie.wiki:3306)/rancher"
rajie@master:~$ curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig-mode 644 -t agent-secret --tls-san k3s.rajie.wiki --node-taint k3s-controlplane=true:NoExecute" sh -s - server
[INFO]  Finding release for channel stable
[INFO]  Using v1.18.2+k3s1 as release
[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v1.18.2+k3s1/sha256sum-amd64.txt
[INFO]  Skipping binary downloaded, installed k3s matches hash
[INFO]  Skipping /usr/local/bin/kubectl symlink to k3s, already exists
[INFO]  Skipping /usr/local/bin/crictl symlink to k3s, already exists
[INFO]  Skipping /usr/local/bin/ctr symlink to k3s, already exists
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.
[INFO]  systemd: Starting k3s
Job for k3s.service failed because the control process exited with error code.
See "systemctl status k3s.service" and "journalctl -xe" for details.

**Comment by Rajakavitha1** [comment]
Here's the log:
19 09:06:42 systemd[1]: k3s.service: Service hold-off time over, scheduling restart.
May 19 09:06:42 systemd[1]: k3s.service: Scheduled restart job, restart counter is at 22.
May 19 09:06:42 systemd[1]: Stopped Lightweight Kubernetes.
May 19 09:06:42 systemd[1]: Starting Lightweight Kubernetes...
May 19 09:06:43 k3s[22408]: time="2020-05-19T09:06:43.344622856+05:30" level=info msg="Starting k3s v1.18.2+k3s1 (698e444a)"
May 19 09:06:43 k3s[22408]: time="2020-05-19T09:06:43.348752556+05:30" level=info msg="Cluster bootstrap already complete"
May 19 09:06:43 k3s[22408]: time="2020-05-19T09:06:43.377182469+05:30" level=fatal msg="starting kubernetes: preparing server: creating storage endpoint: building kine: Error 1045: Access denied for user 'rajie'@'li2120-91.members.linode.com' (using password: YES)"
May 19 09:06:43 systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
May 19 09:06:43 systemd[1]: k3s.service: Failed with result 'exit-code'.
May 19 09:06:43 systemd[1]: Failed to start Lightweight Kubernetes.
May 19 09:06:48 systemd[1]: k3s.service: Service hold-off time over, scheduling restart.
May 19 09:06:48 systemd[1]: k3s.service: Scheduled restart job, restart counter is at 23.
May 19 09:06:48 systemd[1]: Stopped Lightweight Kubernetes.
May 19 09:06:48 systemd[1]: Starting Lightweight Kubernetes...
May 19 09:06:48 k3s[22450]: time="2020-05-19T09:06:48.820053847+05:30" level=info msg="Starting k3s v1.18.2+k3s1 (698e444a)"
May 19 09:06:48 k3s[22450]: time="2020-05-19T09:06:48.824879737+05:30" level=info msg="Cluster bootstrap already complete"
May 19 09:06:48 k3s[22450]: time="2020-05-19T09:06:48.855055805+05:30" level=fatal msg="starting kubernetes: preparing server: creating storage endpoint: building kine: Error 1045: Access denied for user 'rajie'@'li2120-91.members.linode.com' (using password: YES)"
May 19 09:06:48 systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
May 19 09:06:48 systemd[1]: k3s.service: Failed with result 'exit-code'.

**Comment by Rajakavitha1** [comment]
@brandond and @dweomer Please help me with 
msg="starting kubernetes: preparing server: creating storage endpoint: building kine: Error 1071: Specified key was too long; max key length is 767 bytes"

**Comment by Rajakavitha1** [comment]
upgrading mariadb to 10.4 resolved the issue. However, i facing a new issue now:
rajie@master:~$ sudo kubectl get nodes
[sudo] password for rajie: 
Unable to connect to the server: x509: certificate signed by unknown authority
rajie@master:~$ kubectl version --short
Client Version: v1.18.2+k3s1
Unable to connect to the server: x509: certificate signed by unknown authority
rajie@master:~$ sudo systemctl status k3s
● k3s.service - Lightweight Kubernetes
   Loaded: loaded (/etc/systemd/system/k3s.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2020-05-19 10:13:26 IST; 13min ago
     Docs: https://k3s.io
  Process: 14219 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
  Process: 14215 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
 Main PID: 14224 (k3s-server)
    Tasks: 9
   CGroup: /system.slice/k3s.service
           ├─14224 /usr/local/bin/k3s server --write-kubeconfig-mode 644 -t agent-secret --tls-san k3s.rajie.wiki --node-taint 
           └─14252 containerd -c /var/lib/rancher/k3s/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock -

**Comment by brandond** [comment]
Are all of your nodes on the same LAN? If not, did you configure their public IPs with the `--node-external-ip` option?

**Comment by Rajakavitha1** [comment]
> Are all of your nodes on the same LAN? If not, did you configure their public IPs with the `--node-external-ip` option?

let me check that...

**Comment by Rajakavitha1** [comment]
> > Are all of your nodes on the same LAN? If not, did you configure their public IPs with the `--node-external-ip` option?
> 
> let me check that...

Thank you @brandond I was able to resolve the issue I now have:
rajie@master2:~$ kubectl get nodes
NAME      STATUS   ROLES    AGE    VERSION
master    Ready    master   168m   v1.18.2+k3s1
master2   Ready    master   61m    v1.18.2+k3s1

**Comment by Rajakavitha1** [comment]
Closing this issue. However, it might be worth documenting about mariadb 10.4 as a requirement.
