### ISSUE TITLE
/var/lib/rancher/k3s/server/manifests/traefik.yaml doesn't persist after reboot ?

### ISSUE THREAD

**Issue by armandleopold** [rancher/k3s#1815]
Is it normal that after rebooting my raspberry pi 4 the file :
`/var/lib/rancher/k3s/server/manifests/traefik.yaml` 
is overwritten and i loose my custom config ?

**Comment by brandond** [comment]
Yes. There are a couple open issues about it. The one that best represents the current state is probably https://github.com/rancher/k3s/issues/1797.

Your best bet at the moment is to copy traefik.yaml to something unique (coredns-local.yaml, for example), then add `--disable=traefik` to the command-line options, and restart k3s.

**Comment by armandleopold** [comment]
Thanks for the quick response i am going to save the file elsewhere & copy it when needed.
