### ISSUE TITLE
/var/lib/rancher/k3s/storage selinux context wrong, can't create a local volume

### ISSUE THREAD

**Issue by maci0** [rancher/k3s#1821]
`/var/lib/rancher/k3s/storage` is set to `system_u:object_r:container_var_lib_t:s0` by default

This prevents the local volume provisioning from working.

type should be container_file_t. applying this type with chcon fixes the issue

**Comment by tonsV2** [comment]
For anyone who aren't familiar with SELinux. The above mentioned command should look like the following

`sudo chcon system_u:object_r:container_file_t:s0 /var/lib/rancher/k3s/storage`

Also have you previously disabled SELinux you can enable it again by executing the following

`setenforce 1`

**Comment by tonsV2** [comment]
My attempt at translating @maci0's comment into a command is the below but it doesn't work. Can anyone tell me why?

sudo chcon system_u:object_r:container_file_t:s0 /var/lib/rancher/k3s/storage

**Comment by brandond** [comment]
Can you share the error you're receiving?

**Comment by tonsV2** [comment]
@brandond - It actually does seem to work, my bad, thanks for your swift response
