### ISSUE TITLE
Nvidia Jetson Tx2 can't pull image in private registry

### ISSUE THREAD

**Issue by BokyLiu** [rancher/k3s#1842]
Hi, there. I'm using k3s an Nvidia Jetson Tx2 and k3s version is v1.18.2+k3s1. I'm meeting the same problem, but in my master tx2 there has no file name registry.yaml but k3s.yaml in `/etc/rancher/k3s`.
So, how can i make currect configuration?

`
Failed to pull image "192.168.53.10:5000/tx2/k3s-agent:v3": rpc error: code = Unknown desc = failed to pull and unpack image "192.168.53.10:5000/tx2/k3s-agent:v3": failed to resolve reference "192.168.53.10:5000/tx2/k3s-agent:v3": failed to do request: Head https://192.168.53.10:5000/v2/tx2/k3s-agent/manifests/v3: http: server gave HTTP response to HTTPS client
`

Also, i add `"insecure-registries":["192.168.53.10:5000"]` in master tx2's  `/etc/docker/daemon.json`, but doesn't help.

_Originally posted by @BokyLiu in https://github.com/rancher/k3s/issues/1802#issuecomment-635854537_

**Comment by brandond** [comment]
You haven't configured your registries properly. See the example `/etc/rancher/k3s/registry.yaml` content here:
https://github.com/rancher/k3s/issues/1802#issuecomment-629635293

In general, if documentation tells you to place content in a file but the file does not exist, then you should create it.

**Comment by BokyLiu** [comment]
> You haven't configured your registries properly. See the example `/etc/rancher/k3s/registry.yaml` content here:
> [#1802 (comment)](https://github.com/rancher/k3s/issues/1802#issuecomment-629635293)
> 
> In general, if documentation tells you to place content in a file but the file does not exist, then you should create it.

Yes, great idea!
