### ISSUE TITLE
when I see "--storage-backend=etcd3" in default start args

### ISSUE THREAD

**Issue by yyf1986** [rancher/k3s#1849]
**Version:**

k3s version v1.17.2+k3s1 (cdab19b0)

**K3s arguments:**

k3s server --docker --no-deploy traefik -l ./k3s_server.log

**Describe the bug**

I run `k3s server -h`,the default datastore is use sqlite.
--datastore-endpoint value                 (db) Specify etcd, Mysql, Postgres, or Sqlite (default) data source name [$K3S_DATASTORE_ENDPOINT]
I use default datastore-endpoint to start the server,but I see like this in log
time="2020-06-01T11:10:53.379573826+08:00" level=info msg="Running kube-apiserver --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=unknown --authorization-mode=Node,RBAC --basic-auth-file=/var/lib/rancher/k3s/server/cred/passwd --bind-address=127.0.0.1 --cert-dir=/var/lib/rancher/k3s/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --enable-admission-plugins=NodeRestriction --etcd-servers=unix://kine.sock --insecure-port=0 --kubelet-certificate-authority=/var/lib/rancher/k3s/server/tls/server-ca.crt --kubelet-client-certificate=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.crt --kubelet-client-key=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.key --proxy-client-cert-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt --proxy-client-key-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.key --requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6444 --service-account-issuer=k3s --service-account-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-account-signing-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-cluster-ip-range=10.43.0.0/16 `--storage-backend=etcd3` --tls-cert-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt --tls-private-key-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.key"

**To Reproduce**

**Expected behavior**

**Actual behavior**

**Additional context / logs**

**Comment by yyf1986** [comment]
find storage-backend is etcd3

**Comment by brandond** [comment]
As far as kube-apiserver is concerned, kine is etcd. It implements the same API, but with a SQL backend. Is there a problem?

**Comment by yyf1986** [comment]
no problem  thanks
