### ISSUE TITLE
svclb-traefik occurs error: can't create /proc/sys/net/ipv4/ip_forward: Read-only file system

### ISSUE THREAD

**Issue by yedward** [rancher/k3s#1859]
**Version:**
k3s version v1.18.3+k3s1 (96653e8d)

**K3s arguments:**
--docker --write-kubeconfig-mode 666

**Describe the bug**

VM OS：Ubuntu 18.04

When installed k3s, everything seem to be right.

![image](https://user-images.githubusercontent.com/8938021/83539186-536b3b00-a529-11ea-89a8-c29841e5bad1.png)

But I look into pod `svclb-traefik-jjt7m`, something goes wrong.

![image](https://user-images.githubusercontent.com/8938021/83539374-87466080-a529-11ea-90f4-349b01900d0d.png)

![image](https://user-images.githubusercontent.com/8938021/83539435-99c09a00-a529-11ea-83a8-528ab63619a5.png)

Just like above, occurs error: can't create /proc/sys/net/ipv4/ip_forward: Read-only file system, I  have retried very times, always like this.

**To Reproduce**

first install docker, then install k3s using offical installation script.

**Comment by MaximumQuiet** [comment]
@yedward do you manage to resolve this error? I have the same problem
