### ISSUE TITLE
Preload Container Images in Agent Before Start

### ISSUE THREAD

**Issue by cyberjaws** [rancher/k3s#1864]
I have attempted to follow the instructions to preload additional images (besides the k3s-airgap-images) by placing a tar from "docker save" into the /var/lib/rancher/k3s/agent/images/ folder and only the k3s-airgap-images appear to load. Is there something else that must be done to add additional containers? We are testing in a multi node cluster and don't have a centralized registry so reloading would be expedient.

**Comment by samirsss** [comment]
you need to restart k3s service after placing the tar of the images. k3s ctr image list should show all the images loaded by k3s. 

Also you should follow the logs on k3s `journalctl -f -u k3s` to see if there were issues loading the images.

**Comment by cyberjaws** [comment]
Thanks for the quick response. Can you help me understand how I can load custom containers before becoming an active agent node in the cluster? Perhaps a way to start the k3s agent, but not join the server? So start K3S -> Add Custom Containers -> Join Server Node? If there is a better way to bootstrap I will certainly give it a try. I have attempted to place the TAR with my custom containers with K3S air-gapped TAR BEFORE starting K3S and only the K3S air gapped containers get loaded.

Concept of Operations:
- I have K3S Server Running on Node A.
- I want to add an additional Agent after the fact on Node B.
- On Node B -> I have the K3S Agent binaries, the K3S air-gapped containers, and my application containers. I would prefer to have my application containers preloaded so that when the cluster shifts pods from NodeA to NodeB the containers are ready to go.

**Comment by cyberjaws** [comment]
I figured it out. My tar was named "app.0.1.9.tar". I renamed it to "app-0-9-1.tar" and it now works. **Perhaps a documentation update?**

Thanks again for support -- k3s has enabled our dev team run fast and lean!
