### ISSUE TITLE
disabling traefik-prometheus and kube-dns-upstream services

### ISSUE THREAD

**Issue by samirsss** [rancher/k3s#1866]
**Version:**
$ k3s -v
k3s version v1.18.2+k3s1 (698e444a)

**K3s arguments:**
ExecStart=/apps/bin/k3s server --kube-controller-manager-arg pod-eviction-timeout=1m --disable local-storage,metrics-server,servicelb --disable-cloud-controller --data-dir /apps/rancher/k3s --disable traefik --kube-apiserver-arg feature-gates="ServiceTopology=true,EndpointSlice=true" --kubelet-arg serialize-image-pulls=true --datastore-endpoint mysql://root:root@tcp(10.24.95.4:3306)/k3s

**Describe the bug**
when i look at the output of the following command:

k3s kubectl -n kube-system get svc
NAME                 TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
kube-dns             ClusterIP      10.43.0.10      <none>        53/UDP,53/TCP,9153/TCP       34m
**traefik-prometheus   ClusterIP      10.43.19.242    <none>        9100/TCP                     33m
kube-dns-upstream    ClusterIP      10.43.46.3      <none>        53/UDP,53/TCP                33m**
traefik              LoadBalancer   10.43.255.109   10.24.95.4    80:30088/TCP,443:30840/TCP   33m

I would like to understand what are traefik-prometheus and kube-dns-upstream services used for and if possible how to disable them as part of k3s deployment.

**To Reproduce**
Just install k3s and see the services

We're just trying to minimize the services running since the deployments are going to be on systems with lower cpus and memory and hence trying to strip down unnecessary components.

We dont expect to do any live update checks or get any metrics for our deployment.

**Comment by brandond** [comment]
I don't believe either of these come from the bundled manifests. Can you confirm that you don't have anything else in your manifests directory, or old cluster data in your SQL database? Here's all that I have:

```
root@dev01:~# k3s kubectl -n kube-system get svc
NAME       TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                  AGE
kube-dns   ClusterIP   10.43.0.10   <none>        53/UDP,53/TCP,9153/TCP   33s
```

This is from k3s installed with: 
```
./k3s.sh server --kube-controller-manager-arg=pod-eviction-timeout=1m --disable=local-storage,metrics-server,servicelb,traefik --disable-cloud-controller --kube-apiserver-arg=feature-gates=ServiceTopology=true,EndpointSlice=true --kubelet-arg=serialize-image-pulls=true
```

**Comment by samirsss** [comment]
Thanks for the response @brandond 

We do need Traefik for our deployment.

Here's the k3s.service definition

(efa:extreme)extreme@node1:~$ cat /etc/systemd/system/multi-user.target.wants/k3s.service
[Unit]
Description=Lightweight Kubernetes
Documentation=https://k3s.io
After=network-online.target
[Service]
ExecStartPre=-/sbin/modprobe br_netfilter
ExecStartPre=-/sbin/modprobe overlay
ExecStartPre=/bin/sleep 20
ExecStart=/apps/bin/k3s server --kube-controller-manager-arg pod-eviction-timeout=1m --disable local-storage,metrics-server --disable-cloud-controller --data-dir /apps/rancher/k3s --disable traefik --kube-apiserver-arg feature-gates="ServiceTopology=true,EndpointSlice=true"
KillMode=process
Delegate=yes
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target

(efa:extreme)extreme@node1:~$ k3s kubectl -n kube-system get svc
NAME                 TYPE           CLUSTER-IP      EXTERNAL-IP    PORT(S)                      AGE
kube-dns             ClusterIP      10.43.0.10      <none>         53/UDP,53/TCP,9153/TCP       35m
traefik-prometheus   ClusterIP      10.43.110.152   <none>         9100/TCP                     32m
traefik              LoadBalancer   10.43.99.215    10.24.95.177   80:31711/TCP,443:30284/TCP   32m

**Comment by samirsss** [comment]
Ok I see that prometheus getting enabled when we patch traefik during installation. I'll fix that.

**Comment by brandond** [comment]
Yeah, I was going to say, you've disabled the built-in traefik deployment with `--disable traefik`, so if you HAVE traefik, that and anything else (like traefik-prometheus) would be coming from something that you are installing yourself...

**Comment by samirsss** [comment]
Closing this issue, since its resolved now.
