### ISSUE TITLE
Changes to helm chart values or values.yaml aren't always triggering an upgrade

### ISSUE THREAD

**Issue by cjellick** [rancher/k3s#187]
As the title says

see https://github.com/rancher/k3s/pull/183

**Comment by erikwilson** [comment]
Verified by modifying /var/lib/rancher/k3s/server/manifests/traefik.yaml to add spec.valuesContent, on change the helm-install-traefik pod was re-run to process the modification.

**Comment by jwillmer** [comment]
Is it correct that helm is installed alongside of k3s? I couldn't find it, last time I checked I needed to manually install it.

**Comment by pmahoney** [comment]
@jwillmer k3s includes a HelmChart CRD that uses [https://github.com/rancher/klipper-helm] to run helm install/upgrade/remove. There is no tiller pod in the cluster.

@erikwilson I'm seeing similar behavior (upgrades not happening). I've been applying and modifying HelmChart resources directly via `kubectl apply`, not via the manifests directory. Should I expect that to work?

**Comment by erikwilson** [comment]
Helm upgrade are broken at the moment, we probably need to remove the old job first.

**Comment by jmbe** [comment]
It indeed works fine if the old job is removed manually before applying the updated helm chart. Tested with k3s version v0.7.0.

```
kubectl delete job --namespace=kube-system helm-install-cert-manager 
kubectl apply -f cert-manager-helmchart.yaml
```

A new install job was properly created.
