### ISSUE TITLE
Can't Resolve DNS using Host's /etc/resolv.conf

### ISSUE THREAD

**Issue by cyberjaws** [rancher/k3s#1872]
**Version:**
1.17.4

**K3s arguments:**
--no-deploy traefik --resolve-conf "/etc/resolv.conf"

**Describe the bug**
CoreDNS Doesn't resolve hostnames from my local DNS server which is configured on the host node.

**To Reproduce**

**Expected behavior**
Local DNS server from host's /etc/resolv.conf is used and hostnames are resolved.

**Actual behavior**
ping result for another machine on the network (not another node) by hostname yields:
"Temporary failure in name resolution"

**Additional context / logs**
This is on a RHEL7 box with the usual K8 prereqs set (no selinux, firewalld is off, swap is off, etc).

The RHEL7 VM has the following in its /etc/resolve.conf
;generated by /usr/sbin/dhclient-script
```
search my.local.domain.com
nameserver 10.7.35.11  # Can't resolve hostnames from this server!
nameserver 10.120.40.11
nameserver 10.120.40.12
```

The first nameserver is to the local DNS server for the lab I am using to test in. The latter two are to resolve parent services from the enterprise where I work.

I spin up K3S, start a pod, and then exec into the pod. From inside the pod I can resolve hostnames to the parent services but can NOT resolve to other machines using the first nameserver. In the pod I see my custom search (my.local.domain.com) and the static IP of CoreDNS as the nameserver.

I can mod the Corefile with a stub domain for my.local.domain.com that forwards to 10.7.35.11 however I am in the same boat as other tickets that I lose the Corefile configmap on K3S service restart.

Have I misunderstood how CoreDNS uses the host's /etc/resolv.conf?

**Comment by cyberjaws** [comment]
Confirmed that the sub domain will indeed work and that we need to ensure that we consolidate the nameservers down to a single instance on the host.

**Comment by yamlCase** [comment]
> Confirmed that the sub domain will indeed work and that we need to ensure that we consolidate the nameservers down to a single instance on the host.

@cyberjaws would you elaborate?  I've been fighting with this issue better part of the day and am hopeful you've got the secret sauce that'll help me move forward.

**Comment by cyberjaws** [comment]
@yamlCase  -- Sorry for such a late response. We ended up adding an additional hosts section to the CoreDNS Corefile to supply the custom DNS lookups.
