### ISSUE TITLE
Failed at step EXEC spawning /usr/local/bin/k3s: Permission denied

### ISSUE THREAD

**Issue by BruceWayneVsSuperMan** [rancher/k3s#1874]
This problem puzzled me the whole day...
![IMG20200607-000552846](https://user-images.githubusercontent.com/17560384/83948853-d3a7de00-a852-11ea-935a-6bd5ba19b9b3.jpeg)
![image](https://user-images.githubusercontent.com/17560384/83948865-e7ebdb00-a852-11ea-811c-80ea5d3d68ab.png)
![image](https://user-images.githubusercontent.com/17560384/83948870-ef12e900-a852-11ea-8bba-8535bbab15a5.png)

**Comment by wkclz** [comment]
/usr/local/bin/k3s is a directory, can not be execute
# cd k3s && ./k3s.bin -server

**Comment by BruceWayneVsSuperMan** [comment]
@wkclz  love you boody
