### ISSUE TITLE
Question: How to use K3s with NAT and host only network in Virtualbox 

### ISSUE THREAD

**Issue by DavidRotert** [rancher/k3s#1879]
Hello, I tried to set up K3s + Rancher in a VirtualBox VM. The Guest is a Debian 10 OS and I have NAT as first network adapter and host only as second. But if I start K3s it uses only the NAT interface by default and its not possible to access traefik or use any port mapping like host port or node port. The services are not accessible even from inside the VM or any other network assigned to it. I see the following behavior:

Opening IP of VM in browser (to connect to traefik): tries to connect until it times out
Curl inside VM with localhost and port 80: same
Curl with NAT IP and port 80 inside of VM: works.

I tried the different IP related parameters as described in the K3s server docs, but it doesn't help. I can set up Rancher and see the host only IP in the UI used as the default node IP, but port mappings for services still seem to use anything else. The weird thing is that I can reach the services from inside the VM with its host only IP, but not with any other (even localhost?!) and not from outside (host). Is there anything I have to change in my install parameters or if not is there any good workaround for that?

**Comment by bodzio4749** [comment]
It looks that you assigned a wrong type of network interface for this VM. What you are looking for is "bridge" type. Nothing to do with k3s. NAT behaves exactly the same way as your router NAT. It is only one-way access, and I don't know enough of VirtualBox to know if  there is a "port forwarding" feature in it. Try bridge.  Of course, I could be wrong, as it happens once a year.

https://www.virtualbox.org/manual/ch06.html#:~:text=Use%20the%20VM's%20Settings%20dialog,down%20list%20of%20networking%20modes.

**Comment by brandond** [comment]
Yes, you cannot access pods from outside the cluster when using flannel - they're on virtual interfaces with private addresses. This is normal.

**Comment by DavidRotert** [comment]
@bodzio4749 Yes, VirtualBox has port forwarding for NAT. But I never used it before. And bride network isn't a solution in my case because of restrictions in my workplaces network.

**Comment by DavidRotert** [comment]
@brandond Sorry, I edited my question because it was not clear what I mean. I don't mean that I can't access the pods with its cluster IP. The problem is that all mapped ports like mode port or host port can only be accessed from within the VM by using the NAT interface IP.

**Comment by brandond** [comment]
The best way to do this would be to use a single adapter in bridged mode. If you can't do that, I would use a single adapter in nat mode, and go into the advanced settings in the VM network configuration and set up port forwards to the ports you're using in k3s.

**Comment by runningman84** [comment]
Or you could have a router vm which does nat and provide an internal network to the k3s vms...

**Comment by DavidRotert** [comment]
Hmm, I tried following on Debian 10: NAT Network with port Forwarding for 22 and 80. I tried to connect to ssh - no problem. But traefik and K3s stuff is still not accessible from any IP. Even in the VM itself. Is this an expected behaviour for K3s? Or could this be a possible bug? It seems like something unexpected because all Kubernetes services seems to be bound **ONLY** to the IP used for NAT.

**Comment by DavidRotert** [comment]
Sorry, I didn't saw that Debian Buster isn't supported because of nftables.

**Comment by brandond** [comment]
Even with a router vm you still need to forward ports from the host if all you can do is NAT due to corp network restrictions...

**Comment by DavidRotert** [comment]
Thank you very much for your advices! On Ubuntu everything works fine, even with host only network.
