### ISSUE TITLE
Containerd log level env var not respected

### ISSUE THREAD

**Issue by cjellick** [rancher/k3s#188]
If `CONTAINERD_LOG_LEVEL`, it is not being respected

**Comment by cjellick** [comment]
see https://github.com/rancher/k3s/pull/182/files

**Comment by erikwilson** [comment]
Verified that running `sudo CONTAINERD_LOG_LEVEL=debug ./k3s-rc6 server` produced `level=debug` output in `/var/lib/rancher/k3s/agent/containerd/containerd.log`
