### ISSUE TITLE
rootless with native snapshotter grows disk with every restart of k3s

### ISSUE THREAD

**Issue by coopstah13** [rancher/k3s#1890]
**Version:**
`k3s-1.16.7 version v1.16.7+k3s1 (16c99b87)` - cannot upgrade beyond due to #1709 

**K3s arguments:**
`--rootless`

**Describe the bug**
Every time k3s stops and starts again, the disk space usage grows by about 200MB.

**To Reproduce**
Run rootless k3s with native snapshotter

**Expected behavior**
Disk space does not grow simply by k3s restarting.

**Actual behavior**
Disk space usage increases by ~200MB after restart.

**Additional context / logs**
config.toml.tmpl:
```
[plugins.cri.containerd]
  snapshotter = "native"
```
Running on RHEL 7.7 - cannot use overlay due to #575

**Comment by brandond** [comment]
According to https://github.com/containerd/containerd/issues/830#issuecomment-300549448 the native snapshotter is only meant for debugging and should not be used for actual workloads.

**Comment by coopstah13** [comment]
OK so if its related to native snapshotter (the only one that works rootless on RHEL) then I guess i have to pursue other avenues.

**Comment by brandond** [comment]
Yeah I think at the moment, rootless is best on ubuntu or other distros that have picked up the ubuntu overlayfs patch.

**Comment by coopstah13** [comment]
I can't use ubuntu. I will close this issue as there is no action required.

**Comment by AkihiroSuda** [comment]
On XFS with reflink, native can save disk space.
