### ISSUE TITLE
 Include busybox image to k3s-airgap-images tarball

### ISSUE THREAD

**Issue by vvanouytsel** [rancher/k3s#1920]
**Version:**

```
k3s version v1.17.3+k3s1 (5b17a175)
```

**K3s arguments:**
```
usr/bin/k3s server --data-dir=/mnt/data/kubernetes/k3s --cluster-cidr=10.42.0.0/16 --service-cidr=10.43.0.0/16 --cluster-dns=10.43.0.10 --node-ip=192.168.15.1 --advertise-address=192.168.15.1 --bind-address=192.168.15.1 --node-external-ip=10.92.95.85 --flannel-iface=dummy0 --kube-scheduler-arg address=192.168.15.1 --kube-controller-manager-arg address=192.168.15.1 --kube-apiserver-arg address=192.168.15.1 --kubelet-arg address=127.0.0.1
```

**Describe the bug**
K3s supports complete [air-gapped](https://rancher.com/docs/k3s/latest/en/installation/airgap/) installations.

A 'k3s-airgap-images' tarball is available for [download](https://github.com/rancher/k3s/releases) which includes all necessary docker images.

Even though the [local-path-provisioner](https://github.com/rancher/local-path-provisioner) image is included in the image, the local-path-provisioner uses the [busybox](https://github.com/rancher/local-path-provisioner/blob/master/main.go#L30) docker image to create the necessary volume directories on the host.

This means that a complete air-gapped installation is not supported, since we require internet access to download the busybox image from the docker registry server.

We should include the [busybox](https://hub.docker.com/_/busybox) image in the 'k3s-airgap-images' tarball to fully support air-gapped installations.

**To Reproduce**
* Follow the k3s airgap installation [documentation](https://rancher.com/docs/k3s/latest/en/installation/airgap/).
* Deploy the [local-path-provisioner](https://github.com/rancher/local-path-provisioner/)
* Disable internet connectivity
* Create a PersistentVolumeClaim

**Expected behavior**

A PersistentVolume is created.

**Actual behavior**

The helper container used by local-path-provider cannot be started, since it tries to pull the 'busybox' container from the docker.io registry.

**Comment by bflorat** [comment]
Dup of #1908
