### ISSUE TITLE
Add drain node functionality

### ISSUE THREAD

**Issue by MonzElmasry** [rancher/k3s#1929]
Add `kubectl drain node' command to drain nodes prior to maintenance 
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#drain

**Comment by brandond** [comment]
Is this for the SUC or ?

**Comment by geotransformer** [comment]
Does K3S support "kubectl drain node"? It seems not

**Comment by brandond** [comment]
k3s kubectl supports everything that upstream kubectl supports.
