### ISSUE TITLE
Stop exposing port 10010 on public interface

### ISSUE THREAD

**Issue by maxmeyer** [rancher/k3s#193]
**Describe the bug**

Port 10010 is exposed on a public interface for no good reason. There were quite a few discussions on this. Example: https://github.com/moby/moby/issues/37507. This was fixed in https://github.com/containerd/cri/pull/858.

~~~
tcp        0      0 37.x.x.x:10010    0.0.0.0:*               LISTEN      5145/containerd
~~~

**To Reproduce**

~~~
sudo k3s server &
sudo netstat -nlpt
~~~

**Expected behavior**
~~~
tcp        0      0 127.0.0.1:10010    0.0.0.0:*               LISTEN      5145/containerd
~~~

**Additional context**
I think this can be fixed by changing this 
https://github.com/rancher/k3s/blob/7fbeafea4632503f07d869baa5d370bcef9f3900/pkg/agent/containerd/containerd.go#L32

**Comment by ibuildthecloud** [comment]
@maxmeyer  Thanks we are aware of this and working on a fix and realize it's a security issue.  The reason that this is happening is because on your system your hostname (the output of `hostname`) does not resolve to a 127.x address.  On a lot of systems `/etc/hosts` has a line like

```
127.0.1.1 myhostname
```

**Comment by ibuildthecloud** [comment]
It's not as easy of a fix as just setting the stream server address to localhost.

**Comment by maxmeyer** [comment]
@ibuildthecloud Thanks for the fast response and how I can work around this. Great, that you're already working on this. Feel free to close this issue.
