### ISSUE TITLE
kubectl command sometimes not work.

### ISSUE THREAD

**Issue by jmbkeyes** [rancher/k3s#1934]
I installed k3s on my vmware with **CentOS Linux release 7.8.2003 (Core)**, but came across some issues as below, could someone help me, thanks in advance?

**Version:**

v1.18.3+k3s1
**K3s arguments:**

/usr/local/bin/k3s \
    server \
	'--docker' \
	'--write-kubeconfig' \
	'/root/.kube/config' \
	'--write-kubeconfig-mode' \
	'666' \

use external database(Mysql5.7)
**Describe the bug**

**Run kubectl get nodes command(kubectl get nodes), it sometimes show correct responds, but sometimes error occurs as below.**
The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get nodes)

**run command(kubectl get pods -n kube-system),  most of the time, error occurs as bellow,**
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get pods)

**run command(k3s kubectl get all --all-namespaces), most of the time, error occurs as below,**
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get pods)
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get replicationcontrollers)
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get services)
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get daemonsets.apps)
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get deployments.apps)
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get replicasets.apps)
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get statefulsets.apps)
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get horizontalpodautoscalers.autoscaling)
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get jobs.batch)
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get cronjobs.batch)

The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?
The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?
The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?
The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?
The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?
The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?
The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?
The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?
The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?
The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?
**To Reproduce**

**Expected behavior**

**Actual behavior**

**Additional context / logs**

I saw some abnormal logs in /var/log/messages, but not sure what's the reason?
Jun 19 18:30:36 master1 k3s: E0619 18:30:35.995119   36767 leaderelection.go:356] Failed to update lock: Put https://127.0.0.1:6444/api/v1/namespaces/kube-system/endpoints/cloud-controller-manager: context deadline exceeded
Jun 19 18:30:36 master1 k3s: I0619 18:30:35.995166   36767 leaderelection.go:277] failed to renew lease kube-system/cloud-controller-manager: timed out waiting for the condition
Jun 19 18:30:36 master1 k3s: F0619 18:30:35.995178   36767 controllermanager.go:213] leaderelection lost
Jun 19 18:30:36 master1 systemd: k3s.service: main process exited, code=exited, status=255/n/a
Jun 19 18:30:36 master1 systemd: Unit k3s.service entered failed state.
Jun 19 18:30:36 master1 systemd: k3s.service failed.
Jun 19 18:30:41 master1 systemd: k3s.service holdoff time over, scheduling restart.

**Comment by brandond** [comment]
This sounds like either your datastore or the k3s node are overtaxed. What cpu, memory, and disk are you using to host k3s and the datastore?

**Comment by jmbkeyes** [comment]
datastore is on my host(6C32G), and k3s nodes are installed via vmware(CentOS7.8), server node is allocated 1Core, 1.5G mem, 40G max disk usage, work node is allocated 1Core,1G mem,40G max disk usage .

**Comment by brandond** [comment]
What sort of disk is it backed by? k3s doesn't need a ton of throughput, but it does need pretty low latency on the datastore. Do you have any additional logs? Based on what you've shared so far, it looks like the queries are taking an excessive amount of time to complete.

**Comment by jmbkeyes** [comment]
My datastore uses the normal hard disk not solid disk, and sql excute works fast. And the k3s nodes in VM use also use the normal hard disk, but I find that the k3s node starts, the hard disk takes 100% usage in resource monitor.
![image](https://user-images.githubusercontent.com/12583734/85354885-1994bf80-b53e-11ea-9cfc-d2a40c22ac43.png)

**Comment by brandond** [comment]
Sure looks like your disk can't keep up with the io load of two k3s nodes and the database. This might work on a sad, but definitely not on rotational media. Do you at least have a different disk you could try putting the database on?

**Comment by jmbkeyes** [comment]
I move my datastore from normal hard disk to ssd, and most of time kubectl command works well. Thanks for help!!
