### ISSUE TITLE
Run the master without kubelet

### ISSUE THREAD

**Issue by toonsevrin** [rancher/k3s#1943]
Is it possible to run the master without the kubelet? I'd like to do k3s-in-k3s (eg. one cluster manages the other master), but I can't see to figure out how to disable the kubelet on the master nodes.

**Comment by brandond** [comment]
I haven't tested it myself, but there's a hidden option for that:

https://github.com/rancher/k3s/blob/master/pkg/cli/cmds/server.go#L302

**Comment by toonsevrin** [comment]
@brandond that does the job! Memory usage is still 375 Mb on a 1-node master (without any configuration) :open_mouth:

Any way to cut this down (ideally to <100Mb RAM)?

**Comment by brandond** [comment]
If you can find a way to run the entire Kubernetes control plane plus datastore in less than 100mb, I think that would be newsworthy ;)

**Comment by toonsevrin** [comment]
Agreed, anyways, I've started a separate issue for this: #1944. Target is 150-200MB.

**Comment by brandond** [comment]
I have personally tried running it with as little as 256M, but it gets OOM killed pretty quick. at 384M it runs but doesn't perform well. As far as I can tell it should really have at least 512M.

**Comment by protosam** [comment]
Permalink for the curious that stumble upon this page: https://github.com/k3s-io/k3s/blob/5a81fdbdc5d02527c886af9a31324a73573d1909/pkg/cli/cmds/server.go#L302

**Comment by SOF3** [comment]
> I haven't tested it myself, but there's a hidden option for that:
> 
> https://github.com/rancher/k3s/blob/master/pkg/cli/cmds/server.go#L302

link is obsolete, which line are you actually referring to?

**Comment by brandond** [comment]
Because we don't technically support it. Many operators (system upgrade controller, etcd controller, and others) assume that the control-plane hosts will have nodes that can be used to track operations.

**Comment by protosam** [comment]
Much thanks @FabianKramm at Loft.sh for keeping the flag functional, ref: https://github.com/k3s-io/k3s/issues/4873 and https://github.com/k3s-io/k3s/issues/5118

It was definitely broken for a few versions, but has been fixed since this issue was originally created. When it was initially fixed, I don't think that the fix was propagated back to older releases.

**Comment by brandond** [comment]
Well I was the one that fixed both of those, but yes thanks to everyone for reporting issues.

**Comment by protosam** [comment]
I definitely misremembered that. Much thanks to you @brandond. Sorry about that.
