### ISSUE TITLE
Reduce master memory usage below 300MB

### ISSUE THREAD

**Issue by toonsevrin** [rancher/k3s#1944]
For a hobby project, I'm developing a system that allows you to run "kubescale up" on any machine (raspberry pi, vm...) and it will completely automatically connect to an overlay VPN an a k3s master in the cloud, turning the machine in a kubelet. 

As this is really quite amazing in practice, I am hoping to provide a free tier for this up to n nodes.

But currently the economics do not work out: A single k3s master still requires 300MB of RAM in steady-state. As I pay about 1 EUR/GBram/month, this free service would become relatively expensive for me to provide.

Are there ways to significantly reduce the memory usage? Ideally to about 150-200MB in steady-state. If I use a single etcd node for all masters, will this help with resource consumption?

**Comment by brandond** [comment]
I'm not sure what else you could cut out. k3s is already pretty stripped down compared to other kubernetes distributions.

**Comment by toonsevrin** [comment]
I got to agree with you on that :) 

Are there any components other then the database that could be shared among clusters?

**Comment by brandond** [comment]
You might take a look at https://github.com/kubernetes-sigs/multi-tenancy if you haven't yet.

**Comment by toonsevrin** [comment]
@brandond very interesting, virtual clusters would completely solve this issue (for the free tier). Thank you very much for the share!! I'm looking forward to that being implemented.

**Comment by toonsevrin** [comment]
I was able to reduce base memory usage to about 190 Mi by increasing garbage collection frequency (Environment variable GOGC=10)

**Comment by brandond** [comment]
@toonsevrin this seems to come at a cost to datastore performance. I haven't dug into it in great depth yet but there seem to be some internal resource caches that get purged excessively agressively if you run with low memory.

**Comment by toonsevrin** [comment]
Yep, always a tradeoff!

**Comment by toonsevrin** [comment]
Finally, if anyone is still interested: By removing the cloud-controller and keeping GOGC=10, base memory usage is down to 140-150mb :tada: 

P.S: Almost cheap enough for a free tier of the Kubescale service :stuck_out_tongue: dang I want to provide that (but fear that I won't be able to afford it)

**Comment by ccll** [comment]
@toonsevrin 
I'm very interested in your solution as I'm planning to run k3s on a cheap VPS box.

I'm following your advice as:
1. change systemd service executable to `k3s server --disable-cloud-controller`
2. add `Environment=GOGC=10` in systemd service file

My k3s server memory footprint reduced from around 500MB to 360MB, but still very far to your 150MB.
I'm running k3s version `v1.17.5+k3s1`.

What could be wrong?
Any help is appreciated!

**Comment by toonsevrin** [comment]
Hi ccll, I bet the main difference is that I reported the process memory, and you reported the server memory. Do a `top` to see your process usage. I only care about the process usage because I was going to run many k3s servers on one operating system.

**Comment by ccll** [comment]
@toonsevrin Thanks for the reply, I'm actually reading the memory usage from top/htop.

![image](https://user-images.githubusercontent.com/5366582/96074018-36347900-0eda-11eb-9a1c-c42fddd88bfc.png)

This is weird, I guess maybe we are using different versions of k3s?

**Comment by brandond** [comment]
300MB is pretty low, as discussed above and in other threads I'm not sure how much lower you can get it - especially if you plan on putting much load on the control plane.

**Comment by jdmarshall** [comment]
How much perf analysis has been done for k8s regarding memory footprint? With a smaller space budget, there's a longer list of memory inefficiencies that will cross the threshold of attention.

Given all the work k3s has already done, I don't doubt that the answer to 'make k3s smaller' might be 'make k8s (or embedded etcd) smaller'.

**Comment by fanlix** [comment]
* fresh install, default k3s  RES=**530M**
* with `GOGC=10` & `--disable-cloud-controller`, k3s RES=**310M**
  * append traefik,cordns,metrics.  total k3s cluster RES=**500M**

**Comment by yanggeorge** [comment]
@fanlix   I know  appending "--disable-cloud-controller"  to k3s.service, but where to  set GOGC ?  
Thx in advance.

**Comment by kerberjg** [comment]
@brandond Is it safe to disable the built-in cloud controller?

**Comment by brandond** [comment]
Only if you install a different cloud provider, otherwise the nodes will stay in uninitialized state.

**Comment by kerberjg** [comment]
Does this apply in a scenario where I manually provision VMs, let's say on a local network?

**Comment by brandond** [comment]
Yes. You need a stub cloud-provider (like the one K3s provides) to clear the uninitialized taint, or to do it manually with kubectl. Turning off the K3s cloud provider doesn't provide any meaningful reduction in memory anyway.

**Comment by yufengjinsong** [comment]
> @toonsevrin I'm very interested in your solution as I'm planning to run k3s on a cheap VPS box.
> 
> I'm following your advice as:
> 
> 1. change systemd service executable to `k3s server --disable-cloud-controller`
> 2. add `Environment=GOGC=10` in systemd service file
> 
> My k3s server memory footprint reduced from around 500MB to 360MB, but still very far to your 150MB. I'm running k3s version `v1.17.5+k3s1`.
> 
> What could be wrong? Any help is appreciated!

how do you set Environment=GOGC=10

**Comment by YYM0093** [comment]
> @fanlix如何设置环境=GOGC=10

Add Environment=GOGC=10 in the file /etc/systemd/system/k3s.service, then run systemctl restart k3s.
