### ISSUE TITLE
k3s server rootless failed

### ISSUE THREAD

**Issue by matthdan** [rancher/k3s#1949]
Hello all, 
I think that not many in the community to use the "rootless" k3s mode, that is an experimental mode, but very useful for testing in user land on latest system (like centos .7.7). I notice a non-functional behavior on k3s 1.18.X rootless mode.
Find all the information : 

**Version:**
```
$ k3s --version
k3s version v1.18.4+k3s1 (97b7a0e9)
```

**K3s arguments:**
```
k3s --debug server --rootless
```

**Describe the bug**
```
$ k3s server --rootless
FATA[2020-06-24T22:37:41.538205795+02:00] failed to setup network &{binary:slirp4netns mtu:65520 ipnet:0xc0012e2d50 disableHostLoopback:true apiSocketPath: enableSandbox:false enableSeccomp:false}: waiting for ready fd (/home/matth/.rancher/k3s/data/3a8d3d90c0ac3531edbdbde77ce4
a85062f4af8865b98cedc30ea730715d9d48/bin/slirp4netns --mtu 65520 -r 3 --disable-host-loopback --cidr 10.41.0.0/16 49044 tap0): slirp4netns failed 
FATA[2020-06-24T22:37:41.543622565+02:00] child diedparsing message from fd 3: EOF
```
It seems that the *slirp4netns* from rootlesskit is too old and not support the entire arguments:
```
 ./slirp4netns --mtu 65520 -r 3 --disable-host-loopback --cidr 10.41.0.0/16 49044 tap0
the option -r FD requires -c
```
default version : 
```
./slirp4netns  --version
slirp4netns version 0.3.0-alpha.2+dev
commit: unknown
```
updated version (from https://github.com/rootless-containers/slirp4netns/releases/tag/v1.1.1):  
```
$ ./slirp4netns  --version
slirp4netns version 1.1.1
commit: bbf27c5acd4356edb97fa639b4e15e0cd56a39d5
libslirp: 4.3.0
SLIRP_CONFIG_VERSION_MAX: 3
```
After manually update the *slirp4netns* to the latest stable version, everything comes normal! :+1: 

**To Reproduce**
wget k3s x86_64 binary from github and lanch the command.

**Expected behavior**
k3s correcly launch and *k3s kubectl get pods* working.
Seems just a simple build deps update to update rootlesskit to 0.7.X to 0.9.5 (latest at this date)

**Additional context / logs**
Running on a centos 7.7 with a Docker rootless working like a charm ! 

thank you community for your help ! 

Cheers

**Comment by brandond** [comment]
There are a couple PRs open for this but for some reason none of them have been merged yet: https://github.com/rancher/k3s-root/pulls

**Comment by matthdan** [comment]
Indeed, seems duplicate #1709. thank you @brandond for your infos !

Best!
