### ISSUE TITLE
Installation on Alpine Linux failed

### ISSUE THREAD

**Issue by MarkusAGSchmidt** [rancher/k3s#1972]
**Version:**
v1.18.4+k3s1

**K3s arguments:**
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.18.4+k3s1 sh -s - server --token p147f0rm

**Describe the bug**
The installation of k3s (as master) on Alpine Linux failed, because the service cloud not be started.
Note, that the above curl command works for Debian Linux.

**To Reproduce**
Get a clean Alpine VM (e.g. Virtual boxes roboxes/alpine39 and generic/alpine39) and execute the above curl command.

**Expected behavior**
The service is started successfully.

**Actual behavior**
The service failed to start because of an invalid value of  **respawn-max** in the init script.

**Workaround**
Modify content of init script so that the value of **respawn-max** is 1.

**Additional context / logs**
Console output:
> [INFO]  openrc: Starting k3s
>  * Caching service dependencies ...  [ ok ]
>  * Mounting cgroup filesystem ...    [ ok ]
>  * Starting k3s ...
>  * failed to start k3s [ !! ]
>  * ERROR: k3s failed to start

 /var/log/messages:

> Jun 29 08:33:04 alpine39 authpriv.notice sudo:  vagrant : TTY=pts/0 ; PWD=/home/vagrant ; USER=root ; COMMAND=/etc/init.d/k3s restart
> Jun 29 08:33:04 alpine39 daemon.err /etc/init.d/k3s[2665]: Invalid respawn-max value '0'
> Jun 29 08:33:04 alpine39 daemon.err /etc/init.d/k3s[2450]: ERROR: k3s failed to start

**Comment by ShylajaDevadiga** [comment]
@MarkusAGSchmidt From the logs respawn-max  flag seems to be invalid. Could you update it to respawn_max and and see if it fixes the issue?
I tried installing k3s version v1.18.4+k3s1 and v1.18.6+k3s1 successfully without workarounds. 

```
alpine:~# cat /etc/alpine-release 
3.12.0
alpine:~# k3s -v
k3s version v1.18.4+k3s1 (97b7a0e9)
alpine:~# kubectl get nodes 
NAME     STATUS   ROLES    AGE     VERSION
alpine   Ready    master   2m36s   v1.18.4+k3s1
alpine:~# kubectl get pods -A 
NAMESPACE     NAME                                     READY   STATUS      RESTARTS   AGE
kube-system   local-path-provisioner-6d59f47c7-p8mn9   1/1     Running     0          2m30s
kube-system   metrics-server-7566d596c8-686fh          1/1     Running     0          2m30s
kube-system   helm-install-traefik-jdhb4               0/1     Completed   0          2m30s
kube-system   svclb-traefik-4mgcc                      2/2     Running     0          2m12s
kube-system   coredns-8655855d6-z66zg                  1/1     Running     0          2m30s
kube-system   traefik-758cd5fc85-cttvw                 1/1     Running     0          2m12s
alpine:~# cat /etc/init.d/k3s
#!/sbin/openrc-run

depend() {
    after network-online
    want cgroups
}

start_pre() {
    rm -f /tmp/k3s.*
}

supervisor=supervise-daemon
name=k3s
command="/usr/local/bin/k3s"
command_args="server \
    >>/var/log/k3s.log 2>&1"

output_log=/var/log/k3s.log
error_log=/var/log/k3s.log

pidfile="/var/run/k3s.pid"
respawn_delay=5
respawn_max=0

set -o allexport
if [ -f /etc/environment ]; then source /etc/environment; fi
if [ -f /etc/rancher/k3s/k3s.env ]; then source /etc/rancher/k3s/k3s.env; fi
set +o allexport
```

**Comment by brandond** [comment]
This appears to be a bug in Alpine see respawn_max in the openrc docs:
https://github.com/OpenRC/openrc/blob/master/supervise-daemon-guide.md#variable-settings

**Comment by brandond** [comment]
You might also try a newer release of Alpine, 3.9 is only a couple months out from end-of-life: https://wiki.alpinelinux.org/wiki/Alpine_Linux:Releases

**Comment by brandond** [comment]
OpenRC added support for setting this to 0 about 16 months ago: https://github.com/OpenRC/openrc/commit/54780a45826f789f1291742eb2c99be369bfe64c

**Comment by ShylajaDevadiga** [comment]
As @brandond mentioned we see this issue in older version of Alpine 
```
cat /etc/alpine-release 
3.9.6
```
Logs:
```
Jul 21 06:39:01 alpine39 daemon.err /etc/init.d/k3s[2200]: Invalid respawn-max value '0'
Jul 21 06:39:01 alpine39 daemon.err /etc/init.d/k3s[2180]: ERROR: k3s failed to start
```

**Comment by ShylajaDevadiga** [comment]
Closing the issue as it is narrowed down to old Alpine version. @MarkusAGSchmidt  please feel free to reopen if you have any concerns. Thanks.
