### ISSUE TITLE
/var/lib/rancher/k3s/ is 9GB on master, 12GB on worker nodes after 60 Days

### ISSUE THREAD

**Issue by admantium-sg** [rancher/k3s#1976]
**Environmental Info:**
K3s Version: 
k3s version v1.17.2+k3s1 (cdab19b0)

Node(s) CPU architecture, OS, and Version: 
Linux k3s-server 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux

Cluster Configuration:
1 master, 2 nodes

**Describe the bug:**
On the master node, /var/lib/rancher/k3s/  consumes 9GB after 60 days of operations.
On the worker nodes, /var/lib/rancher/k3s/  consumes 12GB after 60 days of operations.

How to clean up old files? E.g. there seems to be a lot of snapshot data in 	/var/lib/rancher/k3s/agent/containerd/io.containerd.snapshotter.v1.overlay

**Steps To Reproduce:**
- Install K3S
- Run for 60 days

**Expected behavior:**
- Less space required

**Actual behavior:**
- 9GB required

**Additional context / logs:**
- n.a.

**Comment by brandond** [comment]
See the discussion on image garbage collection here: https://github.com/rancher/k3s/issues/1900#issuecomment-644453072

**Comment by admantium-sg** [comment]
Thank you very much!

I executed `k3s crictl rmi --prune` on each machine.

- master: 9GB => 1.4GB
- worker: 12GB => 2.6GB

**Comment by admantium-sg** [comment]
Please close this ticket.
