### ISSUE TITLE
Unable to continue work if network temporary interrupted

### ISSUE THREAD

**Issue by pranasblk** [rancher/k3s#198]
**Describe the bug**
I was trying hello word style cluster definition:

``
apiVersion: v1
kind: Pod
metadata:
  name: example
spec:
  containers:
  - name: web
    image: nginx
  - name: centos
    image: centos
    command: ["/bin/sh", "-c", "while : ;do curl http://localhost:80/; sleep 10; done"]
``

but laptop Wifi connection got interrupted.

I have ended up with dead pod:

``
Events:
  Type    Reason     Age   From                            Message
  ----    ------     ----  ----                            -------
  Normal  Scheduled  29m   default-scheduler               Successfully assigned default/example to localhost.localdomain
  Normal  Pulling    29m   kubelet, localhost.localdomain  pulling image "nginx"
  Normal  Pulled     21m   kubelet, localhost.localdomain  Successfully pulled image "nginx"
  Normal  Created    21m   kubelet, localhost.localdomain  Created container
  Normal  Started    21m   kubelet, localhost.localdomain  Started container
  Normal  Pulling    21m   kubelet, localhost.localdomain  pulling image "centos"
``

**To Reproduce**

**Expected behavior**
Pooling of image would recover after temporary network interruption.

**Additional context**
I have tried to kill and restart k3s server (with all default services) and it did not help.

Deleting cluster seems to me very drastic, but I'll do it after bug sumission ...

**Comment by ShylajaDevadiga** [comment]
Unable to reproduce this issue.
When the network is down pod network is interrupted and recovers when the network connectivity is restored.

```root@localhost:~# k get pods -A
NAMESPACE     NAME                                      READY   STATUS         E
kube-system   coredns-57d8bbb86-55bfd                   1/1     Running        m
kube-system   helm-install-traefik-rq4l7                0/1     Completed      m
kube-system   svclb-traefik-9w64r                       3/3     Running        m
kube-system   traefik-65bccdc4bd-5dw9h                  1/1     Running        m
default       example                                   2/2     Running        m
kube-system   local-path-provisioner-58fb86bdfd-ndlmf   0/1     CrashLoopBackOfm
root@localhost:~# k logs -n kube-system local-path-provisioner-58fb86bdfd-ndlmf
Error from server: Get https://localhost:10250/containerLogs/kube-system/local-t
root@localhost:~# ifconfig eth0 up
root@localhost:~# k get pods -A
NAMESPACE     NAME                                      READY   STATUS      RESE
kube-system   coredns-57d8bbb86-55bfd                   1/1     Running     0  m
kube-system   helm-install-traefik-rq4l7                0/1     Completed   0  m
kube-system   svclb-traefik-9w64r                       3/3     Running     0  m
kube-system   traefik-65bccdc4bd-5dw9h                  1/1     Running     0  m
default       example                                   2/2     Running     0  m
kube-system   local-path-provisioner-58fb86bdfd-ndlmf   1/1     Running     15 m
root@localhost:~# 
```

**Comment by davidnuzik** [comment]
@pranasblk we were not able to reproduce the issue with the latest release. If you still observe the issue with the latest release please let us know and we can re-open the issue if necessary.
