### ISSUE TITLE
kubectrl delete -f cluster_def.yaml does not finish

### ISSUE THREAD

**Issue by pranasblk** [rancher/k3s#199]
**Describe the bug**
Attempt to delete pot rendered my console to indefinitely running command.

**To Reproduce**
(base) [pranas@localhost kube-boook]$ ls
3-2-1_pod.yaml
(base) [pranas@localhost kube-boook]$ kubectl delete -f 3-2-1_pod.yaml
pod "example" deleted

**Expected behavior**
I'd like to get my command prompt back after cluster has been deleted.

**Additional context**
The system was in "strange" state. See #198

**Comment by pranasblk** [comment]
I'm total newbie for Kubernets but expect some log entry on the pod during deletion:

Events:
  Type    Reason     Age   From                            Message
  ----    ------     ----  ----                            -------
  Normal  Scheduled  41m   default-scheduler               Successfully assigned default/example to localhost.localdomain
  Normal  Pulling    41m   kubelet, localhost.localdomain  pulling image "nginx"
  Normal  Pulled     33m   kubelet, localhost.localdomain  Successfully pulled image "nginx"
  Normal  Created    33m   kubelet, localhost.localdomain  Created container
  Normal  Started    33m   kubelet, localhost.localdomain  Started container
  Normal  Pulling    33m   kubelet, localhost.localdomain  pulling image "centos"
(base) [pranas@localhost kube-boook]$ kubectl create -f 3-2-1_pod.yaml 
Error from server (AlreadyExists): error when creating "3-2-1_pod.yaml": object is being deleted: pods "example" already exists

**Comment by erikwilson** [comment]
Closing this in favor of fixing the root of the issue in rancher/k3s/issues/198
