### ISSUE TITLE
Can't specify interface/IP for controller, leading to invalid apiserver certificate

### ISSUE THREAD

**Issue by discordianfish** [rancher/k3s#200]
**Describe the bug**
I have 3 network interfaces. k3s server should be made reachable on the IP of eth2. k3s selects the IP of eth0 for use in the apiserver certificate though, making the certificate invalid to be used for connecting to the IP on eth2.

**To Reproduce**
- Configure multiple interfaces
- run k3s server
- Connect to k3s via the IP of the second interface

**Expected behavior**
I should be able to configure the apiserver certificates IP addresses or the interface to use.

**Comment by yoink00** [comment]
I believe this duplicates issue #72

**Comment by discordianfish** [comment]
Depends on the resolution, but yeah if one could specify interface it would also solve #72. Leaving it to @ibuildthecloud to close this one.

**Comment by erikwilson** [comment]
This should be addressed by the `--tls-san` flag from PR rancher/k3s/pull/239 and https://github.com/rancher/k3s/issues/214#issuecomment-478003830, if not please re-open.

**Comment by discordianfish** [comment]
That works, thanks!

**Comment by cbluth** [comment]
@discordianfish can you explain how you were able to get it to work? which command did you use to install?
