### ISSUE TITLE
k3s seems to require more than 512MB RAM

### ISSUE THREAD

**Issue by carlosonunez** [rancher/k3s#2003]
## **Is your feature request related to a problem? Please describe.**
This is a problem with a potential feature request attached.

I tried provisioning a two-node k3s cluster within Vagrant with a vanilla install. Each node ran Alpine Linux and had 512MB RAM, the minimum amount of memory required per the documentation. 

My experience was not good:

- The primary node had less than 4M free, which you can see from running `top`.
- All `kubectl` commands hung due to connection and TLS timeouts. Some would succeed, which is another strong indicator of resource starvation.

## **Describe the solution you'd like**

I would love to run Kubernetes with 512MB RAM (or less)! This would make it easy to run a k3s cluster on resource-constrained machines (like my 8GB Mac Mini). Additional configuration might be required to enable this, however. Instructions on how to do that would be great!

## **Describe alternatives you've considered**
I originally tried running my cluster with Ubuntu Xenial but switched to Alpine to make my nodes even leaner.

**Comment by carlosonunez** [comment]
Here are some stats from a cluster I started up:

```sh
k3s-node-0:~$ # Here are my stats before executing any kubectl commands.
k3s-node-0:~$ time sudo ps -efo comm,pid,rss,args | grep -Ei "COMMAND|k3s|kube"
COMMAND          PID   RSS  COMMAND
supervise-daemo   1983   56 supervise-daemon --start --pidfile /var/run/k3s.pid /usr/local/bin/k3s -- server --node-ip=192.168.50.2 --flannel-iface=eth1
containerd-shim   2499 2252 /var/lib/rancher/k3s/data/3a8d3d90c0ac3531edbdbde77ce4a85062f4af8865b98cedc30ea730715d9d48/bin/containerd-shim-runc-v2 -namespace k8s.io -id 7d1a4c7579a638743de2377b95db572eb1d8ead6866423da7f4172ef897af2fa -address /run/k3s/containerd/containerd.sock
containerd-shim   2501 2160 /var/lib/rancher/k3s/data/3a8d3d90c0ac3531edbdbde77ce4a85062f4af8865b98cedc30ea730715d9d48/bin/containerd-shim-runc-v2 -namespace k8s.io -id ef78dedbfb8a2a91c67aa7e25d1ef1586b412f2ebba9e2b7a14550ae3c665c6f -address /run/k3s/containerd/containerd.sock
containerd-shim   2520 2020 /var/lib/rancher/k3s/data/3a8d3d90c0ac3531edbdbde77ce4a85062f4af8865b98cedc30ea730715d9d48/bin/containerd-shim-runc-v2 -namespace k8s.io -id dea89f95498d4f196065fee96e0dae7268e586f231b15562262494d251ed700f -address /run/k3s/containerd/containerd.sock
k3s-server       13564 387m {k3s-server} /usr/local/bin/k3s server --node-ip=192.168.50.2 --flannel-iface=eth1
containerd       13578  35m containerd -c /var/lib/rancher/k3s/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state /run/k3s/containerd --root /var/lib/rancher/k3s/agent/containerd
containerd-shim  13929 2012 /var/lib/rancher/k3s/data/3a8d3d90c0ac3531edbdbde77ce4a85062f4af8865b98cedc30ea730715d9d48/bin/containerd-shim-runc-v2 -namespace k8s.io -id 928ad7088e182652e44170a83af3e6b122b9fafc64717b605a6059713a175b5c -address /run/k3s/containerd/containerd.sock
grep             15937    4 grep -Ei COMMAND|k3s|kube
real    0m 0.30s
user    0m 0.00s
sys     0m 0.00s
k3s-node-0:~$ time cat /proc/meminfo | grep -Ei 'memtotal|memfree' # Mem free
MemTotal:         501512 kB
MemFree:            4704 kB
real    0m 0.46s
user    0m 0.00s
sys     0m 0.00s
k3s-node-0:~$ k3s kubectl get nodes & # Backgrounding to show mem consumption difference.
k3s-node-0:~$ time cat /proc/meminfo | grep -Ei 'memtotal|memfree'
real    0m 0.14s
user    0m 0.00s
sys     0m 0.00s
MemTotal:         501512 kB
MemFree:            4724 kB
k3s-node-0:~$ time sudo ps -efo comm,pid,rss,args | grep -Ei "COMMAND|k3s|kube"
COMMAND          PID   RSS  COMMAND
supervise-daemo   1983   56 supervise-daemon --start --pidfile /var/run/k3s.pid /usr/local/bin/k3s -- server --node-ip=192.168.50.2 --flannel-iface=eth1
containerd-shim   2499 2252 /var/lib/rancher/k3s/data/3a8d3d90c0ac3531edbdbde77ce4a85062f4af8865b98cedc30ea730715d9d48/bin/containerd-shim-runc-v2 -namespace k8s.io -id 7d1a4c7579a638743de2377b95db572eb1d8ead6866423da7f4172ef897af2fa -address /run/k3s/containerd/containerd.sock
containerd-shim   2501 2192 /var/lib/rancher/k3s/data/3a8d3d90c0ac3531edbdbde77ce4a85062f4af8865b98cedc30ea730715d9d48/bin/containerd-shim-runc-v2 -namespace k8s.io -id ef78dedbfb8a2a91c67aa7e25d1ef1586b412f2ebba9e2b7a14550ae3c665c6f -address /run/k3s/containerd/containerd.sock
containerd-shim   2520 2052 /var/lib/rancher/k3s/data/3a8d3d90c0ac3531edbdbde77ce4a85062f4af8865b98cedc30ea730715d9d48/bin/containerd-shim-runc-v2 -namespace k8s.io -id dea89f95498d4f196065fee96e0dae7268e586f231b15562262494d251ed700f -address /run/k3s/containerd/containerd.sock
k3s-server       13564 387m {k3s-server} /usr/local/bin/k3s server --node-ip=192.168.50.2 --flannel-iface=eth1
containerd       13578  35m containerd -c /var/lib/rancher/k3s/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state /run/k3s/containerd --root /var/lib/rancher/k3s/agent/containerd
containerd-shim  13929 1948 /var/lib/rancher/k3s/data/3a8d3d90c0ac3531edbdbde77ce4a85062f4af8865b98cedc30ea730715d9d48/bin/containerd-shim-runc-v2 -namespace k8s.io -id 928ad7088e182652e44170a83af3e6b122b9fafc64717b605a6059713a175b5c -address /run/k3s/containerd/containerd.sock
kubectl          15945 1040 kubectl get nodes
grep             15954    8 grep -Ei COMMAND|k3s|kube
real    0m 0.03s
user    0m 0.00s
sys     0m 0.00s
k3s-node-0:~$

```

**Comment by brandond** [comment]
I would say that 512mb is the minimum for a server. You can cut the k3s server process down to about 300mb with systemd limits, otherwise it will use a bit more to prevent go from having to garbage collect too aggressively. Agents can get by with a little less memory since they don't have to run any controllers.

If you want to run workloads pods on a server, you're obviously going to need more memory for those. With all the memory used up by processes there will be very little left for OS filesystem cache, and things will probably be quite slow. If you haven't followed kubernetes best practices and disabled swap on your nodes, you'll probably find that the system is swapping hard, which is actually worse than things getting killed due to out-of-memory in my experience.

**Comment by carlosonunez** [comment]
Fair points, but I would say that publishing a memory floor that allows for a k3s server that can’t run pods in a meaningful way is worse than publishing a higher floor that can at least support _some_ workloads along with the OS. (Your min for k3s server lines up with my observations; a controller that did nothing consumed about 380m in my little experiment).

**Comment by brandond** [comment]
It's the minimum. It's the lowest possible amount you can have and reasonably expect things to work. Obviously things are not going to work GREAT at the minimum level. Is there a better way that you think this could be phrased on the website?

**Comment by carlosonunez** [comment]
I think so! I've pushed a pull request showing how I would word this. What do you think?

**Comment by cjellick** [comment]
Merged the pr. going to close
