### ISSUE TITLE
Windows Binary 

### ISSUE THREAD

**Issue by luistrigueiros** [rancher/k3s#202]
Where can I find the windows binary it does not look to be in the released  binaries but the site  mentions support for it.

Thank you, kindly
Oscar

**Comment by jackharrhy** [comment]
> Linux 3.10+

^ Mentioned in the "Minimum System Requirements" tab on https://k3s.io/, no mention of Windows support.

**Comment by bencompton** [comment]
Dupe of #114?

**Comment by ibuildthecloud** [comment]
We have no support for windows right now. The best bet would be to run Docker for Windows and try the `docker-compose.yml` in the root of this repo.

**Comment by deniseschannon** [comment]
Closing in favor of #114

**Comment by coderafei** [comment]
@ibuildthecloud https://github.com/rancher/k3s/blob/master/docker-compose-agent.yml can not run on windows
Failed to get system container stats for...
