### ISSUE TITLE
Upgrade to kubernetes v1.19.0

### ISSUE THREAD

**Issue by davidnuzik** [rancher/k3s#2020]
Vendor in v1.19.0 into master so QA and community testing can begin.

**Comment by davidnuzik** [comment]
Posting here for informative purposes. upstream v1.19.0 k8s is out: https://github.com/kubernetes/sig-release/issues/1196
(As of posting 8/26 2:30pm pacific they have yet to check everything off but is indeed [done](https://github.com/kubernetes/kubernetes/releases/tag/v1.19.0) and publicly announced. They just haven't updated the linked GH issue yet)

**Comment by cjellick** [comment]
We're actively working on this. Approximate timeline is to release k3s 1.19 in two weeks.

We need to update k3s's authentication bootstrapping due to the removal of the `--basic-auth-file` flag being dropped from Kubernetes (see https://github.com/kubernetes/kubernetes/pull/89069)

**Comment by schmitch** [comment]
also some existing clusters probably were created with basic-auth-file as the main authn mechanism so that should be migrated to `--basic-auth-token` aswell.

**Comment by davidnuzik** [comment]
Upstream v1.19.1 plans to drop 9/9; as such we created https://github.com/rancher/k3s/issues/2217 to bump to this. We plan to push out k3s v1.19.1+k3s1 and skip .0 due to 1) the testing effort required for a new minor release and 2) the short time between .0 and .1 release upstream.

**Comment by davidnuzik** [comment]
I am closing this issue because we will test v1.19 via https://github.com/rancher/k3s/issues/2217 (v1.19.1) instead.
