### ISSUE TITLE
k3s server is started failed

### ISSUE THREAD

**Issue by lojurn** [rancher/k3s#2024]
ubuntu 16.0.4 start k3s server,   I get a error below, 
 level=error msg="Failed to generate kubeconfig: server https://127.0.0.1:6443/cacerts is not trusted: Get https://127.0.0.1:6443/cacerts: x509: certificate signed by unknown authority"
it looks like a CA problem
k3s.yaml file generate failed.   How to solve this problem?

**Comment by lojurn** [comment]
I solve the problem myself.  

sudo cd /var/lib/rancher/k3s/agent
sudo cp *.crt /usr/local/share/ca-certificates
sudo update-ca-certificates

**Comment by lojurn** [comment]
can I do that? Is that right?

**Comment by brandond** [comment]
No, you should not need to do that. k3s uses internal CAs to establish trust between components. These should not be trusted at a system level.
