### ISSUE TITLE
Version parameter doesn't show correct version

### ISSUE THREAD

**Issue by superseb** [rancher/k3s#203]
Thanks for helping us to improve k3s! We welcome all bug reports. At this stage, we are also looking for help in testing/QAing fixes. Once we've fixed you're issue, we'll ping you in the comments to see if you can verify the fix. We'll give you details on what version can be used to test the fix. Additionally, if you are interested in testing fixes that you ***didn't*** report, look for the issues with the `status/to-test` label. You can pick any of these up for verification.  ***You can delete this message portion of the bug report.***

**Describe the bug**
Version info is wrong when using `k3s --version`

**To Reproduce**

* Download k3s binary
* Run `k3s --version`
```
k3s --version
k3s version dev (HEAD)
```

**Expected behavior**
compiled version (tag/commit etc)

**Screenshots**

**Additional context**

**Comment by dnoland1** [comment]
Tested with v0.3.0-rc4 build:
```
vagrant@k3s-node1:~$ k3s -version
k3s version v0.3.0-rc4 (44d2f3a)
```

**Comment by erikwilson** [comment]
Thanks for testing @dnoland1!
