### ISSUE TITLE
How to use K3S_CLUSTER_INIT enviroment variable.

### ISSUE THREAD

**Issue by OrwillT** [rancher/k3s#2038]
Given that the relevant flag does not require value, how to use `K3S_CLUSTER_INIT` and `K3S_CLUSTER_RESET` as enviroment variable?

**Comment by brandond** [comment]
I believe you should just be able to set them to any non-empty string. Are you seeing different behavior?

**Comment by OrwillT** [comment]
No I didn't, I just don't understand how this work at that time. Thanks for your help. 😄
