### ISSUE TITLE
k3s installing master - dial tcp 10.43.0.1:443: connect: no route to host

### ISSUE THREAD

**Issue by jrcichra** [rancher/k3s#2046]
**Environmental Info:**
K3s Version: 

`k3s version v1.18.6+k3s1 (6f56fa1d)`
Node(s) CPU architecture, OS, and Version: 

`Linux oracle01 5.4.0-1021-oracle #21-Ubuntu SMP Fri Jul 10 06:33:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
+ Ubuntu 20.04 Oracle Cloud Free Tier
+ 2CPU 1GB RAM 2GB Swap 50GB storage

Cluster Configuration:

Trying to spin up a master with `curl -sfL https://get.k3s.io | sh -s - server --docker`

**Describe the bug:**

Pods are crashing over and over with only kube-system containers, no api endpoint (which is what the error is in the pods):
```
root@oracle01:/home/justin# kubectl get pods -A
NAMESPACE     NAME                                     READY   STATUS             RESTARTS   AGE
kube-system   coredns-8655855d6-97dzm                  0/1     Running            0          85s
kube-system   metrics-server-7566d596c8-tndj2          0/1     Error              2          85s
kube-system   helm-install-traefik-jbptr               0/1     CrashLoopBackOff   2          86s
kube-system   local-path-provisioner-6d59f47c7-jshnb   0/1     Error              3          85s
root@oracle01:/home/justin# 
```
`kubectl logs coredns-8655855d6-97dzm -n kube-system`
`E0721 20:03:36.509863       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Service: Get https://10.43.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.43.0.1:443: connect: no route to host`
**Steps To Reproduce:**

- Installed K3s with the curl from the website, with and without the docker flag (I'd just prefer to use docker). k3s output from the script seems fine but pods aren't starting

**Expected behavior:**
I have a master node that doesn't have crashing pods unable to find the API endpoint.

**Actual behavior:**
Pods crash and can't find the endpoint. Also seeing less pods than I'd expect.

**Additional context / logs:**

`docker version`
```
root@oracle01:/home/justin# docker version
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:44 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:15 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by brandond** [comment]
I haven't played with Oracle Cloud myself but I notice that this node is running an Oracle kernel, not one of the normal Ubuntu kernels. Is this a full VM or just a container-based VPS? You might run `k3s check-config` and see what you get.

**Comment by jrcichra** [comment]
That's a pretty cool command. Here's what I got (FYI I put swap on because 1Gig ran me out of RAM given what comes with the VM, so I needed some swap space to keep from freezing.

```
justin@oracle01:~$ k3s check-config

Verifying binaries in /var/lib/rancher/k3s/data/6ab65ee0083924a980f6161177c37163fa68681b710316bb3dc59f118ff27636/bin:
- sha256sum: good
- links: good

System:
- /usr/sbin iptables v1.8.4 (legacy): ok
- swap: should be disabled
- routes: ok

Limits:
- /proc/sys/kernel/keys/root_maxkeys: 1000000

modprobe: FATAL: Module configs not found in directory /lib/modules/5.4.0-1021-oracle
info: reading kernel config from /boot/config-5.4.0-1021-oracle ...

Generally Necessary:
- cgroup hierarchy: properly mounted [/sys/fs/cgroup]
- /sbin/apparmor_parser
apparmor: enabled and tools installed
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_CPUSETS: enabled
- CONFIG_MEMCG: enabled
- CONFIG_KEYS: enabled
- CONFIG_VETH: enabled (as module)
- CONFIG_BRIDGE: enabled (as module)
- CONFIG_BRIDGE_NETFILTER: enabled (as module)
- CONFIG_NF_NAT_IPV4: missing (fail)
- CONFIG_IP_NF_FILTER: enabled (as module)
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_IPVS: enabled (as module)
- CONFIG_IP_NF_NAT: enabled (as module)
- CONFIG_NF_NAT: enabled (as module)
- CONFIG_NF_NAT_NEEDED: missing (fail)
- CONFIG_POSIX_MQUEUE: enabled

Optional Features:
- CONFIG_USER_NS: enabled
- CONFIG_SECCOMP: enabled
- CONFIG_CGROUP_PIDS: enabled
- CONFIG_BLK_CGROUP: enabled
- CONFIG_BLK_DEV_THROTTLING: enabled
- CONFIG_CGROUP_PERF: enabled
- CONFIG_CGROUP_HUGETLB: enabled
- CONFIG_NET_CLS_CGROUP: enabled (as module)
- CONFIG_CGROUP_NET_PRIO: enabled
- CONFIG_CFS_BANDWIDTH: enabled
- CONFIG_FAIR_GROUP_SCHED: enabled
- CONFIG_RT_GROUP_SCHED: missing
- CONFIG_IP_NF_TARGET_REDIRECT: enabled (as module)
- CONFIG_IP_SET: enabled (as module)
- CONFIG_IP_VS: enabled (as module)
- CONFIG_IP_VS_NFCT: enabled
- CONFIG_IP_VS_PROTO_TCP: enabled
- CONFIG_IP_VS_PROTO_UDP: enabled
- CONFIG_IP_VS_RR: enabled (as module)
- CONFIG_EXT4_FS: enabled
- CONFIG_EXT4_FS_POSIX_ACL: enabled
- CONFIG_EXT4_FS_SECURITY: enabled
- Network Drivers:
  - "overlay":
    - CONFIG_VXLAN: enabled (as module)
      Optional (for encrypted networks):
      - CONFIG_CRYPTO: enabled
      - CONFIG_CRYPTO_AEAD: enabled
      - CONFIG_CRYPTO_GCM: enabled
      - CONFIG_CRYPTO_SEQIV: enabled
      - CONFIG_CRYPTO_GHASH: enabled
      - CONFIG_XFRM: enabled
      - CONFIG_XFRM_USER: enabled (as module)
      - CONFIG_XFRM_ALGO: enabled (as module)
      - CONFIG_INET_ESP: enabled (as module)
      - CONFIG_INET_XFRM_MODE_TRANSPORT: missing
- Storage Drivers:
  - "overlay":
    - CONFIG_OVERLAY_FS: enabled (as module)

STATUS: 2 (fail)

```

**Comment by brandond** [comment]
Hmm that all looks OK. Can you provide full k3s service logs? Have you tried disabling the iptables firewall to see if that changes anything?

**Comment by jrcichra** [comment]
Thanks for pointing out Oracle Cloud as an oddity, that helped me find some older issues that referenced Oracle Cloud and similar issues. Adding these two IP table rules seemed to fix the issue:

https://github.com/rancher/k3s/issues/977#issuecomment-552504848

I made a service with NodePort and added this field to the VPC ingress rules (probably a generally terrible idea for security):

![image](https://user-images.githubusercontent.com/1342149/88114902-ecf6b680-cb82-11ea-8718-003afd5c6f7b.png)

Which lets Oracle have all ports opened up on my VPC to the outside world.

Thanks for your assistance!

**Comment by eramax** [comment]
I had the same issue and the fix was 
`sudo iptables -P INPUT ACCEPT  
curl -sfL https://get.k3s.io -o k3s 
chmod +x k3s
./k3s server  --write-kubeconfig-mode 644  --write-kubeconfig  $HOME/.kube/config --node-name master --bind-address 0.0.0.0 --node-external-ip xx.xx.xx.xx --tls-san xx.com --cluster-domain xx.com
`
