### ISSUE TITLE
Backup/restore with MySql failes

### ISSUE THREAD

**Issue by travis-sobeck** [rancher/k3s#2055]
k3s version v1.18.6+k3s1 (6f56fa1d)

Node(s) CPU architecture, OS, and Version: 
Linux iat-k3s-1 4.15.0-111-generic #112-Ubuntu SMP Thu Jul 9 20:32:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
single master

**Describe the bug:**
Simulating DR, cluster fails to start after restoring DB

**Steps To Reproduce:**
- Installed K3s with MySql DB (works great)
- backup DB (mysqldump)
- Variation 1: uninstall k3s
- Variation 2: shutdown vm running k3s
- Restore DB (delete/drop the "kine" table, restore table and data)
- Variation 1: reinstall k3s with exact same command used in step 1
- Variation 2: power up vm running k3s

**Expected behavior:**
k3s starts up and resumes service, there by simulating a full recovery.

**Actual behavior:**
k3s fails to start

**Additional context / logs:**
From journalctl -xe
-- Unit k3s.service has begun starting up.
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: time="2020-07-23T14:05:54.043577585Z" level=info msg="Starting k3s v1.18.6+k3s1 (6f56fa1d)"
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: time="2020-07-23T14:05:54.048848554Z" level=info msg="Cluster bootstrap already complete"
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: time="2020-07-23T14:05:54.078389805Z" level=info msg="Kine listening on unix://kine.sock"
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: time="2020-07-23T14:05:54.082914572Z" level=info msg="Running kube-apiserver --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=u
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: Flag --basic-auth-file has been deprecated, Basic authentication mode is deprecated and will be removed in a future release. It is not recommended for production e
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: I0723 14:05:54.086031    7671 server.go:645] external host was not specified, using 10.32.210.99
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: I0723 14:05:54.086647    7671 server.go:162] Version: v1.18.6+k3s1
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: I0723 14:05:54.097775    7671 plugins.go:158] Loaded 12 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,Servic
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: I0723 14:05:54.105753    7671 plugins.go:161] Loaded 10 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: I0723 14:05:54.113079    7671 plugins.go:158] Loaded 12 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,Servic
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: I0723 14:05:54.113429    7671 plugins.go:161] Loaded 10 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: I0723 14:05:54.154324    7671 master.go:270] Using reconciler: lease
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: E0723 14:05:54.227420    7671 cacher.go:428] unexpected ListAndWatch error: storage/cacher.go:/secrets: Failed to list *core.Secret: unexpected EOF
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: E0723 14:05:54.237013    7671 cacher.go:428] unexpected ListAndWatch error: storage/cacher.go:/configmaps: Failed to list *core.ConfigMap: unexpected EOF
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: E0723 14:05:54.243491    7671 cacher.go:428] unexpected ListAndWatch error: storage/cacher.go:/namespaces: Failed to list *core.Namespace: unexpected EOF
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: E0723 14:05:54.257183    7671 cacher.go:428] unexpected ListAndWatch error: storage/cacher.go:/serviceaccounts: Failed to list *core.ServiceAccount: unexpected EOF
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: E0723 14:05:54.261758    7671 cacher.go:428] unexpected ListAndWatch error: storage/cacher.go:/services/endpoints: Failed to list *core.Endpoints: unexpected EOF
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: E0723 14:05:54.264284    7671 cacher.go:428] unexpected ListAndWatch error: storage/cacher.go:/services/specs: Failed to list *core.Service: unexpected EOF
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: E0723 14:05:54.268202    7671 cacher.go:428] unexpected ListAndWatch error: storage/cacher.go:/minions: Failed to list *core.Node: unexpected EOF
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: I0723 14:05:54.269472    7671 rest.go:113] the default service ipfamily for this cluster is: IPv4
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: E0723 14:05:54.347454    7671 cacher.go:428] unexpected ListAndWatch error: storage/cacher.go:/pods: Failed to list *core.Pod: unexpected EOF
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: E0723 14:05:54.475360    7671 cacher.go:428] unexpected ListAndWatch error: storage/cacher.go:/jobs: Failed to list *batch.Job: unexpected EOF
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: E0723 14:05:54.486248    7671 cacher.go:428] unexpected ListAndWatch error: storage/cacher.go:/endpointslices: Failed to list *discovery.EndpointSlice: unexpected
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: E0723 14:05:54.486863    7671 cacher.go:428] unexpected ListAndWatch error: storage/cacher.go:/leases: Failed to list *coordination.Lease: unexpected EOF
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: E0723 14:05:54.494219    7671 cacher.go:428] unexpected ListAndWatch error: storage/cacher.go:/leases: Failed to list *coordination.Lease: unexpected EOF
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: E0723 14:05:54.511141    7671 cacher.go:428] unexpected ListAndWatch error: storage/cacher.go:/roles: Failed to list *rbac.Role: unexpected EOF
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: E0723 14:05:54.533440    7671 cacher.go:428] unexpected ListAndWatch error: storage/cacher.go:/roles: Failed to list *rbac.Role: unexpected EOF
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: E0723 14:05:54.534109    7671 cacher.go:428] unexpected ListAndWatch error: storage/cacher.go:/rolebindings: Failed to list *rbac.RoleBinding: unexpected EOF
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: E0723 14:05:54.540444    7671 cacher.go:428] unexpected ListAndWatch error: storage/cacher.go:/clusterrolebindings: Failed to list *rbac.ClusterRoleBinding: unexpe
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: E0723 14:05:54.542457    7671 cacher.go:428] unexpected ListAndWatch error: storage/cacher.go:/clusterroles: Failed to list *rbac.ClusterRole: unexpected EOF
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: E0723 14:05:54.542831    7671 cacher.go:428] unexpected ListAndWatch error: storage/cacher.go:/rolebindings: Failed to list *rbac.RoleBinding: unexpected EOF
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: E0723 14:05:54.546456    7671 cacher.go:428] unexpected ListAndWatch error: storage/cacher.go:/priorityclasses: Failed to list *scheduling.PriorityClass: unexpecte
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: E0723 14:05:54.547402    7671 cacher.go:428] unexpected ListAndWatch error: storage/cacher.go:/clusterroles: Failed to list *rbac.ClusterRole: unexpected EOF
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: E0723 14:05:54.548006    7671 cacher.go:428] unexpected ListAndWatch error: storage/cacher.go:/clusterrolebindings: Failed to list *rbac.ClusterRoleBinding: unexpe
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: E0723 14:05:54.550136    7671 cacher.go:428] unexpected ListAndWatch error: storage/cacher.go:/priorityclasses: Failed to list *scheduling.PriorityClass: unexpecte
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: E0723 14:05:54.565130    7671 cacher.go:428] unexpected ListAndWatch error: storage/cacher.go:/storageclasses: Failed to list *storage.StorageClass: unexpected EOF
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: E0723 14:05:54.583924    7671 cacher.go:428] unexpected ListAndWatch error: storage/cacher.go:/csinodes: Failed to list *storage.CSINode: unexpected EOF
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: E0723 14:05:54.589101    7671 cacher.go:428] unexpected ListAndWatch error: storage/cacher.go:/storageclasses: Failed to list *storage.StorageClass: unexpected EOF
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: E0723 14:05:54.608962    7671 cacher.go:428] unexpected ListAndWatch error: storage/cacher.go:/csinodes: Failed to list *storage.CSINode: unexpected EOF
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: E0723 14:05:54.623022    7671 cacher.go:428] unexpected ListAndWatch error: storage/cacher.go:/deployments: Failed to list *apps.Deployment: unexpected EOF
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: E0723 14:05:54.640941    7671 cacher.go:428] unexpected ListAndWatch error: storage/cacher.go:/daemonsets: Failed to list *apps.DaemonSet: unexpected EOF
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: E0723 14:05:54.651861    7671 cacher.go:428] unexpected ListAndWatch error: storage/cacher.go:/replicasets: Failed to list *apps.ReplicaSet: unexpected EOF
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: E0723 14:05:54.710792    7671 cacher.go:428] unexpected ListAndWatch error: storage/cacher.go:/controllerrevisions: Failed to list *apps.ControllerRevision: unexpe
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: W0723 14:05:54.805938    7671 genericapiserver.go:409] Skipping API batch/v2alpha1 because it has no resources.
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: W0723 14:05:54.821906    7671 genericapiserver.go:409] Skipping API discovery.k8s.io/v1alpha1 because it has no resources.
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: W0723 14:05:54.871355    7671 genericapiserver.go:409] Skipping API node.k8s.io/v1alpha1 because it has no resources.
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: W0723 14:05:54.937809    7671 genericapiserver.go:409] Skipping API rbac.authorization.k8s.io/v1alpha1 because it has no resources.
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: W0723 14:05:54.946140    7671 genericapiserver.go:409] Skipping API scheduling.k8s.io/v1alpha1 because it has no resources.
Jul 23 14:05:54 iat-k3s-1 k3s[7671]: W0723 14:05:54.999300    7671 genericapiserver.go:409] Skipping API storage.k8s.io/v1alpha1 because it has no resources.

**Comment by brandond** [comment]
Did you back up the database while k3s was running? You might try your test again, but shut down k3s before dumping the database.

**Comment by travis-sobeck** [comment]
> Did you back up the database while k3s was running? You might try your test again, but shut down k3s before dumping the database.
@brandond 
Yes.  I can give it a try, but its not really a solution.  Daily backups are managed by the DB team and you can't know in advance a disaster is going to hit ...

**Comment by brandond** [comment]
I'm not sure specifically what went wrong during your test, but I'm curious if your results differ if you stop k3s first. There are some bits of the kine etcd/sql layer that I suspect are not transaction-wrapped and could cause dumps to save an intermediate state. The EOF errors you're getting make me suspect something else is going on though - did you take a look at the database logs?

**Comment by travis-sobeck** [comment]
After a lot of failures, I decided to review some of the switches on mysqldump.  When I added '--hex-blob' things started go better.  One test worked when I dumped it while running and re-imported it while it was running.  Need to do some addition tests tomorrow.

**Comment by brandond** [comment]
Interesting. the kine database is like 99% blob data so getting that dumped and restored correctly would definitely be important.

**Comment by travis-sobeck** [comment]
On a related note, unless I totally missed something, I didn't find any useful docs here https://rancher.com/docs/k3s/latest/en/ on things like starting/stopping the k3s service or what the proper steps for DR on k3s even are, I'm just guessing really.
The only reason I even care is I'd like to run the Rancher server on this, the the DR for rancher seems to be whatever the DR for k3s is (as that's where rancher stores everything).

**Comment by brandond** [comment]
You can just stop and start it via systemctl or openrc init script. If you have an external database, agents should continue to function as long as at least one server is available - there is no quorum requirement at the k3s level, since that is all abstracted out to the datastore. Note that containers are NOT stopped when k3s is stopped, so you can safely upgrade k3s without killing your workload.

**Comment by stefanvangastel** [comment]
@travis-sobeck did you manage to recover the same VM? So the same hostname? I'm having issues disaster recovering a VM with the same hostname. So;

1. Install k3s on server01 using remote MySQL datastore
1. Cluster is running great
1. Uninstall k3s on server01
1. Delete VM server01
1. Create new VM server01
1. Install k3s as in step 1
1. TLS handshake errors

**Comment by travis-sobeck** [comment]
@stefanvangastel I was able to restore on prem and even in Azure with an ubuntu vm (same server name) and an Azure MySql DB.  I did have to add '?tls=true' to the very end of the K3S_DATASTORE_ENDPOINT part because the Azure DB had stronger connect requirements.  In any case it sounds like you're having issues even connecting.  I didn't have that issue, I just had bad data in the backup itself.  For the purpose of testing you may want to install the mysql client on server01 and sort out the connection issues there.

**Comment by stefanvangastel** [comment]
Well the connection is not the issue, k3s can connect to the database the second time, as it can the first time. I'll ask around the Slack channel. Thanks for your response!
