### ISSUE TITLE
kubectl exec times out on mysql dump

### ISSUE THREAD

**Issue by jrcichra** [rancher/k3s#2062]
**Environmental Info:**
K3s Version: 

`k3s version v1.18.6+k3s1 (6f56fa1d)`
Node(s) CPU architecture, OS, and Version: 

`Linux oracle01 5.4.0-1021-oracle #21-Ubuntu SMP Fri Jul 10 06:33:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
Cluster Configuration:

1 master 1 worker, only specified docker at install. It's on two Oracle Cloud instances but I've worked out the IPtable rules.
```
oracle01   Ready    master   2d19h   v1.18.6+k3s1
oracle02   Ready    <none>   2d16h   v1.18.6+k3s1
```

**Describe the bug:**

Trying to take a database backup by execing into a mariadb container times out with no explanation (rc=0 and no stderr)
```
justin@justinovh:/tmp$ time /usr/local/bin/kubectl exec -n mariadb mariadb-master-0 -- sh -c 'mysqldump --all-databases -uroot -ppassword'> /tmp/backup.sql

real	0m27.890s
user	0m0.977s
sys	0m1.181s
justin@justinovh:/tmp$
```

The file hovers around ~70MB when the actual full DB backup is 1.5 gigs. Something is silently timing out.
Manually execing into the pod and keeping a session alive avoids this problem. I've tried with the --tty and --stdin flags with no difference.

**Steps To Reproduce:**

- Installed K3s (w/ docker as the engine):
- Installed the latest mariadb bitnami helm chart with just a single master
Tried to dump data through kubectl exec back to the calling machine. 

**Expected behavior:**

It returns 0 when I have the full dump or non-zero if something bad happened.

**Actual behavior:**

Times out and I have no idea if something went wrong beyond file size / time.

**Additional context / logs:**

**Comment by brandond** [comment]
There is no intrinsic timeout on the exec commands. Issues like this are usually related to a firewall or load-balancer between your kubectl client and the server closing the connection because it looks idle due to no data being passed for an extended period of time.

**Comment by jrcichra** [comment]
Thanks. I'm not sure what is causing it, but I'm working around it by using `mysqldump` installed on the machine I want to directly dump to, and going through the NodePort of the service. That seems to be working. Thanks for the help!
