### ISSUE TITLE
Backport #2073 to release branches

### ISSUE THREAD

**Issue by brandond** [rancher/k3s#2078]
**Environmental Info:**
K3s Version: 1.18 / 1.17 / 1.16

Node(s) CPU architecture, OS, and Version: 
n/a

Cluster Configuration:
n/a

**Describe the bug:**
Future builds of the release-1.x branches on arm will fail for the same reason that master builds started failing - see #2076. We should backport some version of rancher/k3s#2073 to the release branches so that we're not stuck trying to resolve this issue next time we need to pull in an upstream release of k/k. 

Potential questions to answer:
* Should we update alpine on the release branches?
* Should we update golang on the release branches?
* What version of sqlite should we use on the release branches?
  The [initial checkin](https://github.com/rancher/k3s/blob/9bb7c27c62c9a0a04ffa99cf9bc78a0985cea1a8/Dockerfile.dapper#L7) of Dockerfile.dapper used alpine 3.8 with sqlite from edge, and we've never changed the pull from edge, despite the fact that we've moved to newer versions of Alpine that include whatever sqlite updates @ibuildthecloud needed to get from edge at that point in time. Do we want to pin a specific version of sqlite, or just use whatever version is available in the alpine release we pick?

**Steps To Reproduce:**
- Build k3s

**Expected behavior:**
k3s should build on arm

**Actual behavior:**
k3s will fail to build on arm

**Additional context / logs:**
n/a

**Comment by davidnuzik** [comment]
Refer to https://github.com/rancher/k3s/issues/2113. QA has validated the patches via this issue.
