### ISSUE TITLE
 prometheus-adaptor not working: Error: configmaps "extension-apiserver-authentication" not found

### ISSUE THREAD

**Issue by dmarkey** [rancher/k3s#208]
**Describe the bug**

prometheus-adaptor cannot be deployed..

I0310 14:11:26.124010       1 adapter.go:91] successfully using in-cluster auth
W0310 14:11:26.502692       1 authentication.go:245] Unable to get configmap/extension-apiserver-authentication in kube-system.  Usually fixed by 'kubectl create rolebinding -n kube-system ROLE_NAME --role=extension-apiserver-authentication-reader --serviceaccount=YOUR_NS:YOUR_SA'

**To Reproduce**
Try to deploy prometheus-adaptor

**Expected behavior**
That it deploys correctly

**Additional context**
In a greater attempt to deploy kube-prometheus.

also:
kubectl get cm -n kube-system extension-apiserver-authentication 
Error from server (NotFound): configmaps "extension-apiserver-authentication" not found

**Comment by reegnz** [comment]
Related: #252

**Comment by csreegn** [comment]
Git fixed with #252 IMHO.

**Comment by dmarkey** [comment]
I believe this is fixed.
