### ISSUE TITLE
Update To Go 1.15 (follow k/k upsteam)

### ISSUE THREAD

**Issue by warmchang** [rancher/k3s#2086]
Kubernetes 1.19 will be built using go1.15, the plan/tracker:
https://groups.google.com/g/kubernetes-dev/c/uN-hX5zUMFA
https://github.com/kubernetes/release/issues/1421

Currently go1.15rc1, 1.15.0 within a month.

/milestones v1.19

**Comment by warmchang** [comment]
:smile: It's time to go: https://github.com/golang/go/releases/tag/go1.15

**Comment by erikwilson** [comment]
Thanks for the issue & PR @warmchang ! This was updated as part of #2098 & will be tested with #2020
