### ISSUE TITLE
Access K8S FeatureGates for Kube-Proxy

### ISSUE THREAD

**Issue by carpenike** [rancher/k3s#2090]
**Environmental Info:**
K3s Version: v1.18.6+k3s1 (6f56fa1d)

Node(s) CPU architecture, OS, and Version: Linux h2-0 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 master, 4 workers

**Describe the bug:**
There's an upstream bug in Kubernetes where ExternalIPs on services with `type: LoadBalancer` will not honor the `externalTrafficPolicy: Local` setting. See here:

https://github.com/kubernetes/kubernetes/issues/91374

**Steps To Reproduce:**

Deploy a service and set the service `type=LoadBalancer`, add an `ExternalIPs: []`, set `externalTrafficPolicy=Local`. SNAT is persisted to the backend services.

Per this comment: https://github.com/kubernetes/kubernetes/issues/91374#issuecomment-635708873, the fix should be to leverage a featuregate in K8S v1.18:

```
featureGates:
  ExternalPolicyForExternalIP: true
```

I do not believe there's a featuregate option in k3s, correct?

- Installed K3s: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by brandond** [comment]
I believe you should be able to just pass through the feature-gates like any other kubelet arg:
`--kubelet-arg=feature-gates=ExternalPolicyForExternalIP=true`

Note that you will need to do this on every node (both servers and agents)

**Comment by carpenike** [comment]
Aha! It worked! I had only tried that on the master node. Got it deployed to all nodes now and it works great!!!

Thank you!
