### ISSUE TITLE
compressed images tarball support

### ISSUE THREAD

**Issue by dweomer** [rancher/k3s#2145]
**Is your feature request related to a problem? Please describe.**
We currently support the `/var/lib/rancher/k3s/agent/images` drop-in directory for pre-loading images. This is of key importance to supporting air-gapped installations where tarballs can be quite large and in the case of RKE2 must be compressed to be uploaded as a release artifact (otherwise we will exceed the 2GB upload limit for individual files to GH releases). As currying such large, uncompressed tarballs is less-than-ideal, it would be handy if k3s/rke2 could detect and decompress tarballs in the agent images drop-in directory.

**Describe the solution you'd like**
On start-up, prior to spinning up any subprocesses and therefore prior to loading images into containerd, attempt to decompress tarballs in-place. This would amount to a one-time cost per drop-in tarball at start-up.

**Describe alternatives you've considered**
Currying uncompressed tarballs and/or decompressing as part of the drop-in installation process.

**Additional context**
We should support the most common compression algorithms:
- bzip2
- gzip
- lz4

We should also log at INFO level every file encountered in the images drop-in directory and indicate whether they will be skipped or processed.

Additionally, when processing files we should not assume that we own anything we encounter. This means that we may need to setup a k3s-local data directory for recording the hashes of tarballs we have successfully processed (to prevent re-processing at every start).

**Comment by woa7** [comment]
@fkautz it would be great if also add support for zstr or least xz for maximum compression

**Comment by woa7** [comment]
maybe with 
https://godoc.org/github.com/DataDog/zstd
or 
https://godoc.org/github.com/klauspost/compress/zstd

**Comment by rancher-max** [comment]
#### Validated using commitid `077bacc9fcbfd3e7713f44d7fa4104d2b0a542b2`

- 4 types working: `tar`, `tar.gz`, `tar.bz2`, `tar.lz4`
- Images are shown properly when executing `sudo k3s crictl images`:
```
$ sudo ls /var/lib/rancher/k3s/agent/images/
alpine.tar.lz4	busybox.tar.gz	multiport.tar  ubuntu.tar.bz2

$ sudo k3s crictl images
IMAGE                                      TAG                 IMAGE ID            SIZE
docker.io/library/alpine                   latest              a24bb4013296f       5.85MB
docker.io/library/busybox                  latest              6858809bf669c       1.45MB
docker.io/library/ubuntu                   latest              4e2eef94cd6b9       76.3MB
docker.io/maxross/multiport                testing             5e3c24369c24c       366MB
...
```
- Confirmed there are ImageCreate and ImageUpdate events in the containerd.log file to extracting these images
- The images don't appear to add multiple times upon stopping and restarting k3s or re-running install scripts
- @dweomer I don't see any logs mentioning every file encountered. Also I'm not sure we created a k3s-local-data dir at all for this. Are these both still required as part of this issue?

**Comment by dweomer** [comment]
@rancher-max no, consider those possible future enhancements. If the base functionality works that's good enough.
