### ISSUE TITLE
javascript portForward generates Unexpected server response: 401 on websocket

### ISSUE THREAD

**Issue by si458** [rancher/k3s#2147]
**Environmental Info:**
K3s Version: k3s version v1.18.6+k3s1 (6f56fa1d)

Node(s) CPU architecture, OS, and Version:
k3OS 0.11.0 install
Linux kubernetes 5.4.0-37-generic #41 SMP Fri Jun 19 23:11:47 UTC 2020 x86_64 GNU/Linux

Cluster Configuration: 1 master, default config

**Describe the bug:**
unable to port-forward using nodejs, i just keep getting a 401 error, only happens with k3s
[listed in the javascript library issues here](https://github.com/kubernetes-client/javascript/issues/488)

**Steps To Reproduce:**
1. create default k3os or k3s on a ubuntu system
2. setup basic [kubenav in kubernetes (NOT THE APP)](https://github.com/kubenav/kubenav/blob/master/utils/kubernetes/README.md) for management
3. try to forward the port using javascript code and goto localhost:14122, just keep getting a websocket 401 error
4. use kubectl port-forward and have no issues at all?

- Installed K3s: 

**Expected behavior:** to be able to port-forward the ports

**Actual behavior:** getting a random 401 websocket error?

**Additional context / logs:**

**Comment by brandond** [comment]
Is the code from the issue you linked to the same code you're running to reproduce this issue?

Off the top of my head I can't think of anything unusual that k3s is doing that would prevent any standard kubernetes client from working normally, when pointed at the k3s kubectl.conf.

You mentioned that it works with minikube - what version of that were you using?

**Comment by si458** [comment]
Hi

Yes it's exactly the same few lines of code, no difference

Regards

Simon

**Comment by si458** [comment]
turns out the was a WS issue which was fixed upstream and the library hasnt updated it yet 
https://github.com/kubernetes-client/javascript/issues/488 👍
