### ISSUE TITLE
k3s-agent does not pick the value in `--private-registry`

### ISSUE THREAD

**Issue by ttt43ttt** [rancher/k3s#2156]
**Environmental Info:**
K3s Version: 
k3s version v1.18.8+k3s1 (6b595318)

Node(s) CPU architecture, OS, and Version: 
Linux k8s-worker-01 5.4.0-31-generic #35-Ubuntu SMP Thu May 7 20:20:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 master, 1 worker

**Describe the bug:**
`k3s crictl` cannot pull image from private registry.

**Steps To Reproduce:**
- Installed K3s using the default arguments.
- On the worker node, update the `/etc/rancher/k3s/registries.yaml` as described in [the doc](https://rancher.com/docs/k3s/latest/en/installation/private-registry/).
```
mirrors:
  registry.cn-shanghai.aliyuncs.com:
    endpoint:
      - 'https://registry.cn-shanghai.aliyuncs.com'
configs:
  'registry.cn-shanghai.aliyuncs.com':
    auth:
      username: myusername
      password: mypassword
```
- Restart the k3s-agent service.
- `k3s crictl pull` image from the private registry.

**Expected behavior:**
The image can be pulled.

**Actual behavior:**
The private registry config did not take effect. The content in file `/var/lib/rancher/k3s/agent/etc/containerd/config.toml` was not changed (no private registry info).

```
$ sudo cat /var/lib/rancher/k3s/agent/etc/containerd/config.toml

[plugins.opt]
  path = "/var/lib/rancher/k3s/agent/containerd"

[plugins.cri]
  stream_server_address = "127.0.0.1"
  stream_server_port = "10010"
  enable_selinux = false
  sandbox_image = "docker.io/rancher/pause:3.1"

[plugins.cri.cni]
  bin_dir = "/var/lib/rancher/k3s/data/19bb6a9xxxxxxc208fded1/bin"
  conf_dir = "/var/lib/rancher/k3s/agent/etc/cni/net.d"

[plugins.cri.containerd.runtimes.runc]
  runtime_type = "io.containerd.runc.v2"
```

```
$ sudo crictl --debug pull registry.cn-shanghai.aliyuncs.com/linkgo/frp-agent

DEBU[2020-08-24T11:33:54.739831704+08:00] PullImageRequest: &PullImageRequest{Image:&ImageSpec{Image:registry.cn-shanghai.aliyuncs.com/linkgo/frp-agent,},Auth:nil,SandboxConfig:nil,}
DEBU[2020-08-24T11:33:54.827985167+08:00] PullImageResponse: nil
FATA[2020-08-24T11:33:54.828051498+08:00] pulling image failed: rpc error: code = Unknown desc = failed to pull and unpack image "registry.cn-shanghai.aliyuncs.com/linkgo/frp-agent:latest": failed to resolve reference "registry.cn-shanghai.aliyuncs.com/linkgo/frp-agent:latest": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

**Additional context / logs:**
On the master node, this works after restarting the k3s service.

**My Current Workaround:**
Modify/set content in `/var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl`. Then restart the k3s-agent service.
My `config.toml.tmpl` looks like:
```
[plugins.opt]
  path = "{{ .NodeConfig.Containerd.Opt }}"

[plugins.cri]
  stream_server_address = "127.0.0.1"
  stream_server_port = "10010"
  enable_selinux = {{ .SELinuxEnabled }}

{{- if .IsRunningInUserNS }}
  disable_cgroup = true
  disable_apparmor = true
  restrict_oom_score_adj = true
{{end}}

{{- if .NodeConfig.AgentConfig.PauseImage }}
  sandbox_image = "{{ .NodeConfig.AgentConfig.PauseImage }}"
{{end}}

{{- if not .NodeConfig.NoFlannel }}
[plugins.cri.cni]
  bin_dir = "{{ .NodeConfig.AgentConfig.CNIBinDir }}"
  conf_dir = "{{ .NodeConfig.AgentConfig.CNIConfDir }}"
{{end}}

[plugins.cri.containerd.runtimes.runc]
  runtime_type = "io.containerd.runc.v2"

[plugins.cri.registry.mirrors]
[plugins.cri.registry.mirrors."registry.cn-shanghai.aliyuncs.com"]
endpoint = ["https://registry.cn-shanghai.aliyuncs.com"]

[plugins.cri.registry.configs."registry.cn-shanghai.aliyuncs.com".auth]
username = "yourusername"
password = "yourpassword"
```
See template format in https://github.com/rancher/k3s/blob/master/pkg/agent/templates/templates.go#L16

**Comment by brandond** [comment]
Did you place the file and restart k3s on both nodes? It is considered local configuration for each node, so only changing it on the server will have no effect on the agent.

**Comment by ttt43ttt** [comment]
> Did you place the file and restart k3s on both nodes? It is considered local configuration for each node, so only changing it on the server will have no effect on the agent.

I placed the file on the worker node only as I only need to fetch the images from the agent node.
On another k3s server, I tried to place the file on the server. It could work.

**Comment by brandond** [comment]
It's probably best to configure it on all of them, just to avoid confusion.

It's odd that you got it to work by configuring the template - can you provide the content of both registries.yaml, and the resulting `/var/lib/rancher/k3s/agent/etc/containerd/config.toml`, before and after your modifications? You should be able to configure auth [as described here](https://rancher.com/docs/k3s/latest/en/installation/private-registry/#without-tls), without customizing the template.

**Comment by ttt43ttt** [comment]
> It's probably best to configure it on all of them, just to avoid confusion.
> 
> It's odd that you got it to work by changing the template - can you provide the content of both registries.yaml, and the resulting `/var/lib/rancher/k3s/agent/etc/containerd/config.toml`, before and after your modifications? You should be able to configure auth [as described here](https://rancher.com/docs/k3s/latest/en/installation/private-registry/#without-tls), without customizing the template.

I added the content of `registries.yaml` to the issue. The resulting `/var/lib/rancher/k3s/agent/etc/containerd/config.toml` was same before/after changing the registries.yaml & restart k3s-agent.

**Comment by brandond** [comment]
Do you see any errors in the k3s logs? I'm not aware of any open issues that would prevent it from loading the registry configuration.

**Comment by ttt43ttt** [comment]
The `/etc/rancher/k3s/registries.yaml` works now!

After looking at k3s-agent log, I can see the logs "Using registry config file at /etc/rancher/k3s/registries.yaml" and no error. It tried to parse that file, but didn't find any entries (registries).

Things started to work after I delete everything in the `registries.yaml` and re-input the content. I think there may be some format issues or invisible characters in the original file.

Thanks for the quick response.
