### ISSUE TITLE
problem with resolving certain DNS zones

### ISSUE THREAD

**Issue by mimeie** [rancher/k3s#2157]
**Environmental Info:**
K3s Version: 
k3s version v1.18.6+k3s1 (6f56fa1d)

Node(s) CPU architecture, OS, and Version: 
Linux jmaster1 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 master, 2 workers. integrated also in rancher

**Describe the bug:**
when a dns resolve inside a pod is made, a certain zone is only resolved successfully in about 70% of the cases.

**Steps To Reproduce:**
To demonstrate it I've used busybox. But it is the same behaviour in services I've programmed myself.
I've made nslookups on and on, suddenly there is no answer anymore. then a few moments later it is working again.
![image](https://user-images.githubusercontent.com/41549872/91028205-6d368e80-e5fd-11ea-93e6-001e07595b62.png)

other zones are working fine. same for requests to the google dns, etc.

Important to know:
The DNS Server is a bind9 outside the cluster. resolves to this zone outside the cluster are working fine always, in windows, linux or even iOS

Zone Config:

> $TTL    604800
@       IN      SOA     prod.j1. admin.prod.j1. (
                              6         ; Serial
                         604800         ; Refresh
                          86400         ; Retry
                        2419200         ; Expire
                         604800 )       ; Negative Cache TTL
>; name servers - NS records
     IN      NS      jinfra3.mei.local.
     IN      NS      jinfra4.mei.local.

>; name servers - A records
jinfra3.mei.local.          IN      A       192.168.2.213
jinfra4.mei.local.          IN      A       192.168.2.214

>; 192.168.2.0/24 - A records
steuerungentfeuchter.prod.j1.        IN A 192.168.2.113
iobrokerdatacollector.prod.j1.        IN A 192.168.2.113
iobrokerdatawriter.prod.j1.        IN A 192.168.2.113

**Additional context / logs:**
I am not quite sure where to start. But I am happy to add any logs needed

**Comment by brandond** [comment]
Have you tried specifically targeting the upstream name servers to see if one of them is failing more than the other?
`dig hostname @nameserver`

**Comment by mimeie** [comment]
luckily I have no fails anymore. I will try to monitor it in the long run. let's see.
