### ISSUE TITLE
Support to configure the registry through environment variables when installing K3S

### ISSUE THREAD

**Issue by kingsd041** [rancher/k3s#2164]
**Is your feature request related to a problem? Please describe.**
I hope that when installing K3S, the private registry can be specified through environment variables

**Describe the solution you'd like**
Pulling images from docker hub in China is very slow, so I uploaded the K3S image to the Alibaba Cloud  image repository.
Then configure the private registry according to the K3S documentation:
```
# cat /etc/rancher/k3s/registries.yaml
mirrors:
  "docker.io":
    endpoint:
      - "https://registry.cn-hangzhou.aliyuncs.com"
      - "https://registry-1.docker.io"
```

After this configuration, I can quickly pull the K3S image from Alibaba Cloud  and start K3S

At this time, I cannot pull other images from dockerhub, such as:
```
# crictl pull busybox
FATA[2020-08-26T10:24:15.547077080+08:00] pulling image failed: rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/busybox:latest": failed to resolve reference "docker.io/library/busybox:latest": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

If I can specify the registry (not docker.io) through environment variables when I start K3S, I can use Alibaba Cloud registry and docker.io at the same time

**Comment by brandond** [comment]
Mirror configuration is potentially very complex, which is why we use a YAML file. Can you suggest how you might set it up using an environment variable? What would the variable contain, and how would it be used?

**Comment by kingsd041** [comment]
This may be caused by a [bug](https://github.com/containerd/cri/issues/1419) in containerd. If the version of containerd of k3s is upgraded to 1.3.4, it should be resolved.
