### ISSUE TITLE
Worker Nodes won't join the cluster

### ISSUE THREAD

**Issue by rroberts59110** [rancher/k3s#2168]
I am trying to install k3s on three pcs running CentOS 7. I have tried to carefully follow the k3s installation instructions. I set up a private registry. The registries.yaml file has been copied to /etc/rancher/k3s/ and the registry cert files are in the location pointed to by the registries.yaml file, /etc/pki/ca-trust/source/anchors/ and then installed the server with the following command:

curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.17.5%2Bk3s1 sh -s - --write-kubeconfig-mode 644

Then installed the agent on the worker nodes with this command:
 
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.17.5%2Bk3s1 K3S_URL=https://master:6443 K3S_TOKEN=K1041f02d676ba14e50157c207d5c955553d7909dfe3399848113efdb0183b3c16b::server:697165a1d698321d56827ac678d673be sh -

master is identified in the /etc/hosts file of each worker node, the K3S_TOKEN value is copied from /var/lib/rancher/k3s/server/node-token on the server.

All of the services install without error and systemctl status shows all of the services up and running but 'kubectl get nodes' from the master only shows the master node running.

'journalctl -u k3s-agent.service' shows many lines with this on the worker nodes:

Aug 26 18:16:07 worker0 k3s[23146]: time="2020-08-26T18:16:07.684043215-04:00" level=error msg="failed to get CA certs at https://127.0.0.1:39945/cacerts: Get https://127.0.0.1:39945/cacerts: read tcp 127.0.0.1:56418->127.0.0.1:39945: read: connection reset by peer"

At this point I don't know what to do. Any help would be appreciated.

**Comment by brandond** [comment]
Is 6443 open on the master? Can you successfully `curl -vks https://master:6443/` on the agents?

**Comment by rroberts59110** [comment]
I get this response on the master:
curl -vks localhost:6443/static/
* About to connect() to localhost port 6443 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 6443 (#0)
> GET /static/ HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:6443
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 400 Bad Request
< 
Client sent an HTTP request to an HTTPS server.
* Closing connection 0

but this response from the worker nodes:

[developer@worker0 ~]$ curl -vks https://master:6443/static/
* About to connect() to master port 6443 (#0)
*   Trying 172.16.101.10...
* No route to host
* Failed connect to master:6443; No route to host
* Closing connection 0
[developer@worker0 ~]$ 

And yes the ip is correct and I can ping the master successfully.
Firewall issue?

**Comment by brandond** [comment]
Can you show the ping results? Sure looks like a basic network issue.

**Comment by rroberts59110** [comment]
It was indeed a firewall issue. Upon opening the port 6443 in the master's firewall I can see all nodes in the cluster. Thanks for the help! This issue is solved.
