### ISSUE TITLE
[k3s-upgrade] [Question] What's k3s-upgrade license?

### ISSUE THREAD

**Issue by davidmateos** [rancher/k3s#2173]
Hi there,
[k3s-upgrade](https://github.com/rancher/k3s-upgrade) repo doesn't include a license info. What license is k3s-upgrade repo under?

**Comment by davidnuzik** [comment]
The rancher/k3s-upgrade repo has the same license as rancher/k3s. We will fix the license in rancher/k3s-upgrade.

**Comment by davidnuzik** [comment]
This has been fixed in rancher/k3s-upgrade. Thanks for reporting!
