### ISSUE TITLE
"FATA [0000] permission denied" error on BeagleBone Black

### ISSUE THREAD

**Issue by acharaj** [rancher/k3s#2174]
Hi, 

I'm trying to run k3s worker node on a BeagleBone Black device with the following command

/var/volatile/tmp # ./k3s-armhf agent --data-dir /initlo/data/rancher/k3s  --server https://192.168.1.3:6443 --token <TOKEN>

When I run the above command, I see "FATA [0000] permission denied"  if I run it as root and "FATA [0017] permission denied" if I run it as a normal user.

Any help regarding this will be much appreciated. Inside the data directory, /bin and /etc folders are populated by the binary with a lot of stuff inside these directories.

**Comment by brandond** [comment]
Can you provide complete log output? It's hard to tell what's going on from just the two errors.

**Comment by acharaj** [comment]
The issue is resolved if I remount /initlo/data partition with exec. It seems k3s stores under data /bin and /etc directory and probably, it tries to run some executables from /bin . After remounting the partition with exec, the error goes away. I'm closing this issue.
