### ISSUE TITLE
"failed to find memory cgroup" error while running a worker node on BeagleBone Black

### ISSUE THREAD

**Issue by acharaj** [rancher/k3s#2175]
Hi,

I'm trying to run a worker node on BeagleBone Black device running 
Linux PX-Red-BBB-AC-05-BE 4.19.50-rt22-pxred rancher/k3s#1 SMP Tue Jul 28 18:38:14 UTC 2020

The command I use is the following
./k3s-armhf agent --data-dir /initlo/data/jagdish/rancher/k3s --server https://192.168.1.3:6443 --token <token>
where <token> is replaced with the real token.

The command fails with the following
it fails with "failed to find memory cgroup, you may need to add "cgroup_memory=1 cgroup_enable=memory" to your linux cmdline  (/boot/cmdline.txt on a Raspberry Pi)". 

Any help would be appreciated. The issue seems to be related to the use of cgroups for running containers.

**Comment by brandond** [comment]
Have you tried adding the listed args to your kernel boot args, and restarting? If you have already done this and are still getting this error, your kernel likely does not support the required cgroups.

**Comment by acharaj** [comment]
It seems the linux I'm running is built without container support. I tried to build the image this time with Yocto and it gives
/run/jagdish # ./k3s agent --server https://192.168.1.3:6443 --token <token> --data-dir /run/jagdish/
INFO[0000] Preparing data dir /run/jagdish/data/19bb6a9b46ad0013de084cf1e0feb7927ff9e4e06624685ff87f003c208fded1 
INFO[2020-08-29T06:52:39.809329171-04:00] Starting k3s agent v1.18.8+k3s1 (6b595318)   
FATA[2020-08-29T06:52:39.921653301-04:00] open /proc/self/cgroup: no such file or directory

It seems I need to build the image with Yocto by adding the layer that makes necessary config changes to add container support. I'm closing the issue because it seems the problem is my linux kernel and not related to the k3s.
