### ISSUE TITLE
k3s install.sh doesn't respect K3S_TOKEN_FILE env variable

### ISSUE THREAD

**Issue by ericleu** [rancher/k3s#2179]
**Environmental Info:**
K3s Version: 

```
vagrant@master:~$ k3s -v
k3s version v1.18.2+k3s1 (698e444a)
```
Node(s) CPU architecture, OS, and Version: 

```
vagrant@master:~$ uname -a
Linux master 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
Cluster Configuration:

1 master 2 workers

**Describe the bug:**

**Steps To Reproduce:**

- Installed K3s: 

My setup is using vagrant.
step 1: install master
```
 curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC=\"--flannel-iface enp0s8\" sh -
```
step 2: retrieve token (for agent registration); the token is stored in a shared folder where both master and worker have access to
```
sudo cat /var/lib/rancher/k3s/server/node-token  > /shared/TOKEN
```
step 3: Install and register worker node/agent
```
curl -sfL https://get.k3s.io | K3S_URL=\"https://master:6443\" K3S_TOKEN_FILE=\"/shared/TOKEN\" INSTALL_K3S_EXEC=\"--flannel-iface enp0s8\" sh -
```
**Expected behavior:**

a worker node is installed and registered with master successfully

**Actual behavior:**

```
    node1: Running: inline script
    node1: [ERROR]  Defaulted k3s exec command to 'agent' because K3S_URL is defined, but K3S_TOKEN or K3S_CLUSTER_SECRET is not defined.
#<Thread:0x00007f715cc357b0@/usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/batch_action.rb:71 run> terminated with exception (report_on_exception is true):
```
**Additional context / logs:**

According to `k3s agent`, it supports `K3S_TOKEN_FILE`; however, the `install.sh` doesn't support the pass through.
The current work around is to use `K3S_TOKEN` only
This command will allow me to continue (notice the use of `K3S_TOKEN` instead):
```
curl -sfL https://get.k3s.io | K3S_URL=\"https://master:6443\" K3S_TOKEN=\"$(cat /shared/TOKEN)\" INSTALL_K3S_EXEC=\"--flannel-iface enp0s8\" sh -
```
I already opened a PR to address this: https://github.com/rancher/k3s/pull/1847

Thanks for the great work you guys are doing!

**Comment by davidnuzik** [comment]
Thanks for reporting! At first glance it looks like this is indeed a bug. I see in the docs we indicate that `K3S_TOKEN_FILE` is a valid option but I agree I don't see this in install.sh. (See docs https://rancher.com/docs/k3s/latest/en/installation/install-options/agent-config/#cluster-options).

I think here is where we check to ensure you specify K3S_TOKEN or K3S_CLUSTER_SECRET but looks like we fail to do a check for K3S_TOKEN_FILE https://github.com/rancher/k3s/blob/master/install.sh#L166

We'll look into this when able. Right now we are working on getting v1.19 out. I have triaged the issue.

**Comment by rancher-max** [comment]
#### Validated with the latest get.k3s.io 

- This now respects the K3S_TOKEN_FILE argument
- If not supplying the file or token, receive the following correct error:
`[ERROR]  Defaulted k3s exec command to 'agent' because K3S_URL is defined, but K3S_TOKEN, K3S_TOKEN_FILE or K3S_CLUSTER_SECRET is not defined.`
