### ISSUE TITLE
How to make registries.yaml effect after k3s have startup

### ISSUE THREAD

**Issue by jingsam** [rancher/k3s#2187]
Hi, I have a 4 nodes k3s cluster that is running. Now I want set a private registry to the cluster. So I place `registries.yaml` in `/etc/ranchor/k3s` in every node. My question is what can i do to make containerd respect this setting.

I have tried `systemctl restart k3s-agent` on each node. But the master does not have `k3s-agent`. Is it appropriate use `systemctl restart k3s` on master node ?

**Environmental Info:**
K3s Version:  v1.18.8+k3s1

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by brandond** [comment]
> I have tried `systemctl restart k3s-agent` on each node. But the master does not have `k3s-agent`. Is it appropriate use `systemctl restart k3s` on master node ?

Yes. Note that restarting k3s (server or agent) does not restart the pods.
