### ISSUE TITLE
'minikube ip' equivalent on k3s

### ISSUE THREAD

**Issue by mehdihadeli** [rancher/k3s#2188]
Hi,
Is there any command to get cluster IP like minikube command `minikube ip` ?

**Comment by brandond** [comment]
What cluster IP are you looking for? The kubernetes api is available on any of the k3s servers:
```
kubectl get nodes -o wide -l node-role.kubernetes.io/master=true
```

**Comment by mehdihadeli** [comment]
@brandond Yes, we can find it with `kubectl get nodes`, I'm looking for a shorter syntax like `minikube IP` to get the IP of the node but I think it doesn't exist in k3s. but it's ok to get IP of node with `kubectl get nodes`

**Comment by brandond** [comment]
Other than the startup commands (`k3s server` and `k3s agent`) k3s does not have any CLI of its own - you should just use upstream tools like kubectl.

**Comment by mehdihadeli** [comment]
@brandond ok thanks.
