### ISSUE TITLE
Registry mirror fallback not working when using a registry endpoint list

### ISSUE THREAD

**Issue by niusmallnan** [rancher/k3s#2191]
**Environmental Info:**
K3s Version: v1.1.8/v1.17/v1.16

**Describe the bug:**

In some scenarios, registry mirror fallback not working when using a registry endpoint list. This means that the behavior of k3s containerd and docker is very different. 
k3s mainly uses the containerd v1.3.3. If we configure multiple endpoints(A,B) for a registry mirror, the endpoint B will only retry if endpoint A returns 404. However, many public registry mirrors cannot return 404 according to the specification if the pulled image does not exist.

Related PR: https://github.com/containerd/containerd/pull/4007
We need to bump containerd to v1.3.4+.

**Comment by brandond** [comment]
The 1.19 release (and current master branch) use containerd 1.4.0. I don't believe we have any plans to backport containerd updates to the older release branches.

**Comment by davidnuzik** [comment]
This should be effectively fixed in upcoming v1.19.1+k3s1 release which we are planning to get out today or tomorrow (although the date could slip). I'd like to close this out - if there are questions/concerns please feel free to comment or the issue can be reopened.
