### ISSUE TITLE
Error: open /proc/self/cgroup: no such file or directory

### ISSUE THREAD

**Issue by acharaj** [rancher/k3s#2216]
Hi,

Running k3s on a linux, I get the following error
/var/volatile/tmp # ./k3s agent --server https://192.168.1.9:6443 --token <TOKEN>
INFO[0000] Preparing data dir /var/lib/rancher/k3s/data/19bb6a9b46ad0013de084cf1e0feb7927ff9e4e06624685ff87f003c208fded1 
INFO[2020-09-05T02:27:52.975048835-04:00] Starting k3s agent v1.18.8+k3s1 (6b595318)   
FATA[2020-09-05T02:27:53.031033091-04:00] open /proc/self/cgroup: no such file or directory

Any suggestion to solve this issue?

**Comment by dweomer** [comment]
@acharaj without more detail it is hard to know what is preventing k3s from running in your setup. a not exhaustive list of things to look for and/or try:
- if you are running on arm/arm64 make sure that cgroups are supported by your kernel and [properly configured](https://opensource.com/article/20/6/kubernetes-raspberry-pi#enable-cgroups-limit-support)
- make sure that you are not running in a sandboxed environment that does not support cgroups inside the sandbox
- if you are running on a system that supports cgroupsv2 (fedora 31 or higher) you will need to enable v1 support by booting with the `systemd.unified_cgroup_hierarchy=0` kernel parameter

Failing all of that, please review the bug report template and supply detail asked for there (and/or any other relevant detail that you can provided about your setup).

**Comment by acharaj** [comment]
The issue was due to missing kernel flags and cgroups not mounted in the system. It is resolved.
