### ISSUE TITLE
Upgrade to kubernetes v1.19.1

### ISSUE THREAD

**Issue by davidnuzik** [rancher/k3s#2217]
Related: v1.19.0 bump: https://github.com/rancher/k3s/issues/2020
Related upstream v1.19.1 release issue: https://github.com/kubernetes/sig-release/issues/1220

Upstream to release v1.19.1 9/9/2020 according to https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md#119

We will bump to this version, then start testing. Due to the testing effort required and the short time difference between upstream v1.19.0 release and v1.19.1 release, we plan to release v1.19.1 instead of v1.19.0.

**QA will need to run cncf conformance and get v1.19.x certified.**

**Comment by ShylajaDevadiga** [comment]
Validated k3s v1.19.1-rc1+k3s1 and k3s v1.19.1-rc2+k3s1 as part of release testing. We are good to proceed to release v1.19.1+k3s1
