### ISSUE TITLE
[Documentation] --selinux flag

### ISSUE THREAD

**Issue by davidnuzik** [rancher/k3s#2247]
We need to document the change from `--disable-selinux` to `--selinux` in [this area](https://rancher.com/docs/k3s/latest/en/advanced/#experimental-selinux-support)

Users will now need to implicitly specify the `--selinux` flag for both servers and agents if they wish to leverage experimental SELinux.

**Comment by catherineluse** [comment]
Closing this issue because https://github.com/rancher/docs/pull/2686 was merged
