### ISSUE TITLE
K3s with a mysql back end and rancherdb producing endless duplicate primary key errors.

### ISSUE THREAD

**Issue by jgerry2002** [rancher/k3s#2252]
I'm seeing an issue with K3s and rancher backed by a mysql database. I'm not sure if this is a K3s issue or a RancherDB issue, so I am posting here.

**Environmental Info:**
K3s Version: k3s version v1.18.8+k3s1 (6b595318)

Node(s) CPU architecture, OS, and Version: 
Rhel 7 x64, 3.10.0-1127.18.2.el7.x86_64, 2vpu/8gb of ram.

Cluster Configuration:
2 K3s master/workers with proxysql front end distributed to a 3 node Galera MySQL cluster with either Percona Xtradb (5.7) or MariaDB 10.4.14 on the nodes. ProxySQL has a simple configuration that pins read/write to a single hostgroup. The write hostgroup only has a single allowable write node. Rancherdb created with defaults in either database server type.

**Steps To Reproduce:**
Create rancherdb, install rancher is specified in the how to documents.

Results from Proxysql back end and on MySQL server logs:

I'm getting a non stop flood of errors like:
`2020-09-14 21:32:58 MySQL_Session.cpp:3919:handler(): [WARNING] Error during query on (9,mysql-001.local,3306,578): 1062, Duplicate entry '327788' for key 'PRIMARY'`

This usually relates to the fact that some mechanism is attempting to repeatedly attempt endless blind inserts vs an upsert. Its almost like K3s is treating inserts like a keystore vs an actual relational database.  

Perhaps missing some logic such as INSERT ... ON DUPLICATE KEY UPDATE or is there a configuration piece that I've overlooked?

**Comment by brandond** [comment]
This is probably a duplicate of #1311 - in my experience this is usually caused by a SQL datastore with high latency, such that the master compact queries run long and step on each other.

**Comment by jgerry2002** [comment]
This can be closed. I ended up going to etcd cluster as a backing keystore and it easier to maintain.
