### ISSUE TITLE
Error: failed to get CA certs at https://127.0.0.1:36829/cacerts

### ISSUE THREAD

**Issue by acharaj** [rancher/k3s#2261]
**Environmental Info:**
K3s Version: 

v1.18.8+k3s1

Node(s) CPU architecture, OS, and Version: 

Linux PX-Red-BBB-AC-05-BE 4.19.50-rt22-pxred #1 SMP Tue Sep 15 03:52:55 UTC 2020 armv7l GNU/Linux
Custom Linux built with Yocto

Cluster Configuration:

One master running on Ubuntu VM. See below the output of "uname -a" on the VM
Linux test-VirtualBox 5.4.0-47-generic #51~18.04.1-Ubuntu SMP Sat Sep 5 14:35:50 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Additional Info: The master node is behind a NAT with an ip address of 192.168.1.6 (VM with bridged adaptor to get the ip address in the local LAN behind NAT with my home router)

One worker node running on BeagleBone Black ARM device 32-bit (See below)
Linux PX-Red-BBB-AC-05-BE 4.19.50-rt22-pxred #1 SMP Tue Sep 15 03:52:55 UTC 2020 armv7l GNU/Linux
This worker node is also behind the NAT, having an ip address of 192.168.1.11

**Describe the bug:**

Master node is running smoothely (see below)
test@test-VirtualBox:~$ sudo kubectl get node
NAME                    STATUS     ROLES    AGE   VERSION
test-virtualbox         Ready      master   20d   v1.18.8+k3s1

However, my worker node never joins the master node. I run the following command on my worker node
/var/volatile/tmp # ./k3s-armhf --debug agent --server https://192.168.1.6:6443
--token K106551b864ddc9e388cbfba3cded437ac65182ebdf0ee75719436603e29a7c3be4::ser
ver:2e175fa39a8b70bc878fa2772a78d82b
DEBU[0000] Asset dir /var/lib/rancher/k3s/data/aa9b520cec21dfd41d6548e2474b93ad17760f68adec96f97bb60126194d8a11
DEBU[0000] Running /var/lib/rancher/k3s/data/aa9b520cec21dfd41d6548e2474b93ad17760f68adec96f97bb60126194d8a11/bin/k3s-agent [./k3s-armhf --debug agent --server https://192.168.1.6:6443 --token K106551b864ddc9e388cbfba3cded437ac65182ebdf0ee75719436603e29a7c3be4::server:2e175fa39a8b70bc878fa2772a78d82b]
INFO[2020-09-16T11:12:28.673398327-04:00] Starting k3s agent v1.18.8+k3s1 (6b595318)
WARN[2020-09-16T11:12:28.675194574-04:00] Failed to find cpuset cgroup, you may need to add "cgroup_enable=cpuset" to your linux cmdline (/boot/cmdline.txt on a Raspberry Pi)
INFO[2020-09-16T11:12:28.675452853-04:00] module overlay was already loaded
INFO[2020-09-16T11:12:28.675715840-04:00] module nf_conntrack was already loaded
WARN[2020-09-16T11:12:28.691405002-04:00] failed to start br_netfilter module
INFO[2020-09-16T11:12:28.695914618-04:00] Running load balancer 127.0.0.1:36829 -> [192.168.1.6:6443]
DEBU[2020-09-16T11:12:38.700189615-04:00] Dial error from load balancer: dial tcp 192.168.1.6:6443: i/o timeout
DEBU[2020-09-16T11:12:38.700698674-04:00] Incoming conn 127.0.0.1:49662, error dialing load balancer servers: context deadline exceeded
DEBU[2020-09-16T11:12:48.705832335-04:00] Dial error from load balancer: dial tcp 192.168.1.6:6443: i/o timeout
DEBU[2020-09-16T11:12:48.706334519-04:00] Incoming conn 127.0.0.1:49666, error dialing load balancer servers: context deadline exceeded
ERRO[2020-09-16T11:12:48.708357630-04:00] failed to get CA certs at https://127.0.0.1:36829/cacerts: Get https://127.0.0.1:36829/cacerts: read tcp 127.0.0.1:49666->127.0.0.1:36829: read: connection reset by peer

**Steps To Reproduce:**

- Installed K3s: on the master, I installed it through the script (using curl command) provided on the k3s website. No changes. Default settings. It is running on a Ubuntu VM running on x86 architecture.

- k3s on worker node: downloaded the k3s-armhf binary and transferred it to my embedded device, i.e., beaglebone black. Ran this binary with the above command.

**Expected behavior:**

The worker node should have joined the master node.

**Actual behavior:**

Instead we get the above errors.

**Additional context / logs:**

While running curl command on my worker node, I get the following error
 /var/volatile/tmp # curl -vvv https://www.google.com
*   Trying 172.217.168.36:443...
* TCP_NODELAY set
* Connected to www.google.com (172.217.168.36) port 443 (#0)
* error reading ca cert file /etc/ssl/certs/ca-certificates.crt (Error while reading file.)
* Closing connection 0
curl: (77) Problem with the SSL CA cert (path? access rights?)

**Comment by brandond** [comment]
It appears that the kernel on your device is missing several options. You will need to ensure that the required cgroups and modules are enabled in your custom kernel build.

```
WARN[2020-09-16T11:12:28.675194574-04:00] Failed to find cpuset cgroup, you may need to add "cgroup_enable=cpuset" to your linux cmdline (/boot/cmdline.txt on a Raspberry Pi)
INFO[2020-09-16T11:12:28.675452853-04:00] module overlay was already loaded
INFO[2020-09-16T11:12:28.675715840-04:00] module nf_conntrack was already loaded
WARN[2020-09-16T11:12:28.691405002-04:00] failed to start br_netfilter module
```

**Comment by acharaj** [comment]
I compile the kernel with cpuset and all nat flags. however, they are not enabled. 

Anyways, the above issue is not due to these kernel flags as, if my master and worker nodes are on a public network, my worker node is successfully listed at the master node with the state "Ready". however, when the two nodes are behind NAT and outside my enterprise network, they are not able to join each other and the worker node shows the errors above. see a bit further below the kernel flag warnings.

**Comment by brandond** [comment]
If you're putting the master behind NAT, you need to tell it what the NAT address is with the `--node-external-ip=<EXTERNAL-IP>` option. Otherwise the agents try to connect directly to its private IP address.

**Comment by acharaj** [comment]
@brandond are you talking for the case when the master/server is behind the NAT and worker/agent nodes are not behind the same NAT? In my case, both master and worker nodes are behind the same NAT. Do I still need --node-external-ip=<EXTERNAL-IP> flag?

**Comment by acharaj** [comment]
@brandond my master/server is started on a ubuntu VM with the k3s script using the command "curl -sfL https://get.k3s.io | sh -". When I see the service details with "systemctl sattus k3s", I see the following
k3s.service - Lightweight Kubernetes
   Loaded: loaded (/etc/systemd/system/k3s.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2020-09-16 11:53:12 CEST; 20h ago
     Docs: https://k3s.io
 Main PID: 586 (k3s-server)
    Tasks: 93
   CGroup: /system.slice/k3s.service
           ├─ 586 /usr/local/bin/k3s server --tls-san=192.168.1.6 --advertise-address=192.168.1.6
           ├─1594 containerd -c /var/lib/rancher/k3s/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.soc
           ├─2511 /var/lib/rancher/k3s/data/19bb6a9b46ad0013de084cf1e0feb7927ff9e4e06624685ff87f003c208fded1/bin/containerd
           ├─2512 /var/lib/rancher/k3s/data/19bb6a9b46ad0013de084cf1e0feb7927ff9e4e06624685ff87f003c208fded1/bin/containerd
           ├─2604 /pause
           ├─2626 /pause
           ├─2875 /metrics-server
           ├─2907 /var/lib/rancher/k3s/data/19bb6a9b46ad0013de084cf1e0feb7927ff9e4e06624685ff87f003c208fded1/bin/containerd
           ├─2977 local-path-provisioner start --config /etc/config/config.json
           ├─2996 /pause
           ├─3117 /var/lib/rancher/k3s/data/19bb6a9b46ad0013de084cf1e0feb7927ff9e4e06624685ff87f003c208fded1/bin/containerd
           ├─3165 /pause
           ├─3167 /bin/sh /usr/bin/entry
           ├─3326 /traefik --configfile=/config/traefik.toml
           ├─3373 /var/lib/rancher/k3s/data/19bb6a9b46ad0013de084cf1e0feb7927ff9e4e06624685ff87f003c208fded1/bin/containerd
           ├─3399 /bin/sh /usr/bin/entry
           ├─3442 /pause
           └─3510 /coredns -conf /etc/coredns/Corefile

Above, if you see, the k3s is started with --tls-san and --advertise-address options 
" /usr/local/bin/k3s server --tls-san=192.168.1.6 --advertise-address=192.168.1.6"

Should I change the ip address to external/public ip address in the above two flags as well?  Should I specify all three flags with external ip address?

**Comment by brandond** [comment]
Try just using node-external-ip.

**Comment by acharaj** [comment]
On the server, I stop the service with "systemctl stop k3s" and then, try to run the server manually with the command "sudo k3s server --node-external-ip=<ACTUAL_IP>" 
The server prints a lot of errors (like the ones below) and continues doing so.
ateful set
I0917 08:12:21.440733    4394 node_ipam_controller.go:94] Sending events to api server.
INFO[2020-09-17T08:12:21.844104420+02:00] Connecting to proxy                           url="wss://192.168.1.6:6443/v1-k3s/connect"
INFO[2020-09-17T08:12:21.844150826+02:00] Connecting to proxy                           url="wss://51.154.120.25:6443/v1-k3s/connect"
INFO[2020-09-17T08:12:21.846235644+02:00] Handling backend connection request [test-virtualbox] 
ERRO[2020-09-17T08:12:21.847385967+02:00] Failed to connect to proxy                    error="dial tcp 51.154.120.25:6443: connect: connection refused"
ERRO[2020-09-17T08:12:21.847437085+02:00] Remotedialer proxy error                      error="dial tcp 51.154.120.25:6443: connect: connection refused"
I0917 08:12:22.455267    4394 request.go:621] Throttling request took 1.015043874s, request: GET:https://127.0.0.1:6444/apis/events.k8s.io/v1beta1?timeout=32s
INFO[2020-09-17T08:12:26.847530002+02:00] Connecting to proxy                           url="wss://51.154.120.25:6443/v1-k3s/connect"
ERRO[2020-09-17T08:12:26.849409588+02:00] Failed to connect to proxy                    error="dial tcp 51.154.120.25:6443: connect: connection refused"
ERRO[2020-09-17T08:12:26.849425905+02:00] Remotedialer proxy error                      error="dial tcp 51.154.120.25:6443: connect: connection refused"

To test the curl command "curl -ks http://192.168.1.6:6443/static/charts/" I stop the above and restart the k3s service with systemctl. 
Below are the test results
/var/volatile/tmp # curl -vvv -ks http://192.168.1.6:6443/static/charts/
*   Trying 192.168.1.6:6443...
* TCP_NODELAY set
^C
/var/volatile/tmp # ping 192.168.1.6
PING 192.168.1.6 (192.168.1.6): 56 data bytes
64 bytes from 192.168.1.6: seq=0 ttl=64 time=0.906 ms
64 bytes from 192.168.1.6: seq=1 ttl=64 time=0.919 ms
^C
--- 192.168.1.6 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.906/0.912/0.919 ms
/var/volatile/tmp # ip route show
default via 192.168.1.1 dev eth0
default dev eth0 scope link  metric 99
169.254.0.0/16 dev eth0 scope link  metric 99
192.168.1.0/24 dev eth0 scope link  src 192.168.1.11
224.0.0.0/4 dev eth0 scope link

We see above that routing table is properly set at the agent/worker node. I can ping the master/server node but the curl command doesn't succeed.

**Comment by acharaj** [comment]
I also tried to run "telnet 192.168.1.6 6443" from my agent/worker node with ip address 192.168.1.11. telnet doesn't succeed. does it mean the port 6443 on the server/master is not open or my home router is blocking the traffic between these two machines (which are in the same local area network behind the NAT)?

**Comment by brandond** [comment]
If you can't curl or telnet to port 6443 then k3s isn't going to work either. Once you get that straightened out the agent should be able to connect to the server.
