### ISSUE TITLE
Mark v1.19.x as stable when we are happy with v1.19

### ISSUE THREAD

**Issue by davidnuzik** [rancher/k3s#2265]
Because v1.19 is a new milestone release and a new k8s minor release -- we have held back as marking this as [stable](https://github.com/rancher/k3s/blob/master/channel.yaml#L3) in the channel server. Normally, we mark releases as stable within one week.

Because stable to us means ready for production we will stand by, let v1.19.x bake for a bit and then when we are happy specify a v1.19.x release as stable.

**Comment by karimsa** [comment]
Hi, there! New to the project. How long do releases usually stay as latest until they reach stable? Is there a formal release cycle?

**Comment by davidnuzik** [comment]
Hello! We have an unwritten rule to wait 7 days before marking a new release [as stable](https://github.com/rancher/k3s/blob/master/channel.yaml#L3). This can vary occasionally, such as with our v1.19.1 release where introduced experimental features for embedded etcd and etcd snapshot and restore. I plan to document this publicly, but haven't had a chance to get to it yet.

We follow the upstream kubernetes release cycle closely. For example, [about once a month](https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md#upcoming-monthly-releases) they release new patches and we try to do the same.

**Comment by karimsa** [comment]
Where can I track what issues are open and blocking this version from hitting stable?

**Comment by davidnuzik** [comment]
We are mostly keeping a close eye on any etcd issues that get entered and need to wait until we get a couple other project releases out in about a week from today before we can have QA review these. You can [search](https://github.com/rancher/k3s/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%2Fetcd) for k3s issues with the `area/etcd` label which will show a few that we may look into at our earliest ability.

We are also keeping an eye out in other channels such as the rancher users slack for anything.

**Comment by karimsa** [comment]
Sounds good, thanks for the info!

**Comment by davidnuzik** [comment]
https://github.com/rancher/k3s/pull/2487

**Comment by davidnuzik** [comment]
Closing. v1.19.3+k3s2 is now stable!
I want to notify that etcd is not quite yet out of experimental -- nor is SELinux support.
So - we're marking it as stable because we feel good about K3s v1.19 but etcd and SELinux are still experimental in v1.19.3+k3s2.

Here's the plan (subject to change)
- v1.19.4+k3s2 release (slated for late November) moved etcd to certified (take it out of experimental)
- v1.19.4+k3s1 release (slated for 11/11) SELinux moves to certified (take it out of experimental)
