### ISSUE TITLE
Start k3s failed with "Segmentation fault"

### ISSUE THREAD

**Issue by fooevr** [rancher/k3s#2269]
**Environmental Info:**
K3s Version: 
v1.18.8+k3s1 (6b595318)

Node(s) CPU architecture, OS, and Version: 
Linux master00 4.15.0-106-generic #107-Ubuntu SMP Thu Jun 4 11:27:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
3 masters

**Describe the bug:**
k3s working correct for several days. but failed since yesterday, reboot service failed with "Segmentation fault" message.
```
K3S_TOKEN=b8bf0cff5d98326199fb9aa974f5c01c /usr/local/bin/k3s --debug     server --log /var/log/k3s.log -v 5         '--cluster-init'         '--bind-address'         '192.168.0.240'         '--advertise-address'         '192.168.0.240'
```
```
DEBU[0000] Asset dir /var/lib/rancher/k3s/data/19bb6a9b46ad0013de084cf1e0feb7927ff9e4e06624685ff87f003c208fded1 
DEBU[0000] Running /var/lib/rancher/k3s/data/19bb6a9b46ad0013de084cf1e0feb7927ff9e4e06624685ff87f003c208fded1/bin/k3s-server [/usr/local/bin/k3s --debug server --log /var/log/k3s.log -v 5 --cluster-init --bind-address 192.168.0.240 --advertise-address 192.168.0.240] 
signal: segmentation fault
```

**Comment by brandond** [comment]
Normally when k3s segfaults you get a nice stack trace and goroutine dump. Can you share any additional log output? How much disk space do you have free?

**Comment by dweomer** [comment]
@fooevr as mentioned here, https://rancher.com/docs/k3s/latest/en/installation/ha-embedded/ , multi-master with embedded data store is (and always has been) experimental. Moreover you will notice that dqlite (1.0 through 1.18.x) has been dropped in 1.19.x in favor of etcd. What you've run into with your cluster (the unrecoverable crashing) is one of the reasons we have moved away from the dqlite backend. As one of the developers working on and with k3s I wish I had something more helpful to offer but your cluster is likely not recoverable.

**Comment by brandond** [comment]
I too suspect that it's dqlite related, but without more logs it's hard to confirm or deny. Haven't we seen segfaults due to insufficient disk space while extracting the asset dir?

**Comment by dweomer** [comment]
> I too suspect that it's dqlite related, but without more logs it's hard to confirm or deny. Haven't we seen segfaults due to insufficient disk space while extracting the asset dir?

Yes, and also #1938
