### ISSUE TITLE
Inconsistent behaviour for LoadBalancer spec type

### ISSUE THREAD

**Issue by t0rrant** [rancher/k3s#2270]
**Environmental Info:**

K3s Version: 

k3s version v1.18.8+k3s1 (6b595318)

Node(s) CPU architecture, OS, and Version: 

Linux k3s-server 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux

Cluster Configuration:

single master cluster

**Describe the bug:**

On the host the ports are properly forwarded and I can reach the services on those ports, but the external IP stays in the `pending` state and the corresponding svclb pods are also pending with empty logs.

**Steps To Reproduce:**

- Installed K3s: 
   `curl -sfL https://get.k3s.io | sh -s - --tls-san  <public-ip>  --tls-san <hostname.domain>`
- Deployed helm charts with service type of ClusterIP
- Manually change the type to LoadBalancer

**Expected behavior:**

For each service, ports are listening on the host, iptables rules are created, svclb pods are running and service has an externalIP assigned automatically

**Actual behavior:**

For each service, ports are listening on the host, iptables rules are created, some svclb pods are pending and their corresponding services are pending an externalIP

**Additional context / logs:**

After deploying applying multiple helm charts, I edited the services which I wanted exposed by changing their spec type to `LoadBalancer`, most of them get an external IP and everything is fine.
However, for 2 of them the external IP is forever pending and the corresponding svclb pods are also pending, with empty logs.

**pod status**
```
$ kubectl --kubeconfig k3s.yaml get pods
NAME                                      READY   STATUS    RESTARTS   AGE
cega-mq-849dc48db5-q4mtg                  1/1     Running   0          3d
cega-users-5dbd89c76f-jfqvx               1/1     Running   0          3d
posix-sda-svc-verify-59567c4c88-pz2kf     1/1     Running   0          2d20h
posix-sda-svc-ingest-b5ffddc98-sm9cp      1/1     Running   0          2d20h
posix-sda-svc-finalize-689b657bb6-8nlvt   1/1     Running   0          2d20h
svclb-cega-users-4swx6                    0/1     Pending   0          24h
svclb-cega-mq-b6lq8                       4/4     Running   0          23h
svclb-posix-sda-svc-inbox-glffc           1/1     Running   0          23h
svclb-posix-sda-svc-doa-7c66w             0/1     Pending   0          23h
svclb-broker-sda-mq-kvjhc                 0/3     Pending   0          23h
svclb-cega-mq-management-2whk4            2/2     Running   0          3h40m
svclb-postgres-sda-db-cz2qs               1/1     Running   0          3h5m
postgres-sda-db-0                         1/1     Running   0          3d
posix-sda-svc-inbox-54f6c8fd5b-4g7wg      1/1     Running   0          2d20h
broker-sda-mq-0                           1/1     Running   0          3d
posix-sda-svc-doa-bdb47f9fb-rjs9c         1/1     Running   0          2d20h
```

**service status**
```
$ kubectl --kubeconfig k3s.yaml get svc
NAME                  TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)                                                        AGE
kubernetes            ClusterIP      10.43.0.1       <none>          443/TCP                                                        34d
cega-mq               LoadBalancer   10.43.101.187   **REDACTED**    5672:31454/TCP,5671:32734/TCP,4369:31537/TCP,25672:32460/TCP   3d
posix-sda-svc-inbox   LoadBalancer   10.43.189.93    **REDACTED**    2222:31287/TCP                                                 2d20h
posix-sda-svc-doa     LoadBalancer   10.43.245.245   **REDACTED**    443:32134/TCP                                                  2d20h
cega-mq-management    LoadBalancer   10.43.72.15     **REDACTED**    15672:31441/TCP,15671:32634/TCP                                3d
postgres-sda-db       LoadBalancer   10.43.189.162   **REDACTED**    5432:32067/TCP                                                 3d
broker-sda-mq         LoadBalancer   10.43.242.185   <pending>       5671:30471/TCP,4369:31249/TCP,25672:30393/TCP
cega-users            LoadBalancer   10.43.53.184    <pending>       443:30541/TCP                                                  3d
```

**Comment by brandond** [comment]
When using the built-in ServiceLB, ports for LoadBalancer are allocated by finding a cluster member with that port available, and exposing the port on that node. This is covered [in the docs](https://rancher.com/docs/k3s/latest/en/networking/#how-the-service-lb-works):

> If you try to create a Service LB that listens on port 80, the Service LB will try to find a free host in the cluster for port 80. If no host with that port is available, the LB will stay in Pending.

I am guessing that you only have one node in your cluster, which means that only one LoadBalancer service can bind to each port. If you want to bind multiple LoadBalancer services to the same port, you will need to use an alternative load balancer like MetalLB that can provision additional external IP addresses for the services to bind to.

**Comment by t0rrant** [comment]
@brandond I misunderstood the process of the built-in ServiceLB, that's a read the docs reminder.

I added 3 workers to the cluster and now every service has an external IP.

Thanks!

**Comment by brandond** [comment]
That works! Note that if you don't need the capacity of additional workers, adding more nodes just to get more IP addresses isn't particularly efficient. If you can get away with less nodes to support your CPU/memory/HA requirements, you might consider MetalLB or something else to provide the service IPs.

**Comment by t0rrant** [comment]
Duly noted! I'm still green on the kubernetes world but I'll surely look into MetalLB, looks what I'll need for production.
