### ISSUE TITLE
https://github.com/rancher/k3s/releases/download/v1.19.2-rc1+k3s1/sha256sum-arm64.txt not found

### ISSUE THREAD

**Issue by PPCM** [rancher/k3s#2280]
For the latest 1.19.2-rc1 the sha256sum for arm64 is not on Github

In that way `curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL=testing sh -` does nothing --> No error message

**Comment by brandond** [comment]
We have been having CI issues with build artifacts, and will be tagging a new RC to fix.
https://drone-publish.rancher.io/rancher/k3s/911/2/3

**Comment by davidnuzik** [comment]
This should be fixed now with the release of [v1.19.2-rc2+k3s1](https://github.com/rancher/k3s/releases/tag/v1.19.2-rc2%2Bk3s1)

**Comment by PPCM** [comment]
Much better. It's fine for me
Thanks

**Comment by davidnuzik** [comment]
Thank you! I'm going to close this then.
