### ISSUE TITLE
JSON error when connecting worker node to server

### ISSUE THREAD

**Issue by itsMeDacarvalho** [rancher/k3s#2294]
**Environmental Info:**
K3s Version: _v1.16.15_
```sh
/initlo/data/pxred-k3s-needed $ sudo ./k3s-armhf agent --server https://192.168.1.71:6443 --token K10e12e0692a94927a297190d3c969fdf9a2d
ad68ecca37332eaf358b2bb60d81f3::server:4e1f88b7649160d141f163962cfcedb9
INFO[2020-09-21T21:53:53.876170658+01:00] Starting k3s agent v1.16.15+k3s1 (790b740f)
WARN[2020-09-21T21:53:53.883493409+01:00] Failed to find cpuset cgroup, you may need to add "cgroup_enable=cpuset" to your linux cmdline (/boot/cmdline.txt on a Raspberry Pi)
INFO[2020-09-21T21:53:53.885209174+01:00] module overlay was already loaded
INFO[2020-09-21T21:53:53.889997192+01:00] module nf_conntrack was already loaded
WARN[2020-09-21T21:53:53.938820877+01:00] failed to start br_netfilter module
INFO[2020-09-21T21:53:53.944800806+01:00] Running load balancer 127.0.0.1:36961 -> [192.168.1.71:6443]
ERRO[2020-09-21T21:53:54.712690648+01:00] json: cannot unmarshal object into Go struct field Control.Skips of type []string
ERRO[2020-09-21T21:54:00.246542194+01:00] json: cannot unmarshal object into Go struct field Control.Skips of type []string
```

Node(s) CPU architecture, OS, and Version:
_Work Node:_ Linux Arch 5.8.3
_Work Node:_ Custom Yocto Linux  armv7l 

Cluster Configuration:
Just a simple cluster test. 1 server at arch linux machine and a worker node running in a beaglebone black running a custom yocto linux with the (needed, I think) layers to work with k3s.

**Describe the bug:**
When I try to connect to the server I get the error message wich print is the mentioned in the first section. I get CA certificates error before, but now i have this one.

**Steps To Reproduce:**
- Installed K3s on server with script provided in the page and --bind-address flag to point to a localhost IP.
- Installed K3s on worker pointing to the server with respective token. Just to mention that worker node is working under a enterprise proxy.
- Error while is trying to setup worker!

**Expected behavior:**

At least I was expecting to have no errors and see worker node listed on server side.

**Actual behavior:**

I cant setup worker node properly due to the error described.

**Additional context / logs:**

Here the purpose is to try to add K3s support on a edge device, in this case Beaglebone Black just for testing, with a Yocto Linux. I had a virtualization layer but I still miss some of the flags when i run check-config.

**Comment by brandond** [comment]
Are you running 1.16 on both devices? If so, why did you pick this version? It's end of life now that 1.19 is out.

**Comment by itsMeDacarvalho** [comment]
Hi @brandond, I just download the armhf binary and used it on the edge device :) On server side, I used the script and It downloads/installs everything.
- I can try to use the newer version, did you think this can be a missmatch of versions?
- Did you know anything about yocto layers needed to support k3s? I am in a "research" proccess to support k3s in a custom Yocto linux.
Thanks in advance.

**Comment by itsMeDacarvalho** [comment]
I am now using the same version on worker node and server node: 1.18.15, and the error is gone.
Now I am getting this output:
```sh 
INFO[2020-09-22T05:55:36.115176152-04:00] waiting for node px-red-bbb-f8-28-ae CIDR not assigned yet
E0922 05:55:37.835751    8746 proxier.go:841] Failed to ensure that filter chain INPUT jumps to KUBE-EXTERNAL-SERVICES: error checking rule: exit status 2: iptables v1.8.3 (legacy): Couldn't find match `comment'

Try `iptables -h' or 'iptables --help' for more information.
I0922 05:55:37.847674    8746 proxier.go:825] Sync failed; retrying in 30s
INFO[2020-09-22T05:55:38.141135963-04:00] waiting for node px-red-bbb-f8-28-ae CIDR not assigned yet
```
Even with the info being displayed I can see the worker node on server side when I run ``k3s kubectl get nodes``, can you provide some help regarding this one? Thanks in advance.

**Comment by brandond** [comment]
Sounds like your iptables version is too old.

**Comment by itsMeDacarvalho** [comment]
I have 1.8, I think this is not old, right @brandond?

**Comment by brandond** [comment]
Iptables on your node seems to be missing support for comment matching:
> iptables v1.8.3 (legacy): Couldn't find match `comment'

I'm not sure if this is missing from your kernel, or iptables binary. It seems to be a fairly uncommon error so I'm not finding much info on it.

**Comment by itsMeDacarvalho** [comment]
The iptables are present in the system, i get the version from there. I will try to solve it then, thanks :)
