### ISSUE TITLE
Surprising behavior with regards to manifests and no-deploy

### ISSUE THREAD

**Issue by mortenlj** [rancher/k3s#230]
**Is your feature request related to a problem? Please describe.**
I wanted to change the configuration for Traefik, and figured the easiest way was to not deploy the traefik chart as defined by k3s. After adding the `--no-deploy traefik` option, I was surprised to see that the `traefik.yml` file is still written to `/var/lib/rancher/k3s/server/manifests/`. After digging into the code I realised that the no-deploy option makes k3s ignore files matching that name, while I had assumed it would just not generate that file.

This had me confused for the better part of a day, where I was trying to figure out why the traefik.yml I had created constantly was overwritten and ignored. Once I looked at the code, I understood what was happening, but it also made it clear that I can't load my own traefik chart without naming it something else, which feels strange.

**Describe the solution you'd like**
Could the no-deploy option be implemented as "don't create manifest X" instead of "ignore manifests with names matching X"?

**Describe alternatives you've considered**
This is more of a "least surprise" kind of thing, the current solution works, it just wasn't what I expected. It would also be nice to be able to provide my own traefik manifest, without having to come up with alternate names for it, but it's a "nice to have" feature.

**Additional context**
Having looked at the code, I believe it would be easy to just skip the generation instead of ignore the file when listing. I might even be able to provide a PR to that effect if you want (I just need to set up a Go development environment, which I haven't had for a while).

**Comment by dnoland1** [comment]
Ran:
```
vagrant@k3s-node1:~$ sudo k3s server --no-deploy traefik
```
Then ran:
```
root@k3s-node1:/var/lib/rancher/k3s/server/manifests# ls -l
total 4
-rw------- 1 root root 3610 Mar 29 05:30 coredns.yaml
```
The traefix manifest was not generated as expected.

**Comment by erikwilson** [comment]
Thanks for testing @dnoland1!
