### ISSUE TITLE
local-path-provisioner does not work in 1.19

### ISSUE THREAD

**Issue by ElisaMeng** [rancher/k3s#2304]
**Environmental Info:**
K3s Version: 

v1.19.1+k3s1
Node(s) CPU architecture, OS, and Version: 

ubuntu
Cluster Configuration:

3 masters 
**Describe the bug:**

local-path provisioner can create pv but not possible to delete it. 

**Steps To Reproduce:**

- provision a local-path pv
- delete the pvc after it is bound
- local-path controller say it is deleted, but actually the pv stuck in failed state. 

**Expected behavior:**

 pv should be deleted

**Actual behavior:**

pv stuck in failed state. 

**Additional context / logs:**

k3s-service.log report like this: 

```
924 06:50:40.876151    6702 goroutinemap.go:150] Operation for "delete-pvc-5a7c5842-295e-4336-9710-2e8a2bc4bdb1[7894f742-275a-4914-9b15-0748a9ad1757]" failed. No retries permitted until 2020-09-24 06:52:42.876134203 +0800 +08 m=+133484.464916807 (durationBeforeRetry 2m2s). Error: "host_path deleter only supports /tmp/.+ but received provided /var/lib/rancher/k3s/storage/pvc-5a7c5842-295e-4336-9710-2e8a2bc4bdb1"
E0924 06:50:40.876185    6702 goroutinemap.go:150] Operation for "delete-pvc-cb98f518-5ae1-4cf5-a602-651e64b7c20d[9f8809a0-cf33-4249-9a52-c2311c317c02]" failed. No retries permitted until 2020-09-24 06:52:42.876174214 +0800 +08 m=+133484.464956818 (durationBeforeRetry 2m2s). Error: "host_path deleter only supports /tmp/.+ but received provided /var/lib/rancher/k3s/storage/pvc-cb98f518-5ae1-4cf5-a602-651e64b7c20d"
E0924 06:50:40.876207    6702 goroutinemap.go:150] Operation for "delete-pvc-130a7fa4-0c0f-44ad-8182-7d66af41964d[51a68c65-1fff-4bf2-a552-399f1a53eb96]" failed. No retries permitted until 2020-09-24 06:52:42.876197012 +0800 +08 m=+133484.464979617 (durationBeforeRetry 2m2s). Error: "host_path deleter only supports /tmp/.+ but received provided /var/lib/rancher/k3s/storage/pvc-130a7fa4-0c0f-44ad-8182-7d66af41964d"
E0924 06:51:40.867540    6702 goroutinemap.go:150] Operation for "delete-pvc-7221858c-8a2b-47ff-8c67-801a38624019[d5da2e70-8642-4976-a2ca-e7adde64cb39]" failed. No retries permitted until 2020-09-24 06:53:42.867519775 +0800 +08 m=+133544.456302382 (durationBeforeRetry 2m2s). Error: "host_path deleter only supports /tmp/.+ but received provided /var/lib/rancher/k3s/storage/pvc-7221858c-8a2b-47ff-8c67-801a38624019"
E0924 06:51:40.867896    6702 goroutinemap.go:150] Operation for "delete-pvc-6f811d41-3a3a-4e77-a9ba-0664f4a1cd44[95a842a1-ebda-417e-950a-24923d2846a8]" failed. No retries permitted until 2020-09-24 06:53:42.867882841 +0800 +08 m=+133544.456665446 (durationBeforeRetry 2m2s). Error: "host_path deleter only supports /tmp/.+ but received provided /var/lib/rancher/k3s/storage/pvc-6f811d41-3a3a-4e77-a9ba-0664f4a1cd44"

```

**Comment by ElisaMeng** [comment]
Update to version v0.0.17 seem solving the issue.

**Comment by brandond** [comment]
Can you describe what you updated, and how?

**Comment by ElisaMeng** [comment]
Hi @brandond, here is what I did:

First, update the config according the example here (https://github.com/rancher/local-path-provisioner/blob/master/deploy/example-config.yaml)
```
kubectl -n kube-system edit configmap  local-path-config 
```
Append following test to the configmap data
```
  setup: |-
        #!/bin/sh
        path=$1
        mkdir -m 0777 -p ${path}
  teardown: |-
        #!/bin/sh
        path=$1
        rm -rf ${path}
```

Secondly, run the following command to set image version to v0.0.17
```
kubectl -n kube-system edit configmap  local-path-provisioner
```

The deployment restart after editing, the provision/unprovision become OK.

**Comment by ElisaMeng** [comment]
This is a temporary fix, not sure if I reboot the master, will old manifest will overwrite it. Did not test.

**Comment by ShylajaDevadiga** [comment]
@ElisaMeng The pod that is claiming the referenced pvc has to be deleted before deleing the pvc.  Can you confirm you have deleted the pod?

Alternatively if the pod is not deleted you can edit/patch the pvc and set the finalizers to null if it is in Terminating mode.

On k3s version v1.19.1+k3s1, I have tried the example here https://github.com/rancher/local-path-provisioner and i see the pvc being deleted and the pv as well.
```
kubectl get pvc -A -o wide
NAMESPACE   NAME             STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE   VOLUMEMODE
default     local-path-pvc   Bound    pvc-e1f557ba-8927-418e-a112-c77b8d12b2d5   2Gi        RWO            local-path     41s   Filesystem

kubectl get pv -A -o wide
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                    STORAGECLASS   REASON   AGE   VOLUMEMODE
pvc-e1f557ba-8927-418e-a112-c77b8d12b2d5   2Gi        RWO            Delete           Bound    default/local-path-pvc   local-path              32s   Filesystem

kubectl delete -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/examples/pod.yaml
pod "volume-test" deleted
kubectl delete -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/examples/pvc.yaml
persistentvolumeclaim "local-path-pvc" deleted

kubectl get pvc -A -o wide
No resources found
kubectl get pv -A -o wide
No resources found
```
If you still see the issue can you also share the Reclaim Policy set on the pv and steps to repro. Thanks

**Comment by ElisaMeng** [comment]
@ShylajaDevadiga Hmm, I did do as you suggested, but was in a cluster that upgrade from early version. Now I  try to replay my test in a fresh new installed cluster, I don't see the issue anymore. However, I still suggest to uplift local-path-provsioner since version 0.0.14 has a leakage on CPU usage, cause necessary CPU load.

**Comment by ShylajaDevadiga** [comment]
Thanks for the update and suggestion @ElisaMeng 
Closing this issue as resolved.
