### ISSUE TITLE
Create multiple masters, only one can be queried through “kubectl get no”

### ISSUE THREAD

**Issue by RollBack2010** [rancher/k3s#2305]
K3s Version: v1.18.8+k3s1 (6b595318)
Node(s) CPU architecture, OS, and Version: 
Linux test-k3s-master-1 3.10.0-1127.18.2.el7.x86_64 #1 SMP Sun Jul 26 15:27:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Via **curl -sfL http://rancher-mirror.cnrancher.com/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn sh -s-server \
--datastore-endpoint="mysql://root:123@tcp(ip:3307)/k3s"** command created two services,
But **kubectl get no** sees only one master。

For example, there are two servers A\B, first execute **curl -sfL on server A http://rancher-mirror.cnrancher.com/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn sh -s-server \
--datastore-endpoint="mysql://root:123@tcp(ip:3307)/k3s"** then execute it again on server B, wait for A\B to succeed, execute **kubectl get no** to view,
There is only one master, which is the A server。
Who joins first shows who the master is。
The virtual machine I built (centos7) will not have this situation.
Please help to see if the server configuration is wrong, is there a way to track logs

![image](https://user-images.githubusercontent.com/15976246/94098844-23d79a00-fe5c-11ea-8d17-6ce602fc2463.png)
![image](https://user-images.githubusercontent.com/15976246/94098967-5c777380-fe5c-11ea-89c7-415097e37a5e.png)

**Comment by brandond** [comment]
Can you confirm that both nodes have unique hostnames? You can get the logs from journalctl:
 journalctl -u k3s --no-pager

**Comment by RollBack2010** [comment]
![image](https://user-images.githubusercontent.com/15976246/94110664-943ee500-fe75-11ea-80f5-01f60135f323.png)
The second server to join the cluster, through the **journalctl -f -u k3s --no-pager** query has been outputting the information in the figure, this server **kubectl get no** has been able to display the first server node information

**Comment by brandond** [comment]
What do you get from `hostname -f` on both nodes? Can both nodes reach each other on port 6443?

**Comment by RollBack2010** [comment]
![image](https://user-images.githubusercontent.com/15976246/94117264-978a9e80-fe7e-11ea-87b7-fbdad1a662be.png)

![image](https://user-images.githubusercontent.com/15976246/94117278-9d807f80-fe7e-11ea-946b-bd3431dd3b41.png)
The picture shows that there are two servers, and they can be connected, and the host names are also different

**Comment by brandond** [comment]
There are a lot of errors and warnings here but it's hard to tell what's going on with just small screenshots of the logs. Can you upload the full k3s logs from each server?

**Comment by RollBack2010** [comment]
I know the reason. The server has two network cards: private network and public network. The public network security group does not open port 6443. After configuring the parameter "appeal address", it will work normally. Thank you.
