### ISSUE TITLE
How cluster is managed incase of failure, Recovery mechanism for cluster in Rancher?

### ISSUE THREAD

**Issue by devopsmd** [rancher/k3s#2315]
**Environmental Info:**
K3s Version: 

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by davidnuzik** [comment]
Hello. The backup and restore procedure for K3s is documented here: https://rancher.com/docs/k3s/latest/en/backup-restore/

Rancher has one as well here: https://rancher.com/docs/rancher/v2.x/en/backups/
