### ISSUE TITLE
k3s server startup hangs, fails after 3 minutes if first cluster member is offline

### ISSUE THREAD

**Issue by brandond** [rancher/k3s#2316]
**Environmental Info:**
K3s Version: 
k3s version v1.19.2+k3s-b56e52ee (b56e52ee)

Node(s) CPU architecture, OS, and Version: 
Linux centos01.lan.khaus 5.8.10-1.el7.elrepo.x86_64 rancher/k3s#1 SMP Thu Sep 17 10:40:48 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
3 servers, embedded etcd

**Describe the bug:**
If you attempt to restart k3s on any node while the first server is offline, the cluster will unrecoverably lose quorum. 

**Steps To Reproduce:**
1. Install k3s on node 1 with `k3s server --cluster-init --token token`
2. Join node 2 and 3 with `k3s server --server https://server1:6443 --token token`
3. Halt server 1
4. Restart k3s on server 2

**Expected behavior:**
k3s on second node should restart successfully, as 2 of the 3 nodes constitute a quorum.

**Actual behavior:**
k3s on node 2 will hang for almost 3 minutes while starting, and eventually exit with a 'connection timed out' error. Node 3 will crash because a single node does not have quorum. Cluster can now no longer be started due to rancher/k3s#2249

**Additional context / logs:**

This is similar to rancher/k3s#2249 but I wanted to capture this specific sequence for QA.

**Comment by rancher-max** [comment]
#### Validated this scenario on v1.19.3+k3s2

This is fixed in the release with the fix for the main noted issue. This was just an additional scenario we wanted to doubly confirm. Used the same steps as listed in the issue.
