### ISSUE TITLE
How can I get rid of the Klipper ServiceLB which is interfering with metallb (flapping routes)

### ISSUE THREAD

**Issue by bodleytunes** [rancher/k3s#2323]
Hello All!

I was wondering how I can remove the svc-lb (Klipper?) from Rancher which was deployed with helm

It's interfering with metallb and I'm seeing the routes flapping in BGP.

I can't tell if it was installed with K3s or with rancher as I thought I used the correct switches with k3s to not install traefik or servicelb.  (--no-deploy=traefik,servicelb I can see in the systemD unit )

Many thanks
Jon.

![image](https://user-images.githubusercontent.com/619239/94612007-6523db80-029a-11eb-813e-ffbf386c966b.png)

`ExecStart=/usr/local/bin/k3s \
    server \
        '--cluster-init' \
        '--advertise-address' \
        '10.20.23.125' \
        '--kube-apiserver-arg' \
        'default-not-ready-toleration-seconds=10' \
        '--kube-apiserver-arg' \
        'default-unreachable-toleration-seconds=10' \
        '--no-deploy=traefik,servicelb' \
        '--no-deploy=servicelb' \
`

**Comment by bodleytunes** [comment]
`cattle-system       svclb-rancher-lb-5ljd5                                     1/1     Running   0          6m52s
cattle-system       svclb-rancher-lb-7w4rk                                     1/1     Running   0          6m45s
`
![image](https://user-images.githubusercontent.com/619239/94612673-58ec4e00-029b-11eb-9fcb-2033dcdc1771.png)

**Comment by brandond** [comment]
Yes, that should do it. Did you perhaps originally start up without that flag? If so, you may need to delete and recreate any services that were originally deployed while using ServiceLB, as well as deleting any svclb pods.

**Comment by bodleytunes** [comment]
I started it with the flags, never not had them.  I did reinstall rancher at one point via helm as had to give it the data dir /var/lib/kubelet

not sure whats happend.

Will try reinstalling rancher.

Is there a way to verify if the flags are active.

Also this was from the systemd file in the original cluster init server, are the flags the same when joining the other masters?  I used the same flags on  all of them.

Cheers,
Jon.

**Comment by bodleytunes** [comment]
This was what I used initially firing up the cluster

`curl -fL https://get.k3s.io | K3S_TOKEN=jons-secret-token INSTALL_K3S_CHANNEL=latest sh -s - server --cluster-init --advertise-address 10.20.23.125 --kube-apiserver-arg default-not-ready-toleration-seconds=10 --kube-apiserver-arg default-unreachable-toleration-seconds=10 --no-deploy=traefik,servicelb`

**Comment by bodleytunes** [comment]
then went on to deploy rancher via helm and then traefik via helm

**Comment by bodleytunes** [comment]
OK it seems that svc-lb is still lurking.  I reinstall rancher then expose it manually and the svc-lb pods appear

 kubectl expose deployment rancher -n cattle-system --type=LoadBalancer --name=rancher-lb --port=443

**Comment by brandond** [comment]
--no-deploy is deprecated, you want --disable

**Comment by bodleytunes** [comment]
ok thanks will give it a shot!

**Comment by bodleytunes** [comment]
Yeah thats working now with --disable servicelb, --disable traefik

**Comment by lk7777** [comment]
https://rancher.com/docs/k3s/latest/en/networking/#excluding-the-service-lb-from-nodes

This worked for me:
kubectl label nodes <node name> svccontroller.k3s.cattle.io/enablelb=false
ServiceLB is still there but it just doesn't do anything on those labeled nodes.

`daemonset.apps/svclb-ingress-nginx-controller   0         0         0       0            0           svccontroller.k3s.cattle.io/enablelb=true `

**Comment by cawoodm** [comment]
@bodleytunes Could you explain why you specify `--advertise-address 10.20.23.125` if you are not using a built-in load balancer? I had assumed this flag would be passed to `servicelb`.
