### ISSUE TITLE
status=255

### ISSUE THREAD

**Issue by evguenig** [rancher/k3s#2324]

**Comment by dweomer** [comment]
@evguenig if you have a bug to report please review https://github.com/rancher/k3s/blob/master/.github/ISSUE_TEMPLATE/bug_report.md and provide us with some of the information asked for there.

**Comment by davidnuzik** [comment]
@evguenig - we haven't heard back so I'm going to close out this issue. I noticed it looked like I edited the original issue description. I'm now wondering if there was a glitch or mistake by me - maybe I accidently deleted your original post? If so, my most sincere apologies I am usually very careful. Please let us know if we can assist you. Happy to reopen this issue.

**Comment by evguenig** [comment]
Sorry for late reply - your messages got in spam bin.
Yes - please close the ticket. It was false alarm - I installed k3s on system where minikube was running, after cleaning
minikube everything runs as designed.
