### ISSUE TITLE
[proposal] Make etcd voting members responsible for managing learners

### ISSUE THREAD

**Issue by brandond** [rancher/k3s#2329]
There are a couple challenges with the current approach to etcd cluster member addition:
1. Members are responsible for promoting themselves from learner to voting member.
1. Members that fail to join the cluster, or fail to make the transition to voting member, block additional nodes from joining the cluster, as there can be only one learner in the cluster at a time.

We have already had a couple issues caused by things in the promotion path:
* https://github.com/rancher/k3s/issues/2306
* https://github.com/rancher/k3s/issues/2328
* https://github.com/rancher/k3s/issues/2249
* https://github.com/rancher/rke2/issues/347
* https://github.com/rancher/rke2/issues/392

#### Current Promotion Workflow

The joining member starts a goroutine that runs in a loop at 5 second intervals, trying to promote itself. It does this by:
1. Use the join url + token to retrieve a list of etcd cluster members via custom k3s HTTP API
1. Create an etcdv3 client connection to the first non-learner server on the list
1. Retrieve a list cluster members (again) via etcdv3 api
1. Find the first member that is a learner, and attempt to promote it via the etcdv3 api
1. Exit if successful

Current failure cases mostly exist in the period where this loop is running. Join URLs and tokens are required long after the point where the node has actually been bootstrapped to the cluster, just to support reentering this loop if necessary.

#### Proposed Solution

Make one of the voting members responsible for promoting learners, as well as ejecting learners from the cluster if they fail to promote in a timely manner. Etcd already has a leader flag available via the status api that can be used to select the node responsible for maintaining learners without any additional kubernetes-level leasing or leader election.

This would work similar to the current pattern of running a goroutine that periodically checks etcd status and attempts to take action. Every 5 seconds, the goroutine runs the following steps:
1. Retrieve local node status. If status cannot be retrieved, or the local node is not the leader, take no action this interval.
1. Enumerate cluster members.
1. If no learners are found, take no action this interval.
1. If a learner is found, attempt to promote it.
1. If promotion succeeds, clear data on failed promotions (there can be only one learner at a time, and we just promoted it so no need to track promotions any further)
1. If promotion fails, see if we have previously tried to promote this node, and if so when this was first attempted.
1. If the time since promotion was first attempted is over a threshold (TBD), delete the learner from the cluster.
1. If the learner was deleted from the cluster, clear data on failed promotions.
1. If the learner was not deleted from the cluster, record the learner ID and current time (for use in future iterations).

#### Feedback from design:
1. Use an etcd key with ttl to track learner join timestamp (instead of just storing it in memory)
1. Track learner progress through raft terms, reset ttl if learner is progressing (to prevent cleaning up learners on large/busy clusters)

**Comment by davidnuzik** [comment]
Needs design discussion. Perhaps we may even want to fix this in etcd upstream.

**Comment by davidnuzik** [comment]
We discussed and determined that the plan to improve on this is a good call in the short term so we can mark etcd as stable. Later, when etcd 3.5 comes out it may solve this issue.

**Comment by ShylajaDevadiga** [comment]
Validated and updated #2303
