### ISSUE TITLE
TLS handshake error from : remote error: tls: bad certificate

### ISSUE THREAD

**Issue by mibaboo** [rancher/k3s#2330]
**Environmental Info:**
K3s Version: 
k3s version v1.18.9+k3s1 (630bebf9)

Node(s) CPU architecture, OS, and Version: 
Master: Linux ubuntu-VirtualBox 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Node: Linux ubuntu-VirtualBox 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 Master 
1 Node
Both running on Ubuntu VMs on VirtualBox in **Network bridged mode** the Host is MacOS

**Describe the bug:**
I cannot connect the Agent to the Master. When I try I get the following error
TLS handshake error from : remote error: tls: bad certificate
**Steps To Reproduce:**

- Installed K3s on Master:
`curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE=644 sh -`
This works and I get run kubectl get nodes. I only see the master obviously.

- Installed K3s on Node:
`curl -sfL https://get.k3s.io | K3S_TOKEN=THETOKEN K3S_URL=https://192.168.101.125:6443`

I get the token from the master by running:
`sudo cat /var/lib/rancher/k3s/server/node-token`

**Expected behavior:**
The Agent Node to connect to the Master Node

**Actual behavior:**
The Agent does not connect to the Master

**Additional context / logs:**

**Comment by mibaboo** [comment]
I found as solution by adding the hostname in /etc/hosts.

**Comment by jurgenweber** [comment]
which hostname? You add the master hostname in the node and change the k3s URL to use the hostname?
