### ISSUE TITLE
How to restored embedded etcd from snapshot on master node and then the other 2 nodes after first is restored.

### ISSUE THREAD

**Issue by bodleytunes** [rancher/k3s#2337]
**Environmental Info:**
**K3s Version:** 
1.19 embedded etcd
k3s version v1.19.2+k3s1 (d38505b1)

Node(s) CPU architecture, OS, and Version: 
amd64 x2 and arm64 x1

Cluster Configuration:
3 Masters (pi is master but tainted so just participates in etcd)

**Describe the bug:**
Trying to restore etcd from snapshot, works for the first node but can't get the othe two nodes to rejoin succesfully, they seem to have references to the old cluster.

How do you properly rejoin them.  Is it a case of running full k3s-uninstall and then rejoining?  I

**Steps To Reproduce:**
install k3s master on first node
install master on 2nd node
install master on pi 3rd node
installed rancher and various apps, plex, longhorn, traefik, metallb, sabnzb
after a few days "something happens" after a few reboots of one of the main nodes and the quorum is lost, so give up and try to restore from snapshot

restored to the first node using
`k3s server --cluster-reset --cluster-reset-restore-path=/var/lib/rancher/k3s/server/db/snapshots/etcd-snapshot-1601640000
`

seems to work fine, but then don't really know how to rejoin the other nodes again as they still have all the references to the old cluster and fail.
Then try k3s-uninstall on the last 2 dangling nodes and try rejoin and still unable to join.
rejoin command was as follows:
`curl -fL https://get.k3s.io | K3S_TOKEN=my_token INSTALL_K3S_CHANNEL=latest sh -s - server --server https://10.20.23.125:6443 --advertise-address 10.102.0.125 --kube-apiserver-arg default-not-ready-toleration-seconds=10 --kube-apiserver-arg default-unreachable-toleration-seconds=10 --disable=traefik --disable=servicelb`
Dont really know what I'm doing!

**Expected behavior:**
Be able to restore the cluster to all nodes

**Actual behavior:**
end up with a single original master node but the other left dangling and not ready

**Additional context / logs:**

Cheers,

Jon.

**Comment by brandond** [comment]
K3s actually tells you what to do when you run --cluster-reset on the first node:

https://github.com/rancher/k3s/blob/master/pkg/etcd/etcd.go#L155
> Etcd is running, restart without --cluster-reset flag now. Backup and delete ${datadir}/server/db on each peer etcd server and rejoin the nodes

**Comment by bodleytunes** [comment]
Yeah sorry I forgot to update, I did managed to get it sorted removing the cluster-reset flag.
thanks!
Jon.
