### ISSUE TITLE
[ERROR]  Can not find systemd or openrc to use as a process supervisor for k3s on Linux VM 

### ISSUE THREAD

**Issue by ariesyous** [rancher/k3s#2338]
Trying to deploy K3s on a single VM Linux host. 

$ curl -sfL https://get.k3s.io | sh -
**[ERROR]  Can not find systemd or openrc to use as a process supervisor for k3s**

$ uname -a
Linux cs-138884758992-default-boost2-l6m8q 5.4.49+ #1 SMP Wed Sep 23 19:45:38 PDT 2020 x86_64 GNU/Linux

**Comment by dweomer** [comment]
The k3s install script wants to install a systemd unit or openrc service file. If your system init is neither of those then you will likely want to set up the equivalent for your system. Such is only necessary, however, if you want k3s to be started if the system is rebooted.

**Comment by ariesyous** [comment]
Thanks for the reply, I ended up working around the issue by using the k3s binary instead.

**Comment by rbucker** [comment]
When I run the script via ssh:

```
ssh root@1.2.3.4 curl -sfL https://get.k3s.io | eval $server sh -  
```

I get the same error... The error is generated if it cannot locate the `/run/systemd` directory (along with another check).  However, [a] photonos v3 has such a folder and [b] works if I'm actually logged into the machine instead of an ssh command.

```
$ uname -a
Linux phos3k2..local 4.19.150-2.ph3-esx #1-photon SMP Fri Oct 23 02:25:37 UTC 2020 x86_64 GNU/Linux
```
