### ISSUE TITLE
k3s node stuck NotReady

### ISSUE THREAD

**Issue by darkphoenix** [rancher/k3s#2340]
**Environmental Info:**
K3s Version: 
k3s version v1.18.9+k3s1 (630bebf9)

Node(s) CPU architecture, OS, and Version: 
Linux lambda 4.15.18-30-pve #1 SMP PVE 4.15.18-58 (Fri, 12 Jun 2020 13:53:01 +0200) x86_64 GNU/Linux

Cluster Configuration:
One host, running k3s as both master and node.  The host is also running LXC containers using Proxmox, which might cause issues with cgroups?

**Describe the bug:**
k3s node is stuck NotReady with error [container runtime status check may not have completed yet, missing node capacity for resources: ephemeral-storage]

**Comment by brandond** [comment]
Can you provide logs from startup onward? Hard to tell what's going on without more details.

**Comment by darkphoenix** [comment]
Sorry for not responding quickly, I was busy with other project and this kind of got lost - in the process I reconfigured some things and cleaned up the root filesystem a bit and it appears to be working now.  Not sure if it was the filesystem actually be overly full or something else I changed in the process, but whatever it is, it's fixed now.
