### ISSUE TITLE
Traefik installed despite --disabled (--no-deploy) flag

### ISSUE THREAD

**Issue by tburschka** [rancher/k3s#2341]
**Environmental Info:**
K3s Version: k3s version v1.19.2+k3s1 (d38505b1)

Node(s) CPU architecture, OS, and Version: Linux master-100 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration: 2 masters

	kubectl get nodes -o wide
	NAME         STATUS   ROLES         AGE   VERSION        INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
	master-100   Ready    etcd,master   18m   v1.19.2+k3s1   10.10.10.100   <none>        Ubuntu 20.04.1 LTS   5.4.0-48-generic   containerd://1.4.0-k3s1
	master-101   Ready    etcd,master   17m   v1.19.2+k3s1   10.10.10.101   <none>        Ubuntu 20.04.1 LTS   5.4.0-48-generic   containerd://1.4.0-k3s1

**Describe the bug:**
Traefik is installed even with --disable traefik flag. I've also tried with --no-deploy flag (which is default if using --no-extras flag in k3sup)

**Steps To Reproduce:**
- Installed K3s via k3sup:

		export SERVER_IP=10.10.10.100
		export NEXT_SERVER_IP=10.10.10.101

		k3sup install \
		  --print-command \
		  --ip $SERVER_IP \
		  --user $USER \
		  --cluster \
		  --k3s-version v1.19.2+k3s1 \
		  --k3s-extra-args "--disable traefik,servicelb"

		k3sup join \
		  --print-command \
		  --ip $NEXT_SERVER_IP \
		  --user $USER \
		  --server-user $USER \
		  --server-ip $SERVER_IP \
		  --server \
		  --k3s-version v1.19.2+k3s1

**Expected behavior:**
no traefik installation

**Actual behavior:**
traefik is still installed

	kubectl get pods -A                                                                                                             ✔  10238  00:25:37 
	NAMESPACE     NAME                                     READY   STATUS      RESTARTS   AGE
	kube-system   coredns-66c464876b-lcf28                 1/1     Running     0          17m
	kube-system   helm-install-traefik-g5d52               0/1     Completed   0          16m
	kube-system   local-path-provisioner-7ff9579c6-bgg57   1/1     Running     0          17m
	kube-system   metrics-server-7b4f8b595-7pfgk           1/1     Running     0          17m
	kube-system   traefik-5dd496474-wlksq                  1/1     Running     0          16m

**Additional context / logs:**

	Running: k3sup install
	Public IP: 10.10.10.100
	ssh: curl -sLS https://get.k3s.io | INSTALL_K3S_EXEC='server --cluster-init --tls-san 10.10.10.100 --disable traefik,servicelb' INSTALL_K3S_VERSION='v1.19.2+k3s1' sh -

	[INFO]  Using v1.19.2+k3s1 as release
	[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v1.19.2+k3s1/sha256sum-amd64.txt
	[INFO]  Downloading binary https://github.com/rancher/k3s/releases/download/v1.19.2+k3s1/k3s
	[INFO]  Verifying binary download
	[INFO]  Installing k3s to /usr/local/bin/k3s
	[INFO]  Creating /usr/local/bin/kubectl symlink to k3s
	[INFO]  Creating /usr/local/bin/crictl symlink to k3s
	[INFO]  Creating /usr/local/bin/ctr symlink to k3s
	[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
	[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
	[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
	[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
	[INFO]  systemd: Enabling k3s unit
	Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.
	[INFO]  systemd: Starting k3s
	Result: [INFO]  Using v1.19.2+k3s1 as release
	[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v1.19.2+k3s1/sha256sum-amd64.txt
	[INFO]  Downloading binary https://github.com/rancher/k3s/releases/download/v1.19.2+k3s1/k3s
	[INFO]  Verifying binary download
	[INFO]  Installing k3s to /usr/local/bin/k3s
	[INFO]  Creating /usr/local/bin/kubectl symlink to k3s
	[INFO]  Creating /usr/local/bin/crictl symlink to k3s
	[INFO]  Creating /usr/local/bin/ctr symlink to k3s
	[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
	[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
	[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
	[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
	[INFO]  systemd: Enabling k3s unit
	[INFO]  systemd: Starting k3s
	 Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.

	ssh: sudo cat /etc/rancher/k3s/k3s.yaml

	[...]
	 
	Saving file to: /home/torsten/Projekte/k3sup/kubeconfig

	# Test your cluster with:
	export KUBECONFIG=/home/torsten/Projekte/k3sup/kubeconfig
	kubectl get node -o wide
	Running: k3sup join
	Server IP: 10.10.10.100
	ssh: sudo cat /var/lib/rancher/k3s/server/node-token

	K10361580f188c6209b1f89846ab235167c404e07444e0fdeda10b6a8a6ad9fb56a::server:d6a2daaa2713ff9f7e40c2112f079e04
	ssh: curl -sfL https://get.k3s.io/ | K3S_URL='https://10.10.10.100:6443' INSTALL_K3S_EXEC='server --server https://10.10.10.100:6443' K3S_TOKEN='K10361580f188c6209b1f89846ab235167c404e07444e0fdeda10b6a8a6ad9fb56a::server:d6a2daaa2713ff9f7e40c2112f079e04' INSTALL_K3S_VERSION='v1.19.2+k3s1' sh -s - 
	[INFO]  Using v1.19.2+k3s1 as release
	[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v1.19.2+k3s1/sha256sum-amd64.txt
	[INFO]  Downloading binary https://github.com/rancher/k3s/releases/download/v1.19.2+k3s1/k3s
	[INFO]  Verifying binary download
	[INFO]  Installing k3s to /usr/local/bin/k3s
	[INFO]  Creating /usr/local/bin/kubectl symlink to k3s
	[INFO]  Creating /usr/local/bin/crictl symlink to k3s
	[INFO]  Creating /usr/local/bin/ctr symlink to k3s
	[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
	[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
	[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
	[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
	[INFO]  systemd: Enabling k3s unit
	Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.
	[INFO]  systemd: Starting k3s
	Logs: Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.
	Output: [INFO]  Using v1.19.2+k3s1 as release
	[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v1.19.2+k3s1/sha256sum-amd64.txt
	[INFO]  Downloading binary https://github.com/rancher/k3s/releases/download/v1.19.2+k3s1/k3s
	[INFO]  Verifying binary download
	[INFO]  Installing k3s to /usr/local/bin/k3s
	[INFO]  Creating /usr/local/bin/kubectl symlink to k3s
	[INFO]  Creating /usr/local/bin/crictl symlink to k3s
	[INFO]  Creating /usr/local/bin/ctr symlink to k3s
	[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
	[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
	[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
	[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
	[INFO]  systemd: Enabling k3s unit
	[INFO]  systemd: Starting k3s

**Comment by brandond** [comment]
You need to pass the --disable flag to every server, not just the first one. It appears you forgot to do this on the second server - the one you joined to the cluster.

**Comment by tburschka** [comment]
My fault! you are right. I didn't see this.

    $ kubectl get pods -A -o wide  
    NAMESPACE     NAME                                     READY   STATUS    RESTARTS   AGE   IP          NODE         NOMINATED NODE   READINESS GATES
    kube-system   coredns-66c464876b-dqfrb                 1/1     Running   0          83s   10.42.0.2   master-100   <none>           <none>
    kube-system   local-path-provisioner-7ff9579c6-kcss8   1/1     Running   0          83s   10.42.0.4   master-100   <none>           <none>
    kube-system   metrics-server-7b4f8b595-brqkz           1/1     Running   0          83s   10.42.0.3   master-100   <none>           <none>
