### ISSUE TITLE
k3s crictl pull k8s.gcr.io/pause:3.1  failed with root

### ISSUE THREAD

**Issue by lygstate** [rancher/k3s#235]

**Comment by warmchang** [comment]
Are you use k3s in the GWF? You can provide some error info or context logs.

FYI: https://github.com/rancher/k3s/issues/131, https://github.com/rancher/k3s/issues/83

**Comment by lygstate** [comment]
yeap， under GFW. and doesn't work

**Comment by warmchang** [comment]
Oh, that's not surprising. :crying_cat_face: 

Your can preload the pause image: https://github.com/rancher/k3s/issues/131#issuecomment-470019918, https://github.com/rancher/k3s/pull/141

**Comment by lygstate** [comment]
@warmchang I can not preload the pause images under rancheros, don't know why.

**Comment by lygstate** [comment]
@warmchang 
```
ctr: failed to load image: rpc error: code = Unimplemented desc = unknown service api.v1.CRIPluginService
```
What's this means?

**Comment by carvendy** [comment]
16:05:22.682847    1660 pod_workers.go:190] Error syncing pod b0f8d6e6-453e-11e9-afa5-6c2b594a6b00 ("coredns-7748f7f6df-fw6cl_kube-system(b0f8d6e6-453e-11e9-afa5-6c2b594a6b00)"), skipping: failed to "CreatePodSandbox" for "coredns-7748f7f6df-fw6cl_kube-system(b0f8d6e6-453e-11e9-afa5-6c2b594a6b00)" with CreatePodSandboxError: "CreatePodSandbox for pod \"coredns-7748f7f6df-fw6cl_kube-system(b0f8d6e6-453e-11e9-afa5-6c2b594a6b00)\" failed: rpc error: code = Unknown desc = failed to get sandbox image \"k8s.gcr.io/pause:3.1\": failed to pull image \"k8s.gcr.io/pause:3.1\": failed to resolve image \"k8s.gcr.io/pause:3.1\": no available registry endpoint: failed to do request: Head https://k8s.gcr.io/v2/pause/manifests/3.1: dial tcp 74.125.203.82:443: i/o timeout"

**Comment by lianghuiyuan** [comment]
is it fixed? I have the same problem....
My k3s version is v0.5.0 (8c0116dd)

**Comment by aak1247** [comment]
Update?
