### ISSUE TITLE
[k3d] Missing TLS SAN for initializing server node

### ISSUE THREAD

**Issue by iwilltry42** [rancher/k3s#2365]
**Environmental Info:**
K3s Version: 

- Docker Image rancher/k3s:v1.19.2-k3s1

Cluster Configuration:

- 3 servers

**Describe the bug:**

When creating a multi-server k3s cluster with k3d (v3.1.2), the secondary server node (server-1) fails to join the cluster of the primary server node (server-0) with the following logs:

```bash
$ docker logs -f k3d-test-server-1
time="2020-10-08T09:01:48.098912215Z" level=info msg="Starting k3s v1.19.2+k3s1 (d38505b1)"
time="2020-10-08T09:01:48.124151595Z" level=fatal msg="starting kubernetes: preparing server: server https://k3d-test-server-0:6443/cacerts is not trusted: Get \"https://k3d-test-server-0:6443/cacerts\": x509: certificate is valid for kubernetes, kubernetes.default, kubernetes.default.svc.cluster.local, localhost, not k3d-test-server-0"
```

**Steps To Reproduce:**

- Install k3d v3.1.2: e.g. `wget -q -O - https://raw.githubusercontent.com/rancher/k3d/main/install.sh | bash` (Follow https://github.com/rancher/k3d/#get)
- Try to create a multi-server cluster with k3s v1.19.2: `k3d --trace cluster create test -s 2 --k3s-server-arg="--debug" --k3s-agent-arg="--debug" --no-rollback --image rancher/k3s:v1.19.2-k3s1`

**Expected behavior:**

Multi-Server Cluster should be created without the secondary master node crashing.

**Actual behavior:**

The secondary master node crashes with the logs pasted above.

**Additional context / logs:**

- This can be "fixed" in k3d by adding `--tls-san <server name>` to the `k3s server` command in the initializing server node

From Slack discussions:

- potentially, the issue has its origin in the Go HTTP Client that doesn't do SNI by default
  - Server would usually add the requested hostname to the certificate when the client makes a request with the server name being in the SNI Hello message
  - the issue could've been introduced by the Go version update
  - Related issue on Go: https://github.com/golang/go/issues/22704#issuecomment-344137683

Related k3d issue: https://github.com/rancher/k3d/issues/365

cc @brandond & @erikwilson

**Comment by iwilltry42** [comment]
Following @brandond 's investigation, `k3d` is just trying to add additional server nodes too quickly, before the API Server is even running. This could already be fixed on k3d's side by waiting a little longer until the initializing server node logs `k3s is up and running` indicating, that all components are ready.

**Comment by brandond** [comment]
I added some additional tracing and confirmed that the SNI ServerName is being set by the joining client. The issue is that the k3s-serving cert is created at startup with a preconfigured list of SANs, including those requested via the --tls-san flag. However, additional SAN entries to match the system hostname cannot be added to the certificate until after the datastore and apiserver are available. k3d was waiting for a 'Running kubelet' message as an indication that k3s was done starting and was ready to have additional nods join, when in reality the "k3s is up and running" message is probably the one to look for.
