### ISSUE TITLE
v1.19 MountVolume.SetUp failed /run/k3s/containerd/containerd.sock

### ISSUE THREAD

**Issue by clemenko** [rancher/k3s#2368]
**Environmental Info:**
```
NAME       STATUS   ROLES         AGE    VERSION        INTERNAL-IP       EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
k3s-8a29   Ready    etcd,master   151m   v1.19.2+k3s1   104.131.51.91     <none>        Ubuntu 20.04.1 LTS   5.4.0-45-generic   containerd://1.4.0-k3s1
k3s-94fe   Ready    <none>        151m   v1.19.2+k3s1   159.203.173.119   <none>        Ubuntu 20.04.1 LTS   5.4.0-45-generic   containerd://1.4.0-k3s1
k3s-bdf6   Ready    <none>        151m   v1.19.2+k3s1   159.203.164.91    <none>        Ubuntu 20.04.1 LTS   5.4.0-45-generic   containerd://1.4.0-k3s1
```

Node(s) CPU architecture, OS, and Version: 
All the same : 
```
root@k3s-8a29:~# uname -a
Linux k3s-8a29 5.4.0-45-generic #49-Ubuntu SMP Wed Aug 26 13:38:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
root@k3s-8a29:~# lsmod | grep overlay
overlay               114688  69
```

Cluster Configuration:
See above

**Describe the bug:**
Trying to give socket access to Jenkins. Here is the error
```
  Warning  FailedMount  3s (x6 over 19s)  kubelet            MountVolume.SetUp failed for volume "docker-sock" : hostPath type check failed: /run/k3s/containerd/containerd.sock is not a file
```
This works on v1.18 k3s. 

**Steps To Reproduce:**
Setup k3s from latest, aka v1.19. 
I use https://github.com/clemenko/k3s/blob/master/k3s.sh
Then `kubectl apply -f https://raw.githubusercontent.com/clemenko/k8s_yaml/master/jenkins_containerd.yml `

**Expected behavior:**
It works.

**Actual behavior:**
It not workie. 

**Additional context / logs:**
N/A

**Comment by brandond** [comment]
The hostPath mount for containerd.sock should have `type: Socket, not `type: File`. A Unix socket is not a plain file.
See: https://kubernetes.io/docs/concepts/storage/volumes/#hostpath

**Comment by clemenko** [comment]
That worked. Works on v1.18.

**Comment by brandond** [comment]
The kubelet probably got more picky in 1.19. It's not something we've changed.
