### ISSUE TITLE
k3s build problem

### ISSUE THREAD

**Issue by jamesxia20181001** [rancher/k3s#238]
According to the K3S REDMAE file，ther are 2 ways to build k3s:
(1)go build -o k3s
src/github.com/rancher/k3s/main.go
-rwxr-xr-x  1 root root **100M** 3月  18 11:18 k3s

(2)make and that will create ./dist/artifacts/k3s
src/github.com/rancher/k3s/cmd/k3s/main.go
-rwxr-xr-x 1 root root  **36M** 3月  14 17:09 k3s

**The size of the two k3s files is very different.**

then I try to build " ./cmd/k3s/main.go" manually according to the same way as ./script/package-cli

- CMD_NAME=dist/artifacts/k3s${BIN_SUFFIX}
- go generate
- LDFLAGS="-X github.com/rancher/k3s/version.Version=$VERSION -w -s"
- STATIC="-extldflags '-static'"
- CGO_ENABLED=0 go build -ldflags "$LDFLAGS $STATIC" -o ${CMD_NAME} ./cmd/k3s/main.go

The build result to a 2.7M k3s, but this k3s is not work normaly.
-rwxrwxr-x 1 root root 2.7M 3月  18 09:02 k3s*
./k3s server
panic: runtime error: index out of range
goroutine 1 [running]:
main.getAssetAndDir(0x81af8bf, 0x14, 0x14, 0x7e, 0xffffffff, 0x8187640)
        /root/k3sroot/src/github.com/rancher/k3s/cmd/k3s/main.go:101 +0x11c
main.extract(0x81af8bf, 0x14, 0x0, 0x0, 0x0, 0x0)
      ...

Cloud you tell me how to buid a 36M size of k3s directly without the full make steps? Thx!

**Comment by erikwilson** [comment]
Hi @jamesxia20181001, please see the build files in `scripts`. The preferred way to build for devs so everything is bundled with k3s is `./scripts/build && ./scripts/package`. Also see Dockerfile.dapper for how the build environment is setup.

**Comment by jamesxia20181001** [comment]
According to your prompt, I understand the reason for my failure because the binddata has a problem and has been resolved. thank you very much!
