### ISSUE TITLE
Deploying Kong Ingress Controller - Pod is not created on one node

### ISSUE THREAD

**Issue by sandhyarme** [rancher/k3s#2387]
**Environmental Info:**
K3s Version:  v1.18.9+k3s1

k3s version v1.18.9+k3s1 (630bebf9)

Node(s) CPU architecture, OS, and Version: 

Master node and worker nodes same output - 
Linux master.local 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

1 master node and 3 worker node cluster on centos 7 (4 VM's)

On master node -
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable traefik --write-kubeconfig-mode=644" INSTALL_K3S_SELINUX_WARN="true" sh -
On worker node -
curl -sfL https://get.k3s.io | INSTALL_K3S_SELINUX_WARN="true" sh -

NAME                        STATUS   ROLES    AGE   VERSION
master.local                Ready    master   17h   v1.18.9+k3s1
build-smartird.local        Ready    <none>   15h   v1.18.9+k3s1
build-smartird.local1       Ready    <none>   15h   v1.18.9+k3s1
sat-master.in.hpecorp.net   Ready    <none>   89m   v1.18.9+k3s1

**Describe the bug:**

Deployed k3s kong ingress controller using below cmd
kubectl apply -f https://bit.ly/kong-ingress-dbless

[root@master ~]# kubectl get all -n kong -o wide
NAME                                READY   STATUS              RESTARTS   AGE   IP          NODE                        NOMINATED NODE   READINESS GATES
pod/svclb-kong-proxy-6r94j          2/2     Running             0          72m   10.42.1.3   build-smartird.local1       <none>           
pod/svclb-kong-proxy-pnrmj          2/2     Running             0          72m   10.42.0.6   master.local                <none>           
pod/svclb-kong-proxy-8vkkk          2/2     Running             0          72m   10.42.3.2   sat-master.in.hpecorp.net   <none>           
pod/ingress-kong-6b599f5547-782s6   2/2     Running             0          72m   10.42.3.3   sat-master.in.hpecorp.net   <none>           
pod/svclb-kong-proxy-ll5wx          0/2     ContainerCreating   0          9s    <none>      build-smartird.local        <none>           

NAME                              TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)                      AGE   SELECTOR
service/kong-validation-webhook   ClusterIP      10.43.218.233   <none>          443/TCP                      72m   app=ingress-kong
service/kong-proxy                LoadBalancer   10.43.168.127   15.213.141.56   80:32303/TCP,443:32581/TCP   72m   app=ingress-kong

NAME                              DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE   CONTAINERS               IMAGES                                                SELECTOR
daemonset.apps/svclb-kong-proxy   4         4         3       4            3           <none>          72m   lb-port-80,lb-port-443   rancher/klipper-lb:v0.1.2,rancher/klipper-lb:v0.1.2   app=svclb-kong-proxy

NAME                           READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS                 IMAGES                                                                                      SELECTOR
deployment.apps/ingress-kong   1/1     1            1           72m   proxy,ingress-controller   kong:2.1,kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:1.0   app=ingress-kong

Container is in creating state.

**Steps To Reproduce:**

- Installed K3s: with 1 master 3 worker node
- deploying kong ingress controller
kubectl apply -f https://bit.ly/kong-ingress-dbless
- Container in creating state.

**Expected behavior:**

Container/pod should be in running state

**Actual behavior:**

Container/pod is in creating state

**Additional context / logs:**

[root@master ~]# kubectl get events -n kong
LAST SEEN   TYPE      REASON                   OBJECT                              MESSAGE
18m         Warning   FailedCreatePodSandBox   pod/svclb-kong-proxy-65kvk          Failed to create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox image "docker.io/rancher/pause:3.1": failed to pull image "docker.io/rancher/pause:3.1": failed to pull and unpack image "docker.io/rancher/pause:3.1": failed to resolve reference "docker.io/rancher/pause:3.1": failed to do request: Head https://registry-1.docker.io/v2/rancher/pause/manifests/3.1: proxyconnect tcp: tls: first record does not look like a TLS handshake
17m         Normal    TaintManagerEviction     pod/ingress-kong-6b599f5547-782s6   Cancelling deletion of Pod kong/ingress-kong-6b599f5547-782s6
15m         Normal    SuccessfulCreate         daemonset/svclb-kong-proxy          Created pod: svclb-kong-proxy-ll5wx
15m         Normal    Scheduled                pod/svclb-kong-proxy-ll5wx          Successfully assigned kong/svclb-kong-proxy-ll5wx to build-smartird.local
99s         Warning   FailedCreatePodSandBox   pod/svclb-kong-proxy-ll5wx          Failed to create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox image "docker.io/rancher/pause:3.1": failed to pull image "docker.io/rancher/pause:3.1": failed to pull and unpack image "docker.io/rancher/pause:3.1": failed to resolve reference "docker.io/rancher/pause:3.1": failed to do request: Head https://registry-1.docker.io/v2/rancher/pause/manifests/3.1: proxyconnect tcp: tls: first record does not look like a TLS handshake

Have checked on the failure node docker url accessible or not using curl -

[root@build-smartird ~]# curl -i  "https://registry-1.docker.io/v2/rancher/pause/manifests/3.1"
HTTP/1.1 200 Connection established

HTTP/1.1 401 Unauthorized
Content-Type: application/json
Docker-Distribution-Api-Version: registry/2.0
Www-Authenticate: Bearer realm="https://auth.docker.io/token",service="registry.docker.io",scope="repository:rancher/pause:pull"
Date: Wed, 14 Oct 2020 08:24:08 GMT
Content-Length: 156
Strict-Transport-Security: max-age=31536000

{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"rancher/pause","Action":"pull"}]}]}

Have disabled firewalld still same issue. Please need your support.

**Comment by brandond** [comment]
>  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox image "docker.io/rancher/pause:3.1": failed to pull image "docker.io/rancher/pause:3.1": failed to pull and unpack image "docker.io/rancher/pause:3.1": failed to resolve reference "docker.io/rancher/pause:3.1": failed to do request: Head https://registry-1.docker.io/v2/rancher/pause/manifests/3.1: proxyconnect tcp: tls: first record does not look like a TLS handshake

This usually indicates that you need to configure the http_proxy/https_proxy/no_proxy environment variables for the k3s service.

**Comment by sandhyarme** [comment]
Current setup was --

vi /etc/systemd/system/k3s-agent.service.env

K3S_URL=https://15.213.141.56:6443
K3S_TOKEN=K107da447e797f9b70bc6d85ea7aa69be50c2b81049900418261a6d0479fac6b3c0::server:ef9c02204042fc74274be6003334c05d
NO_PROXY=http://web-proxy.in.hpecorp.net:8080
http_proxy=http://web-proxy.in.hpecorp.net:8080
https_proxy=http://web-proxy.in.hpecorp.net:8080
**HTTPS_PROXY=https://web-proxy.in.hpecorp.net:8080**
no_proxy=http://web-proxy.in.hpecorp.net:8080
HTTP_PROXY=http://web-proxy.in.hpecorp.net:8080

As suggested 
HTTPS_PROXY=https://web-proxy.in.hpecorp.net:8080 
changed to
HTTPS_PROXY=http://web-proxy.in.hpecorp.net:8080

restarted k3s-agent.service
on master node - kubectl get all -n kong
pod was in creating state, now its in running state..

[root@master ~]# kubectl get all -n kong
NAME                                READY   STATUS    RESTARTS   AGE
pod/svclb-kong-proxy-6r94j          2/2     Running   0          148m
pod/svclb-kong-proxy-pnrmj          2/2     Running   0          148m
pod/svclb-kong-proxy-8vkkk          2/2     Running   0          148m
pod/ingress-kong-6b599f5547-782s6   2/2     Running   0          148m
pod/svclb-kong-proxy-4hqtk          2/2     Running   0          52m

NAME                              TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)                      AGE
service/kong-validation-webhook   ClusterIP      10.43.218.233   <none>          443/TCP                      148m
service/kong-proxy                LoadBalancer   10.43.168.127   15.213.141.56   80:32303/TCP,443:32581/TCP   148m

NAME                              DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/svclb-kong-proxy   4         4         4       4            4           <none>          148m

NAME                           READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/ingress-kong   1/1     1            1           148m

NAME                                      DESIRED   CURRENT   READY   AGE
replicaset.apps/ingress-kong-6b599f5547   1         1         1       148m


Thanks a lot for resolving the issue.
