### ISSUE TITLE
Cluster with embedded etcd does not initialize (proxy issue)

### ISSUE THREAD

**Issue by betweenclouds** [rancher/k3s#2388]
**Environmental Info:**
k3s version v1.19.2+k3s1 (d38505b1)

Node(s) CPU architecture, OS, and Version: 
Ubuntu 18.04
Linux ids-rnc-k3s-04 4.15.0-118-generic #119-Ubuntu SMP Tue Sep 8 12:30:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
3 nodes with embedded etcd

**Describe the bug:**
first node starts without issues with command:
`curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL=latest sh -s - --cluster-init --token mytoken `

second don't get over "[INFO]  systemd: Starting k3s" with command:
`curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL=latest sh -s - --server https://172.31.24.118:6443 --token mytoken`

Error on first node:
```
Oct 14 09:29:28 ids-rnc-k3s-04 k3s[5360]: health check for peer 681c415795beb90c could not connect: Forbidden
Oct 14 09:29:31 ids-rnc-k3s-04 k3s[5360]: failed to reach the peerURL(https://172.31.24.119:2380) of member 681c415795beb90c (Get "https://172.31.24.119:2380/version": Forbidden)
Oct 14 09:29:31 ids-rnc-k3s-04 k3s[5360]: cannot get the version of member 681c415795beb90c (Get "https://172.31.24.119:2380/version": Forbidden)
```
error on second node:
```
Oct 14 09:30:27 ids-rnc-k3s-05 k3s[2822]: WARNING: 2020/10/14 09:30:27 grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused". Reconnecting...
Oct 14 09:30:28 ids-rnc-k3s-05 k3s[2822]: {"level":"warn","ts":"2020-10-14T09:30:28.134Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"passthrough:///https://127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}
Oct 14 09:30:28 ids-rnc-k3s-05 k3s[2822]: time="2020-10-14T09:30:28.135006852Z" level=info msg="Failed to test data store connection: context deadline exceeded"
```

**Steps To Reproduce:**

- install ubuntu 18.04 cloud image on 3 vmware VMs
- set http(s)_proxy and no_proxy ("0.0.0.0,127.0.0.0/8,10.0.0.0/8,192.168.0.0/16,172.16.0.0/12,129.132.0.0/16,localhost")
- Installed K3s: latest, flags see above

 

**Expected behavior:**
Startup of the cluster with embedded etcd

**Actual behavior:**
cluster could not initialize

>

**Comment by betweenclouds** [comment]
stable channel with dqlite works on the same environment (omitted: "INSTALL_K3S_CHANNEL=latest")

**Comment by brandond** [comment]
Are ports 2379 and 2380 open between the two servers?

**Comment by betweenclouds** [comment]
Yes I opened the whole net on iptables on all nodes:
```
iptables -A INPUT -p tcp -s 172.31.24.112/28 -j ACCEPT
iptables -A OUTPUT -p tcp -d  172.31.24.112/28 -j ACCEPT
```
Yes we use a proxy:
```
https_proxy=http://proxy.ourdomain.corp:3128
http_proxy=http://proxy.ourdomain.corp:3128
no_proxy=0.0.0.0,127.0.0.0/8,10.0.0.0/8,192.168.0.0/16,172.16.0.0/12,localhost
```

If I do a curl local on the second node I get a connection refused too:
```
curl https://localhost:2380/version
curl: (7) Failed to connect to localhost port 2380: Connection refused
```
This should work, right?

**Comment by betweenclouds** [comment]
it really seems to be a proxy issue. If I disable the proxy on both nodes and start it works:
```
export http_proxy=""
export https_proxy=""

K3S_TOKEN=mytoken k3s server --server https://172.31.24.118:6443
```
Is there a IP range or name I missed in the no_proxy?

**Comment by betweenclouds** [comment]
If I delete the proxy in /etc/systemd/system/k3s.service.env the cluster succeeds, but k8s cannot install the container because of the missing proxy.
```
curl -sfL https://get.k3s.io | INSTALL_K3S_SKIP_START=true INSTALL_K3S_CHANNEL=latest sh -s - --cluster-init --token mytoken
echo "" > /etc/systemd/system/k3s.service.env
service k3s start

kubectl get nodes,pod -A
NAME                  STATUS   ROLES         AGE     VERSION
node/ids-rnc-k3s-04   Ready    etcd,master   10m     v1.19.2+k3s1
node/ids-rnc-k3s-05   Ready    etcd,master   7m11s   v1.19.2+k3s1
node/ids-rnc-k3s-06   Ready    etcd,master   6m33s   v1.19.2+k3s1

NAMESPACE     NAME                                         READY   STATUS              RESTARTS   AGE
kube-system   pod/coredns-66c464876b-xvrdn                 0/1     ContainerCreating   0          9m51s
kube-system   pod/helm-install-traefik-ndpxb               0/1     ContainerCreating   0          9m51s
kube-system   pod/local-path-provisioner-7ff9579c6-sm44z   0/1     ContainerCreating   0          9m51s
kube-system   pod/metrics-server-7b4f8b595-5f62k           0/1     ContainerCreating   0          9m51s
```

**Comment by brandond** [comment]
Normally you would also put your internal DNS zone in the no_proxy list, since no_proxy's IP matching logic only works if you're specifying a bare IP address in the URL - it doesn't exclude things that RESOLVE to those ranges. Since you're using short hostnames instead of FQDNs your life is a little more difficult - can you try adding all your node hostnames to the no_proxy list?

**Comment by betweenclouds** [comment]
Sometimes whole IP ranges are accepted as no_proxy, sometimes not. I took this from here:
https://rancher.com/docs/rancher/v2.x/en/installation/other-installation-methods/behind-proxy/launch-kubernetes/

I tried to add each hostname and each IP from the nodes to the no_proxy with the same result.
Then I **changed the no_proxy to uppercase NO_PROXY variable name** and everything works as expected. Even with just the IP ranges:
`NO_PROXY="0.0.0.0,127.0.0.0/8,10.0.0.0/8,192.168.0.0/16,172.16.0.0/12,localhost,ourdomain.tld"`

Thank you for helping me with this!

**Comment by brandond** [comment]
Yes, sometimes netmasks are accepted, sometimes they're not. The proxy dialer logic ALWAYS matches against the host portion of the URI though - if the host is an IP address it will be matched against CIDR blocks (if the library supports it), if it's a hostname it's matched against hostname or domain patterns.

Use of uppercase or lowercase environment variables is another thing that varies by library. I generally set all the proxy vars in both upper and lowercase, just to get the best coverage.
