### ISSUE TITLE
Accessing kong via cluster ip - Service Unavailable error

### ISSUE THREAD

**Issue by sandhyarme** [rancher/k3s#2389]
**Environmental Info:**
K3s Version: v1.18.9+k3s1

Node(s) CPU architecture, OS, and Version: 

Linux master.local 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

1 master and 3 worker nodes on 4 centos 7 VM's
[root@master ~]# kubectl get nodes
NAME                        STATUS   ROLES    AGE     VERSION
build-smartird.local1       Ready    <none>   18h     v1.18.9+k3s1
master.local                Ready    master   20h     v1.18.9+k3s1
sat-master.in.hpecorp.net   Ready    <none>   4h43m   v1.18.9+k3s1
build-smartird.local        Ready    <none>   18h     v1.18.9+k3s1

**Describe the bug:**

Unable to access kong via cluster ip through any node
curl -i http://$PROXY_IP/
service unavailable error

**Steps To Reproduce:**

- Installed K3s: 
Deployed kong ingress
kubectl apply -f https://bit.ly/kong-ingress-dbless
export PROXY_IP=$(kubectl get -o jsonpath="{.spec.clusterIP}" service -n kong kong-proxy)
curl -i http://$PROXY_IP/
service unavailable error

**Expected behavior:**

404 page not found

**Actual behavior:**

503 service unavailable

**Additional context / logs:**

[root@master ~]# kubectl get all -n kong
NAME                                READY   STATUS    RESTARTS   AGE
pod/svclb-kong-proxy-6r94j          2/2     Running   0          4h42m
pod/svclb-kong-proxy-pnrmj          2/2     Running   0          4h42m
pod/svclb-kong-proxy-8vkkk          2/2     Running   0          4h42m
pod/ingress-kong-6b599f5547-782s6   2/2     Running   0          4h42m
pod/svclb-kong-proxy-4hqtk          2/2     Running   0          3h5m

NAME                              TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)                      AGE
service/kong-validation-webhook   ClusterIP      10.43.218.233   <none>          443/TCP                      4h42m
service/kong-proxy                LoadBalancer   10.43.168.127   15.213.141.56   80:32303/TCP,443:32581/TCP   4h42m

NAME                              DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/svclb-kong-proxy   4         4         4       4            4           <none>          4h42m

NAME                           READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/ingress-kong   1/1     1            1           4h42m

NAME                                      DESIRED   CURRENT   READY   AGE
replicaset.apps/ingress-kong-6b599f5547   1         1         1       4h42m

Accessing kong via cluster ip

[root@master ~]# curl -i http://10.43.168.127
curlHTTP/1.1 503 Service Unavailable
Cache-Control: no-cache
Pragma: no-cache
Content-Type: text/html; charset=utf-8
Proxy-Connection: close
Connection: close
Content-Length: 732

<HTML><HEAD>
<TITLE>Network Error</TITLE>
</HEAD>

we can access kong via external ip

[root@master ~]# curl -i http://15.213.141.56
HTTP/1.1 404 Not Found
Date: Wed, 14 Oct 2020 11:39:05 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 48
X-Kong-Response-Latency: 0
Server: kong/2.1.4
Proxy-Connection: Keep-Alive
Connection: Keep-Alive

{"message":"no Route matched with those values"}

Please need your support why unable to access kong via cluster ip

**Comment by brandond** [comment]
> {"message":"no Route matched with those values"}

You don't have an ingress that matches the request you're sending.

**Comment by sandhyarme** [comment]
The current k3s env variables are setup as below..

cd /etc/systemd/system
[root@master system]# cat k3s.service.env
NO_PROXY=http://web-proxy.in.hpecorp.net:8080
http_proxy=http://web-proxy.in.hpecorp.net:8080
https_proxy=http://web-proxy.in.hpecorp.net:8080
HTTPS_PROXY=http://web-proxy.in.hpecorp.net:8080
no_proxy=http://web-proxy.in.hpecorp.net:8080
HTTP_PROXY=http://web-proxy.in.hpecorp.net:8080 

We need to change here 
NO_PROXY/no_proxy=http://10.43.168.127:80 

Is this the change supposed to do ?

**Comment by brandond** [comment]
Please read the bit I included above regarding the correct values for the NO_PROXY variable.

**Comment by sandhyarme** [comment]
I have updated NO_PROXY/no_proxy=localhost,127.0.0.1,0.0.0.0,10.43.168.127:80 , but still unable to access cluster ip its same issue.

[root@master system]# cat k3s.service.env
NO_PROXY=localhost,127.0.0.1,0.0.0.0,10.43.168.127:80
http_proxy=http://web-proxy.in.hpecorp.net:8080
https_proxy=http://web-proxy.in.hpecorp.net:8080
HTTPS_PROXY=http://web-proxy.in.hpecorp.net:8080
no_proxy=localhost,127.0.0.1,0.0.0.0,10.43.168.127:80
HTTP_PROXY=http://web-proxy.in.hpecorp.net:8080

**Comment by brandond** [comment]
Try leaving out the :80 - I'm not sure if curl supports this. Also, if this wasn't clear - you need to be setting up the proxy for your shell (where you're running your curl tests) NOT the k3s environment. Curl needs to know not to go through the proxy to access your cluster.

Either way, k3s and kong appear to be working properly - you're just running into environment-specific OS configuration issues.

**Comment by sandhyarme** [comment]
Thanks Brandond.. Able to access cluster ip...

[root@master system]# export NO_PROXY=10.43.74.111
[root@master system]# export no_proxy=10.43.74.111
[root@master system]# echo NO_PROXY
NO_PROXY
[root@master system]# echo $NO_PROXY
10.43.74.111
[root@master system]# curl -i http://$PROXY_IP/
HTTP/1.1 404 Not Found
Date: Mon, 19 Oct 2020 19:45:19 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
Content-Length: 48
X-Kong-Response-Latency: 1
Server: kong/2.1.4

{"message":"no Route matched with those values"}
