### ISSUE TITLE
k3s and nginx conflicts on port 80 for IPv4

### ISSUE THREAD

**Issue by AntoineNGUYEN31** [rancher/k3s#2403]
**Environmental Info:**
K3s Version: 
1.19

Node(s) CPU architecture, OS, and Version: 
arm64

Cluster Configuration:
1 node

**Describe the bug:**

**Steps To Reproduce:**
nginx is prelimiarly installed using 
```
apt install nginx
```
Welcome message of nginx can be seen by
```
curl localhost
```
Proceed the installation of k3s using
```
curl -sfL https://get.k3s.io | sh -
```
Wait a few minutes, then we will get 404 message when doing
```
curl localhost
```
Knowing that port 80 is binded to nginx by verifying
```
netstat -ntlp
```
And IPv6 is still working (nginx.conf by default listens on IPv4 and IPv6)
```
curl http://[::1]
```
- Installed K3s:  as described above with Raspberry pi 4 with ubuntu 20.04

**Expected behavior:**
As k3s not using port 80, no interference should exist. It works nginx and microk8s this way.

**Actual behavior:**
nginx cannot work on port 80 with IPv4

**Additional context / logs:**
n/a

**Comment by brandond** [comment]
The traefik ingress built in to k3s listens on port 80 and 443. If you for some reason want to deploy a non-containerized web server on your k3s host, you should disable traefik or configure the service to use different ports.

Can I ask why you're trying to install a web server on your k3s host, instead of deploying it as a Kubernetes workload?

**Comment by AntoineNGUYEN31** [comment]
Ok, thank you for this information. It is wierd that netstat does not detect that 80 and 443 are bound to traefik. Can you shade me a light on how to customize traefik built in k3s.
For my case, I am working on mixed deployment (containerized and classic) with nginx as proxy that linked to 1 single domain for multiple micro services, e.g. example.com/app1, example.com/app2, etc.

**Comment by brandond** [comment]
That request routing stuff is exactly what the traefik ingress does. You might look at using the ingress instead of standalone nginx.

Traefik itself is not listening on 80 and 443, but there is a Service on 80 and 443; out of the box these are bound to node ports by ServiceLB - you can find the docs here: https://rancher.com/docs/k3s/latest/en/networking/#traefik-ingress-controller

**Comment by AntoineNGUYEN31** [comment]
Thank you for your helps.

**Comment by yifeikong** [comment]
I have the exact same problem. This is totally weird, how can traefik/servicelb hijack port 80 without any error? Can two process listen on the same port?

**Comment by yifeikong** [comment]
I believe this might be possible via `SO_REUSEPORT`[1]? This hijacking/overtaking port behavior should be mentioned in the docs.

1. https://lwn.net/Articles/542629/

**Comment by brandond** [comment]
Servicelb is able to 'hijack' the port because it doesn't actually listen on the ports; it sets up iptables rules to redirect traffic to the service's pods. If you don't want this behavior, you can disable servicelb, traefik, or both.

**Comment by pfisterer** [comment]
If this helps somebody, I've followed the docs (https://rancher.com/docs/k3s/latest/en/helm/#customizing-packaged-components-with-helmchartconfig) and changed traefik's default ports `80`&rarr; `8088`and `443` &rarr; `8443` using the [Helm chart's values file](https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml) as a reference.

Just be aware, that this needs to be done before installing k3s. This is what I did:

```bash
# Create directory
mkdir -p /var/lib/rancher/k3s/server/manifests/

# Create traefik-config.yaml
cat <<EOF > /var/lib/rancher/k3s/server/manifests/traefik-config.yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
       web:
         exposedPort: 8088

       websecure:
         port: 8443
         expose: true
         exposedPort: 8443

EOF

# Install k3s
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--https-listen-port 7443" sh -
```

**Comment by linsmalldragon** [comment]
> If this helps somebody, I've followed the docs (https://rancher.com/docs/k3s/latest/en/helm/#customizing-packaged-components-with-helmchartconfig) and changed traefik's default ports `80`→ `8088`and `443` → `8443` using the [Helm chart's values file](https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml) as a reference.
> 
> Just be aware, that this needs to be done before installing k3s. This is what I did:
> 
> ```shell
> # Create directory
> mkdir -p /var/lib/rancher/k3s/server/manifests/
> 
> # Create traefik-config.yaml
> cat <<EOF > /var/lib/rancher/k3s/server/manifests/traefik-config.yaml
> apiVersion: helm.cattle.io/v1
> kind: HelmChartConfig
> metadata:
>   name: traefik
>   namespace: kube-system
> spec:
>   valuesContent: |-
>     ports:
>        web:
>          exposedPort: 8088
> 
>        websecure:
>          port: 8443
>          expose: true
>          exposedPort: 8443
> 
> EOF
> 
> # Install k3s
> curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--https-listen-port 7443" sh -
> ```

Thank you guy. It's helpful
