### ISSUE TITLE
Add load test results to docs content

### ISSUE THREAD

**Issue by brandond** [rancher/k3s#2412]
Need to add some baseline perf documentation, based on the initial writeup at https://gist.github.com/brandond/32f8c4846b9f71d6c145c26afced7ed8

Would like to add a couple things to the existing info:
* Warnings about burstable instance types / CPU credit exhaustion (runs great until you don't have burstable credits)
* Additional resource figures for same nodes running Rancher 2.5 monitoring the local cluster

**Comment by davidnuzik** [comment]
Docs PR: https://github.com/rancher/docs/pull/2836

**Comment by davidnuzik** [comment]
Looks like this is merged in. Closing.
