### ISSUE TITLE
how to start the newest version

### ISSUE THREAD

**Issue by hotsmile** [rancher/k3s#242]
Thanks for helping us to improve k3s! We welcome all feature requests. At this stage, we are also looking for help in testing/QAing issues. Once we've addressed your feature request, we'll ping you in the comments to see if you can verify the change. We'll give you details on what version can be used to test the change. Additionally, if you are interested in testing other fixes or feature requests that you ***didn't*** report, look for the issues with the status/to-test label. You can pick any of these up for verification. ***You can delete this message portion of the bug report.***

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hotsmile** [comment]
how to use the newest version ,the readme.md not support.

**Comment by erikwilson** [comment]
@hotsmile there may be some flags that are not documented, can you elaborate on the issue?

**Comment by milosonator** [comment]
@hotsmile Please provide some more details otherwise no one can help you.

**Comment by davidnuzik** [comment]
Please fill out details in the issue or let us know the issue you are running into. To start the latest version of k3s, assuming you are just setting up one node to act as the server and agent you can simply run:
`curl -sfL https://get.k3s.io | sh -`
See our documentation for more info: https://rancher.com/docs/k3s/latest/en/quick-start/

We can re-open the issue if you need anything else; please let us know.
