### ISSUE TITLE
Upgrading from v1.18.9+k3s1 to v1.19.3+k3s1 fails on btrfs

### ISSUE THREAD

**Issue by sseneca** [rancher/k3s#2422]
**Environmental Info:**
K3s Version: v1.18.9+k3s1 (trying to go to v1.19.3+k3s1)

Node(s) CPU architecture, OS, and Version:
`Linux sserver 5.4.69-gnu-1-lts #1 SMP Sun, 04 Oct 2020 20:19:52 +0000 x86_64 GNU/Linux`

I think this is important: I'm running btrfs, in RAID 1.

Cluster Configuration:

1 master node only.

**Describe the bug:**

When I try to upgrade k3s, it never completes. A bunch of errors appear in the logs, most notably:

```
Oct 23 10:39:03 sserver k3s[2828239]: F1023 10:39:03.536403 2828239 kubelet.go:1296] Failed to start ContainerManager failed to get rootfs info: failed to get device for dir "/var/lib/kubelet": could not find device with major: 0, minor: 46 in cached partitions map
```

What follows is impressively long (~1600 lines long), the start of which looks like this:

```
Oct 23 10:41:34 sserver k3s[2830467]: goroutine 30629 [running]:
Oct 23 10:41:34 sserver k3s[2830467]: github.com/rancher/k3s/vendor/k8s.io/klog/v2.stacks(0xc000010001, 0xc011152400, 0xe4, 0x1fa)
Oct 23 10:41:34 sserver k3s[2830467]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:996 +0xb9
Oct 23 10:41:34 sserver k3s[2830467]: github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).output(0x6e952a0, 0xc000000003, 0x0, 0x0, 0xc0092dfc00, 0x6b4d561, 0xa, 0x510, 0x0)
Oct 23 10:41:34 sserver k3s[2830467]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:945 +0x191
Oct 23 10:41:34 sserver k3s[2830467]: github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).printf(0x6e952a0, 0xc000000003, 0x0, 0x0, 0x451eadb, 0x23, 0xc00ba71cb0, 0x1, 0x1)
Oct 23 10:41:34 sserver k3s[2830467]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:733 +0x17a
Oct 23 10:41:34 sserver k3s[2830467]: github.com/rancher/k3s/vendor/k8s.io/klog/v2.Fatalf(...)
Oct 23 10:41:34 sserver k3s[2830467]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:1456
Oct 23 10:41:34 sserver k3s[2830467]: github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubelet.(*Kubelet).initializeRuntimeDependentModules(0xc003fb8a80)
Oct 23 10:41:34 sserver k3s[2830467]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1296 +0x385 
Oct 23 10:41:34 sserver k3s[2830467]: sync.(*Once).doSlow(0xc003fb92b8, 0xc00b8fbdd0)
Oct 23 10:41:34 sserver k3s[2830467]:         /usr/local/go/src/sync/once.go:66 +0xec
Oct 23 10:41:34 sserver k3s[2830467]: sync.(*Once).Do(...)
```

**Steps To Reproduce:**

I installed k3s via the script (`curl -sfL https://get.k3s.io | sh -`). This happens either when using the auto-update mechanism or via running `curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL=latest sh -`.

**Expected behavior:**
It should upgrade.

**Actual behavior:**
Endless loop where k3s never upgrades. Binary has to be manually replaced with 1.18, or `curl -sfL https://get.k3s.io | sh -` works. Actual services it hosts remain up, but I can't run `kubectl` (either complains about being "unauthorised" or the server not being able to handle requests).

**Additional context / logs:**
#471 looks similar, parrticularly because I'm running Parabola which is similar to Arch. Note however I'm not using k3d. ~#48 is about brfs and could also be related.~ (Apologies, I meant https://github.com/rancher/k3d/pull/48, which is about k3d. Nevermind.)

**Comment by brandond** [comment]
Unfortunately this is deep in the kubelet cadvisor code, which means it's probably something that was changed upstream, not in k3s.

It looks like there's some special handling for btrfs just above the code that's producing this error here: https://github.com/rancher/k3s/blob/master/vendor/github.com/google/cadvisor/fs/fs.go#L570 - that was apparently added to fix https://github.com/kubernetes/kubernetes/issues/47046 and https://github.com/kubernetes/kubernetes/issues/65204 but it doesn't seem to handling how you have your system configured.

**Comment by sseneca** [comment]
Thanks for the response. I opened an issue upstream: https://github.com/kubernetes/kubernetes/issues/95826

I'll close this issue and continue over there (feel free to re-open if this should be tracked here too).
