### ISSUE TITLE
svclb crashloops on rhel8 with selinux enabled

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/k3s#2424]
**Environmental Info:**
K3s Version: 
k3s -v
k3s version v1.19.3+k3s1 (974ad30b)

Install script:
https://raw.githubusercontent.com/rancher/k3s/c9af317ed2310d276fab3e6c6e01ca7112902941/install.sh
k3s-selinux-0.2-1.el7_8.noarch

Node(s) CPU architecture, OS, and Version: 
RHEL 8.2

Cluster Configuration:
Single node cluster

**Describe the bug:**
With selinux enabled, svclb crashloops on rhel8
kube-system   svclb-traefik-8m7zp                      0/2     CrashLoopBackOff   16         17m

**Steps To Reproduce:**
Install k3s on single node on rhel8

**Expected behavior:**
Cluster should be up and all pods should be Running

**Actual behavior:**
svclb crashloops

**Additional context / logs:**
```
kubectl logs -n kube-system svclb-traefik-8m7zp lb-port-80
+ trap exit TERM INT
/usr/bin/entry: line 6: can't create /proc/sys/net/ipv4/ip_forward: Read-only file system
+ echo 1
+ true
+ cat /proc/sys/net/ipv4/ip_forward
+ '[' 1 '!=' 1 ]
+ iptables -t nat -I PREROUTING '!' -s 10.43.86.88/32 -p TCP --dport 80 -j DNAT --to 10.43.86.88:80
iptables v1.6.2: can't initialize iptables table `nat': Permission denied
Perhaps iptables or your kernel needs to be upgraded.
```
Audit logs:
```
type=AVC msg=audit(1603491099.794:4209): avc:  denied  { module_request } for  pid=17382 comm="iptables" kmod="iptable_nat" scontext=system_u:system_r:container_t:s0:c162,c460 tcontext=system_u:system_r:kernel_t:s0 tclass=system permissive=0
```

**Comment by Oats87** [comment]
@ShylajaDevadiga Was this reproduced on CentOS 8.x as well or just RHEL?

**Comment by Oats87** [comment]
@ShylajaDevadiga I cannot reproduce this on a RHEL 8.2 system, both in our internal testing environment or in AWS. All I am doing is:
```
curl -sfL https://raw.githubusercontent.com/rancher/k3s/c9af317ed2310d276fab3e6c6e01ca7112902941/install.sh | INSTALL_K3S_CHANNEL=latest sh -
```

Am I missing a step here?

**Comment by ShylajaDevadiga** [comment]
@Oats87 As discussed it is reproducible with selinux enabled, passing --selinux flag

**Comment by Oats87** [comment]
This is reproduced when invoking `./install.sh --selinux`

Need to discuss ways to work around this. I'm not sure we actually want to grant the lb container access to `module_request` -- we could maybe exec a prestart hook in the unit file that would `modprobe iptable_nat`

**Comment by Oats87** [comment]
I just pushed an enhancement to the `install.sh` script to add a third `modprobe` at the start of `k3s` for `iptable_nat` which should work around this issue.

**Comment by ShylajaDevadiga** [comment]
Validated with the below commits with the fix. No fails in svclb.
```
wget https://raw.githubusercontent.com/rancher/k3s/c8d8848e91415068f0d9364a259fab6b8fc149a3/install.sh
chmod +x install.sh
INSTALL_K3S_COMMIT=55d7012d058c795e1cff8ebff2fe333042b6a228 ./install.sh --selinux
```

**Comment by Oats87** [comment]
https://github.com/rancher/k3s/pull/2408

**Comment by ShylajaDevadiga** [comment]
Closing issue as validated using commits
```
[root@ip-172-31-39-254 ~]# k3s -v
k3s version v1.19.3+k3s-55d7012d (55d7012d)
[root@ip-172-31-39-254 ~]# kubectl get nodes
NAME                                          STATUS   ROLES    AGE   VERSION
ip-172-31-39-254.us-east-2.compute.internal   Ready    master   98s   v1.19.3+k3s-55d7012d
[root@ip-172-31-39-254 ~]# kubectl get pods -A|grep svclb
kube-system   svclb-traefik-v5lb6                      2/2     Running     0          70s
[root@ip-172-31-39-254 ~]# cat /var/lib/rancher/k3s/agent/etc/containerd/config.toml |grep selinux
  enable_selinux = true
```
