### ISSUE TITLE
Failed to pull image from "Private registry" x509: certificate is not valid for any names, but wanted to match traefik.local

### ISSUE THREAD

**Issue by zukko78** [rancher/k3s#2429]
**Environmental Info:**
K3s Version: k3s version v1.19.3+k3s1 (974ad30b)
                      crictl version v1.19.0-k3s1

Node(s) CPU architecture, OS, and Version: 

3 vagrant nodes, 1st node - traefik LB/Private docker registry <-> 2nd - Kubemaster1 <-> 3rd - Kubenode1
Cluster Configuration:

1 master, 1 worker
**Describe the bug:**

The problem is that even though the registry.yaml is in accordance to the manual I can pull docker images from a private insecure registry but kublet can't.

**Steps To Reproduce:**

- Installed K3s: 
Master:
curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL=latest sh -s - server --cluster-init --tls-san $(hostname) --bind-address=${current_ip} --write-kubeconfig-mode 644 --advertise-address=${current_ip} --node-ip=${current_ip} --flannel-iface=enp0s8 --no-deploy=traefik
Node:
curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL=latest sh -s - agent --server https://kubemaster1:6443 --token-file /tmp/token --node-ip=${current_ip} --flannel-iface=enp0s8

**Expected behavior:**

the image is pulled

**Actual behavior:**

kubectl run pingtest4 --image=traefik.local:5000/busybox:latest --replicas=3 -- sleep infinity
Describe:
Events:
  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  19s               default-scheduler  Successfully assigned default/pingtest4 to kubenode1
  Normal   BackOff    18s               kubelet            Back-off pulling image "traefik.local:5000/busybox:latest"
  Warning  Failed     18s               kubelet            Error: ImagePullBackOff
  Normal   Pulling    7s (x2 over 18s)  kubelet            Pulling image "traefik.local:5000/busybox:latest"
  Warning  Failed     7s (x2 over 18s)  kubelet            **Failed to pull image "traefik.local:5000/busybox:latest": rpc error: code = Unknown desc = failed to pull and unpack image "traefik.local:5000/busybox:latest": failed to resolve reference "traefik.local:5000/busybox:latest": failed to do request: Head "https://traefik.local:5000/v2/busybox/manifests/latest": x509: certificate is not valid for any names, but wanted to match traefik.local**
  Warning  Failed     7s (x2 over 18s)  kubelet            Error: ErrImagePull
**Additional context / logs:**

root@kubemaster1:~# crictl pull traefik.local:5000/busybox:latest
Image is up to date for sha256:f0b02e9d092d905d0d87a8455a1ae3e9bb47b4aa3dc125125ca5cd10d6441c9f

root@kubemaster1:~# crictl info
{
  "status": {
    "conditions": [
      {
        "type": "RuntimeReady",
        "status": true,
        "reason": "",
        "message": ""
      },
      {
        "type": "NetworkReady",
        "status": true,
        "reason": "",
        "message": ""
      }
    ]
  },
  "cniconfig": {
    "PluginDirs": [
      "/var/lib/rancher/k3s/data/3614aa17e3d63be037903fc568871b78a474a16399842313dad1432a89ad6981/bin"
    ],
    "PluginConfDir": "/var/lib/rancher/k3s/agent/etc/cni/net.d",
    "PluginMaxConfNum": 1,
    "Prefix": "eth",
    "Networks": [
      {
        "Config": {
          "Name": "cni-loopback",
          "CNIVersion": "0.3.1",
          "Plugins": [
            {
              "Network": {
                "type": "loopback",
                "ipam": {},
                "dns": {}
              },
              "Source": "{\"type\":\"loopback\"}"
            }
          ],
          "Source": "{\n\"cniVersion\": \"0.3.1\",\n\"name\": \"cni-loopback\",\n\"plugins\": [{\n  \"type\": \"loopback\"\n}]\n}"
        },
        "IFName": "lo"
      },
      {
        "Config": {
          "Name": "cbr0",
          "CNIVersion": "0.3.1",
          "Plugins": [
            {
              "Network": {
                "type": "flannel",
                "ipam": {},
                "dns": {}
              },
              "Source": "{\"delegate\":{\"forceAddress\":true,\"hairpinMode\":true,\"isDefaultGateway\":true},\"type\":\"flannel\"}"
            },
            {
              "Network": {
                "type": "portmap",
                "capabilities": {
                  "portMappings": true
                },
                "ipam": {},
                "dns": {}
              },
              "Source": "{\"capabilities\":{\"portMappings\":true},\"type\":\"portmap\"}"
            }
          ],
          "Source": "{\n  \"name\":\"cbr0\",\n  \"cniVersion\":\"0.3.1\",\n  \"plugins\":[\n    {\n      \"type\":\"flannel\",\n      \"delegate\":{\n        \"hairpinMode\":true,\n        \"forceAddress\":true,\n        \"isDefaultGateway\":true\n      }\n    },\n    {\n      \"type\":\"portmap\",\n      \"capabilities\":{\n        \"portMappings\":true\n      }\n    }\n  ]\n}\n"
        },
        "IFName": "eth0"
      }
    ]
  },
  "config": {
    "containerd": {
      "snapshotter": "overlayfs",
      "defaultRuntimeName": "runc",
      "defaultRuntime": {
        "runtimeType": "",
        "runtimeEngine": "",
        "PodAnnotations": null,
        "ContainerAnnotations": null,
        "runtimeRoot": "",
        "options": null,
        "privileged_without_host_devices": false,
        "baseRuntimeSpec": ""
      },
      "untrustedWorkloadRuntime": {
        "runtimeType": "",
        "runtimeEngine": "",
        "PodAnnotations": null,
        "ContainerAnnotations": null,
        "runtimeRoot": "",
        "options": null,
        "privileged_without_host_devices": false,
        "baseRuntimeSpec": ""
      },
      "runtimes": {
        "runc": {
          "runtimeType": "io.containerd.runc.v2",
          "runtimeEngine": "",
          "PodAnnotations": null,
          "ContainerAnnotations": null,
          "runtimeRoot": "",
          "options": null,
          "privileged_without_host_devices": false,
          "baseRuntimeSpec": ""
        }
      },
      "noPivot": false,
      "disableSnapshotAnnotations": false,
      "discardUnpackedLayers": false
    },
    "cni": {
      "binDir": "/var/lib/rancher/k3s/data/3614aa17e3d63be037903fc568871b78a474a16399842313dad1432a89ad6981/bin",
      "confDir": "/var/lib/rancher/k3s/agent/etc/cni/net.d",
      "maxConfNum": 1,
      "confTemplate": ""
    },
    "registry": {
      "mirrors": {
        "docker.io": {
          "endpoint": [
            "https://registry-1.docker.io"
          ]
        },
        "traefik.local": {
          "endpoint": [
            "https://traefik.local:5000"
          ]
        }
      },
      "configs": {
        "traefik.local:5000": {
          "auth": {
            "username": "admin",
            "password": "admin",
            "auth": "",
            "identitytoken": ""
          },
          "tls": {
            "insecure_skip_verify": true,
            "caFile": "",
            "certFile": "",
            "keyFile": ""
          }
        }
      },
      "auths": null,
      "headers": null
    },
    "imageDecryption": {
      "keyModel": ""
    },
    "disableTCPService": true,
    "streamServerAddress": "127.0.0.1",
    "streamServerPort": "10010",
    "streamIdleTimeout": "4h0m0s",
    "enableSelinux": false,
    "selinuxCategoryRange": 1024,
    "sandboxImage": "docker.io/rancher/pause:3.1",
    "statsCollectPeriod": 10,
    "systemdCgroup": false,
    "enableTLSStreaming": false,
    "x509KeyPairStreaming": {
      "tlsCertFile": "",
      "tlsKeyFile": ""
    },
    "maxContainerLogSize": 16384,
    "disableCgroup": false,
    "disableApparmor": false,
    "restrictOOMScoreAdj": false,
    "maxConcurrentDownloads": 3,
    "disableProcMount": false,
    "unsetSeccompProfile": "",
    "tolerateMissingHugetlbController": true,
    "disableHugetlbController": true,
    "ignoreImageDefinedVolumes": false,
    "containerdRootDir": "/var/lib/rancher/k3s/agent/containerd",
    "containerdEndpoint": "/run/k3s/containerd/containerd.sock",
    "rootDir": "/var/lib/rancher/k3s/agent/containerd/io.containerd.grpc.v1.cri",
    "stateDir": "/run/k3s/containerd/io.containerd.grpc.v1.cri"
  },
  "golang": "go1.15.2",
  "lastCNILoadStatus": "OK"
}

**Comment by zukko78** [comment]
Private registry IP accessible from the k3s cluster

root@kubemaster1:~# kubectl exec -it pingtest sh
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
/ # ping traefik.local
PING traefik.local (10.0.0.30): 56 data bytes
64 bytes from 10.0.0.30: seq=0 ttl=63 time=0.469 ms
64 bytes from 10.0.0.30: seq=1 ttl=63 time=0.548 ms
^C
--- traefik.local ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.469/0.508/0.548 ms

**Comment by zukko78** [comment]
root@kubemaster1:~# cat /etc/rancher/k3s/registries.yaml 
mirrors:
  traefik.local:
    endpoint:
      - "https://traefik.local:5000"
configs:
  "traefik.local:5000":
    auth:
      username: admin # this is the registry username
      password: admin # this is the registry password
    tls:
      insecure_skip_verify: true

**Comment by brandond** [comment]
I'm not sure how containerd's insecure_skip_verify option works... but why isn't your traefik cert valid for any hostnames?

**Comment by zukko78** [comment]
Hi there, 

Fixed. I found the issue, master node had correct registries.yaml but workernode had incorrect registries.yaml without 
tls:
      insecure_skip_verify: true
About, my traefik cert isn't valid for any hostnames - I don't know, its selfsigned.

**Comment by zukko78** [comment]
I think we can close this issue.

**Comment by abdennour** [comment]
traefik generates 2 keys : `.key` and `.crt`
How can use them with k3s private registries if i don't want to use insecure communication?

 what's mapped to [cert_file , key_file and ca_file](https://rancher.com/docs/k3s/latest/en/installation/private-registry/) ?

**Comment by abdennour** [comment]
Found answer on my last question here: https://github.com/k3s-io/k3s/issues/1148#issuecomment-641687668
