### ISSUE TITLE
K3s Cluster with Kong Ingress with database.

### ISSUE THREAD

**Issue by sandhyarme** [rancher/k3s#2431]
We want to create k3s cluster with 3 nodes in cluster.
Cluster with kong ingress controller with external database.
Please provide us the reference link.. 
exporting datastore= database link would be sufficient or we need to do an changes in config file ?

**Comment by brandond** [comment]
Are you looking for documentation on Kong, or on k3s? The documentation for using k3s with an external datastore is at https://rancher.com/docs/k3s/latest/en/installation/ha/#2-launch-server-nodes. For Kong, you'd have to check their docs, as it's not something we specifically support.

**Comment by sandhyarme** [comment]
k3s supports for postgresql 11.9 ?
In offical site 10.7 and 11.5 is mentioned, can we consider 11.9 is also supported ?

**Comment by sandhyarme** [comment]
Tried with postgresql but received error.

export K3S_DATASTORE_ENDPOINT='postgres://postgres:postgres@15.213.141.54:5432/postgres' k3s server

curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable traefik --disable servicelb --write-kubeconfig-mode=644" INSTALL_K3S_SELINUX_WARN="true" sh -
[INFO]  Finding release for channel stable
[INFO]  Using v1.18.9+k3s1 as release
[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v1.18.9+k3s1/sha256sum-amd64.txt
[INFO]  Skipping binary downloaded, installed k3s matches hash
[WARN]  Failed to find the k3s-selinux policy, please install:
    yum install -y container-selinux selinux-policy-base
    yum install -y https://rpm.rancher.io/k3s-selinux-0.1.1-rc1.el7.noarch.rpm

[INFO]  Creating /usr/local/bin/kubectl symlink to k3s
[INFO]  Creating /usr/local/bin/crictl symlink to k3s
[INFO]  Creating /usr/local/bin/ctr symlink to k3s
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
Created symlink from /etc/systemd/system/multi-user.target.wants/k3s.service to /etc/systemd/system/k3s.service.
[INFO]  systemd: Starting k3s
Job for k3s.service failed because the control process exited with error code. See "systemctl status k3s.service" and "journalctl -xe" for details.

[root@kong ~]# journalctl -xe
--
-- The result is failed.
Oct 28 00:24:24 kong.master systemd[1]: Unit k3s.service entered failed state.
Oct 28 00:24:24 kong.master systemd[1]: k3s.service failed.
Oct 28 00:24:29 kong.master systemd[1]: k3s.service holdoff time over, scheduling restart.
Oct 28 00:24:29 kong.master systemd[1]: Stopped Lightweight Kubernetes.
-- Subject: Unit k3s.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit k3s.service has finished shutting down.
Oct 28 00:24:29 kong.master systemd[1]: Starting Lightweight Kubernetes...
-- Subject: Unit k3s.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit k3s.service has begun starting up.
Oct 28 00:24:30 kong.master k3s[12328]: time="2020-10-28T00:24:30.345735353+05:30" level=info msg="Starting k3s v1.18.9+k3s1 (630bebf9)"
Oct 28 00:24:30 kong.master k3s[12328]: time="2020-10-28T00:24:30.347519884+05:30" level=fatal msg="starting kubernetes: preparing server: creating storage e
Oct 28 00:24:30 kong.master systemd[1]: k3s.service: main process exited, code=exited, status=1/FAILURE
Oct 28 00:24:30 kong.master systemd[1]: Failed to start Lightweight Kubernetes.
-- Subject: Unit k3s.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit k3s.service has failed.
--
-- The result is failed.
Oct 28 00:24:30 kong.master systemd[1]: Unit k3s.service entered failed state.
Oct 28 00:24:30 kong.master systemd[1]: k3s.service failed.
Oct 28 00:24:35 kong.master systemd[1]: k3s.service holdoff time over, scheduling restart.
Oct 28 00:24:35 kong.master systemd[1]: Stopped Lightweight Kubernetes.
-- Subject: Unit k3s.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit k3s.service has finished shutting down.
Oct 28 00:24:35 kong.master systemd[1]: Starting Lightweight Kubernetes...
-- Subject: Unit k3s.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit k3s.service has begun starting up.
