### ISSUE TITLE
etcd fails to start with --node-external-ip

### ISSUE THREAD

**Issue by galal-hussein** [rancher/k3s#2434]
K3s Version: v1.19.3+k3s1 

Node(s) CPU architecture, OS, and Version: 
ubuntu 18.04

Cluster Configuration:
1 node on aws

**Describe the bug:**

when k3s starts with --cluster-init and --node-external-ip on ec2 nodes it fails to bind the external ip to the etcd since the address is not on the system and only private ips are defined for the ec2 instance

**Steps To Reproduce:**

- start k3s using the following command
```
k3s server --cluster-init --node-external-ip <public ip of the node>
```

**Expected behavior:**
k3s should start normally

**Actual behavior:**
etcd fails to start and error logs show:
```
cp 127.0.0.1:2379: connect: connection refused". Reconnecting...
WARNING: 2020/10/27 20:00:29 grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused". Reconnecting...
WARNING: 2020/10/27 20:00:30 grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused". Reconnecting...
WARNING: 2020/10/27 20:00:32 grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused". Reconnecting...
WARNING: 2020/10/27 20:00:37 grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused". Reconnecting...
{"level":"warn","ts":"2020-10-27T20:00:38.154Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"passthrough:///https://127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}
```

**Additional context / logs:**
The fix should be either use 0.0.0.0 to bind address to or using the private ip instead

**Comment by galal-hussein** [comment]
duplicate of https://github.com/rancher/k3s/issues/2345

**Comment by AlNedorezov** [comment]
Just reproduced this issue on `v1.21.1+k3s1` while trying to connect second server to the first one for the HA cluster in my local network.
Is there an easy-to-follow explanation of a workaround/fix for this issue?

I didn't really get the resolution for #2345

**Comment by brandond** [comment]
Etcd only connect to node private IPs. All servers running etcd must be on the same network, with direct connectivity to each other.
