### ISSUE TITLE
Installation Fails on Fedora 33 IOT Edition

### ISSUE THREAD

**Issue by seanmalloy** [rancher/k3s#2452]
**Environmental Info:**
K3s Version: `v1.18.9+k3s1`

Node(s) CPU architecture, OS, and Version: `uname -a Linux localhost.localdomain 5.8.15-301.fc33.aarch64 rancher/k3s#1 SMP Thu Oct 15 15:56:58 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux`

Cluster Configuration: Single node on Raspberry Pi 4 Running Fedora 33 IOT Edition

**Describe the bug:**

The k3s installer is failing with the below error on when run on Fedora 33 IOT Edition. Fedora 33 IOT uses the `rpm-ostree` package manager, not `yum`. Therefore all `yum` commands will fail when run on Fedora 33 IOT Edition because `yum` is not installed.
```
root@localhost ~]# curl -sfL https://get.k3s.io | sh -
[INFO]  Finding release for channel stable
[INFO]  Using v1.18.9+k3s1 as release
[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v1.18.9+k3s1/sha256sum-arm64.txt
[INFO]  Skipping binary downloaded, installed k3s matches hash
main: line 484: yum: command not found

```

**Steps To Reproduce:**

Run the k3s installer on Fedora 33 IOT as the root user.

**Expected behavior:**

I expected the k3s installation script to successfully run on Fedora 33 IOT edition.

**Actual behavior:**

The installation fails because the install script is trying to run a yum command, but the yum command is not installed.

**Additional context / logs:**

N/A

**Comment by seanmalloy** [comment]
Looks like I might need to manually install the SELinux RPM packages using `rpm-ostree` before running the installer script, and then set `INSTALL_K3S_SKIP_SELINUX_RPM` to `true` during the install.

Let me know if there if there would be any interest in updating the installer to support `rpm-ostree`.

**Comment by Oats87** [comment]
We do not support `Fedora 33 IOT`, and thus I have a PR incoming with additional logic to prevent trying to auto-install the `selinux` RPMs on Fedora systems

**Comment by Oats87** [comment]
A fix was merged for this. Please open a new issue if you are still running into issues.
