### ISSUE TITLE
Installation fails on CentOS 7

### ISSUE THREAD

**Issue by jeloba** [rancher/k3s#2454]
**Environmental Info:**
K3s Version:
v1.19.3+k3s1 (974ad30b)

Node(s) CPU architecture, OS, and Version: 
Linux xxx.eu-west-1.compute.internal 3.10.0-1127.19.1.el7.x86_64 rancher/k3s#1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Describe the bug:**
Installations fails with `You need to be root to perform this command.`

**Steps To Reproduce:**
- Install CentOS 7, execute `sudo yum update -y`
- Try to install k3s `curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL=testing sh -`

**Expected behavior:**
Installation should succeed.

**Actual behavior:**
```
$ curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL=testing sh -                                                  
[INFO]  Finding release for channel testing                                                                                                 
[INFO]  Using v1.19.3+k3s1 as release                                 
[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v1.19.3+k3s1/sha256sum-amd64.txt                                  
[INFO]  Downloading binary https://github.com/rancher/k3s/releases/download/v1.19.3+k3s1/k3s                                                
[INFO]  Verifying binary download                                     
[INFO]  Installing k3s to /usr/local/bin/k3s                          
Loaded plugins: fastestmirror                                         
You need to be root to perform this command.   
```

**Additional context / logs:**
Executing with `sh -x` reveals:

```
[...]
+ yum -y install yum-utils     
Loaded plugins: fastestmirror
You need to be root to perform this command.     
```

**Comment by Oats87** [comment]
The `$SUDO` in front of the various `yum` commands is missing. PR incoming to re-add the `$SUDO`.

In the mean time, you can work around this by passing `INSTALL_K3S_SKIP_SELINUX_RPM=true` into the install script

**Comment by Oats87** [comment]
A fix was merged for this. Please open a new issue if you are still running into issues.
