### ISSUE TITLE
Support Caddy Ingress

### ISSUE THREAD

**Issue by mysticaltech** [rancher/k3s#2465]
Traefik can be complex to set up, especially for beginners. Having support for **Caddy ingress** would be great, https://github.com/caddyserver/ingress

I want K3S to support **Caddy** as an ingress type. out of the box, similar to how Traefik is done. Because caddy is so simple to configure and setup, no other server / reverse proxy has been able to achieve such simplicity!

**Comment by brandond** [comment]
We don't currently have plans to provide multiple out-of-the box options for packaged components such as load-balancer, ingress, CNI plugin, etc. As the readme says, we've made "opinionated choices" about packaged components; if users want something else it's easy to disable the packaged components and install something else either manually, or using the automatically-deployed manifests.

**Comment by mysticaltech** [comment]
Got it, thanks for the clarification, and keep up the good work!
