### ISSUE TITLE
Unnecessary warnings in k3s server log

### ISSUE THREAD

**Issue by brandond** [rancher/k3s#2471]
**Environmental Info:**
K3s Version: 
k3s version v1.19.3+k3s2

Node(s) CPU architecture, OS, and Version: 
Linux centos02.lan.khaus 5.8.10-1.el7.elrepo.x86_64 rancher/k3s#1 SMP Thu Sep 17 10:40:48 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
Single server

**Describe the bug:**
Multiple trivial warnings in server logs:

1. 
    ```
    W1102 16:50:20.682429   18319 util_unix.go:103] Using "/run/k3s/containerd/containerd.sock" as endpoint is deprecated, please consider using full url format "unix:///run/k3s/containerd/containerd.sock".
    W1102 16:50:20.682537   18319 util_unix.go:103] Using "/run/k3s/containerd/containerd.sock" as endpoint is deprecated, please consider using full url format "unix:///run/k3s/containerd/containerd.sock".
    ```
1.
    ```
    W1102 16:50:20.054587   18319 controllermanager.go:139] detected a cluster without a ClusterID.  A ClusterID will be required in the future.  Please tag your cluster to avoid any future issues
    ```
1.
    ```
    E1103 16:50:20.023596   27477 core.go:97] Failed to start service controller: the cloud provider does not support external load balancers
    W1102 16:50:20.055788   18319 core.go:115] configure-cloud-routes is set, but cloud provider does not support routes. Will not configure cloud provider routes.
    W1102 16:50:29.406139   18319 core.go:244] configure-cloud-routes is set, but no cloud provider specified. Will not configure cloud provider routes.
    ```

**Steps To Reproduce:**
* Run K3s
* look at logs

**Expected behavior:**
No unnecessary warnings

**Actual behavior:**
Warnings

**Additional context / logs:**

**Comment by rancher-max** [comment]
#### Used latest master commit to validate: `fcb864a5e20f69a4d5b19feb7f265abb9086b749`. Reopening due to one regression noticed.

- containerd sock deprecation warning is no longer present
- clusterid warning no longer present on default option installs.
- Validated core.go errors and warnings no longer present. List of these:
```
Nov 09 17:21:21 ip-172-31-42-30 k3s[2187]: E1109 17:21:21.900387    2187 core.go:229] failed to start cloud node lifecycle controller: no cloud provider provided

Nov 09 17:21:23 ip-172-31-42-30 k3s[2187]: E1109 17:21:23.605152    2187 core.go:90] Failed to start service controller: the cloud provider does not support external load balancers

Nov 09 17:21:23 ip-172-31-42-30 k3s[2187]: W1109 17:21:23.605181    2187 core.go:108] configure-cloud-routes is set, but cloud provider does not support routes. Will not configure cloud provider routes.

Nov 09 17:21:35 ip-172-31-42-30 k3s[2187]: W1109 17:21:35.189264    2187 core.go:243] configure-cloud-routes is set, but no cloud provider specified. Will not configure cloud provider routes.

Nov 09 17:21:35 ip-172-31-42-30 k3s[2187]: E1109 17:21:35.229002    2187 core.go:89] Failed to start service controller: WARNING: no cloud provider provided, services of type LoadBalancer will fail


```

**Regression:** Disabling cloud controller manager and running an external cloud provider on AWS no longer comes up successfully. 
Going off a comment on one of the commits to the PR: 
> One side-effect of this is that the core k8s cloud-controller-manager
also wants to watch nodes, and needs RBAC to do so.

Performed the same steps as in https://github.com/rancher/k3s/issues/1807#issuecomment-675081920. Validated this is working in v1.19.3+k3s2 but now gets CrashLoopBackoff on this commit. The logs of the pod show:
```
...
Error: rendered manifests contain a resource that already exists. Unable to continue with install: ServiceAccount "cloud-controller-manager" in namespace "kube-system" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "aws-cloud-controller-manager"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "kube-system"
```

**Comment by brandond** [comment]
@rancher-max can you retest once https://github.com/rancher/k3s/pull/2493 is merged?

**Comment by rancher-max** [comment]
Using commit id `58b5b21f0d8319da9777b80d3f9e1f7f652b8bd3`, the regression is fixed and it comes up successfully with external cloud provider. Additionally, the clusterid warning is not present in the logs whether using external cloud provider or just a default install. Working as expected 👍
