### ISSUE TITLE
I lost all values when I restart k3s in /var/lib/rancher/k3s/server/manifests/traefik.yaml

### ISSUE THREAD

**Issue by sjkeerthi** [rancher/k3s#249]
OS : CentOS 7.6.1810

**Describe the bug**

I manually updated few values in the /var/lib/rancher/k3s/server/manifests/traefik.yaml
ssl.enforced: "true"
dashboard.enabled: "true"

When restart the k3s I could see all the values varnished and could see the default one.
apiVersion: k3s.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: stable/traefik
  set:
    rbac.enabled: "true"
    ssl.enabled: "true"

**To Reproduce**
do systemsctl restart k3s

**Comment by kyleterry** [comment]
This happened to me as well.

**Comment by mortenlj** [comment]
This is related to #230 I would say.

**Comment by erikwilson** [comment]
Closing as a duplicate, if you think the other issue is different please re-open this with more info.
