### ISSUE TITLE
Cannot find containerd-mount device for arm

### ISSUE THREAD

**Issue by hechengjie** [rancher/k3s#2492]
For arm linux, i run "k3s-armhf server" first, then i import k3s-airgap-images-arm.tar success.
When i try to run the image, k3s give me an error msg. it is the same error msg for all images.

>  ./k3s-armhf ctr run docker.io/rancher/library-busybox:1.31.1 111
> ctr: failed to mount /tmp/containerd-mount076466803: no such device

Maybe i miss something, but i do not know how to resolve it....

**Comment by brandond** [comment]
What OS distribution is this on?

**Comment by hechengjie** [comment]
only busybox on linux kernel

**Comment by brandond** [comment]
I'm not sure we've ever tested it on such a stripped-down system. What are you using for the root filesystem image? Do all of the Filesystem Hierarchy Standard directories exist?

**Comment by hechengjie** [comment]
it need overlayfs, i config it & rebuild kernel.
