### ISSUE TITLE
the location of config.toml has moved

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/k3s#2498]
**Environmental Info:**
K3s Version: 
v1.19.3+k3s-c72c1867

**Node(s) CPU architecture, OS, and Version:**
Ubuntu 20.04

**Cluster Configuration:**
Single node

**Describe the bug:**
The location of config.toml has moved from /var/lib/rancher/k3s/agent/etc/containerd/config.toml to /var/lib/rancher/k3s/etc/containerd/config.toml

**Steps To Reproduce:**
Install k3s using above commit

**Expected behavior:**
config.toml should have been in /var/lib/rancher/k3s/agent/etc/containerd/config.toml 

**Actual behavior:**
config.toml is in /var/lib/rancher/k3s/etc/containerd/config.toml

**Additional context / logs:**
```
sudo cat /var/lib/rancher/k3s/etc/containerd/config.toml

[plugins.opt]
  path = "/var/lib/rancher/k3s/containerd"

[plugins.cri]
  stream_server_address = "127.0.0.1"
  stream_server_port = "10010"
  enable_selinux = false
  sandbox_image = "docker.io/rancher/pause:3.1"

[plugins.cri.containerd]
  disable_snapshot_annotations = true
  snapshotter = "overlayfs"
```

**Comment by brandond** [comment]
2496 will resolve this

**Comment by ShylajaDevadiga** [comment]
Validated using commit v1.19.3+k3s-b873d3a0. 
```
ubuntu@ip-172-31-42-166:~$ sudo cat /var/lib/rancher/k3s/etc/containerd/config.toml
cat: /var/lib/rancher/k3s/etc/containerd/config.toml: No such file or directory
ubuntu@ip-172-31-42-166:~$ sudo cat /var/lib/rancher/k3s/agent/etc/containerd/config.toml

[plugins.opt]
  path = "/var/lib/rancher/k3s/agent/containerd"
...
```
