### ISSUE TITLE
k3s-arm64 server auto exit

### ISSUE THREAD

**Issue by hechengjie** [rancher/k3s#2501]
I run k3s-arm64 server on my arm hardware.
it exited when it run about several minutes.

	

> /usr/local/go/src/net/net.go:182 +0x74
> bufio.(*Reader).Read(0x4003871aa0, 0x4003328038, 0x9, 0x9, 0x400008fc00, 0x7f96d91100, 0x1)
> 	/usr/local/go/src/bufio/bufio.go:227 +0x214
> io.ReadAtLeast(0x4268dc0, 0x4003871aa0, 0x4003328038, 0x9, 0x9, 0x9, 0x402a1554d0, 0x5fab2fc5, 0x4005c46da8)
> 	/usr/local/go/src/io/io.go:314 +0x78
> io.ReadFull(...)
> 	/usr/local/go/src/io/io.go:333
> github.com/rancher/k3s/vendor/golang.org/x/net/http2.readFrameHeader(0x4003328038, 0x9, 0x9, 0x4268dc0, 0x4003871aa0, 0x0, 0x4000000000, 0x0, 0x0)
> 	/go/src/github.com/rancher/k3s/vendor/golang.org/x/net/http2/frame.go:237 +0x5c
> github.com/rancher/k3s/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0x4003328000, 0x40007fb920, 0x65bc760, 0x0, 0x0)
> 	/go/src/github.com/rancher/k3s/vendor/golang.org/x/net/http2/frame.go:492 +0x74
> github.com/rancher/k3s/vendor/google.golang.org/grpc/internal/transport.(*http2Server).HandleStreams(0x40030f2f00, 0x400347e9f0, 0x3dadb98)
> 	/go/src/github.com/rancher/k3s/vendor/google.golang.org/grpc/internal/transport/http2_server.go:458 +0x70
> github.com/rancher/k3s/vendor/google.golang.org/grpc.(*Server).serveStreams(0x40014f6900, 0x43665e0, 0x40030f2f00)
> 	/go/src/github.com/rancher/k3s/vendor/google.golang.org/grpc/server.go:718 +0xdc
> github.com/rancher/k3s/vendor/google.golang.org/grpc.(*Server).handleRawConn.func1(0x40014f6900, 0x43665e0, 0x40030f2f00)
> 	/go/src/github.com/rancher/k3s/vendor/google.golang.org/grpc/server.go:679 +0x38
> created by github.com/rancher/k3s/vendor/google.golang.org/grpc.(*Server).handleRawConn
> 	/go/src/github.com/rancher/k3s/vendor/google.golang.org/grpc/server.go:678 +0x46c
> 
> goroutine 3485 [select]:
> github.com/rancher/k3s/vendor/google.golang.org/grpc/internal/transport.(*recvBufferReader).readClient(0x4002a10f00, 0x4002a0d910, 0x5, 0x5, 0x4005c06898, 0x8970ec, 0x4005c06898)
> 	/go/src/github.com/rancher/k3s/vendor/google.golang.org/grpc/internal/transport/transport.go:186 +0x88
> github.com/rancher/k3s/vendor/google.golang.org/grpc/internal/transport.(*recvBufferReader).Read(0x4002a10f00, 0x4002a0d910, 0x5, 0x5, 0x4005c06928, 0x898e08, 0x4000810060)
> 	/go/src/github.com/rancher/k3s/vendor/google.golang.org/grpc/internal/transport/transport.go:166 +0x178
> github.com/rancher/k3s/vendor/google.golang.org/grpc/internal/transport.(*transportReader).Read(0x400350c3c0, 0x4002a0d910, 0x5, 0x5, 0x4005c06958, 0x896fa0, 0x40031df880)
> 	/go/src/github.com/rancher/k3s/INFO[2020-11-11T00:26:48.313410100Z] Waiting for node (none): nodes "(none)" not found 
> /mnt/k3simage # 
>

**Comment by hechengjie** [comment]
Can k3s work when linux system has not systemd & openrc_run ? 
My system is only busybox with inittab

**Comment by brandond** [comment]
You might be able to get it working - we don't rely on anything specific from the init system. I suspect you're probably missing something else though.

**Comment by hechengjie** [comment]
> ./k3s-arm64 server
> INFO[2020-11-13T01:11:26.284628320Z] Starting k3s v1.19.3+k3s3 (0e4fbfef)         
> INFO[2020-11-13T01:11:26.285297140Z] Cluster bootstrap already complete           
> INFO[2020-11-13T01:11:26.374883200Z] Configuring sqlite3 database connection pooling: maxIdleConns=2, maxOpenConns=0, connMaxLifetime=0s 
> INFO[2020-11-13T01:11:26.375022600Z] Configuring database table schema and indexes, this may take a moment... 
> INFO[2020-11-13T01:11:26.375270240Z] Database tables and indexes are up to date   
> INFO[2020-11-13T01:11:26.377347380Z] Kine listening on unix://kine.sock           
> INFO[2020-11-13T01:11:26.377698580Z] Running kube-apiserver --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=unknown --authorization-mode=Node,RBAC --bind-address=127.0.0.1 --cert-dir=/var/lib/rancher/k3s/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --enable-admission-plugins=NodeRestriction --etcd-servers=unix://kine.sock --insecure-port=0 --kubelet-certificate-authority=/var/lib/rancher/k3s/server/tls/server-ca.crt --kubelet-client-certificate=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.crt --kubelet-client-key=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.key --profiling=false --proxy-client-cert-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt --proxy-client-key-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.key --requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6444 --service-account-issuer=k3s --service-account-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-account-signing-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-cluster-ip-range=10.43.0.0/16 --storage-backend=etcd3 --tls-cert-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt --tls-private-key-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.key 
> I1113 01:11:26.379829    1464 server.go:652] external host was not specified, using 172.16.195.153
> I1113 01:11:26.380432    1464 server.go:177] Version: v1.19.3+k3s3
> I1113 01:11:26.391865    1464 plugins.go:158] Loaded 12 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,StorageObjectInUseProtection,RuntimeClass,DefaultIngressClass,MutatingAdmissionWebhook.
> I1113 01:11:26.391942    1464 plugins.go:161] Loaded 10 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority,PersistentVolumeClaimResize,RuntimeClass,CertificateApproval,CertificateSigning,CertificateSubjectRestriction,ValidatingAdmissionWebhook,ResourceQuota.
> I1113 01:11:26.394876    1464 plugins.go:158] Loaded 12 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,StorageObjectInUseProtection,RuntimeClass,DefaultIngressClass,MutatingAdmissionWebhook.
> I1113 01:11:26.394951    1464 plugins.go:161] Loaded 10 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority,PersistentVolumeClaimResize,RuntimeClass,CertificateApproval,CertificateSigning,CertificateSubjectRestriction,ValidatingAdmissionWebhook,ResourceQuota.
> I1113 01:11:26.498895    1464 master.go:271] Using reconciler: lease
> W1113 01:11:27.711831    1464 genericapiserver.go:412] Skipping API batch/v2alpha1 because it has no resources.
> W1113 01:11:27.810739    1464 genericapiserver.go:412] Skipping API discovery.k8s.io/v1alpha1 because it has no resources.
> W1113 01:11:27.907974    1464 genericapiserver.go:412] Skipping API node.k8s.io/v1alpha1 because it has no resources.
> W1113 01:11:27.965192    1464 genericapiserver.go:412] Skipping API rbac.authorization.k8s.io/v1alpha1 because it has no resources.
> W1113 01:11:27.975878    1464 genericapiserver.go:412] Skipping API scheduling.k8s.io/v1alpha1 because it has no resources.
> W1113 01:11:28.022036    1464 genericapiserver.go:412] Skipping API storage.k8s.io/v1alpha1 because it has no resources.
> W1113 01:11:28.133905    1464 genericapiserver.go:412] Skipping API apps/v1beta2 because it has no resources.
> W1113 01:11:28.134017    1464 genericapiserver.go:412] Skipping API apps/v1beta1 because it has no resources.
> I1113 01:11:28.195624    1464 plugins.go:158] Loaded 12 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,StorageObjectInUseProtection,RuntimeClass,DefaultIngressClass,MutatingAdmissionWebhook.
> I1113 01:11:28.195760    1464 plugins.go:161] Loaded 10 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority,PersistentVolumeClaimResize,RuntimeClass,CertificateApproval,CertificateSigning,CertificateSubjectRestriction,ValidatingAdmissionWebhook,ResourceQuota.
> INFO[2020-11-13T01:11:28.237489880Z] Running kube-scheduler --address=127.0.0.1 --bind-address=127.0.0.1 --kubeconfig=/var/lib/rancher/k3s/server/cred/scheduler.kubeconfig --leader-elect=false --port=10251 --profiling=false --secure-port=0 
> I1113 01:11:28.238492    1464 registry.go:173] Registering SelectorSpread plugin
> I1113 01:11:28.238579    1464 registry.go:173] Registering SelectorSpread plugin
> INFO[2020-11-13T01:11:28.239704580Z] Running kube-controller-manager --address=127.0.0.1 --allocate-node-cidrs=true --bind-address=127.0.0.1 --cluster-cidr=10.42.0.0/16 --cluster-signing-cert-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --cluster-signing-key-file=/var/lib/rancher/k3s/server/tls/client-ca.key --kubeconfig=/var/lib/rancher/k3s/server/cred/controller.kubeconfig --leader-elect=false --port=10252 --profiling=false --root-ca-file=/var/lib/rancher/k3s/server/tls/server-ca.crt --secure-port=0 --service-account-private-key-file=/var/lib/rancher/k3s/server/tls/service.key --use-service-account-credentials=true 
> INFO[2020-11-13T01:11:28.244404820Z] Waiting for API server to become available   
> INFO[2020-11-13T01:11:28.245648920Z] Node token is available at /var/lib/rancher/k3s/server/token 
> INFO[2020-11-13T01:11:28.245728180Z] To join node to cluster: k3s agent -s https://172.16.195.153:6443 -t ${NODE_TOKEN} 
> INFO[2020-11-13T01:11:28.248253900Z] Wrote kubeconfig /etc/rancher/k3s/k3s.yaml   
> INFO[2020-11-13T01:11:28.248351040Z] Run: k3s-arm64 kubectl                       
> WARN[2020-11-13T01:11:28.248478100Z] Failed to find cpuset cgroup, you may need to add "cgroup_enable=cpuset" to your linux cmdline (/boot/cmdline.txt on a Raspberry Pi) 
> INFO[2020-11-13T01:11:28.248516500Z] Module overlay was already loaded            
> WARN[2020-11-13T01:11:28.250582820Z] Failed to start nf_conntrack module          
> WARN[2020-11-13T01:11:28.252607940Z] Failed to start br_netfilter module          
> WARN[2020-11-13T01:11:28.254652240Z] Failed to start iptable_nat module           
> WARN[2020-11-13T01:11:28.254935320Z] Failed to write value 1 at /proc/sys/net/bridge/bridge-nf-call-iptables: open /proc/sys/net/bridge/bridge-nf-call-iptables: no such file or directory 
> WARN[2020-11-13T01:11:28.254977220Z] Failed to write value 1 at /proc/sys/net/bridge/bridge-nf-call-ip6tables: open /proc/sys/net/bridge/bridge-nf-call-ip6tables: no such file or directory 
> INFO[2020-11-13T01:11:28.260083000Z] Cluster-Http-Server 2020/11/13 01:11:28 http: TLS handshake error from 127.0.0.1:44608: remote error: tls: bad certificate 
> INFO[2020-11-13T01:11:28.280700980Z] Cluster-Http-Server 2020/11/13 01:11:28 http: TLS handshake error from 127.0.0.1:44614: remote error: tls: bad certificate 
> INFO[2020-11-13T01:11:28.343389800Z] certificate CN=(none) signed by CN=k3s-server-ca@1605225608: notBefore=2020-11-13 00:00:08 +0000 UTC notAfter=2021-11-13 01:11:28 +0000 UTC 
> INFO[2020-11-13T01:11:28.359428340Z] certificate CN=system:node:(none),O=system:nodes signed by CN=k3s-client-ca@1605225608: notBefore=2020-11-13 00:00:08 +0000 UTC notAfter=2021-11-13 01:11:28 +0000 UTC 
> INFO[2020-11-13T01:11:28.386763860Z] Logging containerd to /var/lib/rancher/k3s/agent/containerd/containerd.log 
> INFO[2020-11-13T01:11:28.387553600Z] Running containerd -c /var/lib/rancher/k3s/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state /run/k3s/containerd --root /var/lib/rancher/k3s/agent/containerd 
> INFO[2020-11-13T01:11:29.388686280Z] Waiting for containerd startup: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /run/k3s/containerd/containerd.sock: connect: no such file or directory" 
> INFO[2020-11-13T01:11:30.398691440Z] Containerd is now running                    
> INFO[2020-11-13T01:11:30.430930060Z] Connecting to proxy                           url="wss://127.0.0.1:6443/v1-k3s/connect"
> INFO[2020-11-13T01:11:30.446319600Z] Handling backend connection request [(none)] 
> WARN[2020-11-13T01:11:30.447927500Z] Disabling CPU quotas due to missing cpu.cfs_period_us 
> WARN[2020-11-13T01:11:30.448029920Z] Disabling pod PIDs limit feature due to missing cgroup pids support 
> INFO[2020-11-13T01:11:30.448222320Z] Running kubelet --address=0.0.0.0 --anonymous-auth=false --authentication-token-webhook=true --authorization-mode=Webhook --cgroup-driver=cgroupfs --cgroups-per-qos=false --client-ca-file=/var/lib/rancher/k3s/agent/client-ca.crt --cloud-provider=external --cluster-dns=10.43.0.10 --cluster-domain=cluster.local --cni-bin-dir=/var/lib/rancher/k3s/data/63dbbe8462074f773c2a00caa9a9a87684fcff868c7e6bf54b4433af70608590/bin --cni-conf-dir=/var/lib/rancher/k3s/agent/etc/cni/net.d --container-runtime-endpoint=/run/k3s/containerd/containerd.sock --container-runtime=remote --containerd=/run/k3s/containerd/containerd.sock --cpu-cfs-quota=false --enforce-node-allocatable= --eviction-hard=imagefs.available<5%,nodefs.available<5% --eviction-minimum-reclaim=imagefs.available=10%,nodefs.available=10% --fail-swap-on=false --feature-gates=SupportPodPidsLimit=false --healthz-bind-address=127.0.0.1 --hostname-override=(none) --kubeconfig=/var/lib/rancher/k3s/agent/kubelet.kubeconfig --node-labels= --pod-manifest-path=/var/lib/rancher/k3s/agent/pod-manifests --read-only-port=0 --resolv-conf=/etc/resolv.conf --serialize-image-pulls=false --tls-cert-file=/var/lib/rancher/k3s/agent/serving-kubelet.crt --tls-private-key-file=/var/lib/rancher/k3s/agent/serving-kubelet.key 
> INFO[2020-11-13T01:11:30.450635820Z] Running kube-proxy --cluster-cidr=10.42.0.0/16 --healthz-bind-address=127.0.0.1 --hostname-override=(none) --kubeconfig=/var/lib/rancher/k3s/agent/kubeproxy.kubeconfig --proxy-mode=iptables 
> Flag --cloud-provider has been deprecated, will be removed in 1.23, in favor of removing cloud provider code from Kubelet.
> Flag --containerd has been deprecated, This is a cadvisor flag that was mistakenly registered with the Kubelet. Due to legacy concerns, it will follow the standard CLI deprecation timeline before being removed.
> I1113 01:11:30.455664    1464 server.go:407] Version: v1.19.3+k3s3
> W1113 01:11:30.457695    1464 server.go:226] WARNING: all flags other than --config, --write-config-to, and --cleanup are deprecated. Please begin using a config file ASAP.
> W1113 01:11:30.467118    1464 server.go:608] failed to get the kubelet's cgroup: mountpoint for cpu not found.  Kubelet system container metrics may be missing.
> F1113 01:11:30.467262    1464 server.go:261] failed to run Kubelet: mountpoint for cpu not found

Can find any info from this log? Or find what i missed...

**Comment by brandond** [comment]
Well yes there's quite a few things in there. You appear to be missing almost every possible kernel module or option that Kubernetes needs to operate:

```
WARN[2020-11-13T01:11:28.248478100Z] Failed to find cpuset cgroup, you may need to add "cgroup_enable=cpuset" to your linux cmdline (/boot/cmdline.txt on a Raspberry Pi)
INFO[2020-11-13T01:11:28.248516500Z] Module overlay was already loaded
WARN[2020-11-13T01:11:28.250582820Z] Failed to start nf_conntrack module
WARN[2020-11-13T01:11:28.252607940Z] Failed to start br_netfilter module
WARN[2020-11-13T01:11:28.254652240Z] Failed to start iptable_nat module
WARN[2020-11-13T01:11:28.254935320Z] Failed to write value 1 at /proc/sys/net/bridge/bridge-nf-call-iptables: open /proc/sys/net/bridge/bridge-nf-call-iptables: no such file or directory
WARN[2020-11-13T01:11:28.254977220Z] Failed to write value 1 at /proc/sys/net/bridge/bridge-nf-call-ip6tables: open /proc/sys/net/bridge/bridge-nf-call-ip6tables: no such file or directory
WARN[2020-11-13T01:11:30.447927500Z] Disabling CPU quotas due to missing cpu.cfs_period_us
WARN[2020-11-13T01:11:30.448029920Z] Disabling pod PIDs limit feature due to missing cgroup pids support
W1113 01:11:30.467118 1464 server.go:608] failed to get the kubelet's cgroup: mountpoint for cpu not found. Kubelet system container metrics may be missing.
F1113 01:11:30.467262 1464 server.go:261] failed to run Kubelet: mountpoint for cpu not found

```

**Comment by hechengjie** [comment]
it's systemd problem
