### ISSUE TITLE
Install script should be able to handle versioned channels

### ISSUE THREAD

**Issue by Oats87** [rancher/k3s#2517]
Currently, the `install.sh` script only handles channels that are one of: `testing`, `latest` and `stable`.

The `install.sh` script needs to be enhanced so as to be able to handle channels that are like `v1.18`, `v1.18-testing`, `v1.19`, and so forth. We will utilize the following logic for the repository channel itself, where:

`v1.18`, `v1.19`, and `stable` or any other specific channel repo will correspond to the `stable` channel for `k3s-selinux` RPMs
`v1.18-testing` and `v1.19-testing` and `testing` will correspond to the `latest` channel for `k3s-selinux` RPMs
`latest` will always correspond to the `latest` channel for the `k3s-selinux` RPMs

**Comment by ShylajaDevadiga** [comment]
1. Validated below scenarios
Installation using below channels installs corresponding versions.
- testing
- latest
- v1.18 
- v1.18-testing 
- v1.19 

2. Upgrade from v1.18 to v1.19 is successful.
3. Upgrade from stable to testing.
```
$ rpm -qa|grep k3s
k3s-selinux-0.2-1.el7_8.noarch
$ sudo yum list|grep rancher
k3s-selinux.noarch                                     0.2-1.el7_8                                       @rancher-k3s-common-stable      
$ sudo chmod 644 /etc/rancher/k3s/k3s.yaml 
$ kubectl get nodes
NAME                                          STATUS   ROLES    AGE     VERSION
ip-172-31-35-115.us-east-2.compute.internal   Ready    master   2m32s   v1.19.3+k3s3
```
After upgrade to testing
```
$ rpm -qa|grep k3s
k3s-selinux-0.3~rc1-0.el8.noarch
$ sudo yum list|grep rancher
k3s-selinux.noarch                                     0.3~rc1-0.el8                                     @rancher-k3s-common-testing     
$ kubectl get nodes
NAME                                          STATUS   ROLES    AGE   VERSION
ip-172-31-35-115.us-east-2.compute.internal   Ready    master   11m   v1.19.4+k3s1

```
Validated uninstall works as expected.
