### ISSUE TITLE
Install script should create a universal repo file

### ISSUE THREAD

**Issue by Oats87** [rancher/k3s#2518]
Today, the `install.sh` script for `k3s` creates a repo file that looks like `rancher-k3s-common-<CHANNEL>.repo` where `<CHANNEL>` is one of `testing`, `latest`, or `stable`. We should simply create a `rancher-k3s-common.repo` file and internally within that file set up the corresponding repository. We should also clean up the old `*-<CHANNEL>.repo` files so as to prevent conflicting packages when a user decides to change their installed channel.

**Comment by ShylajaDevadiga** [comment]
Validated universal repo file is created, with corresponding repo set up internally.

```
cat  /etc/yum.repos.d/rancher-k3s-common.repo 
[rancher-k3s-common-stable]
name=Rancher K3s Common (stable)
...
sudo yum list|grep rancher
k3s-selinux.noarch                                     0.2-1.el7_8                                       @rancher-k3s-common-stable  

 cat  /etc/yum.repos.d/rancher-k3s-common.repo 
[rancher-k3s-common-testing]
name=Rancher K3s Common (testing)

sudo yum list|grep rancher
k3s-selinux.noarch                                     0.3~rc1-0.el8                                     @rancher-k3s-common-testing
```
Validated *-<CHANNEL>.repo file is deleted upon uninstall.
