### ISSUE TITLE
Metrics API (node/pod resource usage)

### ISSUE THREAD

**Issue by hjacobs** [rancher/k3s#252]
The Metrics Server ([Resource Metrics API](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/instrumentation/resource-metrics-api.md)) is currently not set up, this is already mentioned as a to-do in the README:

> Metrics API due to kube aggregation not being setup

Please add support for the [Resource Metrics API](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/instrumentation/resource-metrics-api.md) (`metrics.k8s.io/v1beta1` API version) to track node/pod resource usage and allow using `kubectl top` (#157) and tools like [kube-ops-view](https://github.com/hjacobs/kube-ops-view).

K3s is awesome btw :smile:

**Comment by reegnz** [comment]
Also realized today that the fact that metrics API is not present anything relying on HorizontalPodAutoscaling won't work either. :( That is something I ran into with trying to autoscale a deployment on k3s.

**Comment by hjacobs** [comment]
I had a similar issue with `kind` (Kubernetes in Docker), here how I deployed Metrics API: https://github.com/kubernetes-sigs/kind/issues/398

**Comment by erikwilson** [comment]
Metrics server should work with the latest RC, but needs some extra configuration.

To verify functionality k3s should run with a `--kubelet-arg="address=0.0.0.0"` flag, ex:
```sh
INSTALL_K3S_VERSION=v0.4.0-rc2 ./install.sh --kubelet-arg="address=0.0.0.0"
```

And install metrics server using our custom deployment from the root of this repo:
```sh
kubectl apply -f recipes/metrics-server
```

Then after a minute test metrics scraping:
```sh
kubectl get --raw /apis/metrics.k8s.io/v1beta1/nodes
```

Our goal is to continue improving k3s so a default deployment of metrics-server will work with the default arguments of k3s, this is being tracked in /issues/328.

**Comment by dnoland1** [comment]
Works for me. Started up k3s using:
```
root@k3s-node1:~# k3s server --kubelet-arg="address=0.0.0.0"
```
Applied metrics-server manifests:
```
root@k3s-node1:~# k3s kubectl apply -f k3s/recipes/metrics-server/
clusterrole.rbac.authorization.k8s.io/system:aggregated-metrics-reader created
clusterrolebinding.rbac.authorization.k8s.io/metrics-server:system:auth-delegator created
rolebinding.rbac.authorization.k8s.io/metrics-server-auth-reader created
apiservice.apiregistration.k8s.io/v1beta1.metrics.k8s.io created
serviceaccount/metrics-server created
deployment.apps/metrics-server created
service/metrics-server created
clusterrole.rbac.authorization.k8s.io/system:metrics-server created
clusterrolebinding.rbac.authorization.k8s.io/system:metrics-server created
```
Able to see pod and node metrics:
```
root@k3s-node1:~# k3s kubectl top node
NAME        CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
k3s-node1   40m          4%     350Mi           72%
root@k3s-node1:~# k3s kubectl top pod --all-namespaces
NAMESPACE     NAME                              CPU(cores)   MEMORY(bytes)
kube-system   coredns-857cdbd8b4-dl2bx          4m           11Mi
kube-system   helm-install-traefik-s8x6m        0m           0Mi
kube-system   metrics-server-675d76bcdb-6bc26   1m           14Mi
kube-system   svclb-traefik-6cf7794986-jdpd4    0m           1Mi
kube-system   traefik-55bd9646fc-d8bc9          4m           14Mi  
```

**Comment by erikwilson** [comment]
Thanks for testing @dnoland1!

**Comment by hjacobs** [comment]
@erikwilson fix for the README: https://github.com/rancher/k3s/pull/355
