### ISSUE TITLE
[HELP] After fresh install of k3s local-path-provisioner and metrics-server keep on crashing

### ISSUE THREAD

**Issue by hm0** [rancher/k3s#2529]
**Environmental Info:**
K3s Version: 

root@aura:/home/hmo# k3s --version
k3s version v1.19.3+k3s3 (0e4fbfef)

Node(s) CPU architecture, OS, and Version: 

2 cores, Linux Ubuntu 20.04, 2 Gb ram.

Cluster Configuration:

1 server (no workers)
**Describe the bug:**

After fresh install of k3s with: curl -sfL https://get.k3s.io | sh -
I notice that local-path-provisioner and metrics-server keep on crashing.
NAMESPACE     NAME                                     READY   STATUS             RESTARTS   AGE
kube-system   coredns-66c464876b-pxzp6                 0/1     Running            0          5m10s
kube-system   helm-install-traefik-vjzqh               1/1     Running            2          5m10s
kube-system   local-path-provisioner-7ff9579c6-hjc5m   0/1     CrashLoopBackOff   4          5m10s
kube-system   metrics-server-7b4f8b595-ck4cs           0/1     CrashLoopBackOff   4          5m10s

**Steps To Reproduce:**

- Installed K3s: 
Just apply a fresh install with root user on a Linux Ubuntu 20.04 2 cores 2 Gb ram.

**Expected behavior:**

It shouldn't show errors.

**Additional context / logs:**

root@aura:/home/hmo# kubectl describe pods local-path-provisioner-7ff9579c6-hjc5m -n=kube-system
Name:         local-path-provisioner-7ff9579c6-hjc5m
Namespace:    kube-system
Priority:     0
Node:         aura/172.16.97.11
Start Time:   Sat, 14 Nov 2020 00:30:55 +0000
Labels:       app=local-path-provisioner
              pod-template-hash=7ff9579c6
Annotations:  <none>
Status:       Running
IP:           10.42.0.2
IPs:
  IP:           10.42.0.2
Controlled By:  ReplicaSet/local-path-provisioner-7ff9579c6
Containers:
  local-path-provisioner:
    Container ID:  containerd://94a0968fcdcf12b4e46a03a07324c35323c283b0759c3b489ee1a9e3eba82f9f
    Image:         rancher/local-path-provisioner:v0.0.14
    Image ID:      docker.io/rancher/local-path-provisioner@sha256:40cb8c984c1759f1860eee088035040f47051c959a6d07cdb126e132c6f43b45
    Port:          <none>
    Host Port:     <none>
    Command:
      local-path-provisioner
      start
      --config
      /etc/config/config.json
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Sat, 14 Nov 2020 00:40:05 +0000
      Finished:     Sat, 14 Nov 2020 00:40:35 +0000
    Ready:          False
    Restart Count:  6
    Environment:
      POD_NAMESPACE:  kube-system (v1:metadata.namespace)
      HELPER_IMAGE:   rancher/library-busybox:1.31.1
    Mounts:
      /etc/config/ from config-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from local-path-provisioner-service-account-token-64jn4 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      local-path-config
    Optional:  false
  local-path-provisioner-service-account-token-64jn4:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  local-path-provisioner-service-account-token-64jn4
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     CriticalAddonsOnly op=Exists
                 node-role.kubernetes.io/master:NoSchedule op=Exists
                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason       Age                  From               Message
  ----     ------       ----                 ----               -------
  Normal   Scheduled    11m                  default-scheduler  Successfully assigned kube-system/local-path-provisioner-7ff9579c6-hjc5m to aura
  Warning  FailedMount  11m                  kubelet            MountVolume.SetUp failed for volume "local-path-provisioner-service-account-token-64jn4" : failed to sync secret cache: timed out waiting for the condition
  Warning  FailedMount  11m                  kubelet            MountVolume.SetUp failed for volume "config-volume" : failed to sync configmap cache: timed out waiting for the condition
  Normal   Pulling      11m                  kubelet            Pulling image "rancher/local-path-provisioner:v0.0.14"
  Normal   Pulled       11m                  kubelet            Successfully pulled image "rancher/local-path-provisioner:v0.0.14" in 21.729800615s
  Normal   Pulled       7m44s (x4 over 10m)  kubelet            Container image "rancher/local-path-provisioner:v0.0.14" already present on machine
  Normal   Created      7m44s (x5 over 11m)  kubelet            Created container local-path-provisioner
  Normal   Started      7m44s (x5 over 11m)  kubelet            Started container local-path-provisioner
  Warning  BackOff      99s (x29 over 10m)   kubelet            Back-off restarting failed container

root@aura:/home/hmo# kubectl describe pods metrics-server-7b4f8b595-ck4cs -n=kube-system
Name:         metrics-server-7b4f8b595-ck4cs
Namespace:    kube-system
Priority:     0
Node:         aura/172.16.97.11
Start Time:   Sat, 14 Nov 2020 00:30:55 +0000
Labels:       k8s-app=metrics-server
              pod-template-hash=7b4f8b595
Annotations:  <none>
Status:       Running
IP:           10.42.0.5
IPs:
  IP:           10.42.0.5
Controlled By:  ReplicaSet/metrics-server-7b4f8b595
Containers:
  metrics-server:
    Container ID:   containerd://01fdbcfb737bd82ca3cd9be303d7c8d299a292739103512112fc0650e795270f
    Image:          rancher/metrics-server:v0.3.6
    Image ID:       docker.io/rancher/metrics-server@sha256:b85628b103169d7db52a32a48b46d8942accb7bde3709c0a4888a23d035f9f1e
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Sat, 14 Nov 2020 00:40:16 +0000
      Finished:     Sat, 14 Nov 2020 00:40:47 +0000
    Ready:          False
    Restart Count:  6
    Environment:    <none>
    Mounts:
      /tmp from tmp-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from metrics-server-token-gkghl (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  tmp-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  metrics-server-token-gkghl:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  metrics-server-token-gkghl
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     CriticalAddonsOnly op=Exists
                 node-role.kubernetes.io/master:NoSchedule op=Exists
                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason       Age                   From               Message
  ----     ------       ----                  ----               -------
  Normal   Scheduled    13m                   default-scheduler  Successfully assigned kube-system/metrics-server-7b4f8b595-ck4cs to aura
  Warning  FailedMount  13m                   kubelet            MountVolume.SetUp failed for volume "metrics-server-token-gkghl" : failed to sync secret cache: timed out waiting for the condition
  Normal   Pulling      13m                   kubelet            Pulling image "rancher/metrics-server:v0.3.6"
  Normal   Pulled       12m                   kubelet            Successfully pulled image "rancher/metrics-server:v0.3.6" in 22.390258711s
  Normal   Pulled       9m23s (x4 over 12m)   kubelet            Container image "rancher/metrics-server:v0.3.6" already present on machine
  Normal   Created      9m23s (x5 over 12m)   kubelet            Created container metrics-server
  Normal   Started      9m23s (x5 over 12m)   kubelet            Started container metrics-server
  Warning  BackOff      3m23s (x28 over 11m)  kubelet            Back-off restarting failed container

**Comment by brandond** [comment]
If things are crashing, pod logs would be useful to have.

**Comment by hm0** [comment]
No luck, I'm trying for now with k3d.
