### ISSUE TITLE
channel server down

### ISSUE THREAD

**Issue by curx** [rancher/k3s#2531]
**Describe the bug:**
channel server seems be down 

**Steps To Reproduce:**
` curl -sfL https://get.k3s.io | sh -` 

```
$ curl -I https://update.k3s.io/v1-release/channels/stable
HTTP/2 503
server: openresty/1.15.8.1
date: Sat, 14 Nov 2020 09:56:32 GMT
content-type: text/html
content-length: 203
strict-transport-security: max-age=15724800; includeSubDomains
https://update.k3s.io/v1-release/channels/stable
```

**Comment by danackerson** [comment]
Something similar for me:
[INFO]  Finding release for channel stable
[INFO]  Using stable as release
[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/stable/sha256sum-arm64.txt

`$ curl -I https://github.com/rancher/k3s/releases/download/stable/sha256sum-arm64.txt
HTTP/1.1 404 Not Found
date: Sat, 14 Nov 2020 10:13:49 GMT
content-type: text/plain; charset=utf-8
server: GitHub.com
status: 404 Not Found
vary: X-PJAX, Accept-Encoding, Accept, X-Requested-With
cache-control: no-cache
strict-transport-security: max-age=31536000; includeSubdomains; preload
x-frame-options: deny
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
referrer-policy: no-referrer-when-downgrade
expect-ct: max-age=2592000, report-uri="https://api.github.com/_private/browser/errors"
`

**Comment by brandond** [comment]
I have alerted our engineering team to take a look at this, but it may not be resolved until the AM (Pacific time).

**Comment by MyIgel** [comment]
Looks to me like the github `latest` redirect is not working? 0o

https://github.com/rancher/k3s/releases/download/latest/sha256sum-amd64.txt -> 404
https://github.com/rancher/k3s/releases/download/v1.19.3%2Bk3s3/sha256sum-amd64.txt -> works

**Comment by danackerson** [comment]
Working again from Germany:

```
$ curl -sfL https://get.k3s.io | sh -
[INFO]  Finding release for channel stable
[INFO]  Using v1.19.3+k3s3 as release
[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v1.19.3+k3s3/sha256sum-arm64.txt
[INFO]  Downloading binary https://github.com/rancher/k3s/releases/download/v1.19.3+k3s3/k3s-arm64
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
```

**Comment by alexellis** [comment]
We were getting 404 errors for the "1.18" release channel. Does anyone know if that's been revoked? @dweomer

**Comment by dweomer** [comment]
Channel server is currently down.

**Comment by yankeexe** [comment]
Works now!

**Comment by saiyam1814** [comment]
works for me - curl -sfL https://get.k3s.io | sh -
```
kubectl get nodes
NAME     STATUS   ROLES    AGE   VERSION
host01   Ready    master   77s   v1.19.3+k3s3
```

**Comment by cjellick** [comment]
appears to be up right now..but possibly intermittently down. we're still investigating

**Comment by cjellick** [comment]
we believe we resolved the intermitent issue. we'll keep an eye on it.

**Comment by AntonOfTheWoods** [comment]
Nope, at least `latest` is not working again

**Comment by curx** [comment]
working:  2020-11-15 @ 13:00 CET:
channel: stable => <a href="https://github.com/rancher/k3s/releases/tag/v1.19.3+k3s3">Found</a>.
channel: testing => <a href="https://github.com/rancher/k3s/releases/tag/v1.19.3+k3s3">Found</a>.
channel: latest => <a href="https://github.com/rancher/k3s/releases/tag/v1.19.3+k3s3">Found</a>.
channel: v1.19 => <a href="https://github.com/rancher/k3s/releases/tag/v1.19.3+k3s3">Found</a>.
channel: v1.18 => <a href="https://github.com/rancher/k3s/releases/tag/v1.18.12+k3s1">Found</a>.
channel: v1.17 => <a href="https://github.com/rancher/k3s/releases/tag/v1.17.14+k3s2">Found</a>.

**Comment by davidnuzik** [comment]
Move to the "To Test" state as we are keeping an eye on it at the moment.

**Comment by davidnuzik** [comment]
Closing. If this issue occurs again we can reopen the issue.

**Comment by lucmichalski** [comment]
could not install k3s also with the command line, from Europe, any ways to sort it out ?

**Comment by mkreuzmayr** [comment]
It looks like the redirects are down again.

[https://github.com/rancher/k3s/releases/download/stable/sha256sum-amd64.txt](https://github.com/rancher/k3s/releases/download/stable/sha256sum-amd64.txt)
