### ISSUE TITLE
INSTALL_K3S_CHANNEL=latest broken

### ISSUE THREAD

**Issue by AntonOfTheWoods** [rancher/k3s#2534]
**Environmental Info:**
K3s Version: latest

Node(s) CPU architecture, OS, and Version: N/A

Cluster Configuration: All

**Describe the bug:**
Github has lost the reference to "latest" for the `INSTALL_K3S_CHANNEL=latest`. Changing for `INSTALL_K3S_CHANNEL=v1.19.3+k3s3` works as expected.

**Steps To Reproduce:**

curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL=latest sh -

**Expected behavior:**
It should install

**Actual behavior:**
`curl https://github.com/rancher/k3s/releases/download/latest/sha256sum-amd64.txt`
returns 
`not found` rather than 
```
ad296fb03eb31334eb88ba4c54690145d3f343bde17a1331803093c544025b4a  k3s
c6fcc39f41d3b7a1f49f8d6494127348b10afca3f9859525833d1eaebb07d6b5  k3s-airgap-images-amd64.tar
f4cf2933e56bfa43494967d1dad25066a404161f720324d1bee91dcd778a2e40  k3s-images.txt
```

**Additional context / logs:**

**Comment by Jpac14** [comment]
Same

**Comment by AntonOfTheWoods** [comment]
Actually this looks like it is a dupe of https://github.com/rancher/k3s/issues/2531, closing as the other issue is still open

**Comment by lucmichalski** [comment]
The same for me, cannot install k3s
