### ISSUE TITLE
Metrics server deployment cannot find 'extension-apiserver-authentication' configmap

### ISSUE THREAD

**Issue by reegnz** [rancher/k3s#254]
**Describe the bug**
I tried to install metrics-server into k3s so I can get kubectl top pods to work.
Once I have deployed metrics-server (with the default manifests in their repo), the metrics-server goes into a Crash Loop.

Checking the logs it seems that it is looking for a configmap named 'extension-apiserver-authentication':
```
I0322 11:02:58.536227       1 serving.go:273] Generated self-signed cert (apiserver.local.config/certificates/apiserver.crt, apiserver.local.config/certificates/apiserver.key)
W0322 11:02:59.211219       1 authentication.go:245] Unable to get configmap/extension-apiserver-authentication in kube-system.  Usually fixed by 'kubectl create rolebinding -n kube-system ROLE_NAME --role=extension-apiserver-authentication-reader --serviceaccount=YOUR_NS:YOUR_SA'
Error: configmaps "extension-apiserver-authentication" not found
```

Apparently that's something that the api-server is supposed to create:
https://kubernetes.io/docs/tasks/access-kubernetes-api/configure-aggregation-layer/#kubernetes-apiserver-client-authentication

(Sidenote: I wonder if k3s supports those startup args).

**To Reproduce**
1. Install metrics-server by applying the manifests from https://github.com/kubernetes-incubator/metrics-server/tree/master/deploy/1.8%2B
2. Observe CrashLoopBackoff behaviour with kubectl get pods -n kube-system

**Expected behavior**
metrics server should be able to provide node and pod metrics to the api server through the metrics API. kubectl top nodes and kubectl top pods should then work properly.

**Comment by reegnz** [comment]
It also seems like #208 has the same root cause.

**Comment by hjacobs** [comment]
Related: #252

**Comment by dnoland1** [comment]
Kubectl top works now on v0.4.0-rc3. See https://github.com/rancher/k3s/issues/252#issuecomment-483474051

**Comment by csreegn** [comment]
great!
