### ISSUE TITLE
RancherCD - Support for Jsonnet/Tanka

### ISSUE THREAD

**Issue by ghostsquad** [rancher/k3s#2549]
**Is your feature request related to a problem? Please describe.**
I use [jsonnet](https://github.com/google/go-jsonnet) to generate my yaml manifests, and those yaml files do not get checked into Git. As such, I cannot use the Rancher CD GitOps without support for....

**Describe the solution you'd like**
At minimum, the ability to run an arbitrary step to _generate_ the files that RancherCD then looks for.

**Describe alternatives you've considered**
I've thought about generating yaml files and committing them to a separate repo via an automated workflow, but that seems complicated for no good reason.

**Additional context**

**Comment by brandond** [comment]
I'm not sure that this is the correct repo for this request. Did you mean to create this at https://github.com/rancher/rancher/issues ?

**Comment by ghostsquad** [comment]
should be here. Sorry! I'm moving it
https://github.com/rancher/fleet
