### ISSUE TITLE
K3s certs expired ; cant access anything.

### ISSUE THREAD

**Issue by luisbrandao** [rancher/k3s#2550]
Hello,
I just lost access to my k3s. 

I had the certs check this week to if if they had been auto-updated...  and it seen so:

```
[root@vmpkube001 tls]# pwd
/var/lib/rancher/k3s/server/tls
[root@vmpkube001 tls]# for crt in *.crt; do      printf '%s: %s\n'      "$(date --date="$(openssl x509 -enddate -noout -in "$crt"|cut -d= -f 2)" --iso-8601)"      "$crt"; done | sort
2021-09-18: client-admin.crt
2021-09-18: client-auth-proxy.crt
2021-09-18: client-cloud-controller.crt
2021-09-18: client-controller.crt
2021-09-18: client-k3s-controller.crt
2021-09-18: client-kube-apiserver.crt
2021-09-18: client-kube-proxy.crt
2021-09-18: client-scheduler.crt
2021-09-18: serving-kube-apiserver.crt
2029-11-03: client-ca.crt
2029-11-03: request-header-ca.crt
2029-11-03: server-ca.crt

```

but the cli is broken:
![image](https://user-images.githubusercontent.com/25795753/99576367-a68e5880-29b8-11eb-8840-7a419b9af7eb.png)

Same goes to the dashboard:

![image](https://user-images.githubusercontent.com/25795753/99576490-d2a9d980-29b8-11eb-9721-f53fec55108d.png)

The cluster "age" was about 380~something days.
I am running a "v1.18.12+k3s1" in a centos7 cluster.

I change the date on the server to be able to execute kubectl again...
![image](https://user-images.githubusercontent.com/25795753/99577926-ce7ebb80-29ba-11eb-8808-3ad545e27763.png)
The secrets are wrong... how to update this?

Node logs:
`Nov 18 16:34:17 pmpnode001.agrotis.local k3s[6089]: time="2020-11-18T16:34:17.400604478-03:00" level=error msg="server https://127.0.0.1:33684/cacerts is not trusted: Get https://127.0.0.1:33684/cacerts: x509: certificate has expired or is not yet valid"
`

**Comment by schmitch** [comment]
reboot should renew them

**Comment by brandond** [comment]
Correct, restarting k3s should update the certificates automatically. If this is not occurring, can you provide logs from the k3s server?

**Comment by luisbrandao** [comment]
I rebooted k3s daemon; the server; the entire cluster; nothing. I even notice that the  /etc/rancher/k3s/k3s.yaml has been touched recently, but the data is the same.

**Comment by luisbrandao** [comment]
K3s log:
https://gist.github.com/luisbrandao/7bd49615947f03c0ba7df99d1f9ac237

**Comment by brandond** [comment]
Are you able to test with 1.19.4? There was some additional work done in this space but I can't remember if it was backported or not: https://github.com/rancher/k3s/pull/2053

**Comment by luisbrandao** [comment]
Yes, you didnt backport to 1.18.x..... ¬¬

everything is up again at 1.19.4. thanks.
