### ISSUE TITLE
Test and certify CENTOS/RHEL 7.9

### ISSUE THREAD

**Issue by davidnuzik** [rancher/k3s#2561]
We'd like to add CentOS and RHEL 7.9 to the SLA Support matrix for upcoming Rancher 2.4.11 and 2.5.3 planned for release 11/30.

This will need testing soon, and well before the 11/30 release date so we can update our draft of the support matrix ahead of time.

Testing should cover these specific versions:
- v1.18.12+k3s1
- v1.19.3+k3s3
- v1.19.4+k3s1

Ensure that:
- Installs fine on nodes. No obvious issues. 
- Can add as downstream cluster in Rancher 2.4.11 RC and 2.5.3 RC. No obvious issues.
- Can run as Rancher control plane for specifically Rancher 2.5.3 RC. No obvious issues.

**Comment by ShylajaDevadiga** [comment]
Validated k3s on 2.5.3 rc as downstream cluster
![image](https://user-images.githubusercontent.com/56045581/100136836-64459b00-2e40-11eb-97b4-a59bc1b7974d.png)
Validated k3s on 2.4.11 rc as downstream cluster
![image](https://user-images.githubusercontent.com/56045581/100136944-87704a80-2e40-11eb-9c8e-fe9569a787db.png)

![image](https://user-images.githubusercontent.com/56045581/100139367-395d4600-2e44-11eb-8419-9a2f37231069.png)
![image](https://user-images.githubusercontent.com/56045581/100139661-a96bcc00-2e44-11eb-87fe-e4960695d92a.png)
![image](https://user-images.githubusercontent.com/56045581/100139720-bc7e9c00-2e44-11eb-8f54-e5505622d8b8.png)

![image](https://user-images.githubusercontent.com/56045581/100142686-29943080-2e49-11eb-8da3-80a76d70b6ef.png)
![image](https://user-images.githubusercontent.com/56045581/100142719-357ff280-2e49-11eb-995e-eac52bd27b0c.png)
![image](https://user-images.githubusercontent.com/56045581/100142770-46306880-2e49-11eb-9eb2-6e1643eb5746.png)
