### ISSUE TITLE
k3s installation failed  ErrImagePull.....

### ISSUE THREAD

**Issue by tanjunchen** [rancher/k3s#2562]
**What kind of request is this (question/bug/enhancement/feature request):**

installation

**Steps to reproduce (least amount of steps as possible):**

curl -sfL http://rancher-mirror.cnrancher.com/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn sh -

kubectl get nodes 
kubectl get pods -A

**Result:**
![image](https://user-images.githubusercontent.com/19339970/99697420-b007e580-2aca-11eb-8a57-cb9a621cd134.png)

![image](https://user-images.githubusercontent.com/19339970/99697798-070dba80-2acb-11eb-8ac4-eed47955105a.png)

**Other details that may be helpful:**

The pod has been pulling images, the deployment strategy is IfNotPresent, and the image exists in docker. Is there a problem with the docker version?

```
root@tanjunchen:/home/tanjunchen/istioproject# uname -r
5.4.0-54-generic
root@tanjunchen:/home/tanjunchen/istioproject# uname -a
Linux tanjunchen 5.4.0-54-generic rancher/rancher#60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
 kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3+k3s3", GitCommit:"0e4fbfefe1dd8734756dfa4f9ab4fc89665cece4", GitTreeState:"clean", BuildDate:"2020-11-13T07:19:02Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3+k3s3", GitCommit:"0e4fbfefe1dd8734756dfa4f9ab4fc89665cece4", GitTreeState:"clean", BuildDate:"2020-11-13T07:19:02Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:52 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:20 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by tanjunchen** [comment]
@maggieliu  thanks for your reply.
It doesn't seem to be very useful, I have used other tools.   thank you.
/close

**Comment by tanjunchen** [comment]
@maggieliu 
could you  confirm why the image pull strategy of k3s is problematic? It really slow to start pods. I set the image policy to be local first, but It still try to pull the mirror.
see
```
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  104s  default-scheduler  Successfully assigned istio-system/istiod-6896775fb6-6mg4v to tanjunchen
  Normal  Pulling    104s  kubelet            Pulling image "docker.io/istio/pilot:1.8.0"
root@tanjunchen:~/istiogoproject# docker images | grep  istio
istio/operator                                                    1.8.0               5a03f6ffd41d        6 days ago          265MB
istio/pilot                                                       1.8.0               5f29b94e66b6        6 days ago          263MB
istio/pilot                                                       1.7.4               d241dd7c5ad9        4 weeks ago         261MB
```

kubectl get deployment istiod  -n istio-system -oyaml
```
 image: docker.io/istio/pilot:1.8.0
          imagePullPolicy: IfNotPresent
```

**Comment by brandond** [comment]
@tanjunchen what is the issue here? It looks like you didn't have 1.8.0 on your node, so it was pulled from the registry.

**Comment by tanjunchen** [comment]
My depoyment imagePullPolicy is IfNotPresent, and this image exists locally. K3s seems to pull the mirror every time.

**Comment by brandond** [comment]
Can you show logs of it repulling the image? Slow startup times could be from other things. I'm not aware of any issues that would cause the image pull policy to not be respected.
