### ISSUE TITLE
Allow to specify interface to flannel

### ISSUE THREAD

**Issue by uablrek** [rancher/k3s#259]
**Is your feature request related to a problem? Please describe.**

There are [options to flannel](https://github.com/coreos/flannel/blob/master/Documentation/configuration.md#key-command-line-options) to specify the interface used for vxlan. The default is to use the interface of the default route. But if the default route has multiple hops;

```
# ip ro
default 
        nexthop via 192.168.1.201 dev eth1 weight 1 
        nexthop via 192.168.1.202 dev eth1 weight 1 
```

Then `k3s` fails with;

```
FATA[2019-03-24T12:28:35.562033903Z] flannel exited: failed to get default interface: Found default route but could not determine interface
```

Another case is of course if the default route points to an interface where vxlan between nodes is unwanted or impossible.

**Describe the solution you'd like**

I would like a command line option (or similar) that allows specification of the interface to `flannel`. Or perhaps even better to allow any extra option to be passed to `flannel`.

**Describe alternatives you've considered**

To disable the included flannel CNI plugin and use an own CNI plugin. But that removes some of the desired "easy-to-use" feature of `k3s`.

**Additional context**

The problem happened when setting up `k3s` on [xcluster](https://github.com/Nordix/xcluster). It now works fine with just one hop on the dfault route. Please check the [k3s ovl](https://github.com/Nordix/xcluster/tree/master/ovl/k3s) for more info.

IMHO this is a really simple way to try `k3s` in a cluster and may be suitable for e2e tests. But I am biased since I am the author of xcluster.

**Comment by aaliddell** [comment]
https://github.com/rancher/k3s/pull/250 should cover this if merged

**Comment by uablrek** [comment]
I can confirm that with PR https://github.com/rancher/k3s/pull/250 applied my problem is solved and `k3s` works with a multi-dest default route.
I close this issue since it is a duplicate.
