### ISSUE TITLE
Can't disable traefik in HA

### ISSUE THREAD

**Issue by bamnet** [rancher/k3s#2598]
**Environmental Info:**
K3s Version:  k3s version v1.19.3+k3s3 (0e4fbfef)

Node(s) CPU architecture, OS, and Version: 
Linux 5.8.0-29-generic #31-Ubuntu SMP Fri Nov 6 12:37:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Linux 5.8.0-1007-raspi #10-Ubuntu SMP PREEMPT Thu Nov 5 18:01:40 UTC 2020 armv7l armv7l armv7l GNU/Linux

Cluster Configuration: 3 masters, 1 worker

**Describe the bug:**
I installed a HA cluster on 2 Raspberry Pis and 2 x86_64 boxes, but I forgot to disable traefik when installing the server/master nodes.  I've gone through and purged whatever traces of traefik I can find according to the documentation, but it still randomly respawns.. often a few hours after I've finished removing it.

**Steps To Reproduce:**

- Installed K3s, but forgot to disable traefik.  Oops.
- Removed running traefik pods with `kubectl -n kube-system delete helmcharts.helm.cattle.io traefik`
- Removed traefik manifest with `rm /var/lib/rancher/k3s/server/manifests/traefik.yaml` from all 3 master nodes.
- Added `--disable traefik` to `/etc/systemd/system/k3s.service` on all 3 master nodes and ran `systemctl daemon-reload`.
- Wait several hours.
- Traefik rises from the ashes and starts running again, clobbering existing services I have running on port 80 and 443.

**Expected behavior:**
Traefik remains disabled.

**Actual behavior:**
Traefik respawns for an unknown reason.

**Additional context / logs:**

**Comment by brandond** [comment]
> Added --disable traefik to /etc/systemd/system/k3s.service on all 3 master nodes and ran systemctl daemon-reload.

You need to restart k3s after reloading the systemd configuration. That should do it.

**Comment by bamnet** [comment]
I went ahead and ran `sudo systemctl daemon-reload && sudo systemctl restart k3s` on all the master nodes. Within a few seconds of one of them coming back up, a fresh copy of traefik emerged.  This roughly matches my memory that I physically restarted some / all of the masters during my early troubleshooting steps.

Is there anywhere else it could be hiding?  My cluster is new enough that I can tear it down and start fresh with `--disable traefik` when installing but this feels like a very strange bug.

```
kube-system                    helm-install-traefik-7bpsh                       1/1     Running       0          35s
```

**Comment by bamnet** [comment]
I've also tried purging the addons, since it sounds like that's how Helm charts are getting automagically added:

```
 kubectl delete addon traefik -n kube-system
 kubectl delete addon traefik-config -n kube-system
```

Will wait to see if it rises again.

**Comment by bamnet** [comment]
I decided to tear down and rebuild the cluster with `--disable traefik` from the start, closing.
