### ISSUE TITLE
unikernel

### ISSUE THREAD

**Issue by pierreozoux** [rancher/k3s#26]
I have a silly idea and I have to share it :)

Do we need systemd and journals to run kubernetes?  Or could we craft a special Linux just with what we need?

I'm just wondering how much memory we would save and if it is worth it or not :)

**Comment by ibuildthecloud** [comment]
`systemd` is extremely lightweight, minuscule compared to kubernetes or k3s so probably not worth it.  But if you are someone like me that just hates systemd regardless, totally worth it.  k3s has zero host dependency.  It just need a sane kernel and valid /proc, /sys, /dev setup.  So one could easily boot a linux system and run k3s.  It is on my TODO list to create a "k3sOS" but don't count on me getting around to it soon :)

**Comment by kardianos** [comment]
I'm not sold on unikernals, but I am a fan of removing extra parts. As an alternative to a true unikernel  would be to use https://gokrazy.org/ for a rpi3 release or https://talos.autonomy.io/ for a x64 release.

**Comment by justincormack** [comment]
It should be pretty simple to drop it into https://github.com/linuxkit/kubernetes which is pretty much as minimal as you get for a Linux distro running kub (if you use the containerd version).

**Comment by taigrr** [comment]
Is this issue closeable now given the existence of [this repo?](https://github.com/rancher/k3os)
