### ISSUE TITLE
Changing Cluster CIDR after initialization causes panic

### ISSUE THREAD

**Issue by jamescun** [rancher/k3s#2603]
**Environmental Info:**
K3s Version: 
`k3s version v1.19.3+k3s3 (0e4fbfef)`

Node(s) CPU architecture, OS, and Version: 
`Linux k8s 5.4.72-0-virt #1-Alpine SMP Mon, 19 Oct 2020 06:22:29 UTC x86_64 Linux`

Cluster Configuration:
1 Master, 0 Nodes

**Describe the bug:**
I am experimenting with K3s in the situation where an overlay network (in this instance, WireGuard) already exists, and how to establish static routing of Pod IPs across this overlay.

Initially K3s was started with no network configuration. Subsequently it is started with a network configuration, after about 10 seconds the agent crashes.

Possibly related to https://github.com/rancher/k3s/issues/93#issuecomment-470182596

**Steps To Reproduce:**
- Installed K3s, only specifying `'--disable=traefik --flannel-backend=none --cluster-cidr=100.64.1.0/24'`
- Kubelet fails to start (as expected), lacking CNI configuration.
- Update rc to specify `--flannel-backend=wireguard` removing `--cluster-cidr` entirely.

**Expected behavior:**
Expected K3s to handle its new CNI configuration.

**Actual behavior:**
After ~10s the agent crashes (taking the master with it).

**Additional context / logs:**
```
F1130 12:27:52.694868    5345 controllermanager.go:249] error starting controllers: failed to mark cidr[100.64.1.0/24] at idx [0] as occupied for node: k8s: cidr 100.64.1.0/24 is out the range of cluster
cidr 10.42.0.0/16
goroutine 5144 [running]:
github.com/rancher/k3s/vendor/k8s.io/klog/v2.stacks(0xc000122001, 0xc01593a480, 0xde, 0x212)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:996 +0xb9
github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).output(0x6ea13c0, 0xc000000003, 0x0, 0x0, 0xc016f04cb0, 0x6b2f0fd, 0x14, 0xf9, 0x0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:945 +0x191
github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).printf(0x6ea13c0, 0xc000000003, 0x0, 0x0, 0x4508f5a, 0x1e, 0xc017d51398, 0x1, 0x1)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:733 +0x17a
github.com/rancher/k3s/vendor/k8s.io/klog/v2.Fatalf(...)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:1456
github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app.Run.func1(0x4c2c760, 0xc00011e018)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:249 +0x68e
github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app.Run(0xc00d1d2ab8, 0xc000102660, 0xc0062f6950, 0xc006d7c1b8)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:260 +0x9b1
github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app.NewControllerManagerCommand.func2(0xc006e0ab00, 0xc01053c0e0, 0x0, 0xe)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:124 +0x2b7
github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).execute(0xc006e0ab00, 0xc001fc3500, 0xe, 0x10, 0xc006e0ab00, 0xc001fc3500)
	/go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:846 +0x2c2
github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc006e0ab00, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:950 +0x375
github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:887
github.com/rancher/k3s/pkg/daemons/executor.Embedded.ControllerManager.func1(0xc002d54000, 0xc006e0ab00)
	/go/src/github.com/rancher/k3s/pkg/daemons/executor/embed.go:79 +0x46```

**Comment by brandond** [comment]
I'm not sure that it's expected that the cluster pod and service CIDRs can be changed once the cluster is up and running. The nodes are allocated smaller blocks within the CIDRs when they join the cluster, and these are not reallocated when the CIDR changes. Similarly, cluster critical services like DNS cannot easily be changed once set.

**Comment by jamescun** [comment]
> I'm not sure that it's expected that the cluster pod and service CIDRs can be changed once the cluster is up and running. The nodes are allocated smaller blocks within the CIDRs when they join the cluster, and these are not reallocated when the CIDR changes. Similarly, cluster critical services like DNS cannot easily be changed once set.

Apologies @brandond if I phrased my original report badly!

I was not expecting my configuration to work, the unexpected behavior was changing the CNI to a working configuration resulting in a panic, which I don't think is an unreasonable expectation, particularly for newcomers or when bootstraping a new cluster.

**Comment by brandond** [comment]
Your cluster was already bootstrapped once; the datastore will need to be wiped at this point to change the configuration. Do you have a suggestion on how we could better handle this sort of invalid configuration?
