### ISSUE TITLE
Provide k8s.gcr.io/pause through docker.io

### ISSUE THREAD

**Issue by gabrielcalderon** [rancher/k3s#263]
Currently I can't pull k8s.gcr.io/pause:3.1, I keep getting a authentication error. Why isnt this image provided through docker.io?

**Comment by warmchang** [comment]
Running k3s on an airgap environment: https://github.com/rancher/k3s/issues/172#issuecomment-476339625

**Comment by erikwilson** [comment]
Closing this since there are some other issues which describe the problem and work-around. Please re-open with more info if you think this is not sufficient.
