### ISSUE TITLE
Node Name

### ISSUE THREAD

**Issue by adi90x** [rancher/k3s#271]
Hello, 

Seems like  `--node-name` is not working in v0.0.2.
Got an error : 
`INFO[2019-03-27T20:22:48.803625301+01:00] Waiting for containerd startup: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial unix /run/k3s/containerd/containerd.sock: connect: connection refused" 
containerd: exit status 1`

While it work perfectly without the `--node-name` set.
Is it something known ?

**Comment by erikwilson** [comment]
@adi90x could you provide some more info please? How many nodes are creating, and what value are you using for the node-name(s)?

**Comment by adi90x** [comment]
Hello,

Only creating one, trying to use a random name (only lowercase a-z)
The node is starting fine without the flag, but fail with.
I am not sure it failed due to the error reported in first thread as this
error seems to also happen when it start correctly.

Any clue on that ?

Le jeu. 28 mars 2019 à 19:08, Erik Wilson <notifications@github.com> a
écrit :

**Comment by warmchang** [comment]
Duplicate, try this: https://github.com/rancher/k3s/issues/138#issuecomment-469338640

**Comment by deniseschannon** [comment]
@adi90x please try the comment and let me know if that works for you.

**Comment by adi90x** [comment]
Sorry for the delay , adding the name to `/etc/hosts` is perfectly working ! 
Thanks a lot, closing the issue,
However how complicated it is to automatically add the name to the hosts file in the starting script ?
