### ISSUE TITLE
Kata containers is not able to find containerd.service

### ISSUE THREAD

**Issue by bithavoc** [rancher/k3s#274]
**Describe the bug**
While trying to follow Kata containers [instructions](https://katacontainers.io/posts/kata-deploy-install-kata-containers-kubernetes/) for Kubernetes I found that `kata-deploy` doesn't work, the logs report:

```sh
#!/bin/bash
KATA_CONF_FILE=/opt/kata/share/defaults/kata-containers/configuration.toml /opt/kata/bin/containerd-shim-kata-v2 $@
Failed to restart containerd.service: Unit containerd.service not found.
```

**To Reproduce**
* Install a basic k3s
* `kubectl apply -f https://raw.githubusercontent.com/kata-containers/packaging/master/kata-deploy/kata-rbac.yaml`
* `kubectl apply -f https://raw.githubusercontent.com/kata-containers/packaging/master/kata-deploy/kata-deploy.yaml`
* Check the logs for the error message: `kubectl log <kata-deploy-pod-name> --namespace kube-system `

**Expected behavior**
Kata containers deploy should not crash.

**Comment by erikwilson** [comment]
@bithavoc Even though we ship with containerd we do not set up or provide a systemd containerd.service. I was able to get it working by installing a containerd systemd servive with `sudo apt-get install containerd.io` (on ubuntu). I am not sure it is a great idea of kata to depend on systemd, and not sure if having two containerds running will cause a problem, but with that service started the error appears to go away:
```
erik@lubuntu:~/go/src/github.com/rancher/k3s$ kubectl logs -n kube-system kata-deploy-tglb7
time="2019-03-28T18:51:35Z" level=info msg="Preparing data dir /var/lib/rancher/k3s/data/9c715b28c65f6c2cc540939699c07d35e1bf3b42034370ed2f65c53e59423a1f"
copying kata artifacts onto host
Add Kata Containers as a supported runtime for containerd
[plugins]
  [plugins.cri]
   [plugins.cri.containerd]
     [plugins.cri.containerd.runtimes.kata]
warning: containerd-shim-kata-v2 already exists
        runtime_type = "io.containerd.kata.v2"
#!/bin/bash
KATA_CONF_FILE=/opt/kata/share/defaults/kata-containers/configuration.toml /opt/kata/bin/containerd-shim-kata-v2 $@
node/lubuntu labeled
```

**Comment by bithavoc** [comment]
@erikwilson thanks for the response.

Will k3s use a previously installed containerd runtime?

**Comment by erikwilson** [comment]
It should be, will probably need to install cri-o also, see rancher/k3s/issues/107

**Comment by bithavoc** [comment]
Thanks, I'm going to close this for now.
