### ISSUE TITLE
Ignore swap (.swp) files in manifests folder

### ISSUE THREAD

**Issue by dnoland1** [rancher/k3s#280]
**Describe the bug**
I created a manifest in /var/lib/rancher/k3s/server/manifests/test.yaml and started k3s in server mode. Decided to edit the file using vi, which generates a .swp file in the same folder. This caused the following error message about every 15 seconds:
```
ERRO[2019-03-29T05:16:53.428115408Z] failed to process config: failed to process /var/lib/rancher/k3s/server/manifests/.test.yaml.swp: yaml: control characters are not allowed
ERRO[2019-03-29T05:17:08.429939965Z] failed to process config: failed to process /var/lib/rancher/k3s/server/manifests/.test.yaml.swp: yaml: control characters are not allowed
```
**To Reproduce**
See above

**Expected behavior**
Would be nice if .swp files were ignored. Not sure if it would make sense to have a whitelist of extensions like ".yml", ".yaml", etc. or a blacklist of extensions to ignore like ".swp", ".bak", etc.

**Additional context**
Discovered while testing https://github.com/rancher/k3s/issues/222

**Comment by deniseschannon** [comment]
We should do the reverse in look for only `.yml`, `.yaml` and `.json` only files.

**Comment by deniseschannon** [comment]
and ignore any files that start with `.`

**Comment by dnoland1** [comment]
Tested on v0.5.0-rc3 (21a9dbe2). Successfully deployed files named `test.yaml` and `test.yml` by placing in `/var/lib/rancher/k3s/server/manifests`. Confirmed files with .swp and .txt were ignored. `.test.yml` was also ignored. Working as expected, closing issue.
