### ISSUE TITLE
Upgrade istio to use autoscaling/v2beta2

### ISSUE THREAD

**Issue by erikwilson** [rancher/k3s#285]
**Describe the solution you'd like**
Istio should work out of the box with k3s, we do not support autoscaling/v2beta1 so need to upgrade to autoscaling/v2beta2

**Additional context**
rancher/k3s/issues/90
istio/istio/issues/12823

**Comment by deniseschannon** [comment]
`autoscaling/v2beta1` is now available in v0.4.0-rc1.
