### ISSUE TITLE
Is it possible to cache images on host?

### ISSUE THREAD

**Issue by moltar** [rancher/k3s#296]
I'm testing a big deployment, and every time I restart the k3s cluster, I have to pull all of the images each time.

Is there a way to cache the images? Maybe on the host somehow?

I'm using macOS Docker.

Thanks.

**Comment by warmchang** [comment]
You can put the tar image files (docker save) in "/var/lib/rancher/k3s/agent/images/": https://github.com/rancher/k3s#air-gap-support

**Comment by deniseschannon** [comment]
@moltar the airgap support was added in v0.3.0.

If you still have an issue/questions, please open a new issue.
