### ISSUE TITLE
Remove hostname requirement in `/etc/hosts`

### ISSUE THREAD

**Issue by deniseschannon** [rancher/k3s#299]
Currently, we need to  ensure in the `/etc/hosts` file, the current hostname (output of hostname) is set to a 127.x.x.x address. For example:

```
127.0.1.1	myhost
```

**Comment by uablrek** [comment]
I guess this is to get the TLS certificates generated right. If so there is already an alternative;
```
k3s server --tls-san myhost ...
```

**Comment by uablrek** [comment]
Sorry, I did not see #193 please ignore my remark above.
