### ISSUE TITLE
dqlite for HA database

### ISSUE THREAD

**Issue by de13** [rancher/k3s#300]
As I mentioned [#106](https://github.com/rancher/k3s/issues/106), [dqlite](https://github.com/CanonicalLtd/dqlite) from Canonical  should be a nice improvement over sqlite.

**Comment by ibuildthecloud** [comment]
I'm open to this, but don't really want to be the test bed.  So I'd love to hear just how mature dqlite is and hows the performance.

**Comment by warmchang** [comment]
The Distributed SQLite:
https://github.com/CanonicalLtd/dqlite
https://github.com/rqlite/rqlite

Or just package the etcd in the all in one k3s binary.

**Comment by lygstate** [comment]
prefer rqlite

**Comment by ibuildthecloud** [comment]
rqlite looks quite nice.

**Comment by babykart** [comment]
+1 for rqlite

**Comment by xiaods** [comment]
+1 for rqlite

**Comment by huapox** [comment]
How is it going?  (rqlite)

**Comment by erikwilson** [comment]
We will probably go with dqlite for this, quickly comparing the two it seems to be the more appropriate choice. There are some static builds of the library available here: https://github.com/rancher/dqlite-build

**Comment by ShylajaDevadiga** [comment]
Verified dqlite with 4 nodes(all master and workers). Successfully passed basic testing of add/remove nodes, adding workloads, daemonsets.
