### ISSUE TITLE
Provide arm64v8 pv/pvc layer

### ISSUE THREAD

**Issue by giminni** [rancher/k3s#304]
There is no description what storage layer can be used for an arm64 k3s cluster

**Comment by ekultails** [comment]
I have successfully used `hostPath` and `nfs` for persistent storage on arm64v8 devices (Rock64's).

I agree that having explicit documentation around what storage plugins are available in k3s would be helpful.

**Comment by ibuildthecloud** [comment]
I don't have a specific recommendation here.  Any CSI driver that support arm64 should work on k3s on arm64.  There is a list of drivers available here https://kubernetes-csi.github.io/docs/drivers.html

Also note that we are fixing some CSI related issues that are in v0.4.0-rc1.  So you might want to start there if you are using CSI.
