### ISSUE TITLE
old traefik replica set doesn't delete

### ISSUE THREAD

**Issue by tfiduccia** [rancher/k3s#306]
Version - v0.3.0

**To Reproduce**
1.  edit the /var/lib/rancher/k3s/server/manifests/traefik.yaml so the chart is pointed to stable/traefik
2.  save edit
3.  k3s kubectl get all --all-namespaces (repeat until job.batch/helm-install-traefik has been completed)  

Results:
The old replicaset.app/traefik-<id>, doesn't delete.  So now you have two.  one that is ready and one that is not
![image](https://user-images.githubusercontent.com/11514927/55590759-a6a8ea00-56e8-11e9-9c38-164e5129e3e4.png)

**Expected behavior**
Even thou the old replicaset is not ready, we should still clean it up.

**Comment by reegnz** [comment]
That's a feature (and default behaviour) of the Deployment kind.
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#rolling-back-a-deployment

That's how you do rollbacks of a deployment: the controller scales down the new rs and scales up the old one.

**Comment by tfiduccia** [comment]
Not an issue
