### ISSUE TITLE
coredns pod keeps restarting when setup on behind proxy server

### ISSUE THREAD

**Issue by tfiduccia** [rancher/k3s#307]
Version - v0.3.0

**To Reproduce**
1.  Setup a proxy server
2.  Install and run k3s machine behind proxy

Results:  coredns pod keeps restarting
![image](https://user-images.githubusercontent.com/11514927/55590715-8547fe00-56e8-11e9-9013-6845c8a65f7a.png)

**Expected behavior**
Shouldn't keep restarting

**Comment by ldcastell** [comment]
This worked for me: 
1. Switch to root

2. set your proxy env variables
```
export http_proxy=http://yourproxy.com:8129
export https_proxy=http://yourproxy.com:8130
# Here we add the cluster-cdir and service-cluster-ip-range to the no_proxy env
export no_proxy=localhost,<node IP Address>,<add as you need>,10.43.0.0/16,10.42.0.0/16
```
or add them to the /etc/environment file 

3. Finally start the k3s server:
```
./k3s server --node-ip <your node IP> &
```
NOTE: I guess the `--node-ip` is irrelevant here.
This worked for me, I hope it works for you too

**Comment by tfiduccia** [comment]
Version - v0.4.0-rc3
Verified fixed
