### ISSUE TITLE
In Proxy setup, helm install pod won't start if I use stable/traefik for chart

### ISSUE THREAD

**Issue by tfiduccia** [rancher/k3s#308]
Version - v0.3.0

**To Reproduce**
1.  Setup proxy server
2.  Put k3 on machine behind server
3.  edit /var/lib/rancher/k3s/server/manifests/traefik.yaml and change chart to point at stable/traefik

Results: helm-install-traefik-<id> pod keeps restarting and the job never completes
![image](https://user-images.githubusercontent.com/11514927/55591022-5b430b80-56e9-11e9-83f0-0a84e395a8e3.png)

**Expected behavior**
Should restart and job should complete

**Comment by deniseschannon** [comment]
@galal-hussein Investigate how to pass the proxy variables to helm install job from the helm controller

**Comment by tfiduccia** [comment]
Version - v0.5.0-rc3
Verified fixed

**Comment by tfiduccia** [comment]
Version - 0.5.0-rc2
This is still broken
Error for pod in logs: 

[storage/driver] 2019/05/02 21:16:43 list: failed to list: Get https://10.43.0.1:443/api/v1/namespaces/kube-system/secrets?labelSelector=OWNER%3DTILLER: Unable to connect
Error: Get https://10.43.0.1:443/api/v1/namespaces/kube-system/secrets?labelSelector=OWNER%!D(MISSING)TILLER: Unable to connect


![image](https://user-images.githubusercontent.com/11514927/57107321-8c146180-6ce4-11e9-9321-3805eb5af659.png)

**Comment by erikwilson** [comment]
This should be fixed in 0.5.0-rc4

**Comment by tfiduccia** [comment]
Version - v0.5.0-rc4
Verified fixed.
