### ISSUE TITLE
Import k3s on rancher traefik wss

### ISSUE THREAD

**Issue by giovannicandido** [rancher/k3s#310]
Hi,
I have a single node k3s server with rancher successfully installed.
I create a new 2 node k3s cluster, which I want to import.

The cluster keeps in pending state. Investigation leads me to this log in traefik:

```
{"level":"error","msg":"vulcand/oxy/forward/websocket: Error dialing \"rancher.xx.xx\": websocket: bad handshake with resp: 200 200 OK","time":"2019-04-06T01:59:24Z"}
{"level":"error","msg":"vulcand/oxy/forward/websocket: Error dialing \"rancher.xxx.xxx\": websocket: bad handshake with resp: 200 200 OK","time":"2019-04-06T01:59:34Z"}
```

I did add `traefik.backend.loadbalancer.sticky: "true"` annotation to rancher service.

Ingress description:

```
Name:             rancher
Namespace:        cattle-system
Address:
Default backend:  default-http-backend:80 (<none>)
TLS:
  tls-rancher-ingress terminates rancher.xx.xx
Rules:
  Host                  Path  Backends
  ----                  ----  --------
  rancher.kugelbit.com
                           rancher:80 (<none>)
Annotations:
  nginx.ingress.kubernetes.io/proxy-read-timeout:     1800
  nginx.ingress.kubernetes.io/proxy-send-timeout:     1800
  nginx.ingress.kubernetes.io/proxy-connect-timeout:  30
Events:                                               <none>
```

Did I miss something?

**Comment by deniseschannon** [comment]
Are you able to import any clusters into Rancher? I'm not sure this is a k3s cluster specific issue. 

If you can import other k8s clusters, then it'll be a rancher issue and should be filed in rancher/rancher.

**Comment by giovannicandido** [comment]
Agreed, closing the issue...
Thanks.

**Comment by geoffjukes** [comment]
@giovannicandido I am having this issue and have been unable to find any hints. We’re you able to fix it? And if so, would you mind sharing how?
