### ISSUE TITLE
Provide helm controller as "normal" operator

### ISSUE THREAD

**Issue by cwrau** [rancher/k3s#312]
**Is your feature request related to a problem? Please describe.**
I'd like to use the helm controller in other Clusters as well. E.g. cloud providers

**Describe the solution you'd like**
A helm chart that installs an operator that takes the role of the helm controller.

**Describe alternatives you've considered**
[Bitnami](https://github.com/bitnami-labs/helm-crd) seems to have one, but theirs is experimental.

**Additional context**

**Comment by runningman84** [comment]
What about using flux? It also offers a helm operator and can run anywhere

**Comment by cwrau** [comment]
Flux? You mean [Weaveworks](https://github.com/weaveworks/flux)?
I didn't know about that, thanks!

But depending on the use case, flux seems to be too much?
It is a tool for GitOps, which just (coincidentally) supports Helm charts.

A single operator would be nice as well

**Comment by runningman84** [comment]
yes I mean flux from weaveworks. Defining all configs/manifests in a git repo makes sense anyway from my point of view...

**Comment by cwrau** [comment]
Yeah, I think you're right!

I'll take a closer look at flux, even if I don't use the GitOps stuff, the Helm operator is still useful!
