### ISSUE TITLE
go get github.com/rancher/k3s@v.14.1-k3s.1 fails with "looping trying to add package"

### ISSUE THREAD

**Issue by shrajfr12** [rancher/k3s#315]
**Describe the bug**
Not able to use "go get" on the recent release tags. 
For example, running "go get github.com/rancher/k3s@v1.14.1-k3s.1" fails with 
go: import "github.com/rancher/k3s": looping trying to add package
The same issue is observed with other recent tags like v1.13.5-k3s.1
However no such issues with older version tags like v0.3.0 where the command executes successfully. The version of Go is 1.11.4. The error is seen whether GO111MODULE is set to "on" or not set at all.

**To Reproduce**
1. sudo rm -fr "$(go env GOPATH)/pkg/mod”
2. go get github.com/rancher/k3s@v.14.1-k3s.1 
After going through a screenful of dependencies, the program aborts with following error.
....
....
go: downloading github.com/rancher/k3s v1.14.1-k3s.1
go: finding github.com/rancher/k3s v0.3.0
go: downloading github.com/rancher/k3s v0.3.0
go: import "github.com/rancher/k3s": looping trying to add package
 

**Expected behavior**

It is expected that the "go get" command runs to completion without any errors.

**Comment by shrajfr12** [comment]
Seems to be a known issue when package structure is changed with pre-release or pseudo versions. Please see https://github.com/golang/go/issues/30394 for details. When changed to a full release version e.g v1.14.1, the issue is expected to get resolved.

**Comment by ibuildthecloud** [comment]
This is a known issue we will revisit this after k8s 1.15 is released.  Go modules are an absolute disaster when working with k8s.  k8s recently switched to go modules, be it is still hard to leverage.  It should be much easier once k8s does a proper release.  I'm going to close for now.

**Comment by ibuildthecloud** [comment]
Essentially duplicate of #268
