### ISSUE TITLE
Multi Master possible ?

### ISSUE THREAD

**Issue by DimJacq** [rancher/k3s#318]
Hello, I would like to create a cluster K3S with multi-master to have more avaibility. For exemple, if my first master goes down, my cluster still working with the same option/posibility. Do you know if it's possible ? I have already install K3S on 3 raspberry and all works well but with only 1 master. 
I have already done with https://github.com/kelseyhightower/kubernetes-the-hard-way on my raspberry but I want to try with K3S to compare the performance.
Thank you in advance

**Comment by bencompton** [comment]
HA / etcd is not currently implemented; see #42.

**Comment by deniseschannon** [comment]
Closing in favor of #42
