### ISSUE TITLE
Cluster in GCP is broken

### ISSUE THREAD

**Issue by Lunik** [rancher/k3s#323]
**Describe the bug**

I have two nodes on GCP and I'm playing with this command `kubectl run -it --rm --restart=Never busybox --image=busybox sh`
When `codeDNS` and `busybox` pods are not on the same host, they can't talk.
But when they are on the same node, they can...

**To Reproduce**

My config : 
Two fresh Centos 7 launched on GCP with no firewall filtering between them.
Rancher K3S installed with scripts provided here [get.k3s.io](https://get.k3s.io)
k3s cluster launched with those start commands : 
**server** : `/usr/local/bin/k3s server --docker`
**node** : `/usr/local/bin/k3s agent --docker --server https://server:6443 --token "TOKEN"`

**Expected behavior**

The pod that I start by hand should be able to make DNS request to the `CoreDNS` pod.

**Additional context**
With only one node, everything work like a charm.
When adding a new node : 
- it show up with `kubectl get nodes`
- when running new pods, they start properly on this node

**Comment by Dev-Time** [comment]
Not sure if i had the same issue as you, but I was also having trouble getting pods on different nodes to communicate.  I eventually solved it by disabling flannel in k3s with the `--no-flannel` option and installing flannel manually by following the instructions here: https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/#pod-network.

**Comment by Lunik** [comment]
I have checked that `/proc/sys/net/bridge/bridge-nf-call-iptables` is set to `1`
My server has multiple interfaces so I have well the `--flannel-iface`

**Comment by Lunik** [comment]
With Docker backend, pods are started with docker bridge IP and  not an IP inside the cluster-cidr range. Resulting on the container packet are not forwarded via the iptables

**Comment by Lunik** [comment]
related #255

**Comment by deniseschannon** [comment]
@Lunik Can you test out v0.5.0-rc3 and let me know if your issue is fixed?

**Comment by Lunik** [comment]
It's work perfectly with v0.5.0-rc3. thank's 👍

**Comment by deniseschannon** [comment]
Thanks for the update @Lunik!
