### ISSUE TITLE
kubectl logs fail to get container log  when k3s behind corporate proxy

### ISSUE THREAD

**Issue by vincentmli** [rancher/k3s#325]
Thanks for helping us to improve k3s! We welcome all bug reports. At this stage, we are also looking for help in testing/QAing fixes. Once we've fixed you're issue, we'll ping you in the comments to see if you can verify the fix. We'll give you details on what version can be used to test the fix. Additionally, if you are interested in testing fixes that you ***didn't*** report, look for the issues with the `status/to-test` label. You can pick any of these up for verification.  ***You can delete this message portion of the bug report.***

**Describe the bug**

when running k3s behind corporate proxy, kubectl logs failed to get pod log

start k3s through systemd with corporate proxy setting

cat /etc/systemd/system/k3s.service

<pre>

[Unit]
Description=Lightweight Kubernetes
Documentation=https://k3s.io
After=network.target

[Service]
Type=notify
Environment="HTTP_PROXY=http://10.3.254.254:3128/"
Environment="HTTPS_PROXY=http://10.3.254.254:3128/"
EnvironmentFile=/etc/systemd/system/k3s.service.env
ExecStartPre=-/sbin/modprobe br_netfilter
ExecStartPre=-/sbin/modprobe overlay
ExecStart=/usr/local/bin/k3s server --no-deploy traefik
KillMode=process
Delegate=yes
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity

[Install]
WantedBy=multi-user.target

</pre>

kubectl get po --all-namespaces

<pre>

NAMESPACE     NAME                       READY   STATUS    RESTARTS   AGE
kube-system   coredns-7748f7f6df-p6zhh   1/1     Running   3          6m21s

</pre>

kubectl logs  coredns-7748f7f6df-p6zhh -n kube-system

<pre>

Error from server: Get https://rancher-k3s:10250/containerLogs/kube-system/coredns-7748f7f6df-p6zhh/coredns: proxyconnect tcp: failed to find Session for client 10.3.254.254

</pre>

ping rancher-k3s

<pre>

PING rancher-k3s (10.3.72.189) 56(84) bytes of data.
64 bytes from rancher-k3s (10.3.72.189): icmp_seq=1 ttl=64 time=0.054 ms

</pre>

lsof -i -n -P | grep 10250

<pre>

k3s-serve 2631 root   98u  IPv4  27517      0t0  TCP 127.0.0.1:10250 (LISTEN)

</pre>

 *To Reproduce**

run k3s with systemd behind proxy server

**Expected behavior**

expect to use kubectl logs to get container log with k3s running behind proxy server

**Screenshots**

**Additional context**

**Comment by ibuildthecloud** [comment]
Shoot... I think I know whats up.  The proxyTransport the api server uses to connect to the kubelets should not respect proxy args.  It uses the tunnel dialer.  We'll fix this

**Comment by tfiduccia** [comment]
Broken on 0.4.0-rc1

**Comment by tfiduccia** [comment]
Version - v0.4.0-rc3
Verified fixed
