### ISSUE TITLE
Ability to configure containerd config.toml

### ISSUE THREAD

**Issue by deniseschannon** [rancher/k3s#331]
Look at existing PRs to get it in:
https://github.com/rancher/k3s/pull/248
https://github.com/rancher/k3s/pull/264

**Comment by dnoland1** [comment]
Before changing containerd template, verified it was listening on port 10010:
```
root@k3s-node1:/var/lib/rancher/k3s/agent/etc/containerd# netstat -anp | grep 10010
tcp        0      0 127.0.1.1:10010         0.0.0.0:*               LISTEN      9936/containerd
```
Copied `/var/lib/rancher/k3s/agent/etc/containerd/config.toml` to  `config.toml.tmpl`. Edited `config.toml.tmpl` and changed `stream_server_port = "10011"`.
Restarted k3s. Confirmed containerd is now listening on port 10011:
```
root@k3s-node1:/var/lib/rancher/k3s/agent/etc/containerd# netstat -anp | grep 10011
tcp        0      0 127.0.1.1:10011         0.0.0.0:*               LISTEN      13906/containerd
```
