### ISSUE TITLE
Port forward problem

### ISSUE THREAD

**Issue by giovannicandido** [rancher/k3s#340]
**Describe the bug**
Try to port-forward using kubectl:

` kubectl -n cattle-system port-forward pod/rancher-57f4fdc5bb-tts88 9001:9443`

Access localhost in port 9001

Result:

> 2217 portforward.go:331] an error occurred forwarding 9001 -> 9443: error forwarding port 9443 to pod b1775a7ffe8bc09f90b59cd9325204cd3a6388174160c1e3efb8ecd485ab3e75, uid : failed to execute portforward in network namespace "/var/run/netns/cni-161a7191-3112-488c-197e-db8d048c9e0a": socat command returns error: exit status 1, stderr: "2019/04/12 17:02:59 socat[15663] E connect(5, AF=2 127.0.0.1:9443, 16): Connection refused\n"

*Expected*:

Access to pod/service

**Comment by jrhoward** [comment]
I had the same issue but. This is a containerd configuration issue. 
Following these tasks will get it working for you

https://kubernetes.io/docs/setup/cri/#containerd

**Comment by davidnuzik** [comment]
To test, see if this is still an issue.

**Comment by davidnuzik** [comment]
@giovannicandido Could you try this again in our latest release? (Currently v0.9.1) We think this is fixed now.

**Comment by ShylajaDevadiga** [comment]
With v0.9.1 we have this fixed. 
``` kubectl port-forward redis-master-545d695785-kkpsl 7000:6379
root@ip-172-31-23-2:~# redis-cli -p 7000
127.0.0.1:7000> ping
PONG
127.0.0.1:7000> 
```
Closing issue.

**Comment by mikeschinkel** [comment]
@jrhoward —
> This is a containerd configuration issue on the host. Following these tasks will get it working for you
> 
> https://kubernetes.io/docs/setup/cri/#containerd

I'm trying to resolve the issue in the title but I cannot figure out what I need to set in the containerd config. I tried the instructions in the section _"Configuring the systemd cgroup driver"_ but those did not help.

Would you mind elaborating on the specifics, please?

**Comment by brandond** [comment]
This is an ancient issue that no longer affects K3s. Please open a new issue that describes what problem you're experiencing and we can try to assist.
