### ISSUE TITLE
k3s not starting using CentOS7

### ISSUE THREAD

**Issue by HaJoHe** [rancher/k3s#344]
**Describe the bug**
K3S is not starting correctly. Always restarting coredns + helm-install-traefik
Looks similar to #246, but server has full access to internet, and no issue with the described DNS problem.

**To Reproduce**
Minimal installation of CentOS7 18.10 + SElinux= permissive+ installation of policycoreutils-python

curl -sfL https://get.k3s.io | sh -

**Expected behavior**
A fully working K3S installation

**Logs**
[host]# kubectl --all-namespaces=true get all
NAMESPACE     NAME                             READY   STATUS             RESTARTS   AGE
kube-system   pod/coredns-7748f7f6df-95hk4     0/1     CrashLoopBackOff   31         101m
kube-system   pod/helm-install-traefik-k86rz   0/1     CrashLoopBackOff   36         101m

NAMESPACE     NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                  AGE
default       service/kubernetes   ClusterIP   10.43.0.1    <none>        443/TCP                  101m
kube-system   service/kube-dns     ClusterIP   10.43.0.10   <none>        53/UDP,53/TCP,9153/TCP   101m

NAMESPACE     NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
kube-system   deployment.apps/coredns   0/1     1            0           101m

NAMESPACE     NAME                                 DESIRED   CURRENT   READY   AGE
kube-system   replicaset.apps/coredns-7748f7f6df   1         1         0       101m

NAMESPACE     NAME                             COMPLETIONS   DURATION   AGE
kube-system   job.batch/helm-install-traefik   0/1           101m       101m

[host]# ip route
default via 192.168.100.1 dev eth0 proto dhcp metric 100 
10.42.0.0/24 dev cni0 proto kernel scope link src 10.42.0.1 
192.168.100.0/24 dev eth0 proto kernel scope link src 192.168.100.241 metric 100

[host]# lsmod | grep vx
vxlan                  49678  0 
ip6_udp_tunnel         12755  1 vxlan
udp_tunnel             14423  1 vxlan

[host]# host www.nersc.gov 1.1.1.1
Using domain server:
Name: 1.1.1.1
Address: 1.1.1.1#53
Aliases: 

www.nersc.gov is an alias for www5.nersc.gov.
www5.nersc.gov has address 128.55.209.20
www5.nersc.gov has IPv6 address 2620:0:28b0:d1::14

[host]# kubectl logs coredns-7748f7f6df-95hk4 --namespace=kube-system
E0413 10:26:59.747487       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:315: Failed to list *v1.Service: Get https://10.43.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.43.0.1:443: connect: no route to host

**Comment by superseb** [comment]
Is `firewalld` running and does it work when you disable it?

**Comment by HaJoHe** [comment]
Hello,

as mentioned in #246, I've disabled firewalld and enabled iptables.services.

Looks like disabling iptables.services too, solved the issue.

**Comment by erikwilson** [comment]
It sounds like this has been resolved @HaJoHe, is it good to close?

**Comment by HaJoHe** [comment]
Have checked it on 4 installations. It works on all systems as soon as firewalld is disabled.
