### ISSUE TITLE
Typo in the project description

### ISSUE THREAD

**Issue by arifC** [rancher/k3s#36]
My inner grammar nazi just said:
"Change the project description from 'Lightweight Kubernetes. 5 less **then** k8s.' to 'Lightweight Kubernetes. 5 less **than** k8s.' please."

**Comment by ibuildthecloud** [comment]
Thanks! From https://www.diffen.com/difference/Than_vs_Then

```Than is used to draw a comparison between two or more items, while then is used in relation to time and the order in which events occur. (For example: Julie had been taller than her little brother at the start of the year, but then Corey grew over the summer until he stood half an inch taller than his sister.) ```

**Comment by ibuildthecloud** [comment]
Updated
