### ISSUE TITLE
Update procedure

### ISSUE THREAD

**Issue by edouardkleinhans** [rancher/k3s#363]
**Is your feature request related to a problem? Please describe.**

What is the best way to update server and agent to a new release ?

**Describe the solution you'd like**
Simply rerun the install script

**Comment by staranto** [comment]
@runningman84 "Would say", or "I have upgraded successfully simply by replacing the binaries and restarting"?

**Comment by runningman84** [comment]
Yes I did it a couple of times the same way.

**Comment by tfiduccia** [comment]
@deniseschannon - can we get the update information into the readme?
