### ISSUE TITLE
kube-router support

### ISSUE THREAD

**Issue by runningman84** [rancher/k3s#366]
**Is your feature request related to a problem? Please describe.**
I would like to preserve client ips as described in this issue: https://github.com/rancher/k3s/issues/77
This is not possible with the flannel network

**Describe the solution you'd like**
I would like k3s to support kube-router. Therefore some options have to be passed to the kubelet and kube-controller-manager. Furthermore the kube-proxy service needs to be disabled and all iptables rules created by kube-proxy need to be removed too.
Maybe it would be even possible to package kube-router into k3s itself. The memory footprint might be lower because kube-proxy does not run anymore and flannel is also not needed in this case.

**Describe alternatives you've considered**
I do not know any alternative. It does not seem to be possible to run k3s without kube-proxy.

**Additional context**
This is the generic install guide for kube-router:
https://github.com/cloudnativelabs/kube-router/blob/master/docs/generic.md

**Comment by iMartyn** [comment]
It really should be possible to run k3s and kube-router without disabling kube-proxy, but I have also found it doesn't work too - the pod networking works but even with kube-router only providing pod networking and network policy, the pods can no longer reach the services, including, unfortunately the kube-dns service :(

This is the case even if you add `--kube-proxy-args proxy-mode=ipvs` fwiw

I suspect if we could disable kube-proxy and run the kube-router service proxy, this could fix this but there's no way to flag this yet.

**Comment by Vad1mo** [comment]
Do you know if it does work by now?

**Comment by runningman84** [comment]
I haven't had any success. :(

**Comment by rlex** [comment]
This will be a nice feature indeed. Calico have eBPF mode (preview ATM) which requires disabling kube-proxy.

**Comment by onedr0p** [comment]
@brandond sorry for being ignorant, but when would this be made available?

**Comment by onedr0p** [comment]
I was able to deploy kube-router after disabling kube-proxy in v1.19. I think this issue is resolved.

**Comment by diseq** [comment]
> @runningman84 I was able to deploy kube-router after disabling kube-proxy in v1.19. @rlex In another test I was also able to deploy calico with eBPF after disabling kube-proxy as well.
> 
> I think this issue is resolved.

@onedr0p : any chance you can share the k3s settings. i cannot manage access services from pods.

```
disable-kube-proxy: true
disable-network-policy: true
```
did not work for me. 
(deployment [yaml](https://raw.githubusercontent.com/marcbachmann/kube-router/94a94ccd288915fed239c2c3c558c0fcf12f9517/daemonset/generic-kuberouter-all-features.yaml) )

**Comment by hickersonj** [comment]
@onedr0p can you provide the method/configs to get this working? I too am not able to get k3s up and running. Also perhaps the chart that was used. Thanks!
```
System Info:
  Machine ID:                 321319d6359e9f96be3d772f60de50bd
  System UUID:                03000200-0400-0500-0006-000700080009
  Boot ID:                    0ae40021-d63b-4432-acd5-effc44569d7d
  Kernel Version:             5.4.41
  OS Image:                   Unknown
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  containerd://1.4.4-k3s1
  Kubelet Version:            v1.21.0+k3s1
  Kube-Proxy Version:         v1.21.0+k3s1
PodCIDR:                      10.42.0.0/24
PodCIDRs:                     10.42.0.0/24
```
