### ISSUE TITLE
Suggest to change k3.service "After=network.target" to "After=network-online.target"

### ISSUE THREAD

**Issue by vincentmli** [rancher/k3s#367]
**Describe the bug**
start k3s with the new added --flannel-iface with systemd service as below

<pre>
[Unit]
Description=Lightweight Kubernetes
Documentation=https://k3s.io
After=network.target
#After=network-online.target

[Service]
Type=notify
Environment="HTTP_PROXY=http://10.3.254.254:3128/"
Environment="HTTPS_PROXY=http://10.3.254.254:3128/"
EnvironmentFile=/etc/systemd/system/k3s.service.env
ExecStartPre=-/sbin/modprobe br_netfilter
ExecStartPre=-/sbin/modprobe overlay
ExecStart=/usr/local/bin/k3s server --no-deploy traefik --flannel-iface ens224 --node-ip 10.169.72.189
KillMode=process
Delegate=yes
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
#TimeoutStartSec=infinity

[Install]
WantedBy=multi-user.target
</pre>

reboot and k3s fail to startup with following error:

<pre>
Apr 17 14:17:49 rancher-k3s k3s[727]: time="2019-04-17T14:17:49.806063094-07:00" level=fatal msg="flannel exited: failed to find IPv4 address for interface ens224"
</pre>

change systemd k3.service from "After=network.target" to "After=network-online.target" 
fixed the issue

**To Reproduce**

specify --flannel-iface in k3.service

**Expected behavior**

expect k3s service up with --flannel-iface after reboot

**Screenshots**

**Additional context**

**Comment by galal-hussein** [comment]
@vincentmli I tried to reproduce the issue by following the same steps, I wasn't able to reproduce the issue:
```
root@server01:~# systemctl status k3s
● k3s.service - Lightweight Kubernetes
   Loaded: loaded (/etc/systemd/system/k3s.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2019-04-29 23:07:34 UTC; 1min 52s ago
     Docs: https://k3s.io
  Process: 690 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
  Process: 666 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
 Main PID: 697 (k3s-server)
    Tasks: 88
   Memory: 231.1M
      CPU: 7.878s
   CGroup: /system.slice/k3s.service
           ├─ 736 containerd -c /var/lib/rancher/k3s/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state /run/k3s/containerd --root /var/lib/rancher/k3s/agent/contai
           ├─1137 containerd-shim -namespace k8s.io -workdir /var/lib/rancher/k3s/agent/containerd/io.containerd.runtime.v1.linux/k8s.io/f05431b986172b7c8c25c2affa822de9827787beea590bb1229a4403
           ├─1140 containerd-shim -namespace k8s.io -workdir /var/lib/rancher/k3s/agent/containerd/io.containerd.runtime.v1.linux/k8s.io/7e7cbadc34ad0509b2da9d6233efe56d5ad556094a27bda2eb7c6d31
           ├─1419 containerd-shim -namespace k8s.io -workdir /var/lib/rancher/k3s/agent/containerd/io.containerd.runtime.v1.linux/k8s.io/db3e414f76855b1f26e8d7640628453de05cad49555c9a053a0b99d5
           ├─1433 containerd-shim -namespace k8s.io -workdir /var/lib/rancher/k3s/agent/containerd/io.containerd.runtime.v1.linux/k8s.io/5d6839c948f0d39be4e2e03f75200d60207b04e314c506006834fc44
           ├─1447 containerd-shim -namespace k8s.io -workdir /var/lib/rancher/k3s/agent/containerd/io.containerd.runtime.v1.linux/k8s.io/7907cad3e4c2b02fb8af7298cb6bbfce31728726a29e252e2b784384
           ├─1621 containerd-shim -namespace k8s.io -workdir /var/lib/rancher/k3s/agent/containerd/io.containerd.runtime.v1.linux/k8s.io/1fca07e313478cb93cbf716f84ec747ec334adf82dcae0ab6b5dc6ad
           └─1693 containerd-shim -namespace k8s.io -workdir /var/lib/rancher/k3s/agent/containerd/io.containerd.runtime.v1.linux/k8s.io/83c6903b9f0bc8e42366f62ce530c7d327c94eb0e3cf7bbfefb04993
           ‣ 697 /usr/local/bin/k3s server --no-deploy traefik --flannel-iface enp0s8

Apr 29 23:07:34 server01 k3s[697]: time="2019-04-29T23:07:34.401813321Z" level=info msg="k3s is up and running"
Apr 29 23:07:34 server01 systemd[1]: Started Lightweight Kubernetes.
Apr 29 23:07:37 server01 k3s[697]: time="2019-04-29T23:07:37.793159375Z" level=info msg="Logging containerd to /var/lib/rancher/k3s/agent/containerd/containerd.log"
Apr 29 23:07:37 server01 k3s[697]: time="2019-04-29T23:07:37.796564398Z" level=info msg="Running containerd -c /var/lib/rancher/k3s/agent/etc/containerd/config.toml -a /run/k3s/containerd/conta
Apr 29 23:07:38 server01 k3s[697]: time="2019-04-29T23:07:38.648071397Z" level=info msg="Waiting for containerd startup: rpc error: code = Unavailable desc = all SubConns are in TransientFailur
Apr 29 23:07:39 server01 k3s[697]: time="2019-04-29T23:07:39.667348237Z" level=info msg="Connecting to wss://localhost:6443/v1-k3s/connect"
Apr 29 23:07:39 server01 k3s[697]: time="2019-04-29T23:07:39.668307768Z" level=info msg="Connecting to proxy" url="wss://localhost:6443/v1-k3s/connect"
Apr 29 23:07:39 server01 k3s[697]: time="2019-04-29T23:07:39.672620395Z" level=info msg="Handling backend connection request [server01]"
Apr 29 23:07:39 server01 k3s[697]: time="2019-04-29T23:07:39.675343405Z" level=info msg="Running kubelet --eviction-hard=imagefs.available<5%,nodefs.available<5% --eviction-minimum-reclaim=imag
Apr 29 23:07:39 server01 k3s[697]: Flag --allow-privileged has been deprecated, will be removed in a future version

```

here is my systemd unit file:
```
[Unit]
Description=Lightweight Kubernetes
Documentation=https://k3s.io
After=network.target

[Service]
Type=notify
EnvironmentFile=/etc/systemd/system/k3s.service.env
ExecStartPre=-/sbin/modprobe br_netfilter
ExecStartPre=-/sbin/modprobe overlay
ExecStart=/usr/local/bin/k3s server --no-deploy traefik --flannel-iface enp0s8
KillMode=process
Delegate=yes
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
TimeoutStartSec=0

[Install]
WantedBy=multi-user.target
```

Is there any more information related to your setup ?

**Comment by galal-hussein** [comment]
According to systemd.special man:

> network.target
           This unit is supposed to indicate when network functionality is available, but it is only very weakly defined what that is supposed to mean, with one exception: at shutdown, a
           unit that is ordered after network.target will be stopped before the network — to whatever level it might be set up then — is shut down. It is hence useful when writing service
           files that require network access on shutdown, which should order themselves after this target, but not pull it in. Also see Running Services After the Network is up[1] for
           more information. Also see network-online.target described above.

However `network-online.target` should be used with units that strictly requires a configured network connection, and in that case k3s uses the interface and routable ip on startup which maynot be defined with network.target

**Comment by deniseschannon** [comment]
@vincentmli Would you be able ot test out v0.5.0-rc1 to see if you are still having issues?

**Comment by dnoland1** [comment]
I installed k3s using `curl -sfL https://get.k3s.io | sh -`. It appears the install script has already been changed to use `network-online.target` even though I'm using v0.4.0 and not v0.5.0-rc3:
```
root@k3s-node1:~# grep After /etc/systemd/system/multi-user.target.wants/k3s.service
After=network-online.target
root@k3s-node1:~# k3s -v
k3s version v0.4.0 (7822549f)
```

**Comment by erikwilson** [comment]
This change was made to the install script itself, which is available immediately on merge and not versioned, so the systemd service network-online.target change should be available regardless of the k3s version installed.

**Comment by erikwilson** [comment]
To test this would need to restart the computer/vm a few times to ensure the error message from the issue does not occur. It may be hard to reproduce, could be a race condition with systemd/k3s. The change appears simple enough that I am going to close this assuming it is fixed, my main concern is that network-online.target is old enough to be supported by almost all systemd configurations, which appears to be the case. 

If this is still an issue or needs more work please re-open with additional info.
