### ISSUE TITLE
website k3s.io/docs/ only placeholder

### ISSUE THREAD

**Issue by curx** [rancher/k3s#37]
Is there any work on the https://k3s.io/docs/ ?
Currently only placeholders there "Lorem markdownum..."

**Comment by ibuildthecloud** [comment]
Yeah, sorry. The website isn't really done, we accidentally published it to early.  But right now the README.md in this repo is the only real docs.

**Comment by ibuildthecloud** [comment]
I'll leave this issue open until we publish proper docs on the website.

**Comment by deniseschannon** [comment]
For now, we're going to keep docs in the readme in the repo.
