### ISSUE TITLE
How can I inspect the sqlite database directly?

### ISSUE THREAD

**Issue by gilkotton** [rancher/k3s#370]
I'm interested in visualizing the transactions on the sqlite database, similar to what has been done with etcd in the past.
How can I inspect the sqlite db?
Thanks.

**Comment by warmchang** [comment]
Try this: https://sqlitebrowser.org/

**Comment by gilkotton** [comment]
Thanks for the fast response, I would like to know if there is a service/
address/ port in k3s that I could point the query.

P.S. - I really like k3s.

**Comment by warmchang** [comment]
```
 root@william  /home/fedora  ll /var/lib/rancher/k3s/server/db
total 4.9M
-rw-r--r-- 1 root root 852K Apr 18 05:40 state.db
-rw-r--r-- 1 root root  32K Apr 18 05:44 state.db-shm
-rw-r--r-- 1 root root 4.0M Apr 18 05:45 state.db-wal
 root@william  /home/fedora 
```

The default path for db files is: /var/lib/rancher/k3s/server/db, and it is defined in the source code:
https://github.com/rancher/k3s/blob/f6e0bad95300054ede990f7adc910f4de32ea923/vendor/github.com/ibuildthecloud/kvsql/clientv3/driver/sqlite/sqlite.go#L68

In contrast to many other database management systems, SQLite is not a client–server database engine. 
So there are no service addresses:ports that provide external access like mysql, oracle, PostgreSQL.
