### ISSUE TITLE
'Exec format error' installing metrics server on k3s version v0.4.0 (7822549f) arm64 platform

### ISSUE THREAD

**Issue by giminni** [rancher/k3s#372]
**Describe the bug**
'Exec format error' installing metrics server on k3s version v0.4.0 (7822549f) arm64 platform

**To Reproduce**
```
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable-agent --kubelet-arg='address=0.0.0.0'" sh -

kubectl apply -f ./recipes/metrics-server/
```

**Expected behavior**
```
kubectl top node
```

**Additional context**
#252 #355

**Comment by meldafrawi** [comment]
I tried to install metrics server on k3s using a raspberry pi, and I've got the same error.
the metric server pod always end in CrashLoopBackOff state.

I think the error is due to the following line:
https://github.com/rancher/k3s/blob/4af06882b67cd3f56285b6a5a1388b7190b93533/recipes/metrics-server/metrics-server-deployment.yaml#L39
specifying "amd64" in metrics server image

I've tried to replace that line with arm image:  `image: k8s.gcr.io/metrics-server-arm:v0.3.1`
 and the metrics server pod is now running, and i was able to run `kubectl top node` successfully.

**Comment by giminni** [comment]
@meldafrawi If I execute`kubectl top node`
I got `Error from server (ServiceUnavailable): the server is currently unable to handle the request (get nodes.metrics.k8s.io)`

**Comment by meldafrawi** [comment]
@giminni 
Can you please check the state of the mertics-server pod using:

`kubectl get pods -n kube-system | grep -i metrics-server`

**Comment by staranto** [comment]
Exact experience as @giminni.  

I start the master with --

    ExecStart=/usr/local/bin/k3s server --kubelet-arg='address=0.0.0.0'

and the nodes with --

    ExecStart=/usr/local/bin/k3s agent

(I don't think the agents need the address=0.0.0.0, do they?

After applying the recipe, I have running (in -n kube-system) the a metrics-server deploy, rs, svc and pod.  Akk showing running and no errors.

Stumped.  5 node Rock64 cluster (1 manager, 4 nodes).  All running v1.14.1-k3s-4 and `Linux rock0 4.4.132-1072-rockchip-ayufan-ga1d27dba5a2e #1 SMP Sat Jul 21 20:18:03 UTC 2018 aarch64 GNU/Linux`.

Stumped.

**Comment by staranto** [comment]
Just an update for those that stumble down this path.  My metrics stuff is working now.  What did I change?  Nothing.  I simply wasn't being patient enough.  I just had to wait a loooong time (> 15 min).

**Comment by giminni** [comment]
@meldafrawi Sorry for answering late here the info
```
$ kubectl get pods -n kube-system | grep -i metrics-server
metrics-server-7cb5fc9958-4n6g4         1/1     Running     0          8d
```

**Comment by erikwilson** [comment]
Are you still running with `--kubelet-arg='address=0.0.0.0'"` @giminni?

**Comment by giminni** [comment]
@erikwilson Yes

**Comment by erikwilson** [comment]
How many nodes are being used @giminni? 
Assuming it is multi-node, is the ip resolvable from the server node?

**Comment by giminni** [comment]
Starting with 0.6.0 the metrics server installation is reflected in the K3s documentation #557
