### ISSUE TITLE
kubectl cannot retrieve info from local cluster

### ISSUE THREAD

**Issue by ThomasSchoenbeck** [rancher/k3s#378]
**Describe the bug**
k3s kubectl cannot connect to the cluster as connection is refused

**To Reproduce**
start k3s server via docker (self build image) and run a shell inside it using the command k3s kubectl get node

**Expected behavior**
cluster node info appears

**Screenshots**
![image](https://user-images.githubusercontent.com/5657479/56432826-27faa200-62cf-11e9-8131-6957d014bade.png)
![image](https://user-images.githubusercontent.com/5657479/56432884-4bbde800-62cf-11e9-8126-c90961dd60fb.png)
![image](https://user-images.githubusercontent.com/5657479/56432909-6001e500-62cf-11e9-8447-17348be809b9.png)

**Additional context**

**Comment by galal-hussein** [comment]
I was able to reproduce the issue by using the following steps:

- start k3s server with env `K3S_KUBECONFIG_OUTPUT=/tmp/kubeconfig.yml`
- try `k3s kubectl get nodes`

result:
```
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

Apparently when placing the kubeconfig in a non-default directory k3s kubectl try to get `/etc/rancher/k3s/k3s.yaml`

**Comment by ThomasSchoenbeck** [comment]
removing K3S_KUBECONFIG_OUTPUT did fix the issue.

I got the idea of using this variable from the docker-compose example file.

**Comment by ibuildthecloud** [comment]
What if we make it so that if the user changes the location of the k3s.yml we put it in the custom location and then also create a symlink at /etc/rancher/k3s/k3s.yml that points to the custom location.

**Comment by tfiduccia** [comment]
Version - v0.6.0-rc3
Verified fixed
