### ISSUE TITLE
Node roles are not set

### ISSUE THREAD

**Issue by dnoland1** [rancher/k3s#379]
**Describe the bug**
When viewing nodes, the roles column is not set. Using k3s v0.4.0.

**To Reproduce**
Run: `k3s kubectl get nodes`
```
root@k3s-node1:~# kubectl get nodes
NAME        STATUS     ROLES    AGE   VERSION
k3s-node1   Ready      <none>   15h   v1.14.1-k3s.4
k3s-node2   Ready      <none>   15h   v1.14.1-k3s.4
```
**Expected behavior**
The roles column displays `<none>`. Would like to see something like this:
```
NAME        STATUS     ROLES          AGE   VERSION
k3s-node1   Ready      server,agent   15h   v1.14.1-k3s.4
k3s-node2   Ready      agent          15h   v1.14.1-k3s.4
```

**Screenshots**
n/a

**Additional context**
FYI - RKE sets the following roles:
```
NAME          STATUS   ROLES               AGE     VERSION
192.168.0.3   Ready    controlplane,etcd   4m10s   v1.13.5
192.168.0.4   Ready    worker              4m9s    v1.13.5
```
This feedback was raised and discussed during a k3s meetup.
Believe this is set up by specifying a `node-role.kubernetes.io/<rolename>` label for a node.

**Comment by ibuildthecloud** [comment]
Related https://github.com/rancher/k3s/issues/394

**Comment by tfiduccia** [comment]
Version - v0.6.0-rc2 - Verified fixed, roles are listed as master & worker.
![image](https://user-images.githubusercontent.com/11514927/58508166-4a8e9f00-8148-11e9-949b-b632dd252f2e.png)

**Comment by kiriakos** [comment]
Is it possible that there is a regression here in versions up to v1.16.3-k3s.2? Labeling seemed to work correct some months ago but updating the cluster last week left me with nodes labeled either `master` or `<none>`

**Comment by jffz** [comment]
> Is it possible that there is a regression here in versions up to v1.16.3-k3s.2? Labeling seemed to work correct some months ago but updating the cluster last week left me with nodes labeled either `master` or `<none>`

I am also having this issue using 1.16.3

**Comment by erikwilson** [comment]
That is the expected behavior, also see #878 & #1032.
