### ISSUE TITLE
k3s-created cni0 overrides nginx port rules

### ISSUE THREAD

**Issue by Oxylibrium** [rancher/k3s#383]
**Describe the bug**
When k3s is started, nginx stops serving data, and instead a mysterious `404 page not found` is served on all nginx domains. On using lsof -p 80, only nginx's workers appear, but even after stopping nginx, the strange 404 page persists until reboot. Then, it disappears, and nginx works again until k3s is started.

This appears to be due to https://github.com/rancher/k3s/blob/4af06882b67cd3f56285b6a5a1388b7190b93533/pkg/agent/flannel/setup.go#L26
but I'm just making a guess, as I'm new to k3s and networking.

**To Reproduce**
Start k3s when nginx is running.
Visit any domain served by nginx.

**Expected behavior**
nginx continues to serve requests.

**Comment by nberlee** [comment]
The response you are getting is from the traefik loadbalancer. It has nothing to do with flannel/cni0

It is a nat rule, fully intented to be there.. Only not documented
see:
```
kubectl logs -n kube-system -l app=svclb-traefik -c lb-port-80
```

**Comment by deniseschannon** [comment]
@Oxylibrium if you have more questions, please let us know!

**Comment by r4ym0n** [comment]
I got in the same problem.And I found out it was caused by treafik's own LB.
traefik              LoadBalancer   10.43.127.25    192.168.66.100   80:32635/TCP,443:31959/TCP   139m
use edit command to set the 80 port to 8080. to avoid overwrite situations.
kubectl edit service/traefik -n kube-system
