### ISSUE TITLE
Metrics server unable to collect metrics

### ISSUE THREAD

**Issue by hellupline** [rancher/k3s#386]
**Describe the bug**
on a single master/agent cluster running on `coreos` at digitalocean, running example recipe for metrics servers, the metrics server is unable to fully collect metrics

**To Reproduce**
install k3s:
```sh
sudo mkdir -p /opt/k3s/bin
echo "127.0.0.1 ${HOSTNAME}" | sudo tee -a /etc/hosts # solve problem containerd unable to connect localhost
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v0.4.0 INSTALL_K3S_BIN_DIR="/opt/k3s/bin" INSTALL_K3S_EXEC="--no-deploy traefik" sudo -E sh -
cat /etc/rancher/k3s/k3s.yaml
```
```
$ kubectl apply -f ./recipe/metrics-server
$ kubectl -n kube-system logs $(kubectl -n kube-system get pods -l k8s-app=metrics-server -o jsonpath='{.items[0].metadata.name}')

$ kubectl top nodes
```

**Expected behavior**
metrics server to collect metrics 

**Additional context**

**Comment by erikwilson** [comment]
This is because the `--kubelet-arg="address=0.0.0.0"` flag was not added as described in the docs. k3s v0.5.0 will remove the need for this flag.

**Comment by huapox** [comment]
Wish this can get some help #442

**Comment by erikwilson** [comment]
Closing as old, this should be fixed in more recent versions. Shouldn't need any special flags, use upstream metrics-server deployment. Please re-open if still an issue.
