### ISSUE TITLE
kube-router installation with service-proxy fails

### ISSUE THREAD

**Issue by babykart** [rancher/k3s#391]
**Describe the bug**
The installation of kube-router with full features (https://github.com/cloudnativelabs/kube-router/blob/master/docs/kubeadm.md) fails on init container.

**To Reproduce**
<pre>
k3s server --container-runtime-endpoint /run/containerd/containerd.sock --no-flannel --cluster-cidr 10.12.0.0/16 --service-cidr 10.13.0.0/16 --no-deploy traefik
</pre>
<pre>
kubectl apply -f https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter-all-features.yaml
</pre>
The installation works without the service proxy:
<pre>
kubectl apply -f https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml
</pre>

**Expected behavior**
kube-router with service proxy (kube-proxy alternative) should be able to be installed.
Desactivating the kube-proxy by a flag `k3s server --no-deploy kube-proxy` appears to be a good way.

**Additional context**
<pre>
k3s version v0.4.0 (7822549f)
</pre>

**Comment by yamt** [comment]
a dup of https://github.com/rancher/k3s/issues/366

**Comment by babykart** [comment]
@yamt For me is not exactly a duplicate because issue #366 tells about a potential integration as a package of kube-router in k3s : a feature.
I'm just telling that k3s is not compliant with the kubernetes networking support, in particular with kube-router in this case: a bug.
My 50cts .... :-)

**Comment by deniseschannon** [comment]
It's a duplicate because k3s doesn't support kube-router so I'm closing in favor of adding in support for kube-router.
