### ISSUE TITLE
How to enable MountPropagation?

### ISSUE THREAD

**Issue by vitobotta** [rancher/k3s#404]
It's not really a bug but I didn't have many options...

I need to make sure that MountPropagation is enabled, so that Velero can restore volumes with Restic. How do I enable it and feature gates in general? Thanks!

**Comment by ibuildthecloud** [comment]
k3s is running k8s 1.14 which has this feature on by default (and can't be disable either I believe).

**Comment by ibuildthecloud** [comment]
Regarding feature gates.  All alpha features are removed from k3s.  If you want to use alpha feature you have to use something else.  Beta features are all on by default so the only configuration would be to disable a feature that is already on.  The way to disable features would be to use the kubelet arg like `--kubelet-arg feature-gates=AppArmor=false`

**Comment by vitobotta** [comment]
Oops I am getting old! I opened another related issue because for some reason Github was very slow and it seemed that this issue hadn't been created! Sorry.

I tried adding the kubelet arg with the 0.5.0. version but it didn't recognize MountPropagation as feature gate.

**Comment by ibuildthecloud** [comment]
@vitobotta Is sounds like this is not an issue?  I'm going to close this one, please reopen if you think this is still an issue.
