### ISSUE TITLE
Unable to restore volumes from Velero/Restic backup

### ISSUE THREAD

**Issue by vitobotta** [rancher/k3s#406]
**Describe the bug**
I am unable to restore volumes backed up with Velero using the Restic integration (for file level backup). Restores fail with this error:

```
pod volume restore failed: error restoring volume: error identifying path of volume: expected one matching path, got 0
```
From some searching it seems that this issue might be related to the MountPropagation feature gate, however this feature gate is enabled by default in recent versions of Kubernetes so it should be enabled in K3S too.

**To Reproduce**
1. With Velero and the Restic integration enabled, take a backup of a namespace including one or more volumes to some S3 compatible storage
2. Restore the namespace from the backup

**Expected behavior**
Volumes should be restored successfully without any errors.

**Additional context**
From my testing, this issue happens only with K3S clusters (tested: 0.4.0 and 0.5.0). With standard Kubernetes (tested: 1.13.5) backups and restores of volumes with Velero/Restic work as expected.

**Comment by deniseschannon** [comment]
@vitobotta Can you try again with the latest v0.5.0 release?

**Comment by vitobotta** [comment]
Hi @deniseschannon, with some help I was able to solve by editing the file `20-restic-daemonset.yaml` and changing the hostPath setting to `/var/lib/rancher/k3s/agent/kubelet/pods`. By doing this I was able to restore backups with volumes created by Rook (still having issues with Longhorn but that's another topic). I will close this, thanks.
