### ISSUE TITLE
crashLoopBackOff on various apps for arm64 & armv7

### ISSUE THREAD

**Issue by GitToby** [rancher/k3s#408]
**Describe the bug**
I'm following the UI tutorials on the Kuberneties website to deploy a UI pod and it keeps crashing, ending up in `crashLoopBackOff` state. If it helps in running Raspbian lite on a Pi3

**To Reproduce**
 1. Install k3s with `curl -sfL https://get.k3s.io | sh -`
 2. Create dash services, deployments etc with `kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/recommended/kubernetes-dashboard.yaml`

**Expected behavior**
At least one dashboard deployment should be working.

**Screenshots**
![image](https://user-images.githubusercontent.com/9465529/56863243-e5f6ed80-69ab-11e9-8e77-d4490961bc72.png)

**Additional context**

**Comment by erikwilson** [comment]
For issues with pods in a `crashLoopBackOff` state it is very helpful to provide the output of `kubectl describe` for that pod. 

Looking at `kubernetes-dashboard.yaml` we can see the deployment is using `k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1`, which probably would not work on an arm64 device.  

The best outcome here is for kubernetes-dashboard to create multi-arch images so their default deployment will work with amd64, arm64, and armv7, but the need and use of multi-arch for many projects is new. 

I think that k3s should stay focused on being light-weight and easy to use, but providing multi-arch image support for every project will be difficult and time-consuming. There has been some discussion about creating a k3s community driven catalog of multi-arch apps but my main concern about an initiative like that would be using or endorsing untrusted binaries.

So I would like to see all of these architecture issues upstreamed to the respective project, but any thoughts or discussion on a better way to approach the issue are appreciated.

**Comment by vFondevilla** [comment]
Exactly, the image you're using is AMD64 only:
🍺  Blckh.local ➜ ✗ docker container run --rm mplatform/mquery k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1
Image: k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1
 * Manifest List: No
 * Supports: amd64/linux

Change the image to k8s.gcr.io/kubernetes-dashboard-arm64:v1.10.1 and it should work.

**Comment by GitToby** [comment]
I have recently managed to break my Pi even further and it needs a full reset. I will try the arm64 image once I get it up and running again! just getting into this container thing so thanks for the help! 

I'll close the issue and follow up when I get it working again.
