### ISSUE TITLE
Changing the pod-eviction timer

### ISSUE THREAD

**Issue by Celebrian** [rancher/k3s#412]
**Is your feature request related to a problem? Please describe.**
For a project i'm doing, I would like to change the pod eviction timer so that I do not have to wait at least 5 mins before the container is deleted on failed nodes.

**Describe the solution you'd like**
Some way to change this setting in the kube-controller-manager. An option flag or the like.

**Describe alternatives you've considered**
I have considered, but not tried, to manually edit the database, if that is in fact where this variable is stored.

**Additional context**
No.

**Comment by superseb** [comment]
This was implemented in v0.4.0 as described in https://github.com/rancher/k3s/issues/290

**Comment by Celebrian** [comment]
Thanks, I should be able to figure it out from here. Thank you for the fast reply, feel free to close/delete this.
