### ISSUE TITLE
k3s server --disable-agent mode, with metrics-server installed, kubectl top node/pod not work.

### ISSUE THREAD

**Issue by huapox** [rancher/k3s#442]
**Anay**
The svc of the metrics-server like a.b.c.d:443 can't be reached by the `k3s server --disable-agent` node, because of kube-proxy not set in that server-node.

**How could kube-apiserver communicate with metrics-server in this mode, any good idea?**
ex:
- 1.install kube-proxy in server-node.
- 2.`route add` to route the metrics-server svc's ip traffic to the agent-node.
- 3.just change metrics svc ip/port that is need by kube-apiserver to node ip/port. but how to?

**Comment by huapox** [comment]
the svc of the metrics-server like a.b.c.d:443 can't be reached by the `k3s server --disable-agent` node.

**Comment by erikwilson** [comment]
At the moment it is expected that a server and agent will be run on the same node for network to be setup.

**Comment by huapox** [comment]
> At the moment it is expected that a server and agent will be run on the same node for network to be setup.

yes, this issue is the same with k8s.
