### ISSUE TITLE
the way to change the nodeport 

### ISSUE THREAD

**Issue by wanggonggong** [rancher/k3s#444]
hi,
     can you please tell me How to modify the default port range of nodeport 30000-32767，thanks a lot.

**Comment by warmchang** [comment]
try this:
k3s server --kube-apiserver-arg --service-node-port-range=20618-20828

**Comment by wanggonggong** [comment]
@warmchan  this method works  very well,thank  you very much.

**Comment by jacksgt** [comment]
*Just a little update here for anyone else coming across this issue:*

The correct version of the specifying the argument is (as of k3s version v1.19.5+k3s2 (746cf403)):
```
k3s server --kube-apiserver-arg service-node-port-range=1000-32767
```

If you installed k3s as a systemd service (the default via get.k3s.io), you can make this change permanent by adding the command line argument to `ExecStart` in `/etc/systemd/system/k3s.service`, e.g.:
```
# ...
ExecStart=/usr/local/bin/k3s \
    server \
    --kube-apiserver-arg service-node-port-range=1000-32767
```

Then `systemctl daemon-reload` and `systemctl restart k3s`.
