### ISSUE TITLE
NetworkPolicy Broken?

### ISSUE THREAD

**Issue by staranto** [rancher/k3s#445]
**Describe the bug**
k3s does not appear to be honoring a NetworkPolicy denying all traffic to a pod.

**To Reproduce**
Follow exactly the steps in the example here -- 
https://github.com/ahmetb/kubernetes-network-policy-recipes/blob/master/01-deny-all-traffic-to-an-application.md

**Expected behavior**
I expect the NetworkPolicy to be denying all traffic.

**Additional context**
Five node k3s cluster on arm64.  Single master.  All identical.

```
uname -a
Linux rock0 4.4.132-1072-rockchip-ayufan-ga1d27dba5a2e #1 SMP Sat Jul 21 20:18:03 UTC 2018 aarch64 GNU/Linux

kubectl get nodes
NAME    STATUS                     ROLES    AGE   VERSION
rock0   Ready,SchedulingDisabled   master   37d   v1.14.1-k3s.4
rock1   Ready                      node     37d   v1.14.1-k3s.4
rock2   Ready                      node     37d   v1.14.1-k3s.4
rock3   Ready                      node     37d   v1.14.1-k3s.4
rock4   Ready                      node     27d   v1.14.1-k3s.4
```

**Comment by warmchang** [comment]
Flannel is the in-tree and default CNI plugin in k3s.
And it does not support NetworkPolicy.

FYI:
- https://github.com/coreos/flannel/issues/558
- https://github.com/coreos/flannel#networking-details

![image](https://user-images.githubusercontent.com/13084624/57207247-ac9f2d00-6ffe-11e9-9057-9ff625bb3934.png)

**Comment by staranto** [comment]
Thank you, @warmchang.  You are correct.  I wasn't thinking about it from that perspective.

**Comment by consideRatio** [comment]
Network Policy is currently available by default, see [this trace of it in the docs](https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/#kubernetes-components). But, as reported in #947, it is not robust.

**Comment by erikwilson** [comment]
We are using a an implementation called kube-router (https://github.com/cloudnativelabs/kube-router/blob/856c7d762a73df557e0a1d35721f48fe8ba7925d/pkg/controllers/netpol/network_policy_controller.go#L58) which includes a syncPeriod as part of it's operation, please feel free to open an issue there if it makes sense.
