### ISSUE TITLE
The "Device Plugins" feature is beta in k8s 1.14 but not included in k3s 0.5.0

### ISSUE THREAD

**Issue by uablrek** [rancher/k3s#451]
**Describe the bug**

The [Device Plugins](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/) does not seem to be included. I have not checked the code but the;
```
/var/lib/kubelet/device-plugins/kubelet.sock
```

socket does not appear on k3s agents. This is the device-plugin registration socket and hence plugins fail with;
```
time="2019-05-07T12:34:05Z" level=error msg="failed to start server: device-plugin: cannot register to kubelet service: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial unix /var/lib/kubelet/device-plugins/kubelet.sock: connect: no such file or directory\""
```

**To Reproduce**

Load an application that uses Device Plugins.

I got this problem when attempting to load Network Service Mesh [NSM](https://networkservicemesh.io/) on k3s.

**Expected behavior**

The `/var/lib/kubelet/device-plugins/kubelet.sock` should appear on the k3s agent nodes (it is created by `kubelet`)

**Screenshots**

**Additional context**

If you like to try [NSM](https://networkservicemesh.io/) I found it easiest to install with helm;
```
cd $GOPATH/src/github.com/networkservicemesh/networkservicemesh
helm install deployments/helm/nsm
```

**NOTE**; NSM expects the default service-account to be less restrictive and the name-space was not created by helm, so I had to do;
```
kubectl create clusterrolebinding serviceaccounts-admin \
 --clusterrole=cluster-admin --group=system:serviceaccounts
kubectl create clusterrolebinding nsm-view \
 --clusterrole=nsm-role --group=system:serviceaccounts
kubectl create namespace nsm-system
```
on the cluster before the helm install.

**Comment by warmchang** [comment]
@uablrek The unix socket should be **/var/lib/rancher/k3s/agent/kubelet/device-plugins/kubelet.sock**
```
$ ll /var/lib/rancher/k3s/agent/kubelet/device-plugins/
total 12
drwxr-xr-x 2 root root 4096 May  7 15:31 ./
drwxr-x--- 6 root root 4096 May  7 15:30 ../
-rw-r--r-- 1 root root    0 May  7 15:30 DEPRECATION
-rw------- 1 root root   79 May  7 15:31 kubelet_internal_checkpoint
srwxr-xr-x 1 root root    0 May  7 15:30 kubelet.sock=
$
```

Related code: https://github.com/rancher/k3s/blob/52f845ec844e0ae8f5f1a145bef0e553ac0d6840/pkg/agent/config/config.go#L335

**Comment by uablrek** [comment]
Ah, thanks! I will re-configure NSM to mount the correct dir.

Closing, since this is not a bug.
