### ISSUE TITLE
Embedded containerd: Terminating orphaned containers

### ISSUE THREAD

**Issue by deas** [rancher/k3s#472]
**Is your feature request related to a problem? Please describe.**
I have a pretty basic single node k3s application where we aim for a way to shut down containers managed by the embedded containerd when k3s terminates. I am not very familiar with plain containerd so I might be missing something.

**Describe alternatives you've considered**
Using an external containerd might help us out. Not sure whether containerd toml configuration allows us to express what we are aiming for.

**Comment by erikwilson** [comment]
Probably not an ideal solution, but the installation script will now also install a `k3s-killall.sh` script to completely kill all k3s processes and orphaned containers.

**Comment by deas** [comment]
Awesome. That one should be doing the trick for now. Thanks @erikwilson
