### ISSUE TITLE
K3S on CircleCI

### ISSUE THREAD

**Issue by alexec** [rancher/k3s#480]
Hi - have you run this on CircleCI please? I'd like to see if someone has any useful pointers.

**Comment by mentos1386** [comment]
@alexec did you managed to make it work? Any tips?

**Comment by devopsspiral** [comment]
@alexec @mentos1386 - It's been some time since the original question, but I've created CircleCI orb for k3d/k3s. You can find the docs in https://circleci.com/orbs/registry/orb/devopsspiral/k3d.
