### ISSUE TITLE
failed to get CA certs at https://server_add:6443/cacerts - When trying to add new k3s worker node

### ISSUE THREAD

**Issue by kcns008** [rancher/k3s#484]
ERRO[2019-05-16T02:18:54.984314601Z] failed to get CA certs at https://192.168.155.4:6443/cacerts: Get https://192.168.155.4:6443/cacerts: dial tcp 192.168.155.4:6443: connect: connection timed out

**Comment by erikwilson** [comment]
Closing as a resolved network configuration issue, from Rancher user slack:

> It's working now. I was able to Join K3s ... I had deployed in OpenSTACK - Ubuntu Instance, I was trying to add through Public IP / hostname as server address. That was not working... Once I spin up instace on same private_subnet as master & use private IP as server address ... It's worked ...

**Comment by pentateu** [comment]
Is there an official recommendation on how to deal with this issue?

**Comment by michel-zimmer** [comment]
I've had a similar problem when trying to set up a high availability control plane.

What I did wrong: I've used the `--server` and the `--token` parameter. (They are not needed at all for the masters connected via an external backing database like etcd.)

How I was able to solve my specific problem: Use the `--bind-address` parameter.
