### ISSUE TITLE
Add docs for all available flags

### ISSUE THREAD

**Issue by wxdao** [rancher/k3s#486]
There is no unified content about available flags the k3s command accepts in README, and README seems to be the only doc we have while lacking essential updates. I don't even know there is already a --pause-image flag until I've dug into the release note and the pr of it.

**Comment by nickkeyzer** [comment]
Found all flags here:

https://rancher.com/docs/k3s/latest/en/installation/

**Comment by davidnuzik** [comment]
Flags are now listed in documentation; it's the same output as the CLI help. If there are any specifics that aren't explained well enough via documentation or the CLI help let us know and re-open the issue or ask me to re-open.
