### ISSUE TITLE
Do not upgrade to Kubernetes v1.14.2

### ISSUE THREAD

**Issue by poikilotherm** [rancher/k3s#511]
Please be aware of kubernetes/kubernetes#78308.
Please do not upgrade Kubernetes in k3s to v1.14.2 until this has been fixed.
Thank you for not breaking our applications! :wink: :small_airplane: 

See also IQSS/dataverse-kubernetes#60 and kubernetes/minikube#4369.

**Comment by warmchang** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/78316
😃

**Comment by poikilotherm** [comment]
Yeah, meanwhile Kubernetes 1.14.3 has been released, incorporating the fix :-)

**Comment by erikwilson** [comment]
Thanks for the heads up!
