### ISSUE TITLE
Is there a way to build arm64 distribution on amd64?

### ISSUE THREAD

**Issue by juanahx** [rancher/k3s#530]
I used "make" to build distribution on mac, but always get a amd64 package.Is there a way to build arm64 distribution on amd64? I can't find any document related tot this.

**Comment by ibuildthecloud** [comment]
Unfortunately no.  We do not cross compile.  It is very difficult to maintain cross compilation so in order to build an architecture you must run on that architecture.  I highly recommend running AWS A1 instances for this task.  They are cheap and easy to run.
