### ISSUE TITLE
Please provide a way to change built-in flannel config, e.g. from vxlan to host-gw

### ISSUE THREAD

**Issue by sebschlue** [rancher/k3s#538]
It seems that with k3s, there is no way to change config of built-in flannel.

Upstream k8s offers ConfigMap kube-flannel-cfg with cni-conf.json and net-conf.json. There is no such ConfigMap in k3s.

There is /var/lib/rancher/k3s/agent/etc/flannel/net-conf.json but it seems this is just an auto-generated file with clear-text representation of the internal configuration mode. It gets automatically re-written at restart time.

I guess it would be possible to start with --no-flannel and then install regular upstream flannel CNI, though I haven't tried that path yet.

Use case would be to switch from vxlan to host-gw mode.

**Comment by tmlbl** [comment]
I am running into this as well. Would it make sense to only write this default config file if it doesn't already exist, allowing the user to edit it if desired?

**Comment by segator** [comment]
any new on this? I need host-gw too

**Comment by fuhuasheng** [comment]
Any update? I needed host-gw too

**Comment by segator** [comment]
I implemented it, its on a PR

**Comment by ShylajaDevadiga** [comment]
host-gw support is added in v1.17.2-alpha3+k3s1. Closing issue.

**Comment by DoGab** [comment]
Thank you for the implementation! For an already installed K3S cluster, is it possible to just run the installation script again with the parameter `--flannel-backend=host-gw` for the server nodes and it will switch to `host-gw` or will this break the cluster? Or is there another way to achieve using `host-gw`?

**Comment by Bowser1704** [comment]
Same question. For an already installed K3S cluster, how can i change flannel backend from vxlan to host-gw.

**Comment by brandond** [comment]
Just add the parameter to the arguments in the k3s systemd unit and restart k3s.

**Comment by nilbacardit26** [comment]
Hey @brandond, can you elaborate a little more how to change the flannel backend for an already installed K3s cluster?
Thank you

**Comment by brandond** [comment]
Exactly as I said above.

**Comment by raven-wing** [comment]
I know I'm archaeologist here, but for future newbies, I'll translate @brandond comment (which saved me!):

1. `nano /etc/systemd/system/k3s.service`
2. add `--flannel-backend=host-gw` parameter
3. `service k3s restart`

**Comment by brandond** [comment]
You'd probably want to `systemctl daemon-reload` prior to restarting if you've edited the systemd unit.
