### ISSUE TITLE
0.6.0 - Auth problem, CoreDNS and Traefik installation via helm is broken

### ISSUE THREAD

**Issue by giminni** [rancher/k3s#555]
A CrashLoopBackOff condition prevents the coreDNS and traefik installation using postgres as a storage backend provider.

Here the coreDNS installation log:
```
E0619 22:27:24.051189       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:322: Failed to list *v1.Namespace: Unauthorized
```

Here the traefik installation log:
```
[storage] 2019/06/19 22:23:57 listing all releases with filter
[storage/driver] 2019/06/19 22:23:57 list: failed to list: Unauthorized
Error: Unauthorized
+ LINE=
++ echo
++ cut -f1 -d,
+ INSTALLED_VERSION=
++ cut -f2 -d,
++ echo
+ STATUS=
+ '[' -e /config/values.yaml ']'
+ '[' install = delete ']'
+ '[' -z '' ']'
+ '[' -z '' ']'
+ helm install --name traefik https://10.48.0.1:443/static/charts/traefik-1.64.0.tgz --set-string kubernetes.ingressEndpoint.useDefaultPublishedService=true --set-string rbac.enabled=true --set-string ssl.enabled=true
[tiller] 2019/06/19 22:24:00 preparing install for traefik
[storage] 2019/06/19 22:24:00 getting release history for "traefik"
[storage/driver] 2019/06/19 22:24:00 query: failed to query with labels: Unauthorized
[tiller] 2019/06/19 22:24:00 failed install prepare step: the server has asked for the client to provide credentials
Error: the server has asked for the client to provide credentials
```

**Comment by erikwilson** [comment]
It looks like this is caused by using a database which has already been initialized, but the certs for k3s have changed. When k3s is started again the secrets stored in the database are no long valid as the underlying certs have been regenerated. To resolve you could either reset/drop the underlying database or delete the secrets & pods in kubernetes and let them be regenerated.

**Comment by giminni** [comment]
@erikwilson You're right. I confirm that if I delete the table key_value, and let the k3s installation script recreate it, everything works without problems.

Thanks for the prompt reply.

**Comment by balibebas** [comment]
I'm running into the error mentioned in the OP while attempting to install `cert-manager` as part of the [Rancher Installation](https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/). The idea of just deleting stuff from tables or starting over is tempting but it leads me no closer to the actual solve. There's a [related thread on SO](https://stackoverflow.com/questions/54683563/helm-error-error-the-server-has-asked-for-the-client-to-provide-credentials) but it got me no where.

Any ideas on how to approach debugging this the right way?
