### ISSUE TITLE
[Request for implementation]: Integrate rancher longhorn as storage orchestrator

### ISSUE THREAD

**Issue by giminni** [rancher/k3s#567]
Hey K3s team,
first of all you're doing a great job thanks to all of you for all the hard work.

I would like to have a storage orchestrator for all the architectures that works with volumes as a microservice. K3s has no definition which underlaying storage layer can be used. 

I installed weave with k3s and that was for me the best experience so far, all platforms covered transparently. That means weave runs on armhf, arm64 and amd64 without a problem.

Here the minimal storage orchestrator requisites:
- Be able to handle host path/device volumes for payload that manage replication by its own
- Be able to handle replicated volumes for all the payload that needs reliability
- Be able to cover armhf, arm64 and amd64 transparently
- Be able to be configured on specific storage nodes
- Be able to be configured on specific controller nodes
- Be able to be configured on specific manager nodes

IMHO I see two candidates:

- Longhorn (https://github.com/longhorn/longhorn) V0.5.0 (alpha)
- openEBS  (https://github.com/openebs/openebs) V1.0 (GA)

I think it would be good for K3s and good for Rancher to integrate longhorn into K3s.
Therefore I asked the longhorn team a similar question (https://github.com/longhorn/longhorn/issues/458)

What do you think. Is this possible?

Ideas and thoughts are welcome

**Comment by flobaader** [comment]
Would also love to see this!

**Comment by ShylajaDevadiga** [comment]
@giminni We can deploy longhorn v0.7.0 on K3s cluster.
Here are few docs that would help with deploying longhorn into k3s. And on setting the default data path.
https://github.com/longhorn/longhorn/blob/master/docs/taint-toleration.md
https://github.com/longhorn/longhorn/blob/master/docs/settings.md#default-data-path
Closing issue. Please feel free to re-open if needed.

**Comment by jonstelly** [comment]
I think this issue should be reopened, longhorn currently only supports amd64 (https://github.com/longhorn/longhorn/issues/6, https://github.com/longhorn/longhorn/issues/458).  Obviously that's more longhorn work than k3s work, but the ask in this issue is for a sort of "blessed" or "easy button" storage solution for k3s on any architecture that k3s supports.
