### ISSUE TITLE
0.6.1: Unable to connect to the server: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" ...

### ISSUE THREAD

**Issue by giminni** [rancher/k3s#570]
**Describe the bug**
I could reboot the master two times without a problem. After adding more nodes I get a strange error and dunno how to solve it.

```bash
Unable to connect to the server: x509: certificate signed by unknown authority (possibly 
because of "crypto/rsa: verification error" while trying to verify candidate authority 
certificate "k3s-ca")
```

Looking deeper into the journal output I found:

```bash
... level=info msg="Setting up event handlers"
... level=info msg="Starting k3s.cattle.io/v1, Kind=Addon controller"
... level=info msg="Node token is available at /media/data/rancher/k3s/server/node-token"
... level=info msg="To join node to cluster: k3s agent -s https://<...omitted...>:6443 -t ${NODE_TOKEN}"
... level=info msg="Starting k3s.cattle.io/v1, Kind=ListenerConfig controller"
... level=error msg="Failed to generate kubeconfig: server https://localhost:6443/cacerts is not trusted: Get https://localhost:6443/cacerts: x509: certificate signed by unknown authority (possibly because
... level=info msg="Wrote kubeconfig /etc/rancher/k3s/k3s.yaml"
... level=info msg="Run: k3s kubectl"
... level=info msg="k3s is up and running"
```

I am running 0.6.1 on all arm, arm64 and amd64 nodes using weave as the overlay network
and cockroachDB as the storage backend, metrics-server and dashboard are even installed and running.

**To Reproduce**
Setup:
k3s master has kubelet-arg="address=0.0.0.0"
k3s agent runs on master node
metrics server installed on k3s-agent on master node
using different data-dir

- Add two nodes
- Reboot master
- Execute kubectl get nodes
- Add two more nodes
- Wait until all new nodes joined the cluster
- Reboot master from the command line
- Execute kubectl get nodes again

**Expected behavior**
- Execution of kubectl get nodes returns the description of all nodes

**Additional context**
Even changing the server key in /etc/rancher/k3s/k3s.yaml 
from https://localhost:6443
to https://\<external-host-ip\>:6443
does not work.

**Comment by erikwilson** [comment]
Could you provide some more detail @giminni? Are you restarting the master with a different `--data-dir` using the server flag? If so, that is where the certs are stored, which would explain the error.

**Comment by giminni** [comment]
@erikwilson I can confirm that the server is using what is configured in /etc/systemd/system/k3s.service so far. I rebuilded everything two three times. It happened again after a second rebuild. Now I make a copy of /etc/rancher/k3s/k3s.yaml to ensure nothing is recreated again. Have not rebooted the third time, will do it tomorrow after some own tests.

**Comment by giminni** [comment]
After doing some deploment the master was not able to restart properly, same problem. 

Issuing kubectl version shows it can not connect to the api server
```
$ kubectl version --short
Client Version: v1.14.3-k3s.1
Unable to connect to the server: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "k3s-ca")
```

How do I recover from this situation?

**Comment by erikwilson** [comment]
Sorry you are still having problems @giminni , it would help to have a set of very minimal steps to reproduce (shell commands). I am not sure if you are rebooting a node, or restarting a service, or changing the data-dir, or copying files, etc. It sounds like you don't encounter the issue until after adding four nodes and restarting something, but there should be a simpler way to trigger the issue. It might be worth trying v0.7.0-rc1 (https://github.com/rancher/k3s/releases/tag/v0.7.0-rc1) and seeing if you encounter the same problem, and perhaps a thread in the k3s Rancher user slack (https://slack.rancher.io/) would help iterate through the problem faster.

**Comment by giminni** [comment]
@erikwilson  I installed 0.7.0-rc1 and seems to be more stable. I could restart the master three times successfully. I'll close this issue and repoen if it occures again.

Thx for beeing so quick.
