### ISSUE TITLE
Support hairpin mode

### ISSUE THREAD

**Issue by linchong** [rancher/k3s#582]
**Problem**
Can't access service from it's own pod in a k3s cluster. Even passed kebelet args like --hairpin-mode="promiscuous-bridge".
**feature**
Would you consider keep hairpin support ? It's necessary in many scenarios and  doesn't require a lot of compute resource.
**work around**
Watching /sys/devices/virtual/ for new virtual device  then echoing 1 to hairpin_mode   as a work around.

**Comment by minhnguyenvan95** [comment]
thumb up

**Comment by ccll** [comment]
Instead of watching and run `echo 1 > xxx ` for every veth, just run `ip link set cni0 promisc on` once to enable promiscuous mode on every node.

**Comment by erikwilson** [comment]
Hairpin mode is now enabled for flannel in v0.10.0-alpha1

**Comment by ShylajaDevadiga** [comment]
Hairpin mode is enabled by default in v0.10.0.  `grep -r hairpinMode /var/lib/rancher/k3s/agent/*`
