### ISSUE TITLE
The k3s server started with --disable-agent flag, nslookup failed in the later joined node

### ISSUE THREAD

**Issue by yulix** [rancher/k3s#599]
**Describe the bug**
The k3s server started with  --disable-agent flag,  nslookup failed in the later joined node.

**To Reproduce**
k3s version is 0.6.1.
Use vagrant create 3 virtualbox machines, OS is Ubunttu 16.04 LTS. 
1. Start the server with  --disable-agent flag
2. Node 1 join.
3. Node 2 join.
4. Deploy nginx with replicas=2
5. In nginx container in Node 1, run "nslookup kubernetes", there is no problem.
6. In nginx container in Node 2, run "nslookup kubernetes", no answer.

**Expected behavior**
The nslookup shall be ok in Node 2.

**Screenshots**
```
vagrant@node2:~$ docker exec -it baa68435a2f7 sh
 # nslookup kubernetes
nslookup: can't resolve '(null)': Name does not resolve

nslookup: can't resolve 'kubernetes': Try again
```
**Additional context**
1. The coredns is deployed in Node 1.
2. IP route of Node 1
vagrant@node1:/vagrant$ ip route
default via 10.0.2.2 dev enp0s3
10.0.2.0/24 dev enp0s3  proto kernel  scope link  src 10.0.2.15
10.42.0.0/24 dev cni0  proto kernel  scope link  src 10.42.0.1
10.42.2.0/24 via 10.42.2.0 dev flannel.1 onlink
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 linkdown
192.168.9.0/24 dev enp0s8  proto kernel  scope link  src 192.168.9.11
3. IP route of Node 2
vagrant@node2:/vagrant$ ip route
default via 10.0.2.2 dev enp0s3
10.0.2.0/24 dev enp0s3  proto kernel  scope link  src 10.0.2.15
10.42.0.0/24 via 10.42.0.0 dev flannel.1 onlink
10.42.2.0/24 dev cni0  proto kernel  scope link  src 10.42.2.1
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 linkdown
192.168.9.0/24 dev enp0s8  proto kernel  scope link  src 192.168.9.12

**Comment by erikwilson** [comment]
In vagrant you will want to use the `--flannel-iface` flag so nodes communicate over eth1, and the `--node-ip` flag set to the ip of eth1.

**Comment by yulix** [comment]
It works, thank you!

Following flags are used: 
--flannel-iface enp0s8   --node-ip 192.168.9.11
