### ISSUE TITLE
Interop with existing k8s control plane/cluster

### ISSUE THREAD

**Issue by nmiculinic** [rancher/k3s#61]
How does this play with existing k8s cluster, and I want to use k3s for IoT nodes?

If I use flannel (deployed via official CNI) can I also use flannel integration in k3s?

Can I mix control plane nodes in typical k8s installation with worker nodes in k3s? 

Can I use k3s hyperkube, rename it to kubelet/kube-proxy and server as a drop-in replacement in the worker node setup?

**Comment by ibuildthecloud** [comment]
The `k3s` binary wrapper is not interchangable with a vanilla k8s control plane.  The `hyperkube` binary that we build is though.  You should be able to take `hyperkube` from releases and copy it to `kubelet` and get a smaller kubelet footprint.  This does mean that you still have to fully manage the kubelet, certs, container runtime, args, etc yourself.  But that might be acceptable given your situation.

**Comment by nmiculinic** [comment]
I guess this closes my comment.
