### ISSUE TITLE
Option to not symlink kubectl

### ISSUE THREAD

**Issue by saturnism** [rancher/k3s#622]
**Is your feature request related to a problem? Please describe.**
I already have kubectl in my path, and also all the kube contexts that I normally use. When I install `kind`, it symlinks kubectl to k3s, and it uses k3s config by default.

Ideally, k3s would just update my existing kube context. But short of that, I can also just update KUBECONFIG to contain both my regular config, and also the k3s config.

**Describe the solution you'd like**
When installing k3s via install.sh, give an option to not create kubectl symlink.

**Describe alternatives you've considered**
Considered setting `KUBECONFIG` when I want use different set of contexts. But this becomes hard to keep track. Also, most other tooling default the config path to $HOME/.kube/config, but k3s is reading it from else where. While other tooling is working w/ one cluster, k3s kubectl is working w/ kind cluster. It's hard to keep them in sync.

**Comment by erikwilson** [comment]
Duplicate of #521

**Comment by saturnism** [comment]
thnx!
