### ISSUE TITLE
Add support for default network policy

### ISSUE THREAD

**Issue by davidnuzik** [rancher/k3s#640]
Add support for default network policy (no need to apply a flag to enable/support it)

**Comment by cjellick** [comment]
The idea is currently to use [kube-router](https://github.com/cloudnativelabs/kube-router) for network policy enforcement.

**Comment by cjellick** [comment]
Im not sure of how the UX of this plays out. Is it just a --enable-network-policy=true flag added to the server options?

**Comment by davidnuzik** [comment]
Based on our past discussions it would be installed and on by default. My notes seem to imply this as there is a mention that there is no default currently.

**Comment by cjellick** [comment]
I think there are two levels of default to think about:
- The implementaiton. @ibuildthecloud 's desire is to use kube-router as the default implementation
- What policy do we enforce by default when you turn it on

**Comment by ShylajaDevadiga** [comment]
network-policy support is enabled by default. Verified networkPolicy that controls traffic between pods using labels and rules.
