### ISSUE TITLE
the size of k3s binary

### ISSUE THREAD

**Issue by gssxd** [rancher/k3s#646]
I followed the README to build a k3s binary, but I find the size of binary is about 148MB. anyone can tell how to build a binary of less than 40MB?
I just used this command "go build -o k3s"

**Comment by charles-d-burton** [comment]
I would check this file out:
https://github.com/rancher/k3s/blob/master/scripts/build

They have the scripts that they use in there to build the project.

**Comment by gssxd** [comment]
> 
> 
> I would check this file out:
> https://github.com/rancher/k3s/blob/master/scripts/build
> 
> They have the scripts that they use in there to build the project.

Thanks for you reply.
This script seems comes out several binary files instead of one k3s binary.
-rwxr-xr-x 1 root root 96014888 Jul 18 02:30 containerd
lrwxrwxrwx 1 root root       10 Jul 18 02:30 k3s-agent -> containerd
lrwxrwxrwx 1 root root       10 Jul 18 02:30 k3s-server -> containerd
lrwxrwxrwx 1 root root       10 Jul 18 02:30 kubectl -> containerd
lrwxrwxrwx 1 root root       10 Jul 18 02:30 crictl -> containerd
-rwxr-xr-x 1 root root 84027016 Jul 18 02:31 hyperkube
-rwxr-xr-x 1 root root  3363168 Jul 18 02:31 cni
-rwxr-xr-x 1 root root  7656672 Jul 18 02:31 runc
-rwxr-xr-x 1 root root  6042208 Jul 18 02:31 containerd-shim

**Comment by ravirdv** [comment]
running "make" in project root should generate k3s binary (40mb) under dist/artifacts

**Comment by warmchang** [comment]
When K3S starts, it will automatically extract the binary programs to the specific directory (the first time), and run them.

The main binary is containerd, the k3s-agent/k3s-server/crictl/kubectl soft linked to it:

```
 root@william  /home/fedora  ll /var/lib/rancher/k3s/data/1f8f9ad9556f55492e3461a731703cb5679a41e0ec882d7f94a9b460a2350b03/bin | grep containerd
-rwxr-xr-x 1 root root  92M Jun 19 22:09 containerd
-rwxr-xr-x 1 root root 5.8M Jun 19 22:09 containerd-shim
lrwxrwxrwx 1 root root   10 Jun 21 06:56 crictl -> containerd
lrwxrwxrwx 1 root root   10 Jun 21 06:56 k3s-agent -> containerd
lrwxrwxrwx 1 root root   10 Jun 21 06:56 k3s-server -> containerd
lrwxrwxrwx 1 root root   10 Jun 21 06:56 kubectl -> containerd
 root@william  /home/fedora     
```
