### ISSUE TITLE
[Documentation] HA Configuration and Examples

### ISSUE THREAD

**Issue by davidnuzik** [rancher/k3s#656]
We need to clearly define in our documentation how to set up HA and note what is currently supported.
- We need to provide a minimum of one good example that would suggest how to set this up for production.
- We need to provide a chart that provides a map explaining the different elements so it's easy to visualize.

**Comment by davidnuzik** [comment]
This issue will be partially complete based on incoming changes to the docs. https://github.com/rancher/docs/pull/1886

Later we'd like to expand upon this and provide at least an image showing basically a map of a proper HA configuration and discuss in more detail what a production set up may look like and involve.

**Comment by schmitch** [comment]
actually the doc update missed: https://github.com/rancher/k3s/issues/710

In the docs it says: 
> You should create a TCP Load Balancer for the master nodes. This will allow worker nodes to address any master node should one of them fail. The Load Balancer should point to each of the master nodes on port 6443 (Default port for the server).

however with k3s this is not strictly necessary.

**Comment by davidnuzik** [comment]
Will fix this. Thanks!
