### ISSUE TITLE
High CPU Usage on Raspberry Pi Master

### ISSUE THREAD

**Issue by jrcichra** [rancher/k3s#658]
**Describe the bug**
Higher than expected CPU usage from k3s server.

**To Reproduce**
Download K3S on a Raspberry Pi 3 and disable traefik and the svmlb. Use MetalLB instead.

**Expected behavior**
Less CPU usage with few pods running on master.

**Screenshots**
![image](https://user-images.githubusercontent.com/1342149/61572510-11e6b400-aa6d-11e9-9cec-93376a9dd6a1.png)
![image](https://user-images.githubusercontent.com/1342149/61572516-36429080-aa6d-11e9-81c4-38f6eaca8140.png)
![image](https://user-images.githubusercontent.com/1342149/61572519-3e023500-aa6d-11e9-9c7f-42dde1213b52.png)

**Comment by kingdevnl** [comment]
That isn't realy high cpu usage
