### ISSUE TITLE
Failed to start sandbox container task : cgroups: cgroup deleted: unknown

### ISSUE THREAD

**Issue by danhawkes** [rancher/k3s#660]
**Describe the bug**  
Pod fails to start with error:

```
Warning FailedCreatePodSandBox 11s kubelet, home  Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container task "79a03b1676412f28c6e9ff548e87236a7dc7f342f10af9d3f524600bfe5e4aa0": cgroups: cgroup deleted: unknown
```

**To Reproduce**
- Install alpine standard `3.10.1` to disk
- Follow instructions in https://rancher.com/docs/k3s/latest/en/running/#alpine-linux  
  (Note my install seems to be using grub rather than sysilnux, so kernel params were added to `/etc/default/grub`):
  ```
  GRUB_CMDLINE_LINUX_DEFAULT="modules=sd-mod,usb-storage,ext4 nomodeset quiet rootfstype=ext4 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory"
  ```
  Verified params are present in `/proc/cmdline`.
- Attempt to start pod:  
  ```
  kubectl run testpod --image alpine:3.8 --generator=run-pod/v1 --command date
  ``` 

**Expected behavior**

Pod starts.

**Additional context**

k3s `0.7.0`, but same with `0.6.1`.

Debug logs:
[k3s.log](https://github.com/rancher/k3s/files/3414548/k3s.log)

**Comment by danhawkes** [comment]
Reproduceable in vagrant:

```
vagrant destroy -f && vagrant up
vagrant ssh -c 'sudo /usr/local/bin/k3s kubectl get events'
```

Vagrantfile:
```ruby
Vagrant.configure("2") do |config|

  config.vm.box = "generic/alpine310"

  $s1 = <<-HEREDOC
echo "cgroup /sys/fs/cgroup cgroup defaults 0 0" >> /etc/fstab

cat >> /etc/cgconfig.conf <<EOF
mount {
  cpuacct = /cgroup/cpuacct;
  memory = /cgroup/memory;
  devices = /cgroup/devices;
  freezer = /cgroup/freezer;
  net_cls = /cgroup/net_cls;
  blkio = /cgroup/blkio;
  cpuset = /cgroup/cpuset;
  cpu = /cgroup/cpu;
}
EOF

sed -i "s,^\\(default_kernel_opts=\\"[^\\"]*\\)\\(\\"\\),\\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\\2,g" /etc/update-extlinux.conf

update-extlinux

  HEREDOC

  config.vm.provision "shell", inline: $s1
  config.vm.provision :reload
  config.vm.provision "shell", inline: "curl -sfL https://get.k3s.io | sh -"
  config.vm.provision :reload
  config.vm.provision "shell", inline: "sleep 10; /usr/local/bin/k3s kubectl run testpod --image alpine:3.8 --generator=run-pod/v1 --command date"
end
```

**Comment by danhawkes** [comment]
Seems to be related to a clash with the built in cgroups openrc service. Works on 3.7, broken 3.8 onwards. Still investigating...

**Comment by danhawkes** [comment]
Fix appears to be to use the cgroups service instead of the manual configuration above. So replace:
```bash
echo "cgroup /sys/fs/cgroup cgroup defaults 0 0" >> /etc/fstab

cat >> /etc/cgconfig.conf <<EOF
mount {
  cpuacct = /cgroup/cpuacct;
  memory = /cgroup/memory;
  devices = /cgroup/devices;
  freezer = /cgroup/freezer;
  net_cls = /cgroup/net_cls;
  blkio = /cgroup/blkio;
  cpuset = /cgroup/cpuset;
  cpu = /cgroup/cpu;
}
EOF
``` 
with
```bash
rc-update add cgroups
```

Can this be updated in the docs?

**Comment by erikwilson** [comment]
Many thanks for tracking this down @danhawkes! 

I am curious if this is a difference in cgroup1 vs cgroup2. The docs should probably be updated to say something like, "If /etc/init.d/cgroups exists run ..., otherwise ...", with some context around the versions also.

We should probably also update the install script & docs to include "want cgroups" in the depend part of the openrc init script.

**Comment by radhus** [comment]
Thanks for finding this @danhawkes , I opened #1354 which should do the same as you suggest 🙂 Feel free to test it if you want.
