### ISSUE TITLE
Deleting node, reinstalling and rejoining fails with node password rejected

### ISSUE THREAD

**Issue by NickyHeuperman** [rancher/k3s#663]
Steps to reproduce
Create 2 node cluster
Uninstall k3s-agent through uninstall script
delete node on master
install k3s-agent like before

result:
node joining is rejected because of invalid password

I probably need to delete this password somewhere, I however have no idea where.
Any insight in the matter would be greatly appreciated

**Comment by NickyHeuperman** [comment]
found it, the password is stored in: /var/lib/rancher/k3s/server/node-passwd
removing the entry resolves the problem

**Comment by mrconnerton** [comment]
I  had this same issue. The file I had to update was on the master node and was /var/lib/rancher/k3s/server/cred/node-passwd. Remove the line with the hostname that is causing issues then I rebooted that agent server.
