### ISSUE TITLE
Support for encryption provider config

### ISSUE THREAD

**Issue by davidnuzik** [rancher/k3s#666]
This issue is for tracking effort to add this as an enhancement.
- Encrypt k8s secrets at rest
- For external db

**Comment by cjellick** [comment]
Need more details on what this is for. Is this for encrypting k8s secrets at rest?

**Comment by davidnuzik** [comment]
Yes I believe so. This is a nice-to-have for GA. We should discuss in the meeting today.

**Comment by davidnuzik** [comment]
PR: https://github.com/rancher/k3s/pull/1192

**Comment by ShylajaDevadiga** [comment]
Verified using k3s v1.17.4-alpha1+k3s1, passing the --secrets-encryption flag encrypts the secrets at rest.

```select * from kine where name like "/registry/secrets/default/db-user-pass2";
9298|/registry/secrets/default/db-user-pass2|1|0|0|0|0|k8s:enc:aescbc:v1:aescbckey:{+h?=]V?&hT?-???!_?i?̣?D??r???p??5??~?????~?)=z??9?l?
                                                                                                                                       b?_?E/vȥ??ǝt?????????Ă*??Y??^?}|```

**Comment by davidnuzik** [comment]
Docs issue: https://github.com/rancher/k3s/issues/1315

**Comment by amitkatyal** [comment]
@ShylajaDevadiga, which file to check below output to confirm that data is encrypted at rest.

9298|/registry/secrets/default/db-user-pass2|1|0|0|0|0|k8s:enc:aescbc:v1:aescbckey:{+h?=]V?&hT?-???!_?i?̣?D??r???p??5??~?????~?)=z??9?l?

**Comment by brandond** [comment]
@amitkatyal  I'm not sure whether to answer you here or in the [other issue](https://github.com/rancher/k3s/issues/1558#issuecomment-708978122) where you asked the same question... you would need to query the etcd/sql/sqlite backend directly to see the encrypted version. There is a comment in the other issue that shows making a SQL query to read the encrypted value, if you're using etcd you would need to need to use an etcd client (etcdctl, for example) to access the raw data.

**Comment by amitkatyal** [comment]
> @amitkatyal I'm not sure whether to answer you here or in the [other issue](https://github.com/rancher/k3s/issues/1558#issuecomment-708978122) where you asked the same question... you would need to query the etcd/sql/sqlite backend directly to see the encrypted version. There is a comment in the other issue that shows making a SQL query to read the encrypted value, if you're using etcd you would need to need to use an etcd client (etcdctl, for example) to access the raw key corresponding to an encrypted secret.

Thanks @brandond !!
