### ISSUE TITLE
ctr reports incorrect namespaces

### ISSUE THREAD

**Issue by sahlex** [rancher/k3s#668]
**Bug Description**
When I use the ctr CLI of k3s to show the namespaces it always returns ```k8s.io```

**To Reproduce**
```
# ctr namespaces ls
k8s.io
```

**Expected behavior**
All namespaces should be returned like with ```kubectl ```
```
# kubectl get namespaces
NAME                   STATUS   AGE
cattle-system          Active   49d
default                Active   49d
gravitee               Active   48d
instana-agent          Active   8d
kube-node-lease        Active   49d
kube-public            Active   49d
kube-system            Active   49d
kubernetes-dashboard   Active   49d
```

**Comment by erikwilson** [comment]
I think this is to be expected, the concept of namespaces in k8s and namespaces in containerd are not necessarily 1:1, also see https://github.com/containerd/containerd/blob/master/docs/namespaces.md.

**Comment by sahlex** [comment]
Ok, thanks. Apparently I can't rely on that method. Namespaces in k8s/ containerd seem to be on different levels or scopes.
