### ISSUE TITLE
Metrics Server certificate error "x509: subject with cn=kubernetes-proxy is not in the allowed list: [system:auth-proxy]"

### ISSUE THREAD

**Issue by ahmedmagdiosman** [rancher/k3s#686]
**Describe the bug**
Metrics server does not provide metrics.
**To Reproduce**
1. From ``kubernetes-incubator/metrics-server``, run ``kubectl create -f deploy/1.8+``
2. Wait for metrics server pod to be running.
3. ``kubectl -n kubectl logs -f metrics-server-XXXX``
````
I0729 21:07:32.810717       1 serving.go:273] Generated self-signed cert (apiserver.local.config/certificates/apiserver.crt, apiserver.local.config/certificates/apiserver.key)
[restful] 2019/07/29 21:07:54 log.go:33: [restful/swagger] listing is available at https://:443/swaggerapi
[restful] 2019/07/29 21:07:54 log.go:33: [restful/swagger] https://:443/swaggerui/ is mapped to folder /swagger-ui/
I0729 21:07:54.504591       1 serve.go:96] Serving securely on [::]:443
W0729 21:08:23.100483       1 x509.go:172] x509: subject with cn=kubernetes-proxy is not in the allowed list: [system:auth-proxy]
E0729 21:08:23.106448       1 authentication.go:62] Unable to authenticate the request due to an error: [x509: subject with cn=kubernetes-proxy is not allowed, x509: certificate signed by unknown authority]
````
4. Adding:
````
        command:
        - /metrics-server
        - --kubelet-insecure-tls
        - --kubelet-preferred-address-types=InternalIP
````
to the deployment container spec does not resolve the issue.

**Expected behavior**
No cert issues.

**Additional context**
- k3s version 0.7
- On-prem SBC cluster of x86 (1x) and arm64 (3x)

**Comment by warmchang** [comment]
I made this change with "metrics-server-deployment.yaml":
```
@@ -30,8 +30,11 @@
       containers:
       - name: metrics-server
         image: k8s.gcr.io/metrics-server-amd64:v0.3.3
-        imagePullPolicy: Always
+        # imagePullPolicy: Always
+        imagePullPolicy: IfNotPresent
+        args:
+        - --kubelet-insecure-tls
+        - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
         volumeMounts:
         - name: tmp-dir
           mountPath: /tmp
```

The metric-server works well, @ahmedmagdiosman hope it helps you.

```
 root@william  /home/fedora  kubectl get all -n kube-system --selector="k8s-app=metrics-server"                                                  ✔  ⚡  6539  02:46:59
NAME                                 READY   STATUS    RESTARTS   AGE
pod/metrics-server-9b68d8cb4-mq22j   1/1     Running   3          10d

NAME                             READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/metrics-server   1/1     1            1           10d

NAME                                       DESIRED   CURRENT   READY   AGE
replicaset.apps/metrics-server-9b68d8cb4   1         1         1       10d
 root@william  /home/fedora  kubectl top pod                                                                                                     ✔  ⚡  6540  02:47:50
NAME                                   CPU(cores)   MEMORY(bytes)
alpine-qos-william                     0m           1Mi
deploy-connectivity-59c44dcf4b-kjjw9   0m           2Mi
security-context-demo                  0m           0Mi
 root@william  /home/fedora    
```

**Comment by yamt** [comment]
`cn=kubernetes-proxy` seems like an old cert used by pre-0.7.0 versions of k3s.

**Comment by ahmedmagdiosman** [comment]
@warmchang I already mentioned that I tried that.

@yamt That's true I've used k3s since 0.5. Everything was working fine until 0.7. I've looked into the changelog and there's mention of a Certs refactor. Everything worked without manual creation of certificates before 0.7. Do I need to create them manually now?

Do you know of anyway of fixing this without nuking my cluster? Is there somewhere I can remove existing certs to force k3s to create new ones? 
Apologies if there's an obvious way, I'm still learning about Kubernetes.

**Comment by dewet22** [comment]
FWIW, my upgrade from 0.6 to 0.7 also borked my metrics server and I couldn't fix it despite spending an hour on magic incantations so I ultimately just blew everything away. Luckily I can stand up a cluster from scratch very quickly (yay infrastructure-as-code and persistent volumes).

Also FYI, I just deploy it from helm chart directly instead of individual manifests:

```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  namespace: kube-system
  name: metrics-server
spec:
  chart: stable/metrics-server
  valuesContent: |-
    affinity:
      node: kubernetes.io/arch=arm
    image:
      repository: gcr.io/google_containers/metrics-server-arm:v0.3.2
```

**Comment by jorneilander** [comment]
I managed to fix it by allowing the ```cn=kubernetes-proxy``` to connect to the API-server.

See: https://github.com/kubernetes-incubator/metrics-server/issues/292#issuecomment-516382818

**Comment by ahmedmagdiosman** [comment]
Thanks! this did the trick! I'm also curious why this happened in the first place.

Anyway I'm closing this since there's a workaround for now and it seems clean deployments of v0.7 do not have this issue.
