### ISSUE TITLE
WHat is Actual Minimum System Requirements?

### ISSUE THREAD

**Issue by akuscu-smartpulse** [rancher/k3s#699]
I confused about system requirements.It says:
Linux 3.10+
512 MB of ram per server
75 MB of ram per node
200 MB of disk space
x86_64, ARMv7, ARM64

What is the meaning of : 
512 MB of ram per server
and
75 MB of ram per node

What is the difference of node and server ?

**Comment by vFondevilla** [comment]
AFAIK the server is the control node of K3s and the node is the worker.

**Comment by alexellis** [comment]
I would agree with @vFondevilla on that one.

**Comment by warmchang** [comment]
- server = controller + worker

> it's the default server function, but can use "--disable-agent" option to disable the worker/node feature.

- node = worker

**Comment by raul1991** [comment]
Can I run it on raspberry pi model 2 with 1 Gb ram and 4 vcpus ?

**Comment by alexellis** [comment]
@raul1991 yes, I have done that myself.
