### ISSUE TITLE
Switch to go v1.12.8

### ISSUE THREAD

**Issue by ibuildthecloud** [rancher/k3s#700]
Due to https://github.com/golang/go/issues/33405 containerd will leak fds as reported here https://github.com/containerd/containerd/issues/3481.

As soon as go 1.12.8 is released we should update to it to fix this issue.

**Comment by warmchang** [comment]
go1.12.8 is out https://groups.google.com/forum/#!topic/golang-announce/65QixT3tcmg

**Comment by ibuildthecloud** [comment]
1.12.8 was a security release, we need 1.12.8 which is out today.
