### ISSUE TITLE
website: Better wording for "Uses only 512 MB of RAM"

### ISSUE THREAD

**Issue by ryanmjacobs** [rancher/k3s#71]
Honestly, this is such a superficial report... but when I first saw the website, my immediate thought was: wow, 512 MB seems like a huge overhead for this program's runtime. Obviously, what this is trying to say is that k3s will run on machines with only 512 MB RAM.

Somehow, it'd be nice to connote that this isn't an overhead of k3s. You still get most of that RAM for your containers.

**Current text**
> Uses only 512 MB of RAM.

**Proposed text**
> Supports nodes with only 512 MB of RAM.
> Supports nodes with 512 MB of RAM.

or
> Only 512 MB of RAM required to run.

or
> Supports systems with only 512 MB of RAM.

or
> Runs on machines with only 512 MB of RAM.

or something else. I'm not too sure.

**Screenshot of current text**
![screenshot of current wording](https://user-images.githubusercontent.com/4251257/53510194-3e744200-3a72-11e9-95f5-4cf12a51ebf5.png)

**Similar reports of confusion on HN today**
![evidence of confusion on HN](https://user-images.githubusercontent.com/4251257/53510249-59df4d00-3a72-11e9-8e46-cf32791eb407.png)

**Comment by ibuildthecloud** [comment]
That's a really good point.  I'll work with some wordsmiths on this :)

**Comment by lvuch** [comment]
@ryanmjacobs thank you for pointing it out and the suggestions! this has been fixed https://github.com/rancherlabs/k3s-website/pull/28

**Comment by ibuildthecloud** [comment]
It's live now.

**Comment by bbrks** [comment]
I hate to bikeshed, but the new phrasing is no better than the original. My immediate conclusion was that k3s requires 512MB of RAM to run.
