### ISSUE TITLE
Server panic when starting with k3d

### ISSUE THREAD

**Issue by jlevesy** [rancher/k3s#712]
**Describe the bug**

Hey folks,

With k3d, we can observe running our test suite that the k3s server container sometimes panics after startup.

Here is an example of a the trace.

[k3spanic.log](https://github.com/rancher/k3s/files/3471349/k3spanic.log)

**To Reproduce**

Unfortunately I don't have a stable way to reproduce this issue outside of our test suite.

- `k3d create --name="k3s-default" --workers="2"  --publish="80:80" --publish="443:443" --publish="8080:8080" --server-arg --no-deploy  --server-arg traefik`
- We poll each second `k3d get-kubeconfig` after, but I doubt it is related.

**Expected behavior**

No panic :sweat_smile:.

**Additional context**

- We're running our test suite using docker in docker. (k3d is being run inside a docker container alongside another "hosted" docker daemon).
- This test suite can be run and generate high CPU / disk pressure which could emphasize this issue.
- That might not be the best bug report ever, if you have ideas how to reproduce in a more stable way this problem, I would be glad to to try it.

**Comment by erikwilson** [comment]
Including the panic log is perfect, along with the info to reproduce it provides exactly the data needed to fix the bug. Many thanks for reporting this @jlevesy!

**Comment by erikwilson** [comment]
Should be fixed with #714 and released shortly in v0.8.1, please re-open if there is still an issue.

**Comment by jlevesy** [comment]
Thanks ! :)
