### ISSUE TITLE
Use --no-deploy after the fact

### ISSUE THREAD

**Issue by jonfairbanks** [rancher/k3s#717]
**Is your feature request related to a problem? Please describe.**

Unfortunately our cluster was deployed using the k3s defaults before we really understood the implications of using Traefik's default config. Now, we'd like to use Nginx instead of Traefik. 

Is it possible to remove Traefik and/or other services deployed by default without removing the cluster and starting over?

**Describe the solution you'd like**

A command or process to add `--no-deploy` to a pre-existing cluster. 

**Describe alternatives you've considered**

We've considered uninstalling the cluster and starting over, but this seems fairly drastic.

**Comment by yamt** [comment]
"kubectl delete -n kube-system helmcharts traefik" would remove the default traefik.

**Comment by jonfairbanks** [comment]
Thanks!

**Comment by jonfairbanks** [comment]
Is it possible to do the same for servicelb?

Trying `kubectl delete -n kube-system helmcharts servicelb` I get this error:

```
Error from server (NotFound): helmcharts.helm.cattle.io "servicelb" not found
```

**Comment by yamt** [comment]
unless you have services with type=loadbalancer, i think you can just reboot with `--no-deploy servicelb`

**Comment by jonfairbanks** [comment]
What do you mean by "reboot"?

**Comment by jwbaart** [comment]
> What do you mean by "reboot"?

would also be interested how to reboot with `--no-deploy-servicelb`

**Comment by radicand** [comment]
I had success removing servicelb by executing the install command I originally used again, and then restarting the k3s service.

Any stray servicelb pods can then be manually deleted if they don't disappear.

**Comment by jonfairbanks** [comment]
Thanks @radicand, that worked. 

To confirm, with a pre-existing cluster I ran the following:
```
curl -sfL https://get.k3s.io | sh -s - server --no-deploy traefik --no-deploy servicelb
sudo k3s kubectl get pods --all-namespaces --watch
sudo k3s kubectl delete -n kube-system helmcharts traefik
```

This will clean up the cluster, but if you reboot... helm will re-install traefik. To resolve this, you'll also need to remove/rename the manifest file:
```
sudo mv /var/lib/rancher/server/manifests/traefik.yaml /var/lib/rancher/server/manifests/traefik.yaml.bak
```
