### ISSUE TITLE
Server panic with docker in docker in docker (!!!) and tmpfs.

### ISSUE THREAD

**Issue by jlevesy** [rancher/k3s#721]
**Describe the bug**

This one is somehow farfetched,  and I would understand if you folks don't want to fix it :sweat_smile:.

In our e2e test suite, each test is being ran in a dedicated `docker:dind` container (the test runtime) on which we run k3s using k3d.

To speed up our test suite, we're experimenting mounting the `/var/lib/docker` of our test runtime container as a tmpfs. 

This actually makes k3s panic after startup. Here is a [panic log example](https://github.com/rancher/k3s/files/3481852/k3s-panic.log).

**To Reproduce**

```
# Create the test runtime container
docker run --privileged -d --rm --name test-runtime --mount type=tmpfs,destination=/var/lib/docker docker:18.09-dind

# Get a shell inside this test runtime
docker exec -ti  test-runtime ash

# Add curl and install k3d with it.
apk add curl
curl -sSLO https://github.com/rancher/k3d/releases/download/v1.3.1/k3d-linux-amd64
mv k3d-linux-amd64 /bin/k3d
chmod +x /bin/k3d

# Create a k3s cluster using k3d
k3d create

# After a while you should see the k3s server container panicking.
```

**Expected behavior**

No panic :sweat_smile: 

**Additional context**

Here's system information of my docker host 
```
Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 701
 Server Version: 19.03.1-ce
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 85f6aa58b8a3170aec9824568f7a31832878b603.m
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.2.5-arch1-1-ARCH
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.39GiB
 Name: dexcel
 ID: 4AFS:SCA5:YJQO:OMG5:WGSD:MS43:BW6Z:CBIO:57BU:OLR3:XJZR:H6QY
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Labels:
 Experimental: false
 Insecure Registries:
  10.0.0.1:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

```
(66 ms) ~ λ uname -a
Linux dexcel 5.2.5-arch1-1-ARCH #1 SMP PREEMPT Wed Jul 31 08:30:34 UTC 2019 x86_64 GNU/Linux
```

And, anyway, thanks for this amazing tool and your help :tada:  !

**Comment by erikwilson** [comment]
Looks like this is a known issue for kind: https://kind.sigs.k8s.io/docs/user/known-issues/
That page links this issue as the root cause https://github.com/moby/moby/issues/9939, am guessing there is something else going on and the upstream kubelet code probably needs updating.

**Comment by dduportal** [comment]
Hi @erikwilson , it looks like that these known issues are related to btrfs filesystem.

But here, it is a tmpfs as underlying filesystem.

Did I misunderstood something?

**Comment by erikwilson** [comment]
That is correct @dduportal, but the issue & result look very similar. This may be something completely different and unrelated, but it appears to be an upstream docker or kubernetes bug, not sure there is a lot we can do in k3s.

**Comment by erikwilson** [comment]
Testing out using a volume for /var/lib/docker also fails. If we can fix it would probably need to happen in k3d.
