### ISSUE TITLE
How to access / edit kubernetes controller manager in K3s

### ISSUE THREAD

**Issue by balamuru** [rancher/k3s#730]
I'd like to know how to access / edit kubenernetes controller manager (in order to tweak with some horizontal auto-scaler settings)?

In upstream K8s, this file would normally be at /etc/kubernetes/manifests/kube-controller-manager.yaml

**Comment by warmchang** [comment]
FYI: https://rancher.com/docs/k3s/latest/en/installation/#customizing-components

**Comment by balamuru** [comment]
Thanks
