### ISSUE TITLE
kubectl port-forward does not work as expected for port 80

### ISSUE THREAD

**Issue by buzypi** [rancher/k3s#733]
**Describe the bug**
Port forward with incoming port 80 does not work as expected, however other ports work.

**To Reproduce**
Run the following commands after k3s installation:
```
# Create a deployment
kubectl run --image nginx nginx
# Create a service
kubectl expose deployment/nginx --port 80 --target-port 80
# Port forward the service
kubectl port-forward --address 0.0.0.0 svc/nginx 80:80
```

Go to the browser or curl the IP, to access the Nginx server running on port 80.

We see *404 page not found*

However, these work as expected:
```
kubectl port-forward --address 0.0.0.0 svc/nginx 6080:80
curl ip:6080
kubectl port-forward --address 0.0.0.0 svc/nginx 81:80
curl ip:81
```

**Expected behavior**
See the default Nginx page, with a 200 OK response

**Additional context**
The same example works fine in k8s

**Comment by warmchang** [comment]
Port 80 used by build-in load balancer default, you can disable it by "--no-deploy servicelb" option:

https://rancher.com/docs/k3s/latest/en/configuration/#service-load-balancer

**Comment by buzypi** [comment]
Great!
