### ISSUE TITLE
Can not find systemd or openrc to use as a process supervisor for k3s

### ISSUE THREAD

**Issue by a1exus** [rancher/k3s#734]
Hello  World!

I've tried to perform installation, yet ran into following issue:

```
$ curl -sfL https://get.k3s.io | sh -
[ERROR]  Can not find systemd or openrc to use as a process supervisor for k3s
$ uname -a
Darwin mbp.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
$ 
```

Please advise.

**Comment by warmchang** [comment]
Darwin... MacOSX... doesn't support, ref: https://github.com/rancher/k3s/issues/88

But you can run k3s in docker container (and [docker-compose](https://github.com/rancher/k3s/blob/master/docker-compose.yml)):

> docker-compose up --scale node=3

**Comment by Anishmourya** [comment]
I did solve this through multipass ubuntu Vm, successfully installed k3s, can't wait for mac support,

**Comment by afmsavage** [comment]
Ran into this same issue on WSL 2 which is understandable since its not full blown Linux.  Figured I'd note that here just so others don't ask.  

As @Anishmourya said above, you can launch k3s on a Windows system in an Ubuntu VM.  You can use Multipass from Ubuntu to make creating VMs easier.

**Comment by davidnuzik** [comment]
Yes at this time we do not support running K3s MacOS. You can run K3s in docker or you can leverage K3d https://github.com/rancher/k3d

In the future (possibly near future) we _may_ support WSL 2

**Comment by hacker-h** [comment]
I just ran into this issue on an Alpine VM:
```
node1] (local) root@192.168.0.48 ~
$ curl -sfL https://get.k3s.io | sh -
[ERROR]  Can not find systemd or openrc to use as a process supervisor for k3s
[node1] (local) root@192.168.0.48 ~
$ cat /etc/*release
3.10.3
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.10.3
PRETTY_NAME="Alpine Linux v3.10"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```

This is a default VM of labs.play-with-docker.com

**Comment by afmsavage** [comment]
Have you followed the instructions in the docs for getting k3s to work on alpine @hacker-h ?  I'm guessing its impossible to do inside of play-with-docker since a reboot is required after editing cgroup settings.

https://rancher.com/docs/k3s/latest/en/advanced/#additional-preparation-for-alpine-linux-setup

**Comment by nayanex** [comment]
> Yes at this time we do not support running K3s MacOS. You can run K3s in docker or you can leverage K3d https://github.com/rancher/k3d
> 
> In the future (possibly near future) we _may_ support WSL 2

It's July of 2021, where is this future? 😄

**Comment by nayanex** [comment]
I was only able to get around this issue by using a virtual machine with Vagrant and Virtual Box on Windows.

Vagrant file:

```
ENV["TERM"]="linux"

Vagrant.configure("2") do |config|
  
  # set the image for the vagrant box
  config.vm.box = "opensuse/Leap-15.2.x86_64"
  ## Set the image version
  # config.vm.box_version = "15.2.31.212"

  # st the static IP for the vagrant box
  config.vm.network "private_network", ip: "192.168.50.4"
  
  # consifure the parameters for VirtualBox provider
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 4
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
  end
end
```

In the same directory as your Vagrant file, run:
```
vagrant up
vagrant status
vagrant ssh
curl -sfL https://get.k3s.io | sh -
```

**Comment by doneble001** [comment]
It's June of 2024, where is this future?
