### ISSUE TITLE
after loading tar file on a airgap host no new images are present

### ISSUE THREAD

**Issue by slmagus** [rancher/k3s#735]
**Describe the bug**
Following the documentation to place tar ball in images directory
`sudo cp ./k3s-airgap-images-$ARCH.tar /var/lib/rancher/k3s/agent/images/`
https://rancher.com/docs/k3s/latest/en/running/

My pod was still attempting to download k8s.gcr.io/pause:3.1
Failed create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox image "k8s.gcr.io/pause:3.1": failed to pull image "k8s.gcr.io/pause:3.1": failed to resolve image "k8s.gcr.io/pause:3.1"

running sudo crictl images did not list any images.

**To Reproduce**
have airgaped k3s instance, load images in to specified directory and attempt to deploy pods or list images with `sudo crictl images`

**Expected behavior**
1. Documentation should state commands to have system recognize images have been loaded(restart some service or reboot, I don't' know what exactly what should be done). 
or 
2. Something should automatically detect images have been loaded.

**Workaround**
 Reboot host after loading the tar ball. Run sudo crictl images results in images listed and pod creation.

**Additional Information**
Thanks for supporting air-gap installs!! They are very useful.

I was using a k3OS instance

**Comment by erikwilson** [comment]
The k3s service probably needs a restart to pick up the files that were copied.

**Comment by davidnuzik** [comment]
Hello @slmagus please let us know if you still have the issue after restarting the k3s service. Thanks!

**Comment by slmagus** [comment]
Actually, this was a documentation bug at the time of writing so I don't think it is correct to remove ~kind/documentation The new instructions here https://rancher.com/docs/k3s/latest/en/installation/airgap/ Cover upgrading and a restarting of the services. So I think it is safe to say this issue can be closed.
