### ISSUE TITLE
SHA Mismatch arm64

### ISSUE THREAD

**Issue by charles-d-burton** [rancher/k3s#740]
**Describe the bug**
SHA Mismatch

**To Reproduce**
Run the K3S install script for latest on ARM64

**Expected behavior**
It installs

**Additional context**
[INFO]  Finding latest release
[INFO]  Using v0.8.0 as release
[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v0.8.0/sha256sum-arm64.txt
[INFO]  Downloading binary https://github.com/rancher/k3s/releases/download/v0.8.0/k3s-arm64
[INFO]  Verifying binary download
[ERROR]  Download sha256 does not match ce72a869c1735a7d774ade3dd476375e3d3c3f4ca27da72aecd989a8748a3500
c89c856581f94a12f0c78fb0b0acbf4f7aa45b671777b968598a6a19597916c7, got c89c856581f94a12f0c78fb0b0acbf4f7aa45b671777b968598a6a19597916c7

**Comment by warmchang** [comment]
Contents in file "sha256sum-arm64.txt":
```
2aeeab5b16d784d82a31cb54bcf99cf4215d3adadb6bbedbba51554c7df7e8d1  hyperkube-arm64
ce72a869c1735a7d774ade3dd476375e3d3c3f4ca27da72aecd989a8748a3500  k3s-airgap-images-arm64.tar
c89c856581f94a12f0c78fb0b0acbf4f7aa45b671777b968598a6a19597916c7  k3s-arm64
```

Check the k3s binary by sha256sum:
```
$ sha256sum ./k3s-arm64
c89c856581f94a12f0c78fb0b0acbf4f7aa45b671777b968598a6a19597916c7  ./k3s-arm64
$
```

**Comment by erikwilson** [comment]
It looks like this error might come from a very old version of the install script, before air-gap support was added.

Can you verify how you are getting the script @charles-d-burton?

**Comment by charles-d-burton** [comment]
I'm just running:
```bash
curl -sfL https://get.k3s.io | sh -
```

**Comment by charles-d-burton** [comment]
Huh, weird.  I just re-ran it and it worked fine.  I'll close it, maybe I was hitting a cached version or something.  I tried it a few times throughout the day I reported it.
