### ISSUE TITLE
Ability to subscribe to k3s updates

### ISSUE THREAD

**Issue by davidnuzik** [rancher/k3s#749]
I'd like to propose adding a feature that may allow a user to opt-in to getting k3s updates. Ideally, we could not only get notified when there is a new k3s update, but provide the ability to upgrade k3s (by prompting the user for confirmation).

Some ideas we have:
- Could prompt user during k3s install process if they would like to opt-in to getting notified when there are k3s updates.
- A controller could do checks to see if there is a new k3s version when user prompts or perhaps also on a cron schedule?
- User should do a k3s cli argument to manually check for any k3s updates
- Upgrade policy could be set by user (auto or manual for example) (manual by default)
- If there is an update, ideally user could choose to go ahead and upgrade k3s; the process should be seamless to upgrade if possible in order to avoid any interruptions. The user should also be warned of the risks of upgrading (what if they are in production, etc) via a prompt that briefly explains the risk.

**Comment by runningman84** [comment]
I guess there should be a k3s controller which takes care of updating k3s. I think this feature was annouced with k3os but never seen in real life...
