### ISSUE TITLE
Add information about surviving reboots

### ISSUE THREAD

**Issue by jimangel** [rancher/k3s#76]
**Is your feature request related to a problem? Please describe.**
No, request to document how to build a cluster that survives reboots.

**Describe the solution you'd like**
The systemd docs seem to only be for the server proc, not the agent / nodes. There might even be a better way to do this.

**Additional context**
My goal would be to create a pi cluster that _just works_ on (re)boot and believe this would be beneficial to others.

**Comment by ibuildthecloud** [comment]
Right now the curl script only really covers the server and not the agents.  Adding agent support is being tracked https://github.com/rancher/k3s/issues/65.  Once we support the agents, then the ideal is to just run the agents and servers under systemd and then nodes will just come back after a reboot and join back into the cluster.

**Comment by erikwilson** [comment]
Hi @jimangel, do the updated systemd installation & docs help with this?

**Comment by jimangel** [comment]
Hey @erikwilson, the instructions are way better today then they were a a couple months back. I see the snippet in the code to run `sudo systemctl enable k3s.service` which would solve this issue. It might be nice to call that out in the docs - but that might not be a problem to someone who's starting a net new install today. Thanks!
/close
