### ISSUE TITLE
uninstall doesn't remove iptables entries

### ISSUE THREAD

**Issue by erknie** [rancher/k3s#774]
Thanks for helping us to improve k3s! We welcome all bug reports. At this stage, we are also looking for help in testing/QAing fixes. Once we've fixed you're issue, we'll ping you in the comments to see if you can verify the fix. We'll give you details on what version can be used to test the fix. Additionally, if you are interested in testing fixes that you ***didn't*** report, look for the issues with the `status/to-test` label. You can pick any of these up for verification.  ***You can delete this message portion of the bug report.***

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by erknie** [comment]
When you run the uninstall script, it still leaves all the iptables rules k3s added which can cause problems.

**Comment by jadsonlourenco** [comment]
You can use ```iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X``` to delete all rules after uninstall.

**Comment by abusaidm** [comment]
@jadsonlourenco this will remove all the rules and if you are on SSH you will be kicked out of the VM.

**Comment by jadsonlourenco** [comment]
@abusaidm nop, I did it many times and the ssh session keep working and the port 22 keep open. I think when the iptables don't have any rule mean = all ports are open.

**Comment by ShylajaDevadiga** [comment]
Verified using v0.10.2. Closing issue.
