### ISSUE TITLE
[v0.9.0] `--rootless` should add all required kubelet args automatically

### ISSUE THREAD

**Issue by AkihiroSuda** [rancher/k3s#784]
**Describe the bug**

Rootless mode should only require `--rootless` flag to be specified, but currently it also requires `--kubelet-arg "cgroup-driver=none" --kubelet-arg "feature-gates=SupportNoneCgroupDriver=true" --kubelet-arg "cgroups-per-qos=false" --kubelet-arg "enforce-node-allocatable="` (https://github.com/rootless-containers/usernetes/blob/f745b0ff06b5b5c5bcd9035699cb31fb72465948/boot/kubelet.sh#L15)

**To Reproduce**
`k3s server --rootless`
(k3s version v0.9.0-rc2 (4a5360ea))

**Expected behavior**
k3s should automatically append all required kubelet args when `--rootless` is specified

**Additional context**
The issue happened because `kubelet/cm: ignore cgroups error when running in userns` commit (https://github.com/rancher/k3s/commit/bfb380670177a7647a3a153c0e5dcf5807db2a58) was replaced by `kubelet: new feature gate: SupportNoneCgroupDriver` commit (https://github.com/rancher/k3s/commit/8cef2e14c4fa86b46e4be31baea84c014ef53f67)

**Comment by erikwilson** [comment]
Thanks for the detailed info @AkihiroSuda, unfortunately at the moment I am having problems getting things to where kubelet is starting, am receiving an error like:

```
vagrant🐮k3s:/Users/erik/go/src/github.com/rancher/k3s$ ./dist/artifacts/k3s server --rootless --kubelet-arg "cgroup-driver=none" --kubelet-arg "feature-gates=SupportNoneCgroupDriver=true" --kubelet-arg "cgroups-per-qos=false" --kubelet-arg "enforce-node-allocatable="
open: No such file or directory
FATA[2019-10-18T13:37:03.728357864-07:00] failed to setup network &{binary:slirp4netns mtu:65520 ipnet:0xc00053bfb0 disableHostLoopback:true apiSocketPath:}: setting up tap tap0: executing [[nsenter -t 10499 -n -m -U --preserve-credentials ip tuntap add name tap0 mode tap] [nsenter -t 10499 -n -m -U --preserve-credentials ip link set tap0 up]]: exit status 1
```
I have an `/etc/subuid` & `/etc/subgid` setup like the following:
```
root:165536:65536
vagrant:165536:65536
```

This will probably need extra attention & docs @ShylajaDevadiga

PRs are welcome if it is an easy fix :)

**Comment by AkihiroSuda** [comment]
Seems needs `modprobe tun`.

I tried to open PR, but could not compile the master..

**Comment by erikwilson** [comment]
Thanks for the info @AkihiroSuda. On alpine I needed to `apk add shadow-uidmap` and setup `/etc/subuid` & `/etc/subgid` as describe above. After a `modprobe tun` I was able to get a little bit further, but still seeing an error like:
```
open: Permission denied
FATA[2019-10-18T14:42:56.055281813-07:00] failed to setup network &{binary:slirp4netns mtu:65520 ipnet:0xc0010a3d40 disableHostLoopback:true apiSocketPath:}: setting up tap tap0: executing [[nsenter -t 11541 -n -m -U --preserve-credentials ip tuntap add name tap0 mode tap] [nsenter -t 11541 -n -m -U --preserve-credentials ip link set tap0 up]]: exit status 1
```

Running rootless as root got further, but still never to the point of starting the kubelet. :(

If you are in linux `./scripts/download && ./scripts/build && ./scripts/package-cli` might help create the k3s executable in `dist/artifacts`, running `git add ... && git commit -m 'wip' && make` on a machine with docker will take awhile but should work. We are on go 1.13 now also. There is a Vagrantfile that I use on MacOS in this repo which will nfs mount in the directory so you can use an external editor for changing the code. If there is anything I can do to help with compiling stuff please let me know. 

We will probably need to add back in the kubelet root directory configuration when running rootless:
```diff
diff --git a/pkg/agent/config/config.go b/pkg/agent/config/config.go
index 8bfb95ebdbe..407b410f9f0 100644
--- a/pkg/agent/config/config.go
+++ b/pkg/agent/config/config.go
@@ -348,6 +348,9 @@ func get(envInfo *cmds.Agent) (*config.Node, error) {
        nodeConfig.AgentConfig.KubeConfigNode = kubeconfigNode
        nodeConfig.AgentConfig.KubeConfigKubelet = kubeconfigKubelet
        nodeConfig.AgentConfig.KubeConfigKubeProxy = kubeconfigKubeproxy
+       if envInfo.Rootless {
+               nodeConfig.AgentConfig.RootDir = filepath.Join(envInfo.DataDir, "kubelet")
+       }
        nodeConfig.AgentConfig.PauseImage = envInfo.PauseImage
        nodeConfig.AgentConfig.IPSECPSK = controlConfig.IPSECPSK
        nodeConfig.AgentConfig.StrongSwanDir = filepath.Join(envInfo.DataDir, "strongswan")
```

**Comment by AkihiroSuda** [comment]
`chmod o=rw /host/dev/net/tun` seems needed (https://github.com/docker/for-mac/issues/3838)

I'll open separate issues for building artifacts
