### ISSUE TITLE
k3s is awesome, but lack of quick start guide 

### ISSUE THREAD

**Issue by netroby** [rancher/k3s#795]
k3s is amazing , but it not good for newbie who never used kubernetes.
How to build a web application , from very begin, to expose it with the ingress controller?

I would like contribute document , show how easy to run a real web (app) with k3s. 
where can i put (or contribute?)

**Comment by leematos** [comment]
I'm not a core maintainer and I don't speak for the project, but I think this would probably make sense on a personal blog or something, and the official docs could reference it.

**Comment by bbruun** [comment]
I've just created a small guide while searching for a quick guide for a friend (and ended up here)

The guide is here https://github.com/bbruun/k3s-getting-started and is a very first early draft, but give me feedback and I'll update it.

It is written from memory as I need to setup a vm to test it out and can't do that before I'm home as I already a have a fully instlaled and in-use k3s install on my laptop, so it will have to wait till I have time to a reinstall so I can update it fully - incl double checking the Ingress to set it up correctly (which sometimes fails if the `path` is set incorrectly (and not using `localhost` which I just typed in to get the thing written down now).

**Comment by cjellick** [comment]
that's pretty cool @bbruun. We'll compare it against our official docs and see what we can levarage.

FYI, offical docs are here:
https://github.com/rancher/docs/tree/master/content/k3s
Get published here:
https://rancher.com/docs/k3s/latest/en/

@netroby I was initially going to say that explaining how to spin up an app on k3s was outside the scope of k3s documentation, but perhaps an end-to-end quickstart _does_ make sense. Will consider it a bit more

**Comment by bbruun** [comment]
@cjellick just let me know what you think and I'll update it accordingly. I'll update my guide later tonight as I have time today. 

I agree with the deployment of an app, but most people that want to get started with Kubernetes end up where this issue was created I'd they have zero skills regarding kubernetes and communication with it. 

K3s offers a better and more practical "first install" method than exists and is the perfect tool to do both small and remote deployments and learning kubernetes from the ground up vs a normal bare metal cluster with eg kubeadm etc.

**Comment by bbruun** [comment]
@cjellick the documentation has been updated (rewritten) as I've had time to install a VM and follow through including finding a but in Ubuntu 18.04 Server as the pre-installed Docker version is a **snap** and that does not work with `k3s`.

The systemd service files have been updated and tested and the README-volumes.md have also been updated to get people started on the basics of working with bare metal on the very nice edition to Kubernetes aka **k3s** - it is a joy to work with :-)

**Comment by sandys** [comment]
hi,
i would like to chime in that there should be a section focused only around production usecases - AWS, spot instances, etc

**Comment by davidnuzik** [comment]
Related to https://github.com/rancher/k3s/issues/859
I created this issue to describe a refactor of Docs I am working on. We're going to include a minimum of one example for production such as on AWS. In the future we want to see if we can provide other examples too but for now we've chosen AWS.

**Comment by joshuataylor** [comment]
There is great documentation about HOW to install k3s, but not much about how traefik is used.

Would be awesome to have a cookbook of things such as "here is how you use a simple deployment/service/ingress with traefik to route to a helloworld".

**Comment by sandys** [comment]
@joshuataylor i want to link my similar ticket to this comment - https://github.com/rancher/k3s/issues/868

**Comment by vnwarrior** [comment]
we are looking for the same traefik help. how do we use our own certificate and route it to a particular k8s service ..maybe a helloworld

can someone help ?

**Comment by davidnuzik** [comment]
I created https://github.com/rancher/k3s/issues/985 specifically for documenting at least some examples for Traefik.

**Comment by davidnuzik** [comment]
Regarding docker snap this can be added to the incoming known issues section in the docs. https://github.com/rancher/k3s/issues/984

**Comment by davidnuzik** [comment]
Thank you all for the input! We really appreciate it. If there is anything I missed or there are other additions we really want to see in the documentation please enter any issues if necessary to track this.
