### ISSUE TITLE
Support for cert rotation

### ISSUE THREAD

**Issue by cjellick** [rancher/k3s#804]
Guidance for @ibuildthecloud:
- On startup, today if cert doesnt exist create. Add: if cert exists but its about to expire, replace it with a new one.
- Dont do cert rotation on the CA
- When a cert is request from a node agent. @erikwilson put this in place
- Have to be careful about knowing we generated vs user put it in there. Maybe we should drop support for this. Today is if the file is there, we do not override it.

**Comment by davidnuzik** [comment]
Ran into #875 however other tests succeed. I'm putting testing this further on hold until #875 gets fixed.

**Comment by davidnuzik** [comment]
Closing. Cert rotation tests have passed.
