### ISSUE TITLE
Resolv-conf flag

### ISSUE THREAD

**Issue by adi90x** [rancher/k3s#807]
Hello, 

Is it possible to have more information of what resolv-conf flag is expecting as input ?
Seems my coredns pod is not able to execute request send by the pods .
When I manually erase /etc/resolv.conf in the config map to 8.8.8.8 it works like a charm.

So I guess I have a setup issue somewhere on my hosts ?

Regards,

**Comment by galal-hussein** [comment]
@adi90x resolv-conf is a k3s agent argument that expects a file path to the resolv.conf file, this option will be passed to kubelet when it starts:
```

--resolv-conf string
--
  | Resolver configuration file used as the basis for the container DNS resolution configuration. (default "/etc/resolv.conf")

```

**Comment by adi90x** [comment]
Thanks a lot !
