### ISSUE TITLE
v0.8.1 HA mode, how agent conns to server's lanIPs when not in same lan.

### ISSUE THREAD

**Issue by huapox** [rancher/k3s#810]
Since v0.7.0 HA mode feature be added. the tunnel to the server's 6443 set by `K3S_URL=https://xxx:6443` be unusable. 

when agent not in same lan conns error and can't startup.

**v0.8.1**

```log
node_1  | time="2019-09-13T13:41:23.714868550Z" level=info msg="Starting k3s agent v0.8.1 (d116e74a)"
node_1  | time="2019-09-13T13:41:23.741142094Z" level=info msg="Running load balancer 127.0.0.1:44815 -> [192.168.0.105:6443 139.159.246.22:6443]"
node_1  | time="2019-09-13T13:41:32.132137173Z" level=info msg="Using containerd template at /var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl"
node_1  | time="2019-09-13T13:41:32.132831982Z" level=info msg="Logging containerd to /var/lib/rancher/k3s/agent/containerd/containerd.log"
node_1  | time="2019-09-13T13:41:32.133486305Z" level=info msg="Running containerd -c /var/lib/rancher/k3s/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state /run/k3s/containerd --root /var/lib/rancher/k3s/agent/containerd"
node_1  | time="2019-09-13T13:41:32.134026077Z" level=info msg="Waiting for containerd startup: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial unix /run/k3s/containerd/containerd.sock: connect: no such file or directory\""
node_1  | time="2019-09-13T13:41:33.139295470Z" level=info msg="module br_netfilter was already loaded"
node_1  | time="2019-09-13T13:41:33.139863988Z" level=info msg="module overlay was already loaded"
node_1  | time="2019-09-13T13:41:33.139935462Z" level=info msg="module nf_conntrack was already loaded"
node_1  | time="2019-09-13T13:41:33.321952615Z" level=info msg="Connecting to proxy" url="wss://192.168.0.105:6443/v1-k3s/connect"
	node_1  | time="2019-09-13T13:41:36.378084907Z" level=error msg="Failed to connect to proxy" error="dial tcp 192.168.0.105:6443: connect: no route to host"
	node_1  | time="2019-09-13T13:41:36.378213058Z" level=error msg="Remotedialer proxy error" error="dial tcp 192.168.0.105:6443: connect: no route to host"
	node_1  | time="2019-09-13T13:41:41.378720176Z" level=info msg="Connecting to proxy" url="wss://192.168.0.105:6443/v1-k3s/connect"
	node_1  | time="2019-09-13T13:41:44.442093320Z" level=error msg="Failed to connect to proxy" error="dial tcp 192.168.0.105:6443: connect: no route to host"
	node_1  | time="2019-09-13T13:41:44.442189467Z" level=error msg="Remotedialer proxy error" error="dial tcp 192.168.0.105:6443: connect: no route to host"
```

`192.168.0.105` is the server's lan ip. (agent not in the same lan)

**Comment by huapox** [comment]
**v0.7.0** 

the tunnel seems still be used by agent. We can use the server's publicIP just chang the code back. ref #727
https://github.com/rancher/k3s/releases/tag/v0.7.0
> This release brings limited experimental HA support,
> Have a load balancer setup for the master nodes k8s api (port 6443). (requirement of setting up an external load balancer)
> HA aware agents should be configured to connect to the master nodes through the load balancer, agents will then watch the kubernetes endpoints and setup a reverse tunnel to each master node

**Comment by huapox** [comment]
And when I use v081 with kilo:
- 1. change k3s's code to use publicIP for first conn when cluster agent startup `K3S_URL=https://xxx:6443`. ref #727 
- 2. install kilo, to keep the agent use it's LB to conmmunicate the server's lanIP.

Others works fine. but when i use agola, when it communicate with k3s got this err.

```
error dialing backend: failed to find Session for client ali-vm1
```

`ali-vm1` is my agent. (diff lan to the server node)

ref: agola-io/agola#114

**Comment by erikwilson** [comment]
Related #881

**Comment by felix33333** [comment]
ran into the same issue.  This is how I solved it 

create cluster master node:
```
export K3S_NODE_NAME=${HOSTNAME//_/-}
export K3S_EXTERNAL_IP=xx.xx.xx.xx
export INSTALL_K3S_EXEC="--docker --write-kubeconfig ~/.kube/config --write-kubeconfig-mode 666 --tls-san $K3S_EXTERNAL_IP --kube-apiserver-arg service-node-port-range=1-65000 --kube-apiserver-arg advertise-address=$K3S_EXTERNAL_IP --kube-apiserver-arg external-hostname=$K3S_EXTERNAL_IP"
curl -sfL https://docs.rancher.cn/k3s/k3s-install.sh |  sh -

```

Get Token  on master node:

```
echo -e "export K3S_TOKEN=$(cat /var/lib/rancher/k3s/server/node-token)\nexport K3S_URL=https://$K3S_EXTERNAL_IP:6443\nexport INSTALL_K3S_EXEC=\"--docker --token \$K3S_TOKEN --server \$K3S_URL\""
```


join workers to the cluster:

```
export K3S_TOKEN=xxxx
export K3S_URL=https://xx.xx.xx.xx:6443
export INSTALL_K3S_EXEC="--docker --token $K3S_TOKEN --server $K3S_URL"
export K3S_NODE_NAME=${HOSTNAME//_/-}
curl -sfL https://docs.rancher.cn/k3s/k3s-install.sh | sh -

```

**Comment by huapox** [comment]
> **Try**
> 
> And when I use v081 with kilo:
> 
>     * Change k3s's code to use publicIP for first conn when cluster agent startup `K3S_URL=https://xxx:6443`. ref #727
> 
>     * Install kilo, to keep the agent use it's LB to conmmunicate the server's lanIP
> 

in this case, the lan-k3s problem resolved.

**Comment by huapox** [comment]
> **Result**
> 
> Others works fine. but when i use agola, when it communicate with k3s got this err:
> 
> ```
> error dialing backend: failed to find Session for client ali-vm1
> 
> vendor/github.com/rancher/remotedialer/session_manager.go  func getDialer:
> return nil, fmt.Errorf("failed to find Session for client %s", clientKey)
> ```
> 
> `ali-vm1` is my agent. (diff lan to the server node)
> 
> ref: [agola-io/agola#114](https://github.com/agola-io/agola/issues/114)

this was just another problem, agola will use k8s's api to trans big files, then master/node not in same lan, the limited bandwidth will cause agola got such as timeout err.

**Comment by huapox** [comment]
> ran into the same issue. This is how I solved it

thx, I'll try this with the new version.
