### ISSUE TITLE
Garbage collection

### ISSUE THREAD

**Issue by vitobotta** [rancher/k3s#813]
Hi, it's not a bug report but I had no idea of where to post this, so hopefully it's OK.

I am using a single node cluster for development, and after a while most of the disk is in use. Does K3s/kubelet do a garbage collection automatically for images/containers etc? If yes how does it work / how frequently? Thanks.

**Comment by huapox** [comment]
@vitobotta Yes, same with k8s, default 80%.

**Comment by vitobotta** [comment]
Hi @huapox , what do you mean by 80%? when disk usage reaches the 80%?

**Comment by MarkusTeufelberger** [comment]
https://kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection/#user-configuration

**Comment by vitobotta** [comment]
Thanks! So nothing to worry about. Good. :)
