### ISSUE TITLE
Universal K8S feature reduction and customization mechanism

### ISSUE THREAD

**Issue by jamesxia20181001** [rancher/k3s#82]
1. Will K3S's patch to K8S become a burden for long-term follow-up of the community's mainline version?
2. Will the patch modified by K3S for K8S be pushed into the K8S main line?
3. Is there a plan to promote the source-level reduction customization capability of the Linux-like kernel on the K8S mainline?

**Comment by ibuildthecloud** [comment]
All great questions.  If k3s becomes sufficiently popular will we start an effort to push the changes upstream.  In theory what we are doing here can be accomplished with golang build tags.  And then k3s will just become a specific set of build tags.

The burden of maintaining K3s patch is not huge. It's a fairly straight forward set of changes and in general at Rancher Labs we maintain lots of versions of k8s.  But ideally we would want this all to go upstream.  Right now I'd rather not bother with a SIG until we have more market validation that this is a good approach.  (So far the feedback has been extremely positive).
