### ISSUE TITLE
Longhorn 0.5 does not come up when deployed with rancher 2, ubuntu 18.04, k3s v0.8.1

### ISSUE THREAD

**Issue by orange888** [rancher/k3s#825]
**Describe the bug**

> W0920 10:39:34.315590     746 reflector.go:289] object-"kube-system"/"default-token-8kfq8": watch of ***v1.Secret ended with: too old resource version: 640 (661)**
> E0920 10:39:40.432606     746 pod_workers.go:190] Error syncing pod 40086688-db8a-11e9-ae1a-00163c941646 ("longhorn-manager-csqqm_longhorn-system(40086688-db8a-11e9-ae1a-00163c941646)"), skipping: failed to "StartContainer" for "longhorn-manager" with CrashLoopBackOff: "Back-off 1m20s restarting failed container=longhorn-manager pod=longhorn-manager-csqqm_longhorn-system(40086688-db8a-11e9-ae1a-00163c941646)"

**To Reproduce**
ubuntu 18.04, k3s v0.8.1, rancher 2

**Expected behavior**
Should it come up correctly?

**Screenshots**
[https://i.imgur.com/iD9zK1Q.png](https://i.imgur.com/iD9zK1Q.png
)

**Additional context**

**Comment by ShylajaDevadiga** [comment]
With rancher 2.3.2, k3s v0.8.1 and longhorn v0.5.0 longhorn was successfully deployed. 
![image](https://user-images.githubusercontent.com/56045581/68739892-c9fd1700-059e-11ea-9ba2-a4f4f59ff8b2.png)
```
root@ip-172-31-6-135:~# k3s -v
k3s version v0.8.1 (d116e74a)```

Unable to reproduce.  Please provide steps and re-open if you still see the issue. 
Thanks.
