### ISSUE TITLE
give a config for k8s image url 

### ISSUE THREAD

**Issue by sulegis** [rancher/k3s#83]
**Is your feature request related to a problem? Please describe.**

Location China, Can not run k3s server Success，in debug mode ，I find the reason is I can not pull docker image from https://k8s.gcr.io，detail like this：
--
E0228 11:28:13.907253   28057 kuberuntime_sandbox.go:58] CreatePodSandbox for pod "helm-install-traefik-8jflk_kube-system(cc24543e-3afd-11e9-a630-94de80af904c)" failed: rpc error: code = Unknown desc = failed to get sandbox image "k8s.gcr.io/pause:3.1": failed to pull image "k8s.gcr.io/pause:3.1": failed to resolve image "k8s.gcr.io/pause:3.1": no available registry endpoint: failed to do request: Head https://k8s.gcr.io/v2/pause/manifests/3.1: dial tcp: lookup k8s.gcr.io on 192.168.17.200:53: read udp 192.168.17.121:55619->192.168.17.200:53: i/o timeout
--

**Describe the solution you'd like**
It's not k3s's issue, But If k3s has a config to custom the k8s image url，I can change it to another docker registry to solve it。In these Google Forbidenned Country, open a k8s image url config will be very Useful.

**Comment by liaofeng2** [comment]
I have the same request too,thanks.

**Comment by wildcloud3** [comment]
me, too.

nowhere to find an option to change the images' repo.

**Comment by ibuildthecloud** [comment]
Unfortunately hard coded at the moment.  We will fix.  I know this is a major issue.

**Comment by jimangel** [comment]
@ibuildthecloud, somewhat of a hack, but can someone download the images and load them into containerd (via ./k3s crictl) before running `sudo k3s server`? If so, do you have a list of images that would be needed?

**Comment by Prodian0013** [comment]
> @ibuildthecloud, somewhat of a hack, but can someone download the images and load them into containerd (via ./k3s crictl) before running `sudo k3s server`? If so, do you have a list of images that would be needed?

From what I can tell (and tried), k3s (containerd) needs to be running for the crictl commands to work.  Also, if you modify the containerd config `/var/lib/rancher/k3s/agent/etc/containerd/config.toml` it will get overwritten when you start/restart k3s.  I tried to add an unsecure [registry](https://github.com/containerd/cri/blob/master/docs/registry.md) but the changes were overwritten.

**Comment by ntfs32** [comment]
@jimangel   I had try it and Look through source code,just found image `k8s.gcr.io/pause:3.1` need.
I want to edit the code add some arguments for agent start command, support custom image.

**Comment by ntfs32** [comment]
@Prodian0013   agent config change must update source code ... 
and crictl pull images but it not any arguments to tag it  gcr.io/xx:xx

**Comment by zergl** [comment]
before the problem solved, this trick may help you make the k3s server work well.

[131#comment-469652285](https://github.com/rancher/k3s/issues/131#issuecomment-469652285)

**Comment by lygstate** [comment]
When this gonna be fixed.

**Comment by erikwilson** [comment]
This may be fixed with the most recent airgap PR.

Related issues:
/issues/172
/issues/166

**Comment by xiongsongsong** [comment]
> Unfortunately hard coded at the moment. We will fix. I know this is a major issue.

Can I solve this problem in "v0.5.0-rc2"? Thanks！

**Comment by erikwilson** [comment]
Yep, this is configurable with #345 and will be available in the v0.5.0 release

**Comment by lianghuiyuan** [comment]
My k3s version is v0.5.0 (8c0116dd)
How to config?

**Comment by xiongsongsong** [comment]
@lianghuiyuan 

vi /etc/systemd/system/k3s.service
ExecStart=/usr/local/bin/k3s server **--pause-image=docker.io/xiongsongsong/pause:3.1**

**Comment by lianghuiyuan** [comment]
@xiongsongsong   
Thank you so much!
My k3s is runing in K3OS, there is no "/etc/systemd/system/k3s.service".
I am puzzled, because of the FGW I pulled an image with `k3s crictl pull anjia0532/pause:3.1` 
now the image named "docker/io/anjia0532/pause:3.1", 
![image](https://user-images.githubusercontent.com/8090998/58391532-dc26df80-8068-11e9-861b-0a9542ba9097.png)

 I run a pod, it still failed to get sandbox image "k8s.gcr.io/pause:3.1"
![image](https://user-images.githubusercontent.com/8090998/58391497-b7cb0300-8068-11e9-879b-d25995b5c90b.png)

I want to rename the image "docker/io/anjia0532/pause:3.1" to "k8s.gcr.io/pause:3.1"
but find no rename command in K3OS with containerd.

**Comment by xiongsongsong** [comment]
@lianghuiyuan Have you forgotten ```systemctl restart k3s```?
