### ISSUE TITLE
Add limited telemetry metrics with clear opt-out option

### ISSUE THREAD

**Issue by davidnuzik** [rancher/k3s#834]
**Summary:**
Adding some telemetry metrics is highly beneficial to us as it allows us to better understand the needs of the community so we can focus on what's important for k3s and its users.

We want to make sure that telemetry is minimal, anonymous, and very clear to the user when it is enabled and how to disable it. We want to ensure it is simple to opt-out and install/run k3s without any telemetry enabled.

**Requirements:**
- anonymity and limit metrics solely for the purpose of understanding approximate cluster count and other limited non-identifiable areas
- documentation clearly states what telemetry is, what information is collected, and how to opt out
- binary clearly states that telemetry is enabled and how to opt out
- curl bash install script clearly states that telemetry is enabled and how to opt out (what flag to use to install with it disabled)

Docs issue: https://github.com/rancher/docs/issues/1778

**Comment by ibuildthecloud** [comment]
Nope, not doing it.
