### ISSUE TITLE
K3S Version Reporting Incorrect

### ISSUE THREAD

**Issue by charles-d-burton** [rancher/k3s#839]
**Describe the bug**
When running kubectl get nodes the master node is not reporting the correct kubernetes version.

**To Reproduce**
Starting with a multi node cluster install the master version with  v1.14.5-k3s.1 using the following systemd file.
```bash
[Unit]
Description=Lightweight Kubernetes
Documentation=https://k3s.io
After=network-online.target

[Service]
Type=notify
EnvironmentFile=/etc/systemd/system/k3s.service.env
ExecStartPre=-/sbin/modprobe br_netfilter
ExecStartPre=-/sbin/modprobe overlay
ExecStart=/usr/local/bin/k3s \
    server --write-kubeconfig-mode 644 \
    --no-deploy traefik \
    --no-deploy=servicelb \
    --disable-agent \
KillMode=process
Delegate=yes
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
TimeoutStartSec=0
Restart=always

[Install]
WantedBy=multi-user.target
```

Then stop the master service using:
```bash
sudo systemctl stop k3s
```
Get the arm64 version from git releases for v0.9.1 and copy it over top of the 
```bash
/usr/local/bin/k3s
```

Then start the k3s service, it still reports 
`kube-master   NotReady   <none>   138d   v1.14.5-k3s.1`
Rather than ` v1.15.4-k3s.1`

**Expected behavior**
Correct reporting of the kubernetes version.

**Comment by charles-d-burton** [comment]
I just updated to 1.0 and this is still an issue.  Can someone point me in the general direction to look for the problem?  I'm more than willing to attempt a fix.

**Comment by erikwilson** [comment]
The `--disable-agent` flag should be avoided unless you are a developer and understand the repercussions. Please try removing that flag and restarting the k3s process.

**Comment by erikwilson** [comment]
Also, the line continuation on that service file will probably have unintended consequences for some versions of systemd, might be worth re-running the install script.

**Comment by charles-d-burton** [comment]
Is there a better configuration options to ensure the master doesn't join as a node that can have pods scheduled on it?  It's easy enough to cordon it off, but I'm using that with the intention of forcing the master to only be a master rather than a combined master/worker.

**Comment by erikwilson** [comment]
If you start the server with the no schedule taint I think that should have the desired effect, essentially cordoning it on start: 
`--kubelet-arg register-with-taints=kubernetes.io/unschedulable:NoSchedule`

**Comment by charles-d-burton** [comment]
I started the cluster with this:
```
--no-deploy=servicelb \
    --node-taint key=value:NoSchedule```

But it appears to not be working

```
kubectl get nodes -o json | jq '.items[].spec'
{
  "podCIDR": "10.42.1.0/24",
  "podCIDRs": [
    "10.42.1.0/24"
  ]
}
{
  "podCIDR": "10.42.0.0/24",
  "podCIDRs": [
    "10.42.0.0/24"
  ]
}
{
  "podCIDR": "10.42.3.0/24",
  "podCIDRs": [
    "10.42.3.0/24"
  ]
}
{
  "podCIDR": "10.42.2.0/24",
  "podCIDRs": [
    "10.42.2.0/24"
  ]
}```

This very much could be operator headspace and timing though.

**Comment by charles-d-burton** [comment]
Ah nm, it says right in the doc it can't be added later.
