### ISSUE TITLE
[Documentation] General improvements to navigation/structure and deployment examples

### ISSUE THREAD

**Issue by davidnuzik** [rancher/k3s#859]
We'd like to improve the existing documentation by making any improvements to the navigation/structure of the docs currently. There are ways we may be able to improve the flow/structure as you read through the docs.

We should also provide at least a couple of basic deployment examples (scenarios/configurations) such as what a typical HA set up may look like and how one may set this up such as with AWS or something.

Building from source:
Should this be in it's own small section somewhere? how important is this? This is typically used for running latest master builds i.e. for development. Does this belong in the GH README.md instead? I would think probably yes (and remove from our rancher.com docs).
- I've heard that if you just want to test latest (master) you should really just run make and that's all
- If we are going to mention the scripts to we need to mention any caveats / gotchas? It never worked for me with golang v1.13

**Comment by sandys** [comment]
i would like to upvote this 100x. 

production deployment examples on AWS would be super spectacular. If you can show an example with Spot instances, that will be the most brilliant thing ever. 

HA is not super important right now. We already realize and accept that k3s does not have HA right now

**Comment by davidnuzik** [comment]
HA is available currently but experimental (not documented) when we release some time in November we plan to have HA support so the guide will now describe this and at least provide an AWS example :)

**Comment by davidnuzik** [comment]
Side-note for me later: Want to get this addressed. It's hard to see underscores in one-line monotype on rancher docs site currently and this is an issue for K3S as we use underscores for env vars for curl script. This should be fixed before we release in November. https://github.com/rancher/docs/issues/1816
