### ISSUE TITLE
[Documentation] Explain local storage solution and provide example(s) (Longhorn, etc)

### ISSUE THREAD

**Issue by davidnuzik** [rancher/k3s#863]
At a bare-minimum we need to:
- Explain the local storage solution we now have in docs (there is no mention of storage currently at all so we need a section)
- Provide an example of using the local storage
- Provide an example of Longhorn set up

Ideally we should:
- Also provide at least one more example of another storage option besides local and longhorn (We might have to do this after GA).

**Comment by kingdevnl** [comment]
https://github.com/rancher/local-path-provisioner Has some good info on it.

**Comment by kingdevnl** [comment]
Maybe the docs could have a link to that?
