### ISSUE TITLE
with mysql db backend nodes do not get added in v0.9.1 and nodes are in NotReady state in v.0.10.0

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/k3s#874]
**Version:**
v0.9.1 and v0.10.0

**Describe the bug**
In the k3s HA env, second node is not added to the cluster in v0.9.1
and in v0.10.0, second node is added but nodes are in NotReady state.

**To Reproduce**
Configure mysql db as backend
Install node1 using credentials to connect to db.

`curl -sfL https://get.k3s.io | sh -s - server --storage-endpoint='mysql://user:password@tcp(hostname:3306)/dbname’ —bootstrap-save`

Install node2 using

`curl -sfL https://get.k3s.io | sh -s - server --storage-endpoint='mysql://user:password@tcp(hostname:3306)/dbname’`

Run 
```
kubectl get nodes
kubectk get pods -A -o wide
```

**Expected behavior**
Node should be added to cluster

**Actual behavior**
Node is not added or in Ready state

**Comment by davidnuzik** [comment]
To investigate. We should try to discover the cause of the issue and estimate work required to fix before we actually put any significant effort to fix.

**Comment by galal-hussein** [comment]
I wasn't able to reproduce the issue with v0.10.0:
```
# k3s kubectl get nodes
NAME               STATUS   ROLES    AGE    VERSION
ip-172-31-11-175   Ready    master   2m5s   v1.16.2-k3s.1
ip-172-31-11-236   Ready    master   5s     v1.16.2-k3s.1

```
I can see both masters in Ready state and connected to the database correctly:
```
mysql> select count(*) from kine;
+----------+
| count(*) |
+----------+
|      524 |
+----------+
1 row in set (0.01 sec)
```

**Comment by ShylajaDevadiga** [comment]
Related issue https://github.com/rancher/k3s/issues/948

**Comment by davidnuzik** [comment]
Looks like this is in v1.x - Backlog so sounds like this can wait until after kubecon.

**Comment by davidnuzik** [comment]
Need to verify and see if this is still an issue.

**Comment by rancher-max** [comment]
I don't see this anymore in current state. **Not an issue anymore.** Left cluster overnight to ensure wait was long enough and see the cluster running correctly:
```
$ k3s kubectl get nodes
NAME               STATUS   ROLES    AGE   VERSION
ip-172-31-6-26     Ready    master   15h   v1.18.6+k3s1
ip-172-31-12-101   Ready    master   15h   v1.18.6+k3s1

$ sudo k3s kubectl get pods -A
NAMESPACE     NAME                                     READY   STATUS      RESTARTS   AGE
kube-system   local-path-provisioner-6d59f47c7-zrbjr   1/1     Running     0          15h
kube-system   metrics-server-7566d596c8-f9hxc          1/1     Running     0          15h
kube-system   helm-install-traefik-t84h6               0/1     Completed   1          15h
kube-system   svclb-traefik-dln49                      2/2     Running     0          15h
kube-system   coredns-8655855d6-68rhm                  1/1     Running     0          15h
kube-system   traefik-758cd5fc85-l6cjf                 1/1     Running     0          15h
kube-system   svclb-traefik-5sjtc                      2/2     Running     0          15h

mysql> show tables;
+---------------+
| Tables_in_k3s |
+---------------+
| kine          |
+---------------+

mysql> select count(*) from kine;
+----------+
| count(*) |
+----------+
|     2690 |
+----------+
```
