### ISSUE TITLE
Cert Rotation not working correctly for kubelet

### ISSUE THREAD

**Issue by davidnuzik** [rancher/k3s#875]
**Version:**
v0.10.0-alpha1

**Describe the bug**
When certs are rotated the agent certs don't seem to update. It looks like the kubelet cert is not updated.

**To Reproduce**
- Run the test binary with 10-min cert expiry (in-house QA only). `k3s server` (this runs the server and agent on the same machine)
- Wait 10 mins until the certs are expired
- Stop the k3s server
- Put the latest alpha1 binary on the system, use it to bring `k3s server` up again

**Expected behavior**
We had expected the agent certs on the machine to be updated.

**Actual behavior**
The agent certs didn't appear to be updated. It looks like the kubelet cert is expired.
k3s server logs complain that one or more certs are expired or not trusted.

**Additional context**
Related: rancher/k3s#804

**Comment by ShylajaDevadiga** [comment]
This issue is fixed with v0.10.0.
