### ISSUE TITLE
Roles for worker nodes are not updated when worker nodes are upgraded from v.0.9.1 to v.0.10.0

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/k3s#878]
Version:
v0.9.1 and v0.10.0 HA Cluster env, using postgres db

Describe the bug
Role of the worker node  does not change to <none> when a worker is upgraded from v0.9.1 to v0.10.0-alpha version

To Reproduce
Create two master with v0.10.0
Join a worker with v0.10.0
run kubectl get nodes
Join another worker with v0.9.1 and upgrade it to v0.10.0
run kubectl get nodes

Expected behavior
All worker nodes with v0.10.0 should be having Role <none>

Actual behavior
Worker nodes that are upgraded from v0.9.1 to v0.10.0 are having role as "worker"
```
Shylajas-MBP:~ shylajadevadiga$ k get node
NAME              STATUS   ROLES    AGE    VERSION
ip-172-31-6-96    Ready    <none>   48m    v1.16.0-k3s.1
ip-172-31-15-68   Ready    <none>   135m   v1.16.0-k3s.1
ip-172-31-8-41    Ready    worker   38m    v1.16.0-k3s.1
```

**Comment by zimme** [comment]
Seeing this too when joining a 0.10.1 node.

**Comment by erikwilson** [comment]
The default is to have no roles on purpose. https://github.com/kubernetes/kubernetes/issues/55232

Is it causing an issue for you?

**Comment by billimek** [comment]
This is interesting, previously k3s-provisioned workers has the `workers` role and the k3s master had (or has?) the `master` role.

When I was researching this, I saw references in some of the rancher code that seems to specifically look for nodes with the `worker` role defined.  I know k3s isn't really related to rancher right now but not sure if there are possible downstream implications by removing? the worker role assignment from k3s-provisioned nodes.

It is, of course, easy to manually define the role post-provisioning but it seems like different behavior with the recent release or two of k3s.

**Comment by davidnuzik** [comment]
Should not cause any k3s issues or issues with Rancher. We recommend removing the role if you wish.
Unless this actually causes any issues we do not have any plans to change the behavior.
