### ISSUE TITLE
k3s cluster is not injecting sidecars properly to rio services.

### ISSUE THREAD

**Issue by izaac** [rancher/k3s#879]
**Version:**

k3s version v0.9.1 (755bd1c6)

Master install:
`curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable-agent" sh -`

Agent Install: 
`curl -sfL https://get.k3s.io | K3S_URL=https://<Master External IP Here>:6443 K3S_TOKEN="<Master Token Here>" sh -`

**Describe the bug**
While using k3s to deploy a cluster with one master and one agent to use rio with it to deploy services we've notice the services had only one pod, but usually the sidecar injector created one for proxy.

**To Reproduce**
 - Install Master and Agent in two different Linodes (Ubuntu 18.04).
 - Install Rio and deploy a services like `rio run -p 80 -n not-default/test1 nginx`
   - `curl -sfL https://get.rio.io | INSTALL_RIO_VERSION=v0.5.0 sh -` inside the master node.
 - At some point the deployed service would only report one pod, but with rio a sidecar is expected to also deploy with the service ending up with 2 pods. `k get pod -n not-default`

**Expected behavior**
The service deployed by rio to report 2 pods for the service, one pod for the service and one the injected sidecar.

**Actual behavior**
Just one pod is deployed in this k3s setup for the deployed service.

**Additional context**
@StrongMonkey also did some investigation and found out that the cluster `api-server` was not communicating properly with regular k8s services.
`Post https://linkerd-proxy-injector.linkerd.svc:443/?timeout=30s: dial tcp 10.43.234.164:443: i/o timeout`
Linodes had only external IP assigned.

**Comment by erikwilson** [comment]
The `--disable-agent` flag should not be used.

**Comment by izaac** [comment]
@erikwilson Ok I don't see that flag in the latest documentation anymore implying what you've just mentioned. I think we can close this @davidnuzi
