### ISSUE TITLE
website k3s.io, the Github links refer to submariner

### ISSUE THREAD

**Issue by curx** [rancher/k3s#880]
On the website https://k3s.io, the github link refer to https://github.com/submariner-io/submariner
not to k3s repo. Is there a repo for the website also?

Btw. nice yellow theme :+1:

**Comment by warmchang** [comment]
And nice yellow logo. :smiley:

**Comment by erikwilson** [comment]
Thanks for reporting @curx, the link has been updated, will see what I can do about getting the tagline updated @warmchang
