### ISSUE TITLE
Remove stale link for air gap single node page with config private registry

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/k3s#889]
Below page returns a 404 as it is moved to a different location. I bumped upon this page while looking for private registry docs online using keywords "rancher private registry"

https://rancher.com/docs/rancher/v2.x/en/installation/air-gap-single-node/config-rancher-for-private-reg/

Moved to
https://rancher.com/docs/rancher/v2.x/en/installation/air-gap/install-rancher/

**Comment by erikwilson** [comment]
Those are docs for Rancher, not k3s. Feel free to put a PR in on the docs site to fix the link.
