### ISSUE TITLE
[CLI] hide --disable-agent flag

### ISSUE THREAD

**Issue by davidnuzik** [rancher/k3s#890]
**Version:**
v0.10.0-alpha1

**Describe the bug**
Confusion around `--disable-agent` flag

The usage of --disable-agent should be for testing/developer purposes only. This flag is confusing, if you want to create master nodes and use the --disable-agent flag the node will not have the kubelet running so you can't list the master nodes.

This causes a problem where we have "hidden" masters (cannot get with `kubectl get nodes` for example) and so we can't manage the master nodes.

Let's remove the `--disable-agent` flag from the CLI (it can stay there but be hidden). Master nodes should always have the agent running on them for typical usage.

I will create a separate docs issue to remove this from rancher.com docs and we can migrate this to developer docs for example.
Docs issue: https://github.com/rancher/k3s/issues/891

**Comment by CamelCaseNotation** [comment]
I am using this flag. Will it be hidden or non functional?

**Comment by davidnuzik** [comment]
The plan is to simply make it hidden due to it causing confusion/problems for much of the community and QA. It will still function.
