### ISSUE TITLE
Update k3s.io webpage with the actual amount of resources being used while running the k3s binary with v0.9.1 and above

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/k3s#893]
**Version:**
v0.9.1 and v0.10.0-alpha1

**Describe the bug**
With v0.9.1, k3s binary is 43.5 MB and with v0.10.0-alpha1 it is 54.6 MB.
Memory used while running the k3s server is 534MB with v0.9.1
```
root@ip-172-31-6-192:~# free -m
              total        used        free      shared  buff/cache   available
Mem:           3943         534        2449           1         959        3247
Swap:             0           0           0
```

**To Reproduce**
Run k3s server.
`k3s server`

**Expected behavior**
As in the webpage, binary size should be 40MB and does not  consume more than 512MB of memory

**Actual behavior**
Binary size exceeds 40MB and consumes at least 534 MB of memory.

***Additional Information***
```
root@ip-172-31-6-192:~# k3s kubectl get pods -A
NAMESPACE     NAME                         READY   STATUS      RESTARTS   AGE
kube-system   coredns-66f496764-9pmwk      1/1     Running     0          8m55s
kube-system   helm-install-traefik-wd7gf   0/1     Completed   0          8m55s
kube-system   svclb-traefik-nqsxf          3/3     Running     0          8m24s
kube-system   traefik-d869575c8-bfppw      1/1     Running     0          8m24s

root@ip-172-31-6-192:~# k3s kubectl get node
NAME              STATUS   ROLES    AGE     VERSION
ip-172-31-6-192   Ready    master   9m26s   v1.15.4-k3s.1
root@ip-172-31-6-192:~#
```

**Comment by davidnuzik** [comment]
The amount of memory used will vary. I have tested on Raspi3 for example with little Ram and it would use much less. Depending on what deployments are running on it more memory is required. 512MB is the minimum and I was able to run a few nginx deployments on a 1 node raspi 3.
