### ISSUE TITLE
Role label is not being set on all master nodes in HA setups

### ISSUE THREAD

**Issue by galal-hussein** [rancher/k3s#895]
Thanks for helping us to improve k3s! We welcome all bug reports. Please fill out each area of the template so we can better help you.  ***You can delete this message portion of the bug report.***

**Version:**
v0.10.0-alpha1

**Describe the bug**
role label is not being set on master nodes in HA setups, after debugging it looks likes controller informers are only started on the leader nodes, so cache is not working in the setMasterRoleLabel() function

**To Reproduce**
Start k3s in HA mode with multiple masters

**Expected behavior**
All master nodes should have role "master"

**Actual behavior**
Only the first node gets the role master

**Comment by ShylajaDevadiga** [comment]
Verified using v0.10.0-rc1
