### ISSUE TITLE
where to find master node password

### ISSUE THREAD

**Issue by jandriotty** [rancher/k3s#896]
Hello, I was updating the node password of a worker node in /var/lib/rancher/k3s/server/cred/node-passwd and I accidentally overwrote the password for the master node instead of the worker I was trying to change, and now The cluster wont create any pods when I make a deployment. Is there another place on the server or agents where the server's node password is stored? I tried using the password found in /var/lib/rancher/k3s/server/cred/passwd, but the cluster doesn't seem to be working with that.  

If I can't find the old password, can I reset or change something on agents to match the server's new password? I can't find anywhere on the agents that has the server node password, but I could be looking in the wrong place. 
Thanks

**Comment by tdorsey** [comment]
Not an expert, but to my knowledge that's the only location for the master credential. 

You could try setting the master credential to a known value, then delete /var/lib/rancher/k3s/agent/node-password.txt, and re registering your agents against the new master password, but I have only ever done that when agents can't reregister, not when the master is having issues, so I can't say if there would be side effects or not.

Only other option I know of is to dump your cluster config to json, recreate the master, and reimport

**Comment by davidnuzik** [comment]
Closing; if the information that @tdorsey provided is not sufficient let us know.
