### ISSUE TITLE
Remove iptables entries after executing uninstall on any node on the cluster

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/k3s#909]
**Version:**
v0.9.1 or v010.0

**Describe the bug**
iptables entries still persist after uninstall

**To Reproduce**
Run the uninstall script.
```
k3s-uninstall.sh
k3s-agent-uninstall.sh 
```

**Expected behavior**
All iptables chains are removed.

**Actual behavior**
Iptables chain still persist.

**Comment by davidnuzik** [comment]
Closing in favor of original issue (this is a duplicate)
https://github.com/rancher/k3s/issues/774
