### ISSUE TITLE
crictl will be not working when reboot the master node 

### ISSUE THREAD

**Issue by gssxd** [rancher/k3s#910]
**Version:**
# k3s -v
k3s version v0.6.1 (7ffe802a)

**Describe the bug**
the crictl command does works well when I installed k3s. However, when I reboot the master node,  it will be not working any more.
# crictl ps
FATA[2019-10-17T10:04:55.211741427Z] failed to connect: failed to connect: context deadline exceeded

**Comment by gssxd** [comment]
@ erikwilson 
Basically I used the script that got from the website 'https://get.k3s.io' to install the k3s. This is a fresh system for my k3s testing, there is no system crictl been installed.
 # ll /usr/local/bin/
total 40896
lrwxrwxrwx 1 root root        3 Sep  2 03:24 crictl -> k3s
-rwxr-xr-x 1 root root 41868896 Sep  2 03:23 k3s
-rwxr-xr-x 1 root root     1096 Sep  2 03:24 k3s-killall.sh
-rwxr-xr-x 1 root root      882 Sep  2 03:24 k3s-uninstall.sh
lrwxrwxrwx 1 root root        3 Sep  2 03:24 kubectl -> k3s
[root@k3s-master ~]# k3s crictl ps
FATA[2019-10-18T01:54:59.275751022Z] failed to connect: failed to connect: context deadline exceeded

On master side:
# ps axf |grep k3s
 1287 ?        Ss     0:01 avahi-daemon: running [k3s-master.local]
27144 pts/0    S+     0:00  |       \_ grep --color=auto k3s
26716 ?        Ssl   13:21 /usr/local/bin/k3s server --disable-agent

On node side:
# ps axf |grep k3s
 1326 ?        Ss     0:01 avahi-daemon: running [k3s-node1.local]
31663 pts/0    S+     0:00  |       \_ grep --color=auto k3s
 2611 ?        Sl     1:06 containerd-shim -namespace k8s.io -workdir /var/lib/rancher/k3s/agent/containerd/io.containerd.runtime.v1.linux/k8s.io/4808c5a5875f9f4c225c4d2e5ccd421364788c8248587526ca395939fa4ec314 -address /run/k3s/containerd/containerd.sock -containerd-binary /var/lib/rancher/k3s/data/1f8f9ad9556f55492e3461a731703cb5679a41e0ec882d7f94a9b460a2350b03/bin/containerd
 2755 ?        Sl     1:04 containerd-shim -namespace k8s.io -workdir /var/lib/rancher/k3s/agent/containerd/io.containerd.runtime.v1.linux/k8s.io/60417ce6784591100177df14de978bbdc981409ffd036244505c463fa0d24c39 -address /run/k3s/containerd/containerd.sock -containerd-binary /var/lib/rancher/k3s/data/1f8f9ad9556f55492e3461a731703cb5679a41e0ec882d7f94a9b460a2350b03/bin/containerd
 2800 ?        Sl     1:02 containerd-shim -namespace k8s.io -workdir /var/lib/rancher/k3s/agent/containerd/io.containerd.runtime.v1.linux/k8s.io/809514bd707efa8d6de5d5c556d2be854ff5371ac2f63887803a58cbcbff9442 -address /run/k3s/containerd/containerd.sock -containerd-binary /var/lib/rancher/k3s/data/1f8f9ad9556f55492e3461a731703cb5679a41e0ec882d7f94a9b460a2350b03/bin/containerd
 2850 ?        Sl     1:01 containerd-shim -namespace k8s.io -workdir /var/lib/rancher/k3s/agent/containerd/io.containerd.runtime.v1.linux/k8s.io/be6500f96cf4623e93579ba2fdd5949161ba43083a9b7fa885de7a4128dfb55f -address /run/k3s/containerd/containerd.sock -containerd-binary /var/lib/rancher/k3s/data/1f8f9ad9556f55492e3461a731703cb5679a41e0ec882d7f94a9b460a2350b03/bin/containerd
 2888 ?        Sl     1:06 containerd-shim -namespace k8s.io -workdir /var/lib/rancher/k3s/agent/containerd/io.containerd.runtime.v1.linux/k8s.io/73cf467e148ca7b34489dfae80cc494ae0c009382c72330e8a059cf9b1797752 -address /run/k3s/containerd/containerd.sock -containerd-binary /var/lib/rancher/k3s/data/1f8f9ad9556f55492e3461a731703cb5679a41e0ec882d7f94a9b460a2350b03/bin/containerd
 2925 ?        Sl     1:04 containerd-shim -namespace k8s.io -workdir /var/lib/rancher/k3s/agent/containerd/io.containerd.runtime.v1.linux/k8s.io/2fb3b905ac80e28dc3c3cf52f33455dc0125dd825c6b16dc00de42c1dbc854d2 -address /run/k3s/containerd/containerd.sock -containerd-binary /var/lib/rancher/k3s/data/1f8f9ad9556f55492e3461a731703cb5679a41e0ec882d7f94a9b460a2350b03/bin/containerd
 2947 ?        Sl     1:01 containerd-shim -namespace k8s.io -workdir /var/lib/rancher/k3s/agent/containerd/io.containerd.runtime.v1.linux/k8s.io/2c1eed0445f2968717b4d0312f81a61b865cbe534880d87fc920a3a9418f15fb -address /run/k3s/containerd/containerd.sock -containerd-binary /var/lib/rancher/k3s/data/1f8f9ad9556f55492e3461a731703cb5679a41e0ec882d7f94a9b460a2350b03/bin/containerd
 3087 ?        Sl     1:09 containerd-shim -namespace k8s.io -workdir /var/lib/rancher/k3s/agent/containerd/io.containerd.runtime.v1.linux/k8s.io/c7ce81438e48b65958319f8f0989f025f192135e6cc7894a528d90686056041f -address /run/k3s/containerd/containerd.sock -containerd-binary /var/lib/rancher/k3s/data/1f8f9ad9556f55492e3461a731703cb5679a41e0ec882d7f94a9b460a2350b03/bin/containerd
 3204 ?        Sl     1:10 containerd-shim -namespace k8s.io -workdir /var/lib/rancher/k3s/agent/containerd/io.containerd.runtime.v1.linux/k8s.io/63d971ad630ce633f527e21acdeb6ac488cd103fdb645bae33f2280f93e61e82 -address /run/k3s/containerd/containerd.sock -containerd-binary /var/lib/rancher/k3s/data/1f8f9ad9556f55492e3461a731703cb5679a41e0ec882d7f94a9b460a2350b03/bin/containerd
 2444 ?        Ssl   13:17 /usr/local/bin/k3s agent
 2463 ?        Sl     3:31  \_ containerd -c /var/lib/rancher/k3s/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state /run/k3s/containerd --root /var/lib/rancher/k3s/agent/containerd
 3055 ?        Sl     0:01      \_ containerd-shim -namespace k8s.io -workdir /var/lib/rancher/k3s/agent/containerd/io.containerd.runtime.v1.linux/k8s.io/9c69cf1a597325d2cd99b87ca7c4206c877aef93dbeb13b3a6d598f96fd60885 -address /run/k3s/containerd/containerd.sock -containerd-binary /var/lib/rancher/k3s/data/1f8f9ad9556f55492e3461a731703cb5679a41e0ec882d7f94a9b460a2350b03/bin/containerd
 3230 ?        Sl     0:01      \_ containerd-shim -namespace k8s.io -workdir /var/lib/rancher/k3s/agent/containerd/io.containerd.runtime.v1.linux/k8s.io/30a5e97bd32abba2f49b9c39fb65ecbc5dd2e5258bffa8f1f33af266e0a07ece -address /run/k3s/containerd/containerd.sock -containerd-binary /var/lib/rancher/k3s/data/1f8f9ad9556f55492e3461a731703cb5679a41e0ec882d7f94a9b460a2350b03/bin/containerd
[root@k3s-node1 ~]#

**Comment by erikwilson** [comment]
Any helpful errors in the containerd logs (/var/lib/rancher/k3s/agent/containerd/containerd.log)? Or possibly /var/log/syslog? Might be worth upgrading also.

Using the `--disable-agent` flag is discouraged, it looks like you are running those processes on different machines and expecting containerd to be running on the server, which would not happen when using `--disable-agent`. The agent needs to be running for containerd to be running, and should be running on the master node.

**Comment by gssxd** [comment]
@erikwilson Removed the --disable-agent flag, it works well. Thanks.
