### ISSUE TITLE
Offline installation: k3s agent failed to get CA certs

### ISSUE THREAD

**Issue by ntx-ben** [rancher/k3s#912]
**Version:**
v0.9.0

**Describe the bug**
Using a custom ISO of RancherOS to perform an offline installation. This ISO comes with k3s Docker image bundled. To "simulate" an offline environment, I simply set the nameservers to bogus IPs in the cloud-config before installing to disk. In my cloud-config file, I also created 2 services: a k3s-server and a k3s-agent (see below).

The goal of this exercise is to have an ISO that contains everything (Docker images, k8s manifests in /var/lib/rancher/k3s/server/manifests, etc.) to be able to do an offline installation of RancherOS with k3s.

Upon rebooting, I notice the k3s-server and k3s-agent containers are running, however when inspecting the logs for the k3s-agent, it shows the following:

`
time="2019-10-17T11:58:24.424886100Z" level=info msg="Waiting for /var/lib/rancher/k3s/server/node-token to be available\n"
time="2019-10-17T11:58:26.425733300Z" level=info msg="Waiting for /var/lib/rancher/k3s/server/node-token to be available\n"
time="2019-10-17T11:58:28.426112200Z" level=info msg="Waiting for /var/lib/rancher/k3s/server/node-token to be available\n"
time="2019-10-17T11:58:30.426781300Z" level=info msg="Starting k3s agent v0.9.0 (65d87648)"
time="2019-10-17T11:58:30.433693600Z" level=info msg="Running load balancer 127.0.0.1:37407 -> [localhost:6443]"
time="2019-10-17T11:58:50.438475600Z" level=error msg="failed to get CA certs at https://127.0.0.1:37407/cacerts: Get https://127.0.0.1:37407/cacerts: read tcp 127.0.0.1:45212->127.0.0.1:37407: read: connection reset by peer"
`

Doing the same procedure with valid nameservers (i.e. 1.1.1.1/1.0.0.1) results in the k3s-agent registering successfully to the k3s-server.

**Expected behavior**
k3s agent able to successfully fetch the server's CA certs.

**Actual behavior**
k3s agent fails to successfully fetch the server's CA certs.

**Additional context**
Relevant RancherOS cloud-config.yml section:

` 
services:
    k3s-server:
      image: rancher/k3s:v0.9.0
      command: server --disable-agent --no-deploy traefik
      environment:
      - K3S_KUBECONFIG_MODE=644
      net: host
      volumes:
        - /etc/rancher/k3s:/etc/rancher/k3s
        - /var/lib/rancher/k3s:/var/lib/rancher/k3s:rshared
     
    k3s-agent:
      image: rancher/k3s:v0.9.0
      command: agent --docker -s https://localhost:6443 --token-file /var/lib/rancher/k3s/server/node-token
      volumes:
        - /var/lib/rancher/k3s:/var/lib/rancher/k3s:rshared
        - /var/lib/docker:/var/lib/docker:rshared
        - /var/run/docker.sock:/var/run/docker.sock:ro
      tmpfs:
        - /var/run
        - /run
      privileged: true
      net: host
      pid: host
      ipc: host
`

**Comment by erikwilson** [comment]
Instead of running a server and agent separately is probably easiest to run both (omit the `--disable-agent` flag on server).
Instead of `localhost` maybe `127.0.0.1` would work better.

**Comment by erikwilson** [comment]
The source of the problem is probably the Golang DNS resolver ignoring /etc/hosts entry for localhost, also see https://github.com/golang/go/issues/22846. It is something I would like to fix but maybe not in scope at the moment.

**Comment by ntx-ben** [comment]
Ok so removing the agent and using only one instance of k3s for both server and agent got me further. Now the issue is:

E1017 17:06:29.677990    1102 pod_workers.go:190] Error syncing pod 8bc6e2cb-f19d-4699-add2-a82a99a2e491 ("kubernetes-dashboard-58b44bc8f5-wm4ql_kubernetes-dashboard(8bc6e2cb-f19d-4699-add2-a82a99a2e491)"), skipping: failed to "CreatePodSandbox" for "kubernetes-dashboard-58b44bc8f5-wm4ql_kubernetes-dashboard(8bc6e2cb-f19d-4699-add2-a82a99a2e491)" with CreatePodSandboxError: "CreatePodSandbox for pod \"kubernetes-dashboard-58b44bc8f5-wm4ql_kubernetes-dashboard(8bc6e2cb-f19d-4699-add2-a82a99a2e491)\" failed: rpc error: code = Unknown desc = failed to get sandbox image \"k8s.gcr.io/pause:3.1\": **failed to pull image \"k8s.gcr.io/pause:3.1\"**: failed to resolve image \"k8s.gcr.io/pause:3.1\": no available registry endpoint: failed to do request: Head https://k8s.gcr.io/v2/pause/manifests/3.1: dial tcp: lookup k8s.gcr.io on 9.8.7.6:53: read udp 192.168.83.58:41303->9.8.7.6:53: i/o timeout"

But the Docker image **k8s.gcr.io/pause:3.1** is already present in user Docker. Is there a way to set the imagePullPolicy "globally" to _IfNotPresent_?

**Comment by erikwilson** [comment]
There is probably some confusion on how images are loaded, the instructions at https://rancher.com/docs/k3s/latest/en/running/#air-gap-support work for containerd that we ship, but when using the `--docker` flag will need to use docker specific commands like `docker tag` or `docker load`.

**Comment by ntx-ben** [comment]
For anyone stumbling in here and trying to accomplish the same thing, the resolve was to use a separate k3s instance for server and agent, and to use 127.0.0.1 instead of localhost.

Bundling the Docker images as part of RancherOS works as well (instead of the image loading of k3s which uses containerd).

**Comment by theAkito** [comment]
Has this not been fixed, yet? Is there at least a valid workaround?
For our setup it is extremely crucial to have one agent and one server instance, separated from each other. Using both on the same instance would break the whole point of using k3s in the first place, in our situation.
