### ISSUE TITLE
Website issue: Google's Featured Snippet link when searching 'install k3s' returns a 404

### ISSUE THREAD

**Issue by boemska-nik** [rancher/k3s#920]
Not sure if this is the right place so please feel free to remove/close, but this was easiest.

`https://rancher.com/docs/k3s/latest/en/running/` returns a 404 from rancher.com, and is the featured result when googling 'install k3s'.

![image](https://user-images.githubusercontent.com/11962123/67114318-8dbedc80-f1d3-11e9-911f-ffedb6045410.png)

**Comment by catherineluse** [comment]
This was corrected by https://github.com/rancher/docs/pull/1906

**Comment by erikwilson** [comment]
Thanks for reporting @boemska-nik and thanks for fixing @catherineluse!
