### ISSUE TITLE
`make package` fails

### ISSUE THREAD

**Issue by AkihiroSuda** [rancher/k3s#922]
**Version:**
v0.10.0-rc2

**Describe the bug**
`make package` fails

**To Reproduce**
`make package`

**Expected behavior**
It should succeed

**Actual behavior**
```console
$ make pacakge
...
+ mkdir -p dist/artifacts
+ tar cvzf ./build/out/data.tar.gz --exclude ./bin/hyperkube ./bin ./etc
./bin/
./bin/containerd-shim-runc-v2
./bin/ctr
./bin/k3s-server
./bin/portmap
./bin/crictl
./bin/containerd-shim
./bin/bridge
./bin/cni
./bin/host-local
./bin/k3s-agent
./bin/flannel
./bin/kubectl
./bin/runc
./bin/loopback
./bin/containerd
tar: ./etc: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
FATA[0478] exit status 2                                
make: *** [Makefile:11: package] Error 1
```

**Comment by warmchang** [comment]
@AkihiroSuda  just run "_make_" to build the full release binary.

If you want to build locally (not in the docker container), you can run the following command. :smiley: 

> ./scripts/download && ./scripts/build && ./scripts/package-cli;

**Comment by AkihiroSuda** [comment]
thanks
