### ISSUE TITLE
Upgrade to v0.10.0-rc2 to use default kubelet directory duplicates pod entry in old as well as in new directories.

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/k3s#929]
**Version:**
Upgrade from v0.9.1 to v0.10.0-rc2

**Describe the bug**
1. Upgrade to v0.10.0-rc2 has all pod entries from /var/lib/rancher/k3s/agent/kubelet/pods/ copied onto /var/lib/kubelet except helm and the pods are restarted.
2. Delete a pod removes in the new default dir and not from the old dir.
3. Helm pod is present only in old dir and not copied to default dir as job is in Completed state.

**To Reproduce**
1. Install v0.9.1
`curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v0.9.1 sh -s - server`
Create a deployment.
Verify the entries in /var/lib/rancher/k3s/agent/kubelet/pods/
 Upgrade to rc2
`curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v0.10.0-rc2 sh -s - server`
Verify the pods status
`kubectl get pods -A`
Verify the entries in /var/lib/kubelet
Verify the entries in /var/lib/rancher/k3s/agent/kubelet/pods/
Scale up the pods
Verify the new entries in /var/lib/kubelet
As expected the new pods are not in /var/lib/rancher/k3s/agent/kubelet/pods/
 Scale down the replicas to 0.
Pod entries are removed from new default dir and continues to appear in old dir.
5. Helm is not copied to new dir
`ls /var/lib/kubelet/pods/container/` |grep helm

**Expected behavior**
Pods created after upgrade should be in new default dir
Pods created before upgrade continue to remain in old dir
All pods are in Running state
Deleting a pod removes it from respective dir

**Actual behavior**
Pods created after upgrade should be in new default dir
Pods created before upgrade continue to remain in old dir as well as in new dir
All pods are in running state.
Deleting a pod removes it from new dir only

*** Additional info ***
```
ls -ltr /var/lib/rancher/k3s/agent/kubelet/pods
total 28
drwxr-x--- 5 root root 4096 Oct 21 18:19 ccd0be75-173e-4df4-aa1e-57979ca63a93
drwxr-x--- 5 root root 4096 Oct 21 18:19 a20c6b3f-2950-4ab9-89bb-6cf08e22c1f6
drwxr-x--- 5 root root 4096 Oct 21 18:19 946d4695-d059-470c-a074-4089bece0944
drwxr-x--- 5 root root 4096 Oct 21 18:19 0456318c-2e28-47f4-95e2-ccdc7b712b8b
drwxr-x--- 5 root root 4096 Oct 21 18:19 7e056156-0b88-442d-a841-1df67def1ae6
drwxr-x--- 5 root root 4096 Oct 21 18:20 75ab116e-7977-45bb-b0f2-1bb3e5a64bcf
drwxr-x--- 5 root root 4096 Oct 21 18:20 58c1bb4a-7d58-4f12-9fa6-5780a50492eb

ls -ltr /var/lib/kubelet/pods
total 24
drwxr-x--- 4 root root 4096 Oct 21 18:20 a20c6b3f-2950-4ab9-89bb-6cf08e22c1f6
drwxr-x--- 4 root root 4096 Oct 21 18:20 0456318c-2e28-47f4-95e2-ccdc7b712b8b
drwxr-x--- 4 root root 4096 Oct 21 18:20 7e056156-0b88-442d-a841-1df67def1ae6
drwxr-x--- 4 root root 4096 Oct 21 18:20 58c1bb4a-7d58-4f12-9fa6-5780a50492eb
drwxr-x--- 4 root root 4096 Oct 21 18:20 75ab116e-7977-45bb-b0f2-1bb3e5a64bcf
drwxr-x--- 5 root root 4096 Oct 21 18:21 ccd0be75-173e-4df4-aa1e-57979ca63a93

ls -ltr /var/lib/rancher/k3s/agent/kubelet/pods/946d4695-d059-470c-a074-4089bece0944/containers/helm/
total 0
ls -ltr /var/lib/kubelet/pods/946d4695-d059-470c-a074-4089bece0944
ls: cannot access '/var/lib/kubelet/pods/946d4695-d059-470c-a074-4089bece0944': No such file or directory
```

**Comment by davidnuzik** [comment]
@ShylajaDevadiga do you have any concerns about the behavior. Is expected. If there are any remaining concerns let's please bring up in our slack channel.

From v0.10.0 release notes:

> The kubelet directory has changed to /var/lib/kubelet/, if using CSI plugins your configuration should be updated to reflect the new kubelet path (CSI plugins are not used in default installs).

> You may continue to see old artifacts in /var/lib/rancher/k3s/agent/kubelet/pods/ if upgrading, those files may be safely removed after a node reboot.

**Comment by ShylajaDevadiga** [comment]
Closing issue. This is expected behavior after upgrade. All references to pod would be its default directory.
