### ISSUE TITLE
Features - HA Storage Backends 

### ISSUE THREAD

**Issue by Guigouu** [rancher/k3s#940]
**Is your feature request related to a problem? Please describe.**

For now HA k3s does not provide HA backend, and it is a critical part if the external storage crash.

It will be nice to have HA storage backend support.

**Describe the solution you'd like**

In a case of PostgreSQL HA (master, slave, replicas) backend,  provide input list for '--storage-backend', which will correspond to master and slave postgresql replicas. If one storage backend it is not reachable the second one will be the new backend.

**ex:** 
--storage-endpoint host1, host2
or
--storage-endpoint-master host1 --storage-endpoint-slave host2

According to this features, it will be also nice also to have read-only and write-only dedicated storage.
**ex:**
--storage-endpoint-write host1 --storage-endpoint-read host2

**Comment by cjellick** [comment]
We assume that the storage backend infrastructure has a means for being HA. We don't want to take this on client-side
