### ISSUE TITLE
Add more doc about metrics-server

### ISSUE THREAD

**Issue by tux-00** [rancher/k3s#944]
Based on this issue https://github.com/kubernetes-incubator/metrics-server/issues/292 it seems that Rancher documentation about metrics-server on K3S is missing a step (see https://github.com/kubernetes-incubator/metrics-server/issues/292#issuecomment-516382818 in the issue).

I was unable to run `kubectl top pods` if `--kube-apiserver-arg="requestheader-allowed-names=system:auth-proxy,kubernetes-proxy"` is not set when starting K3S.

PS: My K3S cluster was upgrade a couple of times and I'm now running v0.10.0.

**Comment by erikwilson** [comment]
Those are pretty old issues, there should not be a need to pass extra args to k3s or modify the default metrics-server deployment from https://github.com/kubernetes-incubator/metrics-server/tree/master/deploy/1.8%2B.

**Comment by tux-00** [comment]
I fully reinstalled the cluster and the problem is not present anymore. But maybe is there a problem with the upgrade process ?

**Comment by erikwilson** [comment]
Probably, there was a certs refactor in v0.7.0 that may not have upgraded a particular cert correctly. Apologies for that! Would you happen to know the original version of k3s that was installed?

**Comment by tux-00** [comment]
Hum I don't remember exactly but it's around v0.7.0 :/

**Comment by sandys** [comment]
let me also add that it would be nice to add documentation/examples around HorizontalPodAutoscaler along with metrics-server (since the former depends on the latter).

**Comment by davidnuzik** [comment]
We will be having metrics-server by default in an upcoming release. Reference: https://github.com/rancher/k3s/issues/990
