### ISSUE TITLE
In a HA environment, deleted node re-joins cluster in Ready State while using mysql as a backend.

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/k3s#948]
**Version:**
v0.10.0

**Describe the bug**
In a HA env, using mysql as backend, the node that is deleted using kubectl command gets re-joined to the cluster. This is not seen using postgres as backend.

**To Reproduce**
Create a 3 node HA cluster.

Node 1:
`curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v0.10.0 sh -s - server --storage-endpoint='mysql://user:password@tcp(hostname:3306)/dbname' —bootstrap-save`

Node 2 and Node 3:
`curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v0.10.0 sh -s - server --storage-endpoint='mysql://user:password@tcp(hostname:3306)/dbname'`

`kubectl get node`

`kubectl delete node <nodename>`

Wait for a minute

`kubectl get node`

**Expected behavior**
After deletion of the node, it should not have been joined(listed).

**Actual behavior**
After deletion of the node, node is joined (listed).

**Additional context**
Node is joined back even if it is terminated and then deleted using kubectl.

Workaround for the mysql issue is to run uninstall (k3s-uninstall) on the node and then delete the node from the cluster.

**Comment by davidnuzik** [comment]
@ShylajaDevadiga does this ONLY happen on mysql? This will not occur on PostgreSQL or embedded sqlite?

**Comment by ShylajaDevadiga** [comment]
@davidnuzik does not happen using postgres as backend or default sqlite.

**Comment by davidnuzik** [comment]
@ShylajaDevadiga at your next availability can you test again on latest master?

**Comment by ShylajaDevadiga** [comment]
@davidnuzik Could you include the PR for this fix to this issue?

**Comment by davidnuzik** [comment]
@erikwilson ^

**Comment by dramich** [comment]
I am seeing this same issue with clusters running master with the latest kine update and Mariadb (mysql). Delete the clusters from the rancher UI, validate they are gone using kubectl then wait approx. 5 min and they come back.

**Comment by ShylajaDevadiga** [comment]
Resolved as of v0.11.0-alpha3. Closing issue.
