### ISSUE TITLE
Renew expired certificate

### ISSUE THREAD

**Issue by mateeyowt** [rancher/k3s#949]
**Version:**
v0.8.1

**Describe the bug**
Was installing k3s on a disconnected environment with no internet access at all. We got it to work, but incidentally we moved the server on a location with internet access. Upon startup the k3s won't start and says: x509: certificate has expired or is not yet valid.
Upon checking the certificate expiry date using this command: `cat /var/lib/rancher/k3s/server/tls server-ca.crt | openssl x509 -noout -enddate` we found out that the expiry date is Dec 2009. Is there a command to renew the certificate? It seems setting the date of the server does not help at all

**Comment by davidnuzik** [comment]
You could perhaps try upgrading to v0.10.1 we recently introduced cert rotation this may fix your issue.
While I'm not clear the true nature of the issue this should at least resolve your problem I think.

**Comment by rpocase** [comment]
I started hitting this issue for v0.10.0 today. Upgrading to v0.10.1 fixed my issue. I likely could've jumped to v1.0.0 but been holding off on jumping for the official release.

**Comment by ieugen** [comment]
I believe this has been answered here https://github.com/rancher/k3s/issues/1621  and the issue can be closed.

**Comment by davidnuzik** [comment]
Closing the issue. If there are further questions let us know and we can reopen if necessary.
