### ISSUE TITLE
--disable-agent flag poblem

### ISSUE THREAD

**Issue by Salvocll** [rancher/k3s#978]
Hi,

Some time ago I installed version 0.8.0 and with the single installation command without other flags in the same host, both the master node and an agent node were executed and if the agent was not wanted in the same host I had used the appropriate flag --disable-agent.

Installing k3s (v0.9.1) again without flag only the master appears and if I use the flag to disable the agent (which does not start) the master node is not visible, as if it did not exist but k3s is correctly running..

I tried to install earlier versions too, thinking that maybe it was a version problem but nothing even for example with version 0.8.0 I get the same result.

**Comment by ShylajaDevadiga** [comment]
@Salvocll This is expected behavior when --disable-agent flag is passed. Its documented in this issue. https://github.com/rancher/k3s/issues/891

**Comment by davidnuzik** [comment]
Let us know if there are any other questions/concerns. `--disable-agent` is no longer advertised in the cli and docs and we do not recommend it as the kubelet won't be running and thus the node won't be listed via kubectl, etc.

You can run k3s without --disable-agent and if you don't want anything to schedule on the master nodes you can taint them with something like this: `--node-taint key=value:NoExecute`
