### ISSUE TITLE
Can't enable debug when using install script

### ISSUE THREAD

**Issue by dramich** [rancher/k3s#997]
When using the install script passing --debug before server breaks as the script prepends server anyways. 

Perhaps an envvar would be useful to set debug?

**Comment by CamelCaseNotation** [comment]
I didn't know there was even a `--debug` flag

**Comment by davidnuzik** [comment]
Needs testing with `K3S_DEBUG=true`

**Comment by davidnuzik** [comment]
Docs issue: https://github.com/rancher/k3s/issues/1310

**Comment by davidnuzik** [comment]
v1.17.2+k3s1

I can confirm the `K3S_DEBUG=true` env var is working now.
